### ISSUE TITLE
https://github.com/xuxueli/xxl-job/issues/992

### ISSUE THREAD

**Issue by lianghongming** [xuxueli/xxl-job#1002]
https://github.com/xuxueli/xxl-job/issues/992

解压的包如下：
已提取: BOOT-INF/lib/xxl-job-core-2.1.0.jar
已提取: BOOT-INF/lib/xxl-rpc-core-1.4.1.jar
已提取: BOOT-INF/lib/xxl-registry-client-1.0.2.jar

**Comment by xuxueli** [comment]
你好，需要提供下稳定复现的操作步骤来复现问题跟进。

**Comment by lianghongming** [comment]
定位出来了，都在同台机器部署会产生，配置到不同的机器不会产生，同一台机器的是127.0.0.1的配置项

**Comment by xuxueli** [comment]
单个执行器示例本身会消耗一部分IO线程和文件句柄，但是单实例是有上限控制的。单机多实例才出现这种情况，应该是单机到达资源上限了。
