### ISSUE TITLE
Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by SteloChen** [xuxueli/xxl-job#1004]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

2.1.0

### Expected behavior

报这个错Lock wait timeout exceeded; try restarting transaction，应该不影响任务的执行

### Actual behavior

报这个错Lock wait timeout exceeded; try restarting transaction，所有任务都不执行了

### Other information

**Comment by SteloChen** [comment]
我发现发邮件异常的话容易出现死锁

**Comment by xuxueli** [comment]
你好，问题无法复现。能提供稳定复现步骤吗？

**Comment by SteloChen** [comment]
在任务的报警邮件一栏配置一个邮箱，如果发邮件的smtp服务不可达，应该可以复现

**Comment by xuxueli** [comment]
你好，按照上述操作步骤并未复现问题。

请进一步提供稳定复现操作步骤。
