### ISSUE TITLE
执行器与调度器之间的通信，能不能支持https协议

### ISSUE THREAD

**Issue by immortalHuang** [xuxueli/xxl-job#1005]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0

### Expected behavior
执行器与调度器之间的通信，支持https协议
### Actual behavior
执行器与调度器之间的通信，不支持https协议
### Other information

**Comment by xuxueli** [comment]
你好，底层通讯以及xxl-rpc，已经提供了Token加密，理论上不需要https。如有需要可自行定制。
