### ISSUE TITLE
当cron是一次性且过期的时候，获取下次执行时间包

### ISSUE THREAD

**Issue by nobsu** [xuxueli/xxl-job#1008]
Please answer some questions before submitting your issue. Thanks!
当cron是一次性任务且过期的时候，start报空指针。
且JobScheduleHelper中也报空指针。
因为获取下次执行时间为null
### Which version of XXL-JOB do you using?
v2.1.1
### Other information
![image](https://user-images.githubusercontent.com/3723537/61180951-81196e00-a651-11e9-86bc-661c81fbef07.png)

**Comment by xuxueli** [comment]
感谢反馈！
问题已经修复并推送master分支，可以pull master体验。将会跟随下个版本一同发布。
