### ISSUE TITLE
大神，你好为什么我的demo会出现这种情况呢？

### ISSUE THREAD

**Issue by 31315474** [xuxueli/xxl-job#101]
![image](https://user-images.githubusercontent.com/20572565/27900351-9cdf5fd2-6260-11e7-906e-d5a07c90ec5c.png)

**Comment by 31315474** [comment]
![image](https://user-images.githubusercontent.com/20572565/27900394-c74134da-6260-11e7-8f0c-c150f0331647.png)
日志没有输出，而且debug模式也不跳转到DemoJobHandler.java类断点，求解惑

**Comment by untrueman** [comment]
有可能是任務阻塞導致的。

**Comment by Lixianshengchao** [comment]
我也出现了这个问题

**Comment by Lixianshengchao** [comment]
解决了：缺少依赖
<dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.4</version>
</dependency>

**Comment by chenxofhit** [comment]
@Lixianshengchao 在哪个子项目里添加依赖?

**Comment by xuxueli** [comment]
@31315474 你好，感谢反馈！
这个问题可能由以下几个原因导致：
1、执行器任务阻塞：后续任务需要等待前面的任务执行器结束才开始执行。
2、执行器执行结果回调失败：检查执行器回调Log是否抛异常，执行器回调地址是否正确。
