### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nyjianjun** [xuxueli/xxl-job#1011]
2.1.0升级后任务管理新增后。无法查询出来
![image](https://user-images.githubusercontent.com/41484097/61264472-564d2800-a7bf-11e9-9346-f2b4f8895511.png)
![image](https://user-images.githubusercontent.com/41484097/61264493-6533da80-a7bf-11e9-9e2d-c7fe4b91ef12.png)

**Comment by xuxueli** [comment]
你好，高版本UI交互有调整，应该是你浏览器缓存了旧版本的UI资源。强刷以下浏览器JS缓存即可。
