### ISSUE TITLE
请教下官网文档是用什么写的？Gitbook吗？ 

### ISSUE THREAD

**Issue by liutf** [xuxueli/xxl-job#1012]
* 问题

请教下xxl-job的官网文档这个是咋搞的？是用的Gitbook？第一页上GetStarted那几个按钮是咋搞的，用的主题吗（啥主题）？

官网地址： [http://www.xuxueli.com/xxl-job/#/?id=xxl-job](http://www.xuxueli.com/xxl-job/#/?id=xxl-job)
 

![](http://qn-imgs.liutf.com/img/20190716155533.png)

![](http://qn-imgs.liutf.com/img/20190716155724.png)

**Comment by xuxueli** [comment]
VUE 的一个库，邮件源代码可以查看。
