### ISSUE TITLE
xxl-job-admin.log.2019-07-12467759331242548.tmp  这个文件是做什么的，目前已太41G。如何让他不快速增长

### ISSUE THREAD

**Issue by gang0713** [xuxueli/xxl-job#1016]
xxl-job-admin.log.2019-07-12467759331242548.tmp  这个文件是做什么的，目前已达到41G。如何让他不快速增长  ，我的版本为2.0.2

**Comment by xuxueli** [comment]
这是 “logback.xml” 配置的常规日志文件，logback生成。
可能是频繁的系统报错导致，可以排查日志，修复对应问题即可。
