### ISSUE TITLE
关于增加任务执行进度记录的讨论

### ISSUE THREAD

**Issue by san21go** [xuxueli/xxl-job#102]
大神们，不知这个任务调度如何能够支持对任务执行完成度的日志进来，任务的最新的执行进度需要记录在数据库中，最好能够直接将完成进度日志直接发回给任务调度器。
我目前能够想到的一种方案是，在任务执行器中增加一个完成进度的日志文件，然后任务调度器远程调用获取最新的日志，

**Comment by xuxueli** [comment]
你好，执行器任务进度，没有使用字段单独记录。
目前的做法是通过 “Rolling 日志” 实时查看的啊，可以将进度打印在Log文件中，调度中心实时查看。
