### ISSUE TITLE
执行器-地址列表

### ISSUE THREAD

**Issue by 1175341729** [xuxueli/xxl-job#1022]
客户端注册成功 但是有时候存在执行器-地址列表为null的情况，目前出现过2次 客户端服务器也没有重启

**Comment by xuxueli** [comment]
执行器地址为空，说明执行器心跳失败被自动摘除了，可以排查下回调Log，是不是存在回调失败的日志。

**Comment by CytFree** [comment]
是的  我这也出现这种情况，心跳和调度同一时刻，然后说地址为空，但是看执行器的心跳日志，显示注册成功了。怀疑是当前admin清理的地址的心跳同一时刻也在执行。怎么破

**Comment by powerLeePlus** [comment]
我也遇到这个问题了。怎么解

**Comment by huangsanyeah** [comment]
I also got this problem,I have only one instance,and it run fails.how to solve it?

**Comment by kuailehehe** [comment]
解决了？出现好多次了，客户端可以正常执行，项目都没有问题，重启后就可以注册成功了
