### ISSUE TITLE
Docker 部署调度中心  访问404

### ISSUE THREAD

**Issue by pencilso** [xuxueli/xxl-job#1024]
以下是docker 日志  可以看到已经启动，并且端口是8082 ，但是访问的时候是404
版本为最新的2.0.1
<img width="915" alt="QQ20190722-132226@2x" src="https://user-images.githubusercontent.com/16483654/61608046-dd007a00-ac83-11e9-8588-1134d0b46e0f.png">

**Comment by xuxueli** [comment]
默认访问路径需要加应用名。
建议升级最新版本 2.1.0

**Comment by pencilso** [comment]
加什么名？  文档上没看到啊，还有，这是最新版的2.1.0    之前打错了。

**Comment by pencilso** [comment]
加上xxl-job-admin 应用名后，能访问到了...
但我觉得不应该这么做，这个docker  镜像做的很low 逼

**Comment by SUKF** [comment]
可以通过环境变量PARAMS后追加 --server.context-path=/ 重置应用的上下文路径

例如：
```docker
docker run -p 8080:8080 -e PARAMS=--server.context-path=/  xuxueli/xxl-job-admin:2.1.0
```
