### ISSUE TITLE
英文文档翻译志愿者征召

### ISSUE THREAD

**Issue by xuxueli** [xuxueli/xxl-job#1028]
目前，中文项目文档已经实时更新到最新版本。但是，英文项目文档仍然停留在低版本，滞后于中文文档。因此，在此征集文档翻译志愿者，通过PR的方式进行英文文档翻译贡献，将会永远记录为项目contributer。

有意向的朋友在在该ISSUE下方留言认领章节，比如：认领章节 ”二、快速入门“。然后通过PR推送英文文档即可。

- 中文文档：https://github.com/xuxueli/xxl-job/blob/master/doc/XXL-JOB%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3.md
- 英文文档：https://github.com/xuxueli/xxl-job/blob/master/doc/XXL-JOB-English-Documentation.md

**Comment by zwchen111** [comment]
还可以认领吗？我有兴趣参与

**Comment by xuxueli** [comment]
@zwchen111 当然可以，可以直接提交PR；
