### ISSUE TITLE
readme文档描述英文拼写错误

### ISSUE THREAD

**Issue by it-noob** [xuxueli/xxl-job#103]
在**发展**的第二行中，描述：“于2015-11月，XXL-JOB终于REALEASE了第一个大版本V1.0”中的REALEASE拼写错误，应该是RELEASE。

**Comment by xuxueli** [comment]
你好，确实存在这个问题，文档文案已经更新。
感谢关注啊 ：）

**Comment by it-noob** [comment]
雪老大，今天看文档的时候，又发现一处错别字。

**Comment by it-noob** [comment]
5.4.7 日志回调服务

调度模块的“调度中心”作为Web服务部署时，一方面承担调度中心功能，另一方面页为执行器提供API服务。
其中"另一方面"后面的也为，也字出错了。

**Comment by xuxueli** [comment]
你好，确实是个别字，已经更新稳定并推送。
谢谢啊：）
