### ISSUE TITLE
数据库字段能否去掉blob类型

### ISSUE THREAD

**Issue by yaakua** [xuxueli/xxl-job#1030]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
V2.1.0

### Expected behavior
数据库表结构里面涉及到JOB_DATA的字段，现在用的Blob类型。由于客户的安全规范要求，不允许使用BLOB字段类型，是否可以更改为其他类型？

**Comment by xuxueli** [comment]
你好，你用的应该低版本，底层耦合quartz库表导致存在Blob类型属性。
最新版本 v2.1.0 已经移除了quartz依赖，不存在上述问题。
