### ISSUE TITLE
是否可以独立一个 xxl-job-core-api.jar 授权为Apache 授权或LGPL，现在这个GPL授权不太友好

### ISSUE THREAD

**Issue by charlesvhe** [xuxueli/xxl-job#1032]
#707 

最近公司同样提出了这个风险，希望能换成比较友好的开源协议。xxl-job很好用，不希望因为开源协议原因逼迫我们替换这个好用的组件。

**Comment by xuxueli** [comment]
已统一处理。

合并至：https://github.com/xuxueli/xxl-job/issues/1033
