### ISSUE TITLE
执行器“xxl-job-core”官方依赖协议补充

### ISSUE THREAD

**Issue by xuxueli** [xuxueli/xxl-job#1033]
***执行器“xxl-job-core”官方依赖协议补充：***
- 针对执行器官方依赖 “xxl-job-core” ，如果仅将其作为项目依赖引入而不进行修改，相关项目不需要考虑协议传染问题。

**Comment by wchaowu** [comment]
![image](https://user-images.githubusercontent.com/131735/69141566-04ffcd00-0b00-11ea-8d07-10306e99bfe5.png)

**Comment by wchaowu** [comment]
![image](https://user-images.githubusercontent.com/131735/69141661-35476b80-0b00-11ea-90b5-c15787304ce0.png)

**Comment by wchaowu** [comment]
![image](https://user-images.githubusercontent.com/131735/69141773-6a53be00-0b00-11ea-8c4f-fbb52c122243.png)

**Comment by changfubai** [comment]
您好，使用调度中心的镜像，也没问题么？我们的产品有私有化部署的需求。

**Comment by smartbetter** [comment]
您好，有两个问题需要您解答一下：
1、在 xxl-job-core 的基础上，二次开发一个client jar包（client 引用 core 的 jar 包），二次开发的 client jar 包需要开源吗？
2、xx-job-admin 如果我们接入内部的sso登录和权限管理系统（修改了 xx-job-admin 的代码），需要开源吗？

**Comment by coolbeevip** [comment]
最好是将客户端需要的部分从 xxl-job-core 中剥离出 xxl-job-client，然后对 xxl-job-client 单独声明 LGPL

**Comment by wealthtears** [comment]
你好， 我们商用项目使用了xxl-job，但是漏洞扫描软件扫出GPL协议风险，客户这边坚决不让使用GPL协议，目前只能换掉xxl-job。可否考虑授权apache协议或者lgpl协议呢？
