### ISSUE TITLE
ReturnT 可能存在的问题

### ISSUE THREAD

**Issue by hongpxiaozhu** [xuxueli/xxl-job#1034]
尝试学习XXL-JOB框架发现
XxlJobTrigger 将一些信息赋值到ReturnT类型的runResult的msg变量中，然而有调用方返回的是ReturnT.SUCCESS这个静态变量，导致无限多的字符串会设置进去且无法清除，希望能复查后给与答复是否会有相关问题。

![image](https://user-images.githubusercontent.com/17108092/61792646-cf97eb00-ae4f-11e9-9faa-60dd762bfed6.png)

![image](https://user-images.githubusercontent.com/17108092/61792720-f1916d80-ae4f-11e9-947c-57f20a6eb6f5.png)

![image](https://user-images.githubusercontent.com/17108092/61792765-0cfc7880-ae50-11e9-9e20-82f4a042b36c.png)

![image](https://user-images.githubusercontent.com/17108092/61792823-32898200-ae50-11e9-85a9-8737c99439bf.png)

SUCCESS虽然是个final类但是其引用不变，内容可以无限增加

**Comment by xuxueli** [comment]
感谢反馈，正在尝试修复！
