### ISSUE TITLE
2.0.2升级到2.1.0，数据库迁移

### ISSUE THREAD

**Issue by liwengangLY** [xuxueli/xxl-job#1035]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by liwengangLY** [comment]
您好，2.0.2升级到2.1.0后，数据库表减到了7张，请问下那我之前的配置有脚本可以直接迁移过来吗，还是只能重新配置了？

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/988
