### ISSUE TITLE
依赖的netty报错找不到方法,无法拉起调用

### ISSUE THREAD

**Issue by babyshy** [xuxueli/xxl-job#1036]
后台netty报错,需要手动引入netty-socketio依赖

**Comment by xuxueli** [comment]
你好，应该是版本冲突，确保netty版本与执行器底层依赖一致；

**Comment by babyshy** [comment]
项目加入euraka服务,spring-cloud-starter-netflix-eureka-client的netty有版本冲突,手动调整下引入顺序解决了
