### ISSUE TITLE
Job Handler [xxxx] not found.

### ISSUE THREAD

**Issue by fangchao3652** [xuxueli/xxl-job#1039]
Please answer some questions before submitting your issue. Thanks!
Which version of XXL-JOB do you using?
2.0.1

Expected behavior
任务应该正常被执行

Actual behavior
Job Handler [xxxx] not found.

Steps to reproduce the behavior
Other information
### Other information
![image](https://user-images.githubusercontent.com/10208927/61946089-3a722f00-afd4-11e9-9985-bb56fd409ac6.png)

还有个问题是，我有两个执行器，其中xxl.job.executor.port设置的都是20173，另外我的执行器是嵌入在另一个springboot应用上的，这个springboot的端口是8080，这样可行吗

**Comment by domineerLong** [comment]
看下你的xxlJobExecutor 是不是配置的 **XxlJobSpringExecutor**

**Comment by tujiu199002** [comment]
你的这个文件 解决了吗？？

**Comment by tujiu199002** [comment]
你的这个问题 解决了吗

**Comment by xuxueli** [comment]
应该是执行器配置或者拼写问题。可以参考提供的Sample示例。

**Comment by strongant** [comment]
请检查下，这个问题一般是由于升级新版本后，由于新版本对Jobhandler的注册方式发生了变更，在JobConfig 中需要使用 com.xxl.job.core.executor.impl.XxlJobSpringExecutor ，具体改动以官方示例为主，修改以前的 XxlJobExecutor 为 XxlJobSpringExecutor ：

  @Bean
    public XxlJobSpringExecutor xxlJobExecutor() {
        logger.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppName(appName);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }
新版本的注册通过 XxlJobSpringExecutor#initJobHandlerRepository 方法如下：

private void initJobHandlerRepository(ApplicationContext applicationContext){
        if (applicationContext == null) {
            return;
        }

        // init job handler action
        Map<String, Object> serviceBeanMap = applicationContext.getBeansWithAnnotation(JobHandler.class);

        if (serviceBeanMap!=null && serviceBeanMap.size()>0) {
            for (Object serviceBean : serviceBeanMap.values()) {
                if (serviceBean instanceof IJobHandler){
                    String name = serviceBean.getClass().getAnnotation(JobHandler.class).value();
                    IJobHandler handler = (IJobHandler) serviceBean;
                    if (loadJobHandler(name) != null) {
                        throw new RuntimeException("xxl-job jobhandler["+ name +"] naming conflicts.");
                    }
                    registJobHandler(name, handler);
                }
            }
        }
    }

XxlJobSpringExecutor 实际上对之前旧的 XxlJobExecutor 做了一层包装，注入方式发生了变化，在注册JobHandler时调用了XxlJobExecutor#registJobHandler方法。

升级之后需要对原有的定时任务配置做如上改动。
