### ISSUE TITLE
一个会导致线程数一直往上涨的bug

### ISSUE THREAD

**Issue by daelly** [xuxueli/xxl-job#1040]
`// new jobhandler
            IJobHandler newJobHandler = XxlJobExecutor.loadJobHandler(triggerParam.getExecutorHandler());

            // valid old jobThread
            if (jobThread!=null && jobHandler != newJobHandler) {
                // change handler, need kill old thread
                removeOldReason = "change jobhandler or glue type, and terminate the old job thread.";

                jobThread = null;
                jobHandler = null;
            }

            // valid handler
            if (jobHandler == null) {
                jobHandler = newJobHandler;
                if (jobHandler == null) {
                    return new ReturnT<String>(ReturnT.FAIL_CODE, "job handler [" + triggerParam.getExecutorHandler() + "] not found.");
                }
            }`

这段逻辑，如果是一个spring bean配置参数不同的两个task的时候会出现一个严重的bug，会对不同的任务id的task创建新的thread，杀掉旧thread，最后导致服务器的pid用光

**Comment by houzhanshanlinzhou** [comment]
我的也是，每隔一会儿，服务器就崩溃了

**Comment by JetBrainZP** [comment]
具体是什么？能讲的更加详细一些吗？

**Comment by crazythinking** [comment]
应该是通过@JobHandler("aaa")，定义一个JobHandler，然后在Admin端用这个JobHandler配置了多个参数不同的Task吧。不建议这么使用。

**Comment by caiwen09** [comment]
@xuxueli 这个问题有解决方案吗？确实存在这样的隐患

**Comment by xuxueli** [comment]
不同任务（JobId）需要进行线程隔离，需要针对每个任务创建任务线程，这是正常的。正常情况下任务数量有限，因此线程数量可控的。
如果针对单个JobHandler配置海量任务，建议拆分不同执行器，缓解单机压力
