### ISSUE TITLE
升级为2.1.0一直报timeout异常

### ISSUE THREAD

**Issue by xiejinhong** [xuxueli/xxl-job#1042]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
升级为2.1.0一直报timeout异常，手动执行无异常
### Expected behavior
com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /172.20.5.199:9999 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) at com.sun.proxy.$Proxy102.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:76) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /172.20.5.199:9999 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ... 1 more Caused by: java.net.ConnectException: Connection timed out: no further information ... 12 more
### Other information

**Comment by kouyandong** [comment]
我也遇到同样问题

**Comment by LiWenGu** [comment]
我也是。任务执行随机出现超时。我们是在测试环境下，同一台机器，内网netty调用

**Comment by xuxueli** [comment]
可以排查下调度中心日志，应该是执行器服务未启动或者网络问题，只是表现为为timeout。

上面这个问题从日志 ”Caused by: java.net.ConnectException: Connection timed out“ 看应该是网络问题。

**Comment by duanjia85** [comment]
这个问题我检查了源码，目前配置timeout时间没有生效，导致目前说有的任务都是3秒时间，所以很容易出现调度超时

**Comment by kuguobing** [comment]
我也碰到同样的问题，调度中心和执行器都在同一台本地的公司PC机器上；晚上让其运行一晚，第二天早上过来看，就有如上的错误日志

**Comment by zhaikangqi** [comment]
我也遇到同样的问题，同一个任务，任务启动后，每次执行都是失败的，但是手动执行都是成功的。

**Comment by zhaikangqi** [comment]
我又给任务加上失败重试次数以后，首次执行失败，重试成功。

**Comment by zhaikangqi** [comment]
多个执行器，目前只发现了一个执行器存在这个问题
