### ISSUE TITLE
Optional int parameter 'triggerStatus' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type.

### ISSUE THREAD

**Issue by zhmingGIT** [xuxueli/xxl-job#1043]
Optional int parameter 'triggerStatus' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type.

**Comment by xuxueli** [comment]
强刷下浏览器缓存即可。
