### ISSUE TITLE
创建用户的时候是否可以生成Secret 用于api访问

### ISSUE THREAD

**Issue by pengzai170** [xuxueli/xxl-job#1044]
我看文档上写还需要在代码上加入注解@PermessionLimit(limit = false)
还需要修改代码，而且安全上也有风险 ，建议创建用户的时候生成Secret 用于api访问

**Comment by pengzai170** [comment]
目前的变态需求
比如 
2019-1-10 ~ 2019-2-1
时间段也是变的
10：00 执行1次
12：00 执行1次
...
..
..
20:00  执行1次
....
所以需要动态添加删除任务

**Comment by xuxueli** [comment]
你好，类似指定时间的延时任务，建议借助消息组件实现啊，推荐 XXL-MQ：https://www.xuxueli.com/xxl-mq/#/

**Comment by junneyang** [comment]
+1
