### ISSUE TITLE
怎么传递系统时间参数

### ISSUE THREAD

**Issue by sunzhiqiangGithub** [xuxueli/xxl-job#1046]
背景：需要在每天10点，15点，21点执行任务，10点执行的需要在13点结束。
所以需要在执行定时任务时候，通过开始时间来确定结束时间，但应用服务器和xxl服务器不在同一个服务器上，有可能服务器之间有时间误差。
如果执行定时任务的时候，可以传xxl服务器时间进来，应该可以解决这个问题。

疑问：xxl定时任务执行时可以传xxl服务器的系统时间进来吗？

**Comment by crazythinking** [comment]
执行器与调度中心必须做时间同步

**Comment by xuxueli** [comment]
+1，建议机器时钟同步。

**Comment by rowstop** [comment]
> 时钟同步 会不会在毫秒级别有误差？ 如果能传递调度器的时间，那我业务只要按调度器时间为准就好了。
> 
> 这边的背景是，每天凌晨0点执行job，生效当天该生效的数据。 但是应用接收到xxl调度是 23:59:59.983，还是停留在昨天。
是有偏差的 他也不把设置的执行时间传过来，只能加几秒然后向下取整
