### ISSUE TITLE
sonar提示有bug，InterruptedException需要Thread.currentThread().interrupt();    

### ISSUE THREAD

**Issue by piglingcn** [xuxueli/xxl-job#1047]
sonar提示有bug，InterruptedException需要Thread.currentThread().interrupt();    
Compliant Solution
	public void run () {    
		 try {      
			while (true) {        // do stuff      
		 }    
		 }catch (InterruptedException e) {      
			LOGGER.log(Level.WARN, "Interrupted!", e);     
		  	// Restore interrupted state...      
			Thread.currentThread().interrupt();    
		 }  
	}

**Comment by xuxueli** [comment]
特性要求如此，可以标记忽略。
