### ISSUE TITLE
Job Handler [xxxx] not found

### ISSUE THREAD

**Issue by tujiu199002** [xuxueli/xxl-job#1050]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by tujiu199002** [comment]
管理平台和自己的应用都可以 正常启动 
管理平台 一直报 code：500
msg：job handler [demoJobHandler] not found.  不知道这是什么情况 管理平台已升级

**Comment by tujiu199002** [comment]
![微信图片_20190805182147](https://user-images.githubusercontent.com/53754399/62457828-2ab1d200-b7ae-11e9-8384-0f9edb77124f.png)
![微信图片_20190805182222](https://user-images.githubusercontent.com/53754399/62457829-2ab1d200-b7ae-11e9-92d9-1e446bc769c7.png)
![Uploading 微信图片_20190805182333.png…]()

**Comment by tujiu199002** [comment]
![微信图片_20190805182333](https://user-images.githubusercontent.com/53754399/62457869-4026fc00-b7ae-11e9-9921-9b46274452fe.png)

**Comment by tujiu199002** [comment]
![微信图片_20190805182222](https://user-images.githubusercontent.com/53754399/62457900-4f0dae80-b7ae-11e9-9c37-424fa1b6e3d2.png)

**Comment by tujiu199002** [comment]
![微信图片_20190805182147](https://user-images.githubusercontent.com/53754399/62457917-55038f80-b7ae-11e9-8ead-e03d37cab994.png)

**Comment by tujiu199002** [comment]
管理平台 和我自己的应用都可以正常 启动 而且 注册也是成功的 就是 管理平台执行 任务的时候 执行不成功
![微信图片_20190805182333](https://user-images.githubusercontent.com/53754399/62458013-82e8d400-b7ae-11e9-9b60-f6134289fbb7.png)

**Comment by scm1219** [comment]
原来写的是 executor = new XxlJobExecutor();，
需要改成 executor = new XxlJobSpringExecutor();
见 2.1.0的说明

**Comment by xuxueli** [comment]
@scm1219  正解

**Comment by tujiu199002** [comment]
好的，谢谢 就是这个问题 以及解决了

**Comment by 1yus2yus3** [comment]
@scm1219 解决了
