### ISSUE TITLE
日志磁盘元数据区域爆满

### ISSUE THREAD

**Issue by DongWeiMa** [xuxueli/xxl-job#1051]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
日志文件一天一个
### Actual behavior
日志文件实际一天几十万个
### Other information
日志框架使用logback

**Comment by DongWeiMa** [comment]
![image](https://user-images.githubusercontent.com/12246952/62507361-b111f680-b836-11e9-94e2-80db2ee7a0c6.png)

**Comment by DongWeiMa** [comment]
![image](https://user-images.githubusercontent.com/12246952/62507372-bc652200-b836-11e9-8234-f54bfdc95e70.png)

**Comment by xuxueli** [comment]
你好，执行器日志支持设置日志自动清理的。为了隔离不同任务之间的日志，需要拆分小文件。

**Comment by 1034323716** [comment]
> 你好，执行器日志支持设置日志自动清理的。为了隔离不同任务之间的日志，需要拆分小文件。

但是logRetentionDays还有最小限制，必须大于等于3吧
