### ISSUE TITLE
【问题请教】如何实现调度数据库的高可用

### ISSUE THREAD

**Issue by chen-ABC** [xuxueli/xxl-job#1054]
当前admin部署在2台机器上，但是数据库连接的都是同一个，那么该数据库崩溃该如何处理。想请教一下大家如何实现数据库的高可用。

**Comment by xuxueli** [comment]
数据库故障时，可以借助配置中心动态切换数据库。比如借助 XXL-CONF 推送新的数据库配置，兼容到配置变更后重新初始化数据库连接池即可。
