### ISSUE TITLE
使用k8s的Galera做为数据库中间件，它是一个mysql的同步多主集群，是否可以使用xxl-job做为分布式任务调度

### ISSUE THREAD

**Issue by arthur-dy-lee** [xuxueli/xxl-job#1056]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
最新版，想上xxl-job。

### Expected behavior
我们使用k8s的Galera做为数据库中间件，它是一个Mysql的同步多主集群，是否可以使用xxl-job? 我看使用说明文档中注明，要单主数据库。

### Actual behavior
目前我们使用的是k8s作容器，想要调研一款轻量级分布式任务调试框架。

### Other information

**Comment by arthur-dy-lee** [comment]
Galera是一个mysql的同步多主集群软件，目前只支持INnoDB存储引擎
功能：
同步复制
Multi-master，及所有节点都可以同时进行读写操作
自动的成员节点控制，失效节点自动被剔除
新节点加入数据自动复制
真正的并行复制，行级
优点：
因为是多主，不存在slave lag(延迟)
不存在丢失交易的情况
同时具有读写的能力
更小的客户端延迟
节点间的数据是同步的（使用rsync进行同步）

**Comment by xuxueli** [comment]
你好，按道理应该是支持的，强制调度中心全部DB操作强制走主库即可。
建议使用master分支，或者等待即将发布的 v2.1.1 分支，对主从切换更友好。
