### ISSUE TITLE
settings在哪？

### ISSUE THREAD

**Issue by wangbaobisheng** [xuxueli/xxl-job#106]

**Comment by xuxueli** [comment]
你好，settings是指什么啊？

**Comment by wangbaobisheng** [comment]
就是maven打包依赖的settings.xml，我们的项目默认settings文件在哪啊？

**Comment by xuxueli** [comment]
你好，release版本的相关依赖已经推送中央仓库，使用mavena安装目录下默认setting文件即可啊。
