### ISSUE TITLE
任务执行时报错找不到io.netty.handler.codec.http.HttpHeaderNames

### ISSUE THREAD

**Issue by jiangbin-github** [xuxueli/xxl-job#1061]
2019/8/11 上午11:58:49Exception in thread "xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-527217989" java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.codec.http.HttpHeaderNames
2019/8/11 上午11:58:49	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
2019/8/11 上午11:58:49	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
2019/8/11 上午11:58:49	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
2019/8/11 上午11:58:49	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
2019/8/11 上午11:58:49	at com.sun.proxy.$Proxy120.run(Unknown Source)
2019/8/11 上午11:58:49	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196)
2019/8/11 上午11:58:49	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149)
2019/8/11 上午11:58:49	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
2019/8/11 上午11:58:49	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:76)
2019/8/11 上午11:58:49	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019/8/11 上午11:58:49	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019/8/11 上午11:58:49	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，应该是NETTY版本冲突，调整为执行器内部相关依赖一致即可。
