### ISSUE TITLE
如何压测？

### ISSUE THREAD

**Issue by leecode** [xuxueli/xxl-job#1062]
### Which version of XXL-JOB do you using?
2.1.0
### Other information
请问调度中心应该怎么进行压测？是通过创建大量任务来做么？通过手动触发调度的接口进行压测是否靠谱？

**Comment by xuxueli** [comment]
你好，可以通过任务触发接口进行压测，任务 ”执行“ 按钮对应的后端接口。

**Comment by leecode** [comment]
请问官网上提到的单机5000任务并发是如何测出来的呢？我个人在压测的时候经常会碰到这种异常：
ERROR [http-nio-8063-exec-269] c.x.j.a.c.r.WebExceptionResolver [WebExceptionResolver.java : 32] WebExceptionResolver:{}
java.util.concurrent.RejectedExecutionException: Task com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3@78c5ba68 rejected from java.util.concurrent.ThreadPoolExecutor@4dd356aa[Running, pool size = 100, active threads = 100, queued tasks = 2000, completed tasks = 4324]

看样子是积压任务过多导致调度被丢弃。
