### ISSUE TITLE
[开发计划] 关于固定间隔的开发计划

### ISSUE THREAD

**Issue by xkcoding** [xuxueli/xxl-job#1063]
### 当前xxl-job版本号

2.1.0

### 期望

期望xxl-job支持固定间隔的任务调度，目前cron无法实现类似 间隔 70分钟这种任务的调度

### 问题

我看TODO-LIST里存在这种固定间隔周期的开发计划，想咨询下，大概何时会完成这个功能

- 如果短期可以实现，麻烦给个发布时间
- 如果短期实现不了，期望可以提供一个解决方案

十分感谢！

**Comment by xuxueli** [comment]
你好，预计在v2.2.x 版本实现，当前大版本新功能特性基本排满了。
目前可以借助XXL-MQ：https://www.xuxueli.com/xxl-mq/#/ 实现，可以在指定延时时间延时消费。
