### ISSUE TITLE
@JobHandler  中的 value 值能否可配 ？

### ISSUE THREAD

**Issue by imsuperman0920** [xuxueli/xxl-job#1065]
SpringBoot 中的 JobHandler value 能否实现可配？

**Comment by xuxueli** [comment]
你好，在调度中心界面上可以动态配置的。

**Comment by imsuperman0920** [comment]
您好，感谢回复，我的意思是在执行器端可配置，现在好像只能在注解里硬编码~

**Comment by imsuperman0920** [comment]
> 你好，在调度中心界面上可以动态配置的。
您好，感谢回复，我的意思是在执行器端可配置，现在好像只能在注解里硬编码~
