### ISSUE TITLE
对于只执行一次的CRON表达式，获取下次触发时间时，会引发NPE

### ISSUE THREAD

**Issue by zhouzuixin** [xuxueli/xxl-job#1067]
jobInfo.setTriggerNextTime(
    new CronExpression(jobInfo.getJobCron())
        .getNextValidTimeAfter(new Date())
            **.getTime()**
)

**Comment by xuxueli** [comment]
你好，这个问题已经修复并推送master分支，临时可以搜索关键字 ”getNextValidTimeAfter“ 作调整即可。或者等待下个版本升级即可。

**Comment by wangdh1** [comment]
经过测试，master分支 仍旧 NPE。
![image](https://user-images.githubusercontent.com/16779197/101597664-fdc09f80-3a31-11eb-82e7-f04e5949ef27.png)

**Comment by zhouzuixin** [comment]
我后面是自己修改了，没有使用他的master分支

wangdh1 <notifications@github.com> 于2020年12月9日周三 下午3:20写道：
