### ISSUE TITLE
2.1.0怎么动态创建任务？

### ISSUE THREAD

**Issue by Hurento** [xuxueli/xxl-job#1069]
@xuxueli 
1. 业务系统中怎么通过XxlJobService创建或移除等任务
2. 怎么获取admin中的XxlJobService

**Comment by xuxueli** [comment]
你好，提供相关API接口来操作任务，文档有说明：http://www.xuxueli.com/xxl-job/#/?id=_5112-%e6%8f%90%e4%be%9b%e7%bb%99%e4%b8%9a%e5%8a%a1%e7%9a%84api%e6%9c%8d%e5%8a%a1%ef%bc%9a
