### ISSUE TITLE
admin（F5） 执行器列表 OnLine 机器列表会重复

### ISSUE THREAD

**Issue by bobpan** [xuxueli/xxl-job#107]
问题描述：
管理器两台，设置了F5，通过一个域名访问，executor分别尝试配置为域名和机器名，发现OnLine 机器列表会重复添加，如下图

![executor](https://user-images.githubusercontent.com/5138465/28048811-e52f8780-6625-11e7-8f82-d1eda1e07fb4.png)

**Comment by xuxueli** [comment]
你好，类似问题在1.8.0的快照版本 （https://github.com/xuxueli/xxl-job/blob/master/xxl-job-admin/src/main/java/com/xxl/job/admin/core/thread/JobRegistryMonitorHelper.java#L49 ，可以参考此处代码修复该问题） 已经做了处理，对系统正常运营没有影响。
问题原因是：同一执行器机器，重复心跳注册时生成了多条记录。
但是，心跳注册通常是更新同一条已存在的记录，根据update行数判断是否存在旧注册记录，不存在才会新增，这个问题比较罕见。

**Comment by bobpan** [comment]
刚看到了另外一个Issue，呵呵，谢谢 @xuxueli
