### ISSUE TITLE
调度成功，控制台也没报错，但执行结果失败

### ISSUE THREAD

**Issue by NYfor2017** [xuxueli/xxl-job#1073]
调度成功，而且控制台也没有报错，admin和executor的版本一样，但是执行结果就是返回失败，请问有什么解决的办法吗？          
2019-08-16 12:04:41 [com.xxl.job.core.thread.JobThread#run]-[124]-[Thread-35] 
----------- xxl-job job execute start -----------
----------- Param:
2019-08-16 12:04:41 [com.xxl.job.core.thread.JobThread#run]-[164]-[Thread-35] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=500, msg=null, content=null]
2019-08-16 12:04:41 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[190]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

[Load Log Finish]

public ReturnT<String> execute(String s) throws Exception {
//        log.info("调用backlogAmountByApplyHandlerDay定时任务");
        ResponseData<?> ret = XXXService.insertXXX();
        System.out.println(ret.getSuccess());
        if(ret.getSuccess()){
            return IJobHandler.SUCCESS;
        }else{
            return IJobHandler.FAIL;
        }
    }

**Comment by xuxueli** [comment]
你好，从日志 “ReturnT [code=500, msg=null, content=null]” 来看是任务结果返回失败导致，是正常的。任务应该走到了 “return IJobHandler.FAIL;” 这里导致任务失败。

**Comment by wanghengGit** [comment]
调度成功，但执行结果失败，有时候执行结果又是成功的，麻烦解答一下，
![image](https://user-images.githubusercontent.com/13342563/99234096-107af680-282f-11eb-8dcd-a3e94e9ced15.png)
ReturnT:ReturnT [code=500, msg=Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool, content=null]
2020-11-16 16:45:13 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[191]-[xxl-job, executor TriggerCallbackThread]
