### ISSUE TITLE
请问多个定时任务并行执行成功后触发某一个定时任务怎么实现呢？

### ISSUE THREAD

**Issue by hhggbb** [xuxueli/xxl-job#1074]
比如定时任务1、2、3都执行成功了才会执行任务4，怎么实现呢？

**Comment by duanjia85** [comment]
你描述这种需求其实是调度依赖，4依赖1,2,3，但是目前xxl-job使用子任务的方式来组合其他调度，暂时实现不了

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/829
