### ISSUE TITLE
docker中执行器自动注册失败

### ISSUE THREAD

**Issue by slyfalcon** [xuxueli/xxl-job#1075]
Please answer some questions before submitting your issue. Thanks!

**Comment by xuxueli** [comment]
你好，问题无法复现。请提供稳定复现条件。
可以检查下注册请求是不是被拦截，或者用报错。

**Comment by b1na2** [comment]
> 你好，问题无法复现。请提供稳定复现条件。
> 可以检查下注册请求是不是被拦截，或者用报错。

docker内的自动注册获取的是容器内的ip,所以注册不了，有什么解决方案吗

**Comment by ybreathing** [comment]
同问执行器向注册中心注册时，一直失败！  用的是容器的ip，请问有什么解决方案吗？

**Comment by slyfalcon** [comment]
> 同问执行器向注册中心注册时，一直失败！ 用的是容器的ip，请问有什么解决方案吗？

最近没有看当前的调度单系统，有解决方法，我在这里post
