### ISSUE TITLE
执行器日志获取出错

### ISSUE THREAD

**Issue by duanjin123** [xuxueli/xxl-job#1076]
执行任务后出现以下错误：
![00CBCE69-B947-4ca5-B5CC-E42617B972A3](https://user-images.githubusercontent.com/20664506/63236621-19b69580-c271-11e9-9198-a2f7829875a9.png)
（非java程序员，有些看不懂这个错误，是因为格式转换出错吗？使用的版本是2.0.2）

**Comment by Jianglinglong** [comment]
执行的方法不存在

**Comment by xuxueli** [comment]
你好，调度中心与执行器版本应该保持一致，上述问题是版本不一致导致的。
