### ISSUE TITLE
一个executor实例是否能并行执行多个任务？

### ISSUE THREAD

**Issue by HScarb** [xuxueli/xxl-job#1077]
服务部署情况：
admin单独部署在一个虚机
另有一些执行机，每台执行机部署一个executor实例
现有同时执行大量任务的需求，但是经试验一个机器上的executor只能同时运行一个任务。
如果达到一个机器并行执行多个任务的效果？

**Comment by xuxueli** [comment]
你好，单机单任务限制并发的。不过，针对同一个JobHandler可以配置多个任务，多个任务是并行的。
