### ISSUE TITLE
请问有没有支持父级依赖，以及依赖树图形界面的计划

### ISSUE THREAD

**Issue by AtlantisWing** [xuxueli/xxl-job#1078]
如题，现在多个任务依赖一个任务的情况非常常见，比如一张宽表需要多个表跑完之后运行，只有子任务无法满足这一情况

另外希望增加依赖树视图界面，可以方便的展现完整依赖流程

**Comment by xuxueli** [comment]
有计划，合并至：https://github.com/xuxueli/xxl-job/issues/829
