### ISSUE TITLE
任务重复调度

### ISSUE THREAD

**Issue by meteorxht** [xuxueli/xxl-job#1079]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.0
### Expected behavior
通过cron表达式0 0 20 19 8 ? 2019指定在固定时刻触发一次任务调度
### Actual behavior
在该时间点触发了多个任务调度
![image](https://user-images.githubusercontent.com/15025425/63314157-577ef100-c339-11e9-8cd3-7b5803d1ffd6.png)
```
[INFO ] 2019-08-19 20:00:00.056 [Thread-21] MyJobHandler:hellloooooooooo-0 0 20 19 8 ? 2019
[INFO ] 2019-08-19 20:00:00.274 [Thread-21] MyJobHandler:hellloooooooooo-0 0 20 19 8 ? 2019
[INFO ] 2019-08-19 20:00:00.274 [Thread-21] MyJobHandler:hellloooooooooo-0 0 20 19 8 ? 2019
[INFO ] 2019-08-19 20:00:00.275 [Thread-21] MyJobHandler:hellloooooooooo-0 0 20 19 8 ? 2019
[INFO ] 2019-08-19 20:00:00.275 [Thread-21] MyJobHandler:hellloooooooooo-0 0 20 19 8 ? 2019
```
### Steps to reproduce the behavior
任务设置如图
![image](https://user-images.githubusercontent.com/15025425/63314204-82694500-c339-11e9-8b19-a8079fd47471.png)

### Other information

**Comment by meteorxht** [comment]
补充，路由策略-轮询、运行模式-BEAN、阻塞处理策略-单机串行

**Comment by meteorxht** [comment]
任务超时时间和失败重试次数均默认为0

**Comment by hhggbb** [comment]
我也是遇到这个问题，而且执行过后的任务不会自动停止的吗？

**Comment by meteorxht** [comment]
经测试版本降级到2.0.2恢复正常调度

**Comment by xuxueli** [comment]
你好，无法复现，能否提供稳定复现条件。

**Comment by onionkc** [comment]
![image](https://user-images.githubusercontent.com/8519622/63400439-697a9580-c406-11e9-8367-190ed3ce7ebc.png)
![image](https://user-images.githubusercontent.com/8519622/63400461-79927500-c406-11e9-8fc4-1b75cb49f67a.png)
xxl-job-executor-sample-springboot 示例运行，复现重复调度

**Comment by wocaonidaye** [comment]
我也经常性出现此问题，用的2.0.1版本，从开发环境迁移到正式环境后，正式环境出现重复调度概率大概有20%

**Comment by zzujustme** [comment]
我也碰到这个问题，经查找发现v2.1.0对于指定时间执行一次的cron存在重复问题，作者已在marster中进行了修复，jobinfomapper.xml中添加了对status值的改变，mapper.xml修改下即可修复

**Comment by zzujustme** [comment]
> 我也经常性出现此问题，用的2.0.1版本，从开发环境迁移到正式环境后，正式环境出现重复调度概率大概有20%

看我上边回答，是否能解决你的问题

**Comment by seguzhizi** [comment]
> > 我也经常性出现此问题，用的2.0.1版本，从开发环境迁移到正式环境后，正式环境出现重复调度概率大概有20%
> 
> 看我上边回答，是否能解决你的问题

你好，我这边的job版本比较低，暂未升级，目前也遇到了重复问题，并且重复任务导致了金额超发，比较严重，还要向领导解释。。。
请问最新版本是否已经解决了重复执行的问题？

**Comment by xuxueli** [comment]
@seguzhizi 你好，低版本任务调度依赖quartz，可以结合阻塞路由策略+一致性哈希路由策略避免重复触发问题。但是quartz依然会有小概率重复触发问题，官方尚未解决。可以升级新版，新版已经做了优化。

@wocaonidaye @onionkc @meteorxht @hhggbb v2.1.0 任务重试问题可以参考 @zzujustme 的解决方案。master分支，即迭代中的 v2.1.1 做了对应的优化，大大降低了任务重复触发的几率。

**Comment by umena337** [comment]
mark
