### ISSUE TITLE
2.1.0的admin源码怎么得到？貌似前端页面错误都不少……

### ISSUE THREAD

**Issue by yuweiming2016** [xuxueli/xxl-job#1080]
1秒钟请求一次数据库，看着有点慌……

前端登录页面有错误，登录后还有不少……
![image](https://user-images.githubusercontent.com/22490427/63319034-2dcec580-c34b-11e9-94a1-4407760bb76d.png)

请问是不是我拿错了源码？tag2.1.0吗？我发现没分支2.1.0，只有tag2.1.0，于是就拿了tag2.1.0的，出现了上述的问题

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/63319325-47bcd800-c34c-11e9-8f40-3f76eb1afff3.png)

**Comment by xuxueli** [comment]
你好，问题无法复现，建议强刷一下JS缓存，或者直接用docker镜像部署体验。
针对登陆用户的操作进行DB校验，频率较低，影响不大，也可以自行优化。

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/63399573-85c90300-c403-11e9-87ee-484bf1732c33.png)

SELECT t.id, t.job_group, t.job_cron, t.job_desc, t.add_time, t.update_time, t.author, t.alarm_email, t.executor_route_strategy, t.executor_handler, t.executor_param, t.executor_block_strategy, t.executor_timeout, t.executor_fail_retry_count, t.glue_type, t.glue_source, t.glue_remark, t.glue_updatetime, t.child_jobid, t.trigger_status, t.trigger_last_time, t.trigger_next_time FROM xxl_job_info t WHERE t.trigger_status = 1 and t.trigger_next_time < ? 

是这个sql一秒查一次，应该跟登录用户没关系吧？@xuxueli
