### ISSUE TITLE
执行日志查询 空白

### ISSUE THREAD

**Issue by hudiehekafei** [xuxueli/xxl-job#1081]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
查看完整日志
### Actual behavior
没有执行日志
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/35168841/63321282-d46a9480-c352-11e9-8d44-64db840e79fe.png)

### Other information

**Comment by xuxueli** [comment]
你好，应该是执行器日志被清空了，可以debug确认下。
