### ISSUE TITLE
执行器启动成功后，控制台一直反复报：xxl-rpc provider netty_http server caught exception

### ISSUE THREAD

**Issue by lvgitt** [xuxueli/xxl-job#1088]
**执行器启动成功后，控制台一直反复报：xxl-rpc provider netty_http server caught exception**
如下：
```
===2019-08-22 15:09:28.821 ERROR com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler Line:129 - >>>>>>>>>>> xxl-rpc provider netty_http server caught exception
--
  | java.io.IOException: Connection reset by peer
  | at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
  | at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
  | at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
  | at sun.nio.ch.IOUtil.read(IOUtil.java:192)
  | at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
  | at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
  | at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
  | at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
```
环境：
1.执行器为基于Springboot 2.0.6搭建的项目
2.依赖xxl-job版本信息为
`<xxl-job-core.version>2.1.0</xxl-job-core.version>`
3.任务调度中心版本为
![image](https://user-images.githubusercontent.com/44693144/63497117-be490980-c4f5-11e9-9ea4-4ae6ecf7f79b.png)

场景：
1.虽然报错，但是执行器能被正常调用并执行，调度日志也都显示成功
2.执行器项目部署在阿里云edas正式环境命名空间的k8s集群上，调度器部署在阿里云测试环境命名空间的k8s集群上（不同命名空间互访相当于跨平台访问）
3.执行器配置的负载均衡外网端口号和映射的应用端口号都和执行器的端口号（9990）一样，但是负载均衡协议是TCP而非HTTP（选不了HTTP）
![image](https://user-images.githubusercontent.com/44693144/63496538-b2107c80-c4f4-11e9-84b5-70c904c8a7da.png)
4.如果执行器配置的负载均衡所映射的应用端口号为执行器服务本身启动的端口号（server.port=18083）而非执行器端口号（xxl.job.executor.port=9990），则启动后不会报如上错误，但是调度器会连接不到执行器（因为执行器的端口号没有通过外网负载均衡映射给外网？）
![image](https://user-images.githubusercontent.com/44693144/63496587-c785a680-c4f4-11e9-963c-22a7d3543791.png)
![image](https://user-images.githubusercontent.com/44693144/63496747-061b6100-c4f5-11e9-80f5-7c49cd2181f2.png)

**Comment by a805748009** [comment]
插眼。同样的问题

**Comment by lvgitt** [comment]
> 插眼。同样的问题

同样的场景，同样的报错吗？

**Comment by a805748009** [comment]
> > 插眼。同样的问题
> 
> 同样的场景，同样的报错吗？

对呀。所以来看issue了

**Comment by biqingguo** [comment]
是的遇到了同样的问题

**Comment by jzbbobo** [comment]
_部署在k8s集群，同样也遇到这个问题了。。。

**Comment by xuxueli** [comment]
@lvgitt  
第一个问题：调度正常进行，但是底层报错。这个是非法请求导致的，并不影响正常调度。可以排查下是否有类似爬虫的组件在不停扫描端口。
第二个问题：执行器通讯端口与Web容器端口不能配置一致，会导致端口冲突。

其他同学的问题，可以完成描述一下，重新提个ISSUE看下。

**Comment by Gitforxuyang** [comment]
遇到了同样的问题。测了一下是因为执行器设置了lb访问方式。阿里云的lb会自动定时检查端口是否可用。把Lb删了问题就解决了

**Comment by mrwangrj** [comment]
> 遇到了同样的问题。测了一下是因为执行器设置了lb访问方式。阿里云的lb会自动定时检查端口是否可用。把Lb删了问题就解决了

关掉lb的监控检查可以了

**Comment by elichn** [comment]
@mrwangrj ，遇到同样的问题，阿里云lb的监控检查在界面哪个位置呢？

**Comment by wangchao550586585** [comment]
解决办法：https://github.com/xuxueli/xxl-job/issues/2507

**Comment by wangchao550586585** [comment]
主要是云提供商lb的健康检查造成的。执行器的9999端口，分别在阿里云和腾讯云配置了lb，而且是tcp协议的。
而xxljob调度中心与执行器的心跳底层是依赖netty进行的http协议维持。
解决办法如下：
1：9999端口在lb上配置http协议。（这个没必要）
2：关闭lb心跳检查。
3：自定义tcp协议。（这个没必要）
4：关闭lb
阿里云给出的方案：
![image](https://user-images.githubusercontent.com/21312820/125557100-240688d4-05c9-472f-8170-b5d567ec37b6.png)
腾讯云给出的方案：
![image](https://user-images.githubusercontent.com/21312820/125557107-3c8e9eb4-8373-4228-a15e-4d5f2e474d3e.png)

**Comment by lgm198** [comment]
@mrwangrj 请教一下执行器的lb怎么关闭

**Comment by jary0524** [comment]
这个问题并没有解决啊？

**Comment by a805748009** [comment]
自动回复——已收到。
