### ISSUE TITLE
SpringBoot全面支持！

### ISSUE THREAD

**Issue by antergone** [xuxueli/xxl-job#109]
SpringBoot版本改好了，有兴趣的可以自己下载编译。由于改动太大，不方便合并到的主项目里。
项目地址：https://github.com/Antergone/xxl-job

**Comment by xuxueli** [comment]
赞！

**Comment by edgelone** [comment]
@Antergone 项目里有很多model 都没有get set方法  怎么跑起来的?

**Comment by Antergone** [comment]
@edgelone 请用javap看一下class文件。关注一下lombok! :)

**Comment by edgelone** [comment]
@Antergone  thank you ~

**Comment by FengRi** [comment]
有计划将XXL-job 整到自己搭建的Spring Cloud 框架中去!

**Comment by xuxueli** [comment]
已合并至：https://github.com/xuxueli/xxl-job/issues/154

主分支已确定于 2.0 迁移至 springboot，敬请期待！
