### ISSUE TITLE
python的环境配置以及执行器如何注册

### ISSUE THREAD

**Issue by LifeStreams** [xuxueli/xxl-job#1090]
哈喽，这边有需求需要使用到 GLUE模式(Python) 来进行Python调用，但是我在官方文档以及issues中没有发现python集成的相关配置，请问有没有相关的集成资料参考呢？

**Comment by WintererOoO** [comment]
@LifeStreams 看代码应该必须要用java来注册,运行python也只是用java里的脚本执行器来执行,不能直接执行python

**Comment by xuxueli** [comment]
@LifeStreams @WintererOoO 你好，按照文档正确部署执行器即可。只需要保障执行器机器正确安装python环境，不需要额外配置。

**Comment by 1325075688gw** [comment]
> @LifeStreams @WintererOoO 你好，按照文档正确部署执行器即可。只需要保障执行器机器正确安装python环境，不需要额外配置。

别人说的意思是如何在Python项目（如Django项目）中通过xxl-job提供的sdk去注册一个定时任务

**Comment by showkeyjar** [comment]
是否可以将文档补充详细一些？
如果用python可能不止一个python环境，virtualenv, conda等等，
然后不同服务器上python执行是否需要自行实现一套与执行器一样的规范？
否则执行进度日志、执行的终止、超时等是否也能实现？
