### ISSUE TITLE
xxl-job, job fail monitor thread error:{}

### ISSUE THREAD

**Issue by fengxinxin** [xuxueli/xxl-job#1092]
![image](https://user-images.githubusercontent.com/13414276/63562528-8f33a600-c590-11e9-95ca-5e4122958406.png)

jenkins打包的部署的时候，经常报空指针异常，我把国际化那里给改了，然后发现，好像这个问题，请问该如何解决？？？

**Comment by xuxueli** [comment]
你好，这是Bean初始化顺序的问题，概率缴小，最新版本已经修复了这个问题。
只需要在XxlJobScheduler组件上添加@DependsOn("xxlJobAdminConfig")即可，可以参考maser分支。
