### ISSUE TITLE
GLUE(Java) 模式不支持事务

### ISSUE THREAD

**Issue by chenxd1991** [xuxueli/xxl-job#1093]
@Transactional(rollbackFor = Exception.class)
    public ReturnT<String> execute(String s) throws Exception {
       .................
       .................
    }
当在GLUE模式下使用Transactional注解的时候并没有生效

**Comment by WintererOoO** [comment]
GLUE本质上是各种不同语言的脚本,由脚本执行器执行.所以是没有被spring容器所管理的,建议你直接使用jdbc,自己控制事务
