### ISSUE TITLE
spring-boot版本是否考虑升级

### ISSUE THREAD

**Issue by mrjerryli** [xuxueli/xxl-job#1096]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
  *     使用的是xxl-job2.1.0版本

介入使用后，为何公司项目使用同一版本的springboot2.0.5，故将xxl-job中对springboot版本提升到2.1.0，所以想问一下后期有打算升级springboot版本的计划还是说升级后会对xxl-job功能有影响，做适配需要时间，是否有危害等？

**Comment by fxbin** [comment]
同问，是够考虑升级SpringBoot 版本到 2.1.X-RELEASE

**Comment by Euthpic** [comment]
已经同时将执行器和调度中心都升到2.1.6,没有影响

**Comment by xuxueli** [comment]
你好，向下兼容的。后续 v2.2 版本计划基于JDK8迭代，会实时跟进最新SpringBoot版本；
