### ISSUE TITLE
集群环境下任务执行丢失

### ISSUE THREAD

**Issue by kervin521** [xuxueli/xxl-job#1099]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
当前版本：v2.1.0
### Expected behavior
任务数：2600
执行时间：0/1 * * * * ? * （每秒一次）
任务路由策略: 一致性Hash
任务阻塞策略：丢弃后续调度
执行器数量：21
运行模式: Bean
任务超时：3600
调度中心：1个

期望：所有任务均执行
### Actual behavior
首次添加任务后所有任务执行一次

执行一次后只有55个不同种类任务（executor_param）循环执行，其他2550个任务不在调度
![image](https://user-images.githubusercontent.com/9798724/63769060-669b0b80-c904-11e9-8f9a-921c267682c6.png)
![image](https://user-images.githubusercontent.com/9798724/63769121-8c281500-c904-11e9-83c8-a314ef42ee8c.png)
![image](https://user-images.githubusercontent.com/9798724/63769152-a235d580-c904-11e9-9305-fc009eea0598.png)

### Steps to reproduce the behavior
请问如何优化？
### Other information
目前采用docker的swarm集群方式部署应用，注册的执行器IP有21个

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/63769224-dd380900-c904-11e9-9f3c-e8b1132e01f2.png)

**Comment by ybreathing** [comment]
想请问下docker容器下的ip自动想调度中心注册失败，是执行中心用docker容器的ip去调度中心注册导致的吗？有什么方法解决吗？

**Comment by kervin521** [comment]
@ybreathing 不要IP自动注册，自己使用网卡接口在应用程序中获取Docker环境下的IP后解决，我已解决这个问题

**Comment by xuxueli** [comment]
@kervin521 你好，任务不触发的问题，推测应该是任务量大，导致调度线程耗尽导致，可以适当调大调度线程，或者集群部署调度中心，分摊调度压力。

@kervin521 你好，你Docker下获取IP问题的解决方案，这个很棒啊，社区里有很多小伙伴遇到这个问题。欢迎重新提交一份ISSUE，分享这个经验啊！

**Comment by Lyeluo** [comment]
@xuxueli 您好，我看了您在2.2.0版本的调度线程源码，是一次性扫描了6000（（200+100）*20）个job，然后放在线程ringdata里面，然后由另一个线程池去执行了。请问是乘数20这个值是如何得来的呢？因为目前我们测试时发现1000个以上的调度任务执行时，会出现任务无法调度或者调度时间不准确的问题出现。这种情况即使集群部署调度中心，可是每次调度中心扫描了6000个调度任务，压力也还是集中在一个调度中心的节点上呀
