### ISSUE TITLE
1.7.2  从maven仓库中下载代码，运行报错

### ISSUE THREAD

**Issue by wildchase** [xuxueli/xxl-job#110]
错误位置  Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/util/thread/ThreadPool : Unsupported major.minor version 52.0

错误原因，deploy到maven仓库中的jetty版本是在jdk8下编译的，运行失败。

在github 上查询，1.7.2中 jetty版本是9.2.21.v20170120，但是仓库下载下来的 9.4.5.v20170502

大爷没有必要这么搞吧，这是歧视jdk7

**Comment by wildchase** [comment]
算了，我自己去掉jetty依赖，重新在工程里引入jdk7版本的jetty

**Comment by wildchase** [comment]
springboot 采用 dependencyManagement的方式引入，
xxlJob的demo 例子springboot1.3.8版本对应的是可以在jdk下运行的jetty， 
我的工程是springboot1.5.4，所以就坑了，相应的试了1.4.*版本，也不行，

**Comment by xuxueli** [comment]
是的，需要过滤掉高版本jetty，引入指定版本：9.2.21.v20170120

**Comment by lisongqiu168** [comment]
test

**Comment by lisongqiu168** [comment]
test
