### ISSUE TITLE
任务管理和执行器是否支持复制功能

### ISSUE THREAD

**Issue by lizhuangs** [xuxueli/xxl-job#1101]
### Other information
多个集群，多个机房的时候，每次都手动添加好累。。
任务管理和执行器管理是否应该支持复制功能？

**Comment by xuxueli** [comment]
你好，执行器操作频率较低，不建议复制。
任务的复制比较有意义，已经加入TODO排期，预计会在v2.2.x 提供。

**Comment by lizhuangs** [comment]
在阿里云上面部署了多套集群的时候就会有这个问题了。。。
