### ISSUE TITLE
怎么只有7张表，而不是16张表了？是缩减了功能吗

### ISSUE THREAD

**Issue by Cuifc** [xuxueli/xxl-job#1108]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Other information

**Comment by yuweiming2016** [comment]
是啊，去掉了quartz了，所以表少了好多，现在是xxl自己写的触发逻辑

**Comment by xuxueli** [comment]
@yuweiming2016  +1
