### ISSUE TITLE
oracle版本

### ISSUE THREAD

**Issue by TuitaKing** [xuxueli/xxl-job#111]
根据原有mybatis改的oracle版本，目前只是测试通过bean模式和GLUE模式。（1.7.2版本）
地址为：https://github.com/TuitaKing/xxl-job.git
如果发现问题，请回复下，谢谢

**Comment by xuxueli** [comment]
赞！

**Comment by untrueman** [comment]
这是我改的 1.8.1的，因为刚升级1.8.1快照版，1.8.0也可以用的。
https://github.com/untrueman/xxl-job

**Comment by ailaopo415** [comment]
两个版本的数据库脚本和mapper文件都不正确，能把修改后的文件上传下吗？

**Comment by TuitaKing** [comment]
我这个是1.7.2的版本，你是用的那个版本啊？

**Comment by mankindli** [comment]
任务执行完毕后无法正常回调写入结果，经比对，问题是出在JobApiController

**Comment by pangkailang** [comment]
任务执行完毕后无法正常回调写入结果，经比对，问题是出在JobApiController，怎么解决的 @mankindli

**Comment by pangkailang** [comment]
任务执行完毕后无法正常回调写入结果，这个注册能够成功，但是执行回调就不成功了 @TuitaKing

**Comment by 93132149** [comment]
任务执行完毕后无法正常回调写入结果，这个注册能够成功，但是执行回调就不成功了，怎么解决的@TuitaKing

**Comment by 93132149** [comment]
任务执行完毕后无法正常回调写入结果，经比对，问题是出在JobApiController，怎么解决的 @mankindli

**Comment by 93132149** [comment]
任务执行完毕后无法正常回调写入结果，经比对，问题是出在JobApiController，怎么解决的 @pangkailang

**Comment by TuitaKing** [comment]
我现在用的还是1.7.2的，后面的版本没有跟进了。不过雪里的代码写的很容易读，建议可以稍微看下源码。

**Comment by xuxueli** [comment]
已合并至：https://github.com/xuxueli/xxl-job/issues/154
