### ISSUE TITLE
xxl-job 2.1.0版本 jackson反序列化导致调用失败

### ISSUE THREAD

**Issue by lacorey** [xuxueli/xxl-job#1110]
xxl-job 2.1.0版本中将序列化改为JACKSON，执行单元测试AdminBizTest中的registryTest方法，在ServletServerHandler中的parseRequest方法会将XxlRpcRequest中的Object[] parameters反序列成LinkedHashMap[] parameters，在XxlRpcProviderFactory的invokeService方法中反射调用registry时参数异常错误。

**Comment by xuxueli** [comment]
你好，建议使用默认配置。
