### ISSUE TITLE
同一任务跑批执行了两次，期望只执行一次

### ISSUE THREAD

**Issue by Goospy** [xuxueli/xxl-job#1111]
你好，我们设置了一个Bean模式的跑批任务，阻塞处理策略是“单机串行”，偶尔会出现第一次跑批任务成功完成，但之后紧接着又触发了一次相同的跑批任务。实现是异步处理业务逻辑，直接返回成功，所以跑批任务会很快结束，不知道这个会不会影响。

**Comment by crazythinking** [comment]
异步肯定会影响，xxljob的实现原理就是通过线程阻塞来感知相同job是否正在执行的

**Comment by Goospy** [comment]
> 异步肯定会影响，xxljob的实现原理就是通过线程阻塞来感知相同job是否正在执行的

哦，可能我没描述清楚，job的execute方法是调用了我们自己一个微服务的接口，我们接口里是异步处理业务逻辑，同步直接返回给jobHandler调用方响应成功，然后execute方法return SUCCESS，所以execute方法可以理解成完全同步的方法。
比较奇怪的是为啥会重复执行。

**Comment by Goospy** [comment]
找到历史相关问题了：https://github.com/xuxueli/xxl-job/issues/370

最新版本移除了quartz，应该没有重复执行的问题了。
