### ISSUE TITLE
TriggerCallbackThread 报错，然后就一直循环

### ISSUE THREAD

**Issue by jszenda** [xuxueli/xxl-job#1113]
for (File callbaclLogFile: callbackLogPath.listFiles()) {
            byte[] callbackParamList_bytes = FileUtil.readFileContent(callbaclLogFile);
            List<HandleCallbackParam> callbackParamList = (List<HandleCallbackParam>) XxlJobExecutor.getSerializer().deserialize(callbackParamList_bytes, HandleCallbackParam.class);

            callbaclLogFile.delete();
            doCallback(callbackParamList);
        }
## 当callbaclLogFile为空的时候，就会反序列失败，然后这个文件不会被删除，
线程一直在监控这个文件夹下的目录，一直循环。。。

**Comment by xuxueli** [comment]
你好，只有在callbackLogPath目录存在且下面存在文件的时候，才会遍历文件，这个时候被遍历的文件是肯定存在，理论上不会出现上述问题。

请进一步提供问题复现步骤。
