### ISSUE TITLE
xxl-job 在操作那里选择执行一次的时候，不能够指定对应的执行机器，不能方便的在测试环境测试

### ISSUE THREAD

**Issue by jssngz** [xuxueli/xxl-job#1114]
@xuxueli 你好，感谢你开发了xxl-job,我在搭建xxl-job平台的时候，发现在操作哪里选择执行一次的时候，没有办法指定对应的已经注册的机器来执行任务。这样的话，在测试环境/线上环境无法指定对应的机器执行。
执行一次这种场景，很大情况是要指定对应的机器来执行的。现在机器是选择是使用路由策略里面设定的策略来选择的，能否设置一个指定机器策略，给定指定的机器，这样能够实现选择指定的机器来执行任务。
再次感谢你的贡献。

**Comment by xuxueli** [comment]
你好，可以新建一个执行器，为该执行器设置固定IP，通过该IP对指定机器触发。
