### ISSUE TITLE
分片广播模式下，子任务会被多次触发

### ISSUE THREAD

**Issue by crazythinking** [xuxueli/xxl-job#1116]
父任务为分片模式时，如果配置了子任务，那么会造成子任务被触发分片数量相同的次数；目前2.1.1的版本下，是否有什么方式能做到分片的父任务完成后聚合全部成功后，才调度子任务，这样子任务应该只被调度一次

**Comment by imsuperman0920** [comment]
同问，我也遇到了这个问题~

**Comment by oszhugc** [comment]
刚开始研究xxl-job, 请问下有解决方案了吗

**Comment by crazythinking** [comment]
我这里持久化了一个batchid，用于标识分片的父任务，作为同一批次的任务，然后再判断同一批次都成功的情况下，才触发之后的子任务，这里结合了我这个项目的具体情况，父任务不成功的情况，不能触发后续子任务

**Comment by oszhugc** [comment]
谢谢, 批次号是在`AdminBizImpl.java`类中的`callBack()`方法里判断吗, 我是这样处理的,但是当分片任务有同时完成的时,子任务也会多次调用.
![20191126174734](https://user-images.githubusercontent.com/30380165/69618520-fa4fb580-1074-11ea-8156-05b91e6e1b91.png)

**Comment by crazythinking** [comment]
是的，关键是要判断同批次的所有任务都要成功

**Comment by oszhugc** [comment]
谢谢, 这样的话把子任务的`阻塞方式`改成`丢弃后续调度`应该会好一些.

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172

你好，分片任务全部完成后才会出发子任务，将会在DAG流程任务里一并实现。规划中。
