### ISSUE TITLE
修改为Mongodb是否只需要修改掉DAO层即可

### ISSUE THREAD

**Issue by ati46** [xuxueli/xxl-job#1118]
公司只用Mongodb，目前需要xxl来作为任务调度，打算修改为Mongodb
请问是否只需要改动dao层？。
因为尽可能要保证源代码不动，才能跟随版本一起更新

**Comment by xuxueli** [comment]
你好，v2.1.0 以以后的版本只需要修改DAO层即可。定制可以参考汇总的其他分支版本：https://github.com/xuxueli/xxl-job/issues/154

**Comment by miaoo92** [comment]
@ati46 你好，我是一个新手，想问问您目前在xxl-job支持MongoDB上是怎么实践的？如果有空的话，能否帮我答疑一下？
