### ISSUE TITLE
任务依赖传参问题

### ISSUE THREAD

**Issue by gaoshuze** [xuxueli/xxl-job#1119]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
在父任务执行完成后，触发子任务执行时，如何对子任务进行传参？？
### Other information

**Comment by imsuperman0920** [comment]
目前不支持吧。只能曲线救国了，比如向指定地方写，再从这个地方读。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/579
