### ISSUE TITLE
为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！

### ISSUE THREAD

**Issue by JavaCodeMood** [xuxueli/xxl-job#1120]
![image](https://user-images.githubusercontent.com/19645978/64220608-8b8f1000-cefc-11e9-919e-e31676ec9d11.png)

**Comment by JavaCodeMood** [comment]
<!DOCTYPE html>
<html>
<head>
  	
	<link rel="icon" href="/xxl-job-admin/static/favicon.ico" />

	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    
    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/bower_components/bootstrap/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/bower_components/font-awesome/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/bower_components/Ionicons/css/ionicons.min.css">
    
    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/dist/css/AdminLTE.min.css">
    
    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/dist/css/skins/_all-skins.min.css">
      
	
    
    

	
	<link rel="stylesheet" href="/xxl-job-admin/static/adminlte/bower_components/PACE/themes/blue/pace-theme-flash.css">


    <link rel="stylesheet" href="/xxl-job-admin/static/adminlte/plugins/iCheck/square/blue.css">
	<title>任务调度中心</title>
</head>
<body class="hold-transition login-page">
	<div class="login-box">
		<div class="login-logo">
			<a><b>XXL</b>JOB</a>
		</div>
		<form id="loginForm" method="post" >
			<div class="login-box-body">
				<p class="login-box-msg">任务调度中心</p>
				<div class="form-group has-feedback">
	            	<input type="text" name="userName" class="form-control" placeholder="请输入登录账号"  maxlength="20" >
	            	<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
				</div>
	          	<div class="form-group has-feedback">
	            	<input type="password" name="password" class="form-control" placeholder="请输入登录密码"  maxlength="20" >
	            	<span class="glyphicon glyphicon-lock form-control-feedback"></span>
	          	</div>
				<div class="row">
					<div class="col-xs-8">
		              	<div class="checkbox icheck">
		                	<label>
		                  		<input type="checkbox" name="ifRemember" > &nbsp; 记住密码
		                	</label>
						</div>
		            </div>
		            <div class="col-xs-4">
						<button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
					</div>
				</div>
			</div>
		</form>
	</div>
	
	<script src="/xxl-job-admin/static/adminlte/bower_components/jquery/jquery.min.js"></script>
	
	<script src="/xxl-job-admin/static/adminlte/bower_components/bootstrap/js/bootstrap.min.js"></script>
	
	<script src="/xxl-job-admin/static/adminlte/bower_components/fastclick/fastclick.js"></script>
	
	<script src="/xxl-job-admin/static/adminlte/dist/js/adminlte.min.js"></script>
	
	<script src="/xxl-job-admin/static/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>

    
    <script src="/xxl-job-admin/static/adminlte/bower_components/PACE/pace.min.js"></script>
	<script src="/xxl-job-admin/static/plugins/jquery/jquery.cookie.js"></script>
	<script src="/xxl-job-admin/static/plugins/jquery/jquery.validate.min.js"></script>

	<script src="/xxl-job-admin/static/plugins/layer/layer.js"></script>

    <script src="/xxl-job-admin/static/js/common.1.js"></script>
    <script>
		var base_url = '/xxl-job-admin';
        var I18n = {"dataTable_sSortAscending":": 以升序排列此列","jobgroup_field_appName_length":"AppName长度限制为4~64","jobconf_route_round":"轮询","system_update_fail":"更新失败","jobconf_block_SERIAL_EXECUTION":"单机串行","jobconf_route_lfu":"最不经常使用","dataTable_sLast":"末页","jobinfo_shard_index":"分片序号","jobinfo_field_executorparam":"任务参数","user_add":"新增用户","jobinfo_field_gluetype":"运行模式","job_dashboard_job_num":"任务数量","system_api_error":"接口异常","jobconf_route_last":"最后一个","jobinfo_opt_log":"查询日志","jobinfo_field_id":"任务ID","jobinfo_field_executorRouteStrategy":"路由策略","jobinfo_job":"任务","daterangepicker_ranges_last_month":"上个月","jobconf_trigger_exe_regaddress":"执行器-地址列表","system_not_found":"不存在","user_password_update_placeholder":"请输入新密码，为空则不更新密码","jobinfo_shard_total":"分片总数","jobgroup_empty":"不存在有效执行器,请联系管理员","system_update_suc":"更新成功","login_password_lt_4":"登录密码不应低于4位","daterangepicker_ranges_this_month":"本月","dataTable_sSearch":"搜索","job_dashboard_trigger_num_tip":"调度中心触发的调度次数","user_role":"角色","user_role_admin":"管理员","joblog_handleCode_500":"失败","daterangepicker_custom_starttime":"起始时间","joblog_status_suc":"成功","joblog_handleCode_502":"失败(超时)","jobgroup_field_order_digits":"请输入整数","jobinfo_name":"任务管理","jobinfo_field_alarmemail":"报警邮件","joblog_rolling_log_refresh":"刷新","daterangepicker_custom_endtime":"结束时间","logout_btn":"注销","jobconf_trigger_type_cron":"Cron触发","jobinfo_field_executorFailRetryCount_placeholder":"失败重试次数，大于零时生效","daterangepicker_custom_monthnames":"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月","joblog_clean_log":"日志清理","user_permission":"权限","dataTable_sLoadingRecords":"载入中...","system_opt_edit":"编辑","admin_name":"任务调度中心","job_dashboard_report_loaddata_fail":"调度报表数据加载异常","user_role_normal":"普通用户","login_param_unvalid":"账号或密码错误","jobconf_trigger_type_retry":"失败重试触发","login_password_empty":"请输入登录密码","jobinfo_field_cron_unvalid":"Cron格式非法","jobconf_beat":"心跳检测","joblog_clean_type_2":"清理三个月之前日志数据","job_dashboard_date_report":"日期分布图","joblog_clean_type_1":"清理一个月之前日志数据","joblog_kill_log":"终止任务","user_update_loginuser_limit":"禁止操作当前登录账号","joblog_clean_type_6":"清理一万条以前日志数据","joblog_clean_type_5":"清理一千条以前日志数据","jobgroup_field_order":"排序","joblog_clean_type_4":"清理一年之前日志数据","joblog_clean_type_3":"清理六个月之前日志数据","jobgroup_field_title_length":"名称长度限制为4~12","jobconf_route_failover":"故障转移","joblog_status":"状态","system_search":"搜索","dataTable_sFirst":"首页","jobgroup_del_limit_1":"拒绝删除, 系统至少保留一个执行器","jobconf_trigger_run":"触发调度","jobinfo_field_update":"更新任务","jobgroup_del_limit_0":"拒绝删除，该执行器使用中","admin_version":"2.1.1-SNAPSHOT","jobconf_route_consistenthash":"一致性HASH","system_ok":"确定","jobconf_trigger_admin_adress":"调度机器","user_username_valid":"限制以小写字母开头，由小写字母、数字组成","system_add_suc":"新增成功","login_username_placeholder":"请输入登录账号","jobconf_trigger_address_empty":"调度失败：执行器地址为空","jobconf_monitor_detail":"监控告警明细","jobinfo_field_childJobId":"子任务ID","jobconf_route_lru":"最近最久未使用","jobinfo_field_executorTimeout_placeholder":"任务超时时间，单位秒，大于零时生效","joblog_rolling_log":"执行日志","jobconf_route_busyover":"忙碌转移","system_please_choose":"请选择","job_help_document":"官方文档","jobconf_route_shard":"分片广播","joblog_clean":"清理","jobinfo_glue_jobid_unvalid":"任务ID非法","jobconf_route_first":"第一个","jobinfo_field_jobgroup":"执行器","system_lengh_limit":"长度限制","dataTable_sSortDescending":": 以降序排列此列","joblog_logid_unvalid":"日志ID非法","logout_confirm":"确认注销登录?","dataTable_sInfoFiltered":"(由 _MAX_ 项结果过滤)","daterangepicker_ranges_recent_week":"最近一周","user_username_repeat":"账号重复","daterangepicker_ranges_recent_hour":"最近一小时","jobgroup_field_registryList_unvalid":"机器地址格式非法","joblog_field_triggerTime":"调度时间","jobconf_block_COVER_EARLY":"覆盖之前调度","system_opt":"操作","joblog_field_handleCode":"执行结果","joblog_status_running":"进行中","user_password":"密码","job_dashboard_jobgroup_num":"执行器数量","jobconf_trigger_type_manual":"手动触发","login_btn":"登录","jobinfo_field_author":"负责人","joblog_field_executorAddress":"执行器地址","joblog_handleCode_200":"成功","dataTable_sPrevious":"上页","system_permission_limit":"权限拦截","joblog_kill_log_byman":"人为操作主动终止","job_dashboard_name":"运行报表","dataTable_sProcessing":"处理中...","jobconf_trigger_type":"任务触发类型","system_cancel":"取消","jobinfo_field_executorFailRetryCount":"失败重试次数","daterangepicker_ranges_recent_month":"最近一月","dataTable_sInfoEmpty":"无记录","login_success":"登录成功","system_digits":"整数","job_help":"使用教程","daterangepicker_custom_name":"自定义","system_tips":"系统提示","jobinfo_field_jobdesc":"任务描述","jobgroup_field_appName_limit":"限制以小写字母开头，由小写字母、数字和中划线组成","jobconf_monitor_alarm_title":"告警类型","system_opt_del":"删除","system_nav":"导航","jobgroup_field_addressType_limit":"手动录入注册方式，机器地址不可为空","job_dashboard_jobgroup_num_tip":"调度中心在线的执行器机器数量","jobconf_trigger_type_api":"API触发","jobgroup_field_title":"名称","system_fail":"失败","jobgroup_del":"删除执行器","dataTable_sEmptyTable":"表中数据为空","joblog_clean_type_unvalid":"清理类型参数异常","jobconf_monitor":"任务调度中心监控报警","system_opt_fail":"操作失败","job_dashboard_report":"调度报表","jobconf_trigger_child_run":"触发子任务","jobinfo_glue_rollback":"版本回溯","joblog_status_fail":"失败","jobgroup_field_orderrange":"取值范围为1~1000","system_close":"关闭","joblog_clean_type_9":"清理所有日志数据","joblog_clean_type_8":"清理十万条以前日志数据","system_show":"查看","joblog_clean_type_7":"清理三万条以前日志数据","jobinfo_field_cron_never_fire":"Cron非法，永远不会触发","jobgroup_edit":"编辑执行器","jobinfo_opt_stop":"停止","jobinfo_script_location":"脚本位置","jobgroup_field_registryList_placeholder":"请输入执行器地址列表，多地址逗号分隔","jobinfo_field_childJobId_placeholder":"请输入子任务的任务ID,如存在多个则逗号分隔","joblog_clean_type":"清理方式","joblog_field_triggerMsg":"调度备注","user_update":"更新用户","login_remember_me":"记住密码","system_opt_suc":"操作成功","jobgroup_name":"执行器管理","daterangepicker_custom_daysofweek":"日,一,二,三,四,五,六","jobinfo_glue_remark":"源码备注","logout_success":"注销成功","jobinfo_field_timeout":"任务超时时间","user_manage":"用户管理","jobgroup_list":"执行器列表","login_password_placeholder":"请输入登录密码","jobconf_idleBeat":"空闲检测","system_empty":"无","joblog_rolling_log_failoften":"终止请求Rolling日志,请求失败次数超上限,可刷新页面重新加载日志","jobconf_callback_child_msg1":"{0}/{1} [任务ID={2}], 触发{3}, 触发备注: {4} <br>","joblog_name":"调度日志","dataTable_sNext":"下页","admin_name_full":"分布式任务调度平台XXL-JOB","daterangepicker_ranges_yesterday":"昨日","logout_fail":"注销失败","system_success":"成功","login_param_empty":"账号或密码为空","jobgroup_add":"新增执行器","job_dashboard_trigger_num":"调度次数","jobinfo_opt_registryinfo":"注册节点","jobconf_monitor_alarm_content":"告警内容","joblog_status_all":"全部","jobconf_route_random":"随机","system_unvalid":"非法","jobinfo_opt_start":"启动","login_username_lt_4":"登录账号不应低于4位","joblog_kill_log_limit":"调度失败，无法终止日志","jobconf_callback_child_msg2":"{0}/{1} [任务ID={2}], 触发失败, 触发备注: 任务ID格式错误 <br>","dataTable_sZeroRecords":"没有匹配结果","jobconf_trigger_type_parent":"父任务触发","jobconf_block_DISCARD_LATER":"丢弃后续调度","joblog_field_handleTime":"执行时间","dataTable_sLengthMenu":"每页 _MENU_ 条记录","jobgroup_field_registryList":"机器地址","system_all":"全部","jobinfo_field_alarmemail_placeholder":"请输入报警邮件，多个邮件地址则逗号分隔","jobgroup_field_addressType":"注册方式","job_dashboard_job_num_tip":"调度中心运行的任务数量","jobconf_trigger_exe_regtype":"执行器-注册方式","jobgroup_field_addressType_1":"手动录入","jobgroup_field_addressType_0":"自动注册","jobconf_monitor_alarm_type":"调度失败","joblog_rolling_log_triggerfail":"任务发起调度失败，无法查看执行日志","dataTable_sInfo":"第 _PAGE_ 页 ( 总共 _PAGES_ 页，_TOTAL_ 条记录 )","jobinfo_opt_run":"执行一次","user_username":"账号","jobinfo_field_executorBlockStrategy":"阻塞处理策略","login_username_empty":"请输入登录账号","joblog_field_handleMsg":"执行备注","jobinfo_field_add":"新增","daterangepicker_ranges_today":"今日","system_save":"保存","job_dashboard_rate_report":"成功比例图","joblog_field_triggerCode":"调度结果","system_status":"状态","system_please_input":"请输入","jobinfo_glue_gluetype_unvalid":"该任务非GLUE模式","system_add_fail":"新增失败","login_fail":"登录失败","jobinfo_glue_remark_limit":"源码备注长度限制为4~100"};
	</script>

<script src="/xxl-job-admin/static/adminlte/plugins/iCheck/icheck.min.js"></script>
<script src="/xxl-job-admin/static/js/login.1.js"></script>

</body>
</html>

**Comment by xuxueli** [comment]
你好，应该会回调地址配错了，执行器回调地址应该为调度中心跟地址。

**Comment by JavaCodeMood** [comment]
xxl-job-admin和xxl-job-executor-samples都需要配置xxl.job.accessToken，保证两个服务的accessToken要相同才行，就可以跳过拦截了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"许雪里"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 晚上6:35
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"无伤无怨"<2510736432@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120)




Closed #1120.

**Comment by JavaCodeMood** [comment]
要获得accessToken，需要你启动xxl-job-admin服务，登录之后，浏览器开发模式下，找到pageList的cookie，accessToken就在里面，自己取出来用就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "霜花似雪"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 晚上6:41
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "无伤无怨"<2510736432@qq.com&gt;; "Your activity"<your_activity@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120)



xxl-job-admin和xxl-job-executor-samples都需要配置xxl.job.accessToken，保证两个服务的accessToken要相同才行，就可以跳过拦截了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"许雪里"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月15日(星期五) 晚上6:35 
 收件人:&amp;nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"无伤无怨"<2510736432@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120) 
 
 
 
 
 Closed #1120.

**Comment by JavaCodeMood** [comment]
不明白可以加我QQ:2510736432，互相学习，互相交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "霜花似雪"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 晚上6:47
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "无伤无怨"<2510736432@qq.com&gt;; "Your activity"<your_activity@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120)



要获得accessToken，需要你启动xxl-job-admin服务，登录之后，浏览器开发模式下，找到pageList的cookie，accessToken就在里面，自己取出来用就可以了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "霜花似雪"<notifications@github.com&amp;gt;;  
 发送时间: 2019年11月15日(星期五) 晚上6:41 
 收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&amp;gt;;  
 抄送: "无伤无怨"<2510736432@qq.com&amp;gt;; "Your activity"<your_activity@noreply.github.com&amp;gt;;  
 主题: Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120) 
 
 
 
 xxl-job-admin和xxl-job-executor-samples都需要配置xxl.job.accessToken，保证两个服务的accessToken要相同才行，就可以跳过拦截了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"许雪里"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2019年11月15日(星期五) 晚上6:35  
  收件人:&amp;amp;nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"无伤无怨"<2510736432@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xuxueli/xxl-job] 为什么调度中心和执行器都配置了accessToken，但是在访问调度中心的接口，还是会被拦截，并返回一个html，要求输入账号和密码？这个accessToken是怎么生成的？要怎么配置在访问调度中心的接口时，才不会被拦截？知道的大佬告诉我一下，万分感谢！ (#1120)  
   
   
   
   
  Closed #1120.
