### ISSUE TITLE
执行器部署在docker，注册到xxl-job-admin的ip不正确

### ISSUE THREAD

**Issue by chenxd1991** [xuxueli/xxl-job#1121]
docker部署执行器在启动项目时，在注册到xxl-job-admin时注册的是docker自己的ip而不是docker所在虚拟机的ip导致admin访问不到执行器项目

**Comment by llade** [comment]
貌似只能自己设置死IP地址。
或者获取本机所有的IP地址，然后自己设置一个参数ipStartWith: 192.168.0
逐个判断IP是否你的目标网段的，找到符合条件的然后作为setIp参数传进去，配置的时候区分开发环境下和k8s方式下ip前缀到不同profile里，可以兼顾开发和容器环境。

**Comment by llade** [comment]
或者仰仗作者做一个功能，把本机IPv4地址列表传到xxl-job-admin端（排除掉环回地址），服务器端用InetAddress.getByName(ipAddress).isReachable(timeOut)逐个判断IP是否可达或者判断执行器端口是否开放，但这样整个注册过程会比较耗时。

**Comment by llade** [comment]
```
public class IpUtils {

    public static List<String> getLocalIPList() {
        List<String> ipList = new ArrayList<String>();
        try {
            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
            NetworkInterface networkInterface;
            Enumeration<InetAddress> inetAddresses;
            InetAddress inetAddress;
            String ip;
            while (networkInterfaces.hasMoreElements()) {
                networkInterface = networkInterfaces.nextElement();
                inetAddresses = networkInterface.getInetAddresses();
                while (inetAddresses.hasMoreElements()) {
                    inetAddress = inetAddresses.nextElement();
                    if (inetAddress != null && inetAddress instanceof Inet4Address) { // IPV4
                        ip = inetAddress.getHostAddress();
                        ipList.add(ip);
                    }
                }
            }
        } catch (SocketException e) {
            e.printStackTrace();
        }
        return ipList;
    }

    public static String getIpStart(String ipStartWith){
        return getLocalIPList().stream().filter(c ->c.startsWith(ipStartWith)).findFirst().get();
    }
}
```

```
@Bean(initMethod = "start", destroyMethod = "destroy")
	public XxlJobSpringExecutor xxlJobExecutor() {
		log.info(">>>>>>>>>>> xxl-job config init.");
		XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
		xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
		xxlJobSpringExecutor.setAppName(appName);
		if(StringUtils.isNotBlank(ip)) {
			xxlJobSpringExecutor.setIp(ip);
		}else if(StringUtils.isNotBlank(ipStartWith)){
			String matchIp = IpUtils.getIpStart(ipStartWith);
			xxlJobSpringExecutor.setIp(matchIp);
		}
		xxlJobSpringExecutor.setPort(port);
		xxlJobSpringExecutor.setAccessToken(accessToken);
		xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

		return xxlJobSpringExecutor;
	}
```
```
xxl:
  job:
    executor:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      #ip:
      # 项目自定义参数，判断IP地址是否该网段，只有ip选项为空的时候，该选项才起作用
      ipStartWith: 192.168.0
```

**Comment by chenxd1991** [comment]
@llade 这种方式不行还是获取不到，获取到的ip还是容器的IP，IP列表为[172.***.***.**,127.0.0.1]

**Comment by llade** [comment]
只能获取到容器的IP，宿主机的IP没法获得，除非你是用https://blog.csdn.net/kozazyh/article/details/79463688

**Comment by chenxd1991** [comment]
好的 我试试。谢了 @llade

**Comment by zhurudong** [comment]
问题：服务器含多网卡无法注册正确IP问题。
描述：使用自动注册功能时，发现会注册上类似docker0、br-0f9fxx这类的网桥或虚拟网卡地址，这类地址并非真实地址。阿里dubbo框架中已做了部分优化，我这边看了xxl-job源码没有解决这个问题，希望作者能够升级版本解决。

添加如下判断：
NetworkInterface network = interfaces.nextElement();
if (network.isLoopback() || network.isVirtual() || !network.isUp()) {
continue;
}

参考：
https://dubbo.apache.org/zh-cn/blog/dubbo-network-interfaces.html

**Comment by chenxd1991** [comment]
@zhurudong 好的 谢谢提供思路。我研究一下

**Comment by chenxd1991** [comment]
@zhurudong  你的这个方式是指服务直接部署在虚拟机上面，而虚拟机存在多个网卡的情况时可以获取到正确的ip地址。但是我说的其实是服务部署在docker中，按照上面说的dubbo解决方式其实获取方式取到的ip还是docker容器的ip，而不是docker所在虚拟机的ip。

**Comment by zhurudong** [comment]
由于docker内部网络默认是bridge，是虚拟自己的一套网络。可以把网络模式改成直接使用宿主机network_mode: host

**Comment by xuxueli** [comment]
@zhurudong 你好，欢迎提供PR啊！

**Comment by zgfh** [comment]
我们是不是可以支持external_url,用户直接配置外部访问地址即可
比如docker部署的，通过-p暴漏主机端口后，把external_url设置成主机ip:主机端口即可
比如k8s部署的，设置成ingress的域名即可

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/708

**Comment by junneyang** [comment]
这个为什么要关闭这个问题呢

这个问题本质原因是设计的缺陷，为什么Master和Worker节点要设计成需要双向通信？
合理的设计是只需要Worker节点能连通Master节点就可以了
任务采用Worker主动PULL的方式，不应该Master接待PUSH下发到Worker节点

**Comment by AF-lmf** [comment]
> 这个为什么要关闭这个问题呢
> 
> 这个问题本质原因是设计的缺陷，为什么Master和Worker节点要设计成需要双向通信？
> 合理的设计是只需要Worker节点能连通Master节点就可以了
> 任务采用Worker主动PULL的方式，不应该Master接待PUSH下发到Worker节点

主动pull  有点类似于携程apollo 客户端获取配置的操作，通过DeferredResult实现长轮询。

**Comment by fly7632785** [comment]
@admlke 这里没有尝试过调整网卡顺序   不太好弄

**Comment by admlke** [comment]
@fly7632785 请问你是怎么解决这个问题的

**Comment by fly7632785** [comment]
@admlke 没解决  还是用的手动注册   所以来问这个问题

**Comment by xqlim** [comment]
这个问题最终还是没解决吧，有什么其他方案吗？

**Comment by lt-fancy** [comment]
> 这个为什么要关闭这个问题呢
> 
> 这个问题本质原因是设计的缺陷，为什么Master和Worker节点要设计成需要双向通信？ 合理的设计是只需要Worker节点能连通Master节点就可以了 任务采用Worker主动PULL的方式，不应该Master接待PUSH下发到Worker节点

作者的设计思路就是admin是作为调度中心来存在的，和executor解耦开来，admin下发任务执行指令到executor，executor收到指令直接去执行任务就行。而且大多数executor是直接集成在业务项目里，如果用executor来pull的话那就侵入业务了，因为业务方不关心我什么时候去执行任务，他只管去执行就行，什么时候执行是admin要负责的，到点了admin就下发指令给executor来执行任务

**Comment by caizi12** [comment]
双向通信设计上应该更简单一些，但对网络设置端口开放要求会多些。单向通信要求较低类似nacos这种。
