### ISSUE TITLE
xxl-job-admin should provider REST API

### ISSUE THREAD

**Issue by luxingxiao** [xuxueli/xxl-job#1125]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
xxl-job-admin should provider REST API
### Actual behavior
The web api is used for UI, can not be used to the other application.
### Other information

**Comment by amao12580** [comment]
+1

**Comment by xuxueli** [comment]
你好，已经在TODO排期中（双向Restful通讯）；

**Comment by caolist** [comment]
太好了！正需要这个！
