### ISSUE TITLE
有没有使用docker部署执行器服务的，自动注册IP是如何解决的？？？？

### ISSUE THREAD

**Issue by chenxd1991** [xuxueli/xxl-job#1128]
在docker部署执行器，由于没有指定IP导致自动注册到admin中的IP为docker自身的IP从而致使admin不能调用执行器服务。除了指定IP有没有其他的办法解决自动注册IP错误问题

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/1121
