### ISSUE TITLE
是否可以管理多集群任务

### ISSUE THREAD

**Issue by arthur-dy-lee** [xuxueli/xxl-job#1129]
比如说，我有2人region：regionA(济南集群)， regionB(北京集群)，我有一个管理软件管理他们，我想执行定时任务，在regionA和regionB各执行一次。
目前xxl-job是否可以满足？还是我需要修改源代码？
谢谢回复！！

**Comment by arthur-dy-lee** [comment]
如果没有这个功能，您有什么好的思路么？

**Comment by xuxueli** [comment]
你好，支持的。可以为每个Region单独配置一个执行器，每个执行器下配置任务即可。
