### ISSUE TITLE
建议: 构建Docker image希望把curl程序添加上

### ISSUE THREAD

**Issue by Hoastar** [xuxueli/xxl-job#1132]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Other information
无法使用原生的HEALTHCHECK，缺少curl命令。当然我自己可以重新构建，但我是希望在源头上或是比较早的镜像层去完成这个功能。

**Comment by xuxueli** [comment]
已支持。
