### ISSUE TITLE
获取定时任务，内存问题

### ISSUE THREAD

**Issue by SevenBlue2018** [xuxueli/xxl-job#1133]
通过阅读源码，我看到定时执行如下sql：
![image](https://user-images.githubusercontent.com/11767168/64515981-369a3200-d320-11e9-8f20-daec545f41f6.png)
如果当前平台中配置很多分钟级别的任务，表达式为0 0/1 * * * ？*，这样的话岂不是一次查询了很多节点进入到内存当中，此处是否存在问题呢？

**Comment by SevenBlue2018** [comment]
@xuxueli 有时间麻烦帮忙解释下

**Comment by TeslaCN** [comment]
“很多任务”的任务数量是个什么量级？

以现在的机器配置，一次装下几千、几万条记录一般不是问题；问题应该在与调度中心的是否调得过来。

我的理解，任务数量千级的话（假设当前10000个任务），要看这些任务触发时间在每分钟的分布情况，例如某一分钟内的第10秒有多少任务触发，第20秒有多少任务触发……

如果这些任务触发时间很集中，例如10000个任务集中在每分钟的第1秒触发，这时候调度中心的压力就很大了。

以上仅仅是个人理解，请指正批评，谢谢😂

**Comment by SevenBlue2018** [comment]
@TeslaCN 我就是这个意思，当任务相同表达式过多时，那么一次查询就会获取到所有的任务，内存岂不是存在者压力？

**Comment by TeslaCN** [comment]
@SevenBlue2018 如果任务数量达到一定量级确实是有压力。

我个人理解，这种压力关键在于DB锁的存在导致调度中心集群节点不能并行调度，每一刻只有一个调度中心节点查出临近调度时间的任务进行调度。

我有个应对**大量任务的调度时间相对集中**的情况的想法：  
* 去掉目前这个粗粒度的锁   
* 让任务通过一定路由规则路由到各个调度中心节点   

例如：
1. 维护一个 **调度中心在线节点列表**  
2. 对 **任务id** 或其他字段进行**哈希**  
3. 任务 **根据哈希值路由** 到调度中心节点   

以此实现各个调度中心并行调度任务。

**Comment by xuxueli** [comment]
你好，每次查询会限制查询数量，这个数量和调度中心线程数成正比，所以这里不会有内存问题。
