### ISSUE TITLE
不能实现数据库的重连

### ISSUE THREAD

**Issue by longkaimao** [xuxueli/xxl-job#1136]
xxl-job版本：2.1.0
问题描述：在Job正常运行的过程中，如果数据库服务器出现故障（或者网络超时），xxl-job抓狂一样的抛出异常信息，待数据库恢复正常后，xxl-job继续扔异常，而不会自动重连，后面的任务也不会再执行。此时，必须重启xxl-job，才能恢复正常。

**Comment by xuxueli** [comment]
你好，这个问题master分支已经优化，可以pull master体验。即将发布的v2.1.1会修复这个问题。
