### ISSUE TITLE
执行器执行了一半挂了

### ISSUE THREAD

**Issue by SevenBlue2018** [xuxueli/xxl-job#1137]
背景：
执行器每天8点执行一次，当前调度中心发送了触发请求成功后，执行器开始执行，结果执行到一半挂了，此时执行器存在其他可用节点。
问题：
经过测试发现，当前执行日志里显示的就是调度成功，没有执行结果，有执行日志和终止任务的按钮，此时该执行器节点已经挂掉，点击这两个按钮都没有任何作用。个人觉得是否调度中心应该提供一个机制，发现执行器挂掉后，补充未执行完的任务呢？

**Comment by xuxueli** [comment]
你好，调度中心提供了任务失败重试的策略，不过依赖执行器回调任务失败信号。
