### ISSUE TITLE
2.0.2版本发现有四个问题大家可以注意下，避免踩坑

### ISSUE THREAD

**Issue by celesky** [xuxueli/xxl-job#1140]
首先感谢作者~~~

然后是几个小问题，建议大家注意下~避免踩坑
1. 进入首页时后台的dashboard方法，统计任务总的比例查询是
SELECT count(1) FROM XXL_JOB_QRTZ_TRIGGER_LOG AS t 
SELECT count(1) FROM XXL_JOB_QRTZ_TRIGGER_LOG AS t WHERE t.handle_code = 200
运行一段时间后，这两个查询会很慢，我现在进入首页需要30秒，
- 我准备将这里改成异步后台统计查询，定时存入redis

2.调用任务的日志记录，
现在是记录的文本文件，一个任务，执行一次任务，就会写一个单独的文本文件。
我这服务器的inode已经爆了好几次了。
- 我已经将这里改成写数据库了

3.就是重复执行的问题，有时候一个任务在同一时刻会被两个节点分别执行一次，也就是加锁看起来是存在有问题，
- 这里问题还没查到，后面准备改成zookeeper实现

4.在日志模块，提供了清理日志功能，但是日志清理是这样清理的
delete from XXL_JOB_QRTZ_TRIGGER_LOG    WHERE  trigger_time  <=  ?
在大量日志数据的情况下，直接删数据mysql会爆出以下问题，导致锁表。
The total number of locks exceeds the lock table size
- 屏蔽这个清理功能，或者重新设计，可以建立分区表，只能根据分区维度去删

**Comment by arthur-dy-lee** [comment]
关于最后一个问题，你最好在Linux下安装个NTP同步下所有调度所有服务器的时间。不知道是不是时间不同步导致的。作者使用的是数据库悲观锁，应该没有问题的。

**Comment by celesky** [comment]
> 关于最后一个问题，你最好在Linux下安装个NTP同步下所有调度所有服务器的时间。不知道是不是时间不同步导致的。作者使用的是数据库悲观锁，应该没有问题的。

时间是一致的，检查了。
我怀疑是The total number of locks exceeds the lock table size ，这个原因导致的，不过还没有仔细查，只是看到了这个报错

**Comment by arthur-dy-lee** [comment]
试试修复策略呢？
调度密集或者耗时任务可能会导致任务阻塞，集群情况下调度组件小概率情况下会重复触发； 针对上述情况，可以通过结合 "单机路由策略（如：第一台、一致性哈希）" + "阻塞策略（如：单机串行、丢弃后续调度）" 来规避，最终避免任务重复执行。
上面一段是官网说明文档

**Comment by zhonghuwu** [comment]
3.就是重复执行的问题 
先确认下这个sql是走从库还是写库，如果走从库是有问题的 SELECT *
		FROM xxl_job_info AS t
		WHERE t.trigger_status = 1
			and t.trigger_next_time<  #{maxNextTime}

**Comment by zhonghuwu** [comment]
数据库使用了主从方式，还是只有写库：
SELECT *
FROM xxl_job_info AS t
WHERE t.trigger_status = 1
and t.trigger_next_time< #{maxNextTime}   @celesky

**Comment by seguzhizi** [comment]
楼主

> 首先感谢作者~~~
> 
> 然后是几个小问题，建议大家注意下~避免踩坑
> 
> 1. 进入首页时后台的dashboard方法，统计任务总的比例查询是
>    SELECT count(1) FROM XXL_JOB_QRTZ_TRIGGER_LOG AS t
>    SELECT count(1) FROM XXL_JOB_QRTZ_TRIGGER_LOG AS t WHERE t.handle_code = 200
>    运行一段时间后，这两个查询会很慢，我现在进入首页需要30秒，
> 
> * 我准备将这里改成异步后台统计查询，定时存入redis
> 
> 2.调用任务的日志记录，
> 现在是记录的文本文件，一个任务，执行一次任务，就会写一个单独的文本文件。
> 我这服务器的inode已经爆了好几次了。
> 
> * 我已经将这里改成写数据库了
> 
> 3.就是重复执行的问题，有时候一个任务在同一时刻会被两个节点分别执行一次，也就是加锁看起来是存在有问题，
> 
> * 这里问题还没查到，后面准备改成zookeeper实现
> 
> 4.在日志模块，提供了清理日志功能，但是日志清理是这样清理的
> delete from XXL_JOB_QRTZ_TRIGGER_LOG WHERE trigger_time <= ?
> 在大量日志数据的情况下，直接删数据mysql会爆出以下问题，导致锁表。
> The total number of locks exceeds the lock table size
> 
> * 屏蔽这个清理功能，或者重新设计，可以建立分区表，只能根据分区维度去删

题主，很不幸，你说的几个问题，我这边都遇到了。。。真的有点小尴尬。。。

**Comment by xuxueli** [comment]
感谢关注！
上述几个问题已经在排期处理。
1、dashboard实现会调整，会新增报表的表，定期同步日志到报表里，dashboard加载速度会更快。同时调度中心会提供日志表定期清理功能。
2、执行器小文件日志，目前已经提供了自动清理功能，可以设置保留时间，过期自动清理。
3、任务重复执行问题，确认调度中心集群和DB时钟是否一致。初次之外，可以结合阻塞策略+一致性哈希来解决重复执行问题。也可以借助分布式锁实现。
4、调度中心日志清理问题：会改为分页获取ID，根据ID删除的方式；

**Comment by xuxueli** [comment]
上述问题已经在最新版本优化和修复，可以体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
