### ISSUE TITLE
调度失败但是执行成功

### ISSUE THREAD

**Issue by chen-ABC** [xuxueli/xxl-job#1141]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
调度失败应该无法执行。行为不一致
### Actual behavior
偶发调度失败但是执行成功
![image](https://user-images.githubusercontent.com/30097790/64757012-5d947600-d563-11e9-87d8-2a50540b6f62.png)
调度异常信息：
![image](https://user-images.githubusercontent.com/30097790/64757082-8ae12400-d563-11e9-8f4d-063f599dd329.png)
但是最后执行脚本成功执行。
### Other information

**Comment by xuxueli** [comment]
你好，这种应该是调度请求没有及时得到响应导致，不影响。
