### ISSUE TITLE
data文件夹

### ISSUE THREAD

**Issue by initsword** [xuxueli/xxl-job#1143]
data文件夹内的脚本是不是可以定期清理，现在太大了，每两三个月就一两百G了，这样速度会非常慢，另外，时期是不是可以统统一一下，如果存在多个时期的机子就会调度混乱

**Comment by xuxueli** [comment]
你好，执行器日志支持配置过期时间的，比如设置3天，过期日志会自动清理的。

**Comment by initsword** [comment]
日志我已经设置成滚动的了，这个问题不大，现在主要是临时脚本太多，data文件夹经常几百G，我现在是使用定时任务去清理，后面是不是不需要的尽量清理掉
------------------
Alex Lai
              All from Small and Ended Big!&nbsp;                           Email:alex@laialex.com


                                            &nbsp;                           
                           
              
 


&nbsp;




------------------&nbsp;Original&nbsp;------------------
