### ISSUE TITLE
为什么一直报错

### ISSUE THREAD

**Issue by X-ration** [xuxueli/xxl-job#1144]
Admin项目一直报这个错误
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
这能执行成功吗

**Comment by xuxueli** [comment]
你好，这个问题master分支已经做了修复，可以PULL master体验下。

**Comment by Jesse-so-cool** [comment]
> 你好，这个问题master分支已经做了修复，可以PULL master体验下。

哪个分支解决的？老版本上线了很久 不好切换
