### ISSUE TITLE
1.9.2升级到2.1.0的方法

### ISSUE THREAD

**Issue by winwill2012** [xuxueli/xxl-job#1146]
原来使用的是1.9.2的版本，mysql表结构比较复杂，现在想升级到2.1.0，但是发现mysql表结构全部变了，原来还有几千个job在跑着，请问有没有平滑升级或者数据迁移的方案？

**Comment by liunancun** [comment]
TRUNCATE xxl_job_group;
INSERT INTO xxl_job_group
SELECT * FROM XXL_JOB_QRTZ_TRIGGER_GROUP;

TRUNCATE xxl_job_info;
INSERT INTO xxl_job_info (id,job_group,job_cron,job_desc,add_time,update_time,author,alarm_email,executor_route_strategy,executor_handler,executor_param,executor_block_strategy,executor_timeout,executor_fail_retry_count,glue_type,glue_source,glue_remark,glue_updatetime,child_jobid)
SELECT id,job_group,job_cron,job_desc,add_time,update_time,author,alarm_email,executor_route_strategy,executor_handler,executor_param,executor_block_strategy,executor_timeout,executor_fail_retry_count,glue_type,glue_source,glue_remark,glue_updatetime,child_jobid FROM XXL_JOB_QRTZ_TRIGGER_INFO;

TRUNCATE xxl_job_logglue;
INSERT INTO xxl_job_logglue
SELECT * FROM XXL_JOB_QRTZ_TRIGGER_LOGGLUE;

TRUNCATE xxl_job_registry;
INSERT INTO xxl_job_registry
SELECT * FROM XXL_JOB_QRTZ_TRIGGER_REGISTRY;

我是这样升级的

**Comment by winwill2012** [comment]
好的，感谢，我试试
