### ISSUE TITLE
分片广播策略下执行器节点出现宕机的情况

### ISSUE THREAD

**Issue by xuhaiaiyuxia** [xuxueli/xxl-job#1147]
目前准备用xxl-job的分片模式执行表数据的同步，正常情况下没有问题，但是模拟了宕机的情况，因为节点宕机，admin并不是第一时间把注册信息进行移除。导致传递过来的分片参数是不正确的（total不正确，把已经移除的节点也传递过来了），导致原本应该宕机节点执行的任务没有执行。同步的数据不完整。请问xxl-job对这种情况有什么好的解决办法。比如说。修改心跳检测时间，做到实时更新注册信息。或者分发分片任务的时候首先做一下心跳检测，将还存在于注册列表中，但是没有心跳回应的节点给踢出掉

**Comment by xuxueli** [comment]
你好，存在心跳检测，心跳过期节点会自动清理的，存在短暂时间延时。
而且，可以开启失败重试，失败的分片会自动重试。
