### ISSUE TITLE
分片广播模式下子任务的执行问题

### ISSUE THREAD

**Issue by xuhaiaiyuxia** [xuxueli/xxl-job#1148]
现在的需求是分片任务子节点全部执行结束之后再执行子任务（只执行一次），而不是现在的有几个节点就执行几次，请问应该如何实现

**Comment by LockiJiang** [comment]
同问，我也有相同的需求

**Comment by xuxueli** [comment]
合并至DAG流程任务：https://github.com/xuxueli/xxl-job/issues/172
