### ISSUE TITLE
为什么xxl-job admin无法自动感知任务

### ISSUE THREAD

**Issue by rockjing** [xuxueli/xxl-job#1149]
任务必须手工定义。
但是，为什么不能在定义任务的时候来选择过滤某类任务？
还是需要手工来填写？
这个功能应该是已经有了吧？

**Comment by xuxueli** [comment]
你好，“任务自动注册” 自动注册已经加入TODO排期。但是考虑到会导致注册任务信息在集群是变更频繁，暂时搁置。
