### ISSUE TITLE
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse

### ISSUE THREAD

**Issue by mifashion** [xuxueli/xxl-job#1153]
使用mast分支整个springboot启动报错
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse，求解！

**Comment by IntoTw** [comment]
我遇到过类似问题，我是调度的时候手动配置了地址，但是配置的地址服务没起，我调试看实际是底层返回了一个404，然后netty和hessian转换的时候就报了类似转换的错误

**Comment by komelio** [comment]
升级2.1.3版本就出这个问题

**Comment by mifashion** [comment]
> 升级2.1.0版本就出这个问题

但是好像并不影响程序运行

**Comment by felixzhang09** [comment]
![image](https://user-images.githubusercontent.com/29116883/67458377-a4987f80-f668-11e9-9c68-06ba1dc620e6.png)
原因是这个位置的地址或者端口号错误了

**Comment by felixzhang09** [comment]
2.1.0这个正确的话也会出现这个错误

**Comment by xuxueli** [comment]
你好，问题无法复现。请完成提供问题复现步骤。

**Comment by IntoTw** [comment]
这种netty底层的cast错误，都是执行器注册和心跳的时候与中心通信的时候，访问的端口等有误，导致返回的不是他底层rpc预期的报文导致的转换错误

**Comment by mifashion** [comment]
感谢各位，现已解决问题

**Comment by GdHuni** [comment]
怎么解决的a

**Comment by BazzJiang** [comment]
这种问题对社区简直没有意义，解决了又不贴出方案，搞锤子。

**Comment by freshgeek** [comment]
> 感谢各位，现已解决问题

怎么解决的？

**Comment by GalenKim** [comment]
是什么配置的问题吗，hello
