### ISSUE TITLE
xxl-job JobThread stoped

### ISSUE THREAD

**Issue by whyloverjack** [xuxueli/xxl-job#1154]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0
### Expected behavior
Job 执行完成后续可以持续
### Actual behavior
Job执行完成之后，提示：xxl-job JobThread stoped
### Steps to reproduce the behavior
1. 将Xxl-job-core 2.0.0版本集成到项目中，创建了一个继承IJobHandler的实现类，里面进行数据库查询并写入缓存操作；
2. 启动应用项目，启用Xxl-job-admin项目，并向xxl-job-admin注册应用名称及端口信息；
3. 首次运行之后，查看日志，
![image](https://user-images.githubusercontent.com/7007502/65305851-b04edd00-dbb6-11e9-9c5c-aa21b4c37a9b.png)
4. 查看Xxl-job-admin控制台日志：
com.xxl.rpc.util.XxlRpcException: com.xxl.rpc.util.XxlRpcException: xxl-rpc
### Other information

**Comment by xuxueli** [comment]
你好，从截图看应该是执行器停止了，没办法提供日志查询服务。
确认调度中心和执行器均正常启动。
