### ISSUE TITLE
运行任务 一片结果为空

### ISSUE THREAD

**Issue by huangyue4727603** [xuxueli/xxl-job#1155]
Please answer some questions before submitting your issue. Thanks!
![image](https://user-images.githubusercontent.com/8024730/65317853-28290180-dbcf-11e9-9d12-c19d033b5436.png)

执行器为windows  IDEA 运行
服务端为docker中运行

**Comment by huangyue4727603** [comment]
不管是Java IDE还是bean 都是这样的情况

**Comment by xuxueli** [comment]
你好，问题无法复现。可以debug查看下任务触发逻辑，是不是有异常报错。
