### ISSUE TITLE
心跳检测的时候会报错误com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74

### ISSUE THREAD

**Issue by snwing** [xuxueli/xxl-job#1157]
admin在执行每5s一次的心跳检测时会报com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74的错误,但是正常执行job任务却不会报错.求问是什么原因.版本:2.0.2
hessian版本已确定一致.版本4.0.60

**Comment by Realworldm** [comment]
我这边也出现这个异常了 你是怎么解决的

**Comment by snwing** [comment]
> 我这边也出现这个异常了 你是怎么解决的

时间长了有点忘记了~好像是版本的问题。client和server端的xxl版本不一致。改成一致就好了

**Comment by cxwangxixi** [comment]
这个问题怎么解决的，2.1.2版本也遇到这问题
