### ISSUE TITLE
我是来提建议的!

### ISSUE THREAD

**Issue by xiaojinzi123** [xuxueli/xxl-job#1158]
公司有多个环境, Dev, Demo, Testing, yufabu, Pro
从 Dev 到最后的 Pro, 其实配置都是一样的, 如果各个环境的 xxl-job 的版本都一致的话, 能否做一个 copy 配置的功能, 或者从某个环境同步一些配置到其他环境...我只是描述一下场景, 希望作者你能懂.
我只是觉得应该有这个功能, 作者你看下是否可以后续支持下.

**Comment by IntoTw** [comment]
配置主要就是在job_info和job_group还有job_user表里，你这三张表拷贝一下就行了

**Comment by xiaojinzi123** [comment]
> 配置主要就是在job_info和job_group还有job_user表里，你这三张表拷贝一下就行了

听上去可行耶
