### ISSUE TITLE
log is too many!

### ISSUE THREAD

**Issue by liulipengju** [xuxueli/xxl-job#1159]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB 2.1.1-SNAPSHOT
### Expected behavior

I want to store the log of valid execution. There is a xxl log save configuration in the execution JAVA code. If I judge that the current task does not need to execute the following code, I can ask the current task not to save the log file!

希望存储有效执行的日志，在执行JAVA代码里有一个xxl日志保存配置，如果我自己判断当前任务不需要执行后面的代码，我可以要求当前任务不保存日志文件！
![TIM截图20190924185148](https://user-images.githubusercontent.com/10510950/65505704-68082580-defc-11e9-80c7-78a0bd70d853.png)

### Other information

**Comment by liulipengju** [comment]
![image](https://user-images.githubusercontent.com/10510950/65506058-49eef500-defd-11e9-8da3-502d0b06a92f.png)

**Comment by xuxueli** [comment]
你好，执行器支持配置日志过期时间的，过期日志只会自动清理。

**Comment by SZMOFEI** [comment]
我也遇到了同样的问题
![){U(E SU5ZG 3QNEFY3O1](https://user-images.githubusercontent.com/29293262/131638563-ac9ad3ae-444c-40f5-b05d-54ba9f60ecd3.png)
为什么每个文件都不是特别大，但是文件数非常多呢？
我使用的版本是2.3.0版本。
配置了日志过期是10天
