### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by liaoxuewei** [xuxueli/xxl-job#1160]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

### Expected behavior
调度日志查询出来的列表希望增加【执行器】和【任务】名称显示，这样方便查阅

### Actual behavior
目前没有显示，只有作为筛选条件。

### Steps to reproduce the behavior
N/A

### Other information
N/A

**Comment by xuxueli** [comment]
你好，日志列目前数据太多，新增列数据展示不友好。如果有需要可以自己定制啊。
