### ISSUE TITLE
一个任务同一时间偶尔被调度两次

### ISSUE THREAD

**Issue by dailiuyang123** [xuxueli/xxl-job#1161]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
一个调度任务。 定时执行一次
### Actual behavior
结果，同时执行了两次
### Other information
 下面是 执行日志

**Comment by dailiuyang123** [comment]
![image](https://user-images.githubusercontent.com/31002194/65565318-29b54980-df82-11e9-9ebc-807be9a1849c.png)

**Comment by celesky** [comment]
是有这个问题的

**Comment by ezrio** [comment]
还是数据库锁的问题吧。分布式锁用sql如果集群环境还是会控制不住的。

**Comment by Luomeng1004** [comment]
确实有这个问题~有没有解决方案呢？

**Comment by zhonghuwu** [comment]
数据库主从不一致导致

**Comment by celesky** [comment]
我自己用redis锁 ，做二次控制，我已经明确的抓到了重复触发的日志，是两个节点分别触发的

**Comment by dailiuyang123** [comment]
> 我自己用redis锁 ，做二次控制，我已经明确的抓到了重复触发的日志，是两个节点分别触发的

所以解决方案是，用redis解决分布式锁的问题吗？可否提供一个demo

**Comment by zhonghuwu** [comment]
数据库使用了主从方式，还是只有写库

**Comment by zhonghuwu** [comment]
> 我自己用redis锁 ，做二次控制，我已经明确的抓到了重复触发的日志，是两个节点分别触发的

在数据库使用了主从方式，还是只有写库：
SELECT *
FROM xxl_job_info AS t
WHERE t.trigger_status = 1
and t.trigger_next_time< #{maxNextTime}

![Snip20191021_7](https://user-images.githubusercontent.com/3360558/67195143-04a1e280-f42b-11e9-8cfe-804fe71b52b3.png)

**Comment by xuxueli** [comment]
DB主从部署时，务必走主库，文档有说明。

该问题合并至：https://github.com/xuxueli/xxl-job/issues/370
