### ISSUE TITLE
spring版本

### ISSUE THREAD

**Issue by junbao611** [xuxueli/xxl-job#1164]
spring版本还是1.5.21，可否升个大版本

**Comment by NeilHao886** [comment]
同问。尝试过吧springboot换成最新办，然后失败了，公司不给时间研究，所以只能厚着脸皮来求方法

**Comment by weinianta** [comment]
![image](https://user-images.githubusercontent.com/13379708/67750517-50c3d700-fa6a-11e9-9f72-50bcc48ed919.png)

可以自行更换的，我已经更新。

**Comment by xuxueli** [comment]
预计在 v2.2.x 升级到springboot最新版，jdk升级到jdk8。可以稍等下。
紧急的话，可以咨询下 @weinianta  如何升级。

**Comment by wanzilong813** [comment]
fd-job-core 能支持 spring 3的版本吗
