### ISSUE TITLE
执行器重复执行失败任务

### ISSUE THREAD

**Issue by chenxd1991** [xuxueli/xxl-job#1165]
![企业微信截图_20190929151739](https://user-images.githubusercontent.com/48288147/65828359-9d31c080-e2cc-11e9-938d-be4ab4aef950.png)
![企业微信截图_20190929151804](https://user-images.githubusercontent.com/48288147/65828387-fa2d7680-e2cc-11e9-88fc-3ee69d11a26e.png)
![企业微信截图_20190929152528](https://user-images.githubusercontent.com/48288147/65828431-77f18200-e2cd-11e9-9d70-3076b5a0bb94.png)

任务状态为stop，手动执行。如果任务执行时失败，任务会重复执行。即使admin服务停止，执行器也会执行，必须手动在日志列表点击结束任务。 @xuxueli 如何避免这种情况

**Comment by xuxueli** [comment]
你好，可以检查下任务执行备注，确认触发的来源。
手动执行重复执行，问题无法复现，需要完整提供复现步骤。
