### ISSUE TITLE
改成oracle后 

### ISSUE THREAD

**Issue by JiangSanQi** [xuxueli/xxl-job#1167]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by JiangSanQi** [comment]
改成oracle后quartz报这个错，一直都是标识符过长
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/23250192/65830284-ac226e00-e2e0-11e9-8592-648eb41089ad.png">

**Comment by key23383** [comment]
解决了吗，oracle可以使用吗，我也打算在oracle上尝试
