### ISSUE TITLE
数据库换成oracle一直报标识符过长

### ISSUE THREAD

**Issue by JiangSanQi** [xuxueli/xxl-job#1168]
数据库换成oracle后quartz一直报标识符过长
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/23250192/65830311-e25fed80-e2e0-11e9-9049-cb2530a47422.png">

**Comment by aaafenghao** [comment]
我也出现了这个问题
发现是这个表名过长了
![image](https://user-images.githubusercontent.com/19221610/67203029-a251dd80-f43c-11e9-940d-8478d647f0b9.png)
不知道如何解决

**Comment by aaafenghao** [comment]
解决了，使用quartz做了数据保存，缩小了一下表名前缀，唉！

**Comment by xuxueli** [comment]
你好，最新版本已经移除了quartz，表数量精简一半，表名也做了优化。
不会有你这个问题，可以升级体验下。
