### ISSUE TITLE
如果我想把某些耗时较长的异步Http调用加入到xxl-job的队列中如何处理

### ISSUE THREAD

**Issue by yosaku01** [xuxueli/xxl-job#117]
是否需要在xxl-job中定制相应的JobHandler？
是否有一个Rest接口，直接支持像这样的Http异步调用请求？

**Comment by xuxueli** [comment]
你好，感谢关注啊！
针对这种场景我建议如下：
1、新建一个任务，Jobhandler即处理每个http耗时调用的逻辑。
2、通过任务参数，接收http调用的URL参数和参数信息，自己处理好数据的定义封装和解析。
3、在调度中心APIController中，开放触发任务调度的API服务。
4、业务方需要处理上述需求场景时，调用步骤3中的API服务进行异步处理。

**Comment by yosaku01** [comment]
谢谢，我试一下
