### ISSUE TITLE
时区支持

### ISSUE THREAD

**Issue by crossoverJie** [xuxueli/xxl-job#1171]
目前版本 `XXL_JOB` 并不支持时区选择，如果是跨地区服务时使用起来会比较难受（甚至每个地区要部署一套）。

基于 `2.1.1-SNAPSHOT` 版本我们定制了多时区功能，只需要部署一套环境便可支持 N 个时区；经过一段时间线上运行已经趋于稳定。

如果社区需要，可以将这部分功能移植过来。

![image](https://user-images.githubusercontent.com/15684156/66408624-dcc18080-ea21-11e9-97ba-77429f5a06eb.png)

```properties
# 时区配置
tz.value=[{"name":"Australia/Sydney","zhName":"堪培拉,墨尔本,悉尼(UTC+10:00)"},{"name":"Asia/Shanghai","zhName":"北京,重庆,香港特别行政区,乌鲁木齐(UTC+08:00)"},{"name":"Asia/Tokyo","zhName":"大阪,札幌,东京(UTC+09:00)"}]
```

**Comment by traceless0929** [comment]
我觉得很需要

**Comment by rockRust** [comment]
很有用，美国有冬令时和夏令时，昨天正好是切换的日子，我手动将所有涉及美国的自动任务往后推迟了一个小时。

**Comment by xuxueli** [comment]
赞！可以在这里分享下：https://github.com/xuxueli/xxl-job/issues/154
或者可以尝试PR。

**Comment by mozaiquan** [comment]
请问支持时区的cron触发哪个版本里有呢？

**Comment by c2498168786** [comment]
> 请问支持时区的cron触发哪个版本里有呢？

同问

**Comment by Yuqingmu** [comment]
> 请问支持时区的cron触发哪个版本里有呢？

同问哪个版本有呢?

**Comment by Jun10ng** [comment]
@crossoverJie 跪求

**Comment by RongieZeng** [comment]
我这边基于2.3.1增加了单任务多时区调度支持，有需要的同学可以参考一下：
https://github.com/RongieZeng/xxl-job

![image](https://user-images.githubusercontent.com/1302662/176063452-fb0162e9-fbcf-4c5d-a645-d1a502ce4688.png)
![image](https://user-images.githubusercontent.com/1302662/176063561-b908871b-f8d1-43fc-b44b-434976148f79.png)

**Comment by Elva2022** [comment]
> 

请问这个合并到官方版本了吗？
