### ISSUE TITLE
查询执行日志

### ISSUE THREAD

**Issue by Yinpeng1** [xuxueli/xxl-job#1175]
2.1.1-SNAPSHOT  查询日志有问题 
![image](https://user-images.githubusercontent.com/29558439/66557840-25457f00-eb85-11e9-924b-ed871e8b5511.png)
![image](https://user-images.githubusercontent.com/29558439/66557858-2d052380-eb85-11e9-84be-bae9e748af83.png)

**Comment by niocoder** [comment]
需在待启用的API服务上添加 “@PermessionLimit(limit = false)” 注解取消登陆态拦截

**Comment by xuxueli** [comment]
从界面看，应该是登陆失效了，可以重新登录下。
