### ISSUE TITLE
是否支持同一任务的唯一调度

### ISSUE THREAD

**Issue by RoonyLi** [xuxueli/xxl-job#1177]
假设任务A的调度周期是3s一次，执行时间不定，可能是3s以上。可否实现调度时判断任务A是否正在执行，如果正在执行，则不进行调度。下一个周期再调度。

**Comment by xuxueli** [comment]
你好，这种是任务阻塞场景，默认已经提供了阻塞策略的，提供的策略可以满足你的需求（丢弃后续调度策略）。

**Comment by RoonyLi** [comment]
好的，我学习下。

**Comment by RoonyLi** [comment]
@xuxueli
