### ISSUE TITLE
期待依赖功能

### ISSUE THREAD

**Issue by lysvanilla** [xuxueli/xxl-job#118]
如A、B、C三个任务，A和B是C的前置任务，当A和B都完成时，自动触发C

**Comment by xuxueli** [comment]
你好，感谢关注！
流程任务已经加入TODO列表，后续会排期跟进哈。目前还没有一个轻量级的解决方案，如果有好的方案欢迎交流啊：）

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
