### ISSUE TITLE
在数据库宕机情况下，执行器执行回调失败问题

### ISSUE THREAD

**Issue by charbus** [xuxueli/xxl-job#1180]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v1.9.1
### Expected behavior
执行器执行完成回调会修改任务执行结果状态。
### Actual behavior
在数据库宕机情况下，回调失败，任务状态一直处于执行中的状态，即使数据库恢复正常。
### Steps to reproduce the behavior
1、任务正常调度
2、数据库宕机一段时间
3、恢复数据库
4、宕机的时间段任务运行的状态回写不成功，即使任务执行正常。
### Other information
后台执行器报错：超时

**Comment by xuxueli** [comment]
你好，目前数据库是最基础的依赖，一定要保障数据库稳定，宕机没有降级方案。
