### ISSUE TITLE
调度平台页面按钮失效

### ISSUE THREAD

**Issue by yangyang122** [xuxueli/xxl-job#1182]
在xxl-job 版本2.1.0中，调度平台任务管理页面，操作下拉按钮，偶尔失灵.

**Comment by xuxueli** [comment]
你好，无法复现，请提供复现的操作步骤重新提交。

**Comment by yangyang122** [comment]
复现的步骤：firefox浏览器，点击操作后的下拉箭头，点击前面“操作“的字样.，反复的两者点击,就会重复出现。
