### ISSUE TITLE
CRON任务执行丢失的问题

### ISSUE THREAD

**Issue by hahajingnt** [xuxueli/xxl-job#1188]
Please answer some questions before submitting your issue. Thanks!

### 2.0.2版本
比如任务执行10分钟一次，有时候不稳定，会出现丢失的情况，任务执行都是成功的。

**Comment by xuxueli** [comment]
你好，这个版本底层依赖quartz驱动，问题需要反馈至quartz社区。不过，高版本（v2.1.0之后）已经移除了quartz，采用自研触发组件，应该大大缓解了上述问题。
