### ISSUE TITLE
v2.1.0在轮询修改任务下次执行时间时报空指针异常

### ISSUE THREAD

**Issue by hexy1989** [xuxueli/xxl-job#1189]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 version : v2.1.0

### Expected behavior
![image](https://user-images.githubusercontent.com/22510469/66982389-8d95e280-f0e8-11e9-87ec-910b2d5db893.png)
这里会报空指针。
当你的任务执行到最后一次的时候，xxl-job在轮询修改下次执行时间时，会报空指针异常，导致所有任务都不能正常执行。

### Actual behavior
![image](https://user-images.githubusercontent.com/22510469/66982489-c9c94300-f0e8-11e9-973b-7e3788285644.png)
目前我已经使用该方法临时修复。
### Steps to reproduce the behavior
想要复现，就建一个只执行一次，或者有终点的任务即可。
### Other information
希望作者可以在下一个版本修复，谢谢！

**Comment by xuxueli** [comment]
你好，这个问题在master分支已经修复，可以pull master体验下。将在下个版本修复发版。
