### ISSUE TITLE
executor注册到admin时不支持域名访问

### ISSUE THREAD

**Issue by lyfZhixing** [xuxueli/xxl-job#1190]
executor注册到admin时不支持域名访问,集成进spring cloud
admin在eureka注册的域名（服务名）为：xxl-job-admin
在executor进行如下配置
xxl:
    job:
      admin:
        address: http://xxl-job-admin/xxl-job-admin

### Which version of XXL-JOB do you using?
version： 2.1.1-SNAPSHOT
### Expected behavior
executor可以正确注册到xxl-job-admin
### Actual behavior
无法解析xxl-job-admin
### Other information
spring cloud version: Greenwich.RELEASE

**Comment by RoonyLi** [comment]
注册过程是用http自己调用的，没有走feign，所以没法解析eureka的服务名。

**Comment by xuxueli** [comment]
你好，调度中心建议分配真实域名。
