### ISSUE TITLE
试了下docker镜像, 不能直接运行...

### ISSUE THREAD

**Issue by SealinRepo** [xuxueli/xxl-job#1194]
我看文档写的Docker拿下来可以直接运行, 配置自定义数据源只是可选项,但是我运行的时候出现了Mysql相关的错误, 是需要搞个localhost:3306的Mysql服务给容器用么?要是有数据库之类的依赖能提供个compose就好了, 解放双手哈哈.

**Comment by xuxueli** [comment]
你好，目前需要提前准备一个mysql实例才可以，这样也是想尽量提高docker镜像的通用性。
如果镜像内部完整集成mysql，其实也可以，但是这样调度中心做集群就不太方便了啊。
