### ISSUE TITLE
master分支，cron表达式填写bug

### ISSUE THREAD

**Issue by Kangkeizai** [xuxueli/xxl-job#1195]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
master-10月22日
新增任务，cron表达式填完之后，再去填写别的选项，cron表达式输入会自动清空

**Comment by traceless0929** [comment]
同样发现这个问题，
另外，cron框现在自己直接填写表达式再保存是无效的

**Comment by xuxueli** [comment]
@Kangkeizai @traceless0929 感谢反馈！

Cron可视化插件是基于一个开源库做的，目前有一些前端兼容性问题在解决中。欢迎各路前端高手前来帮忙解决啊！

**Comment by traceless0929** [comment]
另外，有些cron是合法的但是校验为不合法导致填写失败
比如
0 10/40 22 ? * 1
@xuxueli

**Comment by xuxueli** [comment]
@Kangkeizai @traceless0929 @JiYou @crazystone  上述问题已经修复，并推送master分支。大家可以pull master体验下啊。
