### ISSUE TITLE
cron定时偶现失效

### ISSUE THREAD

**Issue by wJ-noName** [xuxueli/xxl-job#1198]
您好:
      就前几个月引用了您的定时框架,具体版本不太清楚了.  
      出现的问题是,偶发性的定时任务没有触发,后因cron不合规全部stop
      cron格式例如:36 51 03 23 10 ? 2019.
      查看日志,在03:51前后时间段,任务调用是正常的. 
      这种情况会在随机时间发生,想知道是这种情况是调度器触发的问题,还是服务器网络的问题.

**Comment by xuxueli** [comment]
你好，需要提供完善的复现条件，包括版本号，任务量，任务配置等等。现有信息无法复现问题。

**Comment by TeslaCN** [comment]
2.1.0版本，类似楼上的一次性cron表达式，偶发性没有调度，难以重现
状态为Running，trigger_next_time也没有更新，过了一会后任务被当作过期任务处理了

**Comment by xuxueli** [comment]
模拟了上述任务配置，任务无法复现。
需要完整提供问题复现步骤。
