### ISSUE TITLE
xxl-job配置文件支持application.yml

### ISSUE THREAD

**Issue by noseparte** [xuxueli/xxl-job#1199]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
xxl-job配置文件可以支持application.yml
### Actual behavior
xxl-job配置文件仅支持application.properties
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/30165939/67379572-b3752880-f5bb-11e9-81e0-80221bfc1279.png)
![image](https://user-images.githubusercontent.com/30165939/67379627-c7208f00-f5bb-11e9-8957-c9b202498e03.png)
![image](https://user-images.githubusercontent.com/30165939/67379707-d3a4e780-f5bb-11e9-8d96-23440b4520e7.png)
### Other information
想通过yml文件加载配置项，提供支持。

**Comment by hb407033** [comment]
应该是吧支持的吧， yml是Spring 配置文件默认支持的类型，实际在我部署的时候用的也是yml格式

**Comment by noseparte** [comment]
嗯，该问题已经解决。是我没理解到admin与executor的关系。
还有一个问题，如果是动态传参的方式支持吗？

**Comment by hb407033** [comment]
@noseparte 是用程序动态调用任务时传参吗？

**Comment by xuxueli** [comment]
@noseparte 你好，支持的，提供了API服务动态触发任务并传参，可以参考文档。
