### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by w-alun** [xuxueli/xxl-job#1201]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
当有两个执行器的时候，如果一个正在执行一个任务，且正在执行的这个任务的执行器崩掉，会出现
![image](https://user-images.githubusercontent.com/43000905/67387438-7021b680-f5c9-11e9-90ac-c48a0d6ff2d0.png)
调度中心会出现这样的错误。

既然是分布式，这样的容错机制有点低啊。
既然有心跳检测机制，如果某台执行器崩掉，可以对那台执行器上正在执行的任务进行转移啊。

### Other information

**Comment by xuxueli** [comment]
你好，可以对任务启用 “故障转移” 策略，任务触发时会自动检测执行器状态。
