### ISSUE TITLE
任务执行成功后报错

### ISSUE THREAD

**Issue by RengYuXuan** [xuxueli/xxl-job#1206]
Please answer some questions before submitting your issue. Thanks!

### Expected behavior
![S4}ZY6%3LKR7F832)Z7 37](https://user-images.githubusercontent.com/48005679/67477375-88a6d500-f68c-11e9-8f75-d7b09063973e.png)

### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。而且，从日志看应该做了二次开发，需要针对官方版本提供稳定复现步骤后才能介入问题排查。

**Comment by RengYuXuan** [comment]
您好，非常感谢您的xxl-job，问题已经解决了，是因为我执行器这边的连接池的问题。



---原始邮件---
发件人: "许雪里"<notifications@github.com&gt;
发送时间: 2019年10月25日(星期五) 中午11:20
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"RengYuXuan"<1720404911@qq.com&gt;;
主题: Re: [xuxueli/xxl-job] 任务执行成功后报错 (#1206)



你好，问题无法复现，需要进一步提供复现步骤。而且，从日志看应该做了二次开发，需要针对官方版本提供稳定复现步骤后才能介入问题排查。
