### ISSUE TITLE
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout

### ISSUE THREAD

**Issue by mugbya** [xuxueli/xxl-job#1213]
看到很多人都有这个错误，看到有些人描述为偶发性错误，从表征上看是这样的，运行了这么久，也只是出现了两次，下面是详细报错

版本： 2.0.2 

![](https://img.vim-cn.com/8f/5459125992ea1a1afac6de5fbc96459240ea76.png)
![](https://img.vim-cn.com/51/3768d750474d919fb7a3c946893ad00a418a12.png)

其实任务是调度成功的，我实际业务也被执行了，但是远程调用却认为超时了，这个问题不容易复线，所以只有雪里大佬自己搭建个环境一直监控下

> 这个偶发问题我是在开发环境发生过，在生产环境还未发生过

**Comment by xuxueli** [comment]
底层通讯超时3s，网络状况不佳时会发生请求发送到服务方，但是服务方响应数据丢失的情况。这种情况网络正常是不会出现。

**Comment by SincerelyUnique** [comment]
@mugbya 请问下这种情况你们是怎么处理的呢？我这边每天0点准时报一大堆这种log
