### ISSUE TITLE
数据库宕机，错误日志瞬间撑爆服务器内存

### ISSUE THREAD

**Issue by six-oclock** [xuxueli/xxl-job#1216]
因为xxl-job连接的数据库宕机，tomcat线程持续快速输出错误日志，几分钟就用了十几个G

### Other information

**Comment by six-oclock** [comment]
修改tomcat线程连接的配置参数

**Comment by xuxueli** [comment]
你好，这是数据库异常带来的系统日志，并非XXLJOB的日志。可以通过压缩日志等方法优化解决。
