### ISSUE TITLE
执行器管理 -> 自动注册方式 希望添加排序功能

### ISSUE THREAD

**Issue by weinianta** [xuxueli/xxl-job#1218]
目前因为部署多个节点，并且有的节点有ip限制，所以得指定第一个调用，或者最后一个调用。

因为自动注册方式，无法指定节点顺序，我现在已经改为手动注册，并排列好节点ip。

希望作者在后续版本中考虑下，非常感谢

**Comment by ioiioo** [comment]
节点有ip限制 为何要成为执行节点呢?这种安排并不合理．
１．每个执行器应是对等的，他们都有干活的资质，没有干活的资质就不要参于
２．是否可以考虑定时任务的模块与业务交付的模块完全分开，定时任务模块仅用于执行这些离线任务．

**Comment by weinianta** [comment]
因为很多都是没有ip限制的，只有oneLink v2版本的接口有。
但是又不想部署太多调度中心，希望用统一的调度。


所以我目前的解决办法就是


1、注册方式改为手动，这样就能有执行器顺序了
2、把有ip绑定的放到第一个执行器，然后在任务调度的时候就选第一个。
3、其余没有ip绑定的接口，就随机方式 或者轮询方式了


只是个建议，如果采纳的话会更好。祝好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ioiioo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午3:08
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"杨康"<851161583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 执行器管理 -&gt; 自动注册方式 希望添加排序功能 (#1218)




节点有ip限制 为何要成为执行节点呢?这种安排并不合理．
 １．每个执行器应是对等的，他们都有干活的资质，没有干活的资质就不要参于
 ２．是否可以考虑定时任务的模块与业务交付的模块完全分开，定时任务模块仅用于执行这些离线任务．

**Comment by xuxueli** [comment]
“有的节点有ip限制” ，这种节点，禁止进行执行器注册，是不是可以解决问题？
@weinianta
