### ISSUE TITLE
另外，有些cron是合法的但是校验为不合法导致填写失败

### ISSUE THREAD

**Issue by liweixing1995** [xuxueli/xxl-job#1225]
另外，有些cron是合法的但是校验为不合法导致填写失败
比如
0 10/40 22 ? * 1
@xuxueli

_Originally posted by @traceless0929 in https://github.com/xuxueli/xxl-job/issues/1195#issuecomment-545372820_

**Comment by liweixing1995** [comment]
![image](https://user-images.githubusercontent.com/34293510/67842273-d14f0a00-fb34-11e9-8e6b-97f25cc00a06.png)

**Comment by sundylgz** [comment]
这个功能确实是需要的

**Comment by sundylgz** [comment]
这个功能确实是需要的

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/1195
