### ISSUE TITLE
提个日志建议

### ISSUE THREAD

**Issue by petma** [xuxueli/xxl-job#1227]
XxlJobFileAppender
建议修改
makeLogFileName方法中
	.concat(logId)
为.concat(sdf.format(triggerDate))
以解决每天生成十几万个日志文件的问题

**Comment by xuxueli** [comment]
你好，拆分文件为了隔离不同任务的日志。如果复用同一个文件，日志没办法单独查看。

执行器支持设置日志自动清理的，过期日志自动删除。
