### ISSUE TITLE
官方文档挂了

### ISSUE THREAD

**Issue by liaolunhui** [xuxueli/xxl-job#1228]
![image](https://user-images.githubusercontent.com/13741751/67917355-aff12b00-fbd3-11e9-9c7f-852d15136ce1.png)

**Comment by flyingbluesnow** [comment]
文档域名：raw.githubusercontent.com  国内估计被墙了，麻烦换一个文档地址

**Comment by xuxueli** [comment]
@flyingbluesnow 确实是这个问题，已经更换托管方式了。
