### ISSUE TITLE
打包部署启动报错

### ISSUE THREAD

**Issue by lixianyang1987** [xuxueli/xxl-job#1229]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
最新版
### Expected behavior
在Jenkins中拉取代码打包部署
### Actual behavior
实际打包成功了，部署也成功了，但是启动时有一个类加载失败了，在windows下打包不会有问题
![image](https://user-images.githubusercontent.com/15976202/67918018-c304fa80-fbd5-11e9-893d-a82b2af55b3d.png)

### Steps to reproduce the behavior
谢谢
### Other information

**Comment by xuxueli** [comment]
你好，可以重新 pull master体验下。是低版本Bean初始化的一个问题。
