### ISSUE TITLE
1.8.0 建议反馈

### ISSUE THREAD

**Issue by it-noob** [xuxueli/xxl-job#123]
在重写JobGroupController获取执行器列表时，之前1.7.2的时候判断获取的执行器列表里会对注册列表分别判断而1.8.0删掉了对应的判断逻辑代码，如果下线，返回的注册列表为null，但是有于freemaker缓存的问题，虽然设置了缓存时间为0，仍然会有立即停止掉其中一个执行器，导致在线状态未及时更新，是否为bug，或者执行器在线装填显示页面的数据可以不及时。
新版本代码为：

`public String index(Model model) {

		// job group (executor)
		List<XxlJobGroup> list = xxlJobGroupDao.findAll();

		model.addAttribute("list", list);
		return "jobgroup/jobgroup.index";
	}`

旧版本代码为：
`public String index(Model model) {

		// job group (executor)
		List<XxlJobGroup> list = xxlJobGroupDao.findAll();

		if (CollectionUtils.isNotEmpty(list)) {
			for (XxlJobGroup group: list) {
				List<String> registryList = null;
				if (group.getAddressType() == 0) {
					registryList = JobRegistryMonitorHelper.discover(RegistryConfig.RegistType.EXECUTOR.name(), group.getAppName());
				} else {
					if (StringUtils.isNotBlank(group.getAddressList())) {
						registryList = Arrays.asList(group.getAddressList().split(","));
					}
				}
				group.setRegistryList(registryList);
			}
		}

		model.addAttribute("list", list);
		return "jobgroup/jobgroup.index";
	}`

**Comment by xuxueli** [comment]
你好，新版本1.8.0在JobRegistryMonitorHelper中会把自动注册的地址，周期性同步到对应的表字段中，因此不需要从JobRegistryMonitorHelper缓存中同步，老版本的逻辑去掉是正常的。
之所以在线机器同步不及时，是因为调度中心检测在线机器是周期性的，周期之间存在时间间隔。需要等待下次检测周期到达时才会刷新最新机器列表。
