### ISSUE TITLE
同步调度时，为什么Netty设置是SO_KEEPALIVE？

### ISSUE THREAD

**Issue by duofu** [xuxueli/xxl-job#1231]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB-2.0.2

### Actual behavior
Job调度请求对应的服务，网络常常不稳定、频频宕机，引发Admin和Executor大量的超时错误，甚至超出Linux句柄上限（Socket文件打开过多）

### Other information
构建启动类Bootstrap，设置ChannelConfig时，为什么不设置超时时间？为什么使用SO_KEEPALIVE？
![微信截图_20191031195308](https://user-images.githubusercontent.com/8102301/67946043-5f052500-fc1b-11e9-9baf-6335419edb8e.png)

**Comment by xuxueli** [comment]
你好，这个问题应该是没有多idel检测导致，新版本xxl-rpc已经尝试优化，可以升级体验。或者对xxl-rpc提交PR处理这个问题：https://github.com/xuxueli/xxl-rpc/blob/master/xxl-rpc-core/src/main/java/com/xxl/rpc/remoting/net/impl/netty_http/client/NettyHttpConnectClient.java
