### ISSUE TITLE
一个jobHandler任务能否支持多个cron表达式

### ISSUE THREAD

**Issue by zhuweijunz** [xuxueli/xxl-job#1233]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
有两个频率不一样的cron表达式需要执行同一个jobHandler任务，
请问一个jobHandler任务能否支持多个cron表达式，还是只能新建两个jobHandler任务
### Other information

**Comment by xuxueli** [comment]
你好，不支持，需要新建两个任务指向同一个jobHandler。
