### ISSUE TITLE
关于xxl-job的性能

### ISSUE THREAD

**Issue by yangBin666** [xuxueli/xxl-job#1234]
### 版本 2.1.0
以单个admin端为例(4核，16g)，能支持多少个任务，假设每个任务都是每小时执行一次；
如果有耗时的任务，单个任务执行耗时30分钟以上，单个admin能支持多少个耗时任务并发调用？

**Comment by xuxueli** [comment]
你好，支撑任务量和任务耗时没有关系，任务都是异步触发运行的。
如上配置单机5000理论值。
