### ISSUE TITLE
回调出现大量超时，多次尝试才成功

### ISSUE THREAD

**Issue by tidapeng** [xuxueli/xxl-job#1235]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.0
### Expected behavior
回调一次成功
### Actual behavior
回调大量超时
### Steps to reproduce the behavior
调度器和执行器均是集群部署的，执行器回调地址配置了调度器列表，而非调度器集群地址(是否允许只配置一个集群地址)。
### Other information
![image](https://user-images.githubusercontent.com/21035518/68065049-7993e700-fd5e-11e9-9988-6830d21c7585.png)

**Comment by xuxueli** [comment]
你好，确认回调地址是否正确。
