### ISSUE TITLE
shell脚本执行成功，且使用了exit 0  但是始终无法结束

### ISSUE THREAD

**Issue by wendao8469759** [xuxueli/xxl-job#1238]
如题
脚本为
pid=0
pids=$(ps -ef|grep redis-cli |grep -v grep |grep -v 'Watchdog' | awk '{print $2}' )
for pid2 in ${pids};do
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>redis-cli进程存活>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    pid=${pid2};
    echo "redis-cli 读取PID为：pid ${pid2}"
done

#判断PID是否存在
PID_EXIST=`ps aux | awk '{print $2}'| grep -w ${pid}`
echo "PID_EXIST ${PID_EXIST}"
if [ ! ${PID_EXIST} ];then
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>redis-cli进程不存在,启动进程>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        /home/redis/redis-5.0.5/src/redis-cli   monitor | grep '\[1'  >> /opt/logs/redis/nohup.out  2>&1 &
        exit 0
else
        echo -e "进程信息为：" 
        echo -e `ps -ef|grep ${pid}` "\n"
fi
echo "Good bye!"
exit 0

如果走IF 则执行无法结束

**Comment by xuxueli** [comment]
你好，需要确认脚本是否走到了 exit 0 并结束。
