### ISSUE TITLE
Xxl-Job v1.8.0 SpringBoot适配完成！

### ISSUE THREAD

**Issue by antergone** [xuxueli/xxl-job#124]
spring boot版本（https://github.com/Antergone/xxl-job/tree/v1.8.0 ）我那边分支跟到了xxl原版的v1.8.0。大家有兴趣的可以拉下来研究和使用，发现问题可以在群里at我或者issue。
Master分支跟踪到了原版广播分片和dao优化(7926be5）后面协议变更部分未跟踪
再次对 @xuxueli  的开源付出表示感谢~

**Comment by edgelone** [comment]
@Antergone @xuxueli 这版是不是有点小问题,在查看日志界面 一直显示处理中,后台未收到任何请求,无法搜索日志

**Comment by Antergone** [comment]
@edgelone  fixed

**Comment by edgelone** [comment]
@Antergone  哪个bug fix了?   是那个故障转移 策略的?  还是这个日志查询的?

**Comment by ZouDaYi** [comment]
@Antergone  我对你修改的xxlSpringBoot版本很感兴趣，但是我部署完成之后，测试执行器执行任务的时候，任务未能成功执行，日志显示：调度失败：执行器路由策略为空   但是再配置任务的时候已经选择了路由策略：第一个。

**Comment by aola** [comment]
你好，我下载了你的https://github.com/Antergone/xxl-job/tree/v1.8.0 但是没法调度成功啊，执行器那边日志 runJob success, jobKey:1.2  但是job没执行方法。感觉是job没被注册。求解啊，给个交流群方式吧

**Comment by James-TT** [comment]
@Antergone  你好，你改的版本 是没有实现 失败重试的策略吗

**Comment by xuxueli** [comment]
v2.0.0 已经推送发布，原生提供 springboot 版本调度中心。欢迎体验反馈！
