### ISSUE TITLE
xxl-job-admin任务管理编辑任务的cron插件有问题

### ISSUE THREAD

**Issue by flyingbluesnow** [xuxueli/xxl-job#1242]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job  2.1.1-SNAPSHOT
chrome: 78.0.3904.87
jdk1.8.0_111

### Actual behavior
选择完成cron表达式后发现默认的cron只有6位，测试发现是每秒调度一次，怎么用插件修改都不行，后面网上粘贴了7位的cron表达式，瞬间好了，所以页面上的这个cron编辑插件有问题，选择后的cron表达式只有6位

**Comment by xuxueli** [comment]
你好，该插件正在调试中。目前已经稳定，可以体验下。
