### ISSUE TITLE
SQL优化：XxlJobLog中findFailJobLogIds方法，建议增加触发时间范围，日志增多之后频繁全表扫描，增大DB压力

### ISSUE THREAD

**Issue by duanzhenxing** [xuxueli/xxl-job#1246]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Other information

**Comment by xuxueli** [comment]
已经添加分页条件作了优化。

**Comment by zsbtqb** [comment]
@xuxueli 加分页只是对结果集分页吧，但是查询过程还是会对全表扫描，所以是不是应该增加时间范围

**Comment by fjw666-py** [comment]
@zsbtqb 如果是半天前触发的，你这样就没用了呀。

**Comment by zsbtqb** [comment]
> @zsbtqb 如果是半天前触发的，你这样就没用了呀。

1、目的是要减少处理的数据集，一小时只是个举例，如果认为大部分任务执行时间需要再一天执行完，可以调整为一天。
2、这样做的目的是状态字段区分度太低，不适合做索引字段，时间字段区分度高，能快速的检索到有效数据

-----------------------
或者这里对失败任务的检测能否转化为异步消息处理，不再全局扫描任务
