### ISSUE TITLE
任务里面起多个线程执行业务逻辑，并且设置超时停止机制，但是xxl-job超时后并没有办法停止任务

### ISSUE THREAD

**Issue by NewBlack51** [xuxueli/xxl-job#1249]
Please answer some questions before submitting your issue. Thanks!
任务里面起多个线程执行业务逻辑，并且设置超时停止机制，但是xxl-job超时后并没有办法停止任务
### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
期望，超时能够停止job内容
### Actual behavior
实际上停止不下来
### Other information

**Comment by xuxueli** [comment]
你好，目前超时终止接入线程中断机制试下，所以JobHandler里不允许捕获中断异常，需要外抛出来，文档也有提示，可以排查下代码有没有问题。
