### ISSUE TITLE
父任务分片广播，如何判断所有分片全部完成才触发子任务

### ISSUE THREAD

**Issue by houjie1212** [xuxueli/xxl-job#1250]
先完成的分片返回值状态应该是什么？
现在是最先完成的分片就会触发子任务。

**Comment by xuxueli** [comment]
你好，目前子任务之间并没有关联关系，每个成功都会触发一次子任务。全部分片成功后触发子任务，这个确实比较有意义，已经加入TODO将会排期规划。
