### ISSUE TITLE
如何支持多个任务全部执行完毕，再触发一个子任务？

### ISSUE THREAD

**Issue by Stone1112** [xuxueli/xxl-job#1252]
Please answer some questions before submitting your issue. Thanks!
经过测试，发现目前支持如果1个任务执行成功，会自动触发依赖的多个子任务。
但是，如何支持多个任务全部执行成功，再触发一个子任务？
### Which version of XXL-JOB do you using?
 2.1.1
### Other information

**Comment by xuxueli** [comment]
你好，你提到的应该是DAG流程任务，已经排期处理，可以在这里跟进：https://github.com/xuxueli/xxl-job/issues/829
