### ISSUE TITLE
执行器启动异常

### ISSUE THREAD

**Issue by KevinJJH** [xuxueli/xxl-job#1254]
xxx-job版本是2.1.0，自己的项目作为执行器
但是一启动执行器无法和调度中心建立连接,会报出于netty有关的异常

2019-11-07 10:16:16.716  WARN 46873 --- [tLoopGroup-19-1] io.netty.channel.ChannelInitializer      : Failed to initialize a channel. Closing: [id: 0xfbf9ae04]

java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpClientCodec
![image](https://user-images.githubusercontent.com/29230971/68355411-2c42bb80-014a-11ea-959b-49cf35dcd00c.png)

**Comment by 15036900300** [comment]
会不会是因为你的SpringBoot项目的版本过高啊，好像xxl-job和2.X兼容是不是还有一些问题

**Comment by KevinJJH** [comment]
我的springboot版本是2.1.8release,我也是怀疑这个，但是没有找到解决方式，难道我要降低boot版本吗。。

**Comment by KevinJJH** [comment]
> 会不会是因为你的SpringBoot项目的版本过高啊，好像xxl-job和2.X兼容是不是还有一些问题

**Comment by 15036900300** [comment]
@KevinJJH 当时我看作者说了，他是好像通过netty的通信实现连接的，然后现在和SpringBoot2.X集成还有问题，他用的就是1.5.8版本的SpringBoot
