### ISSUE TITLE
关于执行中任务中断和相同任务启动多个线程的解决方案

### ISSUE THREAD

**Issue by wangzhekid** [xuxueli/xxl-job#1259]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1
### Expected behavior
1.目前执行任务中断，如果当前运行线程不处于阻塞状态(调用sleep、join、wait方法)，是不能抛出InterruptedException
如果一个执行中的线程想要终止，需要在执行器内加入如下代码
if(Thread.currentThread().isInterrupted()){
    return FAIL;
}
2.目前执行器通过jobId进行开启线程，如果想要同一个handler开启多线程,需要创建不同的job(拥有不同的jobId);目前想要增加一个jobGroupId的概念，对应多个jobId，但是拥有相同的逻辑配置，这样可以通过配置修改要开启的线程数，而不是通过创建多个相同内容任务，简化操作

**Comment by xuxueli** [comment]
你好，打开一个问题未复现。第二个优化点可以单独新建分支上线，在ISSUE的分支版本汇总文章里分享下啊。
