### ISSUE TITLE
XXL-JOB架构设计交流

### ISSUE THREAD

**Issue by fdx321** [xuxueli/xxl-job#126]

**Comment by xuxueli** [comment]
你好，技术交流可以加入技术交流群一起讨论。目前5群仍未满，可以加入相互探讨下哈 ：）

**Comment by fdx321** [comment]
多谢，我本来想问几个问题的，后来发现是自己想错了，就close了。我比较关注 “任务分片” 这个功能，计划在哪个版本上呢？
