### ISSUE TITLE
二次开发钉钉报警

### ISSUE THREAD

**Issue by hezhiqiang8909** [xuxueli/xxl-job#1260]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by hezhiqiang8909** [comment]
![image](https://user-images.githubusercontent.com/49931482/68522636-4adeb900-02e8-11ea-860e-fad5dacc9e1e.png)

**Comment by hezhiqiang8909** [comment]
https://github.com/hezhiqiang8909/xxl-job 钉钉报警项目代码,里面sql语句已经改好，改上你的配置就可以运行

**Comment by hezhiqiang8909** [comment]
[xxl-job钉钉报警使用文档.pptx](https://github.com/xuxueli/xxl-job/files/3826907/xxl-job.pptx)
这是使用文档

**Comment by xuxueli** [comment]
赞！可以将该分支分享到这里：https://github.com/xuxueli/xxl-job/issues/154
