### ISSUE TITLE
请问最新版本的XXLJOB是否解决了任务重复执行的问题？

### ISSUE THREAD

**Issue by seguzhizi** [xuxueli/xxl-job#1262]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.1

已查看其他issue，发现有蛮多任务重复执行的issue，和本人遇到的问题基本一致，但是当前版本较低，不清楚如果升级到最新版本是否能解决问题？

另外，这里是xxl的回复：
https://github.com/xuxueli/xxl-job/issues/446#issuecomment-423832686
你好，重复调度根源在于quartz重复触发，要解决这个问题有以下几个方面建议：
1、quartz部署机器时钟同步、调度中心DB读写分离时强制主库；
2、结合 xxl-job 的 “单机路由策略”（第一台、一致性哈希等） + “阻塞策略”：可保证调度落到单机，结合单机阻塞策略可以基本保障重复调度问题。

我这边配置的模式是，随机+单机串行+失败告警，但是仍然有重复的任务，目前已经导致金额超发，难以向领导解释。。。
@xuxueli  目前是否只有上述的解决方案？

**Comment by xuxueli** [comment]
你好，防止重复调度，上面已经给了解决方案 （“单机路由策略”（第一台、一致性哈希等） + “阻塞策略”），替换掉你得现有配置就好了。
重复调度是quartz导致的，升级到最新版本可以规避这一问题的。
也可以在业务侧做幂等。

**Comment by 425915374** [comment]
@xuxueli 你好，我这边版本是1.8.2，路由策略为第一台，阻塞策略为单机串行，仍然会有任务重复执行的情况。是我需要升级到最新版本吗？

**Comment by umena337** [comment]
mark

**Comment by guchengdyy** [comment]
> @xuxueli 你好，我这边版本是1.8.2，路由策略为第一台，阻塞策略为单机串行，仍然会有任务重复执行的情况。是我需要升级到最新版本吗？

----

**原因:** 
    早期xxl-job底层使用的是Quartz, Quartz的调度可能会有问题如果配置不当, 见: https://segmentfault.com/a/1190000015492260
**官方建议:** 
    可以通过结合 “单机路由策略（如：第一台、一致性哈希）” + “阻塞策略（如：单机串行、丢弃后续调度）” 来规避，最终避免任务重复执行。
    见: https://www.xuxueli.com/xxl-job/#5.20%20%E9%81%BF%E5%85%8D%E4%BB%BB%E5%8A%A1%E9%87%8D%E5%A4%8D%E6%89%A7%E8%A1%8C
**解决方案:**
    1.按官方的来, 但是很多任务的配置得改
    2.升级xxl-job到v2.1.0版本+应该可以, 该版本的release notes里面有写移除Quartz, 见: https://www.xuxueli.com/xxl-job/ 搜 v2.1.0 Release Notes
    3.任务支持幂等
