### ISSUE TITLE
xxl-job单线程扫描job-info表，万一这个线程阻塞了岂不是影响其他任务的执行？

### ISSUE THREAD

**Issue by jinyue233** [xuxueli/xxl-job#1263]
许老师，最近在看xxl-job的2.1.0版本，请教问题： 
1，xxl-job是通过一个后台的单线程来不停扫描job-info表来执行不同的任务的吗？
2，若是单线程的话，假如有两个任务要同时执行，会存在时间差异吧，还有万一这个线程阻塞了呢，岂不是会影响其他定时任务？

**Comment by xuxueli** [comment]
这个线程内部逻辑都是异步的，正常不会发生阻塞的。
