### ISSUE TITLE
执行器心跳检测

### ISSUE THREAD

**Issue by cowsky** [xuxueli/xxl-job#1267]
如果执行器挂了（非正常下线），调度器如何知道并remove执行器地址呢？

**Comment by jinyue233** [comment]
通过心跳检测。

**Comment by jzdayz** [comment]
执行器会定时进行注册，http调用admin的register，数据库会一直修改xxl_job_registry的update_time，admin中有一个后台线程，定期去查询，如果update_time的时间+90秒<now(说明90秒内这个注册器没有进行续约)， 那么会将这个执行器剔除

**Comment by jzdayz** [comment]
com.xxl.job.admin.core.thread.JobRegistryMonitorHelper#start 这个是admin中后台monitor线程的执行逻辑

**Comment by cowsky** [comment]
感谢大佬们的回复，了解了

**Comment by xuxueli** [comment]
👍
