### ISSUE TITLE
定时任务执行问题

### ISSUE THREAD

**Issue by mxz668** [xuxueli/xxl-job#1268]
### Which version of XXL-JOB do you using?
master 最新代码

![image](https://user-images.githubusercontent.com/26405774/68728890-7ec91f80-0603-11ea-9420-90b07c04546b.png)
我设置任务每五分钟执行一次，最终执行日志确实每分钟几十次，
![image](https://user-images.githubusercontent.com/26405774/68729109-0f9ffb00-0604-11ea-8547-a72d895e5248.png)

怀疑 JobScheduleHelper在执行List<XxlJobInfo> scheduleList = XxlJobAdminConfig.getAdminConfig().getXxlJobInfoDao().scheduleJobQuery(nowTime + PRE_READ_MS);时逻辑有些问题

**Comment by jzdayz** [comment]
这个corn 有问题呀。 0 0/5 * * * ? * 这个才是5分钟一次。  https://qqe2.com/cron

**Comment by mxz668** [comment]
谢谢
确实是表达式有问题，这么看来前端cron插件有点问题，因为选分钟，秒就会置为 *




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huqingfeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 下午3:25
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"风落"<402416390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 定时任务执行问题 (#1268)




这个corn 有问题呀。 0 0/5 * * * ? * 这个才是5分钟一次。  https://qqe2.com/cron
