### ISSUE TITLE
【严重】2.1版本最好不要创建一次性任务，否则所有任务都将不能调度

### ISSUE THREAD

**Issue by qiang845469063** [xuxueli/xxl-job#1270]
测试方法：创建一个cron :  00 30 16 13 11 ? 2019 的任务

当16:30:00任务执行后，16:30:01扫描任务时，算下次执行时间为空。
将会抛出如下异常。导致调度中心所有任务不能调度。
16:36:44.002 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#scheduleThread error:{}
java.lang.NullPointerException: null
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:85)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，2.1.1 已经做了修复。可以pull master体验下。

**Comment by mrFranklin** [comment]
@xuxueli 请问何时发布2.1.1版本，2.1.0发布之后，也有一段时间了
