### ISSUE TITLE
高并发时任务丢失，methodName='registry'调用超时

### ISSUE THREAD

**Issue by qiang845469063** [xuxueli/xxl-job#1277]
单机并发两千。14:07:00两千个任务同时执行
cron = 00 07 14 18 11 ? 2019

实际情况
14:07:00秒开始执行任务
14:07:06执行了大约1千多个任务
14:07:16时报错，调用 registry接口超时。

猜测是在14:07:07秒时，调度中心认为其他任务过期超5秒，不再执行，导致丢失了900任务。

大约丢失了900个任务未执行。 有什么好的解决办法？只能通过增加调度中心或调整线程池？我觉得那900个任务丢失是非常不合理的。

**Comment by xuxueli** [comment]
你好，这种密集调度爆发的问题，目前只能通过调大线程池、调度中心集群的方式解决。
单机线程池被耗尽，为了保障系统稳定，长时间过期任务只能丢失了。
