### ISSUE TITLE
V2.1.0 任务参数“IJobHandler.execute”入参改为“String params”，怎么获取任务id  logId

### ISSUE THREAD

**Issue by chenxing0755** [xuxueli/xxl-job#1279]
我们公司已经将xxljob用于生产环境了，现在正在升级到 2.1.0版本。
         我想通过执行器执行完任务后进行RPC回调，异步通知调度中心任务的结果，并记录在这条任务执行日志中。如图，源码中，用HandleCallbackParam这个类传递回调的结果，里面有logId，通过这个和调度中心的调度日志关联 ，这个logid怎么获取呢

![8888](https://user-images.githubusercontent.com/45444321/69145479-a7bc4980-0b08-11ea-8248-75b3462e865f.jpeg)

**Comment by chenxing0755** [comment]
V2.1.0版本 IJobHandler执行器的方法参数由TriggerParam triggerParam改成了 String param，无法获取logid了，原来旧版本的是通过triggerParam.getLogId()获取的。



<img width="1028" alt="33333333" src="https://user-images.githubusercontent.com/45444321/69147363-b86ebe80-0b0c-11ea-84d4-9c2be530e993.png">

**Comment by chenxing0755** [comment]
我通过修改源码解决了  IJobHandler  JobThread

**Comment by xingsheq** [comment]
> 我通过修改源码解决了 IJobHandler JobThread

hi,能否分享下改的代码，我也有这个问题

**Comment by luozhao528** [comment]
怎么改的

**Comment by honghuhu** [comment]
> 怎么改的

### XxlJobContext.class 构造器新增一个 logId 属性就行, 哪里有引用改哪里就可
    public XxlJobContext(long jobId, long logId, String jobParam, String jobLogFileName, int shardIndex, int shardTotal) {
        this.jobId = jobId;
        this.logId = logId;
        this.jobParam = jobParam;
        this.jobLogFileName = jobLogFileName;
        this.shardIndex = shardIndex;
        this.shardTotal = shardTotal;

        this.handleCode = HANDLE_CODE_SUCCESS;  // default success
    }
