### ISSUE TITLE
针对每个任务的执行，可能加入一个任务的执行时长？

### ISSUE THREAD

**Issue by SongwenWYU** [xuxueli/xxl-job#128]
使用时，发现没有一个可以观察任务执行时长的地方，虽然可以通过查日志的方式计算时长，终归是不方便，在日志查询页面，加入执行时长可行？

**Comment by ImbigKK** [comment]
源码都开放给你了，自己去改呗~




发自网易邮箱大师


在2017年8月4日 16:39，songwen<notifications@github.com> 写道：

使用时，发现没有一个可以观察任务执行时长的地方，虽然可以通过查日志的方式计算时长，终归是不方便，在日志查询页面，加入执行时长可行？

**Comment by xuxueli** [comment]
@SongwenWYU @ImbigKK 你好，感谢关注啊！
任务时长在任务统计的时候有意义，先记录下来，但是和TODO中规划相比优先级较低。如果紧急的话，可以自己定制哈 ：）
