### ISSUE TITLE
数据源配置不能自动恢复重连

### ISSUE THREAD

**Issue by huangst2016** [xuxueli/xxl-job#1280]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1-SNAPSHOT

### Expected behavior
当数据库意外挂掉挂掉或者因为一些未知的网络原因导致程序中数据源连接缓存池中连接全部失效，过后数据库恢复或者网络恢复，程序的数据库连接也应该自动恢复。
### Actual behavior
在线上数据库部署在另外一台服务器上，可能由于网络原因导致的程序数据源连接挂掉后，程序不能自动恢复正常的数据源连接，导致后续调度一直失败。
### Steps to reproduce the behavior
1.启动xxl-job-admin
2.手动关闭数据库（或者断开网络）
3.观察到xxl-job-admin开始报数据源连接错误后，再重启数据库（或恢复网络）
4.xxl-job-admin还是一直报数据源连接错误
### Other information
针对此问题，我已经修改成自己预期的数据源连接自动恢复的效果了，希望作者考虑这点也做相应的修改。下面是我自己修改的内容。。
pom里新增：
                <dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid</artifactId>
			<version>1.1.10</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid-spring-boot-starter</artifactId>
			<version>1.1.10</version>
		</dependency>
配置文件里数据源连接配置改为：
### xxl-job, datasource 数据库配置 ##########################
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/digital-cockpit?useUnicode=true&characterEncoding=utf-8&connectTimeout=5000&socketTimeout=5000&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driverClassName= com.mysql.cj.jdbc.Driver
#连接池的配置信息
spring.datasource.type = com.alibaba.druid.pool.DruidDataSource
#配置初始化大小、最小、最大 ###
spring.datasource.datasource.initialSize=10
spring.datasource.minIdle=10
spring.datasource.maxActive=40
#配置获取连接等待超时的时间 ###
spring.datasource.maxWait=10000
#是否重试：-1不重试，0重试一次 ###
spring.datasource.notFullTimeoutRetryCount=-1
#配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 ###
spring.datasource.timeBetweenEvictionRunsMillis=60000
#配置一个连接在池中最小生存的时间，单位是毫秒###
spring.datasource.minEvictableIdleTimeMillis=300000
spring.datasource.validationQuery=SELECT 'x'
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
#配置监控统计拦截的filters，去掉后监控界面sql无法统计###
spring.datasource.filters=config,stat
spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据
spring.datasource.useGlobalDataSourceStat=true

**Comment by xuxueli** [comment]
你好，你看的应该是早起snapshot版本，最新snapshot版本已经修复了这个问题，可以pull master体验下。
