### ISSUE TITLE
由于执行日志报错信息数据过长导致无法入库

### ISSUE THREAD

**Issue by zgl1011** [xuxueli/xxl-job#1285]
Please answer some questions before submitting your issue. Thanks!
由于执行日志报错信息数据过长导致无法入库
### Which version of XXL-JOB do you using?
2.0.1
### Other information

**Comment by zgl1011** [comment]
![image](https://user-images.githubusercontent.com/26699764/69236544-b0775300-0bce-11ea-94a3-b29232227202.png)

**Comment by zgl1011** [comment]
执行器重复的打印报错信息，每次调度都会执行。由于报错信息过长，93674，超过了text字段64k的长度

**Comment by xuxueli** [comment]
你好，从日志看这是 cutomer_grow 一张业务表，并非XXLJOB底层表。可以限制下报错信息长度解决。

**Comment by zgl1011** [comment]
也许我没有表述清楚，简单的说就是xxl_job_log表里面的handle_msg字段是text类型，但是client端的报错信息超过了这个长度，导致callback失败，从而导致不断的重试，能否用longtext或者对于报错信息进行截取来避免这个问题
