### ISSUE TITLE
执行器注册会出现错误，不必现，运行一段时间，就会很多这样的错误日志，错误日志见附件

### ISSUE THREAD

**Issue by biliangliang** [xuxueli/xxl-job#1288]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Other information
![4d853cf895f1097b7044483a985e98a0](https://user-images.githubusercontent.com/40481743/69392345-aeb5a880-0d10-11ea-9841-ef76384bcfdb.png)

**Comment by xuxueli** [comment]
你好，最新版本已经做了优化，可以pull master体验下。将会在下个小版本修复；

**Comment by biliangliang** [comment]
是更新了xxl-rpc吗，请问大佬2.1.1计划什么时候发布
