### ISSUE TITLE
怎么添加新的包？

### ISSUE THREAD

**Issue by 0428402001** [xuxueli/xxl-job#129]
对于一些简单的任务，我使用GLUE在线编辑代码，但有些使用的包没有打包在在线环境下，我怎么手动的把这些包添加进去？

**Comment by xuxueli** [comment]
你好，GLUE任务依赖执行器容器环境，依赖的包需要预先编译部署的。

**Comment by 0428402001** [comment]
依赖包放到maven里面 编译后部署下 ？
如果部署好的项目已经在tomcat下运行了，我把要用到的jar包直接放到lib目录下，并且重启tomcat是否可行？

**Comment by xuxueli** [comment]
@0428402001 GLUE任务运行在执行器，执行器添加需要的依赖重新部署即可。

**Comment by dongluyang** [comment]
打包成一个fat jar,放到执行器的classpath中，或着通过java反射动态加载jar,并且调用方法。具体的请看
https://www.toutiao.com/article/7227496875803345446/
