### ISSUE TITLE
加入spring boot actuator 后 默认健康端点无法访问

### ISSUE THREAD

**Issue by 192100705** [xuxueli/xxl-job#1291]
调度器加入该依赖
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
    <version>2.0.8.RELEASE</version>
</dependency>

默认的健康检查端点都为404无法访问
eg:
  /actuator
  /actuator/health

**Comment by xuxueli** [comment]
已合并master分支，将会在下个版本发布。
