### ISSUE TITLE
定时任务触发问题

### ISSUE THREAD

**Issue by wyhbert** [xuxueli/xxl-job#1294]
使用的xxl-job版本是1.9.2
现象：Cron方式定时任务未执行（正常执行时，注解了jobhandle的类会打印调用成功的日志）
![image](https://user-images.githubusercontent.com/12029588/69476404-6da6bc80-0e14-11ea-9e09-f3bb2931e85e.png)

**Comment by xuxueli** [comment]
你好，问题未复现， 需要进一步提供复现步骤。
