### ISSUE TITLE
建议使用再封装的ORM工具，例如Mybatis-plus

### ISSUE THREAD

**Issue by MHlihao** [xuxueli/xxl-job#1298]
感谢作者！
今天将数据源改为Oracle时，出现SQL不兼容情况，看了下有  !() 语法，小弟斗胆建议作者使用再封装的工具进行开发。如Mybatis-Plus 因为他们有专人负责搞不兼容问题，哈哈
感谢作者！

**Comment by xuxueli** [comment]
你好，引入三方依赖会增加维护成本。
可以将不兼容的SQL汇总贴出来，我们调整一下。

**Comment by MHlihao** [comment]
1.特殊字符 `
2.XxlJobLogMapper.findFailJobLogIds 的 !()
3.SELECT <include refid="Base_Column_List" />
		FROM XXL_JOB_GROUP AS t
		ORDER BY t."order" ASC . Oracle 不用 as 
4.Limit 关键字     这个占大头

**Comment by MHlihao** [comment]
还有自增ID

**Comment by MHlihao** [comment]
com.xxl.job.admin.dao.XxlJobRegistryDao.findDead-Inline 
 无效的列类型: 1111 
不行，改不动了。找架构组要MYSQL数据库去

**Comment by MHlihao** [comment]
SQL结尾 ; 号

**Comment by MHlihao** [comment]
使用序列后 useGeneratedKeys="true" 会报错

**Comment by MHlihao** [comment]
oracle  不支持 useGeneratedKeys =true

**Comment by dudiao** [comment]
大佬考虑使用mybatis plus吗？我可以帮忙改造
