### ISSUE TITLE
支持每月最后一天23点这种cron表达式吗？比如：0 0 23 L * ?

### ISSUE THREAD

**Issue by xuanan9** [xuxueli/xxl-job#1299]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，支持的。最新Release版本提供了Web Cron插件，可以界面操作生成Cron表达式。

**Comment by xuanan9** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 许雪里 <notifications@github.com&gt;
发送时间: 2019年11月25日 15:47
收件人: xuxueli/xxl-job <xxl-job@noreply.github.com&gt;
抄送: xuanan <1571745134@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xuxueli/xxl-job] 支持每月最后一天23点这种cron表达式吗？比如：0 0 23 L * ? (#1299)
