### ISSUE TITLE
bean模式是否支持python，或者glue模式如何使用公司内部的python库

### ISSUE THREAD

**Issue by z-hanwen** [xuxueli/xxl-job#1300]
你好，我们公司里面java和python都有，xxl是之前用的比较好的job框架。
我想咨询下python如果想用的话，能否使用bean模式，或者glue模式下如何实现比较复杂的场景

**Comment by xuxueli** [comment]
你好，python可以借助glue-python模式。
glue模式可以通过import引入执行器机器安装的模块或脚本。
