### ISSUE TITLE
Linux系统与windows系统执行器线程启动有差异，windows上有问题

### ISSUE THREAD

**Issue by l1421637415** [xuxueli/xxl-job#1302]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
linux系统与windows系统的启动执行器应该是一样的。
### Actual behavior
 我的执行器是基于spring boot的设置web(WebApplicationType.NONE)不启动web服务，这时候执行器在linux系统上可以正常运行，在windows系统上则会直接退出。查看代码发先里面的基础服务线程都是以守护线程的方式启动的，在linux上系统的行为是会先启动netty的tcp端口服务，有业务线程在运行然后系统就不会退出，在windows系统上在开启rpc客户端的时候（还没有走到开启tcp服务）守护线程就会结束全部退出。即差距就在于启动rpc服务的时机，两个系统不一样，windows上还没启动tcp服务，守护线程就全部结束退出了，也有极小的概率Windows上会启动成功，在此说明用了两台Windows10的电脑结果一样。
  如果在boot的main方法里面调用SpringApplication.run后在让主线程sleep几秒，则windows系统上的问题就会消除，或者将源码中的任意一个基础服务线程设置为非守护线程windows上也不会出问题。查阅了一些资料也debug了代码但是还是不明白究竟是两个系统哪里的差异导致了这个问题，如果哪位大神知道问题根源还望不吝赐教。
### Steps to reproduce the behavior
1：新建一个springboot的执行器，在main方面里设置web(WebApplicationType.NONE)
2：分别在Linux系统和windows10系统上执行。
3：linux系统正常启动保持运行，windows10上则会启动后直接退出结束
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
这个问题根源在SpringBoot，可以给SpringBoot仓库提个ISSUE跟进啊：https://github.com/spring-projects/spring-boot

**Comment by l1421637415** [comment]
好的，多谢。



---原始邮件---
发件人: "许雪里"<notifications@github.com&gt;
发送时间: 2019年11月27日(星期三) 晚上8:27
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送: "l1421637415"<1421637415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xuxueli/xxl-job] Linux系统与windows系统执行器线程启动有差异，windows上有问题 (#1302)



你好，感谢反馈！
 这个问题根源在SpringBoot，可以给SpringBoot仓库提个ISSUE跟进啊：https://github.com/spring-projects/spring-boot
