### ISSUE TITLE
请问能不能出一个批量导出或者对比的功能？

### ISSUE THREAD

**Issue by qq253498229** [xuxueli/xxl-job#1305]
由于Job越来越多了，环境也很多，导致不同环境的job不同步，而人工维护成本也很高，所以想问一下能不能出一个导出导入的功能，这样就可以批量的把一个环境的所有job都同步到新环境上。

**Comment by xuxueli** [comment]
你好，不同环境迁移其实有个非常好的方式。DB复制一份即可。
