### ISSUE TITLE
当调度中心不可用时，执行器可否在心跳检查若干次后，停止心跳检查，防止错误日志每30s刷一次及执行器内存压力

### ISSUE THREAD

**Issue by wybrono** [xuxueli/xxl-job#1306]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
当调度中心不可用时，执行器可否在心跳检查若干次后，停止心跳检查，防止错误日志每30s刷一次及执行器内存压力，当调度中心恢复后，可以唤醒执行器继续心跳注册
### Actual behavior
当调度中心不可用时，执行器一直在心跳注册，错误日志每30s刷一次，且内存压力变大
### Steps to reproduce the behavior
1、保证调度中心为可用状态
2、启动执行器
3、down掉调度中心
### Other information

**Comment by xuxueli** [comment]
你好，如果执行器暂停心跳，调度中心恢复时会导致注册延时，有隐患。
可以考虑升级最新版本，最新版本心跳注册改为restful方式，损耗较小。
