### ISSUE TITLE
任务列表无法读取

### ISSUE THREAD

**Issue by zraul** [xuxueli/xxl-job#131]
使用1.8.1的war包直接替换1.6的war包以后，任务列表与调度日志的具体内容就无法读取，一直显示处理中。首页显示调度任务数与成功数又是正常的。请问这是为什么。
PS：数据库值从别的机器备份过来直接用的

**Comment by xuxueli** [comment]
你好，1.6升级1.8，表结构做了调整，需要重新初始化表结构的啊。
1.8.x 几个小版本是向下兼容的，可以直接升级。
