### ISSUE TITLE
邮件告警异常

### ISSUE THREAD

**Issue by slinhuang** [xuxueli/xxl-job#1310]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

### Expected behavior
邮件告警正常发送
### Actual behavior
邮件告警没有发送,但是调度是正常的,重启服务时,一天内发出大量的几个月前的告警,导致邮箱超出当日限额不可用.
### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。请进一步提供复现步骤。

**Comment by fan0916** [comment]
我们遇到了同样的问题，经排查是smtp没有配置超时时间导致线程全部hang住，重启有大量告警邮件需要发送
