### ISSUE TITLE
以main方法直接启动执行器会退出不是boot问题

### ISSUE THREAD

**Issue by l1421637415** [xuxueli/xxl-job#1312]
脱离springboot直接手写main函数启动一个执行器，Linux系统与window系统都会直接退出，开启不了rpc服务，又查阅资料跟踪启动线程最后个人得出的结论：执行器自己相关的线程都是守护线程，当使用执行器的项目没有自己的常驻主业务线程（例如web项目会开启tcp服务），执行器里面的守护线程就没有时间执行到开启rpc服务的代码,即开启不了自带的tcp服务。因为主线程时间太短立刻就执行完毕，守护线程里面的代码还未执行完毕会立刻被中断退出。所以建议在使用文档里面说明此事项，如果项目没有常驻主业务线程建议在main函数执行XxlJobExecutor.start()后让主线程sleep几秒。

**Comment by xuxueli** [comment]
你好，main函数启动执行器可以参考 xxl-job-executor-sample-frameless 示例。启动组件 FramelessApplication 已经有主动sleep的参考代码，注释也完善了。
