### ISSUE TITLE
用户管理，建议优化

### ISSUE THREAD

**Issue by 1725785880** [xuxueli/xxl-job#1318]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
    2.1.1
### Expected behavior
    提供API接口调用OSS系统校验用户
### Actual behavior
    依赖系统自定义的用户表
### Other information
    建议预留调用OSS系统校验用户，并优化用户管理

**Comment by xuxueli** [comment]
你好，权限拦截可以通过自定义权限拦截器实现。
