### ISSUE TITLE
xxl-job注册到调度中心失败

### ISSUE THREAD

**Issue by LeoMuhammad** [xuxueli/xxl-job#1319]
**调度中心用docker部署的，版本2.1.0，启动成功，页面可以访问**
![image](https://user-images.githubusercontent.com/40845334/69855818-4c881500-12c7-11ea-8886-ac45106b5dc0.png)

**本地的客户端用的xxl-job-core的版本是2.1.2-SNAPSHOT，启动时发现注册失败**
![image](https://user-images.githubusercontent.com/40845334/69855657-edc29b80-12c6-11ea-8139-a5a4d39dd4a5.png)

**客户端版本改成2.1.0，结果还是注册失败**

**直接调用http://172.16.14.7:8888/xxl-job-admin/api/registry接口时，发现404**
![image](https://user-images.githubusercontent.com/40845334/69855865-66295c80-12c7-11ea-832d-1aa27aa1efab.png)
请问下，这可能是什么问题造成的

**Comment by xuxueli** [comment]
你好，可以Debug查看一下相关API。
针对API服务，已经提供了测试用例的，“com.xxl.job.adminbiz.AdminBizTest”，可以利用这个测试用例测试回调服务。

**Comment by dongxiangxi** [comment]
我也碰到了这个问题，我是下的最新的代码，在master分支上编译后直接启动；executor启动时
`xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='http://192.168.31.43:9999/'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting fail, StatusCode(404) invalid. for url : http://127.0.0.1:8080/xxl-job-admin/api/registry, content=null]`

直接调用接口也是404
`http://127.0.0.1:8080/xxl-job-admin/api/registry`

查看JobApiController 定义接口，api/{uri} ,应该是没匹配到，怀疑可能存在jar包冲突
