### ISSUE TITLE
corn表达式选择

### ISSUE THREAD

**Issue by Selegant** [xuxueli/xxl-job#1323]
任务管理 任务编辑 选择corn 表达式时 选择 每1分钟执行一次生成的corn表达式为 * 0/1 * * * ? 但是其实应该为0 0/1 * * * ?

**Comment by ljzorz** [comment]
是啊！真是坑！

**Comment by xuxueli** [comment]
你好，corn 每个TAB下的选项，只会影响当前TAB位置的数据。比如 “分钟” TAB中的每1分钟执行1次，只说明分钟级别的触发周期。其他级别，比如分钟、日、月等要单独设置。

如果希望查看触发时间效果，可以通过 “下次执行时间” 按钮查看后续几次的执行时间。
