### ISSUE TITLE
io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.110.41:17000

### ISSUE THREAD

**Issue by hlbfoxboy** [xuxueli/xxl-job#1325]
2.1.1和2.1.0 都出现这样的问题，每隔一分钟执行   有的成功有的失败，请问一下 是什么原因

-
![微信截图_20191202162314](https://user-images.githubusercontent.com/17540007/69943192-214c3280-1520-11ea-8ebb-164e8f65c04a.png)
![微信截图_20191202162335](https://user-images.githubusercontent.com/17540007/69943214-25785000-1520-11ea-9a94-80fe0cf9748a.png)

**Comment by ergouge** [comment]
请问是怎么解决的？2.2.0版本也遇到这样的问题
