### ISSUE TITLE
docker部署执行器，注册ip地址变化后无法获取XxlJobLogger.log打印的日志

### ISSUE THREAD

**Issue by MerryYou** [xuxueli/xxl-job#1328]
**使用版本1.9.2**

**前提条件：**

> 当执行器部署到docker容器中，并且执行器使用XxlJobLogger.log()方式打印日志到控制台

**现象**
- 如果不重启docker容器，IP地址不会发生变化，通过控制台查看执行日志正常
- 如果重启docker容器，自动注册的IP地址发生变化，但是原始日志在表XXL_JOB_QRTZ_TRIGGER_LOG字段executor_address中存放的依然是之前的docker虚拟IP，导致无法连接执行器获取日志文件

> 这种情况除了通过配置执行器ip固定为宿主机IP，并且打通宿主机与容器对应端口外，是否可以进行别的更优方案解决？

**Comment by zhipingwu** [comment]
xxljob，并不保证ip迁移代码的变化没有影响，所以你可以考虑使用hostname来解决此问题，因为docker里面的hostname是不变的。

**Comment by xuxueli** [comment]
@zhipingwu +1，或者可以重写XxlJobLogger，读写到单独的日志组件里。

**Comment by MerryYou** [comment]
@zhipingwu @xuxueli 多谢大佬指点，get到啦
