### ISSUE TITLE
在1.8.2-SNAPSHOT上使用kryo序列化及对sharding-broadcast添加分组（主从）保证HA，有兴趣的可以一起讨论

### ISSUE THREAD

**Issue by Mrwb** [xuxueli/xxl-job#133]
已经推送到我的分支下了，有兴趣的可以看下
https://github.com/Mrwb/xxl-job/tree/1.8.2-SNAPSHOT-kryo

**Comment by it-noob** [comment]
kryo在序列化注册类的时候的索引问题你有遇到过么？比如dubbox宣称的准备将序列化协议默认为kryo结果再多个服务者调用时就会发生无法反序列化的为。可能跟xxl-job讨论没太大关系，但是纯属请教探讨
