### ISSUE TITLE
Docker 启动的 2.1.1 版本访问 /xxl-job-admin/api 404

### ISSUE THREAD

**Issue by 576272014** [xuxueli/xxl-job#1330]
Docker 版本 18.09.8
镜像 xuxueli/xxl-job-admin:2.1.1

启动后服务端一直出现以下 WARN，每隔 30s 出现一次：
![image](https://user-images.githubusercontent.com/39613868/70053131-bf6af600-160f-11ea-85b1-e0e2df7cff86.png)
logback [http-nio-8080-exec-2] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/xxl-job-admin/api] in DispatcherServlet with name 'dispatcherServlet'

执行器每隔 30s 出现一次以下错误：
![image](https://user-images.githubusercontent.com/39613868/70053338-2e484f00-1610-11ea-87f7-3f768c7ba206.png)

请教大神如何解决，多谢多谢！

**Comment by xuxueli** [comment]
针对API服务，已经提供了测试用例的，“com.xxl.job.adminbiz.AdminBizTest”，可以利用这个测试用例测试回调服务。

上述问题应该是执行器回调地址配错了，应该是调度中心跟地址。
