### ISSUE TITLE
日志中文乱码问题

### ISSUE THREAD

**Issue by dong4j** [xuxueli/xxl-job#1331]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 2.1.1
### Steps to reproduce the behavior
 在 JobHandler 中抛出自定义异常存在中文时, client 端通过 api/callback 接口发送给 admin 时, 由于 `dataOutputStream.writeBytes(requestBody);` 导致乱码, 修改为 `dataOutputStream.write(requestBody.getBytes());` 就可以了
 
### Other information

**Comment by xiaofeihhu** [comment]
遇到相同问题，结果就是在监控页面上，查看执行备注时显示乱码，数据库表中数据也是乱码

**Comment by xuxueli** [comment]
问题已修复，可以参考 @zhipingwu 同学的PR：#1345

可以自行调整相关代码，或者等待即将发布下个小版本。
