### ISSUE TITLE
xxl-job-core 2.1.1 端口占用问题解决

### ISSUE THREAD

**Issue by weinianta** [xuxueli/xxl-job#1332]
![image](https://user-images.githubusercontent.com/13379708/70108373-1e6a5280-1684-11ea-8acb-6e89b81dd88f.png)

xxl-job-core 2.1.0版本没有这个问题，升级为2.1.1后就会报端口被占用

**Comment by ljzorz** [comment]
同问，我也碰到这个问题！

**Comment by saygoodbye** [comment]
使用2.1.2版本也存在相同报错，但是不影响服务使用，发现注册端口做了两次连接，坐等解决

**Comment by houjie1212** [comment]
把执行器组件配置声明bean的参数去掉就好了，example里面去掉了但是文档没有更新
![bug](https://user-images.githubusercontent.com/4403472/70585811-5d5a5400-1c00-11ea-949f-c8b978489763.png)

**Comment by xuxueli** [comment]
@houjie1212  
XxlJobSpringExecutor 组件初始化的Bean参数已经不需要，可以参考执行器sample项目，文档已更新。

**Comment by weinianta** [comment]
好的，已经修改完毕，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"许雪里"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 晚上7:29
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"杨康"<851161583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] xxl-job-core 2.1.1 报端口被占用 (#1332)




@houjie1212
 XxlJobSpringExecutor 组件初始化的Bean参数已经不需要，可以参考执行器sample项目，文档已更新。
