### ISSUE TITLE
RPC 能给个开关吗?

### ISSUE THREAD

**Issue by dong4j** [xuxueli/xxl-job#1333]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1

业务端代码依赖了 xxl-job 的 client, 可以添加一个 enable 通过配置来选择是否加载 xxl-job 的相关类, 因为我可能只是在本地开发, 暂时还不需要 job 相关的功能, 只是暂时依赖了 job-core.
但是却关不掉 rpc, 导致一直报错, 虽然不影响使用, 但是却很不友好, 因此想能不能也给 rpc 添加一个开关? 或者搞个 starter 吧, 用注解来启用 job

**Comment by xuxueli** [comment]
你好，如果不希望启动内嵌执行器，不配置执行器组件即可。
如果只想要单独使用rpc功能，可以单独引入xxl-rpc提供通讯支持。
