### ISSUE TITLE
web IDE 多文件模式

### ISSUE THREAD

**Issue by jjeejj** [xuxueli/xxl-job#1334]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
web IDE 支持多文件模式，文件夹什么的
### Actual behavior
单文本模式
### Other information

**Comment by xuxueli** [comment]
你好，目前仅支持单文件，如果有多个依赖可以将依赖脚本上传到执行器机器import使用。

**Comment by laizezhong** [comment]
@xuxueli 大佬，多文件模式，其实指的是工程项目制，这样会更方便取使用，单文件就仅仅是脚本，要取服务器把原来都传进去还是挺麻烦的，不同执行器都要上传一份，代码又任何修改都要去多台服务器里改
