### ISSUE TITLE
任务执行结束，但是任务没有终止

### ISSUE THREAD

**Issue by hapoy9** [xuxueli/xxl-job#1336]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.2
### Expected behavior
任务正常结束
### Actual behavior
任务执行完了，任务的返回也是正常的，但是回调返回失败triggerCallbackThread#callbacklog，返回结果ReturnT [code=500,msg=the request data invalid, content=null]，导致任务一直没有结束
### Other information

**Comment by xuxueli** [comment]
你好，2.1.2 还在迭代中，可以重新pull master再 体验下。
