### ISSUE TITLE
cron表达式和执行的情况不匹配

### ISSUE THREAD

**Issue by xuehanxin** [xuxueli/xxl-job#1337]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2-SNAPSHOT
### Expected behavior
希望配置的cron表达式符合结果预期
### Actual behavior
执行job和配置的cron表达式不对
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/15827948/70371593-0149b400-1910-11ea-90e3-ee7034b8f9fd.png)

### Other information
最近没空看源码排查问题，希望能解决一下

**Comment by zhipingwu** [comment]
![image](https://user-images.githubusercontent.com/50327335/70373837-00704c80-1927-11ea-8d7a-8eb5caccc900.png)
上面截图得表达式意思就是1秒执行一次。

如果要每小时执行一次可以用: 0 0 0/1 * * ? *

**Comment by zhipingwu** [comment]
![image](https://user-images.githubusercontent.com/50327335/70383120-7a461b80-19a3-11ea-85b5-984885a73753.png)
是的，这个选择也没问题，你应该选择指定0秒，0分，然后每小时

如果你执行每秒+每分+0/1(从0小时开始每1小时一次)，那也就是每秒的意思了。

**Comment by xuxueli** [comment]
@zhipingwu  +1
