### ISSUE TITLE
IJobHandler为啥是个abstract class，而不是interface?

### ISSUE THREAD

**Issue by solosky** [xuxueli/xxl-job#134]
从命名和接口定义上，不是interface没天理啊。
请问作者是什么考虑呢？
```
/**
 * remote job handler
 * @author xuxueli 2015-12-19 19:06:38
 */
public abstract class IJobHandler {

	/**
	 * job handler
	 * @param params
	 * @return
	 * @throws Exception
	 */
	public abstract ReturnT<String> execute(String... params) throws Exception;
	
}
```

**Comment by xuxueli** [comment]
你好，感谢关注啊！
一开始考虑用抽象类，是为了方便在父类中做一些基础逻辑封装，而不是直接调用execute方法，但是后来把这部分逻辑迁移到JobThread中去了。
从现在代码结构来看，二者都可以实现，没有区别。

**Comment by solosky** [comment]
几个建议啊，不过考虑到兼容性问题，很难改了：
* IJobHandler 改成interface
* JobHandler注解支持方法级别注解，这样可以在一个类里面写多个定时任务方法
* 注解和接口方式只需使用一种方式即可，实现一个task不需要既要加注解，又要实现接口，有点冗余
* 执行器的名称长度增加到100个字符，现在太短了。。
* bean模式自动发现注册task，而不是人工去手动填写一下
* 支持手动选择节点调度，调试task的时候很有用
* task列表加上最后一次执行结果，很快就能定位哪个task有问题

**Comment by zsf513** [comment]
支持将IJobHandler改成interface。搞成抽象类，局限性就大了：java是单一继承，如果业务中有个类已经继承了其他类，而这个类又想继承IJobHandler，那么就不能满足了。而改成接口，则方便很多。并且从IJobHandler这个类的命名上来说，让人感觉就是一个接口。

**Comment by bugmeng** [comment]
确实有问题，深入才发现现在要改的真的不少

**Comment by XuMinCha** [comment]
> 几个建议啊，不过考虑到兼容性问题，很难改了：
> 
> * IJobHandler 改成interface
> * JobHandler注解支持方法级别注解，这样可以在一个类里面写多个定时任务方法
> * 注解和接口方式只需使用一种方式即可，实现一个task不需要既要加注解，又要实现接口，有点冗余
> * 执行器的名称长度增加到100个字符，现在太短了。。
> * bean模式自动发现注册task，而不是人工去手动填写一下
> * 支持手动选择节点调度，调试task的时候很有用
> * task列表加上最后一次执行结果，很快就能定位哪个task有问题



> 几个建议啊，不过考虑到兼容性问题，很难改了：
> 
> * IJobHandler 改成interface
> * JobHandler注解支持方法级别注解，这样可以在一个类里面写多个定时任务方法
> * 注解和接口方式只需使用一种方式即可，实现一个task不需要既要加注解，又要实现接口，有点冗余
> * 执行器的名称长度增加到100个字符，现在太短了。。
> * bean模式自动发现注册task，而不是人工去手动填写一下
> * 支持手动选择节点调度，调试task的时候很有用
> * task列表加上最后一次执行结果，很快就能定位哪个task有问题

不难改：
我基于1.0版本做了几个修改：
IJobHandler 改成了接口，引入AbstractJobHander抽象类；
引入MutilpleJobHandler注解，像spring的@scheduled一样支持方法级别的任务
executor应用中去掉了JobThread类，换成JobTask, 同时引入线程池（这样做admin无法对executor中的任务执行线程进行控制，不要用线程池好像也无法控制）
修改记录日志方式，加入job.log用于记录一天内的所有定时任务log，因为之前是执行一次任务一个log，不方便快速定位问题。

2.0的代码还没来得及看

**Comment by bugmeng** [comment]
> > 几个建议啊，不过考虑到兼容性问题，很难改了：
> > 
> > * IJobHandler 改成interface
> > * JobHandler注解支持方法级别注解，这样可以在一个类里面写多个定时任务方法
> > * 注解和接口方式只需使用一种方式即可，实现一个task不需要既要加注解，又要实现接口，有点冗余
> > * 执行器的名称长度增加到100个字符，现在太短了。。
> > * bean模式自动发现注册task，而不是人工去手动填写一下
> > * 支持手动选择节点调度，调试task的时候很有用
> > * task列表加上最后一次执行结果，很快就能定位哪个task有问题
> 
> 不难改：
> 我基于1.0版本做了几个修改：
> 
> > * IJobHandler 改成了接口，引入AbstractJobHander抽象类；
> > * 引入MutilpleJobHandler注解和JobMethod注解，像spring的@scheduled一样支持方法级别的任务
> > * executor应用中去掉了JobThread类，换成JobTask, 同时引入线程池（这样做admin无法对executor中的任务执行线程进行控制，不用线程池好像也无法控制）
> > * 修改记录日志方式，加入job.log用于记录一天内的所有定时任务log，因为之前是执行一次任务一个log，不方便快速定位问题。
> 
> 2.0的代码还没来得及看

我差点脱坑，发现挺多不满足自己需求的东西，并且现在好多都是流式和血缘

**Comment by xuxueli** [comment]
你好，最新版本已经支持基于方法开发任务，可以升级体验下：https://github.com/xuxueli/xxl-job/issues/447
