### ISSUE TITLE
初始源码一跑起来就报错

### ISSUE THREAD

**Issue by zhangjing007** [xuxueli/xxl-job#1340]
刚刚克隆的源码  运行起来（运行的自带的案例）就报错！什么原因呢？
![image](https://user-images.githubusercontent.com/24825020/70374563-db7fd780-192e-11ea-81e7-47a6dff3481c.png)
![image](https://user-images.githubusercontent.com/24825020/70374569-f18d9800-192e-11ea-92f3-0d51eef16389.png)
![image](https://user-images.githubusercontent.com/24825020/70374576-ff431d80-192e-11ea-8514-aa1ea0bc0ee0.png)

**Comment by zhipingwu** [comment]
![image](https://user-images.githubusercontent.com/50327335/70383069-75349c80-19a2-11ea-9a4f-31a7bfb6878e.png)
因为第一次你的管理端刚刚启动，执行器需要注册到管理器，管理器的servletDispatch还没有初始化好。
而这边对于register设置的默认时间readTimeout为3S，所以超时，但后面重试又好了，因为管理端已经初始化好了。

这个看看后续有没有办法优化一下，比如启动管理器之前做一个预热。

**Comment by zhipingwu** [comment]
我也复现了，这是一个bug，我修复一下。

**Comment by zhangjing007** [comment]
> 我也复现了，这是一个bug，我修复一下。

谢谢.

**Comment by zhipingwu** [comment]
改好了，已经提交pull request，https://github.com/xuxueli/xxl-job/pull/1343
等待许老师合并。

**Comment by zhangjing007** [comment]
> 改好了，已经提交pull request，#1343
> 等待许老师合并。

谢谢，坐等合并，不知道老师啥时间能合并

**Comment by xuxueli** [comment]
已修复，合并PR：https://github.com/xuxueli/xxl-job/pull/1345

将会跟随下个小版本发布，或者可以自行调整。
