### ISSUE TITLE
执行初始化SQL报错

### ISSUE THREAD

**Issue by EternallyTm** [xuxueli/xxl-job#1346]
2.1.2版本的sql在mysql-5.6.46上执行报 Specified key was too long; max key length is 767 bytes

**Comment by zhipingwu** [comment]
有截图吗

**Comment by EternallyTm** [comment]
![image](https://user-images.githubusercontent.com/27730979/70402252-bc3b9400-1a6d-11ea-9321-2fa712467144.png)

**Comment by EternallyTm** [comment]
> 有截图吗

有的
![image](https://user-images.githubusercontent.com/27730979/70402277-cc537380-1a6d-11ea-800d-7f0e059d2e32.png)

**Comment by zhipingwu** [comment]
图片看不清楚，麻烦再传输一次。

**Comment by zhipingwu** [comment]
看不到图片。

**Comment by EternallyTm** [comment]
> 看不到图片。

图片我是传上去了的，我都能看到的

**Comment by EternallyTm** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhipingwu"<notifications@github.com&gt;; 
发送时间: 2019年12月9日(星期一) 下午2:14
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "1028106567"<1028106567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] 执行初始化SQL报错 (#1346)




图片看不清楚，麻烦再传输一次。

**Comment by xuxueli** [comment]
你好，2.1.1 字符编码有调整，如果遇到上述索引长度问题，有如下两个解决方式：
1、mysql版本升级到mysql 5.7+；
2、修改registry相关表的 row format 格式为 Dynamic ；
