### ISSUE TITLE
unexpected end of file错误

### ISSUE THREAD

**Issue by zhangjing007** [xuxueli/xxl-job#1347]
### 当我通过任务调度中心去启动默认的执行器（自带的那个执行器），启动后查看项目运行情况基本上没问题，但是当我修改执行器的参数后，报错：
![image](https://user-images.githubusercontent.com/24825020/70386814-649f1900-19d8-11ea-9dd7-254234db147d.png)
### 修改的参数的地方：
![image](https://user-images.githubusercontent.com/24825020/70386823-8bf5e600-19d8-11ea-8be4-7df86b212065.png)

**Comment by zhipingwu** [comment]
看不到图片，能再发一次吗

**Comment by zhangjing007** [comment]
> 看不到图片，能再发一次吗

![image](https://user-images.githubusercontent.com/24825020/70388991-8d350c00-19f4-11ea-8b20-6e3de2def6eb.png)
![image](https://user-images.githubusercontent.com/24825020/70388995-945c1a00-19f4-11ea-8aa4-1f9a076ca389.png)

**Comment by zhangjing007** [comment]
> 看不到图片，能再发一次吗
![image](https://user-images.githubusercontent.com/24825020/70389013-ce2d2080-19f4-11ea-8c31-e3096356b9a5.png)
![image](https://user-images.githubusercontent.com/24825020/70389017-d4230180-19f4-11ea-8e19-9ad08cc13d9b.png)

**Comment by zhangjing007** [comment]
已重发




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhipingwu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 晚上7:53
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"ZJInfo"<2361296320@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] unexpected end of file错误 (#1347)




看不到图片，能再发一次吗
