### ISSUE TITLE
麻烦说明下V2.1.0 升级为 V2.1.1需要注意哪些问题?

### ISSUE THREAD

**Issue by kbigbus** [xuxueli/xxl-job#1349]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
V2.1.0
### Expected behavior
准备升级到V2.1.1, 但是怕出坑
### Other information
希望作者能提供下版本升级注意的点, 最好是每个版本能标注出是否支持平滑过度

**Comment by xuxueli** [comment]
你好，建议等待升级2.1.2，将于近期上级。
