### ISSUE TITLE
1.9.1版本迁移到2.1.1执行器记录和定时任务迁移步骤

### ISSUE THREAD

**Issue by strongant** [xuxueli/xxl-job#1350]
1. 在1.9.1的调度中心库导出所有执行器记录，导出SQL：

select id,
app_name,
title,
`order`,
address_type
from 
xxl_job_qrtz_trigger_group

2. 将记录导出为SQL文件后，修改表名为 xxl_job_qrtz_trigger_group 为 xxl_job_group ， 然后在2.1.1的调度中心库执行导出的SQL脚本；

3. 在 1.9.1 的调度中心导出所有定时任务的记录，导出SQL：

select id,
job_group,
job_cron,
job_desc,
add_time,
update_time,
author,
alarm_email,
executor_route_strategy,
executor_handler,
executor_param,
executor_block_strategy,
glue_type,
glue_source,
glue_remark,
glue_updatetime,
child_jobid,
executor_timeout from xxl_job_qrtz_trigger_info;

4. 将定时任务的SQL导出脚本表名“xxl_job_qrtz_trigger_info”修改为“xxl_job_info”，在2.1.1的调度中心库导入即可。

5. 注意导入前清空2.1.1调度中心执行器表和定时任务表，脚本如下：

truncate table xxl_job_group;
truncate table xxl_job_info;

6. 2.1.1 支持执行器级别的用户权限，新版调度中心迁移后，我们将旧版本的任务全量导入后，建立不同角色的用户，为每个用户绑定不同的执行器，进行执行器级别的权限隔离。

**Comment by xuxueli** [comment]
👍

**Comment by xuxueli** [comment]
v2.1.2已发布，迁移流程和基本2.1.1一致：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2

**Comment by guodage** [comment]
2.0.2 迁到 2.1.1，略有变更
跑完初始化table的sql后，执行这些：

-- 同步执行器
insert into xxl_job_group select * from XXL_JOB_QRTZ_TRIGGER_GROUP;
-- 同步任务详情（多了三个默认字段）
insert into xxl_job_info select id , job_group , job_cron , job_desc , add_time , update_time , author , alarm_email , executor_route_strategy , executor_handler , executor_param , executor_block_strategy , executor_timeout , executor_fail_retry_count , glue_type , glue_source , glue_remark , glue_updatetime , child_jobid , '0' , '0' , '0' from XXL_JOB_QRTZ_TRIGGER_INFO;
-- 同步当前任务调度状态
update xxl_job_info set trigger_status=1 where id in (select JOB_NAME from XXL_JOB_QRTZ_TRIGGERS);
