### ISSUE TITLE
2.1.1版本执行器与nacos不兼容 

### ISSUE THREAD

**Issue by Lyeluo** [xuxueli/xxl-job#1352]
启动报错：
***************************
APPLICATION FAILED TO START
***************************

Description:

Application failed to connect to Nacos server: ""

Action:

Please check your Nacos server config

**Comment by laolooong** [comment]
2.1.1版本和nacos应该是可以兼容的，我现在用nacos当做注册中心和发现中心
bootstrap.properties中的配置供你参考

spring.application.name=my-scheduler

spring.main.allow-bean-definition-overriding=true

spring.cloud.nacos.config.server-addr=xx.xx.xx.xx:8848
spring.cloud.nacos.discovery.server-addr=xx.xx.xx.xx:8848
spring.cloud.nacos.config.file-extension=yml

##开发环境的nacos配置
spring.profiles.active=dev
spring.cloud.nacos.config.namespace=XXXXXXXXXXX
spring.cloud.nacos.discovery.namespace=XXXXXXXXXXXXxxx
spring.cloud.inetutils.preferred-networks=xx.xx.xx.

**Comment by Lyeluo** [comment]
@laolooong 谢谢你的回答，我把我的bootstrap文件改成properties又revert回yml就好了，我也不晓得咋回事，有可能是我的配置文件格式的问题。。
