### ISSUE TITLE
集群分片任务没有按预期工作

### ISSUE THREAD

**Issue by LyndonZhao** [xuxueli/xxl-job#1356]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1
### Expected behavior
三台机器分片执行一个任务, 故意让其中一台挂掉, 希望其分片任务能让其他两台机器执行.
### Actual behavior
xxl-job-admin的任务调度中心始终无法检测到分片机器已经挂了, 任务的执行结果一直空白
### Steps to reproduce the behavior
见 Expected behavior和Actual behavior
### Other information

**Comment by xuxueli** [comment]
你好，执行器需要主动回调失败结果，才会触发失败重试。如果强杀进程，回调结果丢失不会触发回调的。

**Comment by LyndonZhao** [comment]
你好, 雪里大神.

我用java -jar启动两个任务, 再用idea更改代码, 
让第三个任务在执行一次返回错误或者抛出异常.
此时第三个任务的分片仍然没有转移到前面两个任务中一个中去执行.
此时, 第三个任务直接返回失败结果.

所以这可能还不是您说的"主动回调失败结果". 
那请问怎么才能实现主动回调失败结果呢?

**Comment by LyndonZhao** [comment]
@xuxueli 
你好, 雪里大神.

我用java -jar启动两个任务, 再用idea更改代码,
让第三个任务在执行一次返回错误或者抛出异常.
此时第三个任务的分片仍然没有转移到前面两个任务中一个中去执行.
此时, 第三个任务直接返回失败结果.

所以这可能还不是您说的"主动回调失败结果".
那请问怎么才能实现主动回调失败结果呢?

**Comment by LyndonZhao** [comment]
@xuxueli
您好, 雪里大神.

从文档和源代码(XxlJobTrigger.processTrigger)看, 
现在是无法实现执行器返回失败的结果的故障转移.
需要改造这个函数才能实现, 谢谢雪里大神.
