### ISSUE TITLE
JobRegistryMonitorHelper 循环中断问题

### ISSUE THREAD

**Issue by alicgq** [xuxueli/xxl-job#1359]
Please answer some questions before submitting your issue. Thanks!

JobGroup遍历过程中，由于某一个Group处理异常，后续的Group不再处理，最终导致后续的Group的注册地址不能被更新

**Comment by alicgq** [comment]
查看过当前master代码，依然存在此问题

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。

**Comment by alicgq** [comment]
> 你好，问题无法复现，需要进一步提供复现步骤。

复现很简单的：group的adreelist长度限制小一点，2个group，第一个group注册数量多一些，报DAO错误即可复现第二个group不处理
