### ISSUE TITLE
提供繁體中文包

### ISSUE THREAD

**Issue by chuwelee** [xuxueli/xxl-job#1360]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Other information

繁體中文包
解壓縮後放置 xxl-job-admin/src/main/resources/i18n/

xxl-job-admin/src/main/resources/application.properties 修改
xxl.job.i18n=zh_TC
[message_zh_TC.zip](https://github.com/xuxueli/xxl-job/files/3949783/message_zh_TC.zip)

**Comment by xuxueli** [comment]
你好，感谢关注！
可以直接提交PR的啊，提交之后会合并到master分支中。

**Comment by xuxueli** [comment]
你好，中文繁体语言支持已经推送master分支，可以pull master分支体验。
