### ISSUE TITLE
执行器注册的时候提示80端口调不通

### ISSUE THREAD

**Issue by z-hanwen** [xuxueli/xxl-job#1363]
执行器注册的时候提示80端口调用不通
我们这边都是https的访问，只有443的端口才能访问
address配置的也是https的地址，为什么会访问80端口呢，或者如何修改呢

**Comment by xuxueli** [comment]
你好，”执行器回调地址https兼容支持“ 的优化已经推送至master分支，可以pull master体验下，将会在下个版本发布。
