### ISSUE TITLE
自定义JobHandler时使用XxlJobLogger打日志会中断

### ISSUE THREAD

**Issue by YongCloud** [xuxueli/xxl-job#1364]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
自定义JobHandler使用XxlJobLogger正常打日志，Web端可以正常查看
### Actual behavior
当打印了一个较长的日志信息（应用中是一个SQL）后，接下来的日志就不再打印了
### Steps to reproduce the behavior
在自定义的JobHandler中，使用XxlJobLogger打印日志。
关键代码如下：
String srcSQL = ...
XxlJobLogger.log("fetch data, SQL: {}", srcSQL);
XxlJobLogger.log("other log...");
实际结果：
fetch data, SQL: select DATAID,DEVICENO,TESTTIME,LONGITUDE,POLICESTATION,LATITUDE from MY_TABLE_XXX where DBTIME>=TO_DATE(:start,'yyyy-mm-dd hh24:mi:ss') and DBTIME----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=200, msg=null, content=null]
2019-12-10 15:34:00 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[190]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

可以看到：
1.完整的SQL没打印出来；
2.打印SQL之后的日志再也没打印了。
### Other information
希望官方帮忙看下什么原因

**Comment by xuxueli** [comment]
无法复现，需要提供完整的稳定复现数据。

**Comment by YongCloud** [comment]
> 无法复现，需要提供完整的稳定复现数据。

我给你复现方法吧。
step1：在xxl-job-executor-sample-springboot项目的com.xxl.job.executor.service.jobhandler包下新建一个自定义JobHandler。源代码在这边：
https://github.com/YongCloud/JavaRepo/blob/master/TestLogJobHandler.java
step2：调度中心新建一个任务，运行模式是BEAN，JobHandler写自定义的testLogJobHandler，再填上其他必填项，保存。
step3：执行刚刚新建的任务，查看日志，就会出现我上面说的问题，日志打印会中断。

**Comment by YongCloud** [comment]
@xuxueli 我提供了详细的复现步骤，请帮忙抽时间复现下问题并解决。感谢！

**Comment by YongCloud** [comment]
@xuxueli 上面的问题，我自己追溯了下，发现打印到日志文件里面的日志是完整和正常的，但是调度中心通过RPC去取来Web端展示的日志却是不完整的。

**Comment by xuxueli** [comment]
你好，之前问题推测是json组件导致。master分支已经推送了修复代码，可以 pull master 体验下。新版将会不日发布。
