### ISSUE TITLE
防止重复执行

### ISSUE THREAD

**Issue by wzxit** [xuxueli/xxl-job#1366]
private final static int permits = 1;
private final static Semaphore sem = new Semaphore(permits);
@Override
    public ReturnT<String> execute(String param) {
        synchronized (this) {
            if (sem.availablePermits() < permits) {
                XxlJobLogger.log("该handler正在执行，没有足够的执行许可次数，任务被抛弃");
                return ReturnT.SUCCESS;
            }
        }
        try {
            sem.acquire(permits);
            doExecute();
        } catch (Throwable e) {
            XxlJobLogger.log(e);
            return ReturnT.FAIL;
        } finally {
            sem.release(permits);
        }
        return ReturnT.SUCCESS;
    }
代码如上：但是正在执行时候下一个代码进来不执行synchronized里面的内容

**Comment by xuxueli** [comment]
你好，这是单机防止重复触发的方式。单机可以借助提供的阻塞策略方式重复重发的啊。
