### ISSUE TITLE
如果这个功能可以尽快加入就完美了

### ISSUE THREAD

**Issue by kinbod** [xuxueli/xxl-job#1368]
Please answer some questions before submitting your issue. Thanks!

### Steps to reproduce the behavior
、DAG流程任务：替换子任务，支持参数传递：配置并列的”a-b、b-c”路径列表，构成串行、并行、dag任务流程，”dagre-d3”绘图；任务依赖，流程图，子任务+会签任务，各节点日志；支持根据成功、失败选择分支；
### Other information

**Comment by xfworld** [comment]
你这是流程引擎的需求啊

**Comment by hjki456789** [comment]
自动化数据流程处理。

**Comment by kinbod** [comment]
> 自动化数据流程处理。

可视化配置

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
