### ISSUE TITLE
手动注册，执行任务提示连接超时

### ISSUE THREAD

**Issue by z-hanwen** [xuxueli/xxl-job#1369]
自动注册的话，我们这边会出现注册中兴和执行器在2台机器上ip相同
的情况，然后就调用不通了，我换成手动注册，地址填写执行器的域名访问地址，
域名在注册中心的机器上可以ping通，执行任务一直报链接超时。手动注册的时候不能填写域名吗，还是什么问题？

**Comment by xuxueli** [comment]
你好，手动注册的地址需要些 IP:PORT 格式的地址。

**Comment by z-hanwen** [comment]
只能使用ip：port格式的是吗
