### ISSUE TITLE
SimpleDateFormat是非线程安全的，推荐使用FastDateFormat代替

### ISSUE THREAD

**Issue by solosky** [xuxueli/xxl-job#137]
https://github.com/xuxueli/xxl-job/blob/b0f44ed973daf68685add22d5ac826d319f46ca4/xxl-job-core/src/main/java/com/xxl/job/core/log/XxlJobLogger.java#L15

**Comment by change1st** [comment]
我改为了joda-time，java8也可以用自带的

**Comment by xuxueli** [comment]
以优化处理，请pull master代码体验。
