### ISSUE TITLE
广播任务支持不分片

### ISSUE THREAD

**Issue by msdemt** [xuxueli/xxl-job#1372]
场景如下：

在一个广播任务中，有5个执行器，4个成功，1个失败，则认定该广播任务失败，5个执行器的子任务都不会执行。

只有当5个执行器的任务都执行成功后，该5个执行器的子任务才会执行

希望能够支持这种模式，谢谢

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/1116
