### ISSUE TITLE
xxl.job.admin.addresses=https://127.0.0.1:79443/xxl-job-admin能否增加https支持

### ISSUE THREAD

**Issue by xiaojun0621** [xuxueli/xxl-job#1375]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xiaojun0621** [comment]
将xxl-job-admin项目部署在基于https请求的tomcat的中时，执行JobHandler项目中xxl-job.propierties中xxl.job.admin.addresses地址不支持填写

**Comment by xuxueli** [comment]
你好，最新版本以支持。
