### ISSUE TITLE
路由策略能否同时支持故障转移 + 轮询/随机等？

### ISSUE THREAD

**Issue by willzhujian** [xuxueli/xxl-job#1376]
路由策略能否同时支持 故障转移 + 轮询/随机等？目前的故障转移策略是所有任务都在一台机器上执行。望支持，对小公司还是有必要的

**Comment by king-kuiyuan** [comment]
支持自定义的路由策略

**Comment by willzhujian** [comment]
这要改源代码呀，以后升级不就很麻烦

**Comment by willzhujian** [comment]
> 支持自定义的路由策略

这要改源代码呀，以后升级不就很麻烦
