### ISSUE TITLE
执行器怎么通过rpc方式，调用job-admin服务的接口（或某个controller、Service方法）

### ISSUE THREAD

**Issue by 6haining** [xuxueli/xxl-job#1377]
示例场景描述：
某运营人员在企业后台，创建了一个活动（表单），并设置了启动、禁用时间。
保存完成后，要自动通过rpc调用job-admin的接口，新增并发起一个任务（一次性任务：按时启用或禁用这个活动）。

注：xxl-job-admin和自己的服务是分开部署的，不允许自己的服务直接调用、写入xxl-job的数据库。不允许Controller方法使用@PermissionLimit(limit=false)绕过权限验证。
我通过httpclient，调用Controller接口，会有权限验证，被拦截到登录页……

@xuxueli 大佬们，谁知道有没有可通过xxl-job自研的RPC，内部通讯调用job-admin服务，创建、修改任务？

**Comment by xiaoluobotouzi** [comment]
accessToken

**Comment by xuxueli** [comment]
你好，可以参考执行器，内部有RPC请求调度中心的逻辑。

**Comment by firstep** [comment]
xxljob开源协议决定我们不能改controller的PermissionLimit注解。
所以直接用cookie就好了，cookie的XXL_JOB_LOGIN_IDENTITY字段实际就是账号和密码(md5)的json串做hex，LoginService.makeToken函数有生成的方式

**Comment by firstep** [comment]
xxljob开源协议决定我们不能改controller的PermissionLimit注解。
所以直接用cookie就好了，cookie的XXL_JOB_LOGIN_IDENTITY字段实际就是账号和密码(md5)的json串做hex，LoginService.makeToken函数有生成的方式

**Comment by lianbitangjin** [comment]
几乎相同的需求，怎么处理啊
