### ISSUE TITLE
xxl-job-core not bind ip

### ISSUE THREAD

**Issue by msgcode** [xuxueli/xxl-job#138]
xxl-job-core所启动的jetty没有配置绑定ip 导致有挖矿机来袭。后来在jetty的Connector加上绑定xxl-job的注册ip后解决。希望作者采纳。

**Comment by xuxueli** [comment]
你好，感谢您的建议！
针对上述提到的建议，在master分支已经做了相应调整，将会跟随下个版本一起发布。

**Comment by JaleelLiu** [comment]
感谢你的回应和对开源社区的奉献。

**Comment by xuxueli** [comment]
@msgcode 你好， 线上接到多起反馈多网卡情况下手动设置IP情况下会导致IP绑定失败。所以，需要暂时将jetty绑定IP的逻辑取消掉，望知晓。

响应的IP设置优化方案仍在排期调研中。

**Comment by xuxueli** [comment]
你好，最新版本已经移除了Jetty，可以升级体验下。
