### ISSUE TITLE
在执行任务后，一直回调失败

### ISSUE THREAD

**Issue by cjm327** [xuxueli/xxl-job#1382]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

version：2.1.2

### Actual behavior
在执行任务后，一致回调失败，显示错误如下
ReturnT [code=500,msg=the request data invalid, content=null]

### Steps to reproduce the behavior

在返回的对象ReturnT的msg或content参数中放JSON字符串就会议一致导致回调报错，我测试过用Jackson就会报这个错，但是用阿里的Fastjson及没这个样的问题，后期是否会考虑更换json工具包呢？

### Other information

盼望答复，感谢！

**Comment by 6haining** [comment]
Jackson反序列化解析的大bug：
json字符中包含 \" 时，要转为 \\\"
O__O "…

**Comment by 6haining** [comment]
Jackson反序列化解析的大bug：
json字符中包含 \\\" 时，要转为 \\\\\\\"
O__O "…

**Comment by cjm327** [comment]
而且不止是这一个问题，我发现如果ReturnT携带msg 和content，content居然没显示出来。。

**Comment by cjm327** [comment]
还是jackson反序列化的问题。。

**Comment by xuxueli** [comment]
高版本已经修复这问题。

**Comment by jzdayz** [comment]
> 而且不止是这一个问题，我发现如果ReturnT携带msg 和content，content居然没显示出来。。

content是在代码里面故意去掉的
