### ISSUE TITLE
建议添加任务复制功能

### ISSUE THREAD

**Issue by jiadongpo** [xuxueli/xxl-job#139]
类似的任务比较好，每次都新建任务比较麻烦，如果有clone会方便些

**Comment by xuxueli** [comment]
你好，感谢关注啊！
任务clone功能已经记录下来，后面会排期跟进，在此感谢提供建议啊：）

**Comment by cjm327** [comment]
我自己悄悄的修改了代码，实现了

**Comment by xuxueli** [comment]
你好，复制功能已经实现并推送master分子，可以pull master分支体验下。
