### ISSUE TITLE
 Scope 'step' is not active for the current thread

### ISSUE THREAD

**Issue by ericbu88** [xuxueli/xxl-job#1390]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
正常调度spring batch job
### Actual behavior
Error creating bean with name 'xxlJobExecutor' defined in class path resource [cn/porsche/smamo/aggregator/job/config/XxlJobConfig.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.connectorProcessor': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
![image](https://user-images.githubusercontent.com/35948359/71145201-b1e27c80-225b-11ea-87e4-faa333cb9d7f.png)

### Steps to reproduce the behavior
XXL-job集成spring batch， 使用JobLauncher调用带动态JobParameters的Job， 因此step上加了@StepScope注解。
### Other information
spring batch4.1.3， spring boot 2.1.11

**Comment by xuxueli** [comment]
最新版本 “XxlJobSpringExecutor” 逻辑有调整，历史项目中该组件的配置方式请参考Sample示例项目进行调整，尤其注意需要移除组件的init和destroy方法；

**Comment by chris-peng** [comment]
我也碰到这个问题了，兄弟你解决了吗

**Comment by ericbu88** [comment]
> 我也碰到这个问题了，兄弟你解决了吗
没有，我退回2.1.1了

**Comment by chris-peng** [comment]
> > 我也碰到这个问题了，兄弟你解决了吗
> 
> 没有，我退回2.1.1了

刚刚正好找到原因，是XxlJobSpringExecutor在执行initJobHandlerMethodRepository方法时，主动触发spring创建bean了，但是加了StepScope注解的bean实际上是需要延迟创建的，这里其实需要忽略这部分bean，我把这个方法修改了一下，可以临时用一下

`private void initJobHandlerMethodRepository(ApplicationContext applicationContext) {
        if (applicationContext == null) {
            return;
        }

        // init job handler from method
        String[] beanDefinitionNames = applicationContext.getBeanDefinitionNames();
        for (String beanDefinitionName : beanDefinitionNames) {
            // 忽略spring batch中需要延迟创建的bean
            if(applicationContext instanceof AbstractApplicationContext){
                AbstractApplicationContext abstractApplicationContext = (AbstractApplicationContext) applicationContext;
                BeanDefinition beanDefinition = abstractApplicationContext.getBeanFactory().getBeanDefinition(beanDefinitionName);
                if(beanDefinition != null && ("step".equals(beanDefinition.getScope()) || "job".equals(beanDefinition.getScope()))){
                    continue;
                }
            }
            Object bean = applicationContext.getBean(beanDefinitionName);
            Method[] methods = bean.getClass().getDeclaredMethods();
            for (Method method: methods) {
                XxlJob xxlJob = AnnotationUtils.findAnnotation(method, XxlJob.class);
                if (xxlJob != null) {

                    // name
                    String name = xxlJob.value();
                    if (name.trim().length() == 0) {
                        throw new RuntimeException("xxl-job method-jobhandler name invalid, for[" + bean.getClass() + "#"+ method.getName() +"] .");
                    }
                    if (loadJobHandler(name) != null) {
                        throw new RuntimeException("xxl-job jobhandler[" + name + "] naming conflicts.");
                    }

                    // execute method
                    if (!(method.getParameterTypes()!=null && method.getParameterTypes().length==1 && method.getParameterTypes()[0].isAssignableFrom(String.class))) {
                        throw new RuntimeException("xxl-job method-jobhandler param-classtype invalid, for[" + bean.getClass() + "#"+ method.getName() +"] , " +
                                "The correct method format like \" public ReturnT<String> execute(String param) \" .");
                    }
                    if (!method.getReturnType().isAssignableFrom(ReturnT.class)) {
                        throw new RuntimeException("xxl-job method-jobhandler return-classtype invalid, for[" + bean.getClass() + "#"+ method.getName() +"] , " +
                                "The correct method format like \" public ReturnT<String> execute(String param) \" .");
                    }
                    method.setAccessible(true);

                    // init and destory
                    Method initMethod = null;
                    Method destroyMethod = null;

                    if(xxlJob.init().trim().length() > 0) {
                        try {
                            initMethod = bean.getClass().getDeclaredMethod(xxlJob.init());
                            initMethod.setAccessible(true);
                        } catch (NoSuchMethodException e) {
                            throw new RuntimeException("xxl-job method-jobhandler initMethod invalid, for[" + bean.getClass() + "#"+ method.getName() +"] .");
                        }
                    }
                    if(xxlJob.destroy().trim().length() > 0) {
                        try {
                            destroyMethod = bean.getClass().getDeclaredMethod(xxlJob.destroy());
                            destroyMethod.setAccessible(true);
                        } catch (NoSuchMethodException e) {
                            throw new RuntimeException("xxl-job method-jobhandler destroyMethod invalid, for[" + bean.getClass() + "#"+ method.getName() +"] .");
                        }
                    }

                    // registry jobhandler
                    registJobHandler(name, new MethodJobHandler(bean, method, initMethod, destroyMethod));
                }
            }
        }
    }`

**Comment by kunghsu1021** [comment]
解决办法1
重写XxlJobSpringExecutor，去掉initJobHandlerMethodRepository方法。不过这就意味着不能再用@XxlJob注解。意味着削减了一部分功能。

解决办法2
将版本退回到2.1.1.

解决办法3（推荐）
重写XxlJobSpringExecutor，多定义一个注解就行了，例如@XxlJobClass，在@XxlJob注解出现的类上多加一个注解，然后用spring的工具类方法专门找加了某种注解的bean。。
        String[] beanDefinitionNames = applicationContext.getBeanNamesForAnnotation(XxlJobClass.class);

@xuxueli
