### ISSUE TITLE
xxl-job两个场景需求目前未找到解决方案

### ISSUE THREAD

**Issue by zhengyunpengby** [xuxueli/xxl-job#1391]
1.获取标准调度时间
  直接在任务中通过获取系统时间可能存在误差（机器性能问题、时间为同步）
  如：cron定时为每分钟执行一次，需要在任务handle中获取准确的每分0秒的时间，目前通过newdate()方式存在时间差，对一些业务场景不适用
  注：若首次执行失败，目前日志中的调度时间会是第二次调度。调度可能跟执行时间有误差
2.任务指定定时时间
  任务每分钟执行一次。执行过程中执行失败，停止任务，手动修改（手动处理时间10分钟），则再次开启任务时间则为从当前时间开始，停止的10分钟跳过了。
  若可以指定启动时间，则可以由上次定制时间开始每分钟启动一次，则可以补充跳过的时间任务

**Comment by xuxueli** [comment]
你好，这种场景建议是任务handler里自己维护一个最后一次运行结束时间，每次执行时比对这个时间来处理跳过的时间。

**Comment by zhengyunpengby** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        收到，谢谢指导
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhengyunpengby
                            
                    
                        
                            
                                    zhengyunpengby@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年2月27日 16:50，许雪里<notifications@github.com> 写道： 


你好，这种场景建议是任务handler里自己维护一个最后一次运行结束时间，每次执行时比对这个时间来处理跳过的时间。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
