### ISSUE TITLE
集成2.1.2版本  Hession序列化失败 求解决

### ISSUE THREAD

**Issue by qingc1996** [xuxueli/xxl-job#1392]
集成2.1.2版本  服务器端反序列化requestBytes失败
线上NettyHttpServerHandler中channelRead0方法中requestBytes 反序列化失败
同时抛出异常throw new XxlRpcException("xxl-rpc request data empty.")
请问什么情景下会触发这样的情况

**Comment by xuxueli** [comment]
你好，这是执行器端口服务被非法访问导致，可以排查下。

**Comment by qingc1996** [comment]
嗯嗯 雪里大神 已经 解决了

**Comment by qingc1996** [comment]
问题是出在 ：
我们的服务器上安全组端口访问权 没有配置
导致有爬虫扫描到了 调度中心端口 导致了非法请求
