### ISSUE TITLE
v2.1.1 版本 进行中状态任务日志 执行 终止任务操作后一直被当成进行中状态

### ISSUE THREAD

**Issue by rabbitlhf** [xuxueli/xxl-job#1394]
v2.1.1 版本 进行中状态任务日志 执行 终止任务操作后一直被当成进行中状态，导致还可以继续操作 终止任务 操作，继续打开执行日志重复刷新请求

**Comment by yishuijianghu** [comment]
不要再给我发信息了

**Comment by rabbitlhf** [comment]
> 不要再给我发信息了

你自己取消订阅啊

**Comment by xuxueli** [comment]
任务回调结构丢失导致，排查下回调配置数据。
