### ISSUE TITLE
分片任务执行过程中，手动下线某个执行器，剩余分片执行过程中分片总数参数怎么没有减少？

### ISSUE THREAD

**Issue by ye39zi** [xuxueli/xxl-job#1395]
Please answer some questions before submitting your issue. Thanks!
分片任务执行过程中，手动下线某个执行器，剩余分片执行过程中分片总数参数未减少？
### Which version of XXL-JOB do you using?   
使用的2.2.0-SNAPSHOT

### Steps to reproduce the behavior  
1.其中一个分片任务，并由两台机器负责执行
2.执行过程中下线某个机器
3.剩余机器在执行过程中，发现分片总数未变化

### Other information

**Comment by xuxueli** [comment]
你好，执行器下线有短暂延迟，稍等下即可。
