### ISSUE TITLE
任务使用线程池打印日志bug

### ISSUE THREAD

**Issue by losemy** [xuxueli/xxl-job#1399]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1-SNAPSHOT
### Expected behavior
每次任务日志都打印到对应日志文件
### Actual behavior
之后线程池中线程打印的日志只会打印到第一次的日志文件
### Steps to reproduce the behavior
运行任务，在任务重使用线程池运行，重复运行即可复现
### Other information
修改方案：将 XxlJobFileAppender中的InheritableThreadLocal
修改成ali的TransmittableThreadLocal即可，然后运行加上javaagent
-javaagent:/apps/jars/transmittable-thread-local-2.11.2.jar

我理解使用InheritableThreadLocal 应该就是考虑到会在任务中使用线程，而目前
来说，基本规范都是使用线程池来完成，也就意味着这个设置会失效。

**Comment by WWangYu** [comment]
我也遇到了这个问题，在使用线程池的时候，复用线程会导致job日志输出到此线程第一次创建的job日志里。

**Comment by m1a1y1u1** [comment]
找了一圈，只有问题没有解决方案吗 = =

**Comment by WWangYu** [comment]
> 找了一圈，只有问题没有解决方案吗 = =

将 InheritableThreadLocal 改为 TransmittableThreadLocal 的方案是可以解决一些问题的，如果job之间的子线程没有在同一时间共用的话，就可以正常打印日志，但是如果Job在同一时间运行过多，还是会出现日志输出错误。

**Comment by powerLeePlus** [comment]
这个问题解决了吗

**Comment by m1a1y1u1** [comment]
没有，我就将就看看，影响也不大



---原始邮件---
发件人: "powerLeePlus"<notifications@github.com&gt;
发送时间: 2020年7月21日(周二) 下午5:26
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"m1a1y1u1"<498143987@qq.com&gt;;
主题: Re: [xuxueli/xxl-job] 任务使用线程池打印日志bug (#1399)




 
这个问题解决了吗

**Comment by xuxueli** [comment]
你好，底层家住ThreadLocal匹配日志存储信息，有两种方式解决上述问题：
- 1、每个线程日志各自收集起来，线程终止时统一打印，入口任务阻塞获取线程结果；
- 2、将入口任务的日志文件信息带入下线程上下文，可以参考如下代码：
```
// 入口任务，获取日志地址
String logFileName = XxlJobContext.getXxlJobContext().getJobLogFileName();

// 线程中，赋值日志地址
XxlJobContext.getXxlJobContext().setJobLogFileName(logFileName);

```

**Comment by ukhack** [comment]
@xuxueli 

问题在新版又出现了。但现在XxlJobContext 中 jobLogFileName 不可修改，如何解决这个问题

**Comment by jiajiancheng** [comment]
version:2.2.0
亲测有效
// 入口任务，获取日志地址
XxlJobFileAppender.contextHolder.get()
// 线程中，赋值日志地址
XxlJobFileAppender.contextHolder.set()

**Comment by sdmjhca** [comment]
原因分析：出现这个问题是由于 InheritableThreadLocal变量 和 ThreadPool的thread初始化的顺序问题，
查看thread的源码发现inheritableThreadLocals会在Thread 初始化的时候赋值；
通常线程池会提前初始化一些核心线程，这些核心线程如果在InheritableThreadLocal变量初始化之前，则会导致得到的日志路径为默认路径。
       解决方案同上：即在使用线程池之前确保InheritableThreadLocal变量赋值了正确的路径

**Comment by wacgy123** [comment]
多线程异步日志的问题还没解决吗？ 2.3.0 通过XxlJobContext也赋值不了

**Comment by alixiaodi** [comment]
兄弟们这个问题简单，老夫告诉你们一个解决方案，已经验证过了
![image](https://github.com/user-attachments/assets/5893d1d8-d0d2-4758-a5f2-866c8c4a8a1f)
![image](https://github.com/user-attachments/assets/9536af87-0005-425a-8563-063230c984fa)
