### ISSUE TITLE
GLUE模式(Java) 如何支持第三方jar

### ISSUE THREAD

**Issue by xiaoluobotouzi** [xuxueli/xxl-job#1401]
如题。
xxl-job有没有交流钉钉群或微信群

**Comment by xuxueli** [comment]
你好，文档中有QQ群。

**Comment by dongluyang** [comment]
和https://github.com/xuxueli/xxl-job/issues/254，https://github.com/xuxueli/xxl-job/issues/129 一样，请看这两个吧
