### ISSUE TITLE
【xxl-job-core】BasicJsonwriter#writeObjItem转换问题

### ISSUE THREAD

**Issue by LyndonZhao** [xuxueli/xxl-job#1404]
### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
xxl-job-core中的转换jason函数com.xxl.registry.client.util.json.BasicJsonwriter#writeObjItem在进行转换Jason时，如果key/value为字符串中包含”时， 需要在"之前加上转义符。
### Actual behavior
实际情况是，com.xxl.registry.client.util.json.BasicJsonwriter#writeObjItem在进行jason转换时，并没有加转义符，导致转换后的jason在admin中无法解析， 出现异常如下txt

[xxl-job-admin jason解析异常打印.txt](https://github.com/xuxueli/xxl-job/files/3991467/xxl-job-admin.jason.txt)

需要转换的对象只如下：
[转换前的对象toString值.txt](https://github.com/xuxueli/xxl-job/files/3991471/toString.txt)

**Comment by LyndonZhao** [comment]
个人想到的修改方案是：
在com.xxl.registry.client.util.json.BasicJsonwriter#writeObjItem函数中做如下修改：

// "key:"
        if (key != null) {

            json.append(STR_SLASH).append(key.replace("\"", "\\\"")).append(STR_SLASH_STR);
        }

        // val
        if (value == null) {
            json.append("null");
        } else if (value instanceof String
                || value instanceof Byte
                || value instanceof CharSequence) {
            // string
            String tempValue = value.toString().replace("\"", "\\\"");
            json.append(STR_SLASH).append(tempValue).append(STR_SLASH);
        }

**Comment by zhangjing007** [comment]
你好，这个问题我也遇见了，你提的方案是修改依赖包中的代码，但是这个只有等官方修改，毕竟我们手里没有那个依赖的源码。那么现在官方还没有修改这个bug，请问你是怎么解决的呢？

**Comment by zhangjing007** [comment]
![image](https://user-images.githubusercontent.com/24825020/71351822-a1116e00-25af-11ea-9215-17c612c62de5.png)
这是我目前想到的办法  只有通过重新构造了

**Comment by LyndonZhao** [comment]
@zhangjing007 
如何你改这个文件，最简单方式就是引入gson依赖。
然后用将
 String requestBody = BasicJson.toJson(requestObj);
替换成
 String requestBody=new Gson().toJson(requestObj);
依赖：
`        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.6</version>
        </dependency>`

**Comment by xuxueli** [comment]
这个问题master分支已经修复，大家可以pull master分支体验下。
