### ISSUE TITLE
xxl-job开源版 大任务量下有瓶颈吗？   是否做过压测，结果如何？

### ISSUE THREAD

**Issue by 971287765zy** [xuxueli/xxl-job#1406]
xxl-job 大任务量下有瓶颈吗？

**Comment by 971287765zy** [comment]
xxl-job开源版 大任务量下有瓶颈吗？ 是否做过压测，结果如何？

**Comment by 6haining** [comment]
我觉得这个问题，着重点在于你的执行器是否支持了高并发设计。
xxl-job-core只是负责向你的执行器服务发送调度“命令”，即使它1ms发送1W次调度，要看你的执行器能不能抗住，有木有幂等拦截等等了。
xxl-job-admin也设计了基于数据库表形式的分布式锁。个人观点，欢迎纠正。

**Comment by xuxueli** [comment]
你好，可以参考这恩：https://github.com/xuxueli/xxl-job/issues/225
