### ISSUE TITLE
2.1.2版本，下次执行时间与cron表达式不相符

### ISSUE THREAD

**Issue by DspringL** [xuxueli/xxl-job#1409]
图片详见：https://gitee.com/xuxueli0323/xxl-job/issues/I177X2#note_2166732

**Comment by olicu** [comment]
你检查下是不是你系统时间和服务器时间不一致，你cron那个下次执行时间预览获取的应该是你本机的时间，而不是服务器的时间。

**Comment by xuxueli** [comment]
你好，应该是机器时钟不一致问题。确保DB和应用时区一致。

**Comment by sunqb** [comment]
@xuxueli 

这个问题建议日终的时候增加一个校验啊，以corn表达式为准，然后重置数据库里面保存的下一次执行时间

**Comment by XiaoyuWant** [comment]
@DspringL 

You can set the default timezone for a Java program using the following syntax:

```java
TimeZone timeZone = TimeZone.getTimeZone("Asia/Shanghai");
TimeZone.setDefault(timeZone);
```
