### ISSUE TITLE
2.0.2任务调度运行一段时间全部终止

### ISSUE THREAD

**Issue by limeng1111** [xuxueli/xxl-job#1410]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

### Actual behavior
调度线程超时终止后，没有新的线程生成，所有调度任务全部停止，但是调度任务的状态还是RUNNING

### Other information

**Comment by xuxueli** [comment]
你好，低版本委托给quartz触发。建议升级最新release版本，不会有上述问题。

**Comment by limeng1111** [comment]
您好，由于这个问题是线上出现的，不能随意升级，能否麻烦您给我说下是什么原因导致的呢？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "许雪里"<notifications@github.com&gt;; 
发送时间: 2020年1月19日(星期天) 晚上7:53
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "李猛"<1536593201@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] 2.0.2任务调度运行一段时间全部终止 (#1410)




你好，低版本委托给quartz触发。建议升级最新release版本，不会有上述问题。
