### ISSUE TITLE
2.0.2版本执行器执行任务之后线程没有释放，持续增长。有解决方案吗？

### ISSUE THREAD

**Issue by liaopengju** [xuxueli/xxl-job#1412]

**Comment by kongwu-** [comment]
一样的问题。。。请问你解决了吗

**Comment by liaopengju** [comment]
源码中线程池默认是50。（有新的请求线程池不论线程池中是否有空闲线程都创建新的线程直到50个为止） 所以看到线程池中的线程一直增加没有释放。

**Comment by kongwu-** [comment]
我这里是netty的线程，nioEventLoop有大量不释放，最后oom了，可能和你的情况有点区别

**Comment by liaopengju** [comment]
> 我这里是netty的线程，nioEventLoop有大量不释放，最后oom了，可能和你的情况有点区别

xxl-rpc, NettyHttpServer-serverHandlerPool-1308262792  我这边是这个线程池中的线程数一直增长 。
这个的底层是netty 不知道和你遇到的情况是否一样

**Comment by kongwu-** [comment]
好的谢谢，我这里是admin的netty client线程爆了，原因未知；猜测可能是过多无效连接，或者异常连接没有释放的原因

**Comment by kongwu-** [comment]
好的谢谢，我这里是admin的netty client线程爆了，原因未知；猜测可能是过多无效连接，或者异常连接没有释放的原因

**Comment by xuxueli** [comment]
这个问题低版本已经修复，上级到v2.1.x或以上版本可以修复。
