### ISSUE TITLE
执行器失效后已触发的任务不自动终止

### ISSUE THREAD

**Issue by hb407033** [xuxueli/xxl-job#1413]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.2
### Expected behavior
执行器终止后，任务自动终止
### Steps to reproduce the behavior
触发执行时间长的任务， 停止执行器，执行器不终止
### Other information
调度环境在k8s中， 执行器通过StatefulSet运行

**Comment by xuxueli** [comment]
你好，调度中心依赖执行器回调感知任务结果。你的问题回调结果丢失导致的。
迭代中的版本会针对这个问题进行优化，长时间处于运行中的任务会主动探测是否存活。
