### ISSUE TITLE
无法动态设置cron

### ISSUE THREAD

**Issue by dujiecn** [xuxueli/xxl-job#1415]
项目的需求是发送一个通知，里面的时间属性是动态设置的，而xxl-job的cron需要手动的配置。无法针对不同的通知设置不同的时间，因为handler就一个java类

**Comment by 6haining** [comment]
自己修改了一个动态添加任务的xxl-job，获取可给你参考。欢迎纠正：
https://github.com/6haining/xxl-job/tree/master

**Comment by xuxueli** [comment]
你好，动态设置任务时间建议借助XXL-MQ实现，自定义消费时间点。
