### ISSUE TITLE
对于大任务量的密集调度，现版本能否有好的应对方案，比如1秒中调度100次

### ISSUE THREAD

**Issue by WuJunta0** [xuxueli/xxl-job#1416]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by WuJunta0** [comment]
最新版本的xxljob

**Comment by songquanhe-gitstudy** [comment]
同问，现在的策略是未执行的任务，已队列的形式存在内存中。若某一时刻调度的任务量很大，内存应该也吃不消吧。

**Comment by xuxueli** [comment]
cron单个任务最小粒度是1s一个，任务是有上限的，数量不会太多。
如果真的有每秒上千级别的调度，可以通过执行器集群分摊压力。
