### ISSUE TITLE
线程池最大数量配置，优化建议：xxl.job.triggerpool.fast.max=本机最大CPU核数

### ISSUE THREAD

**Issue by 6haining** [xuxueli/xxl-job#1417]
线程池最大线程数量，
当前设置太大了：
xxl.job.triggerpool.fast.max=200
xxl.job.triggerpool.slow.max=100
推荐设置：
xxl.job.triggerpool.fast.max=20
xxl.job.triggerpool.slow.max=10

理由：
以（英特尔Xeon E5-2690V3）24线程处理器为例，当活动线程的最大数量大于24时，将导致单个核心线程之间频繁切换。如果再次使用docker虚拟机，单个实例分配的核心数可能小于24。
另外，系统本身还要占用一部分线程时间片！。

因此，不建议设置太多线程，以避免单核频繁切换线程，从而严重降低性能。

**Comment by xuxueli** [comment]
你好，这个调度线程池负责远程任务调度，远程通讯耗时较高因此线程池不宜设置太小。
