### ISSUE TITLE
官方提供的dockerfile文件有问题

### ISSUE THREAD

**Issue by fushiqinghuan111** [xuxueli/xxl-job#1418]
### 无法指定环境参数

![image](https://user-images.githubusercontent.com/31064707/71453279-68e37880-27c5-11ea-9c2c-0a1f4dc5177c.png)

**Comment by fushiqinghuan111** [comment]
https://blog.csdn.net/woshiyeguiren/article/details/79867320  可参考

**Comment by xuxueli** [comment]
你好，master分支已经做了优化可以参考参考下。
