### ISSUE TITLE
[BUG反馈] handler_code状态异常

### ISSUE THREAD

**Issue by yangBin666** [xuxueli/xxl-job#1419]
Please answer some questions before submitting your issue. Thanks!

### 现象
job日志执行成功后，偶尔出现handler_code=0的情况，应该为200

### 原因
服务端异步调用执行端执行，之后会更新日志信息，如果执行端在此之间回调执行结果，会发生handler_code被覆盖的情况

### 修改建议
AdminBizImpl类回调时增加判断，如果发现trigger_code==0,则休眠等待；
```
int flg=6;  
        while (log.getTriggerCode() == 0&&flg-->0) {
            //执行端很快返回结果时，可能存在服务端还未更新log，此时会出现log数据异常，增加休眠处理
            try {
                TimeUnit.MILLISECONDS.sleep(500);
            } catch (InterruptedException e) {
                return new ReturnT<String>(ReturnT.FAIL_CODE, e.getMessage());
            }
            log = xxlJobLogDao.load(handleCallbackParam.getLogId());
        }
```

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。

目前 “handle_code” 只在两个地方赋值。第一处是调度请求发送前生成日志信息，第二处是任务回调时，并没有其他会覆盖写该字段的逻辑，理论上并没有这个问题。
