### ISSUE TITLE
如果一个执行器含有10条任务，每个任务1秒执行一次，那么日志表中每天就有864000条日志记录，需要怎么处理

### ISSUE THREAD

**Issue by sunyuanchao** [xuxueli/xxl-job#142]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，任务Log是任务追踪的敏感数据，系统默认不会进行删除的，只能手动处理。
执行日志界面提供了Log清理功能，可以手动清除冗余Log。
