### ISSUE TITLE
xxl-rpc request timeout

### ISSUE THREAD

**Issue by fallingyou** [xuxueli/xxl-job#1420]
sometimes print com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:

xxl-rpc 请求超时时间超时，可否支持自定义rpc超时时间，默认的1s

**Comment by voidluffy** [comment]
[com.xxl.job.core.util.XxlJobRemotingUtil]-[xxl-job, executor ExecutorRegistryThread]-[postBody]-[146]-[ERROR] Read timed out
[xxl-job, executor ExecutorRegistryThread]-[run]-[54]-[INFO] >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='mot-executor', registryValue='106.12.93.69:9998'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Read timed out), for url :

经常出现超时的异常，算是bug吗

**Comment by xuxueli** [comment]
你好，目前默认超时3s，如果有需要可以自行调整，不过不建议调太大， 会消耗调度线程。
