### ISSUE TITLE
如何添加类似于statefuljob的任务

### ISSUE THREAD

**Issue by user-zhaoJM** [xuxueli/xxl-job#1422]
xxl-job可以实现类似于quartz的statefuljob的定时任务吗

**Comment by xuxueli** [comment]
你好，你是期望任务共享参数吗？
是期望父子任务之间共享参数？还是单个任务多次触发时共享参数？

**Comment by xuxueli** [comment]
已经规划dag流程任务覆盖了这一块，到时候可以参考下。

**Comment by xuxueli** [comment]
你好，你是希望共享变量？还是希望限制并发？如果限制并发，功能已经提供了，提供了阻塞策略。
