### ISSUE TITLE
【需求】关于xxl-job的性能表现文档

### ISSUE THREAD

**Issue by ElesG** [xuxueli/xxl-job#1426]
Please answer some questions before submitting your issue. Thanks!
感谢作者开源了这么优秀的工具！
### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
由于xxl-job是由调度中心控制定时任务调度的，一旦调度中心挂了会导致接入的全部定时任务都无法执行的情况。考虑到上传问题，期望官方能够给出有关于xxl-job性能方面的一些指标，比如能够承担的调度频率上限、接入执行器的数量、接入节点的数量、任务配置数量等。如果有生产环境使用建议就更好了。
另外也想了解关于调度任务接入后对被接入应用的性能影响的情况。
### Actual behavior
官网文档中无关于这方面具体的数据说明
### Steps to reproduce the behavior
资料来源：https://www.xuxueli.com/xxl-job/
### Other information

**Comment by xuxueli** [comment]
你好，压测报告可以参考这里：https://github.com/xuxueli/xxl-job/issues/225

**Comment by ElesG** [comment]
好的 ，感谢
