### ISSUE TITLE
高并发场景

### ISSUE THREAD

**Issue by songquanhe-gitstudy** [xuxueli/xxl-job#1429]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
请问，当有1万个job同时提交，同时创建1万个JobThread实例不会出问题吗？？？
### Other information

**Comment by yangBin666** [comment]
fast执行线程池max=200，缓存队列1000，如果高并发，线程池占满，后续任务添加会报错，调度线程会重新开始调度；
1万个任务完全不存在问题，只要不是同一时间点执行；
测试过如果同一时间超过3000个任务，就会出现问题，主要是5s内处理不了3000个任务，后续的任务一致misfire丢弃了，这个时候添加机器也没啥效果

**Comment by xuxueli** [comment]
海量任务是支持的。

调度部分，可以进行调度中心集群，支持海量调度。

执行部分，建议讲这些任务拆分到不同执行器，比如1w任务均分给10个执行器。每个执行器只需要处理1000个任务即可。
