### ISSUE TITLE
建议在任务管理的时候,支持任务克隆,就跟阿里云配置安全组一样

### ISSUE THREAD

**Issue by chenshiyun2011github** [xuxueli/xxl-job#1430]
Please answer some questions before submitting your issue. Thanks!
新建任务的时候很不方便,加个任务克隆呗,类似,阿里云服务器控制台的安全组克隆

### Which version of XXL-JOB do you using?
2.12
### Other information

**Comment by hezhiqiang8909** [comment]
正有此想法，可惜我是运维不是JAVA开发，正在努力学习，应该新版有加此功能。

**Comment by xuxueli** [comment]
你好，迭代版本已经加入了相关规划。

**Comment by chenshiyun2011github** [comment]
那就真的太棒了,有克隆的话,操作任务的时候就会简单很多,克隆后小改部分参数就可以直接使用

**Comment by xuxueli** [comment]
你好，任务复制功能已经推送master分支，可以pull master体验下。将会跟随下个版本发布。
