### ISSUE TITLE
ReturnT content null问题

### ISSUE THREAD

**Issue by zealotTL** [xuxueli/xxl-job#1436]
com.xxl.job.core.thread.JobThread 类，162行
`executeResult.setContent(null);	// limit obj size`
这个强制设成null，什么原因？

**Comment by feishu2019** [comment]
不设置成null，回调请求会报一个请求参数无效的bug，不知道作者是否修复了

**Comment by xuxueli** [comment]
任务结果里，这个泛型属性没用到。
