### ISSUE TITLE
点击执行一次输入任务参数之后，后面所有的自动任务都会使用之前的任务参数

### ISSUE THREAD

**Issue by weinianta** [xuxueli/xxl-job#1439]
版本：2.1.2

![image](https://user-images.githubusercontent.com/13379708/71810611-bb6a4200-30ad-11ea-8085-10a35cb650a2.png)

在手动执行一次输入任务参数，比如1

后面自动执行本任务的时候，任务参数会一直带着1

但是点击编辑里面的输入参数就不会有这个问题。

**Comment by xuxueli** [comment]
你看，手动执行一次时的参数只有本次有效。

问题无法复现，确认是不是手动触发的。
