### ISSUE TITLE
调度中心集群部署时的会话不能同步？

### ISSUE THREAD

**Issue by crossoverJie** [xuxueli/xxl-job#144]
### Which version of XXL-JOB do you using?
1.8.2-SNAPSHOT

### Expected behavior
分别访问两台Tomcat应该同时登录。

### Actual behavior
登录了其中一个，另一个还需要重新登录。

### Steps to reproduce the behavior
分别部署在: 
xx.xx.xx.1:8080/xxl-job
xx.xx.xx.2:8080/xxl-job
登录其中一个，再访问另一个。

### Other information
是我的部署姿势不对，还是集群部署时并不支持会话同步？大概看了下代码登录用的是cookie存储的会话信息？

**Comment by xuxueli** [comment]
你好，调度中心集群时，推荐通过nginx等为集群配置一个统一内部域名，这样cookie写在域名下，两台机器都可以读取到，实现集群登录认证。如果不配置域名，只能通过启动一个节点来访问了。
但是，底层任务调度还是集群进行，不会受到影响的。

**Comment by crossoverJie** [comment]
@xuxueli  感谢解答，是我的问题了，忘记配NG来负载了。

还是得通过节点来负载,通过节点来访问也有可能出现节点挂了的情况。

**Comment by luobotiantang** [comment]
问一下执行器配置地址是下面这样吗？ 通过nginx配置集群
xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin,http://127.0.0.1:8081/xxl-job-admin 
还是这样？ 
xxl.job.admin.addresses=http://www.xxxxll.com/xxl-job-admin 
都可以吗？

**Comment by luobotiantang** [comment]
还有就是xxl-job不用nginx做集群有什么影响？
