### ISSUE TITLE
调度中心调度任务后报错

### ISSUE THREAD

**Issue by ProgrammerMonkey** [xuxueli/xxl-job#1444]
警告: Hessian/Burlap: 'com.xxl.rpc.remoting.net.params.Beat$1' is an unknown class in ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
sun.misc.Launcher$AppClassLoader@18b4aac2
:
java.lang.ClassNotFoundException: com.xxl.rpc.remoting.net.params.Beat$1

客户端maven版本号：2.0.1

**Comment by xuxueli** [comment]
你好，应该是版本冲突导致，确认两端版本是否一致。
