### ISSUE TITLE
bean对象可能为空，需要进行非空校验

### ISSUE THREAD

**Issue by zhouyongshen** [xuxueli/xxl-job#1445]
https://github.com/xuxueli/xxl-job/blob/d41c992ca1c5f3996e2faceb1773448493a68235/xxl-job-core/src/main/java/com/xxl/job/core/executor/impl/XxlJobSpringExecutor.java#L83

**Comment by zhouyongshen** [comment]
使用@Bean 注解注入bean对象但是返回一个null 此时启动便会报错
   @Bean
    public Object config() {
        //do something
        return null;
    }

**Comment by xuxueli** [comment]
你好，最新master分支已经推送了相关问题修复，可以pull master体验下。
