### ISSUE TITLE
界面BUG

### ISSUE THREAD

**Issue by BigStrong0717** [xuxueli/xxl-job#1447]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
不弹出告警信息
### Actual behavior
弹出告警信息
### Steps to reproduce the behavior
- 在任务管理中，进入到某任务的GLUE IDE。
- 点击保存并输入源码备注之后，回车会出现systm error的错误。
- 而点击保存时，不会出现该错误。
### 图片如下:
![image](https://user-images.githubusercontent.com/31980819/71964145-fef0b780-3237-11ea-9d8a-60dc72f9c01b.png)
![image](https://user-images.githubusercontent.com/31980819/71964162-044e0200-3238-11ea-90c1-7420893a28ef.png)

**Comment by 428hanlong** [comment]
我也出现了

**Comment by chinacculy** [comment]
i got this error, too

**Comment by xuxueli** [comment]
已修复并推送master分支，可以pull master分支体验。
将会跟随 v2.2.0 版本发布。
