### ISSUE TITLE
当使用spring-boot-devtools,代码重新加载bug

### ISSUE THREAD

**Issue by joney888999** [xuxueli/xxl-job#1449]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2

### Expected behavior
修改代码重启之后执行器应该能够正常在线

### Actual behavior
springboot重新加载重启之后，执行器没办法恢复在线状态

### Steps to reproduce the behavior
使用spring-boot-devtools，修改代码之后，重新加载应用，发现执行器下线了，但是重启之后
确没看到执行器在线

### Other information

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤；
