### ISSUE TITLE
分片序号重排优化与执行器自动降级（v2.1.2）

### ISSUE THREAD

**Issue by RexFang** [xuxueli/xxl-job#1450]
版本：v2.1.2

一、分片序号进行重排时，发现是所有执行器的需要都会发生变化，这个现象在极端情况下，会导致通过分片数量、分片序号进行数据区间分割时，数据区间冲突，进而导致数据重复处理的问题，建议优化序号重排策略，例如有：0、1、2 三个分片，当分片 0 宕机时，把序号最大的 2 改为序号 0，确保分片 1 不受影响，而非把剩余所有执行器的分片序号都减一。

二、在分片策略下，执行器在运行时出现运行时异常，触发器还是会在下个触发点触发该执行器，需要人工停掉有问题的执行器才会进行分片的重排，即使在执行器已经返回执行失败的结果给到触发器。建议添加自动降级功能。

**Comment by xuxueli** [comment]
感谢反馈。
1、分片序号依靠执行器节点实时计算，如果固定数量，会丧失动态分片能力。
2、分片故障时执行器正常会自动下线，故障机器不参与分片计算。可以确认下宕机节点下线是否正常。

**Comment by RexFang** [comment]
> 感谢反馈。
> 1、分片序号依靠执行器节点实时计算，如果固定数量，会丧失动态分片能力。
> 2、分片故障时执行器正常会自动下线，故障机器不参与分片计算。可以确认下宕机节点下线是否正常。

感谢处理。
1、结合分布式锁解决了数据区间冲突问题；
2、我再验证一下哈，3Q。
