### ISSUE TITLE
建议实现DAG流程任务，这是大数据项目必须的功能(附开源参考)

### ISSUE THREAD

**Issue by viokuma** [xuxueli/xxl-job#1451]
你好，我们项目已经上了XXL-JOB很长一段时间了，主要是觉得XXL容易开发和管理，但是却缺少多流程任务管理，这在大数据任务中经常有这种用法，当前子任务的功能太薄弱了。建议完成DAG流程任务，这才能让XXL-JOB成为一个生产级别的、通用的调度框架，其他调度框架真的比较难用。

以下是一个开源的调度，已完成DAG流程图
https://github.com/apache/incubator-dolphinscheduler

![image](https://user-images.githubusercontent.com/1708895/72130938-d7275e00-33b5-11ea-81d9-fb203a0f0ed3.png)

**Comment by w5862338** [comment]
同求该功能

**Comment by xuxueli** [comment]
感谢支持，规划 v2.2.x 主推这个功能。

**Comment by WeiYe-Jing** [comment]
v2.2.x预计什么时候开发啊

**Comment by Lvbm** [comment]
顶一个，希望增加多父任务执行完毕后再触发子任务，仅执行一次，而不是每个父任务执行完都触发子任务执行。谢谢。

**Comment by xuxueli** [comment]
DAG流程任务合并至：https://github.com/xuxueli/xxl-job/issues/172

**Comment by viokuma** [comment]
![image](https://user-images.githubusercontent.com/1708895/87014326-90001580-c1fe-11ea-9c43-8665af72102a.png)
感觉阿里的schedulerX 参考了xxl-job的设计，并且实现了任务编排，xxl-job实现任务编排就完美了

**Comment by xey11111** [comment]
找到一个这个，看看有没有用。  [https://github.com/kpali/wolf-flow ](url)
