### ISSUE TITLE
indexing之久，久到离谱

### ISSUE THREAD

**Issue by R1310328554** [xuxueli/xxl-job#1453]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
顺利的启动程序

### Actual behavior
![图片](https://user-images.githubusercontent.com/9073658/72321682-7f536480-36df-11ea-89bb-01827e4d7a38.png)

直接导入到idea之后，一直处于indexing，差不多一个小时了 还没结束；

indexing之久，久到离谱

### Steps to reproduce the behavior
项目直接导入到idea 

### Other information

**Comment by xuxueli** [comment]
这应该是IDE和网速的问题。
