### ISSUE TITLE
client和admin 转json和解析json不是一种方式，导致错误

### ISSUE THREAD

**Issue by liuchao9186** [xuxueli/xxl-job#1455]
Please answer some questions before submitting your issue. Thanks!
2.1.2
XxlJobRemotingUtil.postBody object转json 用的BasicJson 
admin 中JobApiController解析json用的是JacksonUtil JacksonUtil 针对msg 返回长文本报错

**Comment by xuxueli** [comment]
请进一步提供复现操作步骤和相关数据。

**Comment by liuchao9186** [comment]
定位到问题代码
`      List<HandleCallbackParam> callbackParamList = Lists.newArrayList();
        HandleCallbackParam param = new HandleCallbackParam();
        param.setLogId(2222L);
        param.setLogDateTim(11111L);
        ReturnT returnT = new ReturnT();
        returnT.setCode(200);
        returnT.setMsg("\"http://xxxxxxx/xxxx/xxx\"");
        param.setExecuteResult(returnT);
        callbackParamList.add(param);
        String requestBody = BasicJson.toJson(callbackParamList);
        System.out.println("JSON：" + requestBody);`
如上 msg 中包含 双引号 使用 BasicJson.toJson(callbackParamList) 结果为
`[{"logId":2222,"logDateTim":11111,"executeResult":{"code":200,"msg":""http://xxxxxxx/xxxx/xxx"","content":null}}]`
可以看出 "msg": 后面是两个双引号

**Comment by xuxueli** [comment]
json工具后续版本会优化。

合并至：https://github.com/xuxueli/xxl-job/issues/1472
