### ISSUE TITLE
线程池环境下，XxlJobLogger.log() 日志输出异常

### ISSUE THREAD

**Issue by WWangYu** [xuxueli/xxl-job#1457]
线程池环境下，XxlJobLogger.log() 日志输出异常

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
在线程池的环境下，job的日志应该输出到对应的日志文件里
### Actual behavior
job日志输出到了第一次创建线程job的日志文件里。
### Steps to reproduce the behavior
Spring boot环境下，使用Async注解，设置线程池参数如下：
```
ThreadPoolTaskExecutor threadPool = new ThreadPoolTaskExecutor();
threadPool.setCorePoolSize(2);
```
//省略其他配置
......

然后新建一个JobHandler，使用Async注解，里面使用XxlJobLogger.log()方法打印日志，运行三次后会发现第三次的日志会输出到第一次的日志文件里。
### 已知解决办法
引入 TransmittableThreadLocal 依赖，
更改 XxlJobFileAppender 的contextHolder 为
```
public static final InheritableThreadLocal<String> contextHolder = new TransmittableThreadLocal<>();
```
更改@Async配置为 TtlExecutors.getTtlExecutor(threadPool)；
示例：
```
public Executor getAsyncExecutor() {
        ThreadPoolTaskExecutor threadPool = new ThreadPoolTaskExecutor();
        //省略其他配置
        return TtlExecutors.getTtlExecutor(threadPool);
    }
```

**Comment by xuxueli** [comment]
你好，最新版本底层日志已经改为InheritableThreadLocal方式，可以参考下。

**Comment by ukhack** [comment]
目前2.2.0依然存在这个问题。
在CompletableFuture.runAsync(() -> {})中调用xxlLog 日志输出到了第一次创建线程job的日志文件里

**Comment by liunancun** [comment]
@xuxueli 这个是由于线程池里面的线程复用引起的
private static InheritableThreadLocal<XxlJobContext> contextHolder = new InheritableThreadLocal<XxlJobContext>();
1、主线程A通过线程池创建了子线程1，这个变量就是主线程A跟子线程1共享的
2、主线程B执行的时候没有创建新的线程，而是通过线程池获得了子线程1，但子线程1的线程变量是跟主线程A共享的，所有在主线程B执行任务的时候，子线程打印的日志被打印到主线程A任务的日志里面了

**Comment by duxiaojiao** [comment]
有解决办法吗> @xuxueli 这个是由于线程池里面的线程复用引起的
> 
> private static InheritableThreadLocal<XxlJobContext> contextHolder = new InheritableThreadLocal<XxlJobContext>();
> 
> 1、主线程A通过线程池创建了子线程1，这个变量就是主线程A跟子线程1共享的
> 
> 2、主线程B执行的时候没有创建新的线程，而是通过线程池获得了子线程1，但子线程1的线程变量是跟主线程A共享的，所有在主线程B执行任务的时候，子线程打印的日志被打印到主线程A任务的日志里面了
