### ISSUE TITLE
Spring boot 运行测试时如何不启动(停掉) xxljob

### ISSUE THREAD

**Issue by songjiang951130** [xuxueli/xxl-job#1459]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
如题
### Actual behavior
实际上，我运行着项目，再运行测试会出现xxljob端口占用错误
### Other information

**Comment by hjki456789** [comment]
![image](https://user-images.githubusercontent.com/28914312/72676891-1ef26780-3ad1-11ea-9a53-0f1a024cf9b5.png)
 除去配置即可
```
 @Configuration
```

**Comment by xuxueli** [comment]
你好，任务本身也是一个普通的Bean，写一个简单单测即可。
