### ISSUE TITLE
建议将执行参数增加时间占位符与随机数-----徐志摩

### ISSUE THREAD

**Issue by wysnxzm** [xuxueli/xxl-job#146]
便于动态参数的执行

**Comment by xuxueli** [comment]
你好，感谢关注！
时间占位符和随机数，这个没有理解，时间和随机数，在JobHandler都可以编码实现的。

**Comment by wysnxzm** [comment]
在JobHandler实现是可以,但是还是希望在admin管理端可以动态调配.
一个项目有一个项目的职责,负责的任务不一样,不能够越俎代庖.

**Comment by xuxueli** [comment]
你好，这条建议过于偏具体业务，建议自主定制实现哈！
