### ISSUE TITLE
最新版支持异步执行之后，不同的任务执行器，是竞争同一个线程池的线程资源吗，如果某一个执行器的任务队列过多，会不会影响其他执行器执行？

### ISSUE THREAD

**Issue by patience00** [xuxueli/xxl-job#1461]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Other information

**Comment by xuxueli** [comment]
不同任务之间是隔离的，不会出现竞争情况。
