### ISSUE TITLE
调度中心多线程调度，执行器中单个任务执行是串行的还是多线程执行？

### ISSUE THREAD

**Issue by 1432362460** [xuxueli/xxl-job#1462]
比如说我在调度中心配置了两个使用相同jobhandler的任务，在同一时间点发送两个执行请求，该任务单个执行时间为10mine，那么这个时间点，任务在执行器中是处理了第一个10mine后再处理第二个，还是开两个线程同时执行这两个任务

**Comment by xuxueli** [comment]
单个任务单机串行执行。
如果配置多个任务，多个任务之间是隔离的，多个任务并行执行。
