### ISSUE TITLE
调度中心挂了

### ISSUE THREAD

**Issue by LeoMuhammad** [xuxueli/xxl-job#1463]
调度中心挂了，任务还会正常运行吗？正在运行的任务做什么处理？

**Comment by xuxueli** [comment]
调度中心挂了对运行中任务没有丝毫影响。尽快恢复即可。

**Comment by epiphany-zhaobh** [comment]
@xuxueli 调度中心挂了，此时刚好任务调度-结果trigger_code=0，执行-状态handle_code=0，告警状态alarm_status=0。此时日志状态对应的场景如下 : 
1.任务没有调度。
2.任务其实已经调度成功，日志中trigger_code未能进行更新。执行器执行成功，回调时未能更新状态。
3.任务其实已经调度成功，日志中trigger_code未能进行更新。执行器执行失败，回调时未能更新状态。
调度中心启动后，针对情况1是需要重新进行调度的，且如何与情况2、3进行区分，并对情况2、3的状态进行更新。针对此问题如何处理？急！急！急！
