### ISSUE TITLE
admin client端线程模型优化

### ISSUE THREAD

**Issue by kongwu-** [xuxueli/xxl-job#1468]
### admin端线程数过多导致oom

具体为什么创建了大量线程而未销毁原因未知，但都是netty client线程

1. 目前client netty创建/重连时，都是新建的bootstrap，重连时应该复用bootstrap，而不是新建

2. 作为调度中心，如果接入20个系统，每个定时系统部署2台，在4核的机器上以netty默认的线程数（processors count * 2）来计算，就是20\*2\*8=320个线程（线程池内的线程数），作为rpc的client端，应考虑复用线程池
3. 开发环境下，开发人员经常会本地连接到admin，但是开发人员的局域网ip可能会发生变化，可以考虑增加一个销毁失效连接的线程，不然会有大量的netty无用线程（池）

希望改进

**Comment by xuxueli** [comment]
你好，这个问题升级 v2.1.x 及以后版本可以修复。
