### ISSUE TITLE
数据库初始化脚本问题

### ISSUE THREAD

**Issue by qll3609120** [xuxueli/xxl-job#147]
2017年8月22号，下载了源码，按照教程跑数据库初始化脚本的时候提示异常，data too long for column xxx。按照提示找到 如下sql：

****CREATE TABLE `XXL_JOB_QRTZ_TRIGGER_GROUP` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_name` varchar(64) NOT NULL COMMENT '执行器AppName',
  `title` varchar(12) NOT NULL COMMENT '执行器名称',
  `order` tinyint(4) NOT NULL DEFAULT '0' COMMENT '排序',
  `address_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '执行器地址类型：0=自动注册、1=手动录入',
  `address_list` varchar(200) DEFAULT NULL COMMENT '执行器地址列表，多地址逗号分隔',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `XXL_JOB_QRTZ_TRIGGER_GROUP` ( `app_name`, `title`, `order`, `address_type`, `address_list`) values ( 'xxl-job-executor-sample', '示例执行器', '1', '0', null);**
commit;**

再创建表XXL_JOB_QRTZ_TRIGGER_GROUP 时，其中有个属性是·title· ，大小是12个字节，下面做insert的时候如果超过4个汉字就报错，因为utf编码下 一个汉字占用3个字符，希望能够修改下

**Comment by it-noob** [comment]
@qll3609120 请确认下是否配置有问题，我特意确认了下，没有超长的。
![image](https://user-images.githubusercontent.com/12043442/29596530-2bd64bb0-87f0-11e7-9049-1f53ce0a3243.png)
![image](https://user-images.githubusercontent.com/12043442/29596542-31daf5ba-87f0-11e7-88df-26495cac8061.png)

**Comment by qll3609120** [comment]
1、id为2的记录是通过调度中心系统添加的，还是通过手动编写的sql，理论上 确实是有问题的吧。
2、麻烦请添加超过12个汉字再试下

**Comment by it-noob** [comment]
@qll3609120 你说的不是超过4个汉字么varchar一共就12个，超过12个汉字，肯定是不行的。通过调度中心插入的。不过，我对调度中心的代码做了字段限制，最长6个中文，因为我有对Oracle做兼容

**Comment by xuxueli** [comment]
@qll3609120 你好，感谢关注哈！
问题无法复现，建议通过调度中心操作任务数据，调度中心会对数据长度做长度和格式做必要限制的啊。
