### ISSUE TITLE
指定机器执行特定任务

### ISSUE THREAD

**Issue by papalian** [xuxueli/xxl-job#1470]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by papalian** [comment]
你好，我有这样的使用场景：
1. 有python,java等多个执行脚本提前在XXL-JOB后台编写好
2. 在我需要使用上面的脚本的时候，可以选择脚本，指定在特定的服务器上执行此任务，并返回执行结果。

重点是：需要在线即时选择操作脚本并指定特定机器(如:196.128.0.111，可任意指定)马上执行，并反馈结果。

请问结合xxl-job该如何满足此使用场景，谢谢。

**Comment by xuxueli** [comment]
你好，master分支已经支持单次执行器指定执行机器，可以pull master体验下。
