### ISSUE TITLE
如何不通过web界面，代码动态设置定时任务

### ISSUE THREAD

**Issue by jintong001** [xuxueli/xxl-job#1471]
作者大大，你好。由于某种原因，我不能在web页面设置计划任务，那请问，可以在代码里面直接设置调度任务么？

**Comment by broncho** [comment]
[执行器API](https://www.xuxueli.com/xxl-job/#5.12%20执行器API服务)
![image](https://user-images.githubusercontent.com/4987826/75455969-e5a4f580-59b4-11ea-8e31-194ef7bf1143.png)

**Comment by xuxueli** [comment]
参考文档。
