### ISSUE TITLE
任务报错日志中含有“\”字符,回调admin项目中callback时，解析JSON出错导致无限回调

### ISSUE THREAD

**Issue by guoyang924** [xuxueli/xxl-job#1472]
使用2.2.0版本xxl-job-executor-sample-springboot，当任务报错中含有“\”,在admin项目中执行到
https://github.com/xuxueli/xxl-job/blob/ba626795065b44cd80239f9711cfc140cd44b0c8/xxl-job-admin/src/main/java/com/xxl/job/admin/core/util/JacksonUtil.java#L82
会因为字符串中含有“\”字符而报错，导致回调失败。因为回调会无限尝试，导致无限回调。

在JacksonUtil中加入如下代码可以简单复现错误：
```
public static void main(String[] args) throws JsonProcessingException {
		JavaType javaType = getInstance().getTypeFactory().constructParametricType(List.class, HandleCallbackParam.class);
		String jsonStr="[{\"logId\":46,\"logDateTim\":1579594508282,\"executeResult\":{\"code\":500,\"msg\":\"D:\\aaa\",\"content\":null}}]";
		getInstance().readValue(jsonStr, javaType);

}
```

**Comment by yangBin666** [comment]
如果返回的错误信息是json格式的字符串也会出现这个问题，主要是 BasicJson.tojson()这个方法没有考虑到这些情况，希望开发者下个版本修复

**Comment by GhostGod** [comment]
确实有这个问题，希望下个版本可以修复

**Comment by xuxueli** [comment]
这个问题已经修复并推送master分支，可以 pull master 体验下。将会跟随下个版本发布。

**Comment by qhysjpw** [comment]
@xuxueli 请问这个问题在哪个版本修复的，我们版本不能升级
