### ISSUE TITLE
产品License是GPL，能否降为LGPL

### ISSUE THREAD

**Issue by gary-jiao** [xuxueli/xxl-job#1474]
你好，有个不情之请，我看到目前这个产品的License是基于GPL，我们公司为客户开发的项目中是无法使用的（公司有这方面的审计），能否将License改为基于LGPL的呢？非常感谢！

**Comment by xuxueli** [comment]
你好，如果只是不修改情况下使用，不需要关心协议问题。
如果实在有审计方面考虑，可以单独给出授权，可以加入文档中交流群沟通。
可以参考这里：https://github.com/xuxueli/xxl-job/issues/1033

**Comment by coolbeevip** [comment]
> 你好，如果只是不修改情况下使用，不需要关心协议问题。 如果实在有审计方面考虑，可以单独给出授权，可以加入文档中交流群沟通。 可以参考这里：#1033

如果能将客户端依赖的库单独采用 LGPL 发布，会打消大家很多顾虑
