### ISSUE TITLE
集成v2.1.2版的，还要集成xxl-registry吗？？？

### ISSUE THREAD

**Issue by XiFYuW** [xuxueli/xxl-job#1477]
把v2.1.2拉到本地，缺失com.xxl.registry.client.util.json.BasicJson类，整个项目中也没有该类的jar包。
从maven拉已经打包好的，也找不到。还需要集成xxl-registry??

**Comment by xfworld** [comment]
V2.1.0 和V2.1.2 都不兼容，没办法直接升级...
貌似Client 在请求Server 注册路径的时候，有变化....
所以要集成 xxl-registry....
