### ISSUE TITLE
关于GPL-3.0开源协议问题

### ISSUE THREAD

**Issue by alxjerr** [xuxueli/xxl-job#1478]
公司的商用项目依赖了xxl-job-core-api.jar，没有对源码做修改，我们公司的项目源码也需要开源吗。如果我们对xxl-job-core-api.jar的源码做了修改，那我们项目的源码是否也需要开源呢。

**Comment by xuxueli** [comment]
你好，如果只是使用，不需要关心协议问题的。之前已经给出过声明：https://github.com/xuxueli/xxl-job/issues/1033
