### ISSUE TITLE
由于springbean加载顺序的问题，在部分环境中会启动失败

### ISSUE THREAD

**Issue by qbw2006** [xuxueli/xxl-job#1479]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.0.2
### Expected behavior
启动成功
### Actual behavior
启动失败
### Steps to reproduce the behavior
使用jenkins打包，在部分centos7中启动失败
### Other information
xxl-job-admin工程中有两个类XxlJobAdminConfig和XxlJobScheduler，XxlJobAdminConfig必须先于XxlJobScheduler加载才行。但是spring的类加载顺序跟操作系统有关，在某些centos7中，XxlJobAdminConfig后于XxlJobScheduler加载，导致启动失败。应该在类XxlJobScheduler上增加@DenpendOn("xxlJobAdminConfig")才能确保加载顺序正常。

**Comment by xuxueli** [comment]
最新版已经修复了这个问题。
