### ISSUE TITLE
手动执行任务,任务被重复调用，执行两次

### ISSUE THREAD

**Issue by yaqian012** [xuxueli/xxl-job#148]
Please answer some questions before submitting your issue. Thanks!

### 我看了下代码，应该是这个方法RemoteHttpJobBean的executeInternal被执行了两次。

> 日志截图 发到2群了

**Comment by xuxueli** [comment]
你好，感谢关注！
这个问题无法重现，有没有定制过调度中心源码？调度中心部署集群情况方便告知下吗？
