### ISSUE TITLE
执行完任务之后callback失败

### ISSUE THREAD

**Issue by zhaozhian** [xuxueli/xxl-job#1480]
![image](https://user-images.githubusercontent.com/53215867/74098723-4da2b180-4b56-11ea-88e0-61b1297c2a22.png)
![image](https://user-images.githubusercontent.com/53215867/74098735-71fe8e00-4b56-11ea-8d7b-899430b0098e.png)
我检查了回调地址是对的啊，不知道问题出在哪里

**Comment by xuxueli** [comment]
清理下日志目录数据就好了。
