### ISSUE TITLE
java 11 with xxl-job 2.1.2/groovy 2.5.8 WARNING

### ISSUE THREAD

**Issue by slieer** [xuxueli/xxl-job#1483]
Please answer some questions before submitting your issue. Thanks!
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/E:/.m2/org/codehaus/groovy/groovy/2.5.8/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
### Which version of XXL-JOB do you using?
<xxl.job.version>2.1.2</xxl.job.version>
<groovy.version>2.5.8</groovy.version>
### Expected behavior
no WARNING
### Other information

**Comment by slieer** [comment]
upgrade groovy version to <groovy.version>3.0.0</groovy.version> ,  Is this OK ?

**Comment by xuxueli** [comment]
你好，master分支已经升级了groovy可以体验下。
