### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by kckj** [xuxueli/xxl-job#1488]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
using maven import,version is 2.1.2
### Expected behavior
正常执行调度
### Actual behavior
出现报错：java.net.SocketTimeoutException: Read timed out
### Steps to reproduce the behavior
我执行了一个比较长时间的方法，可能这个方法调度完成需要1小时左右。
### Other information
null

请问一下大佬有没有出现这种情况的，我看有人说是超时时间设置的太短。 xxl大佬能不能升级优化下这个地方，感谢(*^__^*)

**Comment by xuxueli** [comment]
你好，这里的超时和任务耗时是两码事。任务执行是异步的，执行多久都可以。上面超时问题应该是网络问题，可以拍查下。
