### ISSUE TITLE
执行器可否做成不内嵌jetty?

### ISSUE THREAD

**Issue by zsf513** [xuxueli/xxl-job#149]
执行器可否做成不内嵌jetty？可否做成一个jar包依赖(比如叫xxl-job-executor-jetty)，需要的时候引入jetty，不需要的时候可用使用应用自身的容器。
目前我的项目是用的springboot，已经内嵌了tomcat，不想再内嵌一个jetty(虽然项目能正常运行)。

**Comment by dragontree101** [comment]
顶一下 这个建议， 我觉得 springboot已经暴露了一个port出来， 为什么不能复用？ 而要还启动一个jetty，感觉好别扭。

**Comment by ljgGit** [comment]
顶一下 这个建议，我也是，线上环境已经使用了tomcat容器，执行器内嵌一个jetty很不方便，而且一个tomcat容器只能部署一个执行器

**Comment by dragontree101** [comment]
以弃坑，换框架吧

发自我的 iPhone

**Comment by xuxueli** [comment]
@zsf513 @ljgGit
感谢关注！
底层jetty端口是为了调度中心与执行器通讯使用的，方案基于以下几个原因：
1、自研rpc通讯目前基于jetty，后续考虑升级netty，进一步提升通讯效率。
2、通讯使用内嵌jetty，只需要"ip+端口"即可通讯，方便机器注册。否则，通讯端口与项目容器如tomcat耦合，tomcat非root路径部署、项目存在权限拦截等情况下都需要特殊处理。
3、可以类比dubbo，服务提供方也会开放通讯端口。

**Comment by dragontree101** [comment]
个人觉得定时任务效率不是关键，不管是jetty还是netty本质差别不大，但是要考虑到业务方使用场景。
额外开端口感觉就特别奇怪，开了端口就意味可以通过rpc方式调用，感觉就把定时任务的入口暴露出去了，又没有相关的权限，感觉也很奇怪。
然后代码层面我稍微看了下，建议加入一些code style，第一感觉就是代码挺乱的。
不过还是支持一下独立开发者的作品

**Comment by xuxueli** [comment]
@denghuafeng 感谢反馈！
额外开放端口早有先例，可以参考上述回复中 “dubbo” 的通讯场景，通讯与现有项目耦合将会大大降低项目的兼容性。
调度中心与执行器通讯是存在权限控制的，文档中有章节介绍。
目前我们是一个团体在维护XXL系列，交流群和管理群数千人，详细问题可以加群进一步沟通，有改进建议也欢迎PR。

**Comment by dragontree101** [comment]
顺便说一下  `@denghuafeng`  是谁？ 不知道是不是打错了？    尴尬  😅

dubbo 的场景 我认为和 job的场景 是不一样的，不是所有的东西 都要往 另外一个东西上面靠， 
而且不是说 dubbo 所有做的设计 都一样 符合 所有的 系统。

我只是个人觉得 job 这类的东西， 如果用rpc的方式来做， 不符合我认为的设计思想， 也只是提个意见。
我认为job 就应该像 linux 的 crontab一样，  只是扩充到分布式环境而已 ， 而不需要加入什么rpc什么的， 可能每个人 设计理念不一样吧。

best wishes！

**Comment by charlesvhe** [comment]
我们也有这个需求，希望端口能复用，希望提供可选配置，不用强制分成两个端口

**Comment by SZMOFEI** [comment]
我们也有这个需求，希望端口能复用，希望提供可选配置，不用强制分成两个端口。
