### ISSUE TITLE
xxl-rpc, invoke error, address:192.168.0.103:9999, XxlRpcRequestXxlRpcRequest

### ISSUE THREAD

**Issue by wempers** [xuxueli/xxl-job#1496]
admin是源码启动的 本地有两个网卡  虚拟机网卡和无线网卡。客户端也是源码启动的。调度失败，发现admin 调度机器地址是虚拟网卡地址。请问怎么解决？配了spring cloud inetutils default-ip-address为无线网卡ip不起作用。

**Comment by xuxueli** [comment]
可以手动配置生效的地址。
