### ISSUE TITLE
xxl-job 版本2.0.2使用中的问题

### ISSUE THREAD

**Issue by zhuyj2016** [xuxueli/xxl-job#1497]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
正常执行调度
### Actual behavior
code：500
msg：block strategy effect：Discard Later
### Steps to reproduce the behavior
做了集群部署，定时任务设置的每20分钟执行一次，可是会偶尔出现同一时间执行两次的情况，第二次执行肯定就失败了，请问这种情况是否正常
### Other information
补充问题1：新建定时任务中的超时时间如果不设置会有默认超时时间？有的话是多久呢？
补充问题2：如果路由策略是分片广播的话，那么阻塞处理策略必须为单机串行吗

**Comment by xuxueli** [comment]
那是因为重复触发，阻塞策略修复了这个问题。可以文档了解下重复触发情况。

超时时间不设置，默认不限制时间。
旅路由策略和阻塞策略可以任意搭配。
