### ISSUE TITLE
项目启动失败，XxlJobSpringExecutor报NPE

### ISSUE THREAD

**Issue by gfanot** [xuxueli/xxl-job#1498]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
项目正常启动
### Actual behavior
项目没有启动，XxlJobSpringExecutor报出NPE
### Steps to reproduce the behavior
如果项目中存在着未成功初始化的Bean，比如我的项目中Jedis的配置类，由于Redis服务到期，而配置类还在项目中残余。则会报出NPE
### Other information
具体代码问题出自initJobHandlerMethodRepository这个方法中，进行全Bean的遍历，但是未做判空。导致了空指针问题。
理论上确实项目中不应该允许出现未成功初始化的Bean，但是我认为这种不进行判空的全局遍历，还是一个比较危险的行为，有可能出现未曾预想到的错误。

**Comment by xuxueli** [comment]
你好，已出发，可以pull master体验下。
