### ISSUE TITLE
建议增加oracle等其他DB版本的支持

### ISSUE THREAD

**Issue by seguzhizi** [xuxueli/xxl-job#150]
引入XXL-JOB之后，由于项目DB使用oracle，只能将其转换为oracle版本，目前还在处理bug中。。。较为麻烦。。不知可否增加DB版本适配（主要就是sql脚本和mapper的适配）

后续再将转换的坑反馈下

**Comment by xuxueli** [comment]
你好，感谢关注和建议哈：）
目前暂时只支持mysql版本，其他db版本还在规划中。
可以将定制的分支版本汇总在这篇issue中，大家可以一起分享讨论啊。

**Comment by seguzhizi** [comment]
在oschina的码云上，我看到有人分享了oracle版本的issue，owner可以参考下，我就不献丑了

**Comment by daisytardis** [comment]
你好，可以发下xxl-job是oracle版本的地址吗?

**Comment by xuxueli** [comment]
@daisytardis Oracle版本可以参考这篇ISSUE哈：https://github.com/xuxueli/xxl-job/issues/154
