### ISSUE TITLE
全局扫描BeanDefinitonNames 导致的启动异常

### ISSUE THREAD

**Issue by Hccake** [xuxueli/xxl-job#1500]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2

### Expected behavior
项目正常启动

### Actual behavior
项目启动失败

### Steps to reproduce the behavior
启动时抛出异常
org.springframework.beans.factory.BeanIsAbstractException: Error creating bean with name ”xxx“,Bean definition is abstract

### Other information
定位了下问题，由于启动时会执行 `initJobHandlerMethodRepository()` 方法，该方法内会根据BeanDefinitionNames，进行一个循环获取bean实例的操作。

由于项目中有配置 abstract bean
```xml
     <bean id="xxBean" abstract="true"> </bean>
```
导致在执行`Object bean = applicationContext.getBean(beanDefinitionName)`方法时抛出异常。

**Comment by xuxueli** [comment]
你好，优化逻辑已经推送master分支，可以pull master体验下。

**Comment by 1ffree** [comment]
@xuxueli  看到解决了非单例的注册问题，但是并没有解决抽象继承父类 在getBean的报错, 是我理解有问题吗？
![image](https://user-images.githubusercontent.com/5736293/91248924-62f4cb80-e788-11ea-8190-393197e6cdaf.png)
