### ISSUE TITLE
期待执行器里面增加java 调度 kettle 的工具 与调度里增加 任务名称

### ISSUE THREAD

**Issue by Jarvis-JunZhu** [xuxueli/xxl-job#1501]
第一个建议： 我在使用了xxl-job去调度我的kettle脚本，没办法，只能自己扩展了java执行kettle的工具，用glue的方式去调用，如： package com.xxl.job.service.handler;

import com.xxl.job.core.log.XxlJobLogger; import com.xxl.job.core.biz.model.ReturnT; import com.xxl.job.executor.util.KettleRunUtil; import com.xxl.job.core.handler.IJobHandler;

public class JOB209_JobHandler extends IJobHandler {

@Override
public ReturnT<String> execute(String param) throws Exception {
	return KettleRunUtil.runTransfer(KettleRunUtil.getRootPath("/dw/1_ods/init_erp_order.ktr"));
}
}

但是最近遇到了一个问题，那就是xxl-job更新了很多好用的功能，想升级，我又不想每升级一次就把这部分代码粘进去，官方能否去做这个事情呢！

第二个建议： 调度器前端查询调度日志，任务名称没有出现在列表里面，这个我也扩展了，不过还是升级的问题，官方能否也加一下

**Comment by LockiJiang** [comment]
可以直接创建shell任务去调度kettle啊

**Comment by xuxueli** [comment]
> 可以直接创建shell任务去调度kettle啊

+1
