### ISSUE TITLE
初始化XxlJobSpringExecutor时会导致所有懒加载的bean实例化

### ISSUE THREAD

**Issue by 783144350** [xuxueli/xxl-job#1503]
private void initJobHandlerMethodRepository(ApplicationContext applicationContext) {
...
        // init job handler from method
        String[] beanDefinitionNames = applicationContext.getBeanDefinitionNames();
        for (String beanDefinitionName : beanDefinitionNames) {
            Object bean = applicationContext.getBean(beanDefinitionName);
            ...
        }
...
}

getBean方法会实例化bean，但是这里并没有判断该bean是否是懒加载的。
同时getBean方法可能会报BeansException，建议处理下该异常。

**Comment by xuxueli** [comment]
你好，该问题已经做了优化，可以pull master体验下。
