### ISSUE TITLE
Cron会支持对于定时执行任务的某些时点的跳过吗？

### ISSUE THREAD

**Issue by classfan** [xuxueli/xxl-job#1505]
Cron会支持对于定时执行任务的某些时点的跳过吗？

由于业务上的需要，在既定的定时执行任务的基础上，有时候还需要配置以便跳过某些执行的时点。比如按15分钟执行一次的job，期望跳过每天的10:15和下午16:15的执行。

基于最新publish版本的XXL Job，是否现有的策略是否有办法实现？如无的话，是否有后续支持计划？（看到TODO List中有“10、任务触发参数优化：支持选择 “Cron触发”、”固定间隔时间触发”、”指定时间点触发”、”不选择” 等；”）

**Comment by mxguodong** [comment]
cron 目前版本估计是不支持排除法的，个人认为可以考虑 executor 本身忽略此特殊时间。在执行任务本身忽略10月1日~10月7日之间的业务逻辑

**Comment by mxguodong** [comment]
好像可以了， cron = * 0/15 0,1,7,9,13,14,15,17,19,20,23 * * ?   或者 cron = * * 0-9,11-15,17-23 * * ? 表示在约定的小时内 每15分钟执行一次

**Comment by classfan** [comment]
> 好像可以了， cron = * 0/15 0,1,7,9,13,14,15,17,19,20,23 * * ? 或者 cron = * * 0-9,11-15,17-23 * * ? 表示在约定的小时内 每15分钟执行一次

Thanks，我试一下是否真的可以。

**Comment by xuxueli** [comment]
@mxguodong 赞！
