### ISSUE TITLE
k8s部署发现admin和executor的内存一直上升直到被kill

### ISSUE THREAD

**Issue by Gitforxuyang** [xuxueli/xxl-job#1509]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2

### Other information
![image](https://user-images.githubusercontent.com/16128584/76481421-6b608080-644c-11ea-9ce4-1f170fabdb18.png)

**Comment by Xusq513** [comment]
这个问题解决了吗

**Comment by Gitforxuyang** [comment]
@Xusq513 解决了，我再上了java启动时对资源的限制参数，然后重新打了一个镜像。
