### ISSUE TITLE
建议把任务的Cron 弄成可下拉选的时分秒年月日，这样配置起来更方便点

### ISSUE THREAD

**Issue by fuqianming** [xuxueli/xxl-job#152]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，感谢关注和反馈：）
Cron功能比较复杂，暂时还没有找到一款符合期望Cron前端组件，如果你有好的建议，可以推荐啊。

**Comment by GoldyMark** [comment]
增加一个[在线Cron表达式生成器](http://cron.qqe2.com/)的链接就好了。:)

@xuxueli

**Comment by wenqibo** [comment]
@xuxueli http://www.cronmaker.com/

**Comment by xuxueli** [comment]
你好，最新版本已经提供支持：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
