### ISSUE TITLE
多数据源定时器如何操作？

### ISSUE THREAD

**Issue by 852675742** [xuxueli/xxl-job#1520]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
现程序采用的是多数据源做的数据隔离，如何做到每个数据源的数据都能在同一个调度点调度呢？
### Other information

**Comment by xuxueli** [comment]
你好，可以使用执行器隔离。

**Comment by 852675742** [comment]
您好，请问下我的数据源是程序运行时动态增加的，不是提前在配置文件中配置的数据源，如何使用执行器隔离？请给点思路
