### ISSUE TITLE
xxl-job支持提供对外接口吗？

### ISSUE THREAD

**Issue by xinyuwuhenlq** [xuxueli/xxl-job#1521]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
xxl-job支持提供对外接口，其他平台可以通过接口动态的向调度平台创建定时任务。这样就比较灵活了。我目前通过数据库插入任务数据的方式创建任务不行，任务不执行。不知道是啥原因。
### Other information

**Comment by RongXiong2016** [comment]
可以的，文档上有提供api，只需要把权限注解去掉即可

**Comment by xuxueli** [comment]
支持的，文档有说明。

**Comment by zyx2075257** [comment]
> 支持的，文档有说明。

文档说明在哪里，找了半天没找到，能否截个图，或者详细说明下，好痛苦啊

**Comment by zyx2075257** [comment]
> 可以的，文档上有提供api，只需要把权限注解去掉即可
哪个Api，找不到啊，求救
