### ISSUE TITLE
如果要创建一个90分钟或150分钟等类似超过1小时的调度任务该如何配置？

### ISSUE THREAD

**Issue by xinyuwuhenlq** [xuxueli/xxl-job#1522]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
如果要创建一个90分钟或150分钟等类似超过1小时的调度任务该如何配置？
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/1481

**Comment by wenfer** [comment]
遇到了类似的需求。。。我们想通过这个实现订单30分钟过期取消的任务，不知道下一个版本能不能支持

**Comment by dudiao** [comment]
@wenfer 订单30分钟过期取消。这个可以每分钟扫描订单更新状态吧
