### ISSUE TITLE
2.1.2版本调度器向下兼容执行器到哪个版本？

### ISSUE THREAD

**Issue by ecmsglobal** [xuxueli/xxl-job#1523]
公司内部使用xxljob有一段时间了，之前是各个项目自行部署调度器，现在想做集中部署，降低运维成本。想咨询一下目前2.1.2版本的调度器向下兼容执行器可以到哪个版本。

从原理上讲，既然是http方式的，那只要接口不变，应该都是兼容的。不知道大家谁有实际应用经验。

我们目前最低版本的执行器是1.9.2

**Comment by xuxueli** [comment]
你好，建议等待即将发布的 2.2.0

**Comment by ecmsglobal** [comment]
实际测试，2.1.2的调度器兼容所有2.1.x的执行器。不兼容2.0.x以下所有版本的执行器。

**Comment by jingbo323** [comment]
新发布2.2.0版本可以兼容 1.9.1 么？
