### ISSUE TITLE
采用2.1.2这个版本，定时器可以正常运行，但是时不时报如下错

### ISSUE THREAD

**Issue by ffyyhh995511** [xuxueli/xxl-job#1524]
#报错信息
xxl-rpc request data empty.]
com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:77)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)

#依赖版本
<groupId>com.xuxueli</groupId>
<artifactId>xxl-job-core</artifactId>
<version>2.1.2</version>

#配置文件
xxl.job.admin.addresses	http://ip:port/xxl-job-admin
xxl.job.executor.logpath	/data/applogs/xxl-job/jobhandler
xxl.job.executor.logretentiondays	-1

#java代码
@XxlJob(value="testJob")
    public ReturnT<String> execute(String param) throws Exception {
        log.info("定时器开始");
        //
       业务代码
        log.info("定时器结束");
        return ReturnT.SUCCESS;
    }

**Comment by xuxueli** [comment]
你好，这是执行器端口服务被恶意扫描导致，可以忽略。
