### ISSUE TITLE
一点改进建议

### ISSUE THREAD

**Issue by tangyanjun2004** [xuxueli/xxl-job#1525]
先是非常抱歉地说，我通读了一遍文档，还没有亲自手动试验。以下建议是从文档的描述和界面上猜想的，如果有不对的地方，请见谅。
改进的建议如下：
1、在使用BEAN模式，无论是方法模式还是类模式，都只是注册了一个执行器，没有办法注册一个任务。 有配置界面虽然是好，单很多情况下，我们希望在注册一个执行器的时候，它的执行时间就确定好了，我们只是期望在那个时候有个任务被触发。通过代码注册的好处在于，上线部署的时候，不用多一个配置的一步。
2、任务的创建的时候，可以支持开始时间和结束时间的选项。虽然可以手动触发和手动停止。但是更多的时候我们的任务是按月来进行的，我们希望月初启动，月末自动结束。

**Comment by xuxueli** [comment]
1、任务注册会导致任务信息变更频繁，混乱，不建议。
2、按月执行，可以通过cron表达式配置。
