### ISSUE TITLE
请问一下调度任务产生的数据支持切片执行吗？

### ISSUE THREAD

**Issue by lycookiss** [xuxueli/xxl-job#1527]
### 2.2.0-SNAPSHOT

请问一下调度任务产生的数据支持切片执行吗？
比如我的调度任务A查询出来1000条数据，我想把这1000条数据切成5片，由另一个任务并行执行这5片，可以直接通过xxl-job实现吗？如何实现？多谢

**Comment by thinwonton** [comment]
支持分片。参考文档：5.9 分片广播 & 动态分片

**Comment by xuxueli** [comment]
原生支持。
