### ISSUE TITLE
如何支持springcloud的sleuth？how to support springcloud-sleuth?

### ISSUE THREAD

**Issue by Chingzuk** [xuxueli/xxl-job#1531]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Chingzuk** [comment]
2.1.1版本,之前用的是java原生自带的schedual，引入了sleuth后默认打印如下：2020-03-20 22:54:00.000  INFO [service-name,729b5819e5e12c81,729b5819e5e12c81,false] 8761 --- [scheduled-thread-3] c.h.k.schedule.OptionsTask           : 定时任务xxxx. --------这是我期望的效果。
改用xxl-job后，打印2020-03-20 23:00:16.292  INFO [service-name,,,] 8761 --- [Thread-68] c.h.k.s.impl.PerforServiceImpl .---------------service-name后的traceId,spanId,都打印不出，请教下作者是否支持，如何配置？感谢！

**Comment by xuxueli** [comment]
你好，xxl-job 有自己一套标准体系，可以搜索 xxl-job 关键字查看。
