### ISSUE TITLE
部署到linux环境时出现执行日志无法读取，后台报Broken pipe

### ISSUE THREAD

**Issue by sampsongi** [xuxueli/xxl-job#1534]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
15:55:47.287 logback [http-nio-8090-exec-6] ERROR c.x.j.a.c.r.WebExceptionResolver - WebExceptionResolver:{}
 127 org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
 128         at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:364)
 129         at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:833)
 130         at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:738)
 131         at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:399)
 132         at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:377)
 133         at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
 134         at org.springframework.util.StreamUtils.copy(StreamUtils.java:138)
 135         at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:110)
 136         at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:102)
 137         at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:45)
 138         at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:228)
 139         at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:480)
 140         at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
 141         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
 142         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
 143         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
 144         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
 145         at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
 146         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
 147         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
 148         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

**Comment by xuxueli** [comment]
你好，问题无法复现。
