### ISSUE TITLE
[ERROR] Read timed out

### ISSUE THREAD

**Issue by voidluffy** [xuxueli/xxl-job#1537]
[com.xxl.job.core.util.XxlJobRemotingUtil]-[xxl-job, executor ExecutorRegistryThread]-[postBody]-[146]-[ERROR] Read timed out
[xxl-job, executor ExecutorRegistryThread]-[run]-[54]-[INFO] >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='executor', registryValue='127.0.0.1:9998'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Read timed out), for url :

经常出现超时的异常，算是bug吗

**Comment by xuxueli** [comment]
默认3s超时，确认下网络情况。

**Comment by rye567** [comment]
> 
> 
> 默认3s超时，确认下网络情况。

默认超时不可配置

**Comment by junshengluo** [comment]
How to solve it?
Recompile the source code to change the default config？
Why not expose this config？

**Comment by JasonShow** [comment]
xxl-job-core中，AdminBizClent、ExecutorBizClient类中默认的timeout是3秒(由于历史原因，自定义超时时间的代码没有合并)，可以增加源码中该字段的这个值。XxlJobRemotingUtil.postBody() 可以看看这个方法的执行链路就知道怎么去更改。
