### ISSUE TITLE
每五分钟执行一次 正常情况一天应该执行288次 但是日志只有280次

### ISSUE THREAD

**Issue by xiang199625** [xuxueli/xxl-job#1541]
如题，请问大佬这种可能是什么问题啊。这只是举个例子，实际遇到的也有284次 270多次，反正就总是在不同的时间会有漏点的情况。日志也没有报错，比如某个时间漏调了，这个时间的日志也是没有的

**Comment by xiang199625** [comment]
![image](https://user-images.githubusercontent.com/23209586/77984864-630dae00-7345-11ea-87f3-ad65e2a28da9.png)
这是任务的配置 日志因为没有打印执行信息 没有异常 所以没有东西 可能是什么原因引起的呢

**Comment by xiang199625** [comment]
这里路由策略是分片广播 但是其实执行的机器只有一台 在做测试

**Comment by xuxueli** [comment]
你好，调度阻塞时会小概率出现misfire情况，除此之外应该不会调度丢失。可以日志全文检索下如下日志：
```
logger.warn(">>>>>>>>>>> xxl-job, schedule misfire, jobId = " + jobInfo.getId());
```
