### ISSUE TITLE
init job handler的问题XxlJobSpringExecutor.java

### ISSUE THREAD

**Issue by csj50** [xuxueli/xxl-job#1545]
release2.1.2版本
// init job handler from method
        String[] beanDefinitionNames = applicationContext.getBeanDefinitionNames();
        for (String beanDefinitionName : beanDefinitionNames) {
            Object bean = applicationContext.getBean(beanDefinitionName);
            Method[] methods = bean.getClass().getDeclaredMethods();
...
}
循环获取bean，然后循环获取方法上的注解判断是否为@XxlJob
问题是如果有其他bean声明为abstract="true"，会抛异常
Caused by: org.springframework.beans.factory.BeanIsAbstractException: Error creating bean with name 'xxxxxxxx': Bean definition is abstract

**Comment by xuxueli** [comment]
你好，这个问题在2.2.0已经修复，可以参考master分支调整下。
