### ISSUE TITLE
定时任务平台调度时会产生大量log4j生成的日志，如若不定期进行删除清理无用日志会占据大量机器内存，关于日志这块的问题有无优化呢

### ISSUE THREAD

**Issue by ZSQLoveCoding** [xuxueli/xxl-job#1548]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，调度中心与执行器均支持自动清理日志，可以参考下文档。

**Comment by zoukun120** [comment]
一共有三处日志，分别为调度中心、执行器和数据库xxl_job_log.
其中最新版本的调度器部分采用的是logback的RollingFileAppender生成日志的，可以修改logbak.xml.
log4j同理

**Comment by 1956025812** [comment]
> 你好，调度中心与执行器均支持自动清理日志，可以参考下文档。

你好  我看文档 

调度中心日志表数据：可借助配置项 “xxl.job.logretentiondays” 设置日志表数据保存天数，过期日志自动清理；详情可查看上文配置说明；

这里面有说明日志表数据清理，  但是我设置了该变量为7， 但是xxl_job_log表的数据还是没有清理  在控制台清理也没有 这个是有问题么？
