### ISSUE TITLE
执行器集群注册，执行器ip问题

### ISSUE THREAD

**Issue by lonkigit** [xuxueli/xxl-job#155]
执行器集群自动注册，两个执行器注册上来的ip不同，一个是内网ip，一个是外网ip，我没有开放外网ip的端口，怎么才能让执行器使用内网ip注册到调度中心呢？

![qq 20170901161151](https://user-images.githubusercontent.com/14899952/29960971-5c71a32c-8f30-11e7-8ce6-5258bbaeee54.png)

**Comment by xuxueli** [comment]
你好，执行器注册的IP如果不手动指定是从网卡中自动获取的，如果存在多网卡情况可能获取IP不唯一。
但是，可以在执行器配置文件中，手动指定期望的IP地址啊。

**Comment by lonkigit** [comment]
好的。谢谢！
