### ISSUE TITLE
xxxl-job mvn 编译失败 求大佬支招

### ISSUE THREAD

**Issue by jc9090kkkk** [xuxueli/xxl-job#1553]
有谁遇到过mvn编译失败的情况，我jdk和maven安装都是成功的 我本身不是做java开发的 我用mvn compile编译的时候 报错如下：
![image](https://user-images.githubusercontent.com/62995891/78206096-82851200-74d0-11ea-8d4a-1800166eced7.png)
有哪位大佬知道是什么问题 是缺少其他组件吗？ 没有java开发经验的人编译起来麻烦死了。。。能否给个文档说明下哦

**Comment by dudiao** [comment]
你maven用的是什么版本的？

不是Java开发，你可直接使用官方的releases包：https://github.com/xuxueli/xxl-job/releases

**Comment by xuxueli** [comment]
@dudiao +1，建议用releases版本。
