### ISSUE TITLE
通过httpJobHandler方式调用外网服务来实现脚本管理 这个功能很鸡肋

### ISSUE THREAD

**Issue by jc9090kkkk** [xuxueli/xxl-job#1554]
![image](https://user-images.githubusercontent.com/62995891/78236048-12947d00-750c-11ea-91c9-4af2b8b8b376.png)
我调用外网的http来执行脚本，发现总是执行失败，最后我发现
![image](https://user-images.githubusercontent.com/62995891/78236164-39eb4a00-750c-11ea-9c0d-d38fffe9fe15.png)
httpJobHanlder里面的超时时间是写死的 我一个脚本如果执行2分钟，xxx-job的监听就是失效的，这块不应该是用异步回调的方式来做监听处理吗？ 有没有更好的解决办法啊？ 所谓的跨平台有点扯了 通用性不强

**Comment by LockiJiang** [comment]
首先，任务超时时间是针对任务的，你具体实现还涉及到其他逻辑自行处理；
其次，BEAM模式的都应该自己开发，人家这个就是个简单的示例

**Comment by jc9090kkkk** [comment]
我理解 如果只是监听任务本身，如果是对接其他的技术栈，那么这么监听就更无用武之地了，因为兼容的准确性太差了，如果使用的glue模式来做， 又不是纯异步的方式 而是起一个监听线程，为什么不做成开始执行，执行中和执行完成分别通过不同的回调状态来做监听？ 想不明白

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/824

你好，最新版将会重构底层通讯逻辑，切换为跨语言通讯模型。届时，非Java语言可以借助内置API服务，扩展实现自己的执行器，从而实现异步执行任务、回调等逻辑。
