### ISSUE TITLE
任务依赖-不支持多个父任务完成后才能执行某个子任务？

### ISSUE THREAD

**Issue by geosmart** [xuxueli/xxl-job#1556]
场景：taskC必须等待taskA,taskB结束后，taskC都完成才能开始执行
taskA finish
child TaskC waiting...
taskB finish
child TaskC run...

这种需求用xxl-job目前能否实现？

类似sia-task实现的任务依赖![sia-task实现的任务依赖](https://raw.githubusercontent.com/siaorg/sia-task/master/docs/images/user-handbook-task-configing.png)

**Comment by dudiao** [comment]
现在只支持配置子任务依赖，当父任务执行结束且执行成功后将会主动触发一次子任务的执行, 多个子任务用逗号分隔；

DAG流程任务在TODO列表里。

**Comment by xuxueli** [comment]
DAG 流程任务可以参考：https://github.com/xuxueli/xxl-job/issues/172

规划中。
