### ISSUE TITLE
咨询一下Simple Trigger会在哪个版本支持？

### ISSUE THREAD

**Issue by zlklink** [xuxueli/xxl-job#1557]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，SimpleTrigger 已经假如TODO排期。预计 2.x 进行迭代。如果自己实现可以参考现有Cron触发方式实现。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/1481
