### ISSUE TITLE
文字是否有误？是不是应该改成“月开始，每”

### ISSUE THREAD

**Issue by babowonkook** [xuxueli/xxl-job#1558]
https://github.com/xuxueli/xxl-job/blob/06fd33ec674447bbbc3e2c5bbdf0c9b87168a85e/xxl-job-admin/src/main/resources/static/plugins/cronGen/cronGen.js#L231

**Comment by xuxueli** [comment]
已修复，Tks。日后类似问题，建议直接提PR啊。
