### ISSUE TITLE
发布时应用时,xxl-job是否可以暂时停止job运行?

### ISSUE THREAD

**Issue by slinhuang** [xuxueli/xxl-job#1559]
只是建议,
项目比较多的数据同步,可能15s就调用一次,
发布应用时,xxl-job会调用不到程序,会一直报错,发了好多错误提醒.
由于邮件一天能发送的数量有限制
想问一下,是否xxl-job有一个功能,表示项目部署中,暂时不发邮件提醒?

**Comment by xuxueli** [comment]
你好，项目发布时可以手动摘除部署机器，不会进行触发的。
