### ISSUE TITLE
日志使用建议

### ISSUE THREAD

**Issue by it-noob** [xuxueli/xxl-job#156]
目前日志是显示调用才会记录到文件中，在调度中心查看时，可能也会想看程序本身通过log4j等打印的日志，或者数据库的相关操作SQL和参数等重要信息，而目前只能做到任务里主动调用静态方法才能使用。作者可有想过做成可有配置的，是否打印相关spring、以及mybatis等日志输出的计划。因为如果要把任务中每一个操作都手动调用日志类，显然不是好的方式。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈啊：）
在v1.3版本，系统支持打印地层中间件日志，是通过依赖并log4j的日志append实现的。可以参考对应版本定制。
在新版本，为了取消对log4j的依赖，采用了自研日志组件r的方式。欢迎提供更好的方案建议啊！

**Comment by qrqhuang** [comment]
@xuxueli 
关于执行日志输出， 目前XxlJobLogger采用的WARN级别， 控制台看着挺吓人的。  
是否应该将级别降低， 最好能设置不同级别供开发人员自行选择。

**Comment by xuxueli** [comment]
你好，最新release版本已经修复该问题，可升级查看下哈！
