### ISSUE TITLE
关于XxlJobInfo任务中的id使用的是int数据库自增问题

### ISSUE THREAD

**Issue by licaibo** [xuxueli/xxl-job#1561]
你好，XxlJobInfo任务中的id使用的是int数据库自增，担心会有用完的一天，能不能改成String支持分布式ID，这样改动会不会影响其他的地方？

**Comment by dudiao** [comment]
你好，我的一个PR中，id改成了long类型，支持分布式自增。欢迎提意见

地址：https://github.com/xuxueli/xxl-job/pull/1530

**Comment by xuxueli** [comment]
任务数量是有限的，正常不会超过int上限的，应该不需要考虑这种问题。

有特殊场景需求吗？可以描述下。
