### ISSUE TITLE
为什么我在本地不显示操作的选项

### ISSUE THREAD

**Issue by yzxbshi** [xuxueli/xxl-job#1562]

**Comment by yzxbshi** [comment]
在‘任务管理’下的‘操作’选项中，没有可以操作的图标（我截的图不能上传到github...）

**Comment by xuxueli** [comment]
无法复现，需要提供操作步骤和截图。可以查看下服务端和浏览器日志。

**Comment by yzxbshi** [comment]
![image](https://user-images.githubusercontent.com/53074038/78894751-3b82b800-7aa0-11ea-9765-f875cd72271f.png)
我下载了v2.1.2的源码，修改了配置之后就用idea启动，出现了如截图这种情况；然后我在idea打包上传到linux服务器，结果也是一样
