### ISSUE TITLE
更新升级文档在哪里看

### ISSUE THREAD

**Issue by lizhuangs** [xuxueli/xxl-job#1566]
### Other information 
请问下作者，我司之前用的是1.x版本的，现在想升级到最新的，发现改动非常大。如何平滑升级，我在官方文档中并没有发现这一块。貌似2.x数据库，注册中心好多都改了。有具体各个版本升级文档吗？

**Comment by xuxueli** [comment]
你好，历史版本数量太多，一一提供升级方案比较难维护。

升级方案可以参考这个思路：数据库升级》调度中心升级》执行器升级。

可以参考这个ISSUE：https://github.com/xuxueli/xxl-job/issues/1038
