### ISSUE TITLE
使用版本2.1.2 执行器进程运行一段时间后 产生大量线程数 9000+

### ISSUE THREAD

**Issue by Xxf9126** [xuxueli/xxl-job#1570]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
需要提供复现步骤，以及这9k线程相关信息。
需要确定线程是执行器生成还是业务代码生成。

**Comment by Xxf9126** [comment]
> 需要提供复现步骤，以及这9k线程相关信息。
> 需要确定线程是执行器生成还是业务代码生成。

昨日下午6点重启后 截止目前又出现5000多 线程信息如下

![image](https://user-images.githubusercontent.com/47099845/79184988-46df3600-7e48-11ea-8783-8c65cc334437.png)
![image](https://user-images.githubusercontent.com/47099845/79185009-52326180-7e48-11ea-8ddf-01bd7da23058.png)
![image](https://user-images.githubusercontent.com/47099845/79185029-624a4100-7e48-11ea-892f-8b261a65f952.png)
