### ISSUE TITLE
如何在（重试的）任务中获取当前任务的首次调度时间？

### ISSUE THREAD

**Issue by photondragon** [xuxueli/xxl-job#1571]
需求：
有一个每日生成报表任务，每天0时执行。  
假设报表数据库挂了，导致当天的生成报表任务一直失败一直重试，直到第2天才恢复。  
那么第2天就会同时存在两个生成报表的任务，如果得不到任务的首次调度时间，那么就无法确定哪个任务是当天的报表任务，哪个是前一天的生成报表任务。  
所以我们需要有一种能在任务执行中获取当前任务信息（包括首次调用时间、重试次数等）的方法。  
请问现在是否有这种方法？  

另外重试的时间间隔是否可以配置？

**Comment by xuxueli** [comment]
该功能评估缺少通用型，建议定制实现。
