### ISSUE TITLE
I stop the job , but the job is still scheduled in the background

### ISSUE THREAD

**Issue by tylr2017** [xuxueli/xxl-job#1577]
1. Question
When I stopped the job on the job management page, the job was still scheduled in the background. At this point, the job management page is refreshed and the job is not stopped。

2. xxl-job version
2.1.2

3.Cause analysis
When I stopped the job on the job management page, the xxl-job will modify the `trigger_status` of job to 0, See the following code：
![image](https://user-images.githubusercontent.com/33024821/79234541-fd6d0600-7e9c-11ea-88bf-96be71aa34f0.png)

But, the scheduleThread in the `JobScheduleHelper `probably got the jobInfo(`trigger_status=1`) before I stop the job, and the `trigger_status` is updated to database after the scheduling, see the following code:
![image](https://user-images.githubusercontent.com/33024821/79234906-82f0b600-7e9d-11ea-9254-baf55e00fb56.png)

So, the job is restarted due to concurrency.

I hope the author can modify the bug,thanks.

**Comment by xuxueli** [comment]
新版本已修复优化，建议升级。
