### ISSUE TITLE
请问支持spring cloud eureka吗

### ISSUE THREAD

**Issue by Mrshengjie** [xuxueli/xxl-job#158]
我这边项目用spring cloud做的,看您这是说是spring cloud consul支持的?支持eureka吗?我这边是eureka的.

**Comment by xuxueli** [comment]
你好，感谢关注和反馈：）
XXL-JOB系统底层已经封装成一个稳定的整体，不强制依赖第三方服务，因此不依赖eureka的啊。

**Comment by diaodiaofly** [comment]
@xuxueli 您好，虽然已经关掉了     很多人有这种需求  想通过xxl-job 注册到eureka或者consul   然后在定时任务里面调对应服务的业务，获取结果  请问如何注册上去呢？

**Comment by yuweiming2016** [comment]
我太需要了

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/58610634-b6a30b80-82de-11e9-9940-dc4a27246842.png)
d底层里把红框识别为服务名称就好了

**Comment by diaodiaofly** [comment]
> ![image](https://user-images.githubusercontent.com/22490427/58610634-b6a30b80-82de-11e9-9940-dc4a27246842.png)
> d底层里把红框识别为服务名称就好了

这样可行？

**Comment by wangzhengxi** [comment]
@diaodiaofly @JiYou @yuweiming2016  我改了下客户端源码可以支持，请看这个项目https://github.com/wangzhengxi/xxl-job-eureka

**Comment by donglulu123** [comment]
> @diaodiaofly @JiYou @yuweiming2016 我改了下客户端源码可以支持，请看这个项目https://github.com/wangzhengxi/xxl-job-eureka

哈哈哈 找到你了
