### ISSUE TITLE
xxl-rpc provider netty_http server caught exception

### ISSUE THREAD

**Issue by chenxd1991** [xuxueli/xxl-job#1582]
什么情况下会出现这个异常。本地测试没有问题，部署服务器就会出现

**Comment by xiepeikuan** [comment]
你部署在什么环境了？我的也是，部署在k8s集群里

**Comment by chenxd1991** [comment]
> 你部署在什么环境了？我的也是，部署在k8s集群里

是的 k8s里，很多项目是这样部署的，但是只有其中一个出现找不到具体的原因

**Comment by maojiayang1012** [comment]
我也遇到这个问题了，怎么解决？

**Comment by loveNin** [comment]
我的也出现这个问题了，xxl-job registry error和类型转换异常

**Comment by xuxueli** [comment]
新版本已修复优化，建议升级。
