### ISSUE TITLE
是不是新版不支持特殊符号的Accesstoken

### ISSUE THREAD

**Issue by iwzd520** [xuxueli/xxl-job#1583]
我就想用中文问个2.2.0版本的问题？
是不是新版不支持特殊符号的Accesstoken，比如$。

因为我把Accesstoken中的$去掉后，就好了，否则就是报错，如下：

14:56:31.153 logback [xxl-job, executor ExecutorRegistryThread] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='xxxx-01', registryValue='xxx.xxx.xxx.xxx:xxxx'}, registryResult:ReturnT [code=500, msg=The access token is wrong., content=null]

**Comment by xuxueli** [comment]
你好，Accesstoken通过http header传递，特殊符号会被转移不建议使用。

**Comment by iwzd520** [comment]
这个不是问题的问题，感谢！
