### ISSUE TITLE
2.2.0版本执行示例任务，调度时间和执行时间显示'Invalid date'

### ISSUE THREAD

**Issue by smalldok** [xuxueli/xxl-job#1584]
![image](https://user-images.githubusercontent.com/13725783/79457075-279c0080-8022-11ea-9b11-5faadd74b31f.png)

**Comment by xuxueli** [comment]
你好，问题无法复现。
建议强刷以下浏览器缓存，重新编译部署尝试下。

**Comment by kevinfujiang** [comment]
https://jifa.name/blog/2018-04-25--momentjs-safari-Invalid-date/
是safari的问题， 在Safari里：
> data="2020-05-14T01:45:00.000+0000"
< "2020-05-14T01:45:00.000+0000"
> moment(new Date(data)).format("YYYY-MM-DD HH:mm:ss")
< "Invalid date"
> moment(data).format("YYYY-MM-DD HH:mm:ss")
< "2020-05-14 09:45:00"
