### ISSUE TITLE
执行器异常退出或者被kill掉时，当前任务状态无法上传到服务器端，导致任务一直处于进行中

### ISSUE THREAD

**Issue by quanwuhui** [xuxueli/xxl-job#1587]
https://github.com/xuxueli/xxl-job/blob/master/xxl-job-core/src/main/java/com/xxl/job/core/thread/JobThread.java
第184 到 195行代码有问题，当程序被kill或者interrupt的时候，finally 方法不会被执行，那么当前任务的执行失败状态不会传给xxl-job服务端。

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
