### ISSUE TITLE
连接阿里云RDS（MySQL）失败

### ISSUE THREAD

**Issue by QloveB** [xuxueli/xxl-job#1588]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
version：2.2.1

### Other information
【application.properties】
spring.datasource.url=jdbc:mysql://rm-8vxxxxxxxxxxxxxxxxx.mysql.zhangbei.rds.aliyuncs.com:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai

【log】
18:43:54.187 logback [xxl-job, admin JobLosedMonitorHelper] ERROR com.zaxxer.hikari.pool.HikariPool - HikariCP - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

**Comment by pengzhizhuo** [comment]
这个问题我也碰到了,是因为它数据库连接默认使用了 SSL，你在数据库连接字符串后加上useSSL=false 就搞定了，供参考

具体问题发现并解决：
发现报错Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
原来是是因为使用了useSSL=true，改为useSSL=false就可以正常访问了。

**Comment by QloveB** [comment]
> 这个问题我也碰到了,是因为它数据库连接默认使用了 SSL，你在数据库连接字符串后加上useSSL=false 就搞定了，供参考
> 
> 具体问题发现并解决：
> 发现报错Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
> 原来是是因为使用了useSSL=true，改为useSSL=false就可以正常访问了。

好的，知道了，感谢~！

**Comment by xuxueli** [comment]
@pengzhizhuo +1
