### ISSUE TITLE
调度的吞吐量

### ISSUE THREAD

**Issue by zhonghuwu** [xuxueli/xxl-job#1591]
想咨询下：调度中心单机支持每分钟或者每秒最大任务数量是多少。采用集群方式比如3台机器，是否吞吐量可以翻3倍。使用版本  v2.1.0 

谢谢啦

**Comment by xuxueli** [comment]
你好，单机任务量受到 ”DB速度、网络速度“ 等因素影响。正常情况下，单机任务量 5K 以上，文档有说明。
吞吐量可以通过两种方式提升：
- 提高调度中心调度线程数；
- 调度中心做集群

任务一种方式（v2.2.0 之后版本），均可以准线性提升吞吐量。
