### ISSUE TITLE
请教一个Quartz的问题

### ISSUE THREAD

**Issue by yuanmabiji** [xuxueli/xxl-job#1592]
1，老师，您好，我想请教一个Quartz被SpringBoot托管后会，即使自己配置了JobStoreTX，但是最终配置失效，配置的JobStoreTX会强制替换为LocalDataSourceJobStore，而使用LocalDataSourceJobStore的话会设置autocommit=ture，从而使得select ... for update悲观锁失效，此时集群节点并行启动时就会出现在多个节点同时争抢到同一资源。 

2，疑问：
既然Spring接管Quartz后，强制使用LocalDataSourceJobStore，而LocalDataSourceJobStore又是JobStoreCMT的子类，而JobStoreCMT一般用在JTA事务。而我用的Quartz的使用场景是单库，为何Spring还要强制使用LocalDataSourceJobStore呢？在LocalDataSourceJobStore中为何要设置autocommit=true，而使得select...for upate悲观锁失效呢？这些这么低级的错误Spring肯定能考虑到，难道是Spring托管Quartz后，我们的相关设置不对吗？

**Comment by xuxueli** [comment]
你好，这种情况建议为quartz单独维护连接池，不和Spring混用。
