### ISSUE TITLE
2.2.0版本的执行器管理无法使用

### ISSUE THREAD

**Issue by xuexiaoao** [xuxueli/xxl-job#1594]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
* 升级到2.2.0版本后发现**执行器管理**页面没有任何的执行器信息，搜索无反应
* springboot版本的执行器的**xxl.job.executor.port**配置为0，注册端口仍然为9999
### Other information

**Comment by ZrealPJ** [comment]
我也遇到也，清一下缓存就行了。

**Comment by xuxueli** [comment]
@ZrealPJ +1，强刷浏览器，清理下前端缓存即可。
