### ISSUE TITLE
2.2.0版新增执行器后始终无法在执行器界面加载

### ISSUE THREAD

**Issue by yueyuanyu** [xuxueli/xxl-job#1599]
公司打算接入xxljob,目前采用2.2.0版时,发现在管理员界面新增执行器后执行器界面一直显示不出来F12调试发现并未发现发起相关请求,点击搜索也并未发起任何请求。
ps：采用2.1.2版本是对的(但是与我司微服务整合时启动不了 xxljob报错applicationContext空指针,升级成2.2.0版没问题,但管理员界面又有问题,很纠结)

**Comment by xuxueli** [comment]
你好，应该JS缓存导致，建议强刷一下浏览器缓存。

**Comment by yueyuanyu** [comment]
@xuxueli 此外 glue(java)模式是不支持lambada表达式吗,我使用此模式报错
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script15874435930991590102261.groovy: 115: unexpected token: -> @ line 115, column 130.
   entityList.stream().map(idtty -> idtty.g
                                 ^

1 error

**Comment by yueyuanyu** [comment]
具体抛异常地方定位到at com.xxl.job.core.glue.GlueFactory.getCodeSourceClass(GlueFactory.java:77)

**Comment by xuxueli** [comment]
@yueyuanyu 你好，glue-java本质上采用groovy语法，groovy 支持 stream，但是有细小差异。
可以学习下groovy，或者改为常规方式开发。
