### ISSUE TITLE
任务HA策略疑问

### ISSUE THREAD

**Issue by JsonJu** [xuxueli/xxl-job#16]
任务“执行器地址”支持配置多个，用逗号分隔，如“127.0.0.1:9998,127.0.0.1:9999”。
如果任务配置多个执行器地址，当调度中心每次发起调度请求时，会按照地址配置的顺序依次对执行器发出心跳检测请求，第一个检测为存活状态的执行器将会被选定。
-------------------------------------------------------------------------------------------------------------------
感觉这种执行器选定策略不能很好的利用资源，可以考虑采用更合理的轮询选定策略。

**Comment by xuxueli** [comment]
你好，感谢对XXL系列的关注！

这是v1.3及以前版本的执行器选举规则。v1.3之后的版本，调度时会针对执行器列表进行一次随机乱序，降低单台执行器的执行压力，即轮训策略。

在v1.5之后的版本会考虑新增执行器选择规则的可选参数，支持选择“随机”或者“单点”，前者每次调度会轮训选择一台执行器，后者会固定选择第一台执行器 ：）

**Comment by JsonJu** [comment]
赞！现处于研究阶段，xxl系列的开源项目很实用！

**Comment by xuxueli** [comment]
感谢支持和关注 ：）
