### ISSUE TITLE
json解析特殊字符失败，导致回调循环异常

### ISSUE THREAD

**Issue by junyang100** [xuxueli/xxl-job#1601]
v2.1.2
自定义JobHandler中如未手动捕获异常，且抛出的异常信息中包含特殊字符，如“，将会导致admin项目JobApiController.callback.parseParam无法解析，处理失败，而客户端TriggerCallbackThread会不断在callbacklog目录下生成重试文件，再次调用JobApiController.callback，如此循环无法终止，只能手动删除callbacklog目录下文件。

**Comment by ecmsglobal** [comment]
2.1.2的bug，升级到2.2.0就好了。或者找下其他issue里面有解决方案。执行器侧的bug。

**Comment by duanjinjin** [comment]
遇到相同的问题

**Comment by xuxueli** [comment]
@ecmsglobal  +1，升级即可。
