### ISSUE TITLE
是否有从执行器嵌入的项目中，使用API对调度系统中增加任务、执行任务的操作

### ISSUE THREAD

**Issue by RemonJia** [xuxueli/xxl-job#1606]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by RemonJia** [comment]
xxl-job 2.2.0版本
在业务项目（已整合执行器）,希望能通过api直接在调度系统中增加相关任务

**Comment by cdcchen** [comment]
先看文档，你们调研都不看文档的吗？

**Comment by dudiao** [comment]
最新版本是支持通过API方式增加调度任务的

**Comment by xuxueli** [comment]
@cdcchen +1
