### ISSUE TITLE
无法在@XxlJob任务方法中使用feignclient调用其他微服务接口

### ISSUE THREAD

**Issue by baiyeGit** [xuxueli/xxl-job#1611]
在@XxlJob方法中，调用其他微服务接口，没有执行，查看日志报如下错：
![image](https://user-images.githubusercontent.com/44809697/79956934-695df880-84b3-11ea-9473-d5d8464d3efd.png)
但是新建一个controller里面去调用这个feignClient就能调到，说明注册是没问题的，路径也是没问题的
![image](https://user-images.githubusercontent.com/44809697/79957077-a629ef80-84b3-11ea-8d40-cb257cbe592f.png)

**Comment by wyyp996** [comment]
请问您的问题有解决方案吗？本人也遇到同样的问题了？？还请大神指点！！！

**Comment by xuxueli** [comment]
你好，问题无法复现。
上述报错日志，是执行器回调失败的日志，并非任务调度日志。回调失败，可以检查下回调地址配置。
