### ISSUE TITLE
任务注册

### ISSUE THREAD

**Issue by GXM2333** [xuxueli/xxl-job#1615]
刚开始调研xxl-job，我看了下文档和官方使用示例有些疑问：

1.job的创建只能通过admin界面吗，不支持通过API向调度器实时提交创建任务吗。

2.如果第1个问题支持的话，可否支持提交 单个主任务[ 比如 newTask (TaskId) ] 或 批量提交子任务 
[new ArrayList().{new SubTask(taskId,subTaskId),new SubTask(taskId,subTaskId)  } ]。调度器是否能够管理起 批量子任务的生命周期。如每个子任务的中断，暂停，重试等。

3.如果在执行器 jobHandler中又用了几层异步线程来拆解任务或子任务，那任务和子任务的生命周期管理，日志管理 是否可1以传递到后面的异步线程中，如果不行的话目前代码容易定制吗？我想的话这个操作就是要通知到异步线程要中断了。调用下异步线程的interrupt()方法，然后异步线程不断轮训检查中断状态。

希望大佬能够回答下，在线等，比较着急。十分感谢：）

**Comment by no1412** [comment]
我也遇到了相同的问题，不过我觉得可以通过admin界面创建job的接口实现

**Comment by cxxly** [comment]
+1

**Comment by xuxueli** [comment]
@no1412 +1，可以借助admin新建job接口实现。
