### ISSUE TITLE
no protocol是什么原因导致的呢？

### ISSUE THREAD

**Issue by jlcon** [xuxueli/xxl-job#1616]
Please answer some questions before submitting your issue. Thanks!

触发调度：
address：190.168.1.37:20770
code：500
msg：xxl-rpc remoting error(no protocol: 190.168.1.37:20770/run), for url : 190.168.1.37:20770/run

**Comment by iminders** [comment]
配置 `xxl.job.executor.address=${EXECUTOR_HOST}:${EXECUTOR_PORT}`
EXECUTOR_HOST 的格式为：`http://(ip/域名)`

**Comment by jlcon** [comment]
自动怎么办呢？我发现是版本兼容的问题

**Comment by iminders** [comment]
> 自动怎么办呢？我发现是版本兼容的问题

我理解的是：xxl-job scheduler向 executor发request走restful api 需要的address包含`http`, 表示 HTTP协议

**Comment by jlcon** [comment]
2.2.0之前的版本不需要

**Comment by iminders** [comment]
> 2.2.0之前的版本不需要

我刚用，直接就是用2.2.0了，碰到这个问题，发现这种方法能fix

**Comment by jlcon** [comment]
嗯，谢谢。但是后来我发现还有其他问题，2.2.0这个版本不太敢用，2.1.2自己升级了springboot版本为2.x后也用起来挺好。

**Comment by iminders** [comment]
有些什么问题，share出来，让作者改进哈

**Comment by jlcon** [comment]
1、发现2.2.0源码跟发布到maven仓库有个设置类方法命名不一致，导致导入源码后项目里面应用2.2.0会报错。
2、2.2.0会多应用很多三方包，例如groovy

**Comment by ltjsj** [comment]
@jlcon 请问是怎么解决的啊，我也遇到这个问题，用的新版本2.2.0

**Comment by jlcon** [comment]
> 
> 
> @jlcon 请问是怎么解决的啊，我也遇到这个问题，用的新版本2.2.0

加http头
