### ISSUE TITLE
请问一下xxl job如何支持生产者消费者的方式进行任务调度？

### ISSUE THREAD

**Issue by qiushics** [xuxueli/xxl-job#1619]
请问一下xxl job如何支持生产者消费者的方式进行任务调度？
说明：
应用程序(生产者)产生调度信息，存入数据库/消息队列等。
当数据库/消息队列中有调度信息时，xxl job进行对应的任务调度，将相关调度信息发送给相关的执行器。
各执行器相当于消费者，处理完调度后返回给xxl job。
xxl job再返回给生产者。

这种方法是否支持？
如果支持应该如何操作？
如果不支持的话有什么可选方案吗？

谢谢

**Comment by xuxueli** [comment]
你好，这种场景建议接入 www.xuxueli.com/xxl-mq
