### ISSUE TITLE
当任务执行失败时，执行任务回退，清除任务脏数据，急急急

### ISSUE THREAD

**Issue by zhangpanzhi** [xuxueli/xxl-job#162]
现在有这么个需求就是当任务内部业务出现错误，比如这个调度任务是一个插入数据库的数据的业务，当任务出现错误时，就会产生很多的脏数据，现在的需求是，如何当任务内部错误500时，让任务执行回退功能，清除脏数据，急，急，急

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
这种功能需求，是指业务数据的事务性支持。这种需求比较偏业务，推荐在执行器中自己实现和控制事务，可以google一下，有很多方案教程。
