### ISSUE TITLE
目前调度器与执行器之间是http方式互访，能否考虑增加支持https方式，增强安全性

### ISSUE THREAD

**Issue by ecmsglobal** [xuxueli/xxl-job#1624]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
调度器与执行器之间支持https方式交互
### Actual behavior
目前采用http方式交互
### Other information

建议考虑增加https方式，便于公网使用过程中最大程度保证安全

**Comment by xuxueli** [comment]
你好，目前是支持https通讯的，可以体验下。
而且目前双向通讯也支持内置的token机制进行加密的。

**Comment by ecmsglobal** [comment]
好的，我试一下。谢谢。

**Comment by brucelpt** [comment]
> 你好，目前是支持https通讯的，可以体验下。 而且目前双向通讯也支持内置的token机制进行加密的。

你好应该怎么支持 HTTPS？调度器调用执行器需要改为 https
