### ISSUE TITLE
能支持动态创建定时任务吗

### ISSUE THREAD

**Issue by zgliang88** [xuxueli/xxl-job#1625]
请问，什么时候支持动态创建定时任务的 ，现在用xxljob 有这样的场景

**Comment by xuxueli** [comment]
你好，可以借助提供的API服务创建。可以自定扩展调度中心 restful api实现。

**Comment by zyx2075257** [comment]
> 你好，可以借助提供的API服务创建。可以自定扩展调度中心 restful api实现。

能否说得详细些

**Comment by zyx2075257** [comment]
@zgliang88  你好，这个问题解决了吗，可否说下怎么解决的，谢谢

**Comment by luozhao528** [comment]
自己封装api

**Comment by wukaka** [comment]
大兄哋，看这里 完美解决 https://blog.csdn.net/lsqingfeng/article/details/108343579。不过，我觉得后期版本是不是可以考虑开发动态创建任务这个功能点？

**Comment by xuxueli** [comment]
> 大兄哋，看这里 [xxl-job通过代码的方式动态添加任务，修改任务，执行任务，停止任务等](https://blog.csdn.net/lsqingfeng/article/details/108343579)

+1
