### ISSUE TITLE
2.2.0版本执行器注册不了，xxl-job-admin执行器列表没有

### ISSUE THREAD

**Issue by gujiachun** [xuxueli/xxl-job#1629]
//执行器代码
@Component
public class OrderJobHandler {
	
	@XxlJob("orderTimeoutJobHandler")
	public ReturnT<String> orderTimeoutJobHandler(String param) throws Exception {
		
		XxlJobLogger.log(">>>>orderTimeoutJobHandler");
		
		return ReturnT.SUCCESS;
	}

}

//配置
xxl: 
  job: 
    accessToken: 
    admin:
      addresses: http://192.168.110.8:8080/xxl-job-admin
    executor:
      appname: jobDemo1
      address: 
      ip: 
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30
      port: 0

//注入配置
@Configuration
@Slf4j
public class XxlJobConfig {
@Value("${xxl.job.admin.addresses}")
    private String adminAddresses;
	
	@Value("${xxl.job.accessToken}")
    private String accessToken;

    @Value("${xxl.job.executor.appname}")
    private String appName;
    
    @Value("${xxl.job.executor.address}")
    private String address;

    @Value("${xxl.job.executor.ip}")
    private String ip;

    @Value("${xxl.job.executor.port}")
    private int port;

    @Value("${xxl.job.executor.logpath}")
    private String logPath;

    @Value("${xxl.job.executor.logretentiondays}")
    private int logRetentionDays;

    @Bean(initMethod = "start", destroyMethod = "destroy")
    public XxlJobSpringExecutor xxlJobExecutor() {
        log.info(">>>>>>>>>>> qy-schedule-server xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        //### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        //### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
        xxlJobSpringExecutor.setAppname(appName);
        //### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
        xxlJobSpringExecutor.setAddress(address);
        //### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
        xxlJobSpringExecutor.setIp(ip);
        //### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
        xxlJobSpringExecutor.setPort(port);
        //### 执行器通讯TOKEN [选填]：非空时启用；
        xxlJobSpringExecutor.setAccessToken(accessToken);
        //### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径
        xxlJobSpringExecutor.setLogPath(logPath);
        //### 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }
}

springboot项目，一直执行器注册不了，是怎么回事？？

**Comment by aslzl** [comment]
请问 这个问题 后来是如何解决的
