### ISSUE TITLE
tables_xxl_job.sql执行报错

### ISSUE THREAD

**Issue by dkgee** [xuxueli/xxl-job#1630]
使用mysql 5.7版本，执行tables_xxl_job.sql报错，显示
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
或者
[Err] 1055 - Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'information_schema.PROFILING.SEQ' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

核对后，发现是sql环境设置有问题，改成下面就可以了
SET NAMES utf8mb4;
SET sql_mode = '';
SET sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES';

**Comment by xuxueli** [comment]
建议升级 8.0及以上
