### ISSUE TITLE
您好作者和各位朋友，本人GLUE模式(Shell) 多台服务器ssh远程调用问题

### ISSUE THREAD

**Issue by ystwo1314** [xuxueli/xxl-job#1631]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
我正在使用最新版本2.2.0版本
### Other information

作者您好和各位码友们好，我现在遇到一个问题，就是在使用xxl-job的GLUE模式(Shell) 的时候，遇到一个无法解决的问题。情况如下：
1、我xxl-job admin 部署到 x.x.x.111 服务器该服务器是处理python脚本等定时任务的。
2、我业务代码A部署到x.x.x.112 服务器。在使用shell模式的时候想ssh 跨服务请求到111服务上，但因为使用的是docker容器。导致 容器A无法使用ssh命令。所以远程调用111服务无法使用。不知道大家有没有类似情况，是如何解决的呢？

**Comment by xuxueli** [comment]
该问题非本项目问题，建议谷歌相关具体问题。
