### ISSUE TITLE
xxl-job经常出现一段时间所有job都没有执行，持续大概15分钟

### ISSUE THREAD

**Issue by 664177758** [xuxueli/xxl-job#1632]
我们有一个15秒的任务，按理每个小时会执行240次，但是我们查询xxl-job的日志，发现该job经常出现15分钟完全没有日志，没有执行的情况，请问是什么原因？
![image](https://user-images.githubusercontent.com/17041266/80381833-18e00400-88d4-11ea-8fda-b89970d10371.png)
![image](https://user-images.githubusercontent.com/17041266/80381895-2f865b00-88d4-11ea-9afd-c07ef9da477c.png)
这个问题表频发，而且发生时，查询xxl-job的admin日志没有任何错误，同时该时刻xxl-job的服务器资源充分

**Comment by ltjsj** [comment]
你这个问题 解决了吗？我也遇到过，有时不执行的问题，

**Comment by 664177758** [comment]
解决不了，始终还是偶然有这个问题，我们的处理方式是安装两个独立的xxl-job，一个执行，一个做遗漏检查。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ltjsj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午3:17
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"Dancer"<664177758@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] xxl-job经常出现一段时间所有job都没有执行，持续大概15分钟 (#1632)





 
你这个问题 解决了吗？我也遇到过，有时不执行的问题，

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。
确认是否存在调度中心集群部署情况（务必机器时钟一致）？以及DB主从部署情况（务必走主库）？
