### ISSUE TITLE
2.2.0最新版部署成功，执行器自动注册成功，但是admin界面上显示不出来，也没有异常，无法定位问题

### ISSUE THREAD

**Issue by zhangqinzhong** [xuxueli/xxl-job#1633]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by luozhao528** [comment]
我也发现有这个问题，我直接在执行器管理页面添加执行器的方式。

**Comment by An0nymous0** [comment]
一样
@xuxueli

**Comment by Malop** [comment]
同问，一样的问题，数据库里xxl_job_registry表已经有注册上来的执行器地址了，但是admin界面里没有显示Online机器地址，导致任务无法执行，尝试手工录入机器地址，但任务执行的时候直接rpc调用失败超时@xuxueli

**Comment by Malop** [comment]
> 同问，一样的问题，数据库里xxl_job_registry表已经有注册上来的执行器地址了，但是admin界面里没有显示Online机器地址，导致任务无法执行，尝试手工录入机器地址，但任务执行的时候直接rpc调用失败超时@xuxueli

跟踪了下，数据库里的xxl_job_registry表一直在被刷新，就是说执行器一直在不停的注册-删除，注册-删除，很奇怪。。。

**Comment by muxinzi** [comment]
我这边自动注册显示的服务器个数与实际服务器个数对不上，显示8个，实际10个

**Comment by KuoCHsiang** [comment]
如果执行器项目重新启动，在admin面板中执行的状态是不在线，导致任务执行失败，这个问题需要怎么解决

**Comment by LiJianGuo123** [comment]
老哥，这个问题有解了吗？ 我先在也是没有显示Online机器地址。但是我看debug日志，是正常注册的，code是200.

**Comment by LiJianGuo123** [comment]
我的问题解决了，建议看下XxlJobRegistry.xml 中的 findAll 方法，这个是否有更改。这个sql关系着执行器的注册。

**Comment by itsanty** [comment]
最新版本的2.4.0-SNAPSHOT也存在这个问题，我是在JobRegistryHelper的monitor中将xxl_job_registry中的执行器更新到xxl_job_group中

**Comment by xuxueli** [comment]
注册有延迟，30s左右。
