### ISSUE TITLE
任务执行一次就会生成一个日志文件？

### ISSUE THREAD

**Issue by joey-happy** [xuxueli/xxl-job#1638]
![image](https://user-images.githubusercontent.com/16012082/80565952-623f6900-8a24-11ea-956f-5ebb91d8e129.png)

现在看到的现象是任务执行一次 就会生成一个新的日志文件

这个有啥地方可以配置吗？

**Comment by xuxueli** [comment]
该功能评估缺少通用型，建议定制实现。
