### ISSUE TITLE
当前的版本是否支持一个任务只是添加上，但不指定定时规则，然后只通过api接口来触发？

### ISSUE THREAD

**Issue by cdcchen** [xuxueli/xxl-job#1639]
我说的这种场景可能直接使用队列或是分布式任务系统更合适，但是小系统不想部署那么多系统，维护成本太高。

所以想把xxl-job也当成任务系统来用。举个例子，像用户注册之后，后端异步发送一些邮件或是消息一类的，直接通过api来触发一个预先添加的任务，即时触发。

**Comment by ckasdf1405** [comment]
任务管理页面，状态=STOP就行了，不要点击【操作-启动】按钮。需要触发时点击【操作-执行一次】

**Comment by xuxueli** [comment]
新版本已优化/支持，建议升级。
