### ISSUE TITLE
失败不一定发送邮件

### ISSUE THREAD

**Issue by Baivin** [xuxueli/xxl-job#164]
测试邮件发送，jobHandler 故意抛出异常，本地开发正常，肯定能发出邮件。部署在服务器上后，异常状况有时执行发送邮件，有时没发（大部分是没发，因为发送邮件的log没出来），请问这个是什么问题？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
请问在这期间，调度中心存在重启的情况吗？机器重启情况下，任务告警信息可能会被销毁掉。

**Comment by Baivin** [comment]
没有重启机器哦，就是测试、正式的服务器会出现报错但是发邮件的线程没有执行发邮件的方法，有时候会发，本地运行是正常的。
