### ISSUE TITLE
通过RESTFUL API的方式，需要配置什么吗？

### ISSUE THREAD

**Issue by ihenjoy** [xuxueli/xxl-job#1642]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
我的执行器是以.net MVc的方式提供，但现在发现 调度中心并不会发迸/beat 这样的url，而是以hessian的方式 进行序列化，并调用的是执行器的根地址，就是restful的方式是调用不了的

### Other information

**Comment by linzhiqiang** [comment]
beat触发 路由策略选择 "故障转移”时触发, 但是这里有个bug没有触发，需要修改源码。
 我也是写.net版本的执行器发现的

**Comment by ihenjoy** [comment]
> beat触发 路由策略选择 "故障转移”时触发, 但是这里有个bug没有触发，需要修改源码。
> 我也是写.net版本的执行器发现的

这个不是问题了，后面发现，是我引用的xxl-job版本比较低，在2.2.0中，xxl-job已经调整Restful的方式
