### ISSUE TITLE
glue shell方式，长时任务无法终止

### ISSUE THREAD

**Issue by sdyyf** [xuxueli/xxl-job#1645]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.1
### Expected behavior
执行日志中能够终止掉glue shell方式调度的长时任务
### Actual behavior
管理后台显示终止成功，实际执行器机器上的脚本没有被终止
### Steps to reproduce the behavior
glue shell代码：
`#!/bin/bash
php artisan queue:work
exit 0`
注：php artisan queue:work 就是laravel框架的任务队列消费脚本，是个长时任务。以前是通过supervisor调度管理的
### Other information

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
