### ISSUE TITLE
2.0.2 执行完毕了 还卡在执行中 是怎么回事

### ISSUE THREAD

**Issue by 617450941** [xuxueli/xxl-job#1646]
![image](https://user-images.githubusercontent.com/7607957/80682186-a13cef80-8af4-11ea-9f5c-bd7be063096b.png)
![image](https://user-images.githubusercontent.com/7607957/80682222-ae59de80-8af4-11ea-911e-509bafecf139.png)

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
