### ISSUE TITLE
xxl-job2.1 能支持	59 59 23 01 05 ? 2020-2021 这种年月日时分秒定时调度吗？

### ISSUE THREAD

**Issue by ltjsj** [xuxueli/xxl-job#1648]
xxl-job2.1 能支持	59 59 23 01 05 ? 2020-2021 这种年月日时分秒定时调度吗？

因业务有个需求，
需要对订单开始时间，和结束时间  这两个时间做任务调度处理数据

59 59 23 01 05 ? 2020-2021   设置了这样的cron 时间表达式，但是会报logback 找不到的异常

很不稳定的样子，有些时间能成功调度，有时不行

请问这个有没什么方法 解决。

**Comment by xuxueli** [comment]
延时任务，建议使用 xxl-mq
