### ISSUE TITLE
建議增加過期時間的設定

### ISSUE THREAD

**Issue by abccbaandy** [xuxueli/xxl-job#1655]
### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
過期後都要補執行
### Actual behavior
現在只有5s內才會(看文件
### Other information

**Comment by xuxueli** [comment]
你好，针对过期5s的任务的补偿。你的建议只补偿1次，还是过期了多少次就补偿多少次？原因是什么啊？

**Comment by abccbaandy** [comment]
就類似quartz的`MISFIRE_INSTRUCTION_FIRE_ONCE_NOW`那樣，立刻補償一次

因為我們有些任務要每天執行一次，但其實不限定時間
ex:
每天1點執行，但2點執行也沒差，所以萬一半夜系統掛了，早上來重啟系統要能繼續執行過期的任務

**Comment by xuxueli** [comment]
该功能评估缺少通用型，建议定制实现。
