### ISSUE TITLE
java glue lambda不能使用

### ISSUE THREAD

**Issue by shouziws** [xuxueli/xxl-job#1656]
等待作者爸爸和网友的回复
使用的core版本:2.2.0
使用的lambda方式:
![1](https://user-images.githubusercontent.com/33045888/81166589-5e808900-8fc6-11ea-876d-c5e7a0ecf1a3.png)
我看之前的issue你说是可以使用，但是我这边是报错
以下是报错信息
![2](https://user-images.githubusercontent.com/33045888/81166731-938cdb80-8fc6-11ea-8301-03ae758c6bc3.png)
是我那里不对吗？ 调试中心 和 执行器都没问题，这里的glue就是不对，请问如何解决呢，

**Comment by xuxueli** [comment]
glue-Java底层借助groovy实现，其lambda语法与Java有思维差异，可以查阅资料了解下。紧急的话， 可以调整为常规Java语法。

**Comment by 15670600690** [comment]
老铁，你有好的解决方案没

**Comment by 15670600690** [comment]
老铁，你有好的解决方案没

**Comment by shouziws** [comment]
> 老铁，你有好的解决方案没

我没有看glue语法资料查阅，写进代码里重新编译运行

**Comment by 15670600690** [comment]
我最后把表达式  替换成匿名函数处理了
