### ISSUE TITLE
k8s上部署xxl-job2.1.2出现了172网段的IP

### ISSUE THREAD

**Issue by caiyj374** [xuxueli/xxl-job#1658]
xxl-job 2.1.2 docker 镜像部署在k8s上
任务执行时调度机器出现了172.17.*.*/16网段，k8s集群是没有这个网段的，docker也不是这个网段的，所以请教一下作者及各位大牛这个网段的IP是怎么生成的，导致无法连通其他的服务，出现了连接超时出错误？

**Comment by chuangtse** [comment]
172.17.0.0/16 这是PodCIDR 分配的ip地址，你可以看下集群是不是分配了 可以通过kubectl get po --all-namespaces -o wide|grep 172.17 看看是不是运行的服务注册上来的。

**Comment by xuxueli** [comment]
你好，多网卡情况下，执行器支持手动指定注册IP。也支持手动指定注册IP端，可以参考执行器sample示例。
