### ISSUE TITLE
希望 xxl-job 能支持工作日触发模式

### ISSUE THREAD

**Issue by yangyanqing** [xuxueli/xxl-job#1660]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0

### Expected behavior
推送规则增加工作日模式，按照排班表只在工作日发送，

### Actual behavior
目前只能按照固定周几的模式，无法满足中国推送需求。

### Other information

**Comment by xuxueli** [comment]
你好，节假日情况变动比较大，并没有一个标准计算方式。这种工作日/节假日场景，可以在执行器逻辑里做过滤。

**Comment by xuxueli** [comment]
该问题非本项目问题，建议谷歌相关具体问题。
