### ISSUE TITLE
2.2.0版本，源码下载运行报错500

### ISSUE THREAD

**Issue by zgz757183190** [xuxueli/xxl-job#1661]
你好大佬，2.2.0版本下载运行，修改admin数据库配置后，每3s执行一次任务 ，后台界面报错500.有时候成功失败各一半。请问一下这是什么情况呢？

触发调度：
address：http://192.168.0.119:9999/
code：500
msg：xxl-rpc remoting error(connect timed out), for url : http://192.168.0.119:9999/run

**Comment by handy-git** [comment]
我2.2.0也出现这个问题,请问你有解决吗?

**Comment by zgz757183190** [comment]
还是会出现这个情况，只是没有那么频繁了，你从新下载一个最新的试试看。

**Comment by bzlrj** [comment]
我也是同样的问题

**Comment by hzxrosydawn** [comment]
@zgz757183190 @handy-git 我的2.2.0也遇到这个问题了。在同一台Windows开发电脑上，刚开始还好好的，突然就出现了这个情况。两位找到解决办法没有啊

**Comment by hzxrosydawn** [comment]
@zgz757183190 @handy-git 我找到问题了，超时失败的日志显示发起调度控制的IP是另一台服务器，多个调度管理器之间冲突了，干掉其他不在集群内的调度器就可以了

**Comment by Q11shiyi** [comment]
@hzxrosydawn 您好，可以详细说明下怎么解决该问题的吗，谢谢

**Comment by imtzc** [comment]
同样遇到这个问题，数据库如果设置为本地数据库，就没问题，设置为阿里云上的数据库，就会有大量的失败，怀疑是否跟从通过数据库进行并发锁有关，望有解决的老铁给个回复

**Comment by Rehoni** [comment]
我在本机跑调度器和多个执行器没有问题；在远程服务器部署的调度器，本机的多个执行器执行任务才会出现xxl-rpc remoting error(connect timed out)。
成功案例
> 任务触发类型：手动触发
> 调度机器：10.0.3.122
> 执行器-注册方式：自动注册
> 执行器-地址列表：[http://10.0.3.122:9999/]
> 路由策略：第一个
> 阻塞处理策略：单机串行
> 任务超时时间：0
> 失败重试次数：0
>
> 触发调度<<<<<<<<<<<
> 触发调度：
> address：http://10.0.3.122:9999/
> code：200
> msg：null

失败案例
> 任务触发类型：手动触发
> 调度机器：198.120.100.101
> 执行器-注册方式：自动注册
> 执行器-地址列表：[http://10.0.3.122:9998/]
> 路由策略：第一个
> 阻塞处理策略：单机串行
> 任务超时时间：0
> 失败重试次数：0
>
> 触发调度<<<<<<<<<<<
> 触发调度：
> address：http://10.0.3.122:9998/
> code：500
> msg：xxl-rpc remoting error(connect timed out), for url : http://10.0.3.122:9998/run

**Comment by RongXiong2016** [comment]
同v2.2.0 执行器集群后出现，大批量调度失败，显示报错 
xxl-rpc remoting error(connect timed out), for url : http://172.22.220.39:9998/run

![image](https://user-images.githubusercontent.com/18466554/101140569-1b66c100-364e-11eb-805f-08f94ddf2cb0.png)

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
