### ISSUE TITLE
请问一下怎么动态添加任务

### ISSUE THREAD

**Issue by Poceer** [xuxueli/xxl-job#1664]
创建任务目前我所知，只有@xxlJob 创建一个Handler ，和 GULE 在线编辑代码。

我现在主要是想实现 BEAN 的重用性，现在的项目前台创建定时任务，并发送数据，用的是同一个方法，比如我用 数据 A 创建定时任务，我要写个 HANDLER， 我换个 数据B 创建另一个定时任务，还要写个 HANDLER ， 这是不可接受的，请问有什么方法可以实现这种需求

**Comment by LockiJiang** [comment]
如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发

**Comment by Poceer** [comment]
> 如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发

打个比方，同一个方法，使用不同数据，数据A 我要7点运行，数据B 要10点运行，这两个任务一起跑

可是任务列表里 JobHandler 不允许重名，我不是还要开发一个吗

**Comment by LockiJiang** [comment]
> 
> 
> > 如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发
> 
> 打个比方，同一个方法，使用不同数据，数据A 我要7点运行，数据B 要10点运行，这两个任务一起跑
> 
> 可是任务列表里 JobHandler 不允许重名，我不是还要开发一个吗

JobHandler 不允许重名你试过吗？
JobHandler 不允许重名指的是执行器开发的handler不能重名，多个任务使用同一个handler是可以的

你看我理解你的需求，这样做是不是对的
任务1，每天7点，handler A，参数A
任务2，每天10点，handler A，参数B
就是创建两个任务，使用同一个hanler，设置不同的cron和参数

**Comment by Poceer** [comment]
> > > 如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发
> > 
> > 
> > 打个比方，同一个方法，使用不同数据，数据A 我要7点运行，数据B 要10点运行，这两个任务一起跑
> > 可是任务列表里 JobHandler 不允许重名，我不是还要开发一个吗
> 
> JobHandler 不允许重名你试过吗？
> JobHandler 不允许重名指的是执行器开发的handler不能重名，多个任务使用同一个handler是可以的
> 
> 你看我理解你的需求，这样做是不是对的
> 任务1，每天7点，handler A，参数A
> 任务2，每天10点，handler A，参数B
> 就是创建两个任务，使用同一个hanler，设置不同的cron和参数

多谢，多个任务的确是可以使用一个handler 的，是我弄错了

**Comment by biqiufeng** [comment]
> > > > 如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发
> > > 
> > > 
> > > 打个比方，同一个方法，使用不同数据，数据A 我要7点运行，数据B 要10点运行，这两个任务一起跑
> > > 可是任务列表里 JobHandler 不允许重名，我不是还要开发一个吗
> > 
> > 
> > JobHandler 不允许重名你试过吗？
> > JobHandler 不允许重名指的是执行器开发的handler不能重名，多个任务使用同一个handler是可以的
> > 你看我理解你的需求，这样做是不是对的
> > 任务1，每天7点，handler A，参数A
> > 任务2，每天10点，handler A，参数B
> > 就是创建两个任务，使用同一个hanler，设置不同的cron和参数
> 
> 多谢，多个任务的确是可以使用一个handler 的，是我弄错了

你好。 我面临同样的问题。您这边最后怎么解决的。如何创建多个任务 用同一个hanler

**Comment by Ozymandias0818** [comment]
> > > 如果用的是同一个方法，数据A和数据B可以通过参数传递给HANDLER，不需要重新开发
> > 
> > 
> > 打个比方，同一个方法，使用不同数据，数据A 我要7点运行，数据B 要10点运行，这两个任务一起跑
> > 可是任务列表里 JobHandler 不允许重名，我不是还要开发一个吗
> 
> JobHandler 不允许重名你试过吗？ JobHandler 不允许重名指的是执行器开发的handler不能重名，多个任务使用同一个handler是可以的
> 
> 你看我理解你的需求，这样做是不是对的 任务1，每天7点，handler A，参数A 任务2，每天10点，handler A，参数B 就是创建两个任务，使用同一个hanler，设置不同的cron和参数

如果数据A 我要7点运行，数据B 也要7点运行，这两个任务可以一起被正常执行吗
