### ISSUE TITLE
xxl 任务卡死

### ISSUE THREAD

**Issue by nzshe** [xuxueli/xxl-job#1667]
### 版本
2.1.1-SNAPSHOT
### 问题
我们在生产上设置了一个JOB，每次1W多数据处理，任务会卡死，在日志哪里显示一直在跑，后面还有个终止任务的红色按钮。 要手动终止任务，然后再跑才行。 
我们设置了一个三点的JOB 和 四点的JOB，都是执行同一个代码。 这个是由于三点的JOB没有跑完，四点的JOB又开始跑导致的吗？  xxl 我记得是，如果上一次没有执行成功，下一次是不会执行的。 难道是分了两个JOB跑同一段代码导致的吗？

**Comment by wz-dazhi** [comment]
我也碰到同样的问题

**Comment by zslbb** [comment]
同一个任务的调度是这样的，但是不同任务的话应该是没有关系的。
你这个应该是任务的问题吧？加了分布式锁？或者是其他的锁导致的。

**Comment by Yuhjiang** [comment]
我也碰到类似的问题，定时三小时执行一次，根据前几天的执行状况，1小时就能执行完了，结果6月5日的时候，下午3点执行的任务一直在执行中，后续的任务也都显示在执行中（实际上并没有执行）。
![image](https://user-images.githubusercontent.com/28681745/84101254-1aa6f680-aa40-11ea-9434-7ba6292fbf58.png)

**Comment by 908028664** [comment]
我也有同样的问题，有的任务卡住了，我自己做了改造，执行失败重试三次还是失败的话，就及时钉钉告警，
 任务在执行器为什么会卡住，执行任务的线程处于什么状态？其中的原理是什么？
我还发下，自动重试3次都失败，手动执行一次 就成功了。
根据经验，应该是任务执行时，和数据库有关系，数据库扛不住，或是当时有锁，不能及时返回响应给执行器，执行器任务线程就卡死了。
上面的只是经验，特别想知道其中原理，作者可以讲讲吗？或是路过的各位谈谈。
谢谢！

**Comment by nzshe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。

**Comment by nzshe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
