### ISSUE TITLE
用docker搭建集群的话，每一个镜像都要单独配置执行器的iip地址不太方便

### ISSUE THREAD

**Issue by AlmondTao** [xuxueli/xxl-job#1668]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by herongyun** [comment]
请问不能跨ip通信的问题解决了吗？

**Comment by AlmondTao** [comment]
跨ip通讯和我说的这个问题好像不是一个问题。通信应该没什么问题吧？

**Comment by xuxueli** [comment]
@AlmondTao 你好，你的问题是执行器自动获取的IP并非外部可以访问的IP，所以需要单独指定吗？
针对这种情况，可借助 "spring-cloud-commons" 提供的 "InetUtils" 组件灵活定制注册IP段，执行器springboot示例conf类的注释里有提示。

**Comment by herongyun** [comment]
是的，因为调取机器和执行器分布在两台机器上，各自的ip是不能相互通信的。
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"许雪里"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月22日(星期五) 中午12:20
 收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
 抄送:&nbsp;"飚神"<247052163@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
 主题:&nbsp;Re: [xuxueli/xxl-job] 用docker搭建集群的话，每一个镜像都要单独配置执行器的iip地址不太方便 (#1668)

 

 

 
@AlmondTao 你好，你的问题是执行器自动获取的IP并非外部可以访问的IP，所以需要单独指定吗？
针对这种情况，可借助 "spring-cloud-commons" 提供的 "InetUtils" 组件灵活定制注册IP段，执行器springboot示例conf类的注释里有提示。

**Comment by herongyun** [comment]
@大佬，我使用的2.1.2的版本。一致性hash+单机串行，会出现重复执行的问题。看论坛里面说的是quartz，但是V2.1.2好像并没有用quartz,请问在xxl更高的版本中是否已经解决了这个问题？还是在以后的版本解决？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"许雪里"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 中午12:20
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"飚神"<247052163@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 用docker搭建集群的话，每一个镜像都要单独配置执行器的iip地址不太方便 (#1668)





 
@AlmondTao 你好，你的问题是执行器自动获取的IP并非外部可以访问的IP，所以需要单独指定吗？
 针对这种情况，可借助 "spring-cloud-commons" 提供的 "InetUtils" 组件灵活定制注册IP段，执行器springboot示例conf类的注释里有提示。

**Comment by AlmondTao** [comment]
@xuxueli 好的，谢谢
