### ISSUE TITLE
执行器自动注册能否支持多个?

### ISSUE THREAD

**Issue by Kang-shen** [xuxueli/xxl-job#1670]
目前使用的是2.1的版本。
根据业务需求，我需要根据不同调度需求创建多个执行器。微服务项目都是通过k8s部署的，容器内部的ip在每次部署后会重新分配，所以xxl-job-admin服务的ip不是固定的。现在采用的方式通过服务名去注册。
现在遇到的问题是有多个执行器，配置中心我们用的Nacos，这个配置xxl.job.executor.appname= xxl-job-executor。只会把执行器名称为xxl-job-executor的自动 注册上去，其他执行器没法自动注册。如下图：
![image](https://user-images.githubusercontent.com/18001320/81466406-1c448b00-9204-11ea-862e-c1b9b296eadd.png)
每次重新发布后，这个ip都会变，我们需要每次都手动去修改这个手动注册的地址。后续我们还会创建很多执行器，发布起来就会不太方便。
尝试着修改了一些源码，发现不太好实现。想问下这种情况，有其他什么方式实现吗？

**Comment by qiuqiuxiaobai** [comment]
我也遇到了，请问怎么解决的

**Comment by Kang-shen** [comment]
暂时还没解决，只能自动注册一个，剩下的手动改了。看看有没有大佬能告知怎么实现的，后面自己改代码了。

**Comment by qiuqiuxiaobai** [comment]
我知道了，请问一下你的是什么版本，我之前用的2.1.2一直是自从注册失败，改成2.1.1可以自动注册成功了，你可以试试

**Comment by Kang-shen** [comment]
我这边自动注册本来就可以成功。就是多个执行器的时候不能全部选自动注册。因为自动注册是根据执行器的AppName去找的，如果有多个执行器AppName不一样，就不能同时注册。我突然发现我可以把AppName改成一致，只是执行器名称不一样，也能满足我多个执行器自动注册的效果。

**Comment by Kang-shen** [comment]
这个问题已经解决了。我这个问题关了。谢谢讨论。

**Comment by taoguoliang** [comment]
> 我这边自动注册本来就可以成功。就是多个执行器的时候不能全部选自动注册。因为自动注册是根据执行器的AppName去找的，如果有多个执行器AppName不一样，就不能同时注册。我突然发现我可以把AppName改成一致，只是执行器名称不一样，也能满足我多个执行器自动注册的效果。

但是定时任务实际执行的时候，一个执行器对应多个服务怎么保证任务在对应的服务上执行
