### ISSUE TITLE
[功能]是否可以添加任务实例功能，方便任务的重跑恢复

### ISSUE THREAD

**Issue by ChunMengLu** [xuxueli/xxl-job#1672]
Please answer some questions before submitting your issue. Thanks!
首先，感谢作者和各位开发者，我提个需求。

### Which version of XXL-JOB do you using?
2.1.0

### Expected behavior
目前在大数据业务使用了 dolphinscheduler，dolphinscheduler 有个任务实例的概念（xxl-job省了这一环节）任务重跑和恢复特别方便，希望能引入。

### Other information

**Comment by xuxueli** [comment]
你好，XXLJOB提供了对应功能的，在 ”任务日志“ 界面，每一次调度都会生成一次调度日志，可以针对这个日志做处理。

**Comment by ChunMengLu** [comment]
> 你好，XXLJOB提供了对应功能的，在 ”任务日志“ 界面，每一次调度都会生成一次调度日志，可以针对这个日志做处理。

确实，稍微扩展一下就行了，感谢。
