### ISSUE TITLE
“appName” 调整为 “appname” 

### ISSUE THREAD

**Issue by parselife** [xuxueli/xxl-job#1676]
Please answer some questions before submitting your issue. Thanks!

### 升级版本

    注意：XxlJobSpringExecutor组件个别字段调整：“appName” 调整为 “appname” ，升级时该组件时需要注意；

想问下，这个修改是基于什么考虑的？有何影响么

**Comment by jlcon** [comment]
下载代码会有这个问题，但是直接从maven仓库引用2.2.0版本，还是appName

**Comment by xuxueli** [comment]
新版本已优化，建议升级。
