### ISSUE TITLE
出现预警发不出去的情况

### ISSUE THREAD

**Issue by ecmsglobal** [xuxueli/xxl-job#1677]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
预警及时发送出去
### Actual behavior
调度失败和执行失败的log，堆积在表中，无法发出。看起来像是发送的线程停了，但是日志里没有相关内容
### Steps to reproduce the behavior
重现有难度，事故现场已经不见了。就是想问问大家，看是否有类似情况出现。如果大家都没有，可能就是个偶发的概率性事件了。
### Other information

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
