### ISSUE TITLE
cronGen.js中有bug

### ISSUE THREAD

**Issue by wjllp** [xuxueli/xxl-job#1679]
使用cronGen修改cron表达式时，修改一处时会导致将整个cron表达式重置为* * * * * ?

例如，我当我编辑任务时，原先的表达式为2 12 0 * * ?，每天0点12分2秒执行，我想让第10秒的时候也执行一下，在秒的Tab中点击10之后，cron就变成了2,10 * * * * ?，这显然是不合理的，我改的是秒，时和分不应该被改变

原因在于cronGen.js的第1014行到1019行解析cron不对，应将此处改为如下：

$("#secondHidden").val(regs[0]);
$("#minHidden").val(regs[1]);
$("#hourHidden").val(regs[2]);
$("#dayHidden").val(regs[3]);
$("#monthHidden").val(regs[4]);
$("#weekHidden").val(regs[5]);

**Comment by xuxueli** [comment]
你好，欢迎直接PR。------------------ 原始邮件 ------------------
发件人: "jun-wang"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 下午4:52
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xuxueli/xxl-job] cronGen.js中有bug (#1679)




 
使用cronGen修改cron表达式时，修改一处时会导致将整个cron表达式重置为* * * * * ?，
 原因在于cronGen.js的第1014行到1019行解析cron不对，应将此处改为如下
 ("#minHidden").val(regs[1]);
 ("#dayHidden").val(regs[3]);
 ("#weekHidden").val(regs[5]);
 
&mdash;

**Comment by xuxueli** [comment]
你好，感谢反馈！
已合并至master分支，将会跟随下个版本一同发布。
