### ISSUE TITLE
操作按钮能否折叠部分或者配置式？

### ISSUE THREAD

**Issue by luoc101** [xuxueli/xxl-job#1681]
Please answer some questions before submitting your issue. Thanks!
表格行操作按钮能否折叠部分或者配置式？
常用按钮 不折叠到下列表，除了任务管理页面的按钮过多 其他页面的不用折叠
### Which version of XXL-JOB do you using?
2.2.0
### Other information

**Comment by xuxueli** [comment]
你好，可以将具体哪个页面，以及对应建议分别列出来啊，一起分析看下。

**Comment by luoc101** [comment]
> 你好，可以将具体哪个页面，以及对应建议分别列出来啊，一起分析看下。

执行器管理页面：
1. 只有 编辑和删除 两个按钮；建议不折叠按钮。
2. 看数据库里面有个排序字段，但页面没有输入框。建议保留排序字段
任务管理页面：
建议把 编辑，执行一次，查询日志按钮 不放入折叠

关于折叠按钮，不需要无意义的 操作 按钮

**Comment by xuxueli** [comment]
新版本已优化，建议升级。
