### ISSUE TITLE
单机情况，用docker拉取2.0.1版本镜像，任务全部都是重复执行两次

### ISSUE THREAD

**Issue by goAhead2013** [xuxueli/xxl-job#1684]
Please answer some questions before submitting your issue. Thanks!

使用的是2.0.1版本的镜像，发现全部任务都是重复成功执行两次，请问这个问题有什么解决方法呢？

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现操作步骤。

可以检查下调度中心与DB时钟是否一致，建议使用最新release版本  2.2.0。
