### ISSUE TITLE
建议添加定时自动清理日志功能

### ISSUE THREAD

**Issue by xingyongfeng** [xuxueli/xxl-job#169]
由于执行器下有很多任务，并且每个任务执行时间间隔很短，数据库就会产生大量日志  建议定时清理日志功能，比如自动清理7天前的日志

**Comment by xuxueli** [comment]
你好，感谢关注和建议！
考虑到任务日志中可能存在业务敏感数据，如若强制清除不太合适。
但是，会排期实现 “调度中心删除执行日志时，同步清理对应的执行器Log文件” 的功能，届时，可以通过调度中心来清理执行器下Log文件。

**Comment by xuxueli** [comment]
你好，最新release版本已经实现该功能，可以升级查看下哈！
