### ISSUE TITLE
exchange邮件服务器无法使用email警报

### ISSUE THREAD

**Issue by wekingc** [xuxueli/xxl-job#1690]
公司内部如果使用exchange服务器，email的验证是使用AD，不能使用密码验证，如果springs.mail取消验证需要spring.mail.username和spring.mail.password同时为空，但是发邮件地址是取spring.mail.username又无法为空，所以导致两难局面。
建议添加spring.mail.from属性，而com.xxl.job.admin.core.conf.XxlJobAdminConfig.java中的    @Value("${spring.mail.username}")
    private String emailUserName;
改为
    @Value("${spring.mail.from}")
    private String emailUserName;

**Comment by xuxueli** [comment]
你好，感谢反馈！
相关PR已经合并至master分支，将会跟随下个版本一同发布。
