### ISSUE TITLE
如何判断服务器已经到达性能瓶颈

### ISSUE THREAD

**Issue by ecmsglobal** [xuxueli/xxl-job#1695]
根据什么参数判断系统是否达到瓶颈呢？因为已经上生产环境了，不想等到出问题了，再来解决调度中心性能问题。

目前的环境：
AWS 2核心4G内存，SSD硬盘服务器
nginx + xxl-job*2 + mysql都在这一台服务器上
24个执行器，385个任务，调度频率在分钟级，就是基本上每隔一两分钟调度一次

目前系统资源情况：

    [root@ip-X ~]# free -m
                total       used       free     shared    buffers     cached
    Mem:          3952       3849        103          0        124       1824
    -/+ buffers/cache:       1899       2052
    Swap:            0          0          0

top命令结果中load为4左右，mysql的cpu在150%左右：

    top - 10:34:27 up 647 days, 20:52,  3 users,  load average: 3.65, 3.85, 3.88
    Tasks: 118 total,   2 running, 116 sleeping,   0 stopped,   0 zombieCpu(s): 20.4%us,  2.1%sy,  0.0%ni, 38.6%id,  1.7%wa,  0.0%hi,  0.2%si, 37.1%st
    Mem:   4047732k total,  3915396k used,   132336k free,   129520k buffersSwap:        0k total,        0k used,        0k free,  1840124k cached
    PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                             
    25441 mysql     20   0 1609m 615m    0 S 109.5 15.6  15082:42 mysqld                                                                                                                                               
    9753 root      20   0  153m 4836   12 S  0.7  0.1   2281:39 redis-server                                                                                                                                         
    19820 root      20   0 3668m 454m 3916 S  0.7 11.5  92:51.64 java                                                                                                                                                 
    19897 root      20   0 3644m 631m 6432 S  0.7 16.0  64:43.09 java               

iostat结果如下，xvdf是挂载的数据盘，mysql和应用都安装在这里面。

    [root@ip-X ~]# iostat
    Linux 4.9.76-3.78.amzn1.x86_64 (ip-X) 	05/19/2020 	_x86_64_	(2 CPU)

    avg-cpu:  %user   %nice %system %iowait  %steal   %idle
               9.28    0.00    0.76   10.17    4.74   75.06
    
    Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
    xvda              0.70        22.45         5.71 1256486897  319348856
    xvdf            177.41     30097.53       852.88 1684758159470 47741372064

**Comment by xuxueli** [comment]
你好，调度中心瓶颈在于调度线程是否充足，建议监控下 JobTriggerPoolHelper 中调度线程状态，如果长时间逼近最大线程，说明调度资源紧张，需要调大调度线程，或者增加调度集群节点
