### ISSUE TITLE
执行器jetty用户生成的callback日志，归属root用户组，导致执行器无法写入日志！

### ISSUE THREAD

**Issue by zqszzs** [xuxueli/xxl-job#1697]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-2.1.1

### Expected behavior
执行器可以正常写入callback日志
### Actual behavior
执行器写入callback日志，出现权限不够异常，原因jetty用户生成的callback日志归属root用户
### Other information
![企业微信截图_1589858739842](https://user-images.githubusercontent.com/38514696/82282584-c5d70980-99c6-11ea-894d-08a8d97c76e5.png)

**Comment by xuxueli** [comment]
需要给执行器进程对日志目录开放读写权限。
