### ISSUE TITLE
任务调度时出现了调度结果为失败，执行结果成功的情况

### ISSUE THREAD

**Issue by henianyou** [xuxueli/xxl-job#1699]
version 2.1.2
查看任务调度情况时出现了调度结果为失败，执行结果为成功的情况，查看日志表中trigger_code=500, handle_code=200, 并且trigger_msg的值是其它执行失败任务的handle_msg,是什么原因导致了日志记录混乱呢？

**Comment by xuxueli** [comment]
你好，问题无法复现。
请确认下是否存在二次定制开发问题，如果存在二次定制，需要自己排查下是不是定制逻辑导致的。
如果不存在定制，需要提供下问题稳定复现步骤。

**Comment by chenyulzhh** [comment]
我这里 V2.2.0 也遇到这样的了，似乎每天偶尔有几条这样的

调度备注如下

任务触发类型：Cron触发
调度机器：192.168.1.61
执行器-注册方式：自动注册
执行器-地址列表：[http://192.168.0.170:9998/, http://192.168.1.60:9998/]
路由策略：故障转移
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
心跳检测：
address：http://192.168.0.170:9998/
code：200
msg：null

触发调度：
address：http://192.168.0.170:9998/
code：500
msg：xxl-rpc remoting error(Read timed out), for url : http://192.168.0.170:9998/run




查看执行日志如下

2020-06-19 11:20:22 [com.xxl.job.core.thread.JobThread#run]-[124]-[Thread-2547] 
----------- xxl-job job execute start -----------
----------- Param: 。。。
。。。。。
。。。。
。。。。
2020-06-19 11:20:26 [com.xxl.job.core.thread.JobThread#run]-[164]-[Thread-2547] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=200, msg=null, content=null]
2020-06-19 11:20:26 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[191]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

[Load Log Finish]

**Comment by olicu** [comment]
version 2.1.2
任务触发类型：Cron触发
调度机器：172.19.0.5
执行器-注册方式：自动注册
执行器-地址列表：[10.197.32.51:20001]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：10.197.32.51:20001
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1593675263004, request:XxlRpcRequest{requestId='edb9b848-4888-48a1-ba3b-6a26bb5ca106', createMillisTime=1593675260003, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=7, executorHandler='stock-real', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=1390128, logDateTime=1593675260002, glueType='BEAN', glueSource='', glueUpdatetime=1563445187000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy106.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) 

也是有几率会出现这种问题
![图片](https://user-images.githubusercontent.com/26193513/86357737-defaf780-bca0-11ea-9e30-fe9eeedd25aa.png)

**Comment by henianyou** [comment]
经过排查闹了乌龙，是我们开发人员不注意修改了静态变量SUCCESS中的属性导致的问题，深感抱歉！

**Comment by muxinzi** [comment]
我这最近一直出现这个问题，调度失败但是执行成功

**Comment by yuxiao97** [comment]
问题版本是多少，我这边也有问题，版本号：2.1.0

**Comment by henianyou** [comment]
我这边问题解决了，是我自己的问题，不小心修改了常量ReturnT.SUCCESS中属性的值，导致结果串在一起了



***@***.***
 
发件人： yuxiao
发送时间： 2021-07-29 10:23
收件人： xuxueli/xxl-job
抄送： henianyou; State change
主题： Re: [xuxueli/xxl-job] 任务调度时出现了调度结果为失败，执行结果成功的情况 (#1699)
问题版本是多少，我这边也有问题，版本号：2.1.0

**Comment by yuxiao97** [comment]
> 我这边问题解决了，是我自己的问题，不小心修改了常量ReturnT.SUCCESS中属性的值，导致结果串在一起了 ***@***.*** 发件人： yuxiao 发送时间： 2021-07-29 10:23 收件人： xuxueli/xxl-job 抄送： henianyou; State change 主题： Re: [xuxueli/xxl-job] 任务调度时出现了调度结果为失败，执行结果成功的情况 (#1699) 问题版本是多少，我这边也有问题，版本号：2.1.0 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

看到好多人都有这个问题，如果是个人问题的话，说明这个结果容易让使用者误用。
