### ISSUE TITLE
tables_xxl_job.sql文件 XXL_JOB_QRTZ_TRIGGER_REGISTRY表的update_time类型错误

### ISSUE THREAD

**Issue by lucky-abel** [xuxueli/xxl-job#17]
XXL_JOB_QRTZ_TRIGGER_REGISTRY表的update_time 类型应该是timestamp

**Comment by xuxueli** [comment]
你好，目前使用的 “datetime”，业务支持的。

**Comment by lucky-abel** [comment]
嗯 昨天跑了一下你们的项目，db文件在数据库里执行有个表创建没成功 改了这个一段类型才通过了

发自我的 iPhone

**Comment by xuxueli** [comment]
你好，应该是你们DBA做了限制。
