### ISSUE TITLE
报错信息太长导致无法入库，一直打印错误日志，导致硬盘空间被沾满

### ISSUE THREAD

**Issue by kevin0016** [xuxueli/xxl-job#1700]
任务执行失败，报错信息太长，错误原因入库的时候超过限制长度，打印错误原因没有任何的限制，一直循环报错，错误日志一直打印，导致服务器硬盘空间被占满进而服务崩溃

**Comment by xuxueli** [comment]
你好，v2.2.0 版本针对这个问题做了处理，超长日志备注做了截断处理，可以升级体验下。

或者，可以在执行器任务里控制下任务备注长度。

**Comment by qhysjpw** [comment]
我也出现这个问题了，无限打印日志，磁盘撑爆，2.1.5版本
