### ISSUE TITLE
xxl-job是否缓存有线程状态

### ISSUE THREAD

**Issue by zzujustme** [xuxueli/xxl-job#1708]
version: 2.1.0

场景： 同一台服务器上如果存在其他java进程，其他进程将服务器线程耗尽；
问题：重启xxl-job，任务依然不能自动触发

猜测：xxl-job是否缓存有线程状态；xxl-job重启后，获取不到线程，其他服务释放线程后，依然获取不到线程

**Comment by xuxueli** [comment]
并没有对服务线程状态做处理。

任务触发通过调度中心的调度线程进行的，可以断点排查下调度线程是否异常。

**Comment by zzujustme** [comment]
大致看了下源码，没有缓存，启动时候会启动线程。

**Comment by zzujustme** [comment]
> 并没有对服务线程状态做处理。
> 
> 任务触发通过调度中心的调度线程进行的，可以断点排查下调度线程是否异常。

看了堆栈日志，schedulejob线程不存在。
