### ISSUE TITLE
官方文档官网 难道就不能迁移到国内来？还不如放github上呢，实在太卡了...

### ISSUE THREAD

**Issue by born198x** [xuxueli/xxl-job#1709]
官方文档官网 难道就不能迁移到国内来？还不如放github上呢，实在太卡了...  

大佬，抽个时间迁移下官网文档吧，国内打开太难受了..........

**Comment by xuxueli** [comment]
你好，官网就是基于github pages来做的，托管在github服务上的。
多刷新下啊
