### ISSUE TITLE
能否对shell分片支持更好一些

### ISSUE THREAD

**Issue by jianzhiunique** [xuxueli/xxl-job#171]
1. 由于公司是PHP栈，一般只用到shell类型的任务，感觉对shell的分片支持不太好，目前我是直接通过改代码实现的,能否更优雅的解决这个问题？
```
if(shardingVO.getTotal() > 1) {
    if(params == null) {
        params = new String[]{Integer.toString(shardingVO.getIndex()), Integer.toString(shardingVO.getTotal()), "sharding"};
        } else {
            List temp = Arrays.asList(params);
            temp.add(Integer.toString(shardingVO.getIndex()));
            temp.add(Integer.toString(shardingVO.getTotal()));
            temp.add("sharding");
            params = (String[])temp.toArray();
        }
}
```
2. 除了邮件之外，能否接入第三方如钉钉机器人来告警？

**Comment by xuxueli** [comment]
你好，感谢关注和建议。
1、目前Java类型任务，是通过 “线程局部变量/ThreadLocal” 来传递分片参数的，它是独立于方法入参之外的第二种参数传递形式。但是针对 “Shell、Python和Nodejs” 等脚本任务语言中，并没有了解到类似实现，所以暂时还没有好的解决方案，如果你有好的方案和建议，欢迎PR啊！！！
2、默认提供邮件失败告警，可扩展短信或钉钉机器人等方式告警，扩展代码位置为 "JobFailMonitorHelper.failAlarm"；

**Comment by xuxueli** [comment]
你好，最新release版本，脚本类型任务（包括 shell）已经原生支持获取分片参数，可以升级查看下哈！
