### ISSUE TITLE
### 关于ORACLE版本

### ISSUE THREAD

**Issue by AaronPiUC** [xuxueli/xxl-job#1713]
xxl老师你好，我刚接触，把db表和admin模块改成了oracle版本的，目前基本功能正常，想问下可以提交吗

**Comment by xuxueli** [comment]
你好，为保证稳定性，主分支暂时以mysql未知迭代。
oracle分支欢迎登记在分支版本汇总里，感兴趣的社区小伙伴可以进行参考：https://github.com/xuxueli/xxl-job/issues/154
