### ISSUE TITLE
日志表未加索引导致登录后跳转首页很慢

### ISSUE THREAD

**Issue by huifeidehuzi** [xuxueli/xxl-job#1720]
SELECT count(1)
		FROM XXL_JOB_QRTZ_TRIGGER_LOG AS t
		 WHERE  t.handle_code = 200;
登录成功后跳转首页会执行此sql统计调度成功的数量，handle_code未加索引，查询非常慢，导致跳转首页时间较长，建议后续版本建表sql带上add index语句

**Comment by xuxueli** [comment]
你好，这是早期版本，建议升级最新版本，对日志系统已经做了针对性优化，即使100W级别日志也不会性能受影响。

**Comment by huifeidehuzi** [comment]
收到 ，感谢！


| |
zhangjianfeng
|
|
邮箱：huifeidehuzi@163.com
|

Signature is customized by Netease Mail Master

在2020年05月28日 19:54，许雪里 写道：

Closed #1720.
