### ISSUE TITLE
开发环境下，IP经常有变化，注册中心中缓存的废弃连接没有销毁导致最终OOM

### ISSUE THREAD

**Issue by kongwu-** [xuxueli/xxl-job#1723]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
开发环境下，IP经常有变化，注册中心中缓存的废弃连接没有销毁导致最终OOM

使用的是默认的Netty_Http方式
![image](https://user-images.githubusercontent.com/7615848/83123481-8bc4e080-a107-11ea-96f4-8a5d1e99eb3f.png)
![image](https://user-images.githubusercontent.com/7615848/83123575-a9924580-a107-11ea-99c7-bb13aa917758.png)

**Comment by xuxueli** [comment]
你好，感谢反馈！
这个问题已经修复，可以升级到最新版本体验下。
