### ISSUE TITLE
httpJobHandler 针对POST请求 是怎么传参的？没找到官方解释

### ISSUE THREAD

**Issue by born198x** [xuxueli/xxl-job#1726]
用的最新版本的 但针对POST请求的传参不知道怎么传才能被正确解析？

**Comment by zhangjianfei** [comment]
这就是个bean类型 job，参考示例代码，你得自己实现

**Comment by zzh630** [comment]
通用的post实现肯定要有啊

**Comment by farmer-it-1024** [comment]
@born198x ：post方式的data中参数对象传json格式，不能换行，要连着写成一行。例如 ：
data:{ "name": "张三", "age": 25, "isStudent": true }
