### ISSUE TITLE
请问下，什么时候使用jpa支持多种数据库啊

### ISSUE THREAD

**Issue by ljwps** [xuxueli/xxl-job#1730]
项目6月7号要上线，由于是XX项目不给用mysql，所以问下大佬什么时候用jpa，如果7号之前不会发布，那我就自己改了

**Comment by LockiJiang** [comment]
那你自己改吧，7号之前肯定不会

**Comment by 15051863961** [comment]
> 项目6月7号要上线，由于是XX项目不给用mysql，所以问下大佬什么时候用jpa，如果7号之前不会发布，那我就自己改了

大兄弟，你改好了没，我的也是要oracle，改好了，来一份啊

**Comment by ljwps** [comment]
> > 项目6月7号要上线，由于是XX项目不给用mysql，所以问下大佬什么时候用jpa，如果7号之前不会发布，那我就自己改了
> 
> 大兄弟，你改好了没，我的也是要oracle，改好了，来一份啊

没有呢，我要把xxl-job的代码搬到公司的开发框架上，然后再改，而且适应多数据库是公司自己封装的类似jpa的一套东西，还不通用。现在代码搬上来了 运行一直GG，头秃中。。。

**Comment by 15051863961** [comment]
好吧，我是先用docker跑的mysql，中转一下。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ljwps"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午9:34
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"Thinking"<201840026@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 请问下，什么时候使用jpa支持多种数据库啊 (#1730)





   
项目6月7号要上线，由于是XX项目不给用mysql，所以问下大佬什么时候用jpa，如果7号之前不会发布，那我就自己改了
  
大兄弟，你改好了没，我的也是要oracle，改好了，来一份啊
  
没有呢，我要把xxl-job的代码搬到公司的开发框架上，然后再改，而且适应多数据库是公司自己封装的类似jpa的一套东西，还不通用。现在代码搬上来了 运行一直GG，头秃中。。。
