### ISSUE TITLE
目标网站存在form表单自动enable漏洞

### ISSUE THREAD

**Issue by vampniklaus** [xuxueli/xxl-job#1734]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Other information
zabbix监测到xxl-job-amdin中的风险
REQUEST:
GET /xxl-job-admin/jobinfo 
Referer: http://192.168.0.123:8021/xxl-job-admin/joblog 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 
Cookie: xxljob_adminlte_settings=on; XXL_JOB_LOGIN_IDENTITY=7b226964223a312c22757365726e616d65223a2261646d696e222c2270617373776f7264223a226531306164633339343962613539616262653536653035376632306638383365222c22726f6c65223a312c227065726d697373696f6e223a6e756c6c7d; m=2258:YWRtaW46YWRtaW4%253D 
Host: 192.168.0.123:8021 

RESPOND:
HTTP/1.1 200 
X-Application-Context: application:8021 
Content-Type: text/html;charset=UTF-8 
Content-Language: zh-CN 
Transfer-Encoding: chunked 
Date: Sun, 31 May 2020 01:22:42 GMT
![image](https://user-images.githubusercontent.com/24869042/83393488-71ea0d00-a429-11ea-8f16-7f83763b002d.png)

**Comment by xuxueli** [comment]
感谢反馈！
问题已修复并推送master分支，将会跟随下个版本一同发布。
