### ISSUE TITLE
2.1.0版本执行器异常返回fail无法触发邮件告警

### ISSUE THREAD

**Issue by LAINGXIANSHENG** [xuxueli/xxl-job#1741]
![image](https://user-images.githubusercontent.com/64855410/83476541-9b577700-a4c3-11ea-8e14-f2800928e5bc.png)
![image](https://user-images.githubusercontent.com/64855410/83476578-a4e0df00-a4c3-11ea-9925-70a61dc42351.png)

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
