### ISSUE TITLE
2.2.0日志报错

### ISSUE THREAD

**Issue by zhangyenull** [xuxueli/xxl-job#1743]
[ERROR] - com.xxl.job.core.thread.JobLogFileCleanThread$1.run(JobLogFileCleanThread.java:71) - Unparseable date: "apollo-crm" 
看了源码是路径解析问题吗

**Comment by zhangjianfei** [comment]
JobLogFileCleanThread扫描的是自定义路径下的日志文件，包文件名定义为日期格式，看你这个错误是因为apollo定义的日志路径也存在这个路径下，解析文件名的时候不是日期格式报错了，不要使用同一个路径就可以了

**Comment by xuxueli** [comment]
@zhangjianfei  +1，执行器日志路径保持独立即可。
