### ISSUE TITLE
根本不能用啊，刚下载的源码，运行起来显示注册成功，注册中心的页面上也不显示执行器。QQ群也不让加。都没地方问问题。

### ISSUE THREAD

**Issue by fslover** [xuxueli/xxl-job#1763]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by mylyed** [comment]
执行器需要自己手动添加，懂？

**Comment by yangshuaidlut** [comment]
这玩意就是自己的一个bug，就别争了。。。而且我个人认为你这个执行器在微服务级别也应该是自声明自申请自注册的，不应该还得让运维的人去搞一把，难道微服务几十个还得让运维一个个的追加么？

**Comment by xuxueli** [comment]
执行器和任务都需要预先添加，xxl-job是中心式设计，配置类信息调度中心统一维护，执行器只纯粹提供任务运行能力即可。

注册有短暂延迟，稍等下。

QQ群已经有近万人，前面群基本已满，可以加 5 群。

**Comment by fslover** [comment]
好的。理解。
