### ISSUE TITLE
admin端不支持高可用啊

### ISSUE THREAD

**Issue by mylyed** [xuxueli/xxl-job#1765]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.1-SNAPSHOT
### Expected behavior
admin端服务器挂掉会 在时间轮ringData需要执行的任务会由其他admin端会从新分配任务
### Actual behavior
admin端挂了不会让其他admin端重新分配任务
### Steps to reproduce the behavior
在JobScheduleHelper 预读了任务后kill进程。预读的任务就错过一次执行的机会。
### Other information
我认为这里是xxl-job的一个缺陷。

解决方法：引入协调服务中间件。😏

(为保证系统”轻量级”并且降低学习部署成本，没有采用Zookeeper作为注册中心，采用DB方式进行任务注册发现；) 这句话我看到了。权衡吧。。

**Comment by solosky** [comment]
还是老老实实部署之前基于quartz版本吧，老版本支持高可用。不建议升级。
