### ISSUE TITLE
运行一段时间后出现MySQLNonTransientConnectionException异常

### ISSUE THREAD

**Issue by gaoqiaoxiu** [xuxueli/xxl-job#1773]
XXL-JOB部署一段时间后，会出现com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown 异常，导致任务无法执行，调优了数据库连接还是会出现该异常

**Comment by gaoqiaoxiu** [comment]
XXL-JOB部署一段时间后，会出现com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown 异常，导致任务无法执行，调优了数据库连接还是会出现该异常

**Comment by xiaoshengaimm** [comment]
遇到同样问题。你用的是什么版本？Mysql-Connector是什么版本的？怀疑是mysql connector版本过低导致，我目前用的版本，mysql-connector是5.1.47.

**Comment by leo-shenliang** [comment]
遇到同样问题
