### ISSUE TITLE
【潜在bug】关于失败邮件监控线程

### ISSUE THREAD

**Issue by Baivin** [xuxueli/xxl-job#178]
XxlJobTrigger.trigger 方法 最后的步骤
        XxlJobDynamicScheduler.xxlJobLogDao.updateTriggerInfo(jobLog);
        JobFailMonitorHelper.monitor(jobLog.getId());
先update log 更新 triggerCode 和 handleCode，然后放入邮件监控队列，这里存在问题，当数据库写的慢，邮件监控队列由于是读取数据库的log做判断，获取的 triggerCode 和 handleCode 可能都是 0，因为数据库没写完，而邮件监控代码判断情形不全
ReturnT.SUCCESS_CODE==log.getTriggerCode() && log.getHandleCode()==0
没有考虑两者都为0的情况，这种情况就会出现没有发送邮件的问题（我服务器出现这种情况了）。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈啊！
该问题已经修复并且推送master分支，将会跟随下个版本一起发布。
