### ISSUE TITLE
建议新增加任务选择【BEAN模式】时能够带出该执行器上的【JobHandler】名字 

### ISSUE THREAD

**Issue by hopeful** [xuxueli/xxl-job#179]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0-SNAPSHOT
### Other information

调度中心，【新增加任务】->选择【执行器】，选择【BEAN模式】，不知道能否带出【JobHandler】的Bean注解name，由现在的手动输入方式改为选择方式，这样即方便又减少用户输入错误的可能性

**Comment by xuxueli** [comment]
你好，感谢关注和建议啊！
该建议已经加入TODO，后续将会排期跟进。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/230
