### ISSUE TITLE
看此文解决: 项目启动异常、注册器成功调度异常、执行异常、执行失败(ip/run)、NullPointException、c.x.job.core.executor.XxlJobExecutor - null

### ISSUE THREAD

**Issue by wolfmanwoking** [xuxueli/xxl-job#1799]
/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=56016:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/macbookpro/Desktop/0_java/cloud_server_xxl_job_run_0628/xxl-job-executor-samples/target/classes:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.2.2.RELEASE/spring-boot-starter-web-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter/2.2.2.RELEASE/spring-boot-starter-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot/2.2.2.RELEASE/spring-boot-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.2.RELEASE/spring-boot-autoconfigure-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.2.2.RELEASE/spring-boot-starter-logging-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/macbookpro/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/macbookpro/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.12.1/log4j-to-slf4j-2.12.1.jar:/Users/macbookpro/.m2/repository/org/apache/logging/log4j/log4j-api/2.12.1/log4j-api-2.12.1.jar:/Users/macbookpro/.m2/repository/org/slf4j/jul-to-slf4j/1.7.29/jul-to-slf4j-1.7.29.jar:/Users/macbookpro/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/macbookpro/.m2/repository/org/yaml/snakeyaml/1.25/snakeyaml-1.25.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.2.2.RELEASE/spring-boot-starter-json-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.1/jackson-databind-2.10.1.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.1/jackson-annotations-2.10.1.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.1/jackson-core-2.10.1.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.1/jackson-datatype-jdk8-2.10.1.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.10.1/jackson-datatype-jsr310-2.10.1.jar:/Users/macbookpro/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.10.1/jackson-module-parameter-names-2.10.1.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.2.2.RELEASE/spring-boot-starter-validation-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.1/jakarta.validation-api-2.0.1.jar:/Users/macbookpro/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.18.Final/hibernate-validator-6.0.18.Final.jar:/Users/macbookpro/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar:/Users/macbookpro/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-web/5.2.2.RELEASE/spring-web-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-beans/5.2.2.RELEASE/spring-beans-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-webmvc/5.2.2.RELEASE/spring-webmvc-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-aop/5.2.2.RELEASE/spring-aop-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-context/5.2.2.RELEASE/spring-context-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-expression/5.2.2.RELEASE/spring-expression-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-core/5.2.2.RELEASE/spring-core-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/spring-jcl/5.2.2.RELEASE/spring-jcl-5.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/com/xuxueli/xxl-job-core/2.2.0/xxl-job-core-2.2.0.jar:/Users/macbookpro/.m2/repository/io/netty/netty-all/4.1.43.Final/netty-all-4.1.43.Final.jar:/Users/macbookpro/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/Users/macbookpro/.m2/repository/org/codehaus/groovy/groovy/2.5.8/groovy-2.5.8.jar:/Users/macbookpro/.m2/repository/org/slf4j/slf4j-api/1.7.29/slf4j-api-1.7.29.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/2.2.2.RELEASE/spring-boot-configuration-processor-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/com/github/ulisesbocchio/jasypt-spring-boot-starter/2.1.1/jasypt-spring-boot-starter-2.1.1.jar:/Users/macbookpro/.m2/repository/com/github/ulisesbocchio/jasypt-spring-boot/2.1.1/jasypt-spring-boot-2.1.1.jar:/Users/macbookpro/.m2/repository/com/melloware/jasypt/1.9.4/jasypt-1.9.4.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.2.2.RELEASE/spring-boot-starter-actuator-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.2.2.RELEASE/spring-boot-actuator-autoconfigure-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/org/springframework/boot/spring-boot-actuator/2.2.2.RELEASE/spring-boot-actuator-2.2.2.RELEASE.jar:/Users/macbookpro/.m2/repository/io/micrometer/micrometer-core/1.3.1/micrometer-core-1.3.1.jar:/Users/macbookpro/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.11/HdrHistogram-2.1.11.jar:/Users/macbookpro/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/macbookpro/.m2/repository/de/codecentric/spring-boot-admin-starter-client/2.2.1/spring-boot-admin-starter-client-2.2.1.jar:/Users/macbookpro/.m2/repository/de/codecentric/spring-boot-admin-client/2.2.1/spring-boot-admin-client-2.2.1.jar:/Users/macbookpro/.m2/repository/org/jolokia/jolokia-core/1.6.2/jolokia-core-1.6.2.jar:/Users/macbookpro/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/Users/macbookpro/.m2/repository/org/projectlombok/lombok/1.18.10/lombok-1.18.10.jar com.xxl.job.executor.XxlJobExecutorApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.2.RELEASE)

22:41:43.793 logback [main] INFO  c.x.j.e.XxlJobExecutorApplication - Starting XxlJobExecutorApplication on chinaunicom.local with PID 5605 (/Users/macbookpro/Desktop/0_java/cloud_server_xxl_job_run_0628/xxl-job-executor-samples/target/classes started by macbookpro in /Users/macbookpro/Desktop/0_java/cloud_server_xxl_job_run_0628)
22:41:43.796 logback [main] INFO  c.x.j.e.XxlJobExecutorApplication - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/macbookpro/.m2/repository/org/codehaus/groovy/groovy/2.5.8/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22:41:44.683 logback [main] INFO  c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor - Post-processing PropertySource instances
22:41:44.734 logback [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
22:41:44.735 logback [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
22:41:44.736 logback [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
22:41:44.736 logback [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
22:41:44.736 logback [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource applicationConfig: [classpath:/application.properties] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
22:41:44.773 logback [main] INFO  c.u.j.f.DefaultLazyPropertyFilter - Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
22:41:44.786 logback [main] INFO  c.u.j.r.DefaultLazyPropertyResolver - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
22:41:44.787 logback [main] INFO  c.u.j.d.DefaultLazyPropertyDetector - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
22:41:44.795 logback [main] INFO  c.x.j.e.core.config.XxlJobConfig - >>>>>>>>>>> xxl-job config init.
22:41:45.091 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:demoJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@1f67761b[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#demoJobHandler]
22:41:45.091 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:shardingJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@5a034157[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#shardingJobHandler]
22:41:45.091 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:commandJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@2f4ba1ae[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#commandJobHandler]
22:41:45.092 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:httpJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@1391af3b[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#httpJobHandler]
22:41:45.092 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:demoJobHandler2, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@3762c4fc[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#demoJobHandler2]
22:41:45.103 logback [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
22:41:45.259 logback [main] INFO  c.x.j.e.XxlJobExecutorApplication - Started XxlJobExecutorApplication in 1.751 seconds (JVM running for 2.726)
22:41:45.262 logback [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
22:41:45.266 logback [SpringContextShutdownHook] ERROR c.x.job.core.executor.XxlJobExecutor - null
java.lang.NullPointerException: null
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
	at com.xxl.job.core.server.EmbedServer.stopRegistry(EmbedServer.java:262)
	at com.xxl.job.core.server.EmbedServer.stop(EmbedServer.java:124)
	at com.xxl.job.core.executor.XxlJobExecutor.stopEmbedServer(XxlJobExecutor.java:158)
	at com.xxl.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:85)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:55)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
22:41:45.267 logback [xxl-job, executor JobLogFileCleanThread] INFO  c.x.j.c.thread.JobLogFileCleanThread - >>>>>>>>>>> xxl-job, executor JobLogFileCleanThread thread destory.
22:41:45.267 logback [xxl-job, executor TriggerCallbackThread] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor callback thread destory.
22:41:45.268 logback [Thread-3] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor retry callback thread destory.

Process finished with exit code 0

**Comment by wolfmanwoking** [comment]
22:41:45.092 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:httpJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@1391af3b[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#httpJobHandler]
22:41:45.092 logback [main] INFO  c.x.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:demoJobHandler2, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@3762c4fc[class com.xxl.job.executor.service.jobhandler.SampleXxlJob#demoJobHandler2]
22:41:45.103 logback [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
22:41:45.259 logback [main] INFO  c.x.j.e.XxlJobExecutorApplication - Started XxlJobExecutorApplication in 1.751 seconds (JVM running for 2.726)
22:41:45.262 logback [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
22:41:45.266 logback [SpringContextShutdownHook] ERROR c.x.job.core.executor.XxlJobExecutor - null
java.lang.NullPointerException: null
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
	at com.xxl.job.core.server.EmbedServer.stopRegistry(EmbedServer.java:262)
	at com.xxl.job.core.server.EmbedServer.stop(EmbedServer.java:124)
	at com.xxl.job.core.executor.XxlJobExecutor.stopEmbedServer(XxlJobExecutor.java:158)
	at com.xxl.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:85)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:55)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
22:41:45.267 logback [xxl-job, executor JobLogFileCleanThread] INFO  c.x.j.c.thread.JobLogFileCleanThread - >>>>>>>>>>> xxl-job, executor JobLogFileCleanThread thread destory.
22:41:45.267 logback [xxl-job, executor TriggerCallbackThread] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor callback thread destory.
22:41:45.268 logback [Thread-3] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor retry callback thread destory.

Process finished with exit code 0




您好，我遇到的这个问题，在我自己的项目里，以modules 方式引入 xxl-job-executor-samples 项目 。接着将  xxl-job-executor-samples 的pom文件里的 parent 值修改为 我自己的项目值。运行后报以上的错误。

**Comment by wolfmanwoking** [comment]
猜测联调方式:
1、建议使用最新版本的xxl-job。
2、job-admin 和 job-server 可分开部署（部署前 先检查其服务所在环境能否相互访问其双方服务和端口）。
3、在遇到问题时，先检查服务器部署后的jar包（不要怀疑xxl-job有bug，很大可能是jar引入的问题），有助于提高问题解决的效率。
4、实在没招的情况下，把git网站的代码下载后，进行拆解，在本地电脑上测试成功后，单独并各自部署在服务器上。
5、如果是docker、k8s等集成部署则一定要检查服务器和端口是否能访问。

**Comment by wolfmanwoking** [comment]
项目急着上线，怕领导怪罪。只能深夜临时补救了。只能采用将xxl-job-core源码，融入到自己项目的方案里。以便及时调整好项目。由于时间紧迫，xxl-job-core源码里的一些小细节，还没有时间花心思查看。只有在此跪求楼主查看并处理相关逻辑。
我目前面临的问题是
1、采用@XxlJob注入时，在 XxlJobSpringExecuter 类117行， initJobHandlerMethodRepository 方法里 执行 if (loadJobHandler(name) != null)  时，发现 该name已经注册了，为啥要丢一个 RuntimeException 的错误出来？不让其再次注册，他不香吗？这导致的结果是 项目启动不起来。

**Comment by xuxueli** [comment]
你好，感谢反馈！

- 问题1：java.lang.NullPointerException: null at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
  - 原因：执行器没有正常启动导致，正常情况下不会发生；


- 问题2：initializeAuthenticationProviderBeanManagerConfigurer 报错 Address already in use
  - 原因：推测，当前项目被初始化了两次，导致重复初始化bean，重复占用端口号；


- 问题3：n("xxl-job jobhandler[" + name + "] naming conflicts.");
  - 原因：和上个问题一样，推测当前项目被初始化了两次，导致重复初始化bean，重复占用端口号；


建议排查一下当前项目，是不是存在重复初始化的问题。解决该问题，其他问题应该可以一并修复掉。
