### ISSUE TITLE
任务无缘无故停掉了

### ISSUE THREAD

**Issue by chenxofhit** [xuxueli/xxl-job#180]
线上定时任务无缘无故停掉了其它任务不受影响, 症状同 [https://github.com/xuxueli/xxl-job/issues/101 ](url) 类似, 请作者稍微关注下,谢谢为开源社区做的贡献.

**Comment by xuxueli** [comment]
你好，感谢反馈！
这个问题可能由以下几个原因导致：
1、执行器任务阻塞：后续任务需要等待前面的任务执行器结束才开始执行。
2、执行器执行结果回调失败：检查执行器回调Log是否抛异常，执行器回调地址是否正确。
