### ISSUE TITLE
修改密码无法弹出密码修改的弹窗

### ISSUE THREAD

**Issue by githubwyj** [xuxueli/xxl-job#1803]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Steps to reproduce the behavior
登陆之后，点击右上角用户名，然后点击“修改”密码 无任何反应
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈，问题无法复现。需要进一步提供复现步骤。
可以强刷一下浏览器缓存重试下，建议使用chrome浏览器。
