### ISSUE TITLE
任务调度异常，无法正常触发

### ISSUE THREAD

**Issue by wangpan3** [xuxueli/xxl-job#1805]
2.1.2版本，任务运行一段时间后就变成每秒触发一次
![Snipaste_2020-07-07_16-48-53](https://user-images.githubusercontent.com/16097912/86752234-cc523b00-c071-11ea-9e24-a2d4ac1fe687.png)

![Snipaste_2020-07-07_16-46-22](https://user-images.githubusercontent.com/16097912/86751716-6fef1b80-c071-11ea-81e2-53522f54754e.png)

**Comment by wangpan3** [comment]
配置的是10分钟触发一次，但是运行一段时间后就变成一秒次了

**Comment by LockiJiang** [comment]
> 
> 
> 配置的是10分钟触发一次，但是运行一段时间后就变成一秒次了

*就表示每秒，你配置的就是每隔10分钟，每秒执行一次

**Comment by wangpan3** [comment]
对的，多谢！
