### ISSUE TITLE
@XxlJob 无法扩展组合注解

### ISSUE THREAD

**Issue by geckhan** [xuxueli/xxl-job#1807]
我们系统有region概念，每次跑指定几个region的数据。想扩展@xxljob做组合注解，因为@Target({ElementType.METHOD}) 限定没法实现。

**Comment by xuxueli** [comment]
你好，你这边有建议吗？欢迎在这里提出讨论啊。

或者，也可以借助执行器的任务扫描注册机制自行扩展注册，如下类路径代码：
```
com.xuxueli.executor.sample.frameless.config.FrameLessXxlJobConfig#initXxlJobExecutor
```

**Comment by geckhan** [comment]
收到
