### ISSUE TITLE
v1.7.2 版本某个任务执行了2次，但有时正常执行1次

### ISSUE THREAD

**Issue by ArronZhu** [xuxueli/xxl-job#182]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v1.7.2
### Expected behavior
任务执行1次
### Actual behavior
任务执行2次
### Steps to reproduce the behavior
![qq 20171010113135](https://user-images.githubusercontent.com/9994871/31368187-b3cbe492-adae-11e7-9589-db9afe798af6.png)
![qq 20171010113159](https://user-images.githubusercontent.com/9994871/31368188-b404f098-adae-11e7-891b-5aaf73bc7cc2.png)

### Other information
这个任务是每天早上6:40执行，执行时判断其他job是否完成，没完成10分钟轮询直到等待3个小时。

**Comment by xuxueli** [comment]
你好，感谢反馈！
任务重复触发可能由以下几个原因：
1、路由策略选择 “分片广播”；
2、调度中心集群部署，集群机器时间不一致。
3、小概率情况下，quartz会重复触发，见quartz的issue （https://github.com/quartz-scheduler/quartz/issues/29  ）。

**Comment by ArronZhu** [comment]
我这边目前通过调整 阻塞处理策略 为“丢弃后续调度”，暂时正常了。
