### ISSUE TITLE
运行报表成功、失败和进行中都是0

### ISSUE THREAD

**Issue by tiaoxixiaoji** [xuxueli/xxl-job#1823]
![微信截图_20200714170956](https://user-images.githubusercontent.com/22673487/87407546-e43b3900-c5f4-11ea-9504-d2abe8d07ed4.png)
第一步先从db中group得到结果，赋值给Map对象
Map<String, Object> triggerCountMap = XxlJobAdminConfig.getAdminConfig().getXxlJobLogDao().findLogReport(todayFrom, todayTo);
第二步解析Map对象
int triggerDayCount = triggerCountMap.containsKey("triggerDayCount")?Integer.valueOf(String.valueOf(triggerCountMap.get("triggerDayCount"))):0;
                                int triggerDayCountRunning = triggerCountMap.containsKey("triggerDayCountRunning")?Integer.valueOf(String.valueOf(triggerCountMap.get("triggerDayCountRunning"))):0;
                                int triggerDayCountSuc = triggerCountMap.containsKey("triggerDayCountSuc")?Integer.valueOf(String.valueOf(triggerCountMap.get("triggerDayCountSuc"))):0;
                                int triggerDayCountFail = triggerDayCount - triggerDayCountRunning - triggerDayCountSuc;

在第二步里用的key都是驼峰式的，但是map里的key都是大写的，导致解析到的值都是0

**Comment by Seayon** [comment]
你数据库字段里面是不是大写

**Comment by tiaoxixiaoji** [comment]
对哦，oracle默认大写，不好意思

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
