### ISSUE TITLE
被触发的任务，不需要定时再触发一次

### ISSUE THREAD

**Issue by blue20080** [xuxueli/xxl-job#184]
父任务执行成功后，会触发子任务。
但子任务自身也有定时，导致的问题是，子任务会被执行两次。
临时解决方案是，修改子任务定时时间，为当月的前面日期。但每月都得手动改一次。

有没有好的解决方法？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
子任务可以暂停掉，暂停状态的任务，是不会触发任务执行的。
