### ISSUE TITLE
xxljob 自动注册，找到的客户端ip地址不对

### ISSUE THREAD

**Issue by Concentrate** [xuxueli/xxl-job#1845]
如果主机上面有docker0 的地址，自动注册直接就是docker0的地址了，而不是eth0的地址。
这个是错误的。查找客户端的eth0地址不正确。 看起来就是找到 客户端ip(ifconfig）的第一个地址，应该检测成eth0的地址。

**Comment by xuxueli** [comment]
你好，执行器测支持指定注册IP，以及注册的IP端，可以参考sample示例。
