### ISSUE TITLE
xxl-job系统启动时报错

### ISSUE THREAD

**Issue by YinHjie** [xuxueli/xxl-job#1849]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
系统启动时xxl-job不报错，虽然不影响，但是报错看着总是不爽
### Actual behavior
系统启动时xxl-job报空指针错误，
2020-07-24 09:42:44.585 ERROR 18068 --- [           main] c.x.j.c.e.impl.XxlJobSpringExecutor      : xxl-job method-jobhandler resolve error for bean[exposeProducer].
exposeProducer 这个bean在什么地方用的，debug时没有加载进来
### Other information

**Comment by luckyJonh** [comment]
看起来是xxl-job在遍历bean寻找@xxl-job注解的method时出现的异常，极有可能是你自己注册的bean哦，建议把从异常堆栈信息寻找原因

**Comment by YinHjie** [comment]
应该不是我自己注册bean的问题，我们有很多个系统接入xxl-job启动都会有这个问题。

**Comment by xuxueli** [comment]
@luckyJonh  +1，这是执行器在扫描当前项目 bean 的时候报的错，建议debug 该 bean[exposeProducer] 的类路径，确认归属。
