### ISSUE TITLE
V2.2.0问题有点多啊 

### ISSUE THREAD

**Issue by codersw** [xuxueli/xxl-job#1861]
总报错 msg：xxl-rpc remoting error(no protocol: xxxxx/run), for url : xxxx/run
然后客户端注册后也不会自动刷新
找到问题原因了，在微服务下会出现这样的问题各位帮忙看看如何解决
![1595994196(1)](https://user-images.githubusercontent.com/31917349/88754225-b7f4f000-d190-11ea-8906-8336ce11c46c.jpg)
![1595994228(1)](https://user-images.githubusercontent.com/31917349/88754256-ce9b4700-d190-11ea-95ef-f9ad51b98327.jpg)
调度机器ip会变成相同注册中心下的内网ip上面

**Comment by xuxueli** [comment]
你好，从日志 ”……no protocol……”关键字来看，应该是执行器注册地址非法导致，应该包含http协议头。检查一下执行器和调度中心版本是否一致。

机器ip是从网卡上获取的第一个合法ip，调度中心ip只是记录使用，没有明确含义。执行器ip用于通讯，如果多网卡可以手动指定。

机器ip根本解决方案是优化机器王卡配置，尽量不要存在多个。

**Comment by bzlrj** [comment]
单次执行一次任务没问题，启动任务后5秒执行一次就会出现xxl-rpc remoting error(connect timed out

**Comment by codersw** [comment]
> 你好，从日志“……没有协议……”关键字来看，应该是执行器注册地址非法导致，应该包含http协议头。检查一下执行器和调度中心版本是否一致。
> 
> 机器ip是从网卡上获取的第一个合法ip，调度中心ip只是记录使用，没有明确含义。执行器ip用于通讯，如果多网卡可以手动指定。
> 
> 机器ip根本解决方案是优化机器王卡配置，尽量不要存在多个。

谢谢作者解答 已经好用了  docker启动的时候需要指定下ip就好了
