### ISSUE TITLE
日志接口参数类型不匹配

### ISSUE THREAD

**Issue by henianyou** [xuxueli/xxl-job#1869]
### 描述：xxl_job_log表的id值超过int范围后查询执行日志(或终止任务)时报错
`There was an unexpected error (type=Bad Request, status=400).Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "xxxxxxxxxxxxxx"`
### BUG复现：
1、修改xxl_job_log表id字段的自增初始值（超过int范围即可），例如：1596171426000
2、执行任务，查看调度日志->操作->执行日志（或终止任务）

### 原因：
查看源码发现JobLogController类有两个方法接收Id时使用的是int类型，而数据库中log id定义的是bitint类型，且对应实体类也使用的是long类型，所以导致调用时如果传参为long类型的大数值会导致参数解析出错。
`	@RequestMapping("/logDetailPage")
	public String logDetailPage(int id, Model model){`
`@RequestMapping("/logKill")
	@ResponseBody
	public ReturnT<String> logKill(int id){`

该问题出现概率极低，只是我做表迁移时无意中改变了自增初始值导致该问题出现，仅供参考。

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
