### ISSUE TITLE
怎么能在本次任务中获取上次成功执行的时间

### ISSUE THREAD

**Issue by f00lish** [xuxueli/xxl-job#1872]
有些任务想要根据上次执行时间来判断如何下一步，怎么获取呢？

### Which version of XXL-JOB do you using?
2.2.0

**Comment by xzionx** [comment]
如果是2.2 版本或者以上
数据库job_info里有列 TriggerLastTime  记录上次触发时间
job_log里 handle_time  记录执行时间

**Comment by f00lish** [comment]
> 如果是2.2 版本或者以上
> 数据库job_info里有列 TriggerLastTime 记录上次触发时间
> job_log里 handle_time 记录执行时间

表是记录了  那框架里有直接获取的方法么

**Comment by xzionx** [comment]
好像没有  我做的时候是自己读的库 。

**Comment by f00lish** [comment]
> 好像没有 我做的时候是自己读的库 。

好吧～

**Comment by xuxueli** [comment]
该功能评估缺少通用型，建议定制实现。
