### ISSUE TITLE
调度中心怎么提升调度能力（集群只能提升高可用，最终调度还是只能一台机调度）？

### ISSUE THREAD

**Issue by wenhsh** [xuxueli/xxl-job#1875]
调度中心怎么提升调度能力（集群只能提升高可用，最终调度还是只能一台机调度）？

### Which version of XXL-JOB do you using?
V2.2.0

问题描述：
比如现在新建了1万个任务，都是每10分钟跑一次，cron表达为：0 0/10 * * * ?
现在admin调度中心的fast线程池设置的max=500

那么每次10分钟调度的时候，会出现调度线程池大量拒绝的错误，请问下这个该如何解决？难道这个框架调度能力没法扩展吗？

**Comment by zqszzs** [comment]
同问，经常出现调度线程池满了的情况，很尴尬，难道只能增加调度线程池的线程数量？

**Comment by wenhsh** [comment]
@xuxueli 老板麻烦看看

**Comment by xuxueli** [comment]
感谢反馈！
提升集群能力有两种方式。
- 1、调度线程数调大：能够线程提升调度能力。
- 2、调度中心集群：调度中心不仅能做到HA，也能够提升调度能力的。集群情况下，不同调度节点会交替方式逐个进行调度，分摊调度压力。

除了上述几种方式，也有其他因素影响调度能力。包括：
- DB速度：DB速度快，能够快速处理任务信息，快速释放调度线程，提升调度性能。
- 调度通讯速度：调度请求速度块，能够快速释放调度通讯线程，提升调度性能。
