### ISSUE TITLE
可以将rpc调用的地方和心跳检测的地方设计成接口的形式。

### ISSUE THREAD

**Issue by liuwenjincoco** [xuxueli/xxl-job#189]
有的公司有自己的rpc框架，很多时候，想将xxl-job与公司的rpc中间件相结合，xxl-job关于rpc调用和接口的形式，以便于扩展和改造。

 自己猜测，@xuxueli 大大自己实现一个轻量级的rpc是为了xxl-job的开箱即用与易于上手，个人建议此处也可以做的更加容易扩展和改造一点，自己的一点点想法，请指点。

**Comment by xuxueli** [comment]
你好，感谢反馈啊！
自研RPC的初衷是为了尽量减少对第三方的依赖，降低学习成本。XXL-JOB 尽量做到高内聚 低耦合。
