### ISSUE TITLE
请教几个细节的问题。spring-boot的例子、任务依赖、任务交互

### ISSUE THREAD

**Issue by dbcdcw** [xuxueli/xxl-job#190]
您好，看到xxl-job的时候感到很惊艳，但是看文档与例子的时候有几个问题，希望您解答一下。
大概测了一下，有如下几个问题
1、例子中spring-boot的启动方式没测试成功：原因是编译后的jar包运行时报异常，找不到类，网上说可能是pom有问题，暂时搁置了spring-boot的测试，但是理论上应该是没问题的，毕竟机制都一样。
是我执行有问题还是什么？我用的java -jar jar包
2、个人现在的任务依赖自上而下，所以是不是如下2条结果？
2.1也就是A执行完之后可以执行B，B执行后可以执行C这种模式，那么另一种A1，B1执行完之后才能执行C1需要自己排顺序才可以。
2.2同时，要把所有子任务都设置成不自动执行也就是cron 0 0 0 0 0 0 0这种，要不然可能会导致子任务提前执行。
3、任务之间没有交互信息。所以B基于A的数据结果继续处理，不支持（除非类似把结果序列化到文件。。。）。任务间不可以交互吧？
3.1、文档中api相关有一句4、触发任务单次执行服务，支持任务根据业务事件触发；
这个触发是怎么算的？分片后触发？比如说。。一个任务100要处理的，然后分片成50/50，是单个50处理完就会触发下一个任务了吧？个人理解这个相当于现在代码之中了，所以是把分给自己的50处理完就触发下一个了吧？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
1、springboot版本，重新编译打包运行下，如果仍然有问题，可以加入QQ交流群沟通啊，群号在项目主页网站。
2.1、现在任务依赖，父任务支持配置多个子任务，子任务不支持多个父任务的啊；
2.2、子任务可以通过暂停，停止cron触发的啊；
3、任务依赖的触发，是根据父任务的结果状态 “SUCCESS” 来触发的，暂时没有数据交互。
如果有定制需求，可以加群进行交流哈！
3.1、关于事件触发的解释：系统提供了API接口，用户客户在业务代码中根据业务逻辑，在需要的时候请求该API进行基于业务事件的任务触发，事件触发适用于所有类型任务，分片任务，普通任务均可。

**Comment by vangoleo** [comment]
> 你好，感谢关注和反馈！
> 1、springboot版本，重新编译打包运行下，如果仍然有问题，可以加入QQ交流群沟通啊，群号在项目主页网站。
> 2.1、现在任务依赖，父任务支持配置多个子任务，子任务不支持多个父任务的啊；
> 2.2、子任务可以通过暂停，停止cron触发的啊；
> 3、任务依赖的触发，是根据父任务的结果状态 “SUCCESS” 来触发的，暂时没有数据交互。
> 如果有定制需求，可以加群进行交流哈！
> 3.1、关于事件触发的解释：系统提供了API接口，用户客户在业务代码中根据业务逻辑，在需要的时候请求该API进行基于业务事件的任务触发，事件触发适用于所有类型任务，分片任务，普通任务均可。

你好，请问下有关于“事件触发”功能的文档吗？找了一圈也没看到，谢谢！
