### ISSUE TITLE
请教下，如果执行器用docker的方式来运行，执行的IP怎么处理？

### ISSUE THREAD

**Issue by utopro** [xuxueli/xxl-job#191]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，感谢关注！
执行器会自动获取IP地址的，然后自动注册到调度中心，不需要人工干预的。

**Comment by utopro** [comment]
docker方式下，执行器获取的是内部的IP，注册到调度中心也是用的内部IP，调度中心调度执行器的时候访问不到。

**Comment by dhyang** [comment]
直接将xx-job运行在Docker容器中， 与执行器在同一个网络中，就不会有问题。
比如直接运行tomcat镜像，然后将xx-job运行在tomcat中。

**Comment by jinhuisheng** [comment]
如果xxl-job-admin不在容器中，执行器在容器中，怎么处理呢？ @dhyang

**Comment by jinhuisheng** [comment]
xxl.job.executor.ip ,这个地址，Jetty会根据它启动，同时，注册调用中心时，也要用这个ip区注册，能把它们分开吗？如果指定一个外网ip，Jetty启动就会报错。 @xuxueli

**Comment by lanhuai** [comment]
> xxl.job.executor.ip ,这个地址，Jetty会根据它启动，同时，注册调用中心时，也要用这个ip区注册，能把它们分开吗？或者就用来注册调度中心时使用，jetty启动时使用本地ip或容器ip。如果指定一个外网ip，Jetty启动就会报错。 @xuxueli 

我也打算改这个呢

**Comment by jinhuisheng** [comment]
期待中

**Comment by itliusir** [comment]
同样遇到这个问题，添加执行器时候要手动注册需要写容器内部IP

**Comment by cheocs** [comment]
如果是使用K8S编排Docker的话，调度中心地址配Service名字就解决了。

**Comment by yuniansheng** [comment]
我也遇到类似问题，我的执行器所部署的机器会存在有多个ip的情况
1.我机器上有多个网卡，一个是虚拟机创建的网卡（ip：192.168.99.1），一个是本地连接（ip：172.18.23.137），192.168.99.1这个地址域中其它机器是不能访问的
2.线上环境使用了LVS因此有vip和实际ip
而执行器自动注册的时候会使用192.168.99.1这个ip，但是这个ip调度中心其实是访问不到的，调度中心只能访问172.18.23.137这个地址，以至于现在我只能通过手动录入的方式注册。
这里能改成调度中心接收执行器注册请求的时候使用TCP连接的客户端ip吗？这样注册的ip就是可访问的了。

**Comment by Hinsteny** [comment]
可以考虑修改注册中心，直接获取执行器的对外请求ip和端口

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/630
（提供docker IP获取方案）

**Comment by Veitor** [comment]
问一下，如果使用docker运行执行器，并且要执行php脚本，那么这个执行器容器中是不是还要再安装php环境？

**Comment by itliusir** [comment]
@Veitor 不然呢 你怎么运行？

**Comment by Veitor** [comment]
> @Veitor 不然呢 你怎么运行？

不太熟悉java，所以没有运行执行器= =！调度器是直接用的docker跑的。。所以还在等执行器的docker出来

目前我就大致的了解一下设计思路，他的这调度器应该是类似客户端的性质是吧，执行的代码是在客户端机器上执行的吧，所以执行器客户端所在环境需要对应脚本的可执行程序是吧

**Comment by itliusir** [comment]
@Veitor 关于服务端客户端的架构，官方文档都有的

**Comment by lvzhihao** [comment]
xxl-job-admin
docker network: xxl-net driver: bridge

xxl-job-executor
docker network: xxl-net external: true

**Comment by sunqb** [comment]
docker里面跑调度器，虚拟机跑执行器。调度器获取不到执行器地址，获取的是docker内的地址，提示找不到，使用的是最新版xxl-job
