### ISSUE TITLE
多个调度中心，任务重复执行

### ISSUE THREAD

**Issue by jipeigong** [xuxueli/xxl-job#1919]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

集群环境：
admin x2，执行器 x2
数据库：阿里云RDS mysql

 创建任务：
![微信截图_20200821113943](https://user-images.githubusercontent.com/7414916/90850134-788e7d80-e3a3-11ea-84bd-89e7a98f0995.png)

执行结果：
![微信截图_20200821114421](https://user-images.githubusercontent.com/7414916/90850235-b12e5700-e3a3-11ea-98aa-c4807c932840.png)

![微信截图_20200821112412](https://user-images.githubusercontent.com/7414916/90850019-3c5b1d00-e3a3-11ea-97b8-1a8082222df7.png)

![微信截图_20200821112419](https://user-images.githubusercontent.com/7414916/90850016-3bc28680-e3a3-11ea-802a-749dbc845f52.png)

同一实际每个调度中心都触发执行了一次
### Other information

同 #1886

**Comment by jipeigong** [comment]
问题已解决：问题是批量执行sql脚本时此INSERT INTO `xxl_job_lock` ( `lock_name`) VALUES ( 'schedule_lock');脚本没生效，导致DB锁未生效

**Comment by xiaozichen** [comment]
请问你是怎么解决的这个锁未生效的问题

**Comment by fengmingli** [comment]
这个问题，我也遇到了。是怎么解决锁未生效的问题的

**Comment by jipeigong** [comment]
手动执行sql

**Comment by itwujt** [comment]
> 问题已解决：问题是批量执行sql脚本时此INSERT INTO `xxl_job_lock` ( `lock_name`) VALUES ( 'schedule_lock');脚本没生效，导致DB锁未生效

未解决：这个表锁有，也生效了，但是还是重复执行了，我用的是 2.3.1 版本的 xxl-job，xxl-job-admin 部署了双节点，执行器双节点，路由策略轮询，阻塞策略单机串行

**Comment by double-zyn** [comment]
> > 问题已解决：问题是批量执行sql脚本时此INSERT INTO `xxl_job_lock` ( `lock_name`) VALUES ( 'schedule_lock');脚本没生效，导致DB锁未生效
> 
> 未解决：这个表锁有，也生效了，但是还是重复执行了，我用的是 2.3.1 版本的 xxl-job，xxl-job-admin 部署了双节点，执行器双节点，路由策略轮询，阻塞策略单机串行
请问下解决了么，我们这生产也遇到了同样的问题，版本是2.2.0。
