### ISSUE TITLE
请教一个分片的问题，以及提一个貌似特别不重要的建议

### ISSUE THREAD

**Issue by dbcdcw** [xuxueli/xxl-job#192]
首先，感谢回答上一个问题。
然后分片，我先说一下个人理解，然后请大大指正。
分片这个是不是可以理解成：
1、前提，比如说10个执行器。100条待处理数据。
2、index分片序号，按10个执行器分别是从0-9自动分发；total：总分片数10。
3、每个处理器中间，首先获取一次全任务，比如说生成一个list，然后每个执行器代码级别控制分别取对应的1/10，进行处理。
4、当10个执行器都处理完成后，这个任务才算处理完成。
请问一下，是大概这么个流程么？
另外如果一个执行器处理失败了，后续会怎么处理？失败重试是怎么个重试？重试当前分片？
建议：
上班期间在天朝度娘用的比google多。。虽然说我在家用google。。度娘搜索xxl-job不能第一时间找到咱们的首页或者github。建议想办法找起来方便些。。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈啊！
1、任务运行包括“触发”和“执行”两个步骤，目前失败重试是针对“触发”的失败，失败重试时，只会重试当前分片。
2、度娘不收录github，项目首页也是托管在github page上的。在考虑在国内搭建个站点方便查看文档：）
