### ISSUE TITLE
重复执行

### ISSUE THREAD

**Issue by NYForever** [xuxueli/xxl-job#1925]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by luckyJonh** [comment]
代码中保证每个job只被其中一个调度进程调度是通过 一个 select ... for update 实现行级锁（mysql InnoDB是行级锁，MyAsim应该是锁表），所以同一时间只有一个 进程能够把这条sql执行了，其他进程执行会阻塞。如果重复调度，可能是你使用的数据库不支持这样的行级锁？抑或是后续job的下次执行时间有问题，可以debug测试一下

**Comment by xuxueli** [comment]
> 代码中保证每个job只被其中一个调度进程调度是通过 一个 select ... for update 实现行级锁（mysql InnoDB是行级锁，MyAsim应该是锁表），所以同一时间只有一个 进程能够把这条sql执行了，其他进程执行会阻塞。如果重复调度，可能是你使用的数据库不支持这样的行级锁？抑或是后续job的下次执行时间有问题，可以debug测试一下

+1
