### ISSUE TITLE
2.2.0版本 自动注册，任务中心日志报了：执行器地址为空 的错误

### ISSUE THREAD

**Issue by thinkersOne** [xuxueli/xxl-job#1926]
![image](https://user-images.githubusercontent.com/19427384/91267788-a8c08c80-e7a6-11ea-8d8a-c0e135527470.png)

**Comment by romeoblog** [comment]
我也是出现了这个类似的事情，接着手动注册绑定，在切换为自动注册，结果正常注册上，存在着偶然的出现概率问题

**Comment by xuxueli** [comment]
你好，从上图看应该是执行器心跳注册失败导致，检查下是不是心跳注册是否存在故障日志。
