### ISSUE TITLE
500错误 msg：java.lang.RuntimeException: Client-error:Connect to x.x.x.x:9999 [/x.x.x.x] failed: connect timed out

### ISSUE THREAD

**Issue by sjby365** [xuxueli/xxl-job#193]
500错误 msg：java.lang.RuntimeException: Client-error:Connect to x.x.x.x:9999 [/x.x.x.x] failed: connect timed out

注册方式：自动注册
阻塞处理策略：覆盖之前调度
失败处理策略：失败告警
地址列表：[ x.x.x.x:9999,  x.x.x.x:9999]
路由策略：故障转移

>>>>>>>>>>>触发调度<<<<<<<<<<< 
心跳检测：
address： x.x.x.x:9999
code：500
msg：java.lang.RuntimeException: Client-error:Connect to  x.x.x.x:9999 [/ x.x.x.x] failed: connect timed out

心跳检测：
address： x.x.x.x:9999
code：500
msg：java.lang.RuntimeException: Client-error:Connect to  x.x.x.x:9999 [/ x.x.x.x] failed: connect timed out

shell方式 定时执行500错误 ，频率相对较高，单机集群都出现，但是心跳检测一直正常   过后手动执行正常。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
这种情况原因是调度中心请求执行器接口超时导致的，可能有以下几个原因：
1、调度中心与执行器之间网络波动，无法通讯。
2、执行器启动失败，无法提供服务接收调度请求。
推测是第一种情况，可以在发出调度请求是加一些Log，确认下当时的网络情况。

**Comment by sjby365** [comment]
感谢回复  阿里主机 之前执行器未绑定ip，自动获取的内网,结果很不稳定    目前第个执行器绑定外网ip运行稳定！！！
