### ISSUE TITLE
求教（建议）。。（如何）用spring-boot的方式启动xxl-job-admin

### ISSUE THREAD

**Issue by dbcdcw** [xuxueli/xxl-job#194]
首先，还是要感谢大神对上个问题的回复。。然后大神没有说我理解分片有什么错误，我就默认我理解对了。。
然后又要麻烦大神了。。请问一下有方法可以让xxl-job-admin以spring-boot的方式启动么？
公司想要把这个以服务的方式集成进系统。。然后现在用的都是spring-boot/spring-cloud的那一套东西。。
以上是“政治因素”另外。。个人觉得（以下纯属个人感觉不要太在意）spring-boot/spring-cloud是不是更能体现xxl-job-admin可以集群？扔进eureka统一管理是不是可以是咱们这个项目更容易集成一点。。

**Comment by xuxueli** [comment]
你好，xxl-job内部已经集成了注册中心，不在依赖外部eureka。

上述提到的springboot运行调度中心，这块预计 2.0 版本提供支持，敬请期待！
