### ISSUE TITLE
cron时间执行不正确的问题 0 30 0 * * ?

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#1940]
admin版本是最新的2.2.0
服务器时间 CST
数据库时间 GMT
预期执行时间是 每日凌晨00:30:00
结果执行时间是 每日早上08:30:00
点击操作 > 下次执行时间 显示的时间是正确的
2020-09-02 00:30:00
2020-09-03 00:30:00
2020-09-04 00:30:00
2020-09-05 00:30:00

不知道各位有遇到这样的情况吗

**Comment by boot-vue** [comment]
数据库 or  系统  时区错了吧   很明显差了8小时

**Comment by farsunset** [comment]
服务器时间为CST 通过date命令查看 时间是没问题

**Comment by farsunset** [comment]
jdbc url 上设置了时区为 shanghai

**Comment by boot-vue** [comment]
> jdbc url 上设置了时区为 shanghai

mysql的话可以select now();看看时间对不对      时间有可能默认按着数据库的时间来    猜的

**Comment by farsunset** [comment]
数据库时间是GMT 不能修改，那就只能修改cron时间了吗，触发时间按理说不应该跟数据库时间相关啊

**Comment by farsunset** [comment]
> > jdbc url 上设置了时区为 shanghai
> 
> mysql的话可以select now();看看时间对不对 时间有可能默认按着数据库的时间来 猜的

看了时间是正确的北京时间

**Comment by boot-vue** [comment]
反正几乎可以确定就是时区的问题    也有可能root用户系统时间是对的   调度中心跑java的用户时间是错的    慢慢排查吧   可以看一下调度中心输出的日志时间是否正确     不太可能是其它方面的问题

**Comment by farsunset** [comment]
问题解决了 需要启动时加参数user.timezone=GMT+8

**Comment by Song122** [comment]
@farsunset 我也遇到了这个问题 java -Xms512m -Xmx1024m -jar xxl-job-admin/target/xxl-job-admin-2.4.0-SNAPSHOT.jar -Dlog4j2.formatMsgNoLookups=true -Duser.timezone=GMT+08 --spring.config.location=/etc/config/application.properties ，我的执行命令是这个也不行
