### ISSUE TITLE
关于springboot执行器配置

### ISSUE THREAD

**Issue by lly835** [xuxueli/xxl-job#1942]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

我看示例项目里，已经在application.properties配置了xxl.job.admin.addresses
`https://github.com/xuxueli/xxl-job/blob/master/xxl-job-executor-samples/xxl-job-executor-sample-springboot/src/main/resources/application.properties`

java代码里再注入了一遍，XxlJobConfig
```
https://github.com/xuxueli/xxl-job/blob/master/xxl-job-executor-samples/xxl-job-executor-sample-springboot/src/main/java/com/xxl/job/executor/core/config/XxlJobConfig.java
```

建议【约定优于配置】
使用者只需要配置application.properties即可使用xxl-job。
开发者对于配置即使用的方式是非常熟悉的，比如springboot里配置了spring.datasource.url就可以操作数据库了

**Comment by hundanLi** [comment]
自己可以写个自动配置类或者starter
