### ISSUE TITLE
微服务场景下，如何在任务调用过程中进行服务间调用鉴权

### ISSUE THREAD

**Issue by kanghouchao** [xuxueli/xxl-job#1945]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
在微服务场景下，我需要在一个任务执行的服务中调用别的服务接口，但是别的服务有鉴权，需要在请求头里面加一些内容
### Actual behavior
现在我找不到在哪里可以设置这种内容
### Other information
因为rpc选择了feign，如果那些接口不做鉴权有安全隐患

**Comment by samz406** [comment]
选shell任务 用curl试试呢

**Comment by kanghouchao** [comment]
> 选shell任务 用curl试试呢

这个思路我试试看，不过现在我换成MQ 调处理了
