### ISSUE TITLE
客户端会生成N多日志文件，根据服务端返回的xxl_job_log表自增Id

### ISSUE THREAD

**Issue by PlayBoyFly** [xuxueli/xxl-job#1946]
1.代码位置  TriggerCallbackThread的
                  callbackLog(callbackParamList, "<br>----------- xxl-job job callback finish.");
2.
![image](https://user-images.githubusercontent.com/13899425/92185175-bf8d7000-ee85-11ea-9f43-3bda789cd827.png)

3.日志文件
![image](https://user-images.githubusercontent.com/13899425/92185200-d0d67c80-ee85-11ea-8e93-57bfd088cfca.png)

**Comment by xuxueli** [comment]
你好，日志支持开启自动清理功能，可以参考启用。
