### ISSUE TITLE
一直报链接超时的错误，但是任务可以正常调度

### ISSUE THREAD

**Issue by chengfeng110** [xuxueli/xxl-job#1947]
![image](https://user-images.githubusercontent.com/33675286/92194219-bb208180-ee9c-11ea-827e-91f8afeaeb78.png)

依赖是最新的2.2.0,任务可以正常调度，但是报连接超时的错误。

**Comment by QloveB** [comment]
同样的问题，这个问题貌似大家挺多人遇到的，不知道什么情况。

**Comment by xuxueli** [comment]
你好，应该是网络问题，确认下是否通常。
