### ISSUE TITLE
是否支持任务只执行一次，而无需定时周期执行？

### ISSUE THREAD

**Issue by kervin521** [xuxueli/xxl-job#195]
针对web请求的分布式调度处理

**Comment by xuxueli** [comment]
你好，感谢关注！
支持的，XXL-JOB支持基于事件触发任务调度，提供API服务，请求一次触发一次任务执行。详细内容可以查看文档或者加入交流群沟通哈。

**Comment by kervin521** [comment]
文档里没有找到啊，在哪里能找到，或如何加群沟通啊？

**Comment by xuxueli** [comment]
项目首页有文档连接的：http://www.xuxueli.com/xxl-job/  ，文档 “技术交流” 章节里有群号信息。

**Comment by kervin521** [comment]
谢谢，我这里访问不到的，受限了

创建任务界面的Cron参数是必填选项，只能是周期执行的

**Comment by jinwandalaohu** [comment]
我是这样实现的，在新增任务时设置触发时间为2049年，然后再把任务pause。

**Comment by itliusir** [comment]
可以自己加个参数判断 如果是单次的执行完就删除

**Comment by xuxueli** [comment]
@kervin521 @littleeleplent 你好，即将发布的 v1.9.2 已经提供了API服务，支持动态触发任务运行，而且支持动态参数，可以pull master参考下。

**Comment by xuxueli** [comment]
@jinwandalaohu 你好，目前任务需要强制绑定Corn进行触发，后续将会扩展提供SampleTrigger，None等多种配置方式，已经加入排期列表。

**Comment by Granstone** [comment]
2.0.2里面看到样例代码了，但是为什么事件触发的任务在调度中心没有日志记录，看数据库里面也没有存相关记录，控制台日志看像是触发成功了如：xxl-job regist JobThread success, jobId:1, handler:com.xxl.job.executor.service.jobhandler.DemoJobHandler@c927f1
