### ISSUE TITLE
关于多数据库支持的问题？Oracle

### ISSUE THREAD

**Issue by zhunian2003** [xuxueli/xxl-job#1954]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
使用最新版本2.2.1
### Expected behavior
能发支持其他数据库，比如SqlServer、Oracle等
### Actual behavior
是否可改为jpa活mybaties-plus这样更容易支持多数据库
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/pull/1572
