### ISSUE TITLE
分片广播路由策略如何实现任务重新分配？

### ISSUE THREAD

**Issue by jsnan** [xuxueli/xxl-job#1956]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB2.2.0
### Expected behavior
在选择 “路由策略” 为 "分片广播"时，如果部分节点宕掉了或者进程挂掉了，这些节点的任务需要让其它正常节点承接过去，例如数据库中有24条任务记录，有三个节点组成的应用集群，正常情况下，每个节点会基于均衡策略分配8个任务，一旦某个节点宕掉了，这个节点的8个任务需要让另外两个正常节点去承接

### Actual behavior
在选择 “路由策略” 为 "分片广播"时，如果部分节点宕掉了或者进程挂掉了，其它正常节点无法感知集群状态，需要自己写逻辑实现任务的重新分配
### Other information

**Comment by xuxueli** [comment]
故障节点停止注册会被摘除，下次调度会跳过
