### ISSUE TITLE
任务执行的本地日志文件过多，是否考虑落库？？避免本地磁盘随着调用量增加而剧增，影响机器性能！

### ISSUE THREAD

**Issue by zwp201301** [xuxueli/xxl-job#1959]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
本地磁盘的小文件数暴增，如果一个任务秒级的调度周期，则在任务执行的时候，生成的小文件会非常多。
### Actual behavior
运维需要定期清理任务调度的日志文件，对于任务调度，特别是调度周期是秒分级别的，更多的是只关注执行结果是成功还是失败，一般不会去关心它的运行日志。
### Steps to reproduce the behavior
有些业务方在配置任务的时候，是每隔几秒执行一次任务，导致任务日志文件特别多。

### Other information
像任务的执行日志比较少，是不是可以考虑保存在数据库中，尤其是数据库已经有调度日志表。只是新增一个字段，记录日志内容。采用懒查询的时候，只有在单个查看执行日志的时候，才触发查询。

**Comment by ChenYichener** [comment]
我现在就是好几个秒级的任务，导致生成了非常多的小文件，请问有什么办法解决吗？

**Comment by zwp201301** [comment]
秒级的调度频率，试着考虑换一个框架，不要过度依赖定时任务

**Comment by 1034323716** [comment]
这个问题解决了么？

**Comment by zwp201301** [comment]
> 这个问题解决了么？

必须没有解决啊，框架都还没有将这个纳入TODO List呢

**Comment by dinghuang** [comment]
同样遇到这个问题，任务执行间隔太频繁，生成的日志文件太多，导致服务器句柄数量不够，目前打算改源码，把日志这一块改成落库，不然没法用了= =

**Comment by zwp201301** [comment]
> 同样遇到这个问题，任务执行间隔太频繁，生成的日志文件太多，导致服务器句柄数量不够，目前打算改源码
> 
> 目前2个思路：1 日志落库，需要前端逻辑也进行修改
> 2 只生成执行失败的日志log，我们不关心成功的log，这样数量可以大大减少

可以考虑给官方提个fork，实现方式层面，做成配置的，想落库的就落库，想写文件的就写文件。

**Comment by dinghuang** [comment]
我们直接修改了源码，是按照2去修改的，成功的我们就不落库了，但是有个缺点就是你想在界面查看成功的log就看不了

**Comment by xuxueli** [comment]
秒级任务，建议用延时消息来做，建议 XXL-MQ
