### ISSUE TITLE
建议把jetty线程池的配置放出来

### ISSUE THREAD

**Issue by zj4775** [xuxueli/xxl-job#196]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
你好，你再用的版本，以及任务数量是多少啊？
一个任务在执行器中会对应一个任务线程，如果多个任务会对应多个任务线程。
但是，在 v1.8.0 新增特性 “任务线程轮空30次后自动销毁”，会主动销毁闲置线程缓解类似情况。

**Comment by zj4775** [comment]
我没有修改代码？就把1.8.0的代码拉下来，然后修改下数据库的连接配置，其他的配置没有修改，最后每个线程状态是：

名称: pool-2-thread-68
状态: java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@df944f4上的WAITING
总阻止数: 0, 总等待数: 1

堆栈跟踪: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by zj4775** [comment]
刚才报oom的是服务器，当时线程数量是266个，奇怪的是我本地跑起来，线程的数量顶峰是280不动了，但任务还在正常的跑。

**Comment by ie7shop** [comment]
现在我下的是1.9.0版本，这个问题存在。。。不敢应用到项目中，有什么解决方法吗

**Comment by xuxueli** [comment]
@ie7shop @zj4775 
你好，上述问题是正常现象，执行器通讯组件jetty内部维护一个maxSize=256的线程池，线程数量上升由此而来。
执行器底层对线程的使用进行了严格的控制，经过系统预热之后，内部维护的线程会维持在一个稳定的数量，并不会无限制增长，可以放心使用。
