### ISSUE TITLE
如何加入Prometheus的监控中去？

### ISSUE THREAD

**Issue by beelzebub2006** [xuxueli/xxl-job#1970]
如何加入Prometheus的监控中去？

**Comment by dususu** [comment]
同问

**Comment by wuxiaoyi** [comment]
可以引入
``` 
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-prometheus</artifactId>
</dependency>
```

监控点url:  xxx/xxl-job-admin/actuator/prometheus
配置到Prometheus平台就好了

**Comment by dususu** [comment]
@wuxiaoyi  谢谢~ 知道了

**Comment by system51** [comment]
@wuxiaoyi  你说的引入是在哪里引入啊？

**Comment by xiaoshumiao6** [comment]
你们搞定了吗？  Prometheus 监控？ 
<img width="692" alt="image" src="https://github.com/xuxueli/xxl-job/assets/34533475/473919c2-0d6e-4359-b6db-9f49971bfa95">

**Comment by huangsijun17** [comment]
> 可以引入
> 
> ```
> <dependency>
> 	<groupId>io.micrometer</groupId>
> 	<artifactId>micrometer-registry-prometheus</artifactId>
> </dependency>
> ```
> 
> 监控点url: xxx/xxl-job-admin/actuator/prometheus 配置到Prometheus平台就好了

我这添加后只有一些Java的指标，怎么加入xxl-job的执行信息等呢？
