### ISSUE TITLE
执行器模块的commandhandler模块进程无限挂起BUG

### ISSUE THREAD

**Issue by huqiandream** [xuxueli/xxl-job#1972]
Please answer some questions before submitting your issue. Thanks!
### Which version of XXL-JOB do you using?
master版本以及历史版本。
### Expected behavior
在本机执行手工执行结束的脚本能在系统中也能达到一致效果
### Actual behavior
手工能执行结束的脚本在执行器执行时却不能正常结束
### Steps to reproduce the behavior
重现方法。尝试脚本中使用find命令，find打印尽可能多的不能find的错误信息，这时候在本机上执行脚本是可以正常执行的，但使用执行器commandhandler命令模式会无法执行结束。
### Other information
产生此原因是因为commandhandler的代码段里引用了
Process process = Runtime.getRuntime().exec(command);
而没有处理错误输出流。当错误输出缓冲区超过默认的2048长度时造成缓冲区溢出导致进程挂起。
改用如下代码可以解决此问题：
   public ReturnT<String> commandJobHandler(String param) throws Exception {
        List<String> command = Arrays.asList("bash","-c",param);
        int exitValue = -1;
        System.out.print(command);
        BufferedReader bufferedReader = null;
        try {
            // command process
            ProcessBuilder processBuilder = new ProcessBuilder();
            processBuilder.command(command);
            processBuilder.redirectErrorStream(true);

            Process process = processBuilder.start();
            BufferedInputStream bufferedInputStream = new BufferedInputStream(process.getInputStream());

//            Process process = Runtime.getRuntime().exec(command);
            bufferedReader = new BufferedReader(new InputStreamReader(bufferedInputStream));

            // command log
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                XxlJobLogger.log(line);
            }

            // command exit
            process.waitFor();
            exitValue = process.exitValue();
        } catch (Exception e) {
            XxlJobLogger.log(e);
        } finally {
            if (bufferedReader != null) {
                bufferedReader.close();
            }
        }

        if (exitValue == 0) {
            return IJobHandler.SUCCESS;
        } else {
            return new ReturnT<String>(IJobHandler.FAIL.getCode(), "command exit value("+exitValue+") is failed");
        }
    }

**Comment by xuxueli** [comment]
你好，感谢反馈！
问题已修复并推送master分支，将会跟随下个版本发布。
