### ISSUE TITLE
使用Druid后控制台总是提示：Closing non transactional SqlSession

### ISSUE THREAD

**Issue by elvis324** [xuxueli/xxl-job#1983]
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3263ce2c]
Creating a new SqlSession

SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@406c36f1] was not registered for synchronization because synchronization is not active

JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@489fd32d] will not be managed by Spring
==>  Preparing: SELECT t.id, t.job_group, t.job_cron, t.job_desc, t.add_time, t.update_time, t.author, t.alarm_email, t.executor_route_strategy, t.executor_handler, t.executor_param, t.executor_block_strategy, t.executor_timeout, t.executor_fail_retry_count, t.glue_type, t.glue_source, t.glue_remark, t.glue_updatetime, t.child_jobid, t.trigger_status, t.trigger_last_time, t.trigger_next_time FROM xxl_job_info AS t WHERE t.trigger_status = 1 and t.trigger_next_time <= ? ORDER BY id ASC LIMIT ? 
==> Parameters: 1601015924038(Long), 6000(Integer)

**Comment by xuxueli** [comment]
你好，问题无法复现。
