### ISSUE TITLE
极端情况下调度器的线程池再初始化可能慢于失败重试的调度从而引发NPL

### ISSUE THREAD

**Issue by liangyd1024** [xuxueli/xxl-job#1984]
![image](https://user-images.githubusercontent.com/5831731/94244062-e1d95180-ff4a-11ea-90ba-37ad74974dcc.png)

如图：第一步先执行了失败重试发起重新调度，第二步才初始化调度器的线程池

**Comment by xuxueli** [comment]
你好，问题已修复并推送master分支，将会跟随下个版本发布。
