### ISSUE TITLE
任务随机运行在集群中，怎么保证上一个任务运行完成后，新的调度任务才能运行

### ISSUE THREAD

**Issue by lxp411** [xuxueli/xxl-job#1991]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
只要上一个任务没有完成，调度日志的调度结果就是失败
### Actual behavior
调度结果是成功
### Steps to reproduce the behavior
调度任务是每1小时执行一次
### Other information
任务执行时间有时候超过1小时，新任务执行后导致数据重复

**Comment by xuxueli** [comment]
你好，可以结合一致性哈希路由策略来实现。
