### ISSUE TITLE
xxl-job客户端不想打印日志文件，希望有地方可以配置。

### ISSUE THREAD

**Issue by liuguangbo1030** [xuxueli/xxl-job#1993]
客户端的服务部署k8s中，服务日志都是打在标准的stdout，不需要指定具体的日志目录，现在在xxl-job-core的日志组件里面必须要以文件的形式打印日志，希望可以做成可配置的。

**Comment by xuxueli** [comment]
你好，执行器日志可以配置自动清理，可以参考下。
