### ISSUE TITLE
是否有计划支持流程调度

### ISSUE THREAD

**Issue by icesugar** [xuxueli/xxl-job#1994]
当前版本满足了执行器部署到各种环境里，是否有计划支持流程的调度。
比如拖拉拽画一个流程，配置每个环节的调度任务，
环节上配置 会签/抢占，调度中心根据流程去调度。
抢占： 环节里的任务一个执行成功/失败 就进入下一个环节
会签： 环节里的所有任务执行成功/失败 就进入下一个环节

使用场景一般是系统之间的数据调度，
例如：核心总账 需要与其他二十几个系统对接 科目 凭证 余额等。且有先后顺序。

**Comment by zhanzhenguang** [comment]
我现在是结合MQ通知+Redis计数，来完成这个场景

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
