### ISSUE TITLE
XXL-JOB 2.2.1-SNAPSHOT使用XxlJobLogger打印日志任务无法结束

### ISSUE THREAD

**Issue by Suny95** [xuxueli/xxl-job#1995]
问题如题，我使用XxlJogLogger打印日志，发现任务一直没有结束掉，去查看执行日志发现：

代码都已执行完成，回调也完成了，但还是一直处于获取日志的状态，导致任务一直无法结束运行。

当我把XxlJogLogger打印日志去掉后，一切就正常了

**Comment by xuxueli** [comment]
你好，建议下载release版本使用。
