### ISSUE TITLE
NettyHttpConnnctClient存在内存泄漏风险!!!!!!

### ISSUE THREAD

**Issue by UFO-Coder** [xuxueli/xxl-job#1996]
在init时，如若不断发生无法连接，连接拒绝，连接超时等异常时，netty相关组件无法close。造成内存泄漏。在这种错误数过多时，会有oom 以及fd 句柄膨胀进而达到限制，无法调度的风险

**Comment by xuxueli** [comment]
你好，这个问题已经修复，升级即可解决。

**Comment by Xusq513** [comment]
请问一下，这个具体是哪块有问题，或者需要升级到哪个版本呢，我这边也有这个问题，目前版本是2.1.2

**Comment by Aleneee** [comment]
你好，请教一下，我们使用版本 2.1.2 也遇到了文件描述符一直上涨的问题，不知道和这个是否相关，可以说明一下具体哪个 MR fix 这个问题吗。

<img width="883" alt="Image" src="https://github.com/user-attachments/assets/e12d7ec4-f0bd-4054-95e0-dc177a4987eb" />

**Comment by xuxueli** [comment]
升级 2.2 及以后即可。建议升级最新版。
