### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.setLength(I)V

### ISSUE THREAD

**Issue by zhaoxinhu** [xuxueli/xxl-job#1999]
12:07:33.908 logback [nioEventLoopGroup-3-1] ERROR c.x.j.c.s.EmbedServer$EmbedHttpServerHandler - >>>>>>>>>>> xxl-job provider netty_http server caught exception
tomcat-xxl-job-1    | java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.setLength(I)V
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:893)
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpObjectDecoder$LineParser.process(HttpObjectDecoder.java:941)
tomcat-xxl-job-1    |   at io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1336)
tomcat-xxl-job-1    |   at io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1316)
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:872)
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpObjectDecoder$LineParser.parse(HttpObjectDecoder.java:928)
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:195)
tomcat-xxl-job-1    |   at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:103)
tomcat-xxl-job-1    |   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
tomcat-xxl-job-1    |   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
tomcat-xxl-job-1    |   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
tomcat-xxl-job-1    |   at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
tomcat-xxl-job-1    |   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
tomcat-xxl-job-1    |   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
tomcat-xxl-job-1    |   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
tomcat-xxl-job-1    |   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
tomcat-xxl-job-1    |   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
tomcat-xxl-job-1    |   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
tomcat-xxl-job-1    |   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
tomcat-xxl-job-1    |   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
tomcat-xxl-job-1    |   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
tomcat-xxl-job-1    |   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
tomcat-xxl-job-1    |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
tomcat-xxl-job-1    |   at java.lang.Thread.run(Thread.java:748)
tomcat-xxl-job-1    | 12:07:33.912 logback [nioEventLoopGroup-3-1] ERROR c.x.j.c.s.EmbedServer$EmbedHttpServerHandler - >>>>>>>>>>> xxl-job provider netty_http server caught exception
tomcat-xxl-job-1    | java.lang.IncompatibleClassChangeError: Class io.netty.util.Recycler$DefaultHandle does not implement the requested interface io.netty.util.internal.ObjectPool$Handle
tomcat-xxl-job-1    |   at io.netty.buffer.PooledByteBuf.recycle(PooledByteBuf.java:179)
tomcat-xxl-job-1    |   at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:174)
tomcat-xxl-job-1    |   at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110)
tomcat-xxl-job-1    |   at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
tomcat-xxl-job-1    |   at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:376)
tomcat-xxl-job-1    |   at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
tomcat-xxl-job-1    |   at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
tomcat-xxl-job-1    |   at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
tomcat-xxl-job-1    |   at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
tomcat-xxl-job-1    |   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
tomcat-xxl-job-1    |   at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
tomcat-xxl-job-1    |   at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
tomcat-xxl-job-1    |   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
tomcat-xxl-job-1    |   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)

**Comment by zhaoxinhu** [comment]
本地测试正常，放到线上docker中执行任务报错，这个有人遇到过吗？

**Comment by zhaoxinhu** [comment]
线上执行器取消了docker的使用，放到正常的tomcat中还是一样的错误。

**Comment by xuxueli** [comment]
你好，从日志看应该是netty版本冲突，可以调整和xxljob内部一致。

**Comment by mishikaluosi** [comment]
@zhaoxinhu 请问有解决了吗？我也遇到相同的问题
