### ISSUE TITLE
山东学而网络科技有限公司

### ISSUE THREAD

**Issue by chenzhenyang** [xuxueli/xxl-job#2]
山东学而网络科技有限公司
http://www.suerlink.com/portal.php

**Comment by xuxueli** [comment]
您好，谢谢您对xxl-job的关注和支持哈。
你好像把使用登记的位置写错了哈，应该在【https://github.com/xuxueli/xxl-job/issues/1】的下面评会回复进行登记的哈。

**Comment by Skynet-Jacopo** [comment]
这公司是个坑,老板李建源是个人渣,拖欠工资,给他打电话被拉黑,辛辛苦苦大半年被这臭不要脸的给坑了.

**Comment by Skynet-Jacopo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19197928/22180551/de4ee04e-e0ad-11e6-9a95-16469a62b760.png)
就是这个不要脸滴,他一般会在一些QQ技术交流群发布一些招聘信息,望大家不要被他骗了

**Comment by Skynet-Jacopo** [comment]
![default](https://cloud.githubusercontent.com/assets/19197928/22180571/a9949870-e0ae-11e6-84ea-1622e62a254f.png)
就是这个人,他叫李建源,大家记住千万不要被他骗了
