### ISSUE TITLE
当一个系统的部署环境包括linux、Windows、Mac时，是否支持为不同任务设置不同的执行服务器？

### ISSUE THREAD

**Issue by fengnex** [xuxueli/xxl-job#2000]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.2.0 最新版

### Expected behavior
当一个系统的部署环境包括linux、Windows、Mac时，由于OS的差异，有些任务只能在1个或多个OS上运行。
这种情况下，是否支持为不同任务（需要的OS的不同），设置不同的执行服务器，然后每个任务只在指定的一组服务器上运行？

### Actual behavior
目前还不支持上述情况。

### Other information

**Comment by fengnex** [comment]
没有人回复下吗？

**Comment by kingvsgirl** [comment]
同问

**Comment by xuxueli** [comment]
你好，这种情况可以针对不同环境，拆分不同执行器来实现。
