### ISSUE TITLE
调度中心接口请求执行器日志中文乱码

### ISSUE THREAD

**Issue by luodl1991** [xuxueli/xxl-job#2001]
##调度中心接口请求执行器日志中文乱码

pom文件添加如下配置：
                              <configuration>
					<executable>true</executable>
					<fork>true</fork>
					<includeSystemScope>true</includeSystemScope>
					
					<jvmArguments>-Dfile.encoding=UTF-8</jvmArguments>
				</configuration>

目的想使jar变成可执行二进制文件，挂载到linux服务执行

**Comment by luodl1991** [comment]
> ##调度中心接口请求执行器日志中文乱码
> 
> pom文件添加如下配置：
> 
> true
> true
> true
> 
> -Dfile.encoding=UTF-8
> 目的想使jar变成可执行二进制文件，挂载到linux服务执行

![image](https://user-images.githubusercontent.com/37208464/95836700-577a5580-0d72-11eb-8fd9-570875fcd0d5.png)

**Comment by xuxueli** [comment]
你好，问题无法复现。
