### ISSUE TITLE
xxl_job_log表数据量清理不生效，配置 “xxl.job.logretentiondays=7” 也没用 

### ISSUE THREAD

**Issue by 1956025812** [xuxueli/xxl-job#2002]
xxl_job_log表数据量清理不生效，配置 “xxl.job.logretentiondays=7” 也没用 
在控制台看的是日志量少了，但是去数据库查看xxl_job_log表的数据还是有很多之前的 炸了
请问是什么问题呢？

**Comment by shidongwa** [comment]
xxl.job.logretentiondays 这个参数主要是控制磁盘上日志文件保留的天数吧

**Comment by lmx1989219** [comment]
+1

**Comment by lmx1989219** [comment]
> xxl_job_log表数据量清理不生效，配置 “xxl.job.logretentiondays=7” 也没用 在控制台看的是日志量少了，但是去数据库查看xxl_job_log表的数据还是有很多之前的 炸了 请问是什么问题呢？

+1

**Comment by wangere** [comment]
+1

**Comment by xuxueli** [comment]
> xxl.job.logretentiondays 这个参数主要是控制磁盘上日志文件保留的天数吧

+1

**Comment by Good-human** [comment]
> > xxl.job.logretentiondays 这个参数主要是控制磁盘上日志文件保留的天数吧
> 
> +1

这个到底怎么解决，配置 成1不生效，日志量太大了
