### ISSUE TITLE
运行出现异常：com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException

### ISSUE THREAD

**Issue by houxudong01** [xuxueli/xxl-job#2006]
参考稳定配置好xxl后运行出现以下问题，找不到原因，还望解答下
com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.41.129:9522 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:250) at com.sun.proxy.$Proxy133.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:68) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

**Comment by xuxueli** [comment]
你好，确认是否存在防火墙。
