### ISSUE TITLE
xxl-job升级后，内存占用增加不少，年轻代fullGC 增加，扩展内存后水涨船高

### ISSUE THREAD

**Issue by zhonghuahero** [xuxueli/xxl-job#2011]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

### Expected behavior
内存稳定持平

### Actual behavior
内存占用稳定增多，尤其年轻代

### Other information

升级后 引入 xxl-job-core，管理后台项目job-admin内存占用下降，具体执行器项目内存占用增加，但是业务数据量并没有明显增加

**Comment by zhonghuahero** [comment]
升级之前没有依赖 xxl-job-core

**Comment by xuxueli** [comment]
你好，问题无法复现，建议dump内存分析下。
