### ISSUE TITLE
是否可以设置某个任务通过某个用户权限运行？

### ISSUE THREAD

**Issue by darouwan** [xuxueli/xxl-job#2016]
Which version of XXL-JOB do you using? XXL-JOB 2.2.1-SNAPSHOT
Expected behavior：我们有不同的任务部署在Windows server的xxl job上， 不同的任务需要不同的用户权限。我现在用 本地的admin权限来跑xxl job的admin和executor， 这样任务在实际运行的时候， 应该也是使用运行executor的权限运行的吧? 是否可以设定不同的任务使用不同的本地权限来运行？

**Comment by xuxueli** [comment]
你好，任务运行在执行器中，可以针对不同用户权限，分别部署各自的执行器。借助执行器来隔离权限。
