### ISSUE TITLE
2.2.0版本 重复执行多次

### ISSUE THREAD

**Issue by Jesse-so-cool** [xuxueli/xxl-job#2017]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
设置的是1分钟执行一次
### Actual behavior
实际表现为某一分钟执行了10来次
### Other information
集群搭建 2台机 192.168.48.178/192.168.48.179

![image](https://user-images.githubusercontent.com/31425351/96839494-da3e9700-147b-11eb-9a63-2ea713a311e1.png)
![image](https://user-images.githubusercontent.com/31425351/96839503-df034b00-147b-11eb-82d0-f11a82c44c47.png)

**Comment by Jesse-so-cool** [comment]
@xuxueli

**Comment by Jesse-so-cool** [comment]
debug发现，多次执行是由于更新TriggerNextTime没成功（但是没报错），导致5秒内获取到多次对应的任务，但是问题依然没有找到

**Comment by Jesse-so-cool** [comment]
问题解决，已提PR：https://github.com/xuxueli/xxl-job/pull/2021/commits

**Comment by Jesse-so-cool** [comment]
猜测是因为xxl-job 获取任务时 select for update 和 select xxl_job_info不是用的同一个连接问题

**Comment by xuxueli** [comment]
你好，是否数据库主从方式部署？
如果主从方式部署，务必强制走主库（文档又说明）。
