### ISSUE TITLE
是否一个执行器一次只能执行一个任务？

### ISSUE THREAD

**Issue by darouwan** [xuxueli/xxl-job#2018]
XXL-JOB 2.2.1-SNAPSHOT

我在文档里看到这句话：“XXL-JOB的每个调度任务虽然在调度模块是并行调度执行的，但是任务调度传递到任务模块的“执行器”确实串行执行的，同时支持任务终止。”， 意思是同一个执行器一次只能执行一个任务吗？ 如果我希望一台机器上有多个任务同时执行， 需要在这台机器上启动多个不同端口的执行器吗?

**Comment by xuxueli** [comment]
单个执行器可以并行运行多个任务的。

- XXL-JOB的不同任务之间并行调度、并行执行。
- XXL-JOB的单个任务，针对多个执行器是并行运行的，针对单个执行器是串行执行的。同时支持任务终止。
