### ISSUE TITLE
任务每次执行都启动新线程

### ISSUE THREAD

**Issue by Roronoa-Zoro** [xuxueli/xxl-job#2020]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
任务可以通过配置线程池执行
### Actual behavior
每次都启动新线程执行，测试环境跑了以后，线程号都到540了，可以配置任务执行线程池吗？
### Other information

**Comment by xuxueli** [comment]
你好，执行器每个任务只会占用1个线程，会自动覆盖销毁的。
