### ISSUE TITLE
内存缓慢增加,任务没有被释放?

### ISSUE THREAD

**Issue by zuohengfeng** [xuxueli/xxl-job#2022]
一个月时间内,任务有五个,时间间隔都是几分钟到几个小时不等,后台监控任务都是执行成功的,但是内存一直在缓慢增加,目前已经到4.5G了

**Comment by xuxueli** [comment]
你好，这里指的是调度中心还是执行器？

**Comment by zuohengfeng** [comment]
是调度中心

**Comment by zuohengfeng** [comment]
![image](https://user-images.githubusercontent.com/29425812/97379287-709d0d80-18ff-11eb-983b-efc19097e22f.png)

**Comment by xuxueli** [comment]
你好，问题无法复现，调度中心自身是个普通Springboot项目，可以dump内存分析内存占用内容，一起排查下。
如果有稳定复现步骤，可以提供。
