### ISSUE TITLE
Rancher 使用dcoker启动的时候，启动后，无法执行任务

### ISSUE THREAD

**Issue by poemp** [xuxueli/xxl-job#2024]
Please answer some questions before submitting your issue. Thanks!
使用spring-cloud整合进来之后，打包项目为docker镜像，使用rancker启动过后，handler可以注册到admin，但是，不能分发任务下去，找不到handler

**Comment by xuxueli** [comment]
你好，问题无法复现。“任务无法分发” 指的是任务调度失败吗？可以排查一下调度请求日志。

**Comment by poemp** [comment]
嗯嗯，知道问题在哪儿了，是因为rancher做docker镜像启动时候，使用的网络模式是“托管”，获取到的是docker镜像里面的网络ip，即注册到xxl-job-admin的是docker内网ip，admin在调用的时候是使用这个注册的ip调用的，所以调不起来。在处理rancher的时候，选择网络的主机就可以了。
![image](https://user-images.githubusercontent.com/15979497/97522288-6439b300-19da-11eb-8f91-aa8d5ea52ed9.png)
谢谢@xuxueli
