### ISSUE TITLE
部署在阿里云，阿里云报反序列化漏洞

### ISSUE THREAD

**Issue by BadSmile01** [xuxueli/xxl-job#2026]
详见：https://help.aliyun.com/noticelist/articleid/1060736995.html

请问这个漏洞如何修复

**Comment by xuxueli** [comment]
你好，上面文档已经给出解决方案（ 增加授权验证，配置 xxl.job.accessToken 即可防止未授权访问漏洞。 ）。

**Comment by popmedd** [comment]
@xuxueli 这个漏洞有最早出现的时间节点么，然否提供一下链接或详情

**Comment by xuxueli** [comment]
这个问题针对严格来说不属于漏洞，目前restful api借助gson实现反序列化，gson反序列化相对是安全的。

**Comment by shen7171** [comment]
不是啊，阿里云透露出的细节看是远程命令执行
    {
        "jobId":1,
        "executorHandler":"demoJobHandler",
        "executorParams":"demoJobHandler",
        "executorBlockStrategy":"COVER_EARLY",
        "executorTimeout":0,
        "logId":1,
        "logDateTime":1603937627000, 
        "glueType":"GLUE_SHELL",
        "glueSource":"touch /tmp/123.txt",
        "glueUpdatetime":1603937627000,
        "broadcastIndex":0,
        "broadcastTotal":0
    }

**Comment by xizhimen** [comment]
配置token也是缓解 没从根本上解决反序列化导致的命令执行

**Comment by xuxueli** [comment]
"漏洞" 声明：https://mp.weixin.qq.com/s/jzXIVrEl0vbjZxI4xlUm-g

该问题本质上不属于 “漏洞”，官网版本提供了鉴权组件，开启即可进行防护。

该问题类似于将一台Mysql、Redis实例，不设置密码并开放给公网，严格来说不能因此说Mysql、Redis有漏洞，只需要设置密码即可。

文章提供详细的安全防护策略。

**Comment by BadSmile01** [comment]
好的，感谢，有设置token，但是还提示，所以就觉得奇怪，后面忽略了
