### ISSUE TITLE
xxl-job 2.2.1 @XxlJob注解 无法与自定义注解进行组合使用问题

### ISSUE THREAD

**Issue by tan-zhuo** [xuxueli/xxl-job#2027]
使用过程中，在spring bean 类的方法上标注 XxlJob 注解之后可以正常调用，但如果想要在此方法上再加自己实现的其他注解时（基于spring aop），会发生调度中心无法调用到对应方法。并抛出异常 
![image](https://user-images.githubusercontent.com/32378959/97379349-8e6a7280-18ff-11eb-9875-fbb241d2582d.png)

![image](https://user-images.githubusercontent.com/32378959/97379081-e785d680-18fe-11eb-950a-451f2ecf4e8f.png)

无自定义注解时，spring bean 对象正常

![image](https://user-images.githubusercontent.com/32378959/97399065-4f501780-1927-11eb-9240-b43936ff3b6e.png)

有自定义注解时  spring bean  为 EnhancerBySpringCGLIB 的实例，从而导致异常。

![image](https://user-images.githubusercontent.com/32378959/97399201-9211ef80-1927-11eb-8667-7c23217b31b3.png)

**Comment by gogodjzhu** [comment]
这个不是xxl的问题，你Service加上了`@Component`注解导致它变成CGLIB代理类。 日志贴全一点，上面还没有包括异常信息。

**Comment by tan-zhuo** [comment]
你好，感谢你的回复。

我指明 @Component 注解是因为我需要 spring 代理来生效 aop 自定义多数据源事物 ( 并且@xxjob注解就是基于 spring bean ，所以此@Component 应当标注 ) , 并且在问题中已说明了是CGLIB代理类导致的错误。

日志信息中已经包含了错误信息：
![image](https://user-images.githubusercontent.com/32378959/98218590-e439bd00-1f86-11eb-9ee8-2bde00983c7d.png)

问题的原因：java.lang.IllegalArgumentException: object is not an instance of declaring class at sun.reflect.NativeMethodAccessorImpl.invoke0
