### ISSUE TITLE
xxl-rpc remoting error(no protocol: 172.20.2.120:9999/run), for url : 172.20.2.120:9999/run

### ISSUE THREAD

**Issue by lapqhg** [xuxueli/xxl-job#2033]
执行器部署在容器上，调用任务时使用“执行一次”都是成功的，但使用cron模式执行几次成功后就会一直失败。
可能原因是容器对于长连接有限制，长连接时间不能超过30s。请问这种情况该如何解决，谢谢。

**Comment by crow123** [comment]
请问是什么原因 怎么解决的
