### ISSUE TITLE
最近频繁出现调度阻塞了，发不出去请求

### ISSUE THREAD

**Issue by DDF-ZTT** [xuxueli/xxl-job#2038]
![image](https://user-images.githubusercontent.com/54521185/97767401-ca4b4500-1b56-11eb-9fa9-41c12621e53e.png)
您好，最近一直会出现如图的现象，某些任务调度一直卡起了。

**Comment by tomzhang170** [comment]
任务里自己去捕获异常，然后返回成功失败，msg里用简单的文字。
xxl-job全局捕获异常的地方有bug，exception的内容post到admin会出现无法转换成对象，于是每隔30s回调一次。

**Comment by 13619205479** [comment]
我遇到的是调度显示成功，执行器没看到任何日志，这个会是上述原因吗，不知道怎么排查
