### ISSUE TITLE
为啥看不到输出日志

### ISSUE THREAD

**Issue by maihc** [xuxueli/xxl-job#205]
Please answer some questions before submitting your issue. Thanks!
按照教程配置的java和bean模式，调度结果和执行结果成功了，但是执行日志Console里面看不到任何输出日志，为啥？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
任务需要通过自研Log组件打印才可以查看的到，可以参考示例JobHandler中的日志输出代码调整下。
