### ISSUE TITLE
事务相关问题

### ISSUE THREAD

**Issue by libraice** [xuxueli/xxl-job#206]
![default](https://user-images.githubusercontent.com/16081187/32206337-66972f24-be2f-11e7-9e7d-a892325094ae.png)大家有没有遇到过这个问题,已经设置了数据库事务隔离级别为
![1509426754 1](https://user-images.githubusercontent.com/16081187/32208387-34768c52-be3d-11e7-8701-07eeb3521f7a.jpg)但是还是在报错

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
这种情况无法复现，可以换一个默认配置的mysql实例重新部署尝试下，也可以文档中的交流群交流讨论啊。
