### ISSUE TITLE
支持springboot2.0 下docker部署数据库连接的问题

### ISSUE THREAD

**Issue by laziobird** [xuxueli/xxl-job#2065]
#1713 # Which version of XXL-JOB do you using?
V2.20
### Expected behavior
数据库配置 Docker 支持启动动态加载配置
### Actual behavior
数据库连接代码写死，注入环境变量是不能生效，详细见
https://github.com/xuxueli/xxl-job/blob/v2.2.0/xxl-job-admin/src/main/resources/application.properties
`
### xxl-job, datasource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root_pwd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
`
如果运行docker，传递系统变量，其实没有用
`
docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123456"  -p 8080:8080 -v /tmp:/data/applogs --name xxl-job-admin  -d xuxueli/xxl-job-admin:2.2.0
`
直接下源码，修改数据库配置，打成本地镜像，docker 启动正常访问

**Comment by yinlijun2004** [comment]
我也遇到一样的问题，找了很多方法，怎么都不能将docker-compose.yml里面的environment变量，覆盖application.properties里的参数，这么说官方的镜像就没有用了，只能自己编译。

**Comment by kayleyang** [comment]
我也遇到这样的问题，排查了原因，估计是因为通过PARAMS传参到启动命令上，会导致启动命令上的url被截掉，如果把url的value加上双引号，数据源又不认

**Comment by cesar-blog** [comment]
V2.3.1还没解决；

` environment:
      - spring.datasource.url=jdbc:mysql://building-mysql:3306/xxl-job?Unicode=true&characterEncoding=UTF-8&autoReconnect=true
      - spring.datasource.password=123456`

**Comment by xuxueli** [comment]
> ment: SPRING_DATASOURCE_URL: "jdbc:mysql://building-mysql:3306/xxl-job?Unicode=true&characterEncoding=UTF-8&autoReconnect=true" SPRING_

+1
