### ISSUE TITLE
Alibaba Java Coding Guidelines(P3C) Inspection Results

### ISSUE THREAD

**Issue by alieismy** [xuxueli/xxl-job#2066]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0-SNAPSHOT
### Expected behavior
IDEA中使用Alibaba Java Coding Guidelines插件代码扫描2.3.0-SNAPSHOT版本后，建议无Critical问题和部分Major问题
### Actual behavior
IDEA中使用Alibaba Java Coding Guidelines插件代码扫描2.3.0-SNAPSHOT版本后，有53个Critical问题，408个Major问题
### Steps to reproduce the behavior
建议作者用Alibaba Java Coding Guidelines插件扫描一下看看，尽可能减少代码的漏洞
### Other information
感谢作者提供的这个工具，另外，看到有新的工具PowerJob，看能否吸收一些，再次表示感谢。

**Comment by xuxueli** [comment]
感谢反馈，在陆续优化
