### ISSUE TITLE
发布定时执行一次的任务

### ISSUE THREAD

**Issue by libraice** [xuxueli/xxl-job#207]
现在能否创建一个天5点执行的任务，这个现在能否支持？

**Comment by qrqhuang** [comment]
是说每天5点？
这种cron表达式完全可以支持呀。
0 0 5 * * ?

**Comment by libraice** [comment]
@qrqhuang  前面没描述清楚，比如：创建一个明天只执行一次的定时任务

**Comment by wenqibo** [comment]
同问，有解决办法了吗

**Comment by littleeleplent** [comment]
同问，有解决办法了吗

**Comment by itliusir** [comment]
可以自己加个参数判断 如果是单次的执行完就删除

**Comment by liyangbing** [comment]
例如：0 0 0 13 5 ? 2018，仅在明天的0点执行一次

**Comment by xuxueli** [comment]
@libraice 你好，只运行一次的JOB，其实本质上是一个延迟消息。
这块推荐实用XXL-MQ来实现啊，支持自定义消息消费事件，重试次数等等。
