### ISSUE TITLE
官网失效不能访问能否处理下?

### ISSUE THREAD

**Issue by dbige** [xuxueli/xxl-job#2073]
官网 https://www.xuxueli.com/xxl-job/ 突然无法访问,
![image](https://user-images.githubusercontent.com/30175389/99327674-66927d00-28b5-11eb-8ee4-d2456cecf073.png)
应该不是我网络的问题,希望有空处理下!

**Comment by LockiJiang** [comment]
应该是你网络问题
![图片](https://user-images.githubusercontent.com/16129287/99340313-b88dcf80-28c2-11eb-8050-7cc512d01429.png)

**Comment by dbige** [comment]
好的好的,可能网络限制了,感谢!
