### ISSUE TITLE
XxlJobGroupMapper.xml 文件中 save 的insert sql里最后有个分号； 没有影响吗？

### ISSUE THREAD

**Issue by LiJianGuo123** [xuxueli/xxl-job#2085]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by ivanyunxian** [comment]
oracle肯定不行，mysql估计是可以支持分号的  ，我对mysql也不太熟悉

**Comment by LiJianGuo123** [comment]
谢谢，我用的Oracle，一直怀疑这种这个写法 笑哭 哭笑 笑出眼泪 破涕为笑 笑死 笑尿 笑cry

**Comment by LiJianGuo123** [comment]
Oracle有影响
