### ISSUE TITLE
执行器改变调度中心的自动注册或者数据库更新有点慢 每次需要几分钟才能知道哪个机器离线或者移除了

### ISSUE THREAD

**Issue by ivanyunxian** [xuxueli/xxl-job#2096]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by GavinCruise** [comment]
可以自行修改 RegistryConfig  中的默认心跳时间，时间设置太短时，注意对数据库的压力。

**Comment by ivanyunxian** [comment]
感谢
