### ISSUE TITLE
任务执行一段时间后客户端使用XxlJobLogger写入日志提示No such file

### ISSUE THREAD

**Issue by zhangyan54545** [xuxueli/xxl-job#2115]
Please answer some questions before submitting your issue. Thanks!

### Actual behavior: 

![image](https://user-images.githubusercontent.com/16732015/101277951-e34cb300-37f2-11eb-8c43-d45ab52b6dc7.png)

### Other information
输出日志的代码

```
 XxlJobLogger.log("分片参数：当前分片序号 = {}, 总分片数 = {}", shardIndex, shardTotal);
```

**Comment by zhangyan54545** [comment]
![image](https://user-images.githubusercontent.com/16732015/101277832-222e3900-37f2-11eb-99c9-368a4493c8dd.png)
这种情况是突然出现的，日志输出目录的读写权限也都有检查过

**Comment by zhangyan54545** [comment]
> Please answer some questions before submitting your issue. Thanks!
> 
> ### Which version of XXL-JOB do you using? 2.2.0
> ### Expected behavior: 日志正常写入
> ### Actual behavior:
> ![image](https://user-images.githubusercontent.com/16732015/101277951-e34cb300-37f2-11eb-8c43-d45ab52b6dc7.png)
> 
> ### Steps to reproduce the behavior
> ### Other information
> 输出日志的代码
> 
> ```
>  XxlJobLogger.log("分片参数：当前分片序号 = {}, 总分片数 = {}", shardIndex, shardTotal);
> ```

**Comment by yangcongcong007** [comment]
大佬 解决了吗

**Comment by ItBeeCoder2020** [comment]
服务日志里同样打印这样的报错信息，刚开始是一头雾水，不知道啥地方出问题了。不过后来在XXL-JOB的调度日志里看执行失败的日志，提示是书写的查询SQL问题，改了SQL之后，定时任务的开头和结束仍旧会报这个错，不过不影响定时任务的执行了。遇到同样问题的小伙伴们可以去看下xxl-job里的报错日志。

**Comment by gttoi** [comment]
我也碰到这个问题了，请问大佬问题解决了吗

**Comment by hei-ying** [comment]
同样碰到了这个问题

**Comment by xuxueli** [comment]
抱歉，问题无法复线。需要进一步提供详细复现操作步骤。

**Comment by caifenghua** [comment]
也是碰到了这个问题

**Comment by lmx1989219** [comment]
是不是在jobhandler里面用了线程池？

**Comment by RoyalJJ** [comment]
> 



> 是不是在jobhandler里面用了线程池？线程池里面打印日志出现的错误？



> 是不是在jobhandler里面用了线程池？线程池里面打印日志出现的错误？

看来我跟你的情况是一样的

**Comment by meowworld** [comment]
> > 
> 
> > 是不是在jobhandler里面用了线程池？线程池里面打印日志出现的错误？
> 
> > 是不是在jobhandler里面用了线程池？线程池里面打印日志出现的错误？
> 
> 看来我跟你的情况是一样的

怎么解决的呢，我也是docker中部署，jobhandler使用线程池
