### ISSUE TITLE
2.2.0版本在创建定时任务时包数据库表缺少t.job_cron

### ISSUE THREAD

**Issue by liaojunhui** [xuxueli/xxl-job#2116]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Wang-if** [comment]
我也遇到了，请问解决了吗

**Comment by Tennyson365** [comment]
所以这个问题还是没有解决？

**Comment by liaojunhui** [comment]
解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuxueli/xxl-job"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 中午11:39
收件人:&nbsp;"xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;;
抄送:&nbsp;"廖俊辉"<junhui.liao@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 2.2.0版本在创建定时任务时包数据库表缺少t.job_cron (#2116)





 
所以这个问题还是没有解决？

**Comment by Tennyson365** [comment]
> 所以这个问题还是没有解决？

docker hub上的镜像还是没有解决的
我现在是自己打jar包，自己构建镜像才不会报错。
镜像的jar包是基于2.2的

**Comment by xuxueli** [comment]
新版本已优化，建议升级。
