### ISSUE TITLE
2.3.0-SNAPSHOT版本添加任务，状态永远是STOP

### ISSUE THREAD

**Issue by yangxiufeng666** [xuxueli/xxl-job#2144]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0-SNAPSHOT
### Expected behavior

![image](https://user-images.githubusercontent.com/6647574/102598714-648f3880-4157-11eb-9850-e8d7b0b86487.png)

**Comment by carl-don-it** [comment]
请问怎么解决
