### ISSUE TITLE
多DB多实例支持

### ISSUE THREAD

**Issue by lichaoxi** [xuxueli/xxl-job#2157]
项目中使用了100台服务器，大概10台服务器一个DB，目前想接入xxl-job，提高定时任务服务器的使用率（目前项目定时任务使用乐观锁，机器使用率太低，冲突过高），不知道xxl-job支持这种处理吗？

**Comment by hellosnowy** [comment]
把数据库乐观锁那一块改成用redis锁机制能解决你的冲突问题

**Comment by xuxueli** [comment]
> 把数据库乐观锁那一块改成用redis锁机制能解决你的冲突问题

+1
