### ISSUE TITLE
xxl-job在半夜有默认操作吗？执行器半夜出现 “结果丢失问题”白天没有

### ISSUE THREAD

**Issue by renanmin** [xuxueli/xxl-job#2167]
![image](https://user-images.githubusercontent.com/33210633/103324214-7a6afa80-4a81-11eb-8d01-69c13bd597c7.png)

1.执行结果是  “失败”，信息为：“任务结果丢失，标记失败”
2.查看日志发现调度其实是执行成功了的
3.猜想是半夜有默认调度之类的地方

**Comment by winshu** [comment]
xxl-job 有个“任务调试丢失监控线程”，会自动扫描**同时满足**以下两个条件的任务，更新为“任务结果丢失，标记失败”：
1. 调度记录停留在 "运行中" 状态超过10min
2. 对应执行器心跳注册失败不在线

从截图可以看到，你的任务执行时间是超过10分钟的，那么，你要做的就是检查一下，当前任务的执行器地址是否在执行器注册地址列表中，也就是说你调度任务的执行器可能掉线了，或者ip变了

可以去阅读这个类的源码  JobLosedMonitorHelper

**Comment by donxak** [comment]
请问这个问题应该怎么解决啊，我这里的这个任务目前肯定是会超过10分钟的，结果丢失就不调用子任务，，，

**Comment by fddc** [comment]
> 请问这个问题应该怎么解决啊，我这里的这个任务目前肯定是会超过10分钟的，结果丢失就不调用子任务，，，

检查xxl_job_log的执行器地址跟你注册的执行器地址是否一致

**Comment by guixiong** [comment]
修改了monitorThread程序里的10min也无效，仍然有程序到了10分钟去修改了
