### ISSUE TITLE
报job thread is running or has trigger queue错误。

### ISSUE THREAD

**Issue by ContinueCoding** [xuxueli/xxl-job#2168]
Please answer some questions before submitting your issue. Thanks!

### Other information
配置了一个每2分钟执行一次的定时任务，任务内容是通过http请求获取接口的数据，然后保存在数据库中。启动之后，前几天的调度是没问题的，调度结果和执行结果都是成功的，过了几天之后就一直失败，调度备注如图所示（报500，job thread is running or has trigger queue错误）。
![image](https://user-images.githubusercontent.com/11802591/103325196-aab49800-4a85-11eb-851b-475f4e1e019b.png)

P.S. 同时还有其他定时任务，但是只有这个任务失败，其他任务都没问题，失败后重新部署服务器就正常了，过一段时间又会出现调度失败的错误。

**Comment by MHYJ** [comment]
可能你这个是个耗时任务，单机服务，阻塞策略设置为“单机串行”，第一次任务处于忙碌（超10min）,下次执行时，任务还处于忙碌状态，后面就会连续失败，阻塞策略修改下试试

**Comment by ContinueCoding** [comment]
> 可能你这个是个耗时任务，单机服务，阻塞策略设置为“单机串行”，第一次任务处于忙碌（超10min）,下次执行时，任务还处于忙碌状态，后面就会连续失败，阻塞策略修改下试试

谢谢！已经修改为5分钟执行一次，阻塞策略改为“覆盖之前调度”，再观察观察。

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
