### ISSUE TITLE
关于终止任务的困惑

### ISSUE THREAD

**Issue by lcyan** [xuxueli/xxl-job#217]
我的一个demoJobHandler里面开起了一堆线程跑业务

那么我在调度平台点终止任务，实际上是不会终止任务中开起的这堆线程呢？

有什么好的解决办法吗？

**Comment by xuxueli** [comment]
你好，感谢关注！
任务终止时，将会在任务Handler逻辑中触发中断异常，因此可以通过捕获该中断异常来主动销毁自己创建的线程。
同时，已经将本建议加入TODO列表 （JobHandler提供 init/destroy 方法，支持自定义任务线程销毁逻辑），将会排期上线。

**Comment by xuxueli** [comment]
你好，最新版本已经支持该特性，JobHandler提供 init/destroy 方法，支持自定义任务线程销毁逻辑。
