### ISSUE TITLE
c.x.job.core.executor.XxlJobExecutor - null

### ISSUE THREAD

**Issue by LiuHuanabc** [xuxueli/xxl-job#2190]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
正常启动
### Actual behavior
报错
### Other information

**Comment by LiuHuanabc** [comment]
![image](https://user-images.githubusercontent.com/48168455/103964989-b0059700-5197-11eb-80d1-28a0f2d8f5cd.png)
![image](https://user-images.githubusercontent.com/48168455/103965002-ba279580-5197-11eb-9c5f-e68a5f6f5666.png)
![image](https://user-images.githubusercontent.com/48168455/103965016-c14ea380-5197-11eb-8e54-d12f09d9c4d8.png)

**Comment by LiuHuanabc** [comment]
![image](https://user-images.githubusercontent.com/48168455/103965081-ecd18e00-5197-11eb-89d4-bbe32bfcca21.png)

**Comment by dengjiexiao** [comment]
你怎么解决这个问题呢？

**Comment by dengjiexiao** [comment]
@LiuHuanabc

**Comment by LiuHuanabc** [comment]
查看了一下源码之后 方法的返回值不要用void 使用TReturn<T&gt;这种类型的就可以了
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "邓杰"; 
Date: 2021年9月23日(星期四) 晚上8:48
To: "xuxueli/xxl-job"; 
Cc: "LiuHuan"; "State change"; 
Subject: Re: [xuxueli/xxl-job] c.x.job.core.executor.XxlJobExecutor - null (#2190)

&nbsp;


 
你怎么解决这个问题呢？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
