### ISSUE TITLE
你好，我的机器上跑了XXL-JOB服务，有时会自动挂掉，不知道是什么原因呢

### ISSUE THREAD

**Issue by orclcast** [xuxueli/xxl-job#220]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，感谢关注！
这种情况暂时无法重现，可以分析下项目停之前的Log或者监控下应用和机器情况。建议加入文档中的交流群进行沟通分析哈。
