### ISSUE TITLE
GlueJobHandler can not exec init(),destroy()

### ISSUE THREAD

**Issue by majinding** [xuxueli/xxl-job#2210]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
before 2.2.0 
### Expected behavior
 GlueJobHandler init(),destroy() would be run
### Actual behavior
GlueJobHandler init(),destroy()  was not work
### Steps to reproduce the behavior
glue jobs
### Other information

**Comment by xuxueli** [comment]
感谢反馈！
相关PR已经合并至master分支，将会跟随下个版本近期发布。
