### ISSUE TITLE
从1.8.2升级到最新版，数据库表不一致，数据怎么导入？？

### ISSUE THREAD

**Issue by skyjilygao** [xuxueli/xxl-job#2212]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.2
### Expected behavior
发现1.8.2使用数据库表跟v2.3.0的数据库表完全不同，那1.8.2的数据怎么导入到新版里的？？
主要是执行器和任务数据
### Other information

**Comment by GavinCruise** [comment]
官方并未提供升级指引，参考 https://github.com/xuxueli/xxl-job/issues/1038 和 https://github.com/xuxueli/xxl-job/issues/1566 

根据新旧表结构变化，新任务表（xxl_job_info）相比原任务表（XXL_JOB_QRTZ_TRIGGER_INFO）新增了三个字段，其他字段均相同，可以直接迁移，并修改表编码为 utf8mb4

但是需要注意，最新版本和旧版本区别较大，底层也有修改，注意兼容问题。

**Comment by xuxueli** [comment]
> 旧表结构变化，新任务表（xxl_job_info）相比原任务表（XXL_JOB_QRTZ_TRIGGER_INFO）新增了三个字段，其他字段均相同，可以直接迁移，并修改表编码为 ut

+1
