### ISSUE TITLE
xxl.job.executor.logpath设置路径如果不是以/结尾执行任务路径错误

### ISSUE THREAD

**Issue by xbeginagain** [xuxueli/xxl-job#222]
执行器设置参数
xxl.job.executor.logpath=/Users/xuzp/Documents/xxlog
路径不以/结尾时
-日志正常记录
-gule python 文件正常创建
但执行任务时找不到目录
看错误是会在上面xxlog目录名称后直接拼Python存储目录gluesource 
/Users/xuzp/Documents/xxloggluesource

**Comment by xbeginagain** [comment]
建议加不加/都可以

**Comment by xuxueli** [comment]
你好，感谢支持和反馈！
已经将本建议加入TODO列表 （执行器回调地址/日志地址格式兼容，是否已"/"结尾均支持），将会排期上线。
