### ISSUE TITLE
SQL慢查询脚本问题

### ISSUE THREAD

**Issue by hjjoe1213123** [xuxueli/xxl-job#2234]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Expected behavior
不应该有长达10分钟的慢查询SQL
### Actual behavior
长达10分钟的慢查询SQL
### Steps to reproduce the behavior
SELECT t.id FROM xxl_job_log AS t WHERE t.trigger_code = 200 and t.handle_code = 0 and t.trigger_time <= '2021-02-02 14:33:20.22' and t.executor_address not in ( SELECT t2.registry_value FROM xxl_job_registry AS t2 )
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈，相关PR已经合并至master分之，将会近期发布。

针对日志表大表问题，建议开启调度中心日志自动清理功能，定期处理过期日志数据。
