### ISSUE TITLE
稳定性问题

### ISSUE THREAD

**Issue by Baivin** [xuxueli/xxl-job#224]
版本：1.8.1

1、请问一下，随着接入的系统增加，能保持一个稳定性吗？  

2：还有一些情况就是发现每天会有一些执行记录是显示终止任务，这个是因为请求客户端执行超时未返回状态码导致的吗？ 这种情况究竟执行了没有， 执行情况如何，好像是不确定的？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
1、调度中心支持集群部署实现HA，目前已经接入数十家公司均稳定运行，部分已知集群以调度超过百万次可以放心接入，如有问题可以加群讨论交流。
2、显示 “终止任务” 是因为执行器没有回调通知任务执行结果导致，可以排查下执行器回调Log是否回调异常（可能网络波动导致，针对失败的回调请求的后续已经排期优化为写文件记录并重试，从而提高回回调成功率），这种情况任务是否执行，可以根据Rolling Log来判断，其中记录了任务执行的完成过程，包括入参，逻辑流程日志，执行结果等信息。
