### ISSUE TITLE
2.3.0不兼容升级，任务核心类 “IJobHandler” 的 “execute” 方法取消出入参设计

### ISSUE THREAD

**Issue by yuanhaoliang** [xuxueli/xxl-job#2250]
首先，喜大普奔，xxl-job终于更新了！
但是！

https://www.xuxueli.com/xxl-job/#7.31%20%E7%89%88%E6%9C%AC%20v2.3.0%20Release%20Notes[2021-02-09]
4、【优化】任务核心类 “IJobHandler” 的 “execute” 方法取消出入参设计。改为通过 “XxlJobHelper.getJobParam” 获取任务参数并替代方法入参，通过 “XxlJobHelper.handleSuccess/handleFail” 设置任务结果并替代方法出参，示例代码如下；
```
@XxlJob("demoJobHandler")
public void execute() {
String param = XxlJobHelper.getJobParam();    // 获取参数
XxlJobHelper.handleSuccess();                 // 设置任务结果
}
```

这个设计导致跟旧版不兼容更新的吧？太坑了吧？

**Comment by xuxueli** [comment]
感谢反馈，项目维护组接受批评。

首先提到 v2.2.x 版本，经过半年多的社区线上考验，功能相对稳定，如果对新版本特性没有强烈诉求，暂时仍可以使用现有 v2.2.x 大版本，大版本升级可以缓慢进行。

针对本次Release的 v2.3.0 版本，由于是大版本升级，迭代特性和优化项众多，从稳定性和可维护性两方面考虑，不能保证 100% 兼容性，带来不便再次道歉。

针对 v2.3.0 大版本升级，存在以下几种方案：
1、出入参逻辑替换【推荐】：一步到位，将任务入参取值和结果赋值逻辑替换为新版方案。新版方案逻辑更加清晰，有一定工作量，但是相对较小。
2、执行期定制：针对执行期 JobThread Line137 开始的任务执行的代码块进行定制，参考 v2.2.0 低版本，将出入参处理逻辑回退即可。

**Comment by xiaoxiangzhenyu** [comment]
这种不兼容的处理方式，实在是太不友好了！ 
从2.2.0升级上来，凡是有传参的任务，对应业务都得发版升级！
另外所有任务触发完成后，都处于了一个『执行中』的状态，直到超时后全都变成了失败状态！

----------
建议能提供下兼容的方案，方便旧用户逐步的过度到新版本上来！

**Comment by xiaoxiangzhenyu** [comment]
这种不兼容的处理方式，实在是太不友好了！ 
从2.2.0升级上来，凡是有传参的任务，对应业务都得发版升级！
另外所有任务触发完成后，都处于了一个『执行中』的状态，直到超时后全都变成了失败状态！

----------
建议能提供下兼容的方案，方便旧用户逐步的过度到新版本上来！

**Comment by linminqin** [comment]
数据库表结构也变了吧，有没有sql升级脚本，这样真的很不友好！

**Comment by xiaoyu830411** [comment]
感觉特别不专业，这个2.3.0升级。API都是可以先兼容一段时间，声明为  @Deprecated， 然后在某个大版本（3.0）再不兼容。
或者干脆开两个分支，一个是3.0，一个是2.x，这样也好。

**Comment by novayoung** [comment]
心塞，有1000+定时任务怎么办？
