### ISSUE TITLE
xxl.job.admin.addresses配置多个管理地址时存在数据库死锁问题

### ISSUE THREAD

**Issue by zrlw** [xuxueli/xxl-job#2256]
### Which version of XXL-JOB do you using?
2.3.0以及之前的版本

### Expected behavior
正常运行

### Actual behavior
xxl-job-registry没有唯一索引，各台xxljob管理实例同时注册重复插入多条记录（update的时候均返回0，save操作各自插入1条）
后续做update的时候，由于数据库执行计划不能保证update重复记录顺序一致，导致死锁。

### Steps to reproduce the behavior
xxl.job.admin.addresses=ip1,ip2,ip3.... （集群模式，访问同一个数据库）

### Other information
1. 建议在表上加唯一索引，保证registry_group，registry_key,registry_value唯一性；
2. update失败再save这样的处理逻辑不支持并发，多个线程同时执行存在并发问题。

**Comment by xuxueli** [comment]
感谢反馈，进一步优化代码已推送master分支，后续随新版本发布。
