### ISSUE TITLE
版本2.3.0任务重复执行的问题

### ISSUE THREAD

**Issue by andyliuxu** [xuxueli/xxl-job#2268]
### 问题描述
使用springboot-2.3.2集成xxl-job-2.3.0 配置一个定时任务，让其每十分钟执行，结果没十分钟有大量的重复执行，请问是我配置有误，还是有我没有注意到的细节，请指教。下面贴出配置和代码：
### 1.任务管理配置
![TQOFFDMG2XT1O N$H5A R3V](https://user-images.githubusercontent.com/76504040/108789864-36dec980-75b6-11eb-8439-a63feb6a5cb1.png)
### 2.代码
![@JT}UBXI8WDL N5B5UJ%E4R](https://user-images.githubusercontent.com/76504040/108789917-5ece2d00-75b6-11eb-8d91-9d62b7195765.png)
### 3. 执行结果
  
![LAP9JPYHP@L4JO50CLNK4)B](https://user-images.githubusercontent.com/76504040/108789975-845b3680-75b6-11eb-869d-d656c50572e9.png)

**Comment by superlbmen** [comment]
看着像是cron表达式配置的一秒钟执行一次。
你可以再把日志截图贴上来。
调度器每次调度都会记录一条日志。

**Comment by andyliuxu** [comment]
### 问题描述
  我检查了数据库中的cron表达式是正确配置的，我不明白是怎样会出现这种情况
### 调度日志
![9PGYXQ3JV4_ U98LDDQ$5J](https://user-images.githubusercontent.com/76504040/108814511-e71bf480-75ed-11eb-981d-858330a5c8c9.png)
###  详情
![6UN5 7_BV6NR7@4FT7O$1C](https://user-images.githubusercontent.com/76504040/108814603-0d419480-75ee-11eb-815b-1ae100e55c5c.png)
### 数据库表信息
![FWLJ3`E80WMJIICFKT)(7MG](https://user-images.githubusercontent.com/76504040/108814801-63163c80-75ee-11eb-9cec-4dd940ef77ff.png)

**Comment by andyliuxu** [comment]
> ### 问题描述
> 我检查了数据库中的cron表达式是正确配置的，我不明白是怎样会出现这种情况
> 
> ### 调度日志
> ![9PGYXQ3JV4_ U98LDDQ$5J](https://user-images.githubusercontent.com/76504040/108814511-e71bf480-75ed-11eb-981d-858330a5c8c9.png)
> 
> ### 详情
> ![6UN5 7_BV6NR7@4FT7O$1C](https://user-images.githubusercontent.com/76504040/108814603-0d419480-75ee-11eb-815b-1ae100e55c5c.png)
> 
> ### 数据库表信息
> ![FWLJ3`E80WMJIICFKT)(7MG](https://user-images.githubusercontent.com/76504040/108814801-63163c80-75ee-11eb-9cec-4dd940ef77ff.png)


### 补充
通过任务管理 点击 操作——>执行一次。定时任务是正常执行一次的，但是每当到达触发时间时，就会重复执行多次

**Comment by Mihawk-lf** [comment]
0 0/10 * * * ?
这是十分钟执行一次，正确的cron表达式

**Comment by perryDavid** [comment]
同问，我这边也出现了相关问题。

**Comment by andyliuxu** [comment]
> 0 0/10 * * * ?
> 这是十分钟执行一次，正确的cron表达式。
> 你配置的cron表达式就是1s执行一次。

### 很感谢您的热心解答，但是希望您回复时能够深思熟虑，再次感谢您的解答

**Comment by wzshuang** [comment]
为啥关掉了，我这边也遇到了，是什么原因，怎么解决呢
