### ISSUE TITLE
线上环境的log文件占用内存过大，占用cpu也太多（50%）左右。各位大佬都咋解决的呀？

### ISSUE THREAD

**Issue by Samwellwang** [xuxueli/xxl-job#2295]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Mihawk-lf** [comment]
你单机什么配置，单机跑了多少任务，理论上是不会有的哇。
是不是也有别的功能在写日志哇，CPU占50%，你可以顺道看下IO大小，进一步确认下是否是日志影响的。
如果是日志，你整个应用程序应该有大量的线程在并发写日志，并且同时刻写了很多的日志文件。

**Comment by Mihawk-lf** [comment]
你单机什么配置，单机跑了多少任务，理论上是不会有的哇。
是不是也有别的功能在写日志哇，CPU占50%，你可以顺道看下IO大小，进一步确认下是否是日志影响的。
如果是日志，你整个应用程序应该有大量的线程在并发写日志，并且同时刻写了很多的日志文件。

**Comment by Samwellwang** [comment]
> 你单机什么配置，单机跑了多少任务，理论上是不会有的哇。
> 是不是也有别的功能在写日志哇，CPU占50%，你可以顺道看下IO大小，进一步确认下是否是日志影响的。
> 如果是日志，你整个应用程序应该有大量的线程在并发写日志，并且同时刻写了很多的日志文件。

好的，感谢。刚看了下IO很小，CPU也是小了。应该是其他原因引起了。我再排查排查，再次感谢哈
