### ISSUE TITLE
调度中心 RESTful API的扩展

### ISSUE THREAD

**Issue by YaoZhangJoel** [xuxueli/xxl-job#2305]
![image](https://user-images.githubusercontent.com/47650262/110298540-aaa9b900-802f-11eb-9860-dbf3a2f5a900.png)
当前只能直接调用执行器执行job，不能通过调度中心执行job。
页面可以手动执行任务，无法通过api->调度中心->执行器 这样调用

**Comment by Mihawk-lf** [comment]
Request URL: http://localhost:8080/xxl-job-admin/jobinfo/trigger
这个接口就可以哇，本来就是REST接口，你用程序请求也可以哇。

**Comment by yanghui-git** [comment]
你f12模仿操作不就行了

**Comment by YaoZhangJoel** [comment]
> Request URL: http://localhost:8080/xxl-job-admin/jobinfo/trigger
> 这个接口就可以哇，本来就是REST接口，你用程序请求也可以哇。

之前是调用/job-admin/jobinfo/trigger接口触发job，trigger接口@PermissionLimit拦截，需要登录cookie调用。
已扩展JobApiController添加接口通过XXL-JOB-ACCESS-TOKEN调用。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/2671
