### ISSUE TITLE
H2Miner挖矿木马利用XXL-JOB未授权命令执行漏洞攻击云主机

### ISSUE THREAD

**Issue by lwsbox** [xuxueli/xxl-job#2319]
https://www.gdcert.com.cn/KeyIntelligence/detail/Vl5DWA

执行器没有做http验证导致的吧

**Comment by shinestmt** [comment]
设置 accessToken 用于验证
更重要的是, 请勿将不必要的端口开放到公网, 这一点尤为重要, 且并不限于 xxl-job, 应该为常识

**Comment by xuxueli** [comment]
> 设置 accessToken 用于验证 更重要的是, 请勿将不必要的端口开放到公网, 这一点尤为重要, 且并不限于 xxl-job, 应该为常识


+1，生产环境建议启用通讯 accessToken提升安全性。
