### ISSUE TITLE
固定延时触发如何使用

### ISSUE THREAD

**Issue by yihuiluo235** [xuxueli/xxl-job#2324]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3版本
### Expected behavior
想使用固定延时触发，该功能是否已经开发完成，如果已具备，该如何使用，没有看到具体的；
使用2.3版本，没有看到可配置的项
### Other information

**Comment by GlowBlur** [comment]
我的理解是固定的秒数，单位为毫秒，例如固定10秒执行一次应配置10000，我的理解，有待验证

**Comment by yihuiluo235** [comment]
> 我的理解是固定的秒数，单位为毫秒，例如固定10秒执行一次应配置10000，我的理解，有待验证

这个了解，只是界面上没看到可以配置的项
![image](https://user-images.githubusercontent.com/2733701/111070607-7b9eb600-850d-11eb-993e-913d2ecf433d.png)

**Comment by GlowBlur** [comment]
2.3版本有个选项是Cron还是固定

**Comment by wangzgBoom** [comment]
目前只有固定频率，没有固定延时

**Comment by yihuiluo235** [comment]
> 目前只有固定频率，没有固定延时
好的，谢谢，我也看到更新文档了
