### ISSUE TITLE
建议任务管理列表，添加最近调度时间、最近执行状态、下一次调度时间 列

### ISSUE THREAD

**Issue by 1990hjp** [xuxueli/xxl-job#233]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
任务列表字段太多会影响操作体验，不过我们会跟进探讨，可以加入文档中交流群一起讨论方案啊。

**Comment by i5possible** [comment]
最近调度时间、最近执行状态、下一次调度时间 确实是定时任务比较关心的内容
