### ISSUE TITLE
admin自动获取ip问题

### ISSUE THREAD

**Issue by tainyuxue** [xuxueli/xxl-job#2336]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
获取执行器本机ip
### Actual behavior
获取到了虚拟网卡的ip

执行器自动注册，ip显示为虚拟网卡的ip，导致调不同。

**Comment by Mihawk-lf** [comment]
虚网ip，怎么就调不通了那？有网络限制？
是什么网络环境那，docker还是虚机。

**Comment by surkuang** [comment]
> 
> 
> 虚网ip，怎么就调不通了那？有网络限制？
> 是什么网络环境那，docker还是虚机。

在局域网中的另一台主机启动一个executor，那台主机中装有vm虚拟机，然后通过自动注册的方式。在admin中显示ip为那台主机的VMware Network Adapter VMnet8网卡ip。 任务调用时失败，错误500.
