### ISSUE TITLE
client 端能否剔除当前注册的 ip ?

### ISSUE THREAD

**Issue by judasnow** [xuxueli/xxl-job#2337]
client 端能否剔除当前注册的 ip ?

### Which version of XXL-JOB do you using?
v2.0.2

### Expected behavior
client 剔除当前注册的 ip ?

### Other information

**Comment by Mihawk-lf** [comment]
某个clint不执行？

**Comment by jianghebo** [comment]
> 某个clint不执行？

不是，就是在做优雅停机的时候希望 在tomcat 延迟关闭这个期间，自动注册的这个client 不在接收job任务来执行，我的想法就是直接在client 关闭时把当前client 应用ip从执行器里面删掉 ，即使轮训策略也不会再到这个ip上执行任务了

**Comment by Mihawk-lf** [comment]
> 轮

应用程序关闭的时候，会执行一个销毁函数，哪里面做了这个处理了。不过你要是kill -9的话，那就没办法生效了。
可以做个类似平滑发布的脚本，在kill前，手动调用下接口把这个client下掉。

**Comment by jianghebo** [comment]
> > 轮
> 
> 应用程序关闭的时候，会执行一个销毁函数，哪里面做了这个处理了。不过你要是kill -9的话，那就没办法生效了。
> 可以做个类似平滑发布的脚本，在kill前，手动调用下接口把这个client下掉。

我刚才在源码中找到了这个 destroy() 在 XxlJobExecutor 中，，试了下，好像是可以生效的， 当前实例已经不再接收job任务执行了

**Comment by jianghebo** [comment]
> > > 轮
> > 
> > 
> > 应用程序关闭的时候，会执行一个销毁函数，哪里面做了这个处理了。不过你要是kill -9的话，那就没办法生效了。
> > 可以做个类似平滑发布的脚本，在kill前，手动调用下接口把这个client下掉。
> 
> 我刚才在源码中找到了这个 destroy() 在 XxlJobExecutor 中，，试了下，好像是可以生效的， 当前实例已经不再接收job任务执行了

不对，好像还是有问题出现了rpc 调用问题

### 
![job](https://user-images.githubusercontent.com/17865919/111563585-2f849780-87d3-11eb-96dc-3e16e56c9f6e.png)

**Comment by judasnow** [comment]
thx
