### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by liuchunchiuse** [xuxueli/xxl-job#2338]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3最新版本

执行任务的时候报错:
`java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: wrong number of arguments at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:206) at com.uhome.job.core.thread.JobThread.run(JobThread.java:150) Caused by: java.lang.IllegalArgumentException: wrong number of arguments at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.uhome.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:27) at com.uhome.job.core.thread.JobThread$1.call(JobThread.java:143) at com.uhome.job.core.thread.JobThread$1.call(JobThread.java:136) at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) at java.util.concurrent.FutureTask.run(FutureTask.java) at java.lang.Thread.run(Thread.java:748)`

**Comment by Mihawk-lf** [comment]
呃呃呃呃。。你提供下你的任务配置撒，这明显的参数类型错误哇。。

**Comment by liuchunchiuse** [comment]
> 呃呃呃呃。。你提供下你的任务配置撒，这明显的参数类型错误哇。。

![Uploading image.png…]()

**Comment by liuchunchiuse** [comment]
![image](https://user-images.githubusercontent.com/26759830/111568437-b5a4dc00-87db-11eb-8238-bd59e997e69a.png)

**Comment by liuchunchiuse** [comment]
找到了,对于升级的小伙伴要注意了,hander接收参数以前可以放在方法里面现在改成treadLocal里面了,方法体不要写任何参数,否则就是报上面的错,现在获取参数方法改为 String param = XxlJobHelper.getJobParam();折磨了两天,建议任何升级都先看一下demo
