### ISSUE TITLE
调度日志是成功的, 但折线图和饼图的统计都是失败的

### ISSUE THREAD

**Issue by slowlog** [xuxueli/xxl-job#234]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
- Powered by XXL-JOB 1.8.2（快照版本）

### Desc
调度任务实际是执行成功的,但是统计的结果却好像反了,请问这是什么原因,
强迫症又犯了

如下图所示:

![default](https://user-images.githubusercontent.com/16852041/33813607-cb37cdee-de5f-11e7-968f-44f07fb8eb2f.png)

**Comment by xuxueli** [comment]
你好，任务包括“调度 + 执行”两个过程，任务报表统计的是任务的“执行”状态，可以确认下数据是否一致啊。

**Comment by utopro** [comment]
请问哪个版本有调度报表？

**Comment by xuxueli** [comment]
你好，最新release版本针对该问题做了优化，已经将 “运行中” 与 “失败” 状态拆分开，可以升级查看下哈！
