### ISSUE TITLE
是否有1.9.2迁移到2.3.0比较好的方案

### ISSUE THREAD

**Issue by junewool** [xuxueli/xxl-job#2344]
目前使用的版本是1.9.2，目前线上几千的任务在跑，想要升级到2.3.0，发现数据库结构和数量都变化好大，有没有平滑迁移的方案

**Comment by Inphoo** [comment]
同求，目前是1.9.3

**Comment by DeepSeaCat** [comment]
你们升级了吗？  有没有具体的方案

**Comment by DeepSeaCat** [comment]
> 使用的用途是.2，目前的方案1.9目前的任务在跑，想要升级到数据库2.3.3.3.，发现结构和数量变化好大，有不同版本的变化

你们已经升级完成了吗？ 有具体的升级方案吗？

**Comment by junewool** [comment]
> > 使用的用途是.2，目前的方案1.9目前的任务在跑，想要升级到数据库2.3.3.3.，发现结构和数量变化好大，有不同版本的变化
> 
> 你们已经升级完成了吗？ 有具体的升级方案吗？

就看了下数据库，按照新版本的数据库结构迁移group跟info表，register表非自动注册的也需要迁移一下

**Comment by firmament2008** [comment]
# 新表名 xxl_job_group
select id ,app_name, `title` from xxl_job_qrtz_trigger_group
;
;
#新表名 xxl_job_info
select 
i.job_group  ,
i.job_cron as schedule_conf  ,
i.job_desc as job_desc  ,
i.add_time as add_time  ,
i.update_time as update_time  ,
i.author as author  ,
i.alarm_email as alarm_email  ,
i.executor_route_strategy as executor_route_strategy  ,
i.executor_handler as executor_handler  ,
i.executor_param as executor_param  ,
i.executor_block_strategy as executor_block_strategy  ,
i.executor_timeout as executor_timeout  ,
i.glue_type as glue_type  ,
i.glue_source as glue_source  ,
i.glue_remark as glue_remark  ,
i.glue_updatetime as glue_updatetime  ,
i.child_jobid as child_jobid   ,
case when t.TRIGGER_STATE in ("ACQUIRED","WAITING") then 1
else 0 
end as trigger_status

from xxl_job_qrtz_triggers t join xxl_job_qrtz_trigger_info i on t.TRIGGER_NAME = i.id
