### ISSUE TITLE
建议：执行器能移除停用的机子

### ISSUE THREAD

**Issue by kevinKaiF** [xuxueli/xxl-job#236]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.0
### Expected behavior
同一个执行器会注册多个机子，当有个机子停用掉后希望能移除
### Actual behavior
同一个执行器会注册多个机子，没法移除

**Comment by xuxueli** [comment]
你好，执行器集群情况下，机器如果连续3次心跳失败会被自动移除的（仅限于自动注册）。请确认下注册类型是否自动注册，然后等待3次心跳周期之后确认下是否下线。
而且，如若启用故障转移路由策略，将会自动忽略下线机器的啊。
