### ISSUE TITLE
老哥，为何不能在文档中restapi栏目增加动态创建（删除）任务的相关接口呢？

### ISSUE THREAD

**Issue by aaronuu** [xuxueli/xxl-job#2361]
老哥，为何不能在文档中restapi栏目增加动态创建（删除）任务的相关接口呢？

**Comment by mj19910923** [comment]
相比手动任务动态任务更常用一些

**Comment by lingfengfa** [comment]
迫切需要通过api的方式，动态的添加任务哈

**Comment by abiao-hub** [comment]
可以代码里调用调度中心的任务增删改查接口，接口放行或者登录后访问

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/2671
