### ISSUE TITLE
轮询策略问题(伪轮询)

### ISSUE THREAD

**Issue by lwsbox** [xuxueli/xxl-job#2366]
版本2.2.0
当前是直接在调度中心缓存一个map记录每个jobId当前轮询的count
但是在部署两个调度中心的时候,这个map是非共享的,在他们抢占调度的时候无法保证轮询的有序性

**Comment by liaomengge** [comment]
这个的轮询是在一批次（默认：6000）轮询的，而不是每次调度都是轮询的，其他策略也是一样的

**Comment by lwsbox** [comment]
批次是什么概念？

**Comment by xfworld** [comment]
int preReadCount = (XxlJobAdminConfig.getAdminConfig().getTriggerPoolFastMax() + XxlJobAdminConfig.getAdminConfig().getTriggerPoolSlowMax()) * 20;

triggerPoolFastMax 默认 200
triggerPoolSlowMax 默认 100
算下来刚好6k

批次：理解为这个时间窗口区间内可以装载任务的最大值

建议升级到2.3.0，异步回调执行可以解决很多线程的问题

**Comment by lwsbox** [comment]
理解了
