### ISSUE TITLE
BEAN 任务模式参数到底怎么传和接收啊，文档只字不提

### ISSUE THREAD

**Issue by linyongfu2013** [xuxueli/xxl-job#2368]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

### Other information

**Comment by huoshanwei** [comment]
XxlJobHelper

**Comment by linyongfu2013** [comment]
> XxlJobHelper

@huoshanwei 都没有这个类啊

**Comment by Bacchusgift** [comment]
`/**
     * 1、简单任务示例（Bean模式）
     */
    @XxlJob("demoJobHandler")
    public ReturnT<String> demoJobHandler(String param) throws Exception {
        XxlJobLogger.log("XXL-JOB, Hello World.");

        for (int i = 0; i < 5; i++) {
            XxlJobLogger.log("beat at:" + i);
            TimeUnit.SECONDS.sleep(2);
        }
        return ReturnT.SUCCESS;
    }`

2.2.0是直接参数传递的，方法传参自动绑定到你传的参数里，是一个字符串，具体如何解析，你自己去解决
