### ISSUE TITLE
提示"请选择执行器"问题

### ISSUE THREAD

**Issue by ghost** [xuxueli/xxl-job#2372]
postman中直接调用xxl-job对外api添加任务成功，同样的参数，在代码中http调用api提示“请选择执行器”，可是执行器参数确定已经传递了。
![image](https://user-images.githubusercontent.com/49225384/114649241-b49b9780-9d12-11eb-94ce-9cdd9ceced01.png)

![image](https://user-images.githubusercontent.com/49225384/114649491-34296680-9d13-11eb-8b46-d7e15f75a548.png)

**Comment by xuxueli** [comment]
建议debug定位。
