### ISSUE TITLE
求助：遇到一个很诡异的问题，job执行成功但是返回失败

### ISSUE THREAD

**Issue by earther01** [xuxueli/xxl-job#239]
xxl-job1.8.2版本，job业务逻辑执行成功，但是返回执行结果却是失败。callback日志如下：
e.thread.TriggerCallbackThread||>>>>>>>>>>> xxl-job callback success, callbackParamList:[HandleCallbackParam{logId=70725, executeResult=ReturnT [code=500, msg=null, content=null]}], callbackResult:ReturnT [code=200, msg=null, content=null]

更诡异的是，这个job本来是一直是正常的，由于数据原因执行失败一次。修复数据之后，job的业务逻辑都执行成功，日志也无报错，但是执行结果返回失败（如callback日志），并且每次运行都返回失败。修复数据并没有变动jobHandler代码。

只有两个job出现这个问题，其余的几十个job均正常。
执行器的运行环境：jdk1.7，tomcat7。
实在是找不出问题原因，求给个解决思路，谢谢！

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
可以debug确认下该任务execute方法的返回数据，注意如果返回为null，会标示为FAIL的。

**Comment by earther01** [comment]
感谢及时的回复！
job的execute方法中没有返回null的语句。
最后还是重启系统解决了问题，并没有改动代码。至于问题的原因，目前还是没有思路，作为一个偶发情况先记下来。
