### ISSUE TITLE
测试用例 DemoJobHandlerTest 报错

### ISSUE THREAD

**Issue by ycyy** [xuxueli/xxl-job#240]
Please answer some questions before submitting your issue. Thanks!

### 版本1.9.0

测试用例 DemoJobHandlerTest 报错com.xxl.job.core.rpc.netcom.jetty.client.JettyClient]-[main]-[send]-[40]-[ERROR] unknown code for readObject at 0x3c (<)
正常 配置执行器能够运行，单独运行 DemoJobHandlerTest 时报错无法执行，打断点显示在HessianSerializer  类 return hi.readObject();时报错
不知道是什么原因

**Comment by xuxueli** [comment]
你好，检查下测试用例对应的执行器机器是否启用，需要执行器处于启动状态来测试。
