### ISSUE TITLE
调度日志是否有定时清理的功能？

### ISSUE THREAD

**Issue by dean-coding** [xuxueli/xxl-job#2416]
针对2.1.0 版本，请问针对调度日志是否有定时清理的功能？

我尝试了`xxl.job.executor.logretentiondays = 3`的配置,但是好像没有效果，是只支持手动清理嘛

**Comment by yanghui-git** [comment]
有的
xxl_job 服务端启动 有一个 JobLogReportHelper 调度  会去清理 xxl.job.executor.logretentiondays = 30 过期的日志 
默认是30天

你失败的原因 ：我这边看源码是 他这边设置允许的最小值是7天 ，否则失效     public int getLogretentiondays() {
        if (logretentiondays < 7) {
            return -1;  // Limit greater than or equal to 7, otherwise close
        }
        return logretentiondays;
    }

你可以自己去看下源码 JobLogReportHelper 97行

解决方式 xxl.job.executor.logretentiondays  配置  》=7

**Comment by dean-coding** [comment]
ok,thanks ,I'll try it again

**Comment by dean-coding** [comment]
> 有的
> xxl_job 服务端启动 有一个 JobLogReportHelper 调度 会去清理 xxl.job.executor.logretentiondays = 30 过期的日志
> 默认是30天
> 
> 你失败的原因 ：我这边看源码是 他这边设置允许的最小值是7天 ，否则失效 public int getLogretentiondays() {
> if (logretentiondays < 7) {
> return -1; // Limit greater than or equal to 7, otherwise close
> }
> return logretentiondays;
> }
> 
> 你可以自己去看下源码 JobLogReportHelper 97行
> 
> 解决方式 xxl.job.executor.logretentiondays 配置 》=7

**Comment by dean-coding** [comment]
我检查了源码，我这边看下来没有JobLogReportHelper这个类？请求你的版本是2.1.0吗？我从源码中只看到这种配置：
```
JobLogFileCleanThread.getInstance().start(logRetentionDays);
...
public void start(final long logRetentionDays){

    // limit min value
    if (logRetentionDays < 3 ) {
        return;
    }
```
另外我也尝试配置了`xxl.job.executor.logretentiondays = 7`,可以依然没有效果,如下图 5-7的日志还存在：
![image](https://user-images.githubusercontent.com/16054592/118765339-824efe00-b8ad-11eb-902a-291cc06f39d6.png)

**Comment by yanghui-git** [comment]
嗯，我下载了2.1.0 的代码看了下 确实没有定时清理日志的功能
不过2.1.2 以及之后是有的，见截图

ps： 2.1.0应该是作者当时没有完善好的小版本，所以也就没有对应的远程分支，2.1.2 是有对应分支的，
我建议你升级到2.1.2

<img width="1439" alt="1621407406818_65271E90-3A4B-4C4D-93EC-3B25EECDFFA6" src="https://user-images.githubusercontent.com/69784471/118769713-0c4d9580-b8b3-11eb-880c-603a7cd6ae1f.png">
<img width="1439" alt="1621407406966_E41F5CC6-455C-4DCE-862E-404780029C48" src="https://user-images.githubusercontent.com/69784471/118769719-0d7ec280-b8b3-11eb-8082-19cc99366e40.png">
![Uploading 截屏2021-05-19 下午3.01.44.png…]()

**Comment by yanghui-git** [comment]
或者你手动改源码  打包*** 部署      但是这样成本比较大

**Comment by dean-coding** [comment]
好吧，感谢回复
