### ISSUE TITLE
java.io.IOException: No such file or directory 	at java.io.UnixFileSystem.createFileExclusively(Native Method)

### ISSUE THREAD

**Issue by zhuSilence** [xuxueli/xxl-job#245]
Please answer some questions before submitting your issue. Thanks!

master版本
调度中心和执行器搭建都成功了，但是执行任务的时候出现如下问题：
![image](https://user-images.githubusercontent.com/8224393/34318188-564453d0-e7fc-11e7-95eb-956f6f543fc9.png)

还请帮忙看一下。谢谢

**Comment by zhuSilence** [comment]
经测试是因为在使用logFile.createNewFile();创建日志文件的时候，没有创建上级文件夹导致的，但是小弟不知为何我这里就不能创建上级文件夹呢？本地是macOS High Sierra， 10.13.2，部署的服务器是CentOS  6.5具体内核不清楚，难道没有跟我遇到同一个问题的吗？

**Comment by xuxueli** [comment]
你好，你部署使用的是哪个分支版本啊？

**Comment by zhuSilence** [comment]
你好，感谢回件，我是直接拉的master分支的。不知道是否可以。
silence
1347023180@qq.com

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
推荐使用release稳定版本，都是经过测试发版的啊。master分支在持续迭代和自测中，不建议使用。

**Comment by happyi** [comment]
手动创建 一下这个目录  /data/applogs/xxl-job/jobhandler

**Comment by codelearner1024** [comment]
> 你好，你部署使用的是哪个分支版本啊？

我这边线上  2.1.2 也有这个问题 大佬 是否是版本的问题，你这边好确认吗？

**Comment by Vernunft** [comment]
遇到同样的问题 是升级后就可以了吗

**Comment by Vernunft** [comment]
> 

请问大佬有解决吗 目录会自己消失的问题
