### ISSUE TITLE
请问有golang客户端吗?

### ISSUE THREAD

**Issue by xhrg** [xuxueli/xxl-job#2457]

**Comment by xhrg** [comment]
我看到了这个，应该是golang客户端：https://github.com/xxl-job/xxl-job-executor-go

**Comment by PGshen** [comment]
按照作者的实现Java执行器的思路，实现的golang版本的执行器，引入包即可使用，欢迎交流～
[https://github.com/PGshen/go-xxl-executor](https://github.com/PGshen/go-xxl-executor)

**Comment by youbeiwuhuan** [comment]
https://gitee.com/youbeiwuhuan/go-xxljob-executor
我也蹭一波热度，哈哈哈。我只实现了2.3.0的原生功能，2.1.2在开发中

**Comment by xuxueli** [comment]
感谢关注，Go版本建议合并至这里：https://github.com/xuxueli/xxl-job/issues/154

@youbeiwuhuan @xhrg @PGshen

**Comment by lizhiyoumai** [comment]
> 我看到了这个，应该是golang客户端：https://github.com/xxl-job/xxl-job-executor-go

这个对应的xxl-job的版本是多少啊 我使用的时候貌似有问题
