### ISSUE TITLE
https://github.com/Antergone/xxl-job       

### ISSUE THREAD

**Issue by Zhouchuanwen** [xuxueli/xxl-job#246]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
https://github.com/Antergone/xxl-job

### Expected behavior
部署后可直接运行

### Actual behavior
/jobinfo/pageList  部署后前端传参异常，参数被固定

### Steps to reproduce the behavior
/jobinfo/pageList   点击下拉框选择不同执行器，返回结果完全一样，且前端参数固定为1

### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。
建议可以加入交流群详细沟通啊。
