### ISSUE TITLE
神马情况？ xxl-job-admin 竟无法启动？ 求解

### ISSUE THREAD

**Issue by luckzhangla** [xuxueli/xxl-job#247]
xxl-job-admin eclipse右击 Run Server,控制台输出 错误 （PS 第一次启动成功，也演示了很多。次日再打开就报这个问题）：

2017-12-25 15:23:11,138 - xxl-job-admin - ERROR [org.springframework.web.context.ContextLoader] - <Context initialization failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in file [D:\Java\wrokspace4xxljob\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\xxl-job-admin\WEB-INF\classes\spring\applicationcontext-xxl-job-admin.xml]: Invocation of init method failed; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [D:\Java\wrokspace4xxljob\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\xxl-job-admin\WEB-INF\classes\mybatis-mapper\XxlJobGroupMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. `Cause:` org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'com.xxl.job.admin.core.model.XxlJobGroup'.  **Cause: java.lang.ClassNotFoundException: Cannot find class: com.xxl.job.admin.core.model.XxlJobGroup**

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
从Log “ ClassNotFoundException” 推测，应该是没有正确编译，重新编译部署下啊。
