### ISSUE TITLE
请问怎么查看 scheduler.triggerJob(jobKey);内部执行

### ISSUE THREAD

**Issue by luckzhangla** [xuxueli/xxl-job#248]
想查看下 xxl-job-admin/core/schedule/XxlJobDynamicScheduler.java 的triggerJob方法内部

 **scheduler.triggerJob(jobKey); 具体怎么根据 jobKey拿到任务的Shell脚本执行的。**

我们现在需要利用 ansible 自己执行 Shell ，所以想看具体t riggerJob 的方法。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
可以从相关源码debug进入查看，可以参考下执行器依赖JAR的实现。
