### ISSUE TITLE
页面增删改查还有操作代码全写在一个页面有点臃肿

### ISSUE THREAD

**Issue by huanzui** [xuxueli/xxl-job#249]
首先赞下整体架构来讲还是非常不错的。

但页面增删改查还有操作代码全写在一个页面有点臃肿 代码老长了，查询、增、改页面能否分开。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
任务管理功能集中在一张页面，代码实现上稍微复杂。但是从用户角度来看，操作更顺畅的啊。
