### ISSUE TITLE
执行日志出现Rolling Log Finish

### ISSUE THREAD

**Issue by waynezhangw** [xuxueli/xxl-job#2491]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
点击执行日志，出现对应的日志
### Actual behavior
点击执行日志，仅出现两行Rolling Log Finish而不加载实际的日志是为什么？

以及点击执行日志如果正常出现日志内容，这些内容是在executor节点上的哪个路径下有这个文件吗？
如果控制台无法显示日志，该去哪个节点的哪个路径下捞这些日志呢？

**Comment by waynezhangw** [comment]
应该是日志过期自动删除导致的，这个参数之前没有注意到，xxl.job.executor.logretentiondays=30，改一下应该就可以了
这个改完配置是不是得重启admin和executor才能生效？

**Comment by zhuohb** [comment]
我也遇到这个问题.情况是,任务没有被执行,xxljob就直接返回200了,所以没有日志

**Comment by tyebu** [comment]
同样遇到这个问题，有解决吗

**Comment by waynezhangw** [comment]
> 同样遇到这个问题，有解决吗

不是日志过期自动删除导致的吗？

**Comment by EverSpring** [comment]
遇到同样问题，大家知道是什么原因、怎么解决的？

**Comment by Ethan-622** [comment]
遇到了同样的问题，目前只能重启执行器服务暂时解决

**Comment by itheimacast** [comment]
xxljob 2.3.0 版本 经常出现指定器空跑，执行日志输出[Rolling Log Finish]

**Comment by l2773938492-art** [comment]
我也出现了同样的情况【终止请求Rolling日志,请求失败次数超上限,可刷新页面重新加载日志】

但是我的任务是跑完了，只是最后没有结束掉。敢问哪个大神遇到过
