### ISSUE TITLE
分片数自定义

### ISSUE THREAD

**Issue by FireEyeMamba** [xuxueli/xxl-job#250]
当前最新版的xxl-job的分片个数是执行器个数，不支持用户自定义分片个数。
而实际上，比如执行器只有2个，我分片数6个，可以一个执行器并发执行3个~
不知道这方面有规划吗？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
自定义分片需要固定分片数，不方便执行器动态扩容锁容。如果希望指定机器的分片数，可以通过任务参数方式实现，任务运行时根据入参处理最终分片数。
