### ISSUE TITLE
关于失效转移

### ISSUE THREAD

**Issue by FireEyeMamba** [xuxueli/xxl-job#251]
当前xxl-job的实现中如果分片失败了可以重试该分片，但是还有一个情况就是运行分片的
执行器所在的机器直接崩溃了，这种情况下你无法获取他的状态，当前xxl-job似乎没有
针对这种情况进行失效转移。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈啊！
分片任务执行器如果崩溃，会在注册中心主动摘除的。失败的分片会进行失败告警。
分片任务的分片转移，已经加入TODO将会排期跟进。

**Comment by xuxueli** [comment]
你好，目前xxl-job支持分片任务的失败重试与转移。版本 v1.9.2 （迭代中，不日发布）可见；
