### ISSUE TITLE
docker方式启动xxl_job_admin失败  mysql password包含特殊字符

### ISSUE THREAD

**Issue by boot-vue** [xuxueli/xxl-job#2512]
`--spring.datasource.password` 不含特殊字符时正常   带特殊字符无法连接数据库  比如 `root!00`  这种的要怎么处理

`bash`执行时 `java -jar --spring.xxxx=root!00`   出错,  试过了`root\!00`  单双引号转义都不行

**Comment by boot-vue** [comment]
其实就是`java -jar xxx.jar --spring.datasource.password=root!00` 如何传递特殊字符的问题

**Comment by anaer** [comment]
双引号包下看看

**Comment by boot-vue** [comment]
> 双引号包下看看

不行
