### ISSUE TITLE
oom, InternalThreadLocalMap里消息占用内存很大，内存溢出

### ISSUE THREAD

**Issue by huan415** [xuxueli/xxl-job#2536]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.1-SNAPSHOT
### Actual behavior
两个任务(没有传额外参数)，一个10min执行一次，一个8min执行一次，两个都任务都占用10m
### Other information
![1](https://user-images.githubusercontent.com/37132274/127630422-4667619e-f1b7-4673-a5b9-007340512eda.jpg)
![2](https://user-images.githubusercontent.com/37132274/127630441-401cd196-32dd-4b9b-a1fb-90ba828f7e5c.jpg)

**Comment by xuxueli** [comment]
你好，SNAPSHOT为快照版不建议使用，建议用稳定版本。
