### ISSUE TITLE
使用GLUE（Java）模式开发时，任务依赖如何管理？

### ISSUE THREAD

**Issue by FireEyeMamba** [xuxueli/xxl-job#254]
使用GLUE（Java）模式开发时，如果Java程序有一些执行器里面不包含的依赖，怎么办？
可以通过支持上传完成Jar来解决这个问题吗？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
目前需要执行器添加依赖并提供运行环境。

**Comment by dongluyang** [comment]
上传完jar 后，得反射机制来动态加载，并执行了。具体看这里有个介绍
https://www.toutiao.com/article/7227496875803345446/
