### ISSUE TITLE
任务代码执行结束为什么node进程一直未退出，只能通过手动终止

### ISSUE THREAD

**Issue by AdeleGo-design** [xuxueli/xxl-job#2551]
![image](https://user-images.githubusercontent.com/70873656/129129028-eb5370a8-9dc4-4697-ac8e-816c804c4ff3.png)

**Comment by pengten** [comment]
任务模式是java BEAN吗？  确认客户端版本和服务端版本是否一致

**Comment by AdeleGo-design** [comment]
> 任务模式是java BEAN吗？ 确认客户端版本和服务端版本是否一致

是gule shell模式

**Comment by AdeleGo-design** [comment]
目前我的方式是在js代码执行结束的地方写 process.exit(0)来退出进程，不知道为什么xxl-job没有终止进程

**Comment by AdeleGo-design** [comment]
@xuxueli 大佬麻烦看一下， 或者有群吗 想加入问一下，非常感谢

**Comment by pengten** [comment]
进程是需要自己结束的，demo的shell代码中，最后也有exit。

**Comment by yuweiming2016** [comment]
我有exit 0也不会结束，日志看到一直没结束

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/131808438-852e98e8-43ff-4a38-b379-489333a6933c.png)

**Comment by yuweiming2016** [comment]
@AdeleGo-design 解决了吗？

**Comment by xuxueli** [comment]
你好，辛苦确认任务回调日志是否异常，回调失败会导致结果丢失。
