### ISSUE TITLE
任务调度，但是客户端并没有接收到任务

### ISSUE THREAD

**Issue by 13619205479** [xuxueli/xxl-job#2552]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0

### Expected behavior
任务正常调度
### Actual behavior
任务调度阻塞
### Other information

**Comment by pengten** [comment]
状态成功？

**Comment by 13619205479** [comment]
调度结果显示成功，执行结果为空

**Comment by xuxueli** [comment]
抱歉，问题无法复线，需要提供完整复线步骤。
