### ISSUE TITLE
在单机串行策略下，任务执行周期超过cron间隔周期，执行结果不返回，出现大量进行中调度日志

### ISSUE THREAD

**Issue by sunmingji** [xuxueli/xxl-job#2555]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0.1

### Expected behavior
任务调度
### Actual behavior
任务一直处理运行中且执行结果为空
### Steps to reproduce the behavior
单机串行策略，任务执行周期超过cron间隔周期
### Other information

**Comment by pengten** [comment]
这是正常现象，加大调度间隔或者异步执行
