### ISSUE TITLE
xxl_job_registry表死锁 xxl-job版本2.1.0

### ISSUE THREAD

**Issue by shanehan** [xuxueli/xxl-job#2558]
2021-08-18 11:07:01 0x7feb47931700
*** (1) TRANSACTION:
TRANSACTION 87959937, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 25012155, OS thread handle 140643721230080, query id 9431449835 10.0.51.15 app updating
DELETE FROM xxl_job_registry
		WHERE update_time   <   DATE_ADD(NOW(),INTERVAL -90 SECOND)

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 15582 page no 6 n bits 112 index i_u of table `xxl_job`.`xxl_job_registry` trx id 87959937 lock_mode X locks rec but not gap
Record lock, heap no 21 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 4; hex 611c7937; asc a y7;;
 1: len 4; hex 8000132f; asc    /;;

*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 15582 page no 4 n bits 104 index PRIMARY of table `xxl_job`.`xxl_job_registry` trx id 87959937 lock_mode X locks rec but not gap waiting
Record lock, heap no 8 PHYSICAL RECORD: n_fields 7; compact format; info bits 0
 0: len 4; hex 8000132f; asc    /;;
 1: len 6; hex 0000053e2980; asc    >) ;;
 2: len 7; hex 01000001f20151; asc       Q;;
 3: len 8; hex 4558454355544f52; asc EXECUTOR;;
 4: len 20; hex 7368617265642d7265706f72742d636f6e666967; asc shared-report-config;;
 5: len 17; hex 3137322e31372e382e3131383a37363736; asc 172.17.8.118:7676;;
 6: len 4; hex 611c7955; asc a yU;;

*** (2) TRANSACTION:
TRANSACTION 87959936, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 25013579, OS thread handle 140644384757504, query id 9431449834 10.0.51.15 app updating
UPDATE xxl_job_registry
        SET `update_time` = NOW()
        WHERE `registry_group` = 'EXECUTOR'
          AND `registry_key` = 'shared-report-config'
          AND `registry_value` = '172.17.8.118:7676'

**Comment by xuxueli** [comment]
建议升级，该问题在高版本进行过多次优化。
