### ISSUE TITLE
version 2.3.0路由策略选择故障转移，失败重试次数选择1 出现无限调度BUG

### ISSUE THREAD

**Issue by 1227488619** [xuxueli/xxl-job#2569]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Actual behavior
路由策略选择故障转移，失败重试次数选择1，不论任务成功或失败，调布中心会一直调度该任务，即使执行器的机器全部停止，调度中心拿到的是空的执行器地址列表，也会一直做调度动作
### Steps to reproduce the behavior
第一次测试
  1.启动好调度中心，任务配置详情
  ![e8353b901cab1a8250e03ea7f6a7745](https://user-images.githubusercontent.com/46393293/130791445-1787ff7e-882a-464d-8604-3625173ea984.png)
  
  2.这段代码启动三个不同的端口，执行器代码详情
  ![03cd51662356c9feaa1e1114398a607](https://user-images.githubusercontent.com/46393293/130791698-eb18ad62-aa4a-4190-ad21-e7f61d834ce7.png)
  
  3.执行一次该任务（不同测试场景不同结果）
  
  4.调度中心选择一个健康的机器执行任务
  ![1](https://user-images.githubusercontent.com/46393293/130793560-518cdf5b-e1aa-42c5-9cca-13bb691abf74.png)
  
  5.代码中sleep 30秒，在这期间，关闭该机器
  
  6.调度中心检测到这个机器不健康了
  
  7.调度中心找到下个健康的机器执行该任务
  ![dea98b8d2d05ff88338c6348226e39c](https://user-images.githubusercontent.com/46393293/130793676-48184f3d-6044-4773-91a3-a0a35b6556b4.png)
  
  8. 前面的4，5，6，7步骤重复两次，也就是之前启动的三个机器都down了
  
  9.调度中心得到的执行器列表地址为空，但是调度中心还会一直重试任务

第二次测试（
     与第一次测试大致步骤相同
     不同的地方为：
     1.代码中 去除 throw new RuntimeException...
     2.重新启动三个机器（或许和之前启动的端口不同，可忽略）
     3.不执行第一次测试的步骤8，执行完前7步，观察结果
）
结果是调度中心会在下个健康的机器上一直执行任务，不论任务的成功失败
![65dab095556621077e98e3eb410ab73](https://user-images.githubusercontent.com/46393293/130796948-4d4b3996-18ea-4f90-ae32-17ed3332f175.png)

![091e6aca28b10c77bb3c38c4accbe6f](https://user-images.githubusercontent.com/46393293/130796957-5494bff8-f976-469e-ae46-07056b3e7da6.png)

![20b4e5083fa6936cdcf6792300f7ea8](https://user-images.githubusercontent.com/46393293/130796959-d56dbdc9-2ffc-4071-be25-50e2ae72b524.png)

![617c1233ff0f9387325e43128c3fa43](https://user-images.githubusercontent.com/46393293/130796966-4ce1de3c-9b7c-41fd-8983-a97f72e98cf9.png)

结论：
           故障转移并不会关注执行任务中的错误和正在执行任务机器的健康
          搭配失败重试次数的使用，出现无限调度问题

**Comment by DongJianLiang** [comment]
![image](https://user-images.githubusercontent.com/19922938/146295427-b9b1807f-311f-4c1c-a2b0-4d45eaa0ed6f.png)
版本2.3.0还会出现这个问题
![image](https://user-images.githubusercontent.com/19922938/146295488-072933c0-8fcd-45da-9aea-273e54769d4c.png)
重复调用很多次
