### ISSUE TITLE
新增任务-执行参数希望支持json格式的传参

### ISSUE THREAD

**Issue by denghuafeng** [xuxueli/xxl-job#259]
如题，目前我是把json格式的","替换成"|"来解决

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
新版本v1.9.0已经增强了任务参数兼容性支持，参数类型改为 “String param” ，方便灵活的进行任务参数的序列化和定制。

**Comment by xuxueli** [comment]
最新release版本已实现改动能，可升级查看哈！

**Comment by denghuafeng** [comment]
so good!
