### ISSUE TITLE
在大数据场景下支持分片调度

### ISSUE THREAD

**Issue by tbb1984** [xuxueli/xxl-job#26]
在大数据场景下，支持按照分片进行调度，比如一个job任务，分片规则为{北京=1，上海=2，广州=3}，在进行一个job调度的时候，执行节点1只处理北京的数据，执行节点2只处理上海的数据，执行节点3只处理广州的数据。如果执行节点1挂了，那么执行节点1的分片，将自动转移到执行节点2或者执行节点3执行，达到分片的高并发，高可靠。

**Comment by xuxueli** [comment]
您好感谢关注啊，这个意见很有必要啊！分片任务已经有了初步的方案，并且已经将分片任务加入到了项目的TODO LIST中并进行了排期。

**Comment by xuxueli** [comment]
你好，该功能已经实现，并且最新Release版本发布，欢迎获取体验。

**Comment by jiahaoXie** [comment]
@xuxueli  请问最新你版本的xxl job 支持高可靠了吗？
例如，如果执行节点1挂了，那么执行节点1的分片，将自动转移到执行节点2或者执行节点3执行，达到分片的高并发，高可靠。
