### ISSUE TITLE
1.5版本后，不是任务可以不关联 执行器吗

### ISSUE THREAD

**Issue by luckzhangla** [xuxueli/xxl-job#260]
从文档可知 在1.5版本后  任务不再关联 执行器，为何调度中心新建任务时，仍然必选一个 执行器。

在执行器集群部署下，详细疑问：
1.  任务新建时，为何必选一个执行器？
2.  任务新建时，路由策略 无论选择 “轮询”或是“最后一个”，它最终调度的为何仍然是  绑定的执行器，而不是我要的“轮询”或是“最后一个”？

**Comment by xuxueli** [comment]
你好，感谢关注！
1、任务必须绑定在执行器下，因为需要从执行器上获取远程机器地址，从而路由选择机器进行任务触发。
2、以 “轮训” 为例，是针对该任务绑定的执行器的在线机器地址列表进行路由选择。
