### ISSUE TITLE
任务执行完成后，有驻留线程存在，而不是自动销毁

### ISSUE THREAD

**Issue by zhanghqgit** [xuxueli/xxl-job#261]
用的master版本，简单跑了下。使用jvisualvm看了下线程。执行一定时间后有大量的驻留线程。

![image](https://user-images.githubusercontent.com/7802877/34433632-8db4ab44-ecbb-11e7-8ad0-8225a4b63bf5.png)

dump线程后，发现很多的线程都是waiting状态

[thread.log](https://github.com/xuxueli/xxl-job/files/1592850/thread.log)

**Comment by zhanghqgit** [comment]
这个有人碰到过么？

**Comment by ie7shop** [comment]
测试一个实例，2台执行器端，2秒跑一次。一会线程就激增到300 多，然后就一直处于驻留状态了。 
![image](https://user-images.githubusercontent.com/6293184/35262306-0cc268ee-004f-11e8-9be0-a7a9b48fbfb0.png)

**Comment by xuxueli** [comment]
你好，上述监控是正常现象，执行器通讯组件jetty内部维护一个maxSize=256的线程池，上图线程数量上升由此而来。
执行器底层对线程的使用进行了严格的控制，经过系统预热之后，内部维护的线程会维持在一个稳定的数量，并不会无限制增长，可从上图查看到，可以放心使用。

**Comment by ie7shop** [comment]
恩，明白了，这就可以放心应用了，有问题再向您请教 @xuxueli

**Comment by xuxueli** [comment]
@ie7shop 
感谢信任啊！
方便的话，接入后可以登记下哈，方便推广：）https://github.com/xuxueli/xxl-job/issues/1
