### ISSUE TITLE
执行器无法注册

### ISSUE THREAD

**Issue by wenhao0422** [xuxueli/xxl-job#263]
我用的框架是spring boot ,在部署测试环境的时候配置执行器，代码如下
`xxl.job.admin.addresses=http://172.16.117.181:9996/xxl-job-admin
xxl.job.executor.appname=sunland-lite-timer
xxl.job.executor.ip=172.16.117.181
xxl.job.executor.port=9987`

执行器 跟 调度中心都在 172.16.117.181 这台机器上，但是tomcat端口不同而已。
启动调度中心之后，能够看到页面。
接口启动执行器，没有任何的反应。调度中心也没有任何变化
[图片](https://ws1.sinaimg.cn/mw690/5137ae86ly1fn3ssniemrj21q40d4go0.jpg)
而且并没有打印出类似于 xxl-job registry success,这种注册的日志。请问怎么回事？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
重新编译部署下，排查下启动日志中是否有异常Log，比如执行器端口冲突等。

**Comment by sanwancoder** [comment]
也遇到这个问题  如何解决的呢

**Comment by wyyl1** [comment]
两种情况：
1. 版本不一致：**xxl-job-core**、**xxl-job-admin**的版本需要一致。
2. **xxl-job-admin**启动了多个，但没有正确配置集群环境。
