### ISSUE TITLE
如何实现在xxljob读取不同的数据源

### ISSUE THREAD

**Issue by 11huahua** [xuxueli/xxl-job#2664]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by NineSwordsMonster** [comment]
xxljob 依赖数据库做分布式调用锁竞争，没明白读取不同的数据源是指的什么

**Comment by MisterChangRay** [comment]
> Please answer some questions before submitting your issue. Thanks!
> 
> ### Which version of XXL-JOB do you using?
> ### Expected behavior
> ### Actual behavior
> ### Steps to reproduce the behavior
> ### Other information

XXLjOB为分布式任务调用, 所以它不涉及到数据源的问题。
