### ISSUE TITLE
回调线程何时调用

### ISSUE THREAD

**Issue by guolimin1118** [xuxueli/xxl-job#267]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.2
当执行器接收调度中心的请求后，执行器执行任务后，回调API的代码，是通过那个类来执行的。因为只看到启动的时候执行了初始化操作。初始化操作中有回调API的代码。

**Comment by xuxueli** [comment]
你好，可以参考下回调线程内部源码逻辑啊。
