### ISSUE TITLE
gson 2.8.6 暴高危漏洞请升级版本

### ISSUE THREAD

**Issue by robintian-bud** [xuxueli/xxl-job#2681]
Please answer some questions before submitting your issue. Thanks!
![image](https://user-images.githubusercontent.com/73927649/142811146-b1e828ec-6711-46b5-838b-ce1d52201fad.png)

### Which version of XXL-JOB do you using?
  2.3.0
### Other information

**Comment by xuxueli** [comment]
已推送升级。
