### ISSUE TITLE
运行任务调度404

### ISSUE THREAD

**Issue by bnyte** [xuxueli/xxl-job#2692]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0

![image](https://user-images.githubusercontent.com/75556346/144011036-71b1557d-aa8f-45e5-9eae-09a2e1d157ce.png)
项目正常在跑，但是404，看了controller没有run的控制器

![image](https://user-images.githubusercontent.com/75556346/144011209-99c60df0-08fa-4a81-a43e-dbd43211c260.png)

**Comment by xchnshi** [comment]
什么原因导致的？我看了下是没有/run接口
