### ISSUE TITLE
log4j2的漏洞对xxljob有影响吗，有没有修复计划？

### ISSUE THREAD

**Issue by pingfang-tx** [xuxueli/xxl-job#2706]
log4j2的漏洞对xxljob有影响吗，有没有修复计划？

**Comment by Zhuaiz** [comment]
> log4j2的漏洞对xxljob有影响吗，有没有修复计划？

现实中就很多你这种人，我实在是看不下去了，执行器的demo里有引用，除非自己大量重写并且暴露外网，否则应该不受影响
人家代码开源了，也有部署文档，什么都给你了。你可以自己部署后做一下测试。也可以自己看代码
上来自己什么都不干就麻烦作者给你回复，不害臊么？

**Comment by pingfang-tx** [comment]
> > log4j2的漏洞对xxljob有影响吗，有没有修复计划？
> 
> 现实中就很多你这种人，我实在是看不下去了，执行器的demo里有引用，除非自己大量重写并且暴露外网，否则应该不受影响 人家代码开源了，也有部署文档，什么都给你了。你可以自己部署后做一下测试。也可以自己看代码 上来自己什么都不干就麻烦作者给你回复，不害臊么？

我们这边也在同步查看，这个开源组件使用范围挺广的，关注这个问题的人应该也很多，还有一部分同学可能不是java语言栈，只是把这个作为一个工具来使用，不清楚里面的实现。我提这个一个issue，让作者或者热心的同学来解答，避免每一个同学都重复去测试或者检查，有什么问题？
话说回来，皇帝不急你个太监急什么，看不下去可以滚

**Comment by pingfang-tx** [comment]
1. xxl-job-admin 和 xxl-job-executor-sample-springboot 没有用到log4j
2. xxl-job-executor-sample-frameless 用到了slf4j, slf4j用到log4j，版本是1.2.17，不在本次log4j2漏洞的影响范围
综上，本次log4j2 JNDI漏洞对xxljob无影响

**Comment by pingfang-tx** [comment]
> log4j

用到了log4j-api，没有用到log4j-core，打日志实际用的是logback库

**Comment by pingfang-tx** [comment]
> xxl-job-admin 2.3.0版本有用到log4j-api:2.13.3 和 log4j-to-slf4j:2.13.3，但没用到log4j-core，不知道有没有影响，要去研究研究

前面说的有点不准确，我重新整理下
我这边的版本是xxljob2.3.0
xxl-job-admin 和 xxl-job-executor-sample-springboot 用到了log4j-api，没有用到log4j-core，无影响
xxl-job-executor-sample-frameless 用到了slf4j, slf4j用到log4j-core，版本是1.2.17，不在本次log4j2漏洞的影响范围
综上，本次log4j2-core JNDI漏洞对xxljob2.3.0无影响

**Comment by wulove** [comment]
> > xxl-job-admin 2.3.0版本有用到log4j-api:2.13.3 和 log4j-to-slf4j:2.13.3，但没用到log4j-core，不知道有没有影响，要去研究研究
> 
> 前面说的有点不准确，我重新整理下 我这边的版本是xxljob2.3.0 xxl-job-admin 和 xxl-job-executor-sample-springboot 用到了log4j-api，没有用到log4j-core，无影响 xxl-job-executor-sample-frameless 用到了slf4j, slf4j用到log4j-core，版本是1.2.17，不在本次log4j2漏洞的影响范围 综上，本次log4j2-core JNDI漏洞对xxljob2.3.0无影响

是的，简单的测了一下，并且没有用到log4j2实现包，没影响
