### ISSUE TITLE
请问Apache Log4j 远程代码执行漏洞怎么修复，或者官方什么时候commit修复？

### ISSUE THREAD

**Issue by fashengba** [xuxueli/xxl-job#2709]
详情： https://vas.riskivy.com/vuln-detail?id=105

**Comment by JiaXiaohei** [comment]
我目标这么改的~ 
`
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>log4j-api</artifactId>
                    <groupId>org.apache.logging.log4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>log4j-to-slf4j</artifactId>
                    <groupId>org.apache.logging.log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-to-slf4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>

`

**Comment by zwp201301** [comment]
xxl-job存在这个漏洞问题吗

**Comment by xuxueli** [comment]
xxl-job 通过 logback 打印日志，不存在这个问题。
