### ISSUE TITLE
xxl-job 能否支持http 请求调用业务系统接口

### ISSUE THREAD

**Issue by ruyuhi** [xuxueli/xxl-job#271]
xxl-job 能否支持http 请求调用业务系统接口？目前公司有非java项目也需要执行job，但他们可以提供http 接口。

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
是支持的。这种场景社区朋友有遇到过，我把使用方法简要和你介绍下。
方法：定制开发一个公共JobHandler，任务参数约定为Http链接，该JobHandler内部获取到任务参数，即Http链接，后发起调用即可。

**Comment by ruyuhi** [comment]
您好！您的建议还是在执行器中，通过调度中心传递过来的参数，然后再由执行器系统进行http调用，这确实是一种解决方案，但是耦合比较大，每次我添加job，执行器系统中也需要再写一遍。

**Comment by zhuSilence** [comment]
直接用Python脚本调用业务系统接口不行吗？

**Comment by ruyuhi** [comment]
我研究了源码，调度中心不负责执行业务逻辑，它主要就是与执行器进行通讯，把相关的执行信息给到执行器

**Comment by xuxueli** [comment]
上面发送http请求的公共JobHandler只需要开发一次就好了，多个任务支持复用的啊。

**Comment by whoooami** [comment]
@xuxueli 不好意思我个人还有一个疑问，这个应该是个挺常用的需求，诚如上所言在原系统上支持这个需求其实也是一个很简单的功能，为什么当时没考虑直接做好集成到系统当中呢？

**Comment by z6165039** [comment]
@xuxueli xuxuli，您好；通用JobHandler 的方式是可以处理的，没问题，实现起来也不会重复造轮子，但是xxl-job本身支持集群的，这是非常优美的事；按照通用JobHandler的实现方式，问题就是我的JobHandler了最好也要多节点，这样大大增加了系统的复杂度；
