### ISSUE TITLE
调度成功，但是一直无执行结果

### ISSUE THREAD

**Issue by dangnian** [xuxueli/xxl-job#2739]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0

### Expected behavior
调度成功，任务实际执行成功，xxljob但是一直无执行结果，日志很多

### Actual behavior
调度成功，任务实际执行成功，执行结果成功

### Other information
![1642009925](https://user-images.githubusercontent.com/28613321/149195084-b77928f4-5f48-4046-8615-b58eff9b560e.jpg)

**Comment by zzeric** [comment]
callback失败吧，admin和executor不在同一台服务器上，要配置一下

**Comment by shpfli** [comment]
我用2.2.0的客户端，出现过上报成功，但是admin中一直没有结果。 后来升级版本到最新版之后，问题没再出现过。

**Comment by liangzhicheng120** [comment]
我也遇到相同的问题，调度成功，不是callback 成功的，但是一直无执行结果

**Comment by dangnian** [comment]
已解决，问题定位到是部分执行器返回结果代码问题，使用的2.2.0的方式返回结果，需要改为2.3.0的方式使用XxlJobHelper，不然会导致任务轮询获取结果空转，xxljob服务日志不断积压，严重会导致服务内存不足的问题
