### ISSUE TITLE
数据库表xxl_job_info表的id字段建议改成bigint类型

### ISSUE THREAD

**Issue by zymapp** [xuxueli/xxl-job#2744]
比如我有以下业务场景：
@Transactional(rollbackFor = Exception.class)
void add(){
    //1、第一步，在个人业务数据库添加一条业务操作记录

   //2、第二步，添加定时任务到xxl-job中,并获得job任务id
   int id = xxlJobClient.add(xxlJobInfo);

   //3、第三步，更新xxl-job任务id到个人业务数据库表中，用于存储记录所对应的任务id
}
如上场景中的事务中如果第3步出错进行回滚了，那么xxl-job-info表会多出一些没用的任务记录，
如果是bigint类型，那么就可以事先通过雪花算法生成一个唯一的id传给xxl-job-info表了，而不需要第3步操作了，
如果是xxl-job-inf表的id字段是int类型的话那在上面这种场景就很容易出现事务出错回滚而任务不回滚的情况。
像这种事务处理中，其实最好的是最后只操作一次xxl-job，如果xxl-job添加出错那么就全回滚了。

**Comment by lanicc** [comment]
如果是在对源码做二次开发，我觉得xxl如果内部没有这种需求，应该不会修改的。
如果是通过xxl的api接口对接开发的，那就涉及到分布式事务，建议回滚也使用xxl的api，进行手动回滚

**Comment by xuxueli** [comment]
你好，上述场景业务关联性较强，目前评估下来看缺乏场景通用性，建议自行二次开发支持。
