### ISSUE TITLE
便捷上下线online机器？

### ISSUE THREAD

**Issue by gonnalee** [xuxueli/xxl-job#275]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.0
### Expected behavior
快速上下线机器，有时并不想停掉某个机器， 但是这个机器某时刻负载比较大，想暂时下线该机器，不分配job给它执行。建议提供机器列表，可以手动在注册机器中选择下线和恢复工作
### Actual behavior
无法自由下线机器，选择某些机器工作某些暂停工作
### Other information

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
执行器注册方式采用 “手动注册” 方式时可以实现的，可以实时动态调整机器列表。

**Comment by Dorae132** [comment]
手动下线的方式应该有风险的？
因为已经调度的任务并不清楚是否被回调（并且任务的调度是基于trigger_group，而不是具体机器），也就是说此时如果不检查所有已经调度的任务状态的话，有可能导致任务中断，或者重复执行。
所以手工下线机器之前，要检查所有该trigger_group中调度到这台机器上的log的trigger_msg字段。这样是不是有点复杂？ @xuxueli

**Comment by xuxueli** [comment]
@Dorae132  切换到 “手动注册” ，让后在机器列表里去掉对应机器没问题的。
另外针对执行器重启可以参考文档 “灰度发布” 章节。
