### ISSUE TITLE
请问xxl-job 2.3版本应该整合那个版本nacos？整合nacos一直报错

### ISSUE THREAD

**Issue by caifenglin** [xuxueli/xxl-job#2754]
整合nacos一直报错，不兼容
Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]

**Comment by caifenglin** [comment]
<spring-cloud.version>2020.0.3</spring-cloud.version>
        <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>

已解决，搜了好多评论找到

**Comment by htwdjqr** [comment]
@caifenglin 能贴下完整的配置吗？
