### ISSUE TITLE
关于xxljob版本升级兼容性的问题

### ISSUE THREAD

**Issue by zhaikangqi** [xuxueli/xxl-job#2758]
我之前使用的版本是v2.1.0。近期计划升级到v2.3.0。
但是排查过程中发现，升级并不平滑易用。数据库字段做了修改，API也做了修改。导致我只能部署一套新的集群，然后将任务慢慢迁移过来。
由于我们围绕着之前的版本API做了一些工单自动审批流程等的工作。现在也需要改版到新的版本API。
希望官方以后的版本升级能够更加考虑到平滑兼容性等问题。

**Comment by XUZHOUWANG** [comment]
哈哈，把你的代码也集成进来啊。

**Comment by fraser-in-school** [comment]
确实不太向下兼容，后面Java bean模式的注解名字都修改了

**Comment by JauYang** [comment]
赶紧换了吧，不能无缝升级，每次搞都很麻烦。。。

**Comment by xuxueli** [comment]
你好，感谢反馈。后续在评估支持任务版本间导入导出工具。
