### ISSUE TITLE
存在 XSS 安全漏洞

### ISSUE THREAD

**Issue by yuzhaopeng** [xuxueli/xxl-job#2765]
Please answer some questions before submitting your issue. Thanks!

执行日志的结果中的如果存在html标签，会导致页面无法打开。

### Which version of XXL-JOB do you using?
所有版本
### Expected behavior
点击菜单 “执行日志” 页面正常打开
### Actual behavior
点击菜单 “执行日志”  页面是白板
### Steps to reproduce the behavior
1. 我的定时任务执行完成之后，会产生一些html标签数据，保存在日志中
2. 此时在打开xxl 的控制台，点击 “执行日志” ，页面白板
3. 排查发现是 xxl_job_log 表中的数据如果有html标签，在打开日志时候就会直接执行这些html， 存在 XSS 安全漏洞
### Other information

**Comment by lanicc** [comment]
这个可能是作者为了把调度日志更好的展示，所以调度日志会在后端存库时刻意的拼接上一些html标签，导致的

**Comment by yuzhaopeng** [comment]
我后来试了下，新增任务时在任务描述里添加html标签，也会导致日志页面打不开，前后端都没有处理这个xss注入的漏洞

**Comment by xuxueli** [comment]
已修复
