### ISSUE TITLE
任务无法结束

### ISSUE THREAD

**Issue by gonnalee** [xuxueli/xxl-job#278]
Please answer some questions before submitting your issue. Thanks!
任务实际代码执行完了，也返回了200，但是无法结束
### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
任务执行完可以结束
### Actual behavior
任务实际代码执行完了，也返回了200，但是无法结束，状态处于进行中。今天早上6点多出现两条这样的记录，直到10点多看还是进行中。后续任务也都正常触发早早结束了
### Other information

**Comment by gonnalee** [comment]
问题是一次call back 失败，造成再也不会call back了，接着这个任务就变成无法结束了

**Comment by hybnew** [comment]
我们也遇到这个问题，望解决

**Comment by 78425665** [comment]
我也是这个问题，而且如果这种任务很多的话，会持续打出大量日志，我就被这个问题搞的机器磁盘报警，结果一看进行中的任务有2000多个，可是返回结果都是200啊，再看日志基本上都是10秒打一次2000多条记录job running的日志，最后在后台把日志全部清了，才暂时解决磁盘报警的问题，但是问题依旧还存在

**Comment by xuxueli** [comment]
@gonnalee @hybnew @78425665 
任务回调失败情况下，调度中心无法感知运行结果导致的。可以排查下任务回调Log。
任务返回结果200说明运行成功，但是无法成功回调依然会识别为失败，需要先排查修复回调失败的问题。
磁盘告警问题，可以排查下，是不是任务Log打印太多，磁盘太小导致的，可以提升Log级别只输出敏感Log即可。
