### ISSUE TITLE
关于失败重试

### ISSUE THREAD

**Issue by IBRANCE** [xuxueli/xxl-job#2783]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using? 
2.1.1-SNAPSHOT
### Expected behavior
有一个发邮件的需求，设置了失败重试次数为3次，本来期望是失败了可以重新发放。
### Actual behavior
直接发了4次

### Other information

这个问题有朋友出现过么，是版本的问题么？

**Comment by IBRANCE** [comment]
连接超时了

**Comment by lanicc** [comment]
最新版本的xxl，报警发送逻辑，是通过调度日志来的，查询到失败的调度日志，就会进行一次告警
