### ISSUE TITLE
TIDB版本问题出现写写冲突的问题(Write conflict)

### ISSUE THREAD

**Issue by lzk416** [xuxueli/xxl-job#2789]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0

### Other information
经过排查非xxl-job，是自身TIDB版本有问题。详细记录可见：https://www.jianshu.com/p/bb9aaf2cfac1

**Comment by lanicc** [comment]
没有描述？

**Comment by lzk416** [comment]
经过排查非xxl-job，是自身TIDB版本有问题。详细记录可见：https://www.jianshu.com/p/bb9aaf2cfac1
