### ISSUE TITLE
邮件报警加下输出的错误信息

### ISSUE THREAD

**Issue by whh19921024** [xuxueli/xxl-job#279]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1

**Comment by xuxueli** [comment]
你好，感谢反馈！
已经将该建议加入到TODO排期跟进。

**Comment by xuxueli** [comment]
你好，该特性已经在版本 v1.9.2 (迭代中)，可以 pull master 分支预览，将会不日发布；
