### ISSUE TITLE
不能支持 sqlserver 吗？

### ISSUE THREAD

**Issue by cxc3214** [xuxueli/xxl-job#28]

**Comment by xuxueli** [comment]
你好，谢谢关注啊！
暂时仅支持mysql版本；如需其他版本可加入交流群咨询，群内许多同学有非mysql版本成功定制经验；

**Comment by waterWang** [comment]
可以考虑liquibase，将所有基础表使用liquibase进行管理，期待项目时候自动生成表结构（不依赖数据库版本）

**Comment by xuxueli** [comment]
感谢关注！
主版本基于mysql迭代。其他语言版本可参考分支版本 （https://github.com/xuxueli/xxl-job/issues/154  ）。多数据支持已经加入TODO排期迭代。
