### ISSUE TITLE
xxl-job失败故障定时时间错误

### ISSUE THREAD

**Issue by gotheworld** [xuxueli/xxl-job#280]
基于xxl-job 1.9.0版本
运行spring bean在2台机器，配置定时任务*/5 * * * * ?，并且轮训执行，此时每台每10秒打印一次，因为2台机器交替运行所以平均下来每5秒执行一次，正常；如果关闭其中一台，剩下的一台每10秒执行一次，按理应该每5秒执行一次才对。急急急！！

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
可以在调度中心查看该任务的执行日志列表，正常情况下，应该是 5s 一次。
你描述的上述问题，应该是该机器自动注册的机器信息尚未被调度中心心跳摘除导致，属于正常情况。
下线机器将会在三次心跳后自动摘除。
