### ISSUE TITLE
2.3.0版本终止任务无效

### ISSUE THREAD

**Issue by montecristoo** [xuxueli/xxl-job#2804]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
在调用日志界面对进行中的任务点击终止任务，会停止任务
### Actual behavior
在调用日志界面对进行中的任务点击终止任务，没有停止任务
### Other information

**Comment by jwister** [comment]
怎么解决的？我也有这个问题

**Comment by jwister** [comment]
已解决。向上抛出interrupt即可

**Comment by yanhua-volvo** [comment]
我现在代码就是catch的中断异常并抛出，但是测试发现后台终止任务并不会触发中断异常。是什么原因啊
