### ISSUE TITLE
xxljob 集群部署 重复执行任务

### ISSUE THREAD

**Issue by Dawnsc** [xuxueli/xxl-job#2806]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-admin 2.3.0
### Expected behavior
单机或多机集群，nginx 负载两个调度中心，一个或多个执行器，执行的任务应是单次
### Actual behavior
单机或多机集群，负载后选择每秒执行、每十秒执行、每分钟都会出现重复，部署几台调度中心就重复几次（即使使用阻塞处理策略，使用丢弃后续调度，也有概率出现重复）
### Steps to reproduce the behavior
单机 两个调度中心服务(springboot)，一个执行器，（多机集群也是多个调度中心多个执行器，调度中心用nginx负载）
### Other information

如果我的操作是错的，请问正确的集群 与 每次任务只执行单次是要怎么配置呢？

**Comment by NineSwordsMonster** [comment]
> Please answer some questions before submitting your issue. Thanks!
> 
> ### Which version of XXL-JOB do you using?
> xxl-job-admin 2.3.0
> 
> ### Expected behavior
> 单机或多机集群，nginx 负载两个调度中心，一个或多个执行器，执行的任务应是单次
> 
> ### Actual behavior
> 单机或多机集群，负载后选择每秒执行、每十秒执行、每分钟都会出现重复，部署几台调度中心就重复几次（即使使用阻塞处理策略，使用丢弃后续调度，也有概率出现重复）
> 
> ### Steps to reproduce the behavior
> 单机 两个调度中心服务(springboot)，一个执行器，（多机集群也是多个调度中心多个执行器，调度中心用nginx负载）
> 
> ### Other information
> 如果我的操作是错的，请问正确的集群 与 每次任务只执行单次是要怎么配置呢？

xxljob 的集群调度依赖 db锁 `select for update ...` 确保多机访问的是同一个数据库

**Comment by Dawnsc** [comment]
谢谢回答，问题已解决，xxl_job_lock中的DB锁字段不存在导致的。

**Comment by Badw0mam** [comment]
> 谢谢回答，已解决，xxl_job_lock中的DB锁问题不存在导致的。

可以详细说说怎么解决的吗

**Comment by baymax55** [comment]
> 

请问是哪个版本解决的

**Comment by Dawnsc** [comment]
> > 
> 
> 请问是哪个版本解决的

我是用的版本是2.3.0；后面断点代码，发现导入的db库xxl_job_lock表缺少字段锁导致的，我自己添加"schedule_lock"上就好了

**Comment by baymax55** [comment]
> > > 
> > 
> > 
> > 请问是哪个版本解决的
> 
> 我是用的版本是2.3.0；后面断点代码，发现导入的db库xxl_job_lock表缺少字段锁导致的，我自己添加"schedule_lock"上就好了

他回复说是:xxl_job_lock中的DB锁字段不存在导致的。那就直接在xxl_job_lock表中加入schedule_lock就可以了.


`select * from xxl_job_lock where lock_name = 'schedule_lock' for update`
