### ISSUE TITLE
邮件参数建议

### ISSUE THREAD

**Issue by xbeginagain** [xuxueli/xxl-job#281]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
配置邮件校验的加密方式
### Actual behavior
目前如果是TLS校验不配置会出现503错误，MailUtil.sendMail 把校验方式注释掉了，建议在配置文件里指定校验方式是TLS或者SSL,然后在MailUtil.sendMail 里自动配置。
//email.setTLS(true); 被标示已经过时
email.setStartTLSEnabled(true); 亲测可用

**Comment by xuxueli** [comment]
赞，欢迎提交PR一起参与到项目里来啊，提交PR的用户将会自动成为 “contributor”
