### ISSUE TITLE
xxl-job 用TiDB兼容度以及要注意的事项问题

### ISSUE THREAD

**Issue by bossjie** [xuxueli/xxl-job#2814]
### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
和tidb兼容使用
### Actual behavior
NA
### Steps to reproduce the behavior
NA
### Other information

感谢提供这么好的job engine.我们部门准备用xxl-job结合我们的TiDB集群(v4.0.11), 
从网上以及github里 搜索,   看3年前贵项目已经在结合TiDB使用了, 目前有以下几点要注意的
1.确认TiDB 用悲观事务模式(参考: https://www.jianshu.com/p/bb9aaf2cfac1), 否则开启多个job admin时会重复调用
2.因为TiDB自增主键不是单一线性增长(而是相互有点隔离间距, 几台机器会产生1234, 几台机器产生1000,1001...), 这个看起来似乎没什么影响
是否还存在其他要注意的事项?  非常感谢您的回答. 基于TiDB在国内十分流行, 如果可以, 我们可以把这个内容更新到ReadMe里面

**Comment by srock82** [comment]
xxl job最新代码 + tidb v5.2.0  运行没有问题，每天18000+次调度 
注意：因乐观事务模式会引起tidb的txnlock超过阈值警告，你可以忽略它，也可以调整xxl job代码解决

**Comment by bossjie** [comment]
多谢 老铁 @srock82
