### ISSUE TITLE
XXL-JOB-2.3.0，注册节点偶尔会莫名消失。

### ISSUE THREAD

**Issue by RedStone365** [xuxueli/xxl-job#2819]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
注册成功后，在我不关闭服务的情况下，注册节点不会消失。
### Actual behavior
我启动了16个后台服务，分别对2个不同的执行器进行注册，每个执行器下有8个注册节点。
一开始是好的，每个执行器下的定时任务，有8个注册节点。
但是运行了2、3天，有些已经注册的节点消失了，由8个注册节点，变成了3个。
![fbcb0790d1e4642bb601d39227b9cf7](https://user-images.githubusercontent.com/23112024/161877988-8af4b6b6-0d1e-4d29-83af-03a3a9a2f2b9.png)
我排查了一下消失节点的服务，未发现异常，日志也没有提示未注册到XXL-JOB的错误信息。
但是XXL-JOB中确实找不到相应节点了，导致我现存的3个节点，不足以支撑我的调度任务。。。
（总计有150个定时任务，所有定时任务每7分钟执行一次。）
### Steps to reproduce the behavior
①创建2个执行器
②每个执行器注册5~8个节点
③等段时间，注册注册节点莫名消失
### Other information
希望大大能给予排查思路或解决方案，有些无从下手，谢谢！

**Comment by liukeless** [comment]
https://github.com/xuxueli/xxl-job/issues/2845  参考这个 可能是这个原因

**Comment by RedStone365** [comment]
> #2845 参考这个 可能是这个原因

感谢您的回答，确实是这个原因。
前段时间我们的某个数据同步任务报出了OOM异常，恰在那时相关的注册节点也消失了。目前我们的做法是优化自身代码，避免OOM的情况。

**Comment by RedStone365** [comment]
问题出现在 nacos-client.1.4.2版本，在1.4.3版本中进行了修复。我们升级到了1.4.3版本。
自此以来未发现过类似问题。
