### ISSUE TITLE
通过api操作任务

### ISSUE THREAD

**Issue by wangtl** [xuxueli/xxl-job#2827]
请问有通过api的方式，对任务进行创建、编辑、执行、删除等么。
我这边有个推送消息的需求，在给定的时间内去推送业务消息，但是不想自己再去实现一套任务调度。用xxl的话，无法通过控制台去创建任务，因为会有很多这样的推送任务，而且任务触发时间是不一样的，动态维护的，随时变化的。不可能手动的去控制台挨个创建任务。

**Comment by lanicc** [comment]
有rest api的呀

**Comment by Kenwangxr** [comment]
可以的，com.xxl.job.admin.controller.JobInfoController#add，模拟登录后直接调这个接口

**Comment by xuxueli** [comment]
参考 @Kenwangxr  的回复。
