### ISSUE TITLE
xxljob 性能问题

### ISSUE THREAD

**Issue by zhoufei1980** [xuxueli/xxl-job#2857]
提一个性能问题。当xxljob的日志表数据量大了起来。一个月数据量会达到2千万左右。每次任务运行前的sql就会变得非常的慢。
SELECT t.id
FROM xxl_job_log AS t
WHERE t.trigger_code = 200
AND t.handle_code = 0
AND t.trigger_time <= '2022-05-16 10:00:51.57'
AND t.executor_address NOT IN (
SELECT t2.registry_value
FROM xxl_job_registry AS t2
)
这个还可以通过索引调整来解决
象下面的这个sql。建议作者增加一个索引提示，不然每次要1分多钟。数据库的io全部都消耗在这个sql上面了
SELECT id FROM xxl_job_log
WHERE
!(
(trigger_code IN (0, 200) AND handle_code = 0)
OR
(handle_code = 200)
)
AND
alarm_status = 0

	ORDER BY id ASC
	LIMIT 1000
这个sql 会被强制使用主键索引。 因为order by id asc的存在。
建议修改为如下：
SELECT id FROM xxl_job_log IGNORE INDEX(PRIMARY)
WHERE
!(
(trigger_code IN (0, 200) AND handle_code = 0)
OR
(handle_code = 200)
)
AND
alarm_status = 0

	ORDER BY id ASC
	LIMIT 1000
可以大大的提升性能

**Comment by zhoufei1980** [comment]
hand_code的索引也需要调整。 要建立handle_code,trigger_code,alarm_status的复合索引。

**Comment by xuxueli** [comment]
你好，xxl-job支持日志动态清理能力，可以启用。如果有进一步优化思路，欢迎PR啊。
