### ISSUE TITLE
 关于路由策略里，一致性Hash的算法依赖参数是什么

### ISSUE THREAD

**Issue by szkissyh** [xuxueli/xxl-job#2859]
我想知道路由策略里一致性Hash的算法是按照IP、任务名称还是其他参数进行计算的。比如我知道nginx有三个选择

consistent_hash $remote_addr; 根据客户端IP进行映射（常用）
consistent_hash $request_uri; 根据客户端请求的uri进行映射（常用）
consistent_hash $args; 根据客户端请求携带的参数进行映射

**Comment by cc-nnqt** [comment]
具体实现在ExecutorRouteConsistentHash，是根据jobId来进行一致性hash计算的

**Comment by szkissyh** [comment]
> 具体实现在ExecutorRouteConsistentHash，是根据jobId来进行一致性hash计算的

谢谢

**Comment by szkissyh** [comment]
ok
