### ISSUE TITLE
失败的报警可不可以支持slack

### ISSUE THREAD

**Issue by baotuo** [xuxueli/xxl-job#286]
不用邮件通知，可以支持slack吗？

**Comment by Ryan-Miao** [comment]
自己写实现吧，看了代码，貌似很久没有重构过了

**Comment by xuxueli** [comment]
@baotuo  感谢关注！
自版本 v1.9.0 开始，已经为失败告警预留了告警扩展接口，可以参考文档自行扩展实现的啊。（代码位置："JobFailMonitorHelper.failAlarm"；）
