### ISSUE TITLE
关于GPL3协议能否就地商用部署的问题

### ISSUE THREAD

**Issue by YSSDG** [xuxueli/xxl-job#2899]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
云服务、就地使用
### Actual behavior
就地服务会对xxl-job做分发，现有协议（GPL3）对分发有约定，公司对该协议（GPL3）抱有谨慎态度，造成无法实际投入使用。
### Other information

作者，你好：
       本公司为客户提供能源管理类型的软件，部分软件需要调度服务，考虑选择一款优秀开源分布式调度服务，对Xxl-job非常的认可。
       但由于Xxl-job的License是GPL3，担心对其分发会造成法律方面的影响。
       现有几个问题
              第一：作者您使用GPL3，是为了避免像本公司类型的业务做二次分发吗？
              第二：该协议是否可以考虑修改？
              第三：如果进行分发，再不做二次开发的情况下，仅仅作为独立的调度服务，是否属于侵权行为。

以上，谢谢您！
施耐德电气，Guan

**Comment by lxb1742** [comment]
作者，你好:

  关于目前有这么都公司接入的情况，大家使用该调度平台都只是内部使用，没有做商业化的用途嘛？还有就是GPL3这个协议目前确实和GPL2有差异和争议，能否考虑进行开源协议变更了？

**Comment by xuxueli** [comment]
@YSSDG @lxb1742  感谢支持。
GPL 协议目的是保障软件自始至终都以开放源代码形式发布，保护社区开发成果不被窃取用作商业发售。

上述两种情况可以自由使用，以及非商业发售的大多数场景下，可以自由使用。如果有担心或需要，可以在官网申请免费的授权。

**Comment by YSSDG** [comment]
@xuxueli 
你好，作者：

我们现在有三种使用场景：云服务、sass服务和边缘侧；
这三种场景，能获得您个人的授权吗？

或者在哪里获取这三种情况的授权？Xxl-Job是有官网吗？

**Comment by lxb1742** [comment]
作者，感谢你的回复。我们调研了该框架，目前比较契合我们的业务场景，但是调度中心这里需要做前后端分离，以及前端页面需要重构和系统保持一致，目前提供的有这样的调度中心改造嘛？发自我的荣耀手机-------- 原始邮件 --------发件人： 许雪里 ***@***.***>日期： 2022年7月1日周五 14:21收件人： xuxueli/xxl-job ***@***.***>抄送： lxb1742 ***@***.***>, Mention ***@***.***>主    题： Re: [xuxueli/xxl-job] 关于GPL3协议能否就地商用部署的问题 (Issue #2899)

@YSSDG @lxb1742  感谢支持。

GPL 协议目的是保障软件自始至终都以开放源代码形式发布，保护社区开发成果不被窃取用作商业发售。

上述两种情况可以自由使用，以及非商业发售的大多数场景下，可以自由使用。如果有担心或需要，可以在官网申请免费的授权。

**Comment by xuxueli** [comment]
@YSSDG @lxb1742 
官网有联系邮箱，发邮件提供公司名称并说明，会免费针对公司授权。
https://www.xuxueli.com/page/community.html.

**Comment by OSSoftwareDev** [comment]
作者你好，我们公司这边一直在联系你获得xxl-job的授权，通过931591021@qq.com的邮箱一直联系不上，看到麻烦回复下

**Comment by wilson99** [comment]
作者你好，我们公司这边在联系你希望获得xxl-job的授权，通过 931591021@qq.com 的邮箱一直联系不上，看到麻烦回复下
