### ISSUE TITLE
执行器内嵌的jetty版本可否降低？

### ISSUE THREAD

**Issue by zhunian2003** [xuxueli/xxl-job#290]
目前项目使用的jdk7，而1.9.0版本内嵌的jetty支持1.8及以上，目前是将jetty换成低版本的了，不知是否有影响？

**Comment by xuxueli** [comment]
你好，目前（1.9.x）项目依赖 jdk 版本为 1.7。
可以查看下pom依赖，保持了pom依赖中的jetty版本一致即可。如果存在jetty版本覆盖，需要单独引入对应版本。
