### ISSUE TITLE
1.9.1 升级后图表出不来

### ISSUE THREAD

**Issue by himanhimao** [xuxueli/xxl-job#291]
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
/xxl-job-admin/triggerChartDate

**Comment by himanhimao** [comment]
清除缓存搞定了

**Comment by xuxueli** [comment]
@himanhimao 
感谢关注和反馈啊！
报表JS有缓存，清理浏览器缓存即可。后续升级版本时候会注意这个问题，JS要加版本号了 ：）
