### ISSUE TITLE
期待有任务超时报警机制

### ISSUE THREAD

**Issue by liuluo129** [xuxueli/xxl-job#292]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1

### Expected behavior
期待可以设置任务执行的超时时间，调度之后，任务超时的话报警

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
任务超时控制已经加入TODO列表，将会排期跟进。
计划在任务超时后，主动终止任务，并且发送告警邮件。

**Comment by liuluo129** [comment]
我提了一个pr，有感兴趣的可以试一下
https://github.com/xuxueli/xxl-job/pull/293

**Comment by xuxueli** [comment]
你好，PR已经 Merge，非常感谢！
该特性已经在版本 v1.9.2 (迭代中)，可以 pull master 分支预览，将会不日发布；
