### ISSUE TITLE
任务阻塞

### ISSUE THREAD

**Issue by jianzhiunique** [xuxueli/xxl-job#295]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9

### Actual behavior
使用scriptJobHandler时，由于程序问题偶然导致程序阻塞不能退出，此时如果选用单机串行，会导致所有后续任务一直等待，任务得不到执行，并且无法及时得知此情况。
```
        DefaultExecutor exec = new DefaultExecutor();
        exec.setExitValues(null);
        exec.setStreamHandler(streamHandler);
        int exitValue = exec.execute(commandline);  // exit code: 0=success, 1=error 这里无法退出时
        return exitValue;

```
希望能够增加任务超时机制
### Other information

**Comment by xuxueli** [comment]
你好，任务超时告警已经加入TODO排期，可以关注ISSUE了解进度：https://github.com/xuxueli/xxl-job/issues/292
