### ISSUE TITLE
job log report 新增报告时判断问题

### ISSUE THREAD

**Issue by cuisuqiang** [xuxueli/xxl-job#2953]
代码：JobLogReportHelper中第75行，判断更新返回值是否大于0，否则就执行新增，这个判断逻辑是不严谨的。
因为在MySQL中，如果更新的内容和原来的值一样，那么就会返回0，此时不是数据不存在，而是没有更新任何内容，此时如果执行新增，就会报错。

`06:28:22.377 logback [xxl-job, admin JobLogReportHelper] ERROR c.x.j.a.c.thread.JobLogReportHelper - &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; xxl-job, job log report thread error:{}
org.springframework.dao.DuplicateKeyException: 
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '2022-08-16 08:00:00' for key 'xxl_job_log_report.i_trigger_day'
; Duplicate entry '2022-08-16 08:00:00' for key 'xxl_job_log_report.i_trigger_day'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '2022-08-16 08:00:00' for key 'xxl_job_log_report.i_trigger_day'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)`

处理意见，在小于1时，再增加一个查询，根据triggerDay字段统计

XxlJobLogReportMapper.xml中：
`<select id="queryLogReportByTriggerDay" resultType="java.lang.Integer">
    SELECT COUNT(*) FROM xxl_job_log_report WHERE `trigger_day` = #{triggerDay}
</select>`

XxlJobLogReportDao中：
`public int queryLogReportByTriggerDay(XxlJobLogReport xxlJobLogReport);`

处理时：

`int ret = XxlJobAdminConfig.getAdminConfig().getXxlJobLogReportDao().update(xxlJobLogReport);
if (ret < 1) {
	ret = XxlJobAdminConfig.getAdminConfig().getXxlJobLogReportDao().queryLogReportByTriggerDay(xxlJobLogReport);
	if(ret < 1) {
		XxlJobAdminConfig.getAdminConfig().getXxlJobLogReportDao().save(xxlJobLogReport);
	}
}`

END

**Comment by maTuaner** [comment]
mysql连接参数把useAffectedRows去掉或者设置为false就好了.
