### ISSUE TITLE
linux环境下 Client-error:unknown code for readObject at 0x20，同一套代码在windows环境却无任何异常问题。

### ISSUE THREAD

**Issue by ie7shop** [xuxueli/xxl-job#297]
您好，项目中在本地环境一直没有问题，部署到linux环境下就出现这个错误。对应的则是执行器管理里面无法自动注册执行器，必须通过手动配置对应的ip:port，才能找到执行器并进行定时任务执行。
可是，就算手工注册后，以下的错误还是同样会出现。不知道是我配置不对还是需要什么特定的设置呢，请您指教一下，谢谢了！
![image](https://user-images.githubusercontent.com/6293184/36788675-c8c0cd1a-1cc9-11e8-9a31-109d4211a6d4.png)

**Comment by xuxueli** [comment]
你好，从Log看是因为执行器回调失败导致。
确认下回调地址配置是否正确？
执行器与调度中心是否可以相互ping的通？
回调地址对应的应用是否启动？
