### ISSUE TITLE
自定义JobHandler 无法识别

### ISSUE THREAD

**Issue by cqliuys** [xuxueli/xxl-job#298]
@JobHandler(value="reportHandler")

![image](https://user-images.githubusercontent.com/17268775/36831809-f2d5eb04-1d63-11e8-8e61-090618332654.png)
![image](https://user-images.githubusercontent.com/17268775/36831824-03cb65d8-1d64-11e8-976c-dfa4e1b4d24e.png)
  使用例子的 value 能执行成功  ，如果使用自己的value 就失败 一直not  found！

![image](https://user-images.githubusercontent.com/17268775/36831873-410aa49a-1d64-11e8-8125-b0d29cbfbe47.png)

**Comment by xuxueli** [comment]
你好，推测这个Handler没有被扫描到Spring容器中，可以确认下扫描路径重新编译下啊。
