### ISSUE TITLE
2.3.1版本accessToken验证有bug

### ISSUE THREAD

**Issue by he-jialin** [xuxueli/xxl-job#3008]
在2.3.1版本部署到docker里面会抛错：
registryResult:ReturnT [code=500, msg=The access token is wrong., content=null]
执行器和控制器实际给的accessToken值是空，参数不变的情况下，更换容器版本为2.3.0就不会报这个错

**Comment by xiaoyuwang1987** [comment]
不知2.3.1，我2.2.0也出现了这个情况，怎么办

**Comment by qq253498229** [comment]
2.4.0也有

**Comment by he-jialin** [comment]
回来报告一下，降低版本到xuxueli/xxl-job-admin:2.3.0，以上好像会出现这问题。最新的不知道的了。2.3.0版本没有这错误

**Comment by huqiangyang** [comment]
各位老师请问2.3.1的这个问题是否有解决方案，之能通过降版本吗
