### ISSUE TITLE
任务暂停出现偶发性的延迟

### ISSUE THREAD

**Issue by LeoYangbs** [xuxueli/xxl-job#302]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
调度中心,点击"暂停",任务应当立即停止.
### Actual behavior
任务会重复的执行一段时间.
### Steps to reproduce the behavior
偶发性, 重复点击暂停与恢复按钮,大概有10%的几率,暂停 任务会延迟生效.
### Other information
暂停 功能延迟生效的日志面板:
<img width="677" alt="default" src="https://user-images.githubusercontent.com/28640809/37197075-29e31bf2-23b4-11e8-9ba6-4ddb1e206970.png">

**Comment by xuxueli** [comment]
你好，任务暂停和恢复，指的是是否触发新的任务。已经触发成功的任务仍然会正常执行。

**Comment by LeoYangbs** [comment]
是对同一任务,由执行状态切换到暂停状态后,发现任务会继续执行一段时间,之后才会真正暂停.
