### ISSUE TITLE
WARN  o.s.web.servlet.PageNotFound - No mapping for POST /xxl-job-admin/api

### ISSUE THREAD

**Issue by MaiJiantian** [xuxueli/xxl-job#3023]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0-2.3.1

### Expected behavior
无异常

### Actual behavior
docker 异常：
WARN  o.s.web.servlet.PageNotFound - No mapping for POST /xxl-job-admin/api
xxl-job控制台异常：
DataTables warning: table id=job_list - Requested unknown parameter 'jobCron' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4

### Steps to reproduce the behavior
无特殊操作

### Other information
本地docker部署无异常，阿里云ecs docker出现异常，执行参数一致

**Comment by wulangcode** [comment]
检查一下自己的表初始化sql有没有问题，示例数据不要删除

**Comment by MaiJiantian** [comment]
> 检查一下自己的表初始化sql没有问题，示例数据不要删除

**Comment by MaiJiantian** [comment]
> 检查一下自己的表初始化sql没有问题，示例数据不要删除

连接的是
