### ISSUE TITLE
xxl-job <=2.3.1存在SSRF漏洞

### ISSUE THREAD

**Issue by lizhuangs** [xuxueli/xxl-job#3039]
xxl-job <=2.3.1存在SSRF漏洞

### Which version of XXL-JOB do you using?
2.3.1

### Other information
[https://www.oscs1024.com/hd/MPS-2022-60127](https://www.oscs1024.com/hd/MPS-2022-60127)

**Comment by xuxueli** [comment]
问题已修复，相关代码已推动。
