### ISSUE TITLE
调度中心执行任务的时间不对？调度中心和业务系统已经当前服务器的时区已经同步

### ISSUE THREAD

**Issue by JssDream** [xuxueli/xxl-job#3044]
Please answer some questions before submitting your issue. Thanks!
调度中心执行任务的时间不对，
描述：
    1.调度中心和业务都在一个服务器，时区：都是东四区，调度中心、业务系统、服务器、数据库都是在东四区，然后调度中心新增任务执行时间是每天0点，正常情况应该是东四区的0点，但是执行时间是东八区时区的，早了4个小时。
### Which version of XXL-JOB do you using?
version 2.3.1
### Expected behavior
执行时间应该是按照东四区的时间
### Actual behavior
执行时间是东八区时区的，早了4个小时
### Other information
1.调度中心和所在机器时间一致
![image](https://user-images.githubusercontent.com/24471999/204083731-196cc06b-66f5-42fe-b304-42adf00a0e19.png)

2.调度中心的连接数据的时区也成东四区了,，使用dockers部署的
xxxx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Dubai
3.执行的记录
![image](https://user-images.githubusercontent.com/24471999/204083775-078f32a8-8312-4848-b066-9ac4d44ab98d.png)

![image](https://user-images.githubusercontent.com/24471999/204083763-493b9f95-696e-4899-bc52-5669e9419efe.png)

**Comment by je1lylee** [comment]
see https://github.com/xuxueli/xxl-job/issues/1940

**Comment by JssDream** [comment]
已解决，docker启动调度中心的时候添加了参数 -e TZ="Asia/Dubai"，就行了
