### ISSUE TITLE
服务启动报循环引用

### ISSUE THREAD

**Issue by zhonghuafy** [xuxueli/xxl-job#3057]
springboot 2.6.13, xxl-job版本 2.1.2。
XxlJobConfig文件：
```
    @Configuration
    @Slf4j
    public class XxlJobConfig {

    @Value("${xxl.job.admin.addresses}")
    private String adminAddresses;

    @Value("${xxl.job.executor.appname}")
    private String appName;

    @Value("${xxl.job.executor.ip}")
    private String ip;

    @Value("${xxl.job.executor.port}")
    private int port;

    @Value("${xxl.job.accessToken}")
    private String accessToken;

    @Value("${xxl.job.executor.logpath}")
    private String logPath;

    @Value("${xxl.job.executor.logretentiondays}")
    private int logRetentionDays;

    @Bean
    public XxlJobSpringExecutor xxlJobExecutor() {
        log.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppName(appName);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }
 } 
```

启动报错：
escription:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  xxlJobExecutor defined in class path resource [com/xx/bc/xxl/job/simple/config/XxlJobConfig.class]
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

其中一个解决方案可以是设置spring.main.allow-circular-references为true。但是想知道为什么会出现这个错误，如何从代码上修正。

**Comment by maozhitao12450** [comment]
com.xxl.job.core.executor.impl.XxlJobSpringExecutor 这个类在2.1.2时有使用问题 使用  InitializingBean 作为任务初始化的标记,任务初始化过程中又遍历了所有的bean,其中包含他自己,但是afterPropertiesSet这个过程并没有完结,故自己这个对象并未完成bean的初始化,所以spring就认为出现了循环引用.

解决方案: 
   升级到2.2.0以上
   或者拉取 git version 266593318022d7e9c9fbce0ceb95774de6b73595

**Comment by zhonghuafy** [comment]
感谢！

**Comment by xiwusheng2015** [comment]
在springboot 1.5可以正常启动在 2.6下就不行了，1.5对比2.6在InitializingBean 处理上，Spring Boot 2.x系列则基于Spring Framework 5.x系列，特别是Spring Boot 2.6是基于Spring Framework 5.3.x。在这个版本中，Spring进一步加强了对Bean依赖的检测，进一步严格化了Bean循环引用的处理，增加了更严格的校验，以提高整体应用程序的稳定性和可维护性
