### ISSUE TITLE
多个依赖任务之间传值问题

### ISSUE THREAD

**Issue by hitman9099** [xuxueli/xxl-job#307]
多个依赖任务,上游任务无法将一些结果传递到下游任务,导致一些任务我发进行流畅串联.

**Comment by xuxueli** [comment]
你好，任务传参可以自己定制实现。
触发子任务逻辑代码位置为 “com.xxl.job.admin.service.impl.AdminBizImpl#callback(com.xxl.job.core.biz.model.HandleCallbackParam)”，可以自行修改。
-
