### ISSUE TITLE
任务执行内部获取当前任务基本信息,如JOB的ID

### ISSUE THREAD

**Issue by hitman9099** [xuxueli/xxl-job#308]
在新建这个任务时,在任务内部需要获取任务的ID和任务的名称,作为处理任务的一些要素

**Comment by xuxueli** [comment]
你好，类似需求比较特殊，可以自行定制实现啊。
可以在任务触发时，主动传递任务信息即可，定制代码位置见：com.xxl.job.admin.core.trigger.XxlJobTrigger
