### ISSUE TITLE
持续输出某一天的异常日志

### ISSUE THREAD

**Issue by UltramanNoa** [xuxueli/xxl-job#3083]
最近发现xxljob出现输出2月2日的异常日志 每天大概输出50多g的日志
### Which version of XXL-JOB do you using?
version 2.1.2

### Expected behavior
![1](https://user-images.githubusercontent.com/16308510/216916004-0af68770-7f2e-4f06-ae07-22b09f49f92f.jpg)
![2](https://user-images.githubusercontent.com/16308510/216916064-d9ce4bae-4815-4d17-a96e-ddd30d60e527.jpg)
![3](https://user-images.githubusercontent.com/16308510/216917169-3bf2cb6d-319e-4dad-91de-ed732a394180.png)
![4](https://user-images.githubusercontent.com/16308510/216917319-b58a3cda-15f1-4f9b-8d4d-526712530005.png)

xxljoblog表里已经没有图上这些日志id了，为什么callback的还是这些日志id  

logid 除了保存在数据库里还有其他方式存储吗，我要怎么跳过或清理这几个异常的logid呀.

**Comment by justhxc** [comment]
我们也遇到了，大量错误信息批量回调导致http超时导致的。解决方法：关闭admin和executor然后删除xxl-job-log表错误数据，/data/applogs/xxl-job/jobhandler和/var/log/jsw/jobhandler下的日志后重启。
