### ISSUE TITLE
XSS 漏洞,在页面中嵌入客户端脚本

### ISSUE THREAD

**Issue by weibingtie** [xuxueli/xxl-job#3091]
![image](https://user-images.githubusercontent.com/26989457/219533806-01e6b70c-2374-4b44-a3fa-532b729545ba.png)
![image](https://user-images.githubusercontent.com/26989457/219533880-c65cda40-bc8b-43ea-8ec3-d33abde64b47.png)

**Comment by weibingtie** [comment]
2.3.0版本

**Comment by xuxueli** [comment]
已修复
