### ISSUE TITLE
任务异常导致磁盘占满

### ISSUE THREAD

**Issue by dudemonkey** [xuxueli/xxl-job#31]
遇到一个莫名其妙的问题。也没报异常日志，感觉像是任务阻塞导致占用资源不释放。
![image](https://cloud.githubusercontent.com/assets/6066358/24077197/dbde3eb4-0c80-11e7-9507-ca053d6e3730.png)
FAIL时查看执行日志，没有任何日志信息
![image](https://cloud.githubusercontent.com/assets/6066358/24077205/21d95aa2-0c81-11e7-961c-a774c4eb9a09.png)

**Comment by dudemonkey** [comment]
oracle的磁盘占用100%，后来我重启了应用后恢复正常。真正磁盘占用才6%

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
问题无法复现啊。执行器只会对执行器配置中日志路径下读写文件，可以确认下磁盘空间占用。

**Comment by zhuSilence** [comment]
您好：
在测试执行器的时候出现这个问题，相关的路径都生成成功了，不知道这为何报错。没有在gluesource同级生成每天的文件夹。望指教！



silence
1347023180@qq.com

**Comment by xuxueli** [comment]
你好，没有生成Log文件，可能是没有改路径的读写权限，可以确认下或者排查下执行器Log。
