### ISSUE TITLE
Logback<=1.2.7远程执行代码漏洞

### ISSUE THREAD

**Issue by VHTK** [xuxueli/xxl-job#3134]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

### Expected behavior
Logack存在远程代码执行漏洞，有编辑配置文件所需权限的攻击者可以制作恶意配置，允许执行从LDAP 服务器加载的任意代码

**Comment by xuxueli** [comment]
非系统问题，人工行为
