### ISSUE TITLE
执行器启动失败，但是有没有任何报错信息。。。。

### ISSUE THREAD

**Issue by wgb1990** [xuxueli/xxl-job#314]
![image](https://user-images.githubusercontent.com/7124162/37553331-11bc2534-2a01-11e8-8eb4-be2418eec1d1.png)
启动的时候并没有报任何启动失败的信息，而且该机器也没有开启防火墙
![image](https://user-images.githubusercontent.com/7124162/37553345-509a3eee-2a01-11e8-97ea-4daca8849a95.png)
telnet 不通

**Comment by wgb1990** [comment]
![image](https://user-images.githubusercontent.com/7124162/37553380-ebd9f002-2a01-11e8-8cc4-9320b14b2d60.png)
netstat 端口号已经被暂用了

**Comment by wgb1990** [comment]
![image](https://user-images.githubusercontent.com/7124162/37553387-0fd1d934-2a02-11e8-9ba3-78391ecb5b05.png)
并且端口号已经被暂用

**Comment by xuxueli** [comment]
你好，可以登录该机器，ping一下 "localhost:9998" 确认是否真正启动啊。如果确定启动的情况下，问题只可能出在网络上了。
