### ISSUE TITLE
有没有计划开发其他语言的执行器？

### ISSUE THREAD

**Issue by julywind** [xuxueli/xxl-job#315]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2-SNAPSHOT
### Expected behavior
期望支持其他语言的执行器，比如nodejs
### Actual behavior
只支持gule模式，但是在gule模式下似乎不能支持导入三方库
### Steps to reproduce the behavior
无
### Other information

**Comment by xuxueli** [comment]
你好，可以通过 “GLUE-Nodejs” 模式开发NodeJS任务。
如需导入第三方库，在目标服务器上安装即可。因为NodeJS脚本最终在执行器机器上运行。
