### ISSUE TITLE
调度中心状态显示 ERROR 但是执行没问题

### ISSUE THREAD

**Issue by edanel** [xuxueli/xxl-job#316]
调度中心状态显示 ERROR 但是执行没问题。
这是什么情况呢？

**Comment by edanel** [comment]
![wechatimg1874](https://user-images.githubusercontent.com/10301830/37570391-3eb3e07a-2b2a-11e8-951e-7aebfa405231.jpeg)

**Comment by xuxueli** [comment]
你好，任务在quartz底层表中产生了脏数据或者JobBean在集群节点不一致，均可能导致该问题，删除重新创建即可。
