### ISSUE TITLE
如果我jobHandler里用的线程池处理，两次不同的任务，但是因为是同一个线程处理的，日志会继续拼在上一个任务里

### ISSUE THREAD

**Issue by shanyuguangyun** [xuxueli/xxl-job#3199]
![image](https://github.com/xuxueli/xxl-job/assets/39542575/adb048fa-1dd3-497e-a511-dde833d8990b)

如图，我上一次任务日志finish后，下一次任务因为还是用的线程池里的线程处理了子任务，但是日志会继续拼在上一次的任务日志里。

**Comment by shanyuguangyun** [comment]
应该是我理解错了，admin的log按老哥的意思是不是就只是记录任务状态相关的日志，然后数据处理的还是记在logback里，这样不会有线程池的问题及日志分片的问题了。

**Comment by shanyuguangyun** [comment]
应该是我理解错了，admin的log按老哥的意思是不是就只是记录任务状态相关的日志，然后数据处理的还是记在logback里，这样不会有线程池的问题及日志分片的问题了。

**Comment by shanyuguangyun** [comment]
还是将程序处理日志记在了logback里，然后xxl的日志就用来记录xxl是否正常执行而已。 两个分离开了

**Comment by sdhzwc** [comment]
> 还是将程序处理日志记在了logback里，然后xxl的日志就用来记录xxl是否正常执行而已。 两个分离开了

我的实践是不用线程池管理，日志就不会这种情况
