### ISSUE TITLE
请问xxl-job是否支持一直运行的任务？

### ISSUE THREAD

**Issue by haojiubujian** [xuxueli/xxl-job#322]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
请问xxl-job是否支持一直运行的任务？
### Actual behavior
不确定
### Other information

**Comment by xuxueli** [comment]
你好，守护方式一直运行，消费消息，其实属于MQ的范畴，可以参考下 XXL-MQ 啊！
