### ISSUE TITLE
springboot 加入xxl-core 定义JobHandler时启动失败

### ISSUE THREAD

**Issue by fengxka** [xuxueli/xxl-job#323]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0/1.9.2
### Expected behavior
应用正常启动
### Actual behavior
![image](https://user-images.githubusercontent.com/10057892/37894149-d9d0a2ba-310f-11e8-9fb7-fa59f61fd079.png)
### Steps to reproduce the behavior
1.pom package改为war 
2.war放到tomcat中
3.spring-boot version:1.5.8.RELEASE/1.5.10.RELEASE
### Other information
将自定义JobHandler的'@JobHandler'注解注释掉重复上述步骤则能正常启动

**Comment by xuxueli** [comment]
从Log看，JobHandler命名重复导致的。

**Comment by fengxka** [comment]
问题已解决,最终是因为总共写了2个SpringBootServletInitializer实现类,导致了项目启动的时候,spring的环境初始化2次,导致重复注册;删除其中一个已能正常启动
