### ISSUE TITLE
params的作用不大

### ISSUE THREAD

**Issue by Sabirjan** [xuxueli/xxl-job#324]
JobHandler 的params参数作用不大啊，因为固定的参数。 希望改成动态的。
比如：有1万个订单号，每秒处理10个订单，我想把每个订单号参数形式发给JobHandler 。。。
现在不知道怎么传过去

**Comment by xuxueli** [comment]
你好，任务参数目前取自任务预先配置的值。
不过，动态Params特性已经加入TODO，将会排期实现。
但是，这种场景是典型的MQ消息消费场景，推荐以MQ的方案解决，可以参考下项目 XXL-MQ 啊。
