### ISSUE TITLE
适配国产数据库

### ISSUE THREAD

**Issue by EightMonth** [xuxueli/xxl-job#3240]
是否可以支持一款国产数据库，达到信创要求。现在nacos已无法在全信创环境中使用，希望可以支持。

**Comment by zuiyu-main** [comment]
我提交了一个pull request，适配了达梦和人大金仓

**Comment by it-noob** [comment]
nacos 不是已经适配了达梦么，想了解，为什么在信创环境中已经无法使用了

**Comment by EightMonth** [comment]
我写错了，我想表达的意思是，xxl-job已无法在全信创环境中使用，希望可以支持
