### ISSUE TITLE
2.3.0升级2.4.0问题

### ISSUE THREAD

**Issue by zhzhf233** [xuxueli/xxl-job#3242]
麻烦问一下，由于2.3.0版本存在中高危漏洞。通过监测2.4.0版本验证漏洞不存在。
如果从2.3.0版本直接升级至2.4.0版本，会存在兼容问题吗？

**Comment by myVictor** [comment]
2.4.0漏洞更多

**Comment by xuxueli** [comment]
业务逻辑不存在兼容逻辑。需要升级数据库脚本，之后客户端、服务端依次升级发布即可。
