### ISSUE TITLE
安全组扫描到执行器端口服务存在信息泄露漏洞

### ISSUE THREAD

**Issue by 383941767a** [xuxueli/xxl-job#3247]
以下是安全组的漏洞报告：
检测类型：系统漏洞扫描

漏洞类型/检查类型：信息泄露

漏洞ID：SF-2022-00684

漏洞类型/检查项名称：允许HTTP TRACE / TRACK方法【原理扫描】

描述/检查点描述：远程Web服务器支持TRACE和/或TRACK方法。 TRACE和TRACK是用于调试Web服务器连接的HTTP方法。

解决方案：如果不使用该服务就禁用它

请问大家遇到此问题吗？怎么解决的呢

**Comment by WilliaJing** [comment]
您好，请问您解决了吗？

**Comment by xuxueli** [comment]
你好，问题无法复线。请完善信息，进一步复线步骤
