### ISSUE TITLE
请问怎么设置在同一个job间隔期间内，当上一个job执行完成之后再去调度下一个job

### ISSUE THREAD

**Issue by fddOs** [xuxueli/xxl-job#325]
假如一个job的执行时间是10秒，5秒执行一次，那么下一次job的执行之间应该是15秒之后，这个xxl-job支持吗?

**Comment by xuxueli** [comment]
你好，感谢关注！
这种情况是支持的，这是典型的任务阻塞情况，可以文档查看任务阻塞的特性支持和提供的策略并选择使用。

**Comment by fddOs** [comment]
好的 谢谢
