### ISSUE TITLE
调度中心登录存在明文传输的漏洞

### ISSUE THREAD

**Issue by emolwy** [xuxueli/xxl-job#3251]
REQUEST:
POST /xxl-job-admin/login HTTP/1.0
X-Forwarded-Port: 443
Host: xxljob.xxxxx.cn
X-Real-IP: 10.20.18.26
X-Forwarded-For: 10.20.18.26
X-Forwarded-Proto: https
Connection: upgrade
Content-Length: 38
sec-ch-ua: &quot;Not.A/Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;114&quot;, &quot;Google Chrome&quot;;v=&quot;114&quot;
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
sec-ch-ua-platform: &quot;Windows&quot;
Origin: https://xxljob.xxxxx.cn
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://xxljob.xxxxx.cn/xxl-job-admin/toLogin
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Accept-Encoding: gzip, deflate

userName=admin&amp;password=Nq%@Nk&9RQnrV5  **##账号及密码明文传输，应加密后再传输，避免中间人直接获取。**

RESPONSE:
HTTP/1.1 200 
Date: Tue, 18 Jul 2023 13:46:02 GMT
Content-Type: application/json
Connection: close
Vary: Accept-Encoding
Set-Cookie: XXL_JOB_LOGIN_IDENTITY=7b226964223a312c22757365726e616d65223a2261646d696e222c2270617373776f7264223a226333393536336431343465623761383632623138656337313765313263333536222c22726f6c65223a312c227065726d697373696f6e223a6e756c6c7d; Path=/; HttpOnly

{&quot;code&quot;:200,&quot;msg&quot;:null,&quot;content&quot;:null}

**Comment by xuxueli** [comment]
建议升级 https 进行防护。
