### ISSUE TITLE
前面的任务执行失败，一直没有执行完，后边的任务到点的任务都不能执行？

### ISSUE THREAD

**Issue by luyee** [xuxueli/xxl-job#328]
比如1点的任务一直在执行。后边2，3，4点。。。的任务都在执行中。。就是都跑不完

**Comment by xuxueli** [comment]
你好，感谢关注！
你好，这种情况是典型的任务阻塞情况，可以参考下文档任务阻塞的策略介绍啊。
在选择单机串行情况下，会FIFO方式串行执行，如果不希望串行执行，选择非串行策略即可。
