### ISSUE TITLE
xxl-job如何调度Python有没有相关Demo?

### ISSUE THREAD

**Issue by ColorfulGhost** [xuxueli/xxl-job#329]
新手 ，我现在有一个项目需要定时调度执行，获取异常日志或并发 ，我看文档这一部分关于Python或者其它语言实现方法好像并不是很理解...如何实现调度Python任务

**Comment by xuxueli** [comment]
你好，感谢关注！
可以参考下 “Glue（Python）”模式任务，新建任务的时候选择该模式，然后在Web IDE中开发python代码即可。
新建python任务的时候，会初始化demo代码，可以部署体验下。

**Comment by zhaoziming** [comment]
调用python的时候无法选择版本吧?
