### ISSUE TITLE
关于定时任务配置每秒执行的问题

### ISSUE THREAD

**Issue by keyang-wu** [xuxueli/xxl-job#3291]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?   
2.3.1
### Expected behavior
如果想配置一个每秒执行一次的定时任务（job1），看源码好像达不到这个要求

在scheduleThread中，如果下一次出发时间在5秒以内，那么会加入一个时间轮中(ringData)，但是只加入一次，

在下一次调度线程执行之前，那这个job1在5秒时间内只执行了两次（一次调度线程，一次时间轮线程）

<img width="1198" alt="image" src="https://github.com/xuxueli/xxl-job/assets/54386652/8075eaf0-b98c-4edb-adf8-f1b8d166d2d8">

或者说有其他机制保证定时任务可以每秒钟执行？
大佬们能不能帮忙解答一下这个问题

**Comment by szx1** [comment]
解决了吗，我认为while应该是没问题的，我也准备这么干

**Comment by JimmyAndZzZ** [comment]
机智
