### ISSUE TITLE
期待有个能传递动态参数的功能

### ISSUE THREAD

**Issue by sc750531323** [xuxueli/xxl-job#330]
在批处理任务中，比如今天跑昨天的数据，那么作为每天的调度任务，就需要每天执行的时候传给我的xxx.sh文件一个昨天的日期作为数据处理的时间，比如说传递一个类似于‘YYYYmmDD-1’这种，然后调度系统能够解析时间，并把这个时间传给sh脚本

**Comment by talywy** [comment]
这个功能我厂内部有个系统有类似的，这种场景可以换个思路，在你的xxx.sh脚本中获取时间进行处理。不过如果有这个动态参数功能的话，会让使用场景变得更加灵活多变。

**Comment by xuxueli** [comment]
你好，感谢反馈！
版本 v1.9.2（迭代中）已经支持动态参数，支持在触发任务时动态传递任务参数。上述提到的类似 “模板参数” 的需求待定。
