### ISSUE TITLE
response content invalid([{"logId":22158643,"logDateTim":1694503442664,"executeResult":{"code":500,"msg":"Task not registered"},

### ISSUE THREAD

**Issue by flashliusz** [xuxueli/xxl-job#3303]
我是部署在k8s上，这个执行很早就注册了，现在这个执行器上的其他任务都可以正常跑，我新建了一个任务选择执行一次的时候报错
任务触发类型：手动触发
调度机器：10.20.1.150
执行器-注册方式：自动注册
执行器-地址列表：[http://10.20.1.233:9999]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://10.20.1.233:9999
code：500
msg：xxl-rpc remoting (url=http://10.20.1.233:9999/run) response content invalid([{"logId":22158643,"logDateTim":1694503442664,"executeResult":{"code":500,"msg":"Task not registered"},"handleCode":500,"handleMsg":"Task not registered"}]).

**Comment by flashliusz** [comment]
这个任务我在数据库的xxl-job-info表中是能找到对应信息的，我的版本是xuxueli/xxl-job-admin:2.3.0

**Comment by teaGod-s** [comment]
我遇到了同样的问题，不过不是k8s部署。排查后发现是执行器的问题，跟其他执行器用的同一个端口，被其他执行器抢占了端口。
