### ISSUE TITLE
XxlJobInfoDao.scheduleUpdate()方法sql需要增加条件为trigger_status=1的条件来避免并发操作

### ISSUE THREAD

**Issue by 965644856** [xuxueli/xxl-job#3306]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### 问题描述
1.JobScheduleHelper获取调度任务信息保存在scheduleList，此时批量获取到的任务状态是启动状态“1”，即XxlJobInfo对象的triggerStatus属性值为“1”；
2.在任务开始循环调度，到修改下一次执行时间，即XxlJobInfoDao.scheduleUpdate()方法前，中间过程，页面操作关闭了scheduleList中包含的任务A，此时数据库任务对应的状态是停止状态“0”，即xxl_job_info表的trigger_status字段值为“0”；
3.当任务调度触发完成，任务对象信息XxlJobInfo对象的triggerStatus值是“1”，执行XxlJobInfoDao.scheduleUpdate()方法，将原本关闭的任务修改成“运行”状态，导致任务被自动开启。

问题：XxlJobInfoDao.scheduleUpdate()方法sql是否需要增加条件为trigger_status=1的条件来避免3中的“并发”操作？

###截图
![clipbord_1695188485704](https://github.com/xuxueli/xxl-job/assets/20923724/6173eb08-23c9-4a1e-a553-3498e70666e6)
![clipbord_1695188706268](https://github.com/xuxueli/xxl-job/assets/20923724/209de586-a492-4350-9f21-ed58873cf064)
![clipbord_1695188630918](https://github.com/xuxueli/xxl-job/assets/20923724/c3a68229-d071-439f-b826-0a919851b0d4)
![clipbord_1695190878692](https://github.com/xuxueli/xxl-job/assets/20923724/ad881c7e-6521-425b-b2d2-2e46e6bae276)

**Comment by lushimin** [comment]
update的sql不会去修改trigger_status字段，没有并发问题吧

**Comment by veritaspei** [comment]
![image](https://github.com/user-attachments/assets/4efec661-7201-45f2-9a1d-f93e13e3e05f)
你这样改如果真想把trigger_status置为0的时候就失效了。

应该这样改吧？

![企业微信截图_17261345611358](https://github.com/user-attachments/assets/8c866729-3ed9-4950-ab69-40f8fad8bd01)

**Comment by xuxueli** [comment]
你好，修复代码已推送master分支，将随后续新版本一并发布
