### ISSUE TITLE
不同周期的任务依赖及任务依赖图执行状况显示

### ISSUE THREAD

**Issue by sc750531323** [xuxueli/xxl-job#331]
期待如下功能：
1.可以查看一个任务的子任务，父任务的依赖关系图。并且可以显示这张图中这次调度执行到了哪里，哪个节点失败了。
2.可以添加不同任务周期的依赖，比如昨天又24个小时任务，昨天的天任务依赖于这24个小时任务的完成才开始执行天任务。

**Comment by xmw200** [comment]
1.可以查看一个任务的子任务，父任务的依赖关系图。

这个确实是非常重要，也是急需的一个特性。期待这个功能。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
