### ISSUE TITLE
jdk1.7打包失败如何解决

### ISSUE THREAD

**Issue by ColorfulGhost** [xuxueli/xxl-job#332]
`[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:repackage (default) on project xxl-job-executor-sample-springboot: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:repackage failed: Unable to load the mojo 'repackage' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/springframework/boot/maven/RepackageMojo : Unsupported major.minor version 52.0`

**Comment by xuxueli** [comment]
你好，这是SpringBoot版本sample项目依赖版本问题导致的。已经修复并推送master，将在下个版本一同发布。

在 “<artifactId>spring-boot-maven-plugin</artifactId>” 依赖中强制添加版本号配置 “<version>${spring-boot.version}</version>” 即可。
