### ISSUE TITLE
为什么自动会写出脚本，是不是有后门？

### ISSUE THREAD

**Issue by myVictor** [xuxueli/xxl-job#3325]
阿里云提示我们对外有dos攻击行为，查看了目录位置发现自动会生成windows和linux的脚本文件。

![24a745ee37b9afb662ee0e217682243](https://github.com/xuxueli/xxl-job/assets/7285684/1c102a50-60e7-44ef-86ea-dd312f31b8df)

![f1288327d8357019bc277fce436eee4](https://github.com/xuxueli/xxl-job/assets/7285684/083abae7-f14b-44f4-9e91-7c6b33d1d1d0)

![48c2b484a13eb363d73f738b0d5614e](https://github.com/xuxueli/xxl-job/assets/7285684/b879b923-b24c-4e9f-bc3b-b703e064c16f)

生成的脚本文件会自动下载远程文件，做dos攻击
![image](https://github.com/xuxueli/xxl-job/assets/7285684/08a2e154-16d8-4b84-a5e8-82274241f120)

**Comment by GuiLinDi** [comment]
我的服务器也出现了这个问题

**Comment by XXMY** [comment]
请问你安装的是什么版本的？

**Comment by Jack724** [comment]
开鉴权

**Comment by Halted** [comment]
配置accesstoken

**Comment by Halted** [comment]
配置accesstoken。 禁用wget和curl

**Comment by qihboy** [comment]
@Jack724 @Halted  How?

**Comment by a870368162** [comment]
是不是公网可以访问你们的xxl-job-admin

**Comment by 75ACOL** [comment]
真的有人会把这种项目放在公网上面执行么？

**Comment by myVictor** [comment]
我放在公网上，现在关闭到内网了
