### ISSUE TITLE
API调用

### ISSUE THREAD

**Issue by gonnalee** [xuxueli/xxl-job#334]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
希望增加一些灵活的API，例如：动态增加任务， 删除任务，开始/暂停任务，动态修改触发时间等一些任务参数。希望把这些功能API提供出来方便业务调用，增加业务灵活性
### Actual behavior
无
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
这个功能已经在迭代中，将会在下个版本发布！
可跟进 https://github.com/xuxueli/xxl-job/issues/277 了解后续详情；
