### ISSUE TITLE
xxl-job-2.4.0，两边accessToken配置的都没错，但还是报错registryResult:ReturnT [code=500, msg=The access token is wrong., content=null]

### ISSUE THREAD

**Issue by weixinke** [xuxueli/xxl-job#3340]
xxl-job配置文件
![image](https://github.com/xuxueli/xxl-job/assets/75015925/8f7d5da5-1495-4621-ae2a-0522ca759e7c)

应用配置文件
![image](https://github.com/xuxueli/xxl-job/assets/75015925/056accb6-9484-4ba8-ba4f-981215afa9db)

报错
![image](https://github.com/xuxueli/xxl-job/assets/75015925/177e6d0a-a57d-431c-acbe-4f6a620d887f)

**Comment by dingziyang** [comment]
我也是遇到同样的问题，我在本地部署2.4版本的admin，在本地起业务服务注册就没问题，但是docker部署到服务器就发生这个问题

**Comment by qihboy** [comment]
我这边是必须重启两端的服务才行

**Comment by dingziyang** [comment]
参考：https://github.com/xuxueli/xxl-job/issues/3342

**Comment by weixinke** [comment]
@dingziyang 老铁，我就是qq群回复你那个皇帝驾到，昨天已经看到问题了，debug发现代码没读accessToken配置
