### ISSUE TITLE
任务回调失败，log item not found

### ISSUE THREAD

**Issue by no-trifling** [xuxueli/xxl-job#3346]
![image](https://github.com/xuxueli/xxl-job/assets/62464230/8b25086b-ecb0-45b8-b56d-d8d7d2ffd0f9)

![image](https://github.com/xuxueli/xxl-job/assets/62464230/a261927c-058b-4e18-97da-3c2aab17b571)

任务执行结束，回调时报错`log item not found`.数据库中确实有这条调度日志，为啥回调时会找不到。

**Comment by kennyQAQ** [comment]
你的xxl-job  数据库是单库吗

**Comment by no-trifling** [comment]
分布式数据库

**Comment by kennyQAQ** [comment]
分布式数据库可能会出现这种问题 回调的时候从库没查到 数据还没同步过来 你想一下 是不是

**Comment by no-trifling** [comment]
我有好多执行器，但就这一个执行器的任务出现这种情况，看了好久也没解决了。

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
