### ISSUE TITLE
mysql数据库 xxl_job_lock表行级死锁，导致全部定时任务不执行，并且无法感知，可不可以邮箱或其他方式通知呢？

### ISSUE THREAD

**Issue by blackqw** [xuxueli/xxl-job#3347]
mysql数据库 xxl_job_lock表行级死锁，导致全部定时任务不执行，并且无法感知，可不可以邮箱或其他方式通知呢？

通知之后可以及时去排查原因，就不用等待用户反馈才开始排查，发现定时任务未执行

**Comment by xuxueli** [comment]
建议接入监控系统，DB或应用层监控。
