### ISSUE TITLE
如何备份和导入任务列表

### ISSUE THREAD

**Issue by wzshuang** [xuxueli/xxl-job#336]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.2

### Expected behavior
我在本地内网环境有个调度中心，上面有大量的任务。在线上生产环境也搭了一个调度中心，上线的时候如何把本地的任务快速的导入到线上去呢？看了下表结构，不是很确定每个表之间的关联关系，而且线上线下任务个数不完全相同，id不好处理。有没有比较优雅的方式解决呢？
### Other information

**Comment by xuxueli** [comment]
你好，有两个方案：
1、将本地任务表数据，全量同步一份到线上环境。
2、熟悉新增任务的Ajax接口，准备任务参数数据，批量请求该接口；
