### ISSUE TITLE
添加springboot版本注册中心，新增实时任务的支持；大多数业务场景不是轮询任务；

### ISSUE THREAD

**Issue by littleeleplent** [xuxueli/xxl-job#337]
添加springboot版本注册中心，新增实时任务的支持；大多数业务场景不是轮询任务；

不知道目前注册中心的新增任务接口性能如何？ 可以支撑多少笔请求/s?

**Comment by xuxueli** [comment]
你好，实时任务是指，Api接口触发并立即执行的任务吗？目前是支持的，提供了相关API服务。
但是，这种需求，更偏向于MQ的场景，可以参考下 XXL-MQ，单机TPS约 8000/s，支持事务消费、延时消费等等特性。
