### ISSUE TITLE
centos7环境下，任务先打印日志，会出现数据库有日志，日志文件没生成的情况

### ISSUE THREAD

**Issue by wenshenghu** [xuxueli/xxl-job#3377]
使用  XxlJobHelper.log 输出日志，就会出现日志文件没有创建，但是数据库日志表有记录，导致任务没执行，代码如下。

@XxlJob("salarySubsidyCreateMonthHandler")
    public ReturnT<String> salarySubsidyCreateMonth() {
        XxlJobHelper.log("工资补贴计算开始：");

        salaryService.salarySubsidyCreateMonth();

        XxlJobHelper.log("工资补贴计算结束！");

        return ReturnT.SUCCESS;
    }

我能证明没执行， 因为我的service里面的代码写了一行  int a = 1/0
如果有正常执行， 那肯定报错，不会返回200，
但是执行日志那边，还是有几率出现正常返回200的

### Which version of XXL-JOB do you using?
centos7 下 使用 2.4.1

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
