### ISSUE TITLE
不定时的某个任务结果丢失，标记失败，之后就一直会失败，重新保存代码后，就会恢复正常

### ISSUE THREAD

**Issue by ottoZeng** [xuxueli/xxl-job#3378]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.0
### Expected behavior
定时任务正常执行成功
### Actual behavior
![96F1ACE5-3D90-48cc-BADD-E1D62F955B68](https://github.com/xuxueli/xxl-job/assets/112684787/ba328a21-7dd7-4e94-917c-1ffe65e655fd)
不定时某个定时任务会任务结果丢失，标记失败
之后就会一直都是这样，只有重新编辑保存代码后，该定时任务才会恢复正常
### Steps to reproduce the behavior
不清楚是什么原因，推测是定时任务太多导致的问题，之前任务少的时候没出过这个问题
每天该调度器总共会执行6000次任务，调度中心有60个任务
xxl-job-core使用的是2.3.0的（就是执行器的代码依赖），调度中心使用的2.4.0的，不清楚是否与版本差异有关
### Other information

**Comment by carry555** [comment]
我也遇到这个问题。。也是2.4版本

**Comment by ottoZeng** [comment]
找到了我们出的问题，在第一个报错的地方会有线程卡住，可以看当时的业务日志看到出了一个linux的系统内核导致的bug，可以试着去切换系统内核版本来解决
