### ISSUE TITLE
一些建议和期待的功能

### ISSUE THREAD

**Issue by littleeleplent** [xuxueli/xxl-job#338]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
正在了解该产品，选型过程中
### Expected behavior
1:期望加入短信预警；任务阻塞 和未执行任务过多 的预警功能；
2:期望新增执行步奏mark功能； 假设任务执行有 1 2 3步奏，执行到2时挂了；重新执行时从2开始 往后执行；
3:新增注册中心springboot支持和实时任务api支持
4:提供api注册接口的性能，满足并发场景的需要
若新增以上功能，我相信xxl会变的非常强大；

### Other information

**Comment by Kiddinglife** [comment]
@jgshzy  airflow gives you what you want.

**Comment by xuxueli** [comment]
DAG流程任务，进度跟进合并至：https://github.com/xuxueli/xxl-job/issues/172
