### ISSUE TITLE
actuator配置是旧版本springboot的key

### ISSUE THREAD

**Issue by DeleteLin** [xuxueli/xxl-job#3385]
actuator配置更新成springboot2.x的版本配置。
建议默认不要和servlet端口一起。

还有数据库啥时候支持jpa，两年前信创改造我就手动改过一版pgsql的版本，当时就看到官网计划支持了，都快3年了还在计划。感觉好慢

**Comment by xuxueli** [comment]
该功能评估缺少通用型，建议定制实现。
