### ISSUE TITLE
2.3.1多个任务配置同一个handle会出现jobthread重复注册的问题

### ISSUE THREAD

**Issue by linshaomin** [xuxueli/xxl-job#3394]
jobthread重复注册会导致线程资源不能复用，旧线程被打断的问题
![image](https://github.com/xuxueli/xxl-job/assets/44076695/a9281482-ffb4-42fb-85a9-9703bfcf0704)
因为每个job的handle都是指向同一个对象，但是这个时候比较的是不同的引用，所以会触发这个逻辑导致重复注册。

**Comment by fenglinjueding** [comment]
老哥有找到解决办法吗，目前任务与执行器必须要一一对应？

**Comment by linshaomin** [comment]
> 老哥有找到解决办法吗，目前任务与handle必须要一一对应？

好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。

**Comment by fenglinjueding** [comment]
> > 老哥有找到解决办法吗，目前任务与handle必须要一一对应？
> 
> 好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。

ok

**Comment by fenglinjueding** [comment]
> > 老哥有找到解决办法吗，目前任务与handle必须要一一对应？
> 
> 好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。

老哥，方面加下联系方式吗 我微信 wxid_5138vr6gtzb522

**Comment by yuanfengdaizhewo** [comment]
> > 老哥有找到解决办法吗，目前任务与handle必须要一一对应？
> 
> 好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。

你说的不对，一个的jobId 对应一个jobThread 只有你设置 阻塞处理策略 为 覆盖之前调度 才会在还存在旧线程还在执行任务的情况下 创建新的jobThread 并将旧线程设置为打断。

**Comment by linshaomin** [comment]
> > > 老哥有找到解决办法吗，目前任务与handle必须要一一对应？
> > 
> > 
> > 好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。
> 
> 老哥，方面加下联系方式吗 我微信 wxid_5138vr6gtzb522

我这边原因弄错了，应该是jobthread自销毁的问题，你看下jobthread源码就知道，循环每次3s去队列读任务，循环次数大于30次就会销毁，也就是说调度时间超过90s的可能就会存在重复注册的问题。
<img width="983" alt="image" src="https://github.com/xuxueli/xxl-job/assets/44076695/0d1b1b06-cc49-470e-855b-425b34584224">

**Comment by linshaomin** [comment]
> > > 老哥有找到解决办法吗，目前任务与handle必须要一一对应？
> > 
> > 
> > 好像只能改源码，多个任务对应一个handle功能可以正常运行，正常一个任务复用一个线程，这种情况会存在任务线程资源浪费，旧线程被打断的情况。
> 
> 你说的不对，一个的jobId 对应一个jobThread 只有你设置 阻塞处理策略 为 覆盖之前调度 才会在还存在旧线程还在执行任务的情况下 创建新的jobThread 并将旧线程设置为打断。

是的，这个我知道，设置的是单机串行，应该是超过阈值线程自己销毁了。
