### ISSUE TITLE
在执行器里增加JavaMelody监控时，会导致调度不成功。

### ISSUE THREAD

**Issue by wxxzy** [xuxueli/xxl-job#34]
在执行器项目中增加了JavaMelody配置已监控项目运行情况。
web.xml增加配置：
`<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
			classpath:monitoring-spring.xml
			classpath:applicationcontext-xxl-job.xml
		</param-value>
	</context-param>`
`<filter>
		<filter-name>javamelody</filter-name>
		<filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
		<init-param>
			<param-name>log</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>javamelody</filter-name>
		<url-pattern>/*</url-pattern>
		<dispatcher>REQUEST</dispatcher>
	</filter-mapping>
	<listener>
		<listener-class>net.bull.javamelody.SessionListener</listener-class>
	</listener>`
monitoring-spring.xml文件为：
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

    
    <bean id="facadeMonitoringAdvisor" class="net.bull.javamelody.MonitoringSpringAdvisor">
        <property name="pointcut">
            <bean class="org.springframework.aop.support.JdkRegexpMethodPointcut">
                <property name="pattern" value="com.meyacom.crm.*" />
            </bean>
        </property>
    </bean>

    <bean class="org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator"/>

    
    <bean id="springDataSourceBeanPostProcessor" class="net.bull.javamelody.SpringDataSourceBeanPostProcessor">
        
    </bean>

    <bean id="ProxyFactoryBean" class="org.springframework.aop.framework.ProxyFactoryBean">
        <property name="interceptorNames">
            <list>
                <value>facadeMonitoringAdvisor</value>
            </list>
        </property>
    </bean>

</beans>`

增加以上配置后会导致只能执行GLUE模式的任务，执行JobHandler调度失败。错误信息：
`Trigger running, 
>>>[address] : 10.0.0.173:9034, 
>>>[status] : FAIL, 
>>>[msg] : job handler for jobKey=[1_201612232118460184] not found. `
 jobKey是存在的，关掉JavaMelody可以正常执行。

**Comment by xuxueli** [comment]
推测JobHandler没有被Spring扫描到导致的，可以在项目启动时以关键字 “xxl-job register jobhandler success, name: ” 搜索启动日志，确认响应JobHandler是否成功注册。
