### ISSUE TITLE
请问Glue模式下执行Shell脚本如何设置注册方式和机器地址

### ISSUE THREAD

**Issue by harryzzp** [xuxueli/xxl-job#340]
我再Windows10下使用Bash on Windows的Ubuntu来运行调度中心，然后想测试配置Glue-Shell，但是执行都报如下错误：

调度机器：169.254.198.247
执行器-注册方式：自动注册
执行器-地址列表：null
路由策略：第一个
阻塞处理策略：单机串行
失败处理策略：失败告警
----------------------
调度失败：执行器地址为空

执行shell直接调用调度中心本地bash，还需要配置执行器地址？

**Comment by MichaelIT** [comment]
请问你是如何解决的？
