### ISSUE TITLE
高版本服务端 v2.4.0 低版本客户端 v2.2.1 

### ISSUE THREAD

**Issue by chaichai31** [xuxueli/xxl-job#3401]
这样使用xxl-job有什么异常问题吗？ 目前迁移方案只是修改数据库的字段后 直接升级服务端，注册任务全都是手动录入，执行后一直没有执行结果

**Comment by cnn007** [comment]
也在升级规划中，测试安装一直不成功， docker 版本。

**Comment by cnn007** [comment]
部署后，访问管理后台，提示404，日志也没有打印。
![image](https://github.com/xuxueli/xxl-job/assets/13449400/72ea93db-3a12-4cb8-b456-7f43f9a77b02)
![image](https://github.com/xuxueli/xxl-job/assets/13449400/98bdb7f6-5c92-4da9-9415-d9abc99886a5)

**Comment by cnn007** [comment]
修改表字段，job_info 表字段有调整。

**Comment by xuxueli** [comment]
> 修改表字段，job_info 表字段有调整。

+1
