### ISSUE TITLE
JettyServer ExecutorThreadPool 线程池无法设置，运行一段时间后可能触发ZABBIX监控线程数告警

### ISSUE THREAD

**Issue by BathSunshine** [xuxueli/xxl-job#341]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by dwhgygzt** [comment]
暂时修改了一下 com.xxl.job.core.rpc.netcom.jetty.server.JettyServer类中的几行代码：

	public void start(final int port, final String ip, final String appName) throws Exception {
		thread = new Thread(new Runnable() {
			@Override
			public void run() {

				ThreadPoolExecutor executor = new ThreadPoolExecutor(
				256, 256, 60, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>());
				**executor.allowCoreThreadTimeOut(true);**

				// The Server
				server = new Server(new ExecutorThreadPool(executor));  // 非阻塞
                                .....

 主要是设置ThreadPoolExecutor 的allowCoreThreadTimeOut为true，即开启可回收空闲线程的开关，默认jetty里面的ExecutorThreadPool() 构造函数中没有对ThreadPoolExecutor开启allowCoreThreadTimeOut。
 
 到底如何调整还请作者指正 @xuxueli

**Comment by xuxueli** [comment]
你好，感谢反馈！
目前使用 ExecutorThreadPool 设置线程，最大线程数 256，线程数量是可控的，可以放心使用。
针对 allowCoreThreadTimeOut 配置，现状配置下可以满足常规情况下执行器要求。
如果执行器任务执行频率较低，可以参考你的方案进行配置，可以节省线程开销。但是如果任务触发频率较高，建议保持现状啊。
