### ISSUE TITLE
2.3.0版本使用异步@Async注解，无法收到回调

### ISSUE THREAD

**Issue by Hemione521** [xuxueli/xxl-job#3416]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0版本

### Expected behavior
期望XxlJobHelper.handleSuccess("handle success");执行，且页面上查询调用日志能看到这句日志；

### Actual behavior
未收到回调，调用日志中无此回调日志

### Steps to reproduce the behavior
去掉异步后，恢复正常

### Other information

**Comment by xiao-le-ge** [comment]
你需要将你job的context传递到你的异步线程里去

**Comment by Hemione521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hemione521** [comment]
> 你需要将你job的context传递到你的异步线程里去

可以详细说一下吗？

**Comment by xiao-le-ge** [comment]
```java
//如果你@Async指定了线程池，你需要在实例化线程池的时候这么操作
//假如你用的是ThreadPoolTaskExecutor
@Bean("async-executor")
    public ThreadPoolTaskExecutor boardFilterExecutor(){
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(20);
        executor.setMaxPoolSize(30);
        executor.setQueueCapacity(256);
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.setThreadNamePrefix("async-");
        executor.setTaskDecorator(runnable -> {
            //获取主线程的上下文
            XxlJobContext xxlJobContext = XxlJobContext.getXxlJobContext();
            return () -> {
                //设置异步线程上下文
                XxlJobContext.setXxlJobContext(context);
                runnable.run();
            };
        });
        return executor;
    }
```

**Comment by xiao-le-ge** [comment]
> > 你需要将你job的context传递到你的异步线程里去
> 
> 可以详细说一下吗？

//如果你@Async指定了线程池，你需要在实例化线程池的时候这么操作
//假如你用的是ThreadPoolTaskExecutor
@Bean("async-executor")
    public ThreadPoolTaskExecutor asyncExecutor(){
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(20);
        executor.setMaxPoolSize(30);
        executor.setQueueCapacity(256);
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.setThreadNamePrefix("async-");
        executor.setTaskDecorator(runnable -> {
            //获取主线程的上下文
            XxlJobContext xxlJobContext = XxlJobContext.getXxlJobContext();
            return () -> {
                //设置异步线程上下文
                XxlJobContext.setXxlJobContext(context);
                runnable.run();
            };
        });
        return executor;
    }

**Comment by Hemione521** [comment]
> > > 你需要将你job的context传递到你的异步线程里去
> > 
> > 
> > 可以详细说一下吗？
> 
> //如果你@async指定了线程池，你需要在实例化线程池的时候这么操作 //假如你用的是ThreadPoolTaskExecutor
> 
> ```java
> @Bean("async-executor")
>     public ThreadPoolTaskExecutor asyncExecutor(){
>         ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
>         executor.setCorePoolSize(20);
>         executor.setMaxPoolSize(30);
>         executor.setQueueCapacity(256);
>         executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
>         executor.setThreadNamePrefix("async-");
>         executor.setTaskDecorator(runnable -> {
>             //获取主线程的上下文
>             XxlJobContext xxlJobContext = XxlJobContext.getXxlJobContext();
>             return () -> {
>                 //设置异步线程上下文
>                 XxlJobContext.setXxlJobContext(context);
>                 runnable.run();
>             };
>         });
>         return executor;
>     }
> ```

之前的代码和这个差不多，刚才按照您的写法试了下，还是不行。
代码如下：
`@Configuration
public class TestAsyncConfig {
    private int corePoolSize = 1;
    private int maxPoolSize = 1;
    private int queueCapacity = 1024;

    @Bean("async-executor")
    public ThreadPoolTaskExecutor asyncExecutor(){
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(20);
        executor.setMaxPoolSize(30);
        executor.setQueueCapacity(256);
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.setThreadNamePrefix("async-");
        executor.setTaskDecorator(runnable -> {
            //获取主线程的上下文
            XxlJobContext xxlJobContext = XxlJobContext.getXxlJobContext();
            return () -> {
                //设置异步线程上下文
                XxlJobContext.setXxlJobContext(xxlJobContext);
                runnable.run();
            };
        });
        return executor;
    }
}`
定时任务类如下：
`@Component
@RequiredArgsConstructor
@Async("async-executor")
public class TestSyncSchedule {

    @XxlJob(value = "testJob")
    public void testJob) {
        try {
            Thread.sleep(3000);
            XxlJobHelper.handleSuccess("job executed success");
        } catch (Exception e) {
            XxlJobHelper.handleFail("job executed fail");
        }
    }`
执行结果如下图：
![image](https://github.com/xuxueli/xxl-job/assets/13196856/5a72753f-dff8-4b56-963a-a8ccf77b1f90)
最新一条是去掉异步线程池之后的效果，这个是期望效果。

**Comment by xiao-le-ge** [comment]
> ```java
> @Async("async-executor")
> ```

可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@Async("async-executor")
然后在testJob中调用该方法
```java
@Service
public class TestService{
       @Async("async-executor")
       public void testService(){
           try {
            Thread.sleep(3000);
            XxlJobHelper.handleSuccess("job executed success");
        } catch (Exception e) {
            XxlJobHelper.handleFail("job executed fail");
        }
       }
}


@Component
public class TestSyncSchedule {

    @
    private  TestService service;

    @XxlJob(value = "testJob")
    public void testJob) {
        service.testService();
    }

```

**Comment by Hemione521** [comment]
> > ```java
> > @Async("async-executor")
> > ```
> 
> 可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@async("async-executor") 然后在testJob中调用该方法
> 
> ```java
> @Service
> public class TestService{
>        @Async("async-executor")
>        public void testService(){
>            try {
>             Thread.sleep(3000);
>             XxlJobHelper.handleSuccess("job executed success");
>         } catch (Exception e) {
>             XxlJobHelper.handleFail("job executed fail");
>         }
>        }
> }
> 
> 
> @Component
> public class TestSyncSchedule {
> 
>     @
>     private  TestService service;
> 
>     @XxlJob(value = "testJob")
>     public void testJob) {
>         service.testService();
>     }
> ```

按照您的写法试了下，依然没有回调
![image](https://github.com/xuxueli/xxl-job/assets/13196856/9ca3a5ac-4002-4a34-a37f-7811f0700bd4)

**Comment by xiao-le-ge** [comment]
> > > ```java
> > > @Async("async-executor")
> > > ```
> > 
> > 
> > 可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@async("async-executor") 然后在testJob中调用该方法
> > ```java
> > @Service
> > public class TestService{
> >        @Async("async-executor")
> >        public void testService(){
> >            try {
> >             Thread.sleep(3000);
> >             XxlJobHelper.handleSuccess("job executed success");
> >         } catch (Exception e) {
> >             XxlJobHelper.handleFail("job executed fail");
> >         }
> >        }
> > }
> > 
> > 
> > @Component
> > public class TestSyncSchedule {
> > 
> >     @
> >     private  TestService service;
> > 
> >     @XxlJob(value = "testJob")
> >     public void testJob) {
> >         service.testService();
> >     }
> > ```
> 
> 按照您的写法试了下，依然没有回调 ![image](https://private-user-images.githubusercontent.com/13196856/319127148-9ca3a5ac-4002-4a34-a37f-7811f0700bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc5MjMsIm5iZiI6MTcxMjEzNzYyMywicGF0aCI6Ii8xMzE5Njg1Ni8zMTkxMjcxNDgtOWNhM2E1YWMtNDAwMi00YTM0LWEzN2YtNzgxMWYwNzAwYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWZjZjRmZWNmMjZhMTBlODdmOTgwNTFiNmQyZjNjMzQ5MTI0NDY3NWJlNjdkOTc4ZDZjMTcyNTVkY2FiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RklzDPwx1PA6Yoqcm-1DvPpV7nWFm-vIgH6G1jYP9ic)

看了下源码，job为异步后，jobThread很快就执行完成execute方法，之后会立马去获取jobContext，获取不到你设置的handlMsg
<img width="742" alt="image" src="https://github.com/xuxueli/xxl-job/assets/26083836/b0542cb0-a047-400c-9d12-2bc7e1658484">

**Comment by Hemione521** [comment]
> > > > ```java
> > > > @Async("async-executor")
> > > > ```
> > > 
> > > 
> > > 可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@async("async-executor") 然后在testJob中调用该方法
> > > ```java
> > > @Service
> > > public class TestService{
> > >        @Async("async-executor")
> > >        public void testService(){
> > >            try {
> > >             Thread.sleep(3000);
> > >             XxlJobHelper.handleSuccess("job executed success");
> > >         } catch (Exception e) {
> > >             XxlJobHelper.handleFail("job executed fail");
> > >         }
> > >        }
> > > }
> > > 
> > > 
> > > @Component
> > > public class TestSyncSchedule {
> > > 
> > >     @
> > >     private  TestService service;
> > > 
> > >     @XxlJob(value = "testJob")
> > >     public void testJob) {
> > >         service.testService();
> > >     }
> > > ```
> > 
> > 
> > 按照您的写法试了下，依然没有回调 ![image](https://private-user-images.githubusercontent.com/13196856/319127148-9ca3a5ac-4002-4a34-a37f-7811f0700bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc5MjMsIm5iZiI6MTcxMjEzNzYyMywicGF0aCI6Ii8xMzE5Njg1Ni8zMTkxMjcxNDgtOWNhM2E1YWMtNDAwMi00YTM0LWEzN2YtNzgxMWYwNzAwYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWZjZjRmZWNmMjZhMTBlODdmOTgwNTFiNmQyZjNjMzQ5MTI0NDY3NWJlNjdkOTc4ZDZjMTcyNTVkY2FiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RklzDPwx1PA6Yoqcm-1DvPpV7nWFm-vIgH6G1jYP9ic)
> 
> 看了下源码，job为异步后，jobThread很快就执行完成execute方法，之后会立马去获取jobContext，获取不到你设置的handlMsg <img alt="image" width="742" src="https://private-user-images.githubusercontent.com/26083836/319132637-b0542cb0-a047-400c-9d12-2bc7e1658484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzgyNzYsIm5iZiI6MTcxMjEzNzk3NiwicGF0aCI6Ii8yNjA4MzgzNi8zMTkxMzI2MzctYjA1NDJjYjAtYTA0Ny00MDBjLTlkMTItMmJjN2UxNjU4NDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMjY0YWVjMjM5MDE3MjJlMDIwMTkyNmExNDEzMTAxZDFjZWFhZmI5YzhmMDk0ZTE3OWE1OTRkZjQ2YjU1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKX2IPp9JiYaG_TGI6ruJzLMsBWS0b18f3jwcGCzS1o">

所以不应该用异步是吧

**Comment by xiao-le-ge** [comment]
> > > > > ```java
> > > > > @Async("async-executor")
> > > > > ```
> > > > 
> > > > 
> > > > 可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@async("async-executor") 然后在testJob中调用该方法
> > > > ```java
> > > > @Service
> > > > public class TestService{
> > > >        @Async("async-executor")
> > > >        public void testService(){
> > > >            try {
> > > >             Thread.sleep(3000);
> > > >             XxlJobHelper.handleSuccess("job executed success");
> > > >         } catch (Exception e) {
> > > >             XxlJobHelper.handleFail("job executed fail");
> > > >         }
> > > >        }
> > > > }
> > > > 
> > > > 
> > > > @Component
> > > > public class TestSyncSchedule {
> > > > 
> > > >     @
> > > >     private  TestService service;
> > > > 
> > > >     @XxlJob(value = "testJob")
> > > >     public void testJob) {
> > > >         service.testService();
> > > >     }
> > > > ```
> > > 
> > > 
> > > 按照您的写法试了下，依然没有回调 ![image](https://private-user-images.githubusercontent.com/13196856/319127148-9ca3a5ac-4002-4a34-a37f-7811f0700bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc5MjMsIm5iZiI6MTcxMjEzNzYyMywicGF0aCI6Ii8xMzE5Njg1Ni8zMTkxMjcxNDgtOWNhM2E1YWMtNDAwMi00YTM0LWEzN2YtNzgxMWYwNzAwYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWZjZjRmZWNmMjZhMTBlODdmOTgwNTFiNmQyZjNjMzQ5MTI0NDY3NWJlNjdkOTc4ZDZjMTcyNTVkY2FiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RklzDPwx1PA6Yoqcm-1DvPpV7nWFm-vIgH6G1jYP9ic)
> > 
> > 
> > 看了下源码，job为异步后，jobThread很快就执行完成execute方法，之后会立马去获取jobContext，获取不到你设置的handlMsg <img alt="image" width="742" src="https://private-user-images.githubusercontent.com/26083836/319132637-b0542cb0-a047-400c-9d12-2bc7e1658484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzgyNzYsIm5iZiI6MTcxMjEzNzk3NiwicGF0aCI6Ii8yNjA4MzgzNi8zMTkxMzI2MzctYjA1NDJjYjAtYTA0Ny00MDBjLTlkMTItMmJjN2UxNjU4NDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMjY0YWVjMjM5MDE3MjJlMDIwMTkyNmExNDEzMTAxZDFjZWFhZmI5YzhmMDk0ZTE3OWE1OTRkZjQ2YjU1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKX2IPp9JiYaG_TGI6ruJzLMsBWS0b18f3jwcGCzS1o">
> 
> 所以不应该用异步是吧

是的

**Comment by Hemione521** [comment]
> > > > > > ```java
> > > > > > @Async("async-executor")
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 可以试下将你的业务代码封装到单独的类和方法，然后在该方法上加@async("async-executor") 然后在testJob中调用该方法
> > > > > ```java
> > > > > @Service
> > > > > public class TestService{
> > > > >        @Async("async-executor")
> > > > >        public void testService(){
> > > > >            try {
> > > > >             Thread.sleep(3000);
> > > > >             XxlJobHelper.handleSuccess("job executed success");
> > > > >         } catch (Exception e) {
> > > > >             XxlJobHelper.handleFail("job executed fail");
> > > > >         }
> > > > >        }
> > > > > }
> > > > > 
> > > > > 
> > > > > @Component
> > > > > public class TestSyncSchedule {
> > > > > 
> > > > >     @
> > > > >     private  TestService service;
> > > > > 
> > > > >     @XxlJob(value = "testJob")
> > > > >     public void testJob) {
> > > > >         service.testService();
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > 按照您的写法试了下，依然没有回调 ![image](https://private-user-images.githubusercontent.com/13196856/319127148-9ca3a5ac-4002-4a34-a37f-7811f0700bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc5MjMsIm5iZiI6MTcxMjEzNzYyMywicGF0aCI6Ii8xMzE5Njg1Ni8zMTkxMjcxNDgtOWNhM2E1YWMtNDAwMi00YTM0LWEzN2YtNzgxMWYwNzAwYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWZjZjRmZWNmMjZhMTBlODdmOTgwNTFiNmQyZjNjMzQ5MTI0NDY3NWJlNjdkOTc4ZDZjMTcyNTVkY2FiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RklzDPwx1PA6Yoqcm-1DvPpV7nWFm-vIgH6G1jYP9ic)
> > > 
> > > 
> > > 看了下源码，job为异步后，jobThread很快就执行完成execute方法，之后会立马去获取jobContext，获取不到你设置的handlMsg <img alt="image" width="742" src="https://private-user-images.githubusercontent.com/26083836/319132637-b0542cb0-a047-400c-9d12-2bc7e1658484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzgyNzYsIm5iZiI6MTcxMjEzNzk3NiwicGF0aCI6Ii8yNjA4MzgzNi8zMTkxMzI2MzctYjA1NDJjYjAtYTA0Ny00MDBjLTlkMTItMmJjN2UxNjU4NDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMjY0YWVjMjM5MDE3MjJlMDIwMTkyNmExNDEzMTAxZDFjZWFhZmI5YzhmMDk0ZTE3OWE1OTRkZjQ2YjU1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKX2IPp9JiYaG_TGI6ruJzLMsBWS0b18f3jwcGCzS1o">
> > 
> > 
> > 所以不应该用异步是吧
> 
> 是的

了解了 感谢
