### ISSUE TITLE
如何贡献代码，  我可以帮你们将spring mvc改为springboot

### ISSUE THREAD

**Issue by aileennian** [xuxueli/xxl-job#342]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，调度中心迁移SpringBoot已经在排期，预计在2.0发布。
在此之前，还会发一版 1.9.2 ，可以先稍等下。

**Comment by aileennian** [comment]
哦。
我已经修改OK了。
源代码不变，只要修改如下信息即可：
不过你是官方的，一定要按照Springboot的编写风络将代码写的很优美的话，我这个方法不适合。

1、增加JobApplication.java

import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ImportResource;

@SpringBootApplication
//@EnableAutoConfiguration
//@Configuration
@ImportResource(locations={"classpath:spring/applicationcontext-syx-job-admin.xml","classpath:spring/springmvc-context.xml","classpath:spring/applicationcontext-base.xml"})
public class JobApplication {

public static void main(String[] args) {
SpringApplication app = new SpringApplication(JobApplication.class);
// app.setAddCommandLineProperties(false);
// app.addListeners(new MyAppListener());
app.setBannerMode(Banner.Mode.CONSOLE);
app.run(args);
// SpringApplication.run(SampleTomcatSslApplication.class, args);

}

}


2. ServletInitializer.java


import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.support.SpringBootServletInitializer;

/** 
 * Title: ServletInitializer 
 * @version 1.0 
 */  
public class ServletInitializer extends SpringBootServletInitializer {
@Override
protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
return application.sources(JobApplication.class);
}
}

3.application.properties
spring.application.name=xxxx
server.port=8080




----------------
aileen.nian
 
发件人： 许雪里
发送时间： 2018-04-28 17:08
收件人： xuxueli/xxl-job
抄送： 念小美; Author
主题： Re: [xuxueli/xxl-job] 如何贡献代码， 我可以帮你们将spring mvc改为springboot (#342)
你好，调度中心迁移SpringBoot已经在排期，预计在2.0发布。
在此之前，还会发一版 1.9.2 ，可以先稍等下。
―

**Comment by aileennian** [comment]
但这样编写的话，可以保证你的spring mvc的代码和spring boot保持同一套。



----------------
aileen.nian
 
发件人： nianxl@sohu.com
发送时间： 2018-05-01 13:37
收件人： xuxueli/xxl-job
主题： Re: Re: [xuxueli/xxl-job] 如何贡献代码， 我可以帮你们将spring mvc改为springboot (#342)
哦。
我已经修改OK了。
源代码不变，只要修改如下信息即可：
不过你是官方的，一定要按照Springboot的编写风络将代码写的很优美的话，我这个方法不适合。

1、增加JobApplication.java

import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ImportResource;

@SpringBootApplication
//@EnableAutoConfiguration
//@Configuration
@ImportResource(locations={"classpath:spring/applicationcontext-syx-job-admin.xml","classpath:spring/springmvc-context.xml","classpath:spring/applicationcontext-base.xml"})
public class JobApplication {

public static void main(String[] args) {
SpringApplication app = new SpringApplication(JobApplication.class);
// app.setAddCommandLineProperties(false);
// app.addListeners(new MyAppListener());
app.setBannerMode(Banner.Mode.CONSOLE);
app.run(args);
// SpringApplication.run(SampleTomcatSslApplication.class, args);

}

}


2. ServletInitializer.java


import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.support.SpringBootServletInitializer;

/** 
 * Title: ServletInitializer 
 * @version 1.0 
 */  
public class ServletInitializer extends SpringBootServletInitializer {
@Override
protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
return application.sources(JobApplication.class);
}
}

3.application.properties
spring.application.name=xxxx
server.port=8080




----------------
aileen.nian
 
发件人： 许雪里
发送时间： 2018-04-28 17:08
收件人： xuxueli/xxl-job
抄送： 念小美; Author
主题： Re: [xuxueli/xxl-job] 如何贡献代码， 我可以帮你们将spring mvc改为springboot (#342)
你好，调度中心迁移SpringBoot已经在排期，预计在2.0发布。
在此之前，还会发一版 1.9.2 ，可以先稍等下。
―

**Comment by qrqhuang** [comment]
@aileennian spring boot  的优势是自动配置。 这样改造意义不大~

**Comment by maylovelil** [comment]
springboot 我已经搞了。改动有些大。不过用起来确实方便不少

**Comment by Dorae132** [comment]
没必要吧？想要简单改造的话直接引入依赖，加一个启动类，引入xml就可以。如果要完全体的只能把原来的xml改成java配置的方式放到config类里边。但是java配置和xml配置本质上是一样的啊。改造的意义何在？

**Comment by cullenx** [comment]
@Dorae132 赶时髦呗
