### ISSUE TITLE
snyk 扫描最新版本xxl-job-core-2.4.1 漏洞详情

### ISSUE THREAD

**Issue by AmbitionX** [xuxueli/xxl-job#3427]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-core-2.4.1.jar

### Expected behavior
期望修复掉目前无法通过的漏洞

### Actual behavior
我们公司是用 snyk （一个用户量很大的安全平台），扫描出2.4.1也就是截止issue发布的最新版本存在两个无法通过的漏洞
漏洞一：Command injection
![image](https://github.com/xuxueli/xxl-job/assets/8198587/9a93623d-ccb0-4c37-af42-fbcd5a5bddc4)

漏洞二：CSRF
![image](https://github.com/xuxueli/xxl-job/assets/8198587/6120d20a-ed45-4c43-893c-b68c03d81b7e)

请问有上述漏洞的修复计划么？

**Comment by jerrychien** [comment]
Encountered the same problem

**Comment by xuxueli** [comment]
漏洞1：Command injection（问题来自 https://github.com/xuxueli/xxl-job/issues/2979 ）。实际非系统漏洞，shell 脚本类任务不限制脚本代码逻辑，该代码为任务 owner 人工指定，符合功能预期。
漏洞2：Cross-site Request Forgery (CSRF)（问题来自https://github.com/xuxueli/xxl-job/issues/3504  ）。问题已修复，推送master分支，随后随新版本（v2.4.2）发布修复。
