### ISSUE TITLE
邮件发送乱码

### ISSUE THREAD

**Issue by Parker-Xiang** [xuxueli/xxl-job#343]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Parker-Xiang** [comment]
邮件发送乱码，都没遇到过吗

**Comment by gonnalee** [comment]
这种问题就不需要问作者了，基本都是邮件编码的问题。我也遇到了，查看源码修改邮件发送编码就行了

**Comment by xuxueli** [comment]
@gonnalee @Parker-Xiang  +1，邮件编码问题。
