### ISSUE TITLE
请问现在有针对执行器宕机转移的功能吗？

### ISSUE THREAD

**Issue by netfreeperson** [xuxueli/xxl-job#344]
请问现在有针对执行器宕机转移的功能吗？谢谢

**Comment by xuxueli** [comment]
你好，支持的。
1、执行器启动自动注册：宕机机器会被注册中心自动摘除；
2、任务路由策略选择Failover：执行器机器路由的时候，会自动跳过宕机的执行器。
可以选择任意一个方案使用，也可以结合使用的啊！

**Comment by c2002509** [comment]
@xuxueli  
1、注册中心网络故障，是不是所有执行器机器都被摘除，有什么影响？
2、执行器被摘除，正在执行的job会怎么处理？
3、Failover会自动跳过宕机的执行器，那其他模式会分派任务给宕机的任务？Failover是否可以跟First等一起使用在一个job调度上
