### ISSUE TITLE
xxl-job 1.9.1版本部署再jdk9环境下首页图表无法展示，其他问题未详细跟踪，兼容性问题

### ISSUE THREAD

**Issue by 18614091661** [xuxueli/xxl-job#346]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1和1.9.2
### Expected behavior
兼容jdk9
### Actual behavior
首页异常，hashmap问题
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
该问题已经修复并推送master分支，可pull最新master代码体验确认。
将会跟随下次版本迭代一同发布。
