### ISSUE TITLE
2.4.2 调度日志展示的调度机器，  为什么展示的是  数据库的机器地址？ 不是应该真是admin部署的机器地址吗？

### ISSUE THREAD

**Issue by shanfushang** [xuxueli/xxl-job#3465]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by zhipingwu** [comment]
我看就是调度机的地址，有具体例子吗
triggerMsgSb.append("<br>").append(I18nUtil.getString("jobconf_trigger_admin_adress")).append("：").append(IpUtil.getIp());

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
