### ISSUE TITLE
求问，“立即执行一次”的restful api如何调用

### ISSUE THREAD

**Issue by iamlake** [xuxueli/xxl-job#3481]
我想通过Java调用restful api来实现“立即执行一次”的效果
现在已经实现获取jobGroup列表、jobInfo列表，以及通过jobId启动任务，
但没有找到立即执行的api地址，想请问一下调用的地址和需传入的参数都是什么，非常感谢~
![123123123](https://github.com/xuxueli/xxl-job/assets/13414995/2d538ab3-4302-494d-a04c-991ea1f9cf4d)

**Comment by SKTT1Fiver** [comment]
public XxlJobResult xxlJobRun(int jobId, String executorParam) {
        String adminAddresses = 地址
        String url=adminAddresses+"/jobinfo/trigger";
        String body;
        try (HttpResponse response = HttpRequest.post(url)
                .form("id", jobId)
                .form("executorParam", executorParam)
                .cookie(设置一个cookie)
                .execute()) {
            body = response.body();
        }
        return JSONUtil.parse(body).toBean(XxlJobResult.class);
    }

**Comment by wzshuang** [comment]
> public XxlJobResult xxlJobRun(int jobId, String executorParam) { String adminAddresses = 地址 String url=adminAddresses+"/jobinfo/trigger"; String body; try (HttpResponse response = HttpRequest.post(url) .form("id", jobId) .form("executorParam", executorParam) .cookie(设置一个cookie) .execute()) { body = response.body(); } return JSONUtil.parse(body).toBean(XxlJobResult.class); }

请问cookie怎么获取

**Comment by SKTT1Fiver** [comment]
Yes, you can get a cookie by calling the login interface, as shown in the following code example
是的，你可以通过调用登录接口获取cookie，代码示例如下
// java code
    public HttpCookie loginAndGetCookie() {
        String adminAddresses =xxxx;
        String url=adminAddresses+"/login";
        HttpResponse response = HttpRequest.post(url)
                .form("userName",xxxx)
                .form("password",xxxx)
                .execute();
        List<HttpCookie> cookies = response.getCookies();
        Optional<HttpCookie> cookieOpt = cookies.stream()
                .filter(c -> c.getName().equals("XXL_JOB_LOGIN_IDENTITY")).findFirst();
        if (!cookieOpt.isPresent())
            throw new RuntimeException("get xxl-job cookie error!");
        return cookieOpt.get();
    }
