### ISSUE TITLE
如何配置任务复杂参数的建议？

### ISSUE THREAD

**Issue by ljywit** [xuxueli/xxl-job#349]
我们公司目前已经对子系统进行了拆分，每歌子系统的定时任务都是通过spring scheduler的定时任务，现在服务需要水平复制面临着瓶颈，需要引入分布式任务调度平台。
但是我们的定时任务依赖的参数条件非常复杂，**甲方能够在UI上勾选各种各样的参数（例如，报表任务能够选择 对象个数，对象属性）**，也希望看到任务执行状态、日志等等特性，但是xxl-job的任务的参数是一个文件框。
想请教下对这样的需求，该如何引入分布式调度平台？

之前想过在应用中使用quartz数据库集群方式，但是我们好多子系统都有定时任务，并且有很多报表执行任务都会超过1个小时，不知道quartz数据库是否会有事务性的问题？可以先不要考虑任务内部的事务问题（因为报表数据的来源主要是mongo）

**Comment by xuxueli** [comment]
你好，感谢关注！
1、任务参数问题：任务参数需要透传到业务JobHandler里，使用String类型通用性比较好。如果希望定制复杂任务参数，可以通过自定义任务参数并最终序列化成JSON字符串传递到JobHandler里，业务逻辑自行解析即可。
2、超时任务完美支持：XXL-JOB 中任务全部异步运行，运行1H甚至10H都不会有问题。调度中心只负责任务触发，因此调度模块并没有事务问题。如需事务处理，在业务JobHandler内部处理即可。
