### ISSUE TITLE
【急急急】connect refused

### ISSUE THREAD

**Issue by MrRechard** [xuxueli/xxl-job#3494]
![image](https://github.com/xuxueli/xxl-job/assets/65805420/372ecec8-8208-4956-94e7-b07c21576eff)
![image](https://github.com/xuxueli/xxl-job/assets/65805420/847063bd-e062-4d85-bf92-e63c589d617a)
执行器可以看到注册的机器地址，但是telnet 9010端口连接不通， netstat9010端口，也找不到，这种情况是什么原因呢？

**Comment by tanqinhao** [comment]
能注册到调度中心，说明执行器可以访问调度中心。调度中心访问不到调度器可能是
1. 执行器部署的服务器存在多网卡或者容器内部署，注册到调度中心的ip调度中心访问不到。
2. 执行器存在防火墙。
在部署调度中心的服务器上ping执行器自动注册的ip 或者 telnet 9010端口
在部署执行器的服务器上netstat9010，确定执行器服务正常

**Comment by xuxueli** [comment]
+1
