### ISSUE TITLE
BEAN模式自动注册

### ISSUE THREAD

**Issue by jackiesteed** [xuxueli/xxl-job#351]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.2
### Expected behavior
BEAN模式自动注册
### Actual behavior
没有自动注册
### Other information

**Comment by valinz** [comment]
需要确认一下bean是否加入到了spring context中。

**Comment by xuxueli** [comment]
你好，Bean模式JobHandler本质上是一个Spring Bean，已经加入到了容器中。
目前，支持执行器维度的自动注册。但是，因为考虑系统可控性相关问题，任务维度的注册并未支持，不过，如果有需要可以自己定制实现。
