### ISSUE TITLE
升级到 2.4.1 xxl-job-core缺少ShardingUtil和XxlJobLogger类，导致代码无法编译

### ISSUE THREAD

**Issue by qq470255867** [xuxueli/xxl-job#3523]
import com.xxl.job.core.log.XxlJobLogger;
import com.xxl.job.core.util.ShardingUtil;
升级到 2.4.1 xxl-job-core缺少ShardingUtil和XxlJobLogger类，导致以下代码无法编译

ShardingUtil.ShardingVO shardingVO = ShardingUtil.getShardingVo();

IJobHandler.SUCCESS
IJobHandler.FAIL

![image](https://github.com/user-attachments/assets/93f66652-2650-4269-8433-f443c93ab9e5)

**Comment by ypforever0719** [comment]
v2.3.0版本更新后，"ShardingUtil" 组件废弃：改用 "XxlJobHelper.getShardIndex()/getShardTotal();"

**Comment by ypforever0719** [comment]
v2.3.0版本更新后，
"ShardingUtil" 组件废弃：改用 "XxlJobHelper.getShardIndex()/getShardTotal();"
"XxlJobLogger" 组件废弃：改用 "XxlJobHelper.log" 进行日志输出；

**Comment by xuxueli** [comment]
+1
