### ISSUE TITLE
截止到20240904目前CVE漏洞列表，希望修复下对应版本

### ISSUE THREAD

**Issue by liuxin638507** [xuxueli/xxl-job#3535]
Please answer some questions before submitting your issue. Thanks!
目前使用v2.4.1版本，扫描发现一些漏洞，详情列表如图：
![image](https://github.com/user-attachments/assets/48fe0563-c698-4475-8f96-150101b2555e)
and
~~~bash
hit:["spring version less than 5.3.38"]
path:/app.jar(BOOT-INF/lib/spring-core-5.3.31.jar)
~~~

### Which version of XXL-JOB do you using?
v2.4.1
### Expected behavior
希望更新下对应CEV漏洞
### Other information

**Comment by xuxueli** [comment]
你好，上述漏洞基本来自于 springboot 2.x。如有诉求可自行升级 springboot 3.x 解决。
项目计划 v2.5.0 升级 springboot3.x 进行修复

**Comment by xuxueli** [comment]
合并至 https://github.com/xuxueli/xxl-job/issues/3425 跟进。
计划 v.2.5.0升级 springboot3 进行修复。
