### ISSUE TITLE
某任务表达式错误，会导致部分任务重复执行，部分正常任务无法执行

### ISSUE THREAD

**Issue by HongyiPaulZeng** [xuxueli/xxl-job#3541]
版本：
2.4.0

现象：
某个任务表达式错误，导致部分正常任务重复执行，部分正常任务无法执行。

原因：
JobScheduleHelper 类，  void start()方法。
约83行  for (XxlJobInfo jobInfo: scheduleList) 循环中，表达式抛出异常会打断循环，导致重复预读，部分任务会被重复执行，异常任务后面的正常任务无法执行。

**Comment by xuxueli** [comment]
感谢反馈，优化代码已推送master分支，将随 v2.4.2 分支发布。
