### ISSUE TITLE
支持Postgres数据库

### ISSUE THREAD

**Issue by forward-seen** [xuxueli/xxl-job#3551]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.1
### Expected behavior
新增特性，多数据源支持，目前默认数据库仅支持mysql，能否增加postgres支持呢
### Actual behavior
暂时仅支持mysql
### Other information
如若实现框架JPA或者mybatisplus或许可以不再需要关注数据源支持了。

**Comment by forward-seen** [comment]
此issue工作量过大，希望作者能回复一下，我可以自己去实现

**Comment by SUMARKER** [comment]
网上有支持pg的脚本……

**Comment by Macfee** [comment]
希望早日加入pg大家庭

**Comment by xuxueli** [comment]
pg分支版本，可参考社区实现：https://github.com/xuxueli/xxl-job/issues/154

**Comment by liuhouting** [comment]
pg分支版本，可参考社区实现：https://github.com/xuxueli/xxl-job/issues/154
到底是哪里啊，没看到有能用的pgsql版本啊。
