### ISSUE TITLE
xxl-job执行器的端口改变的时候，执行器机器地址这里显示离线，没有自动摘除掉

### ISSUE THREAD

**Issue by 121175060LFN** [xuxueli/xxl-job#3559]
平台每次上线，xxl-job执行器的端口会改变，但是机器地址这里显示离线，没有自动摘除掉。随着时间推移，这里会堆积越来越多。有没有什么好的方法可以摘除掉这些离线的机器
![image](https://github.com/user-attachments/assets/a75cff66-4a40-4a67-8d3f-143fe85de55c)

### Which version of XXL-JOB do you using?
2.3.0

**Comment by xuxueli** [comment]
注册变更存在短暂间隔
