### ISSUE TITLE
任务日志保存时sql异常，提示没有executor_sharding_param字段，版本2.3.1

### ISSUE THREAD

**Issue by wzukhh** [xuxueli/xxl-job#3564]
![image](https://github.com/user-attachments/assets/b2da2ba6-a206-48b3-8285-c9d93061640a)

如图，虽然不影响任务执行，但是频繁报错会增大日志体积，以及无法查看任务日志详情。

查看源码后，executor_sharding_param 字段会直接赋值，没有判空。

![image](https://github.com/user-attachments/assets/468e26b1-e52a-467f-98a6-c14ddeae2dba)

**Comment by xuxueli** [comment]
新版本已修复，可升级
