### ISSUE TITLE
MethodJobHandler toString null pointer exception

### ISSUE THREAD

**Issue by jevonsnotes** [xuxueli/xxl-job#3574]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.1
### Expected behavior
normal
### Actual behavior
null pointer exception
### Steps to reproduce the behavior
when the MethodJobHandler 's target field or method field is null ,then call the toString method will throw a null pointer exception
### Other information

**Comment by xuxueli** [comment]
无法复现，需要提供复现步骤

**Comment by jevonsnotes** [comment]
> 无法复现，需要提供复现步骤

 因部分场景需要脱敏日志数据，该对象经过以下逻辑后
String jsonString = JSONObject.toJSONString(obj, JSONWriter.Feature.WriteClassName);
newObj = JSONObject.parseObject(jsonString, ClassUtil.getClass(obj), JSONReader.Feature.SupportAutoType);

产生的克隆对象MethodJobHandler 属性为空，此时调用MethodJobHandler.toString会报错

![4ae24045e62ae8dd7c947c5d20c25ed](https://github.com/user-attachments/assets/1a4d214e-a8b4-43e1-be66-4bdb4aeb5d2d)
