### ISSUE TITLE
简单按照readme的步骤部署了war包后，tomcat包无法读取

### ISSUE THREAD

**Issue by lilongsswang** [xuxueli/xxl-job#36]
报无法读取 xxl-job-admin.properties 这个文件。 但是 在 webapps的目录里面是有的，debug看到，程序也找到文件。

但异常就是在PropertiesUtil里的loadProperties方法里抛出的。
    in = new InputStreamReader(new FileInputStream(url.getPath()), "UTF-8");
    prop.load(in);

绕过登录机制，直接登录后用起来也是没问题的。
是不是Tomcat配置的原因呢？

**Comment by xuxueli** [comment]
你好，这种情况比较少见，可以检查一下资源路径是否全英文，war包中文件是否存在啊。

**Comment by phoenixshen** [comment]
Hi, guys：
我也出现这样的问题，修改
	public ReturnT<String> loginDo(HttpServletRequest request, HttpServletResponse response, String userName, String password, String ifRemember){
//		if (!PermissionInterceptor.ifLogin(request)) {
//			if (StringUtils.isNotBlank(userName) && StringUtils.isNotBlank(password)
//					&& PropertiesUtil.getString("xxl.job.login.username").equals(userName)
//					&& PropertiesUtil.getString("xxl.job.login.password").equals(password)) {
//				boolean ifRem = false;
//				if (StringUtils.isNotBlank(ifRemember) && "on".equals(ifRemember)) {
//					ifRem = true;
//				}
//				PermissionInterceptor.login(response, ifRem);
//			} else {
//				return new ReturnT<String>(500, "账号或密码错误");
//			}
//		}
		boolean ifRem = true;
		PermissionInterceptor.login(response, ifRem);
		return ReturnT.SUCCESS;
	}
之后，成功登陆，我的JDK 版本是1.8，使用intellij idea编译

**Comment by phoenixshen** [comment]
资源路径全英文，而且文件存在

**Comment by xuxueli** [comment]
你好，centos上问题无法复现，社区群也没有对该问题的反馈，上述抛错位置代码PropertiesUtil最新版本已经废弃，可参考下。
