### ISSUE TITLE
追加任务导出功能

### ISSUE THREAD

**Issue by qrqhuang** [xuxueli/xxl-job#365]
为了保证任务配置的一致性， 减少生产手工维护脚本的成本， 可否考虑加入任务通过脚本迁移功能？
适用于开发环境验证无误，导出脚本后直接测试及生产自动化执行而无须人工介入？
谢谢~

**Comment by xuxueli** [comment]
你好，任务导入导出推荐采用库表迁移的方式处理。只需要迁移扩展表即可。
