### ISSUE TITLE
任务执行方法建议加一个返回值，并可以在调度系统把值展示出来

### ISSUE THREAD

**Issue by yangtp** [xuxueli/xxl-job#37]
现在的任务执行方法execute没有返回值，建议可以加个返回值能通过回调传回调度系统如果，方便做其他操作，比如补单等！

**Comment by xuxueli** [comment]
你好，这条建议很有必要，已经将建议汇总到TODO LIST中，会排期跟进 ：）
感谢关注啊！

**Comment by xuxueli** [comment]
最新版本已实现。
