### ISSUE TITLE
spring-batch类似步骤功能

### ISSUE THREAD

**Issue by liangjf85** [xuxueli/xxl-job#371]
希望框架能实现spring-batch类似的业务步骤功能。并且提供步骤图。
该功能作用非常好。便于运维查看日终任务

**Comment by AmazingYHT** [comment]
这个可以有，因为多场景下，有时候需要按照相应步骤进行执行，

**Comment by crazythinking** [comment]
我倒觉得你可以直接整合spring-batch，xxljob是轻量级的只负责调度即可；xxljob相当于给spring-batch插上了分布式的翅膀，我目前的项目里就是这么做的。

**Comment by kuguobing** [comment]
1、调度是调度，高可以HA调度中心 + 去中心的并行执行器； 跑批的处理，应该是业务内部集成spring batch编程模型。
2、当然，也可以实现利用plugin的思想；独立的一个支持DAG的分布式工作流任务调度。

**Comment by xuxueli** [comment]
DAG流程任务，合并至：https://github.com/xuxueli/xxl-job/issues/172
