### ISSUE TITLE
可否用来做延迟队列？

### ISSUE THREAD

**Issue by leohsu91** [xuxueli/xxl-job#373]
你好，针对某些特殊的延迟任务，比如说订单的超时关闭这类只在某一个时间点（过期时间）触发的任务，可否设计支持一个延时队列模块。队列的插入可服务间restApi调用，插入时可携带业务参数。
同一类别的延时任务做为一个Handler 存在

**Comment by xuxueli** [comment]
你好，Job主要处理基于时间的需求场景。MQ更适合处理基于事件的需求场景。
上述订单超时，可以参考下XXL-MQ，支持重试、延迟消费等特点。
