### ISSUE TITLE
JobThread:toStop should be volatile?

### ISSUE THREAD

**Issue by Mrchenli** [xuxueli/xxl-job#377]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
cloned from github

### Expected behavior
JobThread:toStop
private boolean toStop = false;
why is not follows:
private volatile boolean toStop = false;

### Other information
  public static void main(String[] args) throws InterruptedException {
        JobT t = new JobT();
        t.start();
        TimeUnit.SECONDS.sleep(1);
        t.toStop=true;
        t.join();
    }

    public static class JobT extends Thread{

        private volatile boolean toStop;
        @Override
        public void run() {
            System.out.println("toStop:"+toStop);
            while (!toStop){

            }
            System.out.println("toStop:"+toStop);
        }
    }

toStop:false
Disconnected from the target VM, address: '127.0.0.1:54435', transport: 'socket'
toStop:true

while without volatile the JobT will not stop

**Comment by xuxueli** [comment]
你好，在简单的 while(true) 场景下内存同步不及时会到导致暂停变量无法感知。
但是，JobThread:run 内部逻辑复杂，一次循环之后会重新同步主内存中变量，可以真实运行测试下。
不过，为了严谨性，稍后会添加上改修饰符。
