### ISSUE TITLE
执行器已经注册到注册中心数据库中，为什么页面显示不出来

### ISSUE THREAD

**Issue by Lixianshengchao** [xuxueli/xxl-job#378]
执行器已经注册到注册中心数据库中，为什么页面显示不出来？

**Comment by Mrchenli** [comment]
你是指xxl_job_qrtz_trigger_registry这个表有 执行器管理页面没有吗 管理页面查的xxl_job_qrtz_trigger_group这里 你需要在页面手动添加一个执行器集群的名称

**Comment by Lixianshengchao** [comment]
执行器可以自动发现？不需要手动添加

**Comment by talywy** [comment]
@Lixianshengchao 自动发现是要做如下操作：
1. 你在admin端增加执行器时，指定正确的执行器名称（由执行器配置文件中xxl.job.executor.appname属性的值确定），并采用自动注册模式
2.另外执行器配置正确的admin端地址才可以。执行器启动之后会自动向admin端注册自己。

看你的情况，目测是你只做了操作2，没有做操作1

**Comment by xuxueli** [comment]
@Lixianshengchao 你好，目前执行器支持自动注册，自动发现的。

**Comment by Genitana** [comment]
@talywy 的方式是正解， 自动注册其实只是自动发现注册的IP ，在服务端，还是要手动建一下
