### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by waterWang** [xuxueli/xxl-job#38]
我将executor-example中的log4j.xml 变成 log4j.properties

代码如下

`
log4j.rootLogger=CONSOLE,FILE,job
log4j.addivity.org.apache=true

log4j.logger.com.chinasofti.ark.bdadp.schedule.core =CONSOLE,FILE,job
log4j.logger.com.chinasofti.ark.executor =CONSOLE,FILE,job

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Target=System.out
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} executor-example [%c]-[%t]-[%M]-[%L]-[%p] %m%n

log4j.appender.FILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FILE.file=../logs/executor-example.log
log4j.appender.FILE.append=true
log4j.appender.FILE.encoding=UTF-8
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} executor-example [%c]-[%t]-[%M]-[%L]-[%p] %m%n

log4j.appender.job=com.chinasofti.ark.bdadp.schedule.core.log.JobFileAppender
log4j.appender.job.filePath=../logs/jobhandler/
log4j.appender.job.layout=org.apache.log4j.PatternLayout
log4j.appender.job.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} executor-example [%c]-[%t]-[%M]-[%L]-[%p] %m%n
`

调度中心运行job，一直提示XxlJobFileAppender.java 中fos.write(layout.format(event).getBytes("utf-8"));的layout为null，，，我使用的版本是1.6.1-SNAPSHOT

**Comment by xuxueli** [comment]
你好，检查一下log4j.xml是否和example执行器一致，同时建议前往release界面下载稳定版本啊。

**Comment by waterWang** [comment]
@xuxueli 默认的log4j.xml 是正常的，但是我将xml修改为properties后报错的

**Comment by xuxueli** [comment]
你好，感谢关注哈！
这是因为旧版本依赖log4j但是配置错误导致的。
在新版本（v1.7.0：https://github.com/xuxueli/xxl-job/releases/tag/v1.7.0 ）中任务日志改为底层自主实现，不在依赖log4j，因此不会出现类似问题。
