### ISSUE TITLE
作者您好，我可否创建一个QQ交流群加你进来

### ISSUE THREAD

**Issue by bosen365** [xuxueli/xxl-job#380]

**Comment by bosen365** [comment]
![xxl-job](https://user-images.githubusercontent.com/6869773/39953268-73b2705e-55da-11e8-92dc-5c1c6b72ad79.png)

**Comment by xuxueli** [comment]
你好，可以加入官方交流群啊！

**Comment by bosen365** [comment]
官方交流群号多少啊

**Comment by xuxueli** [comment]
在这里：http://www.xuxueli.com/page/community.html
