### ISSUE TITLE
在处理jobhandler上策略问题

### ISSUE THREAD

**Issue by wuweiit** [xuxueli/xxl-job#381]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
调度中心
### Expected behavior
Springboot 重启注册jobhandler
### Actual behavior
注册失败，导致整个应用不能启动
### Steps to reproduce the behavior

Springboot 自动重启注册jobhandler

### Other information
SpringBoot的重启配置使用IDEA配置的，监听到文件变化自动重启。

问题的关键掉在
XxlJobExecutor 166行

建议：
对注册策略改一下：比如：覆盖方式。

**Comment by xuxueli** [comment]
你好，覆盖方式目前会有问题。因为重新初始化 “XxlJobExecutor” 组件，除了重新加载JobHandler，还会重新初始化Jetty，最终会因为端口冲突无法启动。

所以，建议的方式是在 XxlJobExecutor 的 内部增加一个是否初始化的标示，比如 “inited”，重复初始化时直接return，不执行后续逻辑。

如果着急，可以采用上述方式调整、测试下。

稍后针对这种情况会进行优化处理。

**Comment by wuweiit** [comment]
感谢如此详细的解说，我占时是这样处理的把那个抛出的异常注释了，会重新注册覆盖。
![image](https://user-images.githubusercontent.com/4202865/41386971-ff6fba02-6fb6-11e8-84a4-c4459424fedd.png)
