### ISSUE TITLE
执行时间和钉钉通知

### ISSUE THREAD

**Issue by wangjunbo** [xuxueli/xxl-job#382]
希望在调度日志那里加上执行时间一栏  
报警通知可以使用钉钉  
任务管理: 默认显示所有执行器  
调度日志：显示调度描述一栏  
清理：调度器和任务选项现在是不可用状态

**Comment by xuxueli** [comment]
你好，感谢反馈。
1，任务日志已经提供执行时间字段，如果需要展示耗时可以对比调度与执行时间获取。
2，告警已经预留了api，可以经过定制第三方通知。如，短信、钉钉等。
3，任务管理只显示选择的执行器，因为后续会以执行器为粒度做权限控制。
4，调度日志，列太窄显示有样式问题所以只展示id。可自行定制。
5，清理功能上的选项，同步的日志界面上的筛选选项，更新日志筛选选项即可。
