### ISSUE TITLE
日志太多，能否删减

### ISSUE THREAD

**Issue by silloy** [xuxueli/xxl-job#383]
![image](https://user-images.githubusercontent.com/12909107/40175795-e7699fb0-5a0b-11e8-9bbc-5a3998f19cf0.png)
心跳日志太多，能否设置，或者删减

**Comment by xuxueli** [comment]
你好，24h 之内心跳日志只有3000行不到，不是很多啊。可以通过调整日志级别隐藏日志信息的。
