### ISSUE TITLE
客户端jetty线程池

### ISSUE THREAD

**Issue by yfliuas** [xuxueli/xxl-job#39]
今天将代码clone下来了，发现客户端使用jetty时线程池中线程开了200个，建议改下。建议日志处理不要强制使用log4j，祝好。

**Comment by xuxueli** [comment]
你好，感谢关注！
这两个问题在新版本(v1.7.0)都有调整。
1、jetty升级到了9.2.x，线程池采用默认配置；
2、日志处理改为底层自主实现，不再依赖log4j；
