### ISSUE TITLE
为什么要使用groovyclassloader

### ISSUE THREAD

**Issue by fatherican** [xuxueli/xxl-job#391]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.7
### Expected behavior
No
### Actual behavior
No
### Steps to reproduce the behavior
No
### Other information
想请教，项目中为什么使用GroovyClassloder来加载类，
而不是自定义一个类加载器去实现,毕竟使用groovy需要
引入其依赖。

**Comment by xuxueli** [comment]
你好，因为groovyclassloader热部署支持较好，相应api也很友好，也比较稳定。
