### ISSUE TITLE
定时任务实时消息

### ISSUE THREAD

**Issue by zhizhi555555** [xuxueli/xxl-job#394]
有没提供比如我定义了一个定时任务列表，1点触发任务，2点触发任务，3点触发任务 。执行同一个业务流程，而不需要去配置corn表达式呢？

**Comment by xuxueli** [comment]
你好，这种情况建议使用 XXL-MQ 啊。每次触发都是一个MQ消息，支持指定延迟消费时间，重试次数的啊。
