### ISSUE TITLE
分片问题

### ISSUE THREAD

**Issue by EmineWang** [xuxueli/xxl-job#396]
分片问题请教下大神
现有一个任务，2个执行器集群A、B。。

情景：由于需要处理的数据总量不定，需要当JobHandler每次执行时，从订单库中实时拉取。

比如在调度集群A、B过程中，
1、当 A 机器执行时，当时库中获取到2条数据要处理，那么算得各个机器各执行1条；即 A-> 执行1条
2、当 B 机器执行时，此时库中获取到4条数据，算得各个机器各执行2条；即  B->执行2条
最终上面A B一共只执行了3条。 还有一条未执行。

请问这种情况怎么处理呢。

**Comment by conghai-yaoch** [comment]
xxl-job是把任务分片的处理交给了执行器，每台执行器需要计算自己处理的任务范围，这样带来的问题比较多。最好是能把总任务数据提交给调度器，由调度器统一进行任务分片，然后再分发到执行器。
