### ISSUE TITLE
首页统计成功、失败和进行中任务数量的BUG

### ISSUE THREAD

**Issue by wangshulun** [xuxueli/xxl-job#397]
`<select id="triggerCountByDay" resultType="java.util.Map" >
		SELECT
			DATE_FORMAT(trigger_time,'%Y-%m-%d') triggerDay,
			COUNT(handle_code) triggerDayCount,
			SUM(CASE WHEN handle_code = 0  then 1 else 0 end) as triggerDayCountRunning,
			SUM(CASE WHEN handle_code = 200 then 1 else 0 end) as triggerDayCountSuc
		FROM XXL_JOB_QRTZ_TRIGGER_LOG
		WHERE trigger_time BETWEEN #{from} and #{to}
		GROUP BY triggerDay;
    </select>
`
会遗漏触发失败的log（执行器地址为空），首页会将这种情况统计为running。
解决办法：sql加条件 AND trigger_code = 200

**Comment by xuxueli** [comment]
你好，感谢反馈！
问题已修复，并推送master分支，将会跟随 v1.9.2 分支发布。
