### ISSUE TITLE
数据分片

### ISSUE THREAD

**Issue by ritchieyan** [xuxueli/xxl-job#400]
为什么不考虑逻辑分片呢，让每台机器可以并行处理多个分片任务，如果单纯靠机器分片，可能会大大降低机器的利用率，如果数据量较大，需要扩充大量机器，大大增加了机器资源的成本

**Comment by xuxueli** [comment]
你好，通过机器控制分片，可以更方便的实现动态分片。
针对你提到的数据量较大的情况，可以在每个分片任务内部开启多线程处理。比如每2W条数据分配一个子线程，当数据量从10W波动到20W时，只需要动态调整子线程数据即可，保证数据及时处理。
