### ISSUE TITLE
建议增加任务基准时间

### ISSUE THREAD

**Issue by yimu171** [xuxueli/xxl-job#401]
**基准时间**是任务的预期执行时间，这个时间在调度、执行延迟，失败重试后依然保持不变，在数仓管理类任务中极其重要。
#### 推荐实现方案
1. 任务实例表增加基准时间字段 
2. 基准时间可以通过环境变量传递给任务脚本。
3. 脚本增加时间模板，运行时利用基准时间替换模板变量
    例如：基准时间为2018-06-01 12:00:00 将模板变量${yyyyMMddHH,-1d}替换为2018053112
4. 增加失败任务手动重试，历史任务追溯等功能，这样不同的基准时间运行的不同的任务，实现任务幂等性操作
*3) 4) 是易用性拓展，非必须*

**Comment by yimu171** [comment]
该功能能够解决 https://github.com/xuxueli/xxl-job/issues/330 问题

**Comment by xuxueli** [comment]
你好，感谢反馈！
流程任务透传动态参数已经假如TODO，将会排期规划；可以在 https://github.com/xuxueli/xxl-job/issues/330 跟进
