### ISSUE TITLE
任务突然未调度

### ISSUE THREAD

**Issue by sjby365** [xuxueli/xxl-job#404]
一任务之前一直正常，今天发现未调度，也无调度日志    其他任务都正常 有可能哪方面原因？

**Comment by sjby365** [comment]
已解决 其中一台系统时间不一致导致；

其中一台系统时间误设置为6.12号凌晨，导致调度中其他任务都不执行，只有重新设置新时间才能运行，这种情况怎么解？？？

**Comment by xuxueli** [comment]
你好，这种情况首先需要机器时钟同步，然后更新一下cron配置即可。因为旧机器时间已经同步到了底层表里。

**Comment by sjby365** [comment]
我是手动更新完所有任务才让当天任务执行的   时钟这方面后期能不能优化下
