### ISSUE TITLE
您好我在测试任务调度的时候出现了如图所示的问题，不知道怎么解决。

### ISSUE THREAD

**Issue by 18832057259** [xuxueli/xxl-job#406]
![d92785180f39b0e3b6ae23e6c472b9b](https://user-images.githubusercontent.com/24432282/41334723-2ce293d6-6f19-11e8-9b0d-75bbf837aa6f.png)

**Comment by 18832057259** [comment]
不知道是什么原因，是不是少了什么配置呀

**Comment by 18832057259** [comment]
希望群里有知道的大神给解答一下
![1528877967 1](https://user-images.githubusercontent.com/24432282/41338765-a853a33c-6f25-11e8-9028-87b20bb48543.png)

**Comment by ghostg00** [comment]
端口号是80的?

**Comment by hjtoday** [comment]
![image](https://user-images.githubusercontent.com/24535447/41394211-bb8c0da2-6fdb-11e8-873c-e59d0a4389ee.png)
执行器没有设置地址

**Comment by xuxueli** [comment]
你好，执行器地址建议填写IP端口号，而且，执行器端口默认为9999的内嵌端口，而不是web项目的端口，确认下啊。
