### ISSUE TITLE
在测试跑定时任务时，一直报这个错

### ISSUE THREAD

**Issue by shenfeihong** [xuxueli/xxl-job#408]
在测试跑定时任务时，一直报这个错
![error](https://user-images.githubusercontent.com/17996114/41402512-0e197ad2-6ff5-11e8-8d4b-0d8b7169fa84.png)

**Comment by shenfeihong** [comment]
![error](https://user-images.githubusercontent.com/17996114/41402641-6b917b24-6ff5-11e8-82c4-5a3dab87896c.png)

**Comment by xuxueli** [comment]
你好，从Log看该IP端口号调度中心无法访问，网络问题。
