### ISSUE TITLE
xxl-job 无法抓取docker容器IP

### ISSUE THREAD

**Issue by amoyx** [xuxueli/xxl-job#409]
把项目放到docker后， 在xxl-job中抓到的是宿主机IP地址，如何要xxl-job去抓取docker容器IP地址? 另外如何固定端口地址？

**Comment by xuxueli** [comment]
你好，这种情况可以在执行器配置文件里指定注册IP地址来解决问题。

**Comment by amoyx** [comment]
@xuxueli 好的，多谢，我试试
