### ISSUE TITLE
jetty内嵌在执行器里放在jboss服务器下无法正常工作

### ISSUE THREAD

**Issue by star9500** [xuxueli/xxl-job#410]
内嵌了jetty，执行器放在jboss（版本4.2.3.GA）服务器下，jetty启动正常，看端口也启动着，但是无法访问，无法进行通信，请问这是什么原因

**Comment by beston123** [comment]
试一下我找个PR， #339

**Comment by beston123** [comment]
试一下这个PR， #339

**Comment by star9500** [comment]
@beston123 好的，我看一下，多谢了

**Comment by xuxueli** [comment]
赞！可以考虑netty。
jetty无法通讯这个还没遇到过，推测端口拦截了。
