### ISSUE TITLE
脚本任务（比如curl -XDELETE ... 这种）调度到执行器太麻烦，建议增加LOCAL(SHELL)模式在调度中心本地可执行脚本。

### ISSUE THREAD

**Issue by cheocs** [xuxueli/xxl-job#411]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
调度器自身运行SHELL脚本
### Actual behavior
调度器调度任务到执行器上去执行，中间过程多余，比如我们的脚本是删除远端服务器上的日志，通过执行器会增加调用链的长度，难免繁琐。
### Steps to reproduce the behavior
在创建任务时直接支持LOCAL(SHELL),即在执行器端执行脚本。

**Comment by yhan219** [comment]
+1

**Comment by xuxueli** [comment]
你好，感谢反馈！
不建议在调度中心运行业务Job逻辑，因为会占用调度线程，影响调度中心稳定性。
如果期望单机部署，可以考虑同时不是调度中心与执行器。
