### ISSUE TITLE
DemoJobHandlerTest测试代码出错

### ISSUE THREAD

**Issue by iamzken** [xuxueli/xxl-job#413]
![_15295650518982](https://user-images.githubusercontent.com/10125384/41703455-eeaa03d0-7565-11e8-9787-2086826861e4.png)

**Comment by iamzken** [comment]
![_15295650518982](https://user-images.githubusercontent.com/10125384/41703342-8e530ed2-7565-11e8-8394-d4b028c14e66.png)

**Comment by xuxueli** [comment]
你好，不要再此处代码 debug ，ide会触发tostring等操作。将短点加载业务代码里即可。
