### ISSUE TITLE
Springboot 版本，共享给大家。

### ISSUE THREAD

**Issue by maylovelil** [xuxueli/xxl-job#414]
改动比较大,基本摒弃原有的SpringMvc配置：
https://github.com/maylovelil/xxl-job-springboot

**Comment by ghostg00** [comment]
何时作者整合下啊?

**Comment by sxyseo** [comment]
希望作者能出个Boot版。

**Comment by xuxueli** [comment]
已合并至：https://github.com/xuxueli/xxl-job/issues/154
