### ISSUE TITLE
建议cron表达式添加类似如下的生成界面，方便生成表达式

### ISSUE THREAD

**Issue by PC-Chiu** [xuxueli/xxl-job#416]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/8520547/41886703-1d97ac56-7930-11e8-8e5b-379e4091d997.png">

**Comment by gstripe** [comment]
这个提议不错，支持。
我现在也是在线找一个来配置，选好之后再复制进去。
http://cron.qqe2.com/

**Comment by sniperqpc** [comment]
https://gitee.com/finira/cronboot

**Comment by xuxueli** [comment]
赞！一致想加上这个插件，不过一致没有找到满意的。

**Comment by patience00** [comment]
有点不人性化了，你让用户去配置任务执行周期，还要去学一下cron表达式额？建议弄成自定义配置执行周期，单位为秒都可以呀

**Comment by xianwei** [comment]
关注

**Comment by hujiang75277381** [comment]
对于这个问题，我们项目组的解决方案是 前端写一个控件,（也做了一个推荐调度）：
![image](https://user-images.githubusercontent.com/8623830/53614119-a44bff80-3c13-11e9-9371-478e8c820c90.png)

![image](https://user-images.githubusercontent.com/8623830/53614127-b0d05800-3c13-11e9-8e50-e96c2118c0a1.png)

![image](https://user-images.githubusercontent.com/8623830/53614144-bfb70a80-3c13-11e9-8972-28e09dcb8178.png)

**Comment by ting6688** [comment]
关注

**Comment by flycloudOne** [comment]
期待尽快加上

**Comment by lvgitt** [comment]
> 对于这个问题，我们项目组的解决方案是 前端写一个控件,（也做了一个推荐调度）：
> ![image](https://user-images.githubusercontent.com/8623830/53614119-a44bff80-3c13-11e9-9371-478e8c820c90.png)
> 
> ![image](https://user-images.githubusercontent.com/8623830/53614127-b0d05800-3c13-11e9-8e50-e96c2118c0a1.png)
> 
> ![image](https://user-images.githubusercontent.com/8623830/53614144-bfb70a80-3c13-11e9-8972-28e09dcb8178.png)

这个很不错

**Comment by mopoliujia** [comment]
期待尽快加上

**Comment by xuxueli** [comment]
最新版本以支持，可以体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
