### ISSUE TITLE
任务线程销毁漏洞

### ISSUE THREAD

**Issue by cheocs** [xuxueli/xxl-job#421]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by cheocs** [comment]
finally的代码该拆分到try中,不然任务明明停止了却要多执行一次。

**Comment by cheocs** [comment]
直接导致使用覆盖之前调度策略的任务运行犹如单机串行一样，只是强制返回了执行失败的结果而已。

**Comment by xuxueli** [comment]
“覆盖之前调度策略，会销毁旧线程中断旧任务，并不存在上述反馈few问题。”

提问题前请先仔细熟悉代码。

**Comment by xuxueli** [comment]
“覆盖之前调度策略，会销毁旧线程中断旧任务，并不存在上述反馈的问题。”

提问题前请先仔细熟悉代码。
