### ISSUE TITLE
不知道xxljob底层在使用Quartz做调度时有没有遇到山么限制？

### ISSUE THREAD

**Issue by cheocs** [xuxueli/xxl-job#425]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，确实遇到了一些限制。最主要的是定制不灵活，xxl-job提供了数十项功能特性，其中任务触发仅仅时其一个很小的模块，quartz虽然可以承担但是同时包含大部分用不到的冗余特性，而且无法对其底层做定制优化。

因此，TODO排期中规划，考虑移除quartz自研任务触发组件，仍然在规划中。
