### ISSUE TITLE
1.8.x 升级到1.9.2后邮件发送乱码

### ISSUE THREAD

**Issue by sjby365** [xuxueli/xxl-job#426]
1.8升级到1.9.2后邮件发送标题，内容都是乱码 
``
![l](https://user-images.githubusercontent.com/20899681/42308949-d821f942-8069-11e8-9bcc-1d5bf94b9e3d.png)

**Comment by xuxueli** [comment]
你好，版本 v1.9.2 仍然在迭代中， 尚未稳定，不日发布。推荐实用release版本啊。
