### ISSUE TITLE
执行器最好有个状态列

### ISSUE THREAD

**Issue by zhangqunshi** [xuxueli/xxl-job#43]
第一试用发现执行器存在了，但没有看到任务的日志，后来到执行器管理页面发现执行器存在，但Online列没有值不知道怎么回事。最后把IP和状态分成两个列。

这样状态可以单独表述，不论是否有IP地址。

如果你需要我可以帮你改一下。

**Comment by xuxueli** [comment]
你好，你的意思是指：新增一列 “Online机器状态”，如果存在Online机器表示执行器正常，否则表示执行器异常，对吗？

**Comment by zhangqunshi** [comment]
对，差不多吧。也就是说对于每个执行器可以增加一个状态的属性，来表示这个执行器是连接还是断开连接了。
当执行器注册之后，就让其IP地址一直存在，不要让其随状态而变化。我感觉这是两个独立的属性。

**Comment by wzshuang** [comment]
执行器注册方式如果是手动录入的话，online机器那一列就会显示 ip:port，即使机器不在线也会显示，看起来确实有点怪异。

**Comment by xuxueli** [comment]
执行器默认均未在线状态，下线机器会自动清理掉。
