### ISSUE TITLE
当执行器集群部署，任务耗时较久时，还是有可能会遇到任务并发执行的。

### ISSUE THREAD

**Issue by Dorae132** [xuxueli/xxl-job#430]
如果任务的执行时间超过了调度间隔，并且执行器集群部署，那么当两次调度落在不同执行器时，就会导致任务并发运行。这一点和文档5.4.5的解释是有冲突的。

**Comment by cullenx** [comment]
同问？？？

**Comment by xuxueli** [comment]
你好，这种情况可以结合 xxl-job 的 “单机路由策略”（第一台、一致性哈希等） + “阻塞策略” 避免：可保证调度落到单机，结合单机阻塞策略可以基本保障重复调度问题。
