### ISSUE TITLE
对于任务调度成功，但是此时执行器宕机的情况是不是应该额外处理下？

### ISSUE THREAD

**Issue by Dorae132** [xuxueli/xxl-job#431]
任务调度成功，执行器宕机。
此时会导致任务一直存在调度器中的jobFailMonitor线程的监控队列，只能通过重启执行器，终止任务的方式进行解决。

**Comment by xuxueli** [comment]
你好，这个问题在 v1.9.2 (迭代中) 做了优化，执行器宕机时会将任务结果落盘，重启后会自动回调任务结果。
