### ISSUE TITLE
能否提供路由策略的组合使用，例如我可以给同一任务分配多个路由策略，比如同时有忙碌转移和轮询，前者优先级高于后者，任务执行时首先忙碌检测，如果所有的机器都忙碌那么就使用第二种。

### ISSUE THREAD

**Issue by cheocs** [xuxueli/xxl-job#432]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by cheocs** [comment]
这个问题好像重复了～，不过路由策略的选项确实有让我们觉得还有改进的地方，希望新版本越来越好。

**Comment by xuxueli** [comment]
你好，感谢反馈！
忙碌转移是为了避免调度阻塞情况，针对你的需求，可以定制实现一个新的路由策略，比如叫做 “忙碌转移-轮训” 策略，只需要开发一个实现类即可啊。
