### ISSUE TITLE
调度中心集群模式下LRU并不反应真实情况

### ISSUE THREAD

**Issue by cheocs** [xuxueli/xxl-job#435]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by cheocs** [comment]
调度器集群模式下彼此通过DB统一数据，可是LRU、LFU等算法在实现的时候只是在内部使用LinkedHashMap，并未持久化路由数据到数据库，这样一来调度中心各节点掌握的执行器情况各不一致，会造成多个调度器同时调度某一个执行器，而此时其它执行器却处于空闲状态，那么这种伪LRU和LFU路由算法带来的后果是严重的。

**Comment by cheocs** [comment]
比如有A和B两台调度器，1、2、3共三台执行器。
两个任务task1、task2都是LFU路由，这是恰好A触发task1接着B触发task2。
A之前的调度顺序是1、2
B之前的调度顺序也是1、2
那么task1和task2都被安排到3这台执行器上了。

**Comment by cheocs** [comment]
我相信阻塞策略也是有这个痛点的，表现为【覆盖之前调度】这能覆盖单执行器上的任务。不知我的考虑是否是对的，如果真是这样那么你们愿不愿意把路由和阻塞的信息也持久化到数据库中，还是你们有另外的考虑呢？

**Comment by Dorae132** [comment]
这里的阻塞处理确实是只针对单机有效，另外任务串行化也是单机。
执行器集群部署还是会存在任务并行执行的情况

**Comment by xuxueli** [comment]
你好，感谢反馈！
1、阻塞策略时单机的，需要配合单机路由策略一起使用，比如“第一台、一致性哈希” 等；
2、LRU、LFU策略目前也是单机，随着调度数量上升，最终会达到策略目标。
