### ISSUE TITLE
底层rpc当初为什么不考虑使用dubbo

### ISSUE THREAD

**Issue by hanwangkun** [xuxueli/xxl-job#437]
现在很多公司都使用dubbo作为微服务框架，如果当初底层rpc使用dubbo，那么就可以与使用这些dubbo服务的公司进行无缝集成，也大大方便接入效率和改造成本，就不用在执行器上写JobHander，直接就调用dubbo接口搞定。

**Comment by Xiaolitongxue** [comment]
同感。利用dubbo的泛化调用机制完成定时任务调度，很方便。

**Comment by Dorae132** [comment]
不使用rpc框架，zk等，作者的目的应该就是尽量轻量化，减少外部依赖。

**Comment by xuxueli** [comment]
你好，目前并不考虑接入dubbo类似的第三方重量中间件，原因如 @Dorae132 所说，尽量保持轻量级。
目前底层基于 xxl-rpc，轻量的同时做一些特性定制也更加灵活方便。
