### ISSUE TITLE
任务依赖分组

### ISSUE THREAD

**Issue by xingxingt** [xuxueli/xxl-job#442]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
能否优化下任务列表 ，如果任务列表达到几百个的话就很难维护，可否能建立文件夹,然后用户可以自定义文件夹来进行任务的分类和分层级依赖，就像宙斯的任务列表一样，比较友好！而且方便管理；
### Other information

**Comment by hexing521** [comment]
能否优化下任务列表 ，如果任务列表达到几百个的话就很难维护，可否能建立文件夹,然后用户可以自定义文件夹来进行任务的分类和分层级依赖，就像宙斯的任务列表一样，比较友好！而且方便管理；

**Comment by blue20080** [comment]
同意楼上的

**Comment by xuxueli** [comment]
你好，建议拆分不同执行器来维护。不同执行器可以复用相同 AppKey。

**Comment by zhangnew** [comment]
可以添加像 Azkaban 那样的项目功能，在项目下面组织任务，然后对不同的用户授予不同的权限：查看、执行、修改、删除等；

现在貌似只能通过不同执行器来控制不同用户权限，还是很不方便
