### ISSUE TITLE
其他系统对接调度中心

### ISSUE THREAD

**Issue by zhu-wen** [xuxueli/xxl-job#452]
您好，文档中的调度中心API只有如下四个。
![image](https://user-images.githubusercontent.com/36438433/43178028-e8ace3e6-8ffd-11e8-8e86-28b7a400723e.png)
其他的系统应该如何通过非web页面操作的方式对接调度中心呢？例如大批量的增加和删除调度。

**Comment by rongmin** [comment]
同问？需要自己拓展编码么？

**Comment by xuxueli** [comment]
你好，除了通过调度中心界面操作之外，可参考任务界面操作的ajax请求。任何ajax接口均可配置成为API服务，只需在待启用的API服务上添加 “@PermessionLimit(limit = false)” 注解取消登陆态拦截即可；
