### ISSUE TITLE
请问在多个任务并发执行时，是用什么算法决定并发任务的优先级的？如果我要改进并发调度算法时应该在源代码的什么地方改进？望给予帮助，万分感谢！

### ISSUE THREAD

**Issue by ZhenxueXu** [xuxueli/xxl-job#454]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，目前任务之间时隔离的，并没有优先级。可以通过定制执行器依赖core实现，在任务线程内部。
