### ISSUE TITLE
调度任务会阻塞问题

### ISSUE THREAD

**Issue by longhuixuan** [xuxueli/xxl-job#455]
阻塞处理策略：丢弃后续调度。
触发了阻塞策略，任务也没有调用到执行器上面。后续的任务也没有办法执行，不知道为什么？

**Comment by xuxueli** [comment]
你好，启用 “丢弃后续调度” 阻塞策略，一旦发生阻塞，后续任务是不会运行的，正常的。会直接标记失败返回。
