### ISSUE TITLE
simple trigger的实现咨询

### ISSUE THREAD

**Issue by rongmin** [xuxueli/xxl-job#456]
Please answer some questions before submitting your issue. Thanks!

### Other information

咨询下这个特性有没具体的时间表？另外，我考虑自己实现的话，能否帮忙点出关键的需要改造的类名？谢谢！

**Comment by xuxueli** [comment]
你好，SimpleTrigger 已经假如TODO排期。预计 2.x 进行迭代。如果自己实现可以参考现有Cron触发方式实现。
