### ISSUE TITLE
如何迁移任务

### ISSUE THREAD

**Issue by daiing** [xuxueli/xxl-job#457]
如何迁移所有的任务，在文档中没看到相关材料，把整个数据库迁移过去并不行
从测试环境到正式环境，不能重新配置一遍把？

**Comment by cullenx** [comment]
可以

**Comment by daiing** [comment]
@cullenx 请问要迁移哪张表才行

**Comment by xuxueli** [comment]
你好，任务迁移时只需要迁移 xxl-job 依赖的相关表。相关表可以参考建表SQL；
