### ISSUE TITLE
中止任务时，等待本次调度执行完成后再停止当前调度

### ISSUE THREAD

**Issue by sruby** [xuxueli/xxl-job#458]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
等待本次调度执行完成后再停止当前调度
### Actual behavior
中止任务时，会立即停止并清空调度队列；
### Steps to reproduce the behavior
打算的实现方式有2种：
方式1：
目前系统有两类任务：a:允许立即中止和b:不允许立即中止（中途停止要恢复数据比较麻烦）。
所以打算把任务分成两类，用执行参数来传递任务类型的标识，在job kill处获取执行参数，如果是a类则只修改isStop标识，不interrupt。

方式2：
直接去掉kill方法的逻辑，去掉oldJobThread.interrupt();
因为当前系统的任务不会存在进入阻塞队列的情况，不需要清空阻塞队列，只需要停止本次调度即可。

麻烦看下这两种实现方式是否妥当？
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
如果需要定制，推荐实用方式1，应该可以满足你的需求。
