### ISSUE TITLE
xxljob 疯狂打日志，有什么办法可以控制吗

### ISSUE THREAD

**Issue by silloy** [xuxueli/xxl-job#459]
日志产生在 /var/log/message 文件中，而logpath 里的设置也有生效
问题是 /var/log/message 里生成大量的日志，一天差不多有1G的量，有什么办法可以避免吗

**Comment by cullenx** [comment]
修改一下admin模块中 log4j.xml里边配置 简单就是 整体 level 改为warn  也可以单独控制这个类的 都可以

**Comment by silloy** [comment]
好的，已经解决，centos 平台删除 <appender-ref ref="CONSOLE"/> 可以解决

**Comment by xuxueli** [comment]
你好，感谢反馈！
上述日志来源于任务监控线程。目前已经做了优化，运行中任务的监控Log改为debug级别，减少非核心日志量；
