### ISSUE TITLE
执行器不能注册调度中心

### ISSUE THREAD

**Issue by pai01234** [xuxueli/xxl-job#460]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Other information
调度中心log:
![image](https://user-images.githubusercontent.com/30950645/43503479-20a40f4c-9592-11e8-83fa-74fc81301f0a.png)
执行器log：
![image](https://user-images.githubusercontent.com/30950645/43503497-378e7b5c-9592-11e8-95ef-f00ccd11678c.png)

**Comment by xuxueli** [comment]
你好，心跳注册失败，应该回调地址或这网络有问题，可以确认下回调地址是否配错。
