### ISSUE TITLE
jobLog triggerMsg广播模式下，对字符长度未截取,执行器机器过多，会导致sql异常，导致调度失败。

### ISSUE THREAD

**Issue by jeanter** [xuxueli/xxl-job#463]
jobLog triggerMsg广播模式下，对字符长度未截取,执行器机器过多，会导致sql异常，导致调度失败。
其他路由模式下均有对字符长度做截取。
另外，trigger_group表address_list长度为300，线上同一app的执行器地址超过15个就会导致地址丢失。调度逻辑里均是是这里获取的地址列表.

**Comment by xuxueli** [comment]
你好，感谢反馈！
1、任务执行日志、调度日志字段类型调整，改为text类型并取消字数限制（迭代中，近期发布）；
2、执行器机器列表字段已经调整长度为 512 ，支持30台机器的集群配置，已经基本够用了（v1.9.0 开始支持）；
