### ISSUE TITLE
线程过多问题

### ISSUE THREAD

**Issue by 369431735** [xuxueli/xxl-job#464]
为什么要把每个任务都固定在某一个线程里面执行而不是使用线程池了？ 如果JobId过多，这样不会导致线程泛滥吗？
 使用线程池也可以终止任务，或者查询该任务Id是否尚未被执行完啊。
 建议是否可以在这个地方优化一下

**Comment by wangfan9002** [comment]
我觉得执行器是在client端运行的，一般不会有太多的定时任务，每个任务对应一个线程，其实也不会出现太多线程, 而且这些线程在正常运行时，一般也不去回收，线程池的场景一般是线程很容易执行结束，回收到池子中供下次需求直接使用.

**Comment by xuxueli** [comment]
@369431735 @wangfan9002 
你好，感谢关注！
任务线程隔离是为了避免任务资源竞争干扰。
而且，除非高密集任务，执行器并不会运行太多线程的。因为任务线程存在自我销毁机制，连续多次轮空会自动中断销毁的。

**Comment by qixiaobo** [comment]
频繁创建销毁线程也比较耗费资源哦
