### ISSUE TITLE
关于忙碌转移设计如果执行器要是都忙碌就把任务设置为失败了的一点想法

### ISSUE THREAD

**Issue by 369431735** [xuxueli/xxl-job#465]
如题，建议在验证忙碌的时候，是不是可以有一个忙碌度的概念，如忙碌度不是全为0，就选最不忙碌的一个执行器  是否好一些。而不是直接设置为失败

**Comment by xuxueli** [comment]
你好，感谢反馈！
忙碌转移目的在于避免阻塞任务的同时尽量调度平均。
不过你的建议也很有意义，已经假如TODO列表，将会后续讨论排期；

**Comment by stormsend** [comment]
其实这个忙碌转移有些误解，字面理解是机器负载高，然后转移，其实是当前指定的任务正在运行或者阻塞，路由到另一台机器，如果每天运行一次的任务，没有任何意义
