### ISSUE TITLE
数据库可以用postgres吗？

### ISSUE THREAD

**Issue by flykarry** [xuxueli/xxl-job#469]
项目采用postgres数据库，可以用吗？还是必须再安装一个mysql？

**Comment by IAMTJW** [comment]
可以尝试改造一下，基于mybatis改造或者换成mybtais-plus

**Comment by xuxueli** [comment]
你好，主版本目前基于mysql迭代，多数据库支持仍然在排期中。
可以参考 “分支版本汇总”，里面有其他数据库版本：
https://github.com/xuxueli/xxl-job/issues/154
