### ISSUE TITLE
任务调度时间间隔小于任务执行时长，已经被调度且执行完的任务状态异常

### ISSUE THREAD

**Issue by akun2014** [xuxueli/xxl-job#471]
Please answer some questions before submitting your issue. Thanks!

### Expected behavior
demoJobHandler的执行时长为10s，调度间隔为5s。该任务的调度状态在调度中心将会出现截图的情况。已经执行完的任务，依旧显示“执行中”。如果终止其中一个任务，将会终止demoJobHandler所有“执行中”的任务。
### Actual behavior
![image](https://user-images.githubusercontent.com/10229751/44069062-b04cabfa-9faf-11e8-97af-613c99a1e9b9.png)

![image](https://user-images.githubusercontent.com/10229751/44069045-a1196b78-9faf-11e8-9f4f-7497ef1c0b72.png)
![image](https://user-images.githubusercontent.com/10229751/44069418-2fcbbdc0-9fb1-11e8-93b1-9602385c73ed.png)

### Other information

**Comment by xuxueli** [comment]
你好，显示运行中说明执行器回调有问题，确认下执行器回调是否报错，还有回调地址是不是配错了。
任务终止正常的，以为是机器维度的，会将该机器上该任务的队列中和运行中的任务全部终止。
