### ISSUE TITLE
告警提醒是否可以用钉钉

### ISSUE THREAD

**Issue by mylove13289** [xuxueli/xxl-job#475]
Please answer some questions before submitting your issue. Thanks!
告警提醒是否可以用钉钉
### Which version of XXL-JOB do you using?
1.9.1
### Other information

**Comment by wukefang** [comment]
可以

**Comment by leon824** [comment]
觉得这个需求也是挺有用的，相对于邮件报警，处理会更加及时。

**Comment by xuxueli** [comment]
@mylove13289  @wukefang @leon824  
你好，感谢反馈！
默认提供邮件失败告警，可扩展短信、钉钉等，扩展代码位置为 "JobFailMonitorHelper.failAlarm"；
