### ISSUE TITLE
执行器跑着跑着就死了

### ISSUE THREAD

**Issue by grliuxin** [xuxueli/xxl-job#476]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
有bug
### Actual behavior
执行器中报错
### Steps to reproduce the behavior
java.lang.InterruptedException:sleep interrupted
### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现，可以提供复现的条件吗？
可以排查下宕机前后的报错Log，确认下是否存在比较耗资源的任务。

**Comment by grliuxin** [comment]
已经找到原因了，是因为热部署的原因，多谢了

--------------原始邮件--------------
发件人："许雪里 "<notifications@github.com>;
发送时间：2018年9月23日(星期天) 晚上11:46
收件人："xuxueli/xxl-job" <xxl-job@noreply.github.com>;
抄送："grliuxin "<liuxin@gr-data.com>;"Author "<author@noreply.github.com>;
主题：Re: [xuxueli/xxl-job] 执行器跑着跑着就死了 (#476)
-----------------------------------

 
你好，问题无法复现，可以提供复现的条件吗？
 可以排查下宕机前后的报错Log，确认下是否存在比较耗资源的任务。
