### ISSUE TITLE
执行器部署后,调度中心自动检测到了,但是执行任务却一直报连接超时

### ISSUE THREAD

**Issue by chu2179** [xuxueli/xxl-job#477]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.0 版本
### Expected behavior
预期：心跳检测成功，执行任务连接jetty服务地址成功
### Actual behavior
调度中心自动检测到了,但是执行任务却一直报连接超时
### Steps to reproduce the behavior
xxl-job-core项目中JettyServer类中的
server = new Server(new ExecutorThreadPool());  // 非阻塞
改成 server = new Server(); 则不报错
### Other information
两个执行器项目，都是springboot项目，
其中一个执行器项目好着的，
另一个执行器项目是出现这样的问题
多次检查配置都没问题

**Comment by chu2179** [comment]
问题已解决，是执行器版本问题，执行器springboot版本是1.5.13就会出现以上问题；如果是1.5.8则不会出现以上问题；

**Comment by xuxueli** [comment]
赞！推测应该是部分依赖冲突导致。
