### ISSUE TITLE
调用服务器上shell脚本

### ISSUE THREAD

**Issue by wzxit** [xuxueli/xxl-job#479]
执行服务器shell脚本时候，脚本执行完了，但是调度器上一直显示执行中。
如下：
xxl-job: hello shell
脚本位置：/www/webdev/xxljobexecutors/logs/jobhandler/gluesource/35_1529656031000.sh
任务参数：
分片序号 = 0
分片总数 = 1
Good bye!
2018-08-22 08:26:59 [com.xxl.job.core.thread.JobThread#run]-[128]-[Thread-666] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=200, msg=null, content=null]
粗位置一直转圈圈

**Comment by chaiqinghu** [comment]
我也是请问你找到解决方案了吗

**Comment by xuxueli** [comment]
@wzxit @chaiqinghu 你好，看描述应该是执行器回调有问题。可以排查下回调Log，确认回调地址是否配错。
