### ISSUE TITLE
难道所有的执行器必须与调度中心时钟保持一致？

### ISSUE THREAD

**Issue by wangdanqing** [xuxueli/xxl-job#481]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2 snapshot
### Other information

时钟保持一致？而且时区也要一致吗？
既然需要保证时钟一致，为什么不能进行自动同步时钟？
所有执行器自动与调度中心时钟保持同步

**Comment by gstripe** [comment]
我是做了时间同步服务器，即使xxljob允许不一致，但是其他的业务也要保持一致。
所以就弄了台时间同步服务器。网络管理的不给我们弄，我们自己弄，保持自己服务器环境的时间总体一致

**Comment by xuxueli** [comment]
@wangdanqing @gstripe  对的，推荐尽量保证机器事件一致。
