### ISSUE TITLE
job日志查询效率

### ISSUE THREAD

**Issue by gonnalee** [xuxueli/xxl-job#482]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
job log查询快一些
### Actual behavior
job特别多，job触发频率高（1分钟1次），时间稍微一长点日志就会特别多，很容易上百万。日志需要保存一段时间不能删除，此时日志过滤查询效率太低。
### Steps to reproduce the behavior
可否考虑可以在几个关键字段，如：job_group,job_id，触发事件，调度结果等加一些索引。
很多时候我们关注的最近几天的调度日志，在数据库中是排在后面的，100万数据分页时数据在最后效率肯定低，能否考虑倒序，或者其他的针对大数据量时的优化？
### Other information

**Comment by gonnalee** [comment]
我看了下源码，发现是先查询分页数据再select count的，
在查询分页数据时order by id ,花费148ms，而select count时没有倒序排列，数据量大时就很慢，花费3s多。

**Comment by xuxueli** [comment]
你好，这个问题在版本 v1.9.2 （迭代中）已经修复，将会跟随版本近日发布。
