### ISSUE TITLE
glue脚本过长写库报错问题

### ISSUE THREAD

**Issue by guanchaoRen** [xuxueli/xxl-job#484]
`XXL_JOB_QRTZ_TRIGGER_INFO`和`XXL_JOB_QRTZ_TRIGGER_LOGGLUE`表中的`glue_source`字段类型是`text`,当脚本内容过长时，会导致脚本保存失败，建议把该字段类型改为`mediumtext`

**Comment by xuxueli** [comment]
你好，感谢反馈！
相关调整已经推送master分支，将会跟随下个版本一同发布；
