### ISSUE TITLE
xxl-job 和听云同时使用load 飙升到40

### ISSUE THREAD

**Issue by FurionCS** [xuxueli/xxl-job#487]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Actual behavior
部署后线上环境服务器和听云或者arams同时使用 cpu 上涨20%，load 到40 ，圈起来的地方为去除xxl 的时间点，还没有添加任务

![image](https://user-images.githubusercontent.com/16729832/45218281-a2932600-b2d9-11e8-9cf2-6965e402ca40.png)

### Other information

另外：现在群好像都满了，希望能提供一个能加入的群

**Comment by xuxueli** [comment]
你好，问题无法复现，请进一步提供复现步骤条件。
可以前往社区加群交流啊：http://www.xuxueli.com/page/community.html
