### ISSUE TITLE
调度器和执行器部署在同一台机器上，出现“任务管理列表”一直显示处理中

### ISSUE THREAD

**Issue by qujingpeng** [xuxueli/xxl-job#489]
调度器：192.168.21.226   端口号：9097
执行器：192.168.21.226   端口号：9096

调度器配置：
![image](https://user-images.githubusercontent.com/19746824/45259884-29dfb700-b40a-11e8-9f09-5cc11a342ffd.png)

页面一直卡住：
![image](https://user-images.githubusercontent.com/19746824/45259892-3fed7780-b40a-11e8-95f1-98b202e3dafa.png)

**Comment by xuxueli** [comment]
你好，应该是定制的版本。推测时ajax接口报错了，可以debug查看下。
