### ISSUE TITLE
运行一段时间后出现调度备注code：500 msg：java.lang.RuntimeException: Client-error:No route to host (Host unreachable)  手动执行任务正常

### ISSUE THREAD

**Issue by syssss** [xuxueli/xxl-job#491]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，这个问题应该时机器配置问题，可以谷歌下解决方案。

**Comment by NowFlying** [comment]
我们也是遇到了同样的问题，我们部署在云环境里面，执行器有时候会出现No route to host (Host unreachable)，两台服务器可以ping通，两个pod也可以ping通。执行器重新部署，换了一台服务器就好了，搞不清是什么原因？
