### ISSUE TITLE
1.9.1版本，在新增任务时，没有超时时间配置选项

### ISSUE THREAD

**Issue by l36t** [xuxueli/xxl-job#494]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Other information
您好，版本是1.9.1.在新增任务时，没有超时时间配置选项，请问是什么原因呢？

**Comment by xuxueli** [comment]
你好，该特性从 v1.9.2 （迭代中）开始支持，敬请期待。

**Comment by leezshow945** [comment]
> 你好，该特性从 v1.9.2 （迭代中）开始支持，敬请期待。

如果超时设置默认为0，那么会一直等待不会主动结束任务的调度吗
