### ISSUE TITLE
cron支持时区选择吗？

### ISSUE THREAD

**Issue by wangxen** [xuxueli/xxl-job#495]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
cron support zone
### Other information

**Comment by xuxueli** [comment]
你好，目前默认取系统时区 "user.timezone"；

**Comment by liuyl1992** [comment]
> 你好，目前默认取系统时区 "user.timezone"；

默认取系统时间不合理吧。不可能所有业务都在一个时区啊，用户比如设置每周五8点执行的cron表达式转换成UTC 还咋写
