### ISSUE TITLE
配了子任务，没有执行，是什么原因

### ISSUE THREAD

**Issue by canxuewuhua** [xuxueli/xxl-job#501]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Other information

**Comment by canxuewuhua** [comment]
设置父任务的时候，配了一个子任务的ID，跑父任务的时候，子任务没有执行

**Comment by xuxueli** [comment]
你好，父任务运行成功才会触发子任务执行。父任务会在执行备注中记录触发子任务的Log，可以排查下。
