### ISSUE TITLE
favicon.ico 找不到引发 Invalid mime type "text/html;charset=null": unsupported charset 'null'

### ISSUE THREAD

**Issue by bosshe** [xuxueli/xxl-job#508]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2-SNAPSHOT

### Expected behavior
不出现 4XX 异常。
### Actual behavior
页面可以正常操作，只是后台日志偶尔会出现异常。
``` Invalid mime type "text/html;charset=null": unsupported charset 'null' ```

### Steps to reproduce the behavior
在【调度日志】页面点击【执行日志】按钮，再回到原来页面打开其它菜单就会出现该异常。
### Other information
在 common.macro.ftl 文件里把下面这段代码注释起来就正常了。
```
<link rel="icon" href="${request.contextPath}/favicon.ico" />
```

**Comment by xuxueli** [comment]
你好，问题无法复现。可以浏览器请求该 “favicon.ico” 地址确认是否可以加载，也可以在调度中心资源文件中确认是否存在该文件。
