### ISSUE TITLE
使用分片广播遇到的问题（执行器宕机时分片总数无法及时更新）

### ISSUE THREAD

**Issue by wangjwc** [xuxueli/xxl-job#509]
Please answer some questions before submitting your issue. Thanks!
业务场景：
系统有100个用户（来源于用户表）的数据需要处理，5秒处理一次，执行器10个，使用分片方式，按照index和total来分割，每个执行器处理10个用户的数据。
其中1台机器宕机时，在一定时间内（看代码貌似是90秒）该执行器不会从执行器列表里删除，导致任务调度时获取的total仍然等于10，导致有10个用户的数据在该执行器被移出前得不到执行。

### Which version of XXL-JOB do you using?
v1.9.2
### Expected behavior
1、实现多个执行器为1个分片，当分片里的一个执行器调度失败时，可以换其他的重试，尽量避免某个分片得不到执行（JobHandler代码中自己做防重处理）
2、假如某个分片的一组执行器都无法调度成功，则将该分片任务发到其他组里，并删除该组的执行器
ps：临时想的方案，期待更好的解决方式

### Steps to reproduce the behavior
重现：启动两个执行器，注册成功后，kill其中一个
### Other information

**Comment by xuxueli** [comment]
你好，可以降低注册中心的心跳间隔时间，比如提到高3s一次，提高执行器的发现速度可以缓解该问题。
