### ISSUE TITLE
终止任务 停止不彻底

### ISSUE THREAD

**Issue by genghaizhou** [xuxueli/xxl-job#511]
Please answer some questions before submitting your issue. Thanks!
![image](https://user-images.githubusercontent.com/16463776/46188189-35901080-c31a-11e8-86c2-2d850e466127.png)
python 是一个简单的死循环

当我终止任务时
sh 确实被停止了, 但是sh 中调用的python进程并没有被停掉

**Comment by xuxueli** [comment]
你好，脚本任务终止时会自动销毁脚本进程，但是内部开启的子进程时需要手动关闭的。可以通过catch异常处理子进程中断逻辑。
