### ISSUE TITLE
不知道能否支持指定时间执行？

### ISSUE THREAD

**Issue by zuihou** [xuxueli/xxl-job#518]
比如，我有个定时发送邮件功能， 现在10点， 我想定时10点13分发送。

用这个框架方便实现么？
目前想到的方案是： 将10点13转换成Cron， 然后新增一个任务。
有没有直接指定时间执行任务的方法？

**Comment by xuxueli** [comment]
你好，指定固定时间点运行的场景，是典型的延时队列的场景，可以考虑下 XXL-MQ，支持动态设置消息消费事件，自定时重试次数等等。
