### ISSUE TITLE
java.lang.RuntimeException: Network request error: The target server failed to respond

### ISSUE THREAD

**Issue by aooppo** [xuxueli/xxl-job#521]
Please answer some questions before submitting your issue. Thanks!
msg：java.lang.RuntimeException: Network request error: The target server failed to respond

### Which version of XXL-JOB do you using?
v1.9.2
### Actual behavior
client 启动了，并且Jetty 正常启动，自动注册到job admin上了
运行任务实例，控制台报如下:
msg：java.lang.RuntimeException: Network request error: The target server failed to respond

### Steps to reproduce the behavior
client 端使用的tomcat 版本和job admin 的tomcat 版本不一致
例如client 用tomcat8.5.34, job admin 用tomcat 9.0.10
## Other information

**Comment by xuxueli** [comment]
你好，确认下调度 中心与执行器之间网络是不是正常。

**Comment by aooppo** [comment]
> 你好，确认下调度 中心与执行器之间网络是不是正常。

网络是正常的，在一台机器上，也没用docker。

**Comment by xuxueli** [comment]
问题描述不足，无法复现。
