### ISSUE TITLE
xxl-job如何动态创建任务

### ISSUE THREAD

**Issue by Heu1ty** [xuxueli/xxl-job#522]
xxl-job怎么动态创建任务，我使用的是1.9.2的版本。
在自己的业务系统service 创建任务。

有一个场景我们在开发一个规则引擎，需要为在规则创建完成之后开启一个任务作业。
请问该如何实现，具体点谢谢。

**Comment by xuxueli** [comment]
你好，最新版本 v1.9.2 已经提供支持，可以参考文档：http://www.xuxueli.com/xxl-job/#/?id=_5112-%E6%8F%90%E4%BE%9B%E7%BB%99%E4%B8%9A%E5%8A%A1%E7%9A%84api%E6%9C%8D%E5%8A%A1%EF%BC%9A

**Comment by Heu1ty** [comment]
> 你好，最新版本v1.9.2已经提供支持，可以参考文档：[http](http://www.xuxueli.com/xxl-job/#/?id=_5112-%E6%8F%90%E4%BE%9B%E7%BB%99%E4%B8%9A%E5%8A%A1%E7%9A%84api%E6%9C%8D%E5%8A%A1%EF%BC%9A)：//www.xuxueli.com/xxl-job/#/？id = _5112-％E6％8F％90％E4％BE％9％[E7％BB％99％E4％B8％9A％E5％8A％A1％E7％9A％84api％E6％9C％8D％E5％8A％A1％EF％BC％9A](http://www.xuxueli.com/xxl-job/#/?id=_5112-%E6%8F%90%E4%BE%9B%E7%BB%99%E4%B8%9A%E5%8A%A1%E7%9A%84api%E6%9C%8D%E5%8A%A1%EF%BC%9A)

我看了文档，大部分都是通过api去调用的，我想在service 直接调用，我看你的架构图中有rpc，请问怎么使用

**Comment by apa7** [comment]
同问

**Comment by apa7** [comment]
> > 你好，最新版本v1.9.2已经提供支持，可以参考文档：[http](http://www.xuxueli.com/xxl-job/#/?id=_5112-%E6%8F%90%E4%BE%9B%E7%BB%99%E4%B8%9A%E5%8A%A1%E7%9A%84api%E6%9C%8D%E5%8A%A1%EF%BC%9A)：//www.xuxueli.com/xxl-job/#/？id = _5112-％E6％8F％90％E4％BE％9％[E7％BB％99％E4％B8％9A％E5％8A％A1％E7％9A％84api％E6％9C％8D％E5％8A％A1％EF％BC％9A](http://www.xuxueli.com/xxl-job/#/?id=_5112-%E6%8F%90%E4%BE%9B%E7%BB%99%E4%B8%9A%E5%8A%A1%E7%9A%84api%E6%9C%8D%E5%8A%A1%EF%BC%9A)
> 
> 我看了文档，大部分都是通过api去调用的，我想在service 直接调用，我看你的架构图中有rpc，请问怎么使用

你后来有解决吗
