### ISSUE TITLE
执行器是用jetty启动的，是必须要用jetty么？项目导入我们集成框架中包含tomcat，启动到zk注册会导致ip为空，是和tomcat冲突了么？

### ISSUE THREAD

**Issue by shi0907** [xuxueli/xxl-job#527]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，内部并未实用tomcat，应该不会和tomcat冲突。具体问题可以自行分析log或者谷歌啊。
