### ISSUE TITLE
任务只能手动添加吗

### ISSUE THREAD

**Issue by apa7** [xuxueli/xxl-job#528]
现在只找到用/jobinfo/add这个接口来添加了, 而且任务查改都需要任务id来, 
这个在需要自动操作添加/运行/恢复/删除的场景下很麻烦

**Comment by apa7** [comment]
注册中心: 执行器会周期性自动注册任务, 调度中心将会自动发现注册的任务并触发执行。同时，也支持手动录入执行器地址

执行器自动注册任务是通过什么方式  注解吗  文档里面都是手动的方式来的

**Comment by yl-yue** [comment]
同问？
目前想实现诸如：30分钟后取消订单的功能。
需要程序自动化的大量添加定时任务，能通过调用API接口的方式实现么.

**Comment by apa7** [comment]
> 同问？
> 目前想实现诸如：30分钟后取消订单的功能。
> 需要程序自动化的大量添加定时任务，能通过调用API接口的方式实现么.

我现在方案是把这些任务参数放redis里面, 然后这边配定时器去扫

**Comment by yl-yue** [comment]
> > 同问？
> > 目前想实现诸如：30分钟后取消订单的功能。
> > 需要程序自动化的大量添加定时任务，能通过调用API接口的方式实现么.
> 
> 我现在方案是把这些任务参数放redis里面, 然后这边配定时器去扫

看了很多调度框架，发现好像都没有提供像死信队列、过期队列的功能，达到理想的效果。

**Comment by xuxueli** [comment]
@yl-yue @apa7 
1、执行器注册时通过appname心跳注册实现的。
2、类似 30min 超时取消订单的需求，推荐 XXL-MQ，一款分布式消息队列，支持指定时间点延迟消费。
