### ISSUE TITLE
RemoteHttpJobBean是如何被调用的

### ISSUE THREAD

**Issue by gpqhl0071** [xuxueli/xxl-job#532]
请问，源码中，RemoteHttpJobBean是如何被调用的？核心代码在哪里？

**Comment by xuxueli** [comment]
你好，逻辑在quartz包里。

**Comment by gpqhl0071** [comment]
> 你好，逻辑在quartz包里。

admin项目启动后，RemoteHttpJobBean一分钟会被调用一次，这个规则在哪里配置的？

**Comment by gpqhl0071** [comment]
哦 ，我梳理清楚调用逻辑了，以前没用过这种方式，
这里采用了quartz的JDBC作业存储。官方默认提供了几张表，需要我们导入到数据库中，作者对表做了重命名。org.quartz.jobStore.tablePrefix: XXL_JOB_QRTZ_(表前缀)
通过这张表xxl_job_qrtz_job_details，读取我要执行的任务，字段JOB_CLASS_NAME：存储的com.xxl.job.admin.core.jobbean.RemoteHttpJobBean，根据我的时间规则调用。

参考：[http://www.quartz-scheduler.org/documentation/quartz-2.x/migration-guide.html](url)

**Comment by xuxueli** [comment]
👍
