### ISSUE TITLE
关于xxxl-job 1.9.2升级的问题

### ISSUE THREAD

**Issue by idealspark** [xuxueli/xxl-job#533]
我打算从1.91升级到1.9.2,在1.9.2的版本更新日志中看到了,关于数据库字段的修改,但好像并没有提供关于升级的sql脚本,下次版本升级也麻烦提供一下升级文档,使整个开源显得更正规一些

**Comment by xuxueli** [comment]
感谢反馈！
各版本均提供全量建表SQL脚本，可以通过对比建表脚本调整底层库表。
