### ISSUE TITLE
本地搭建伪集群调度中心

### ISSUE THREAD

**Issue by Allen0710** [xuxueli/xxl-job#534]
本地搭建伪集群调度中心：
第二台实例启动时会出现下面的异常，会报-[destroy]-[806]-[INFO] Shutting down Quartz Scheduler
![image](https://user-images.githubusercontent.com/36785050/46795214-2aa69880-cd7c-11e8-850c-352c5e9f70ec.png)

**Comment by xuxueli** [comment]
你好，Log不足，定位不到问题。
