### ISSUE TITLE
PermissionInterceptor.preHandle 重定向路径问题

### ISSUE THREAD

**Issue by bobpan** [xuxueli/xxl-job#54]
response.sendRedirect("/toLogin"); 需要修改为 response.sendRedirect("toLogin");

当使用应用名称的部署时，注销会重定向到http://localhost:11217/toLogin，正确需要到http://localhost:11217/xxl-job/toLogin

**Comment by xuxueli** [comment]
你好感谢关注啊，这个问题master分支已经修复，修改为：response.sendRedirect(request.getContextPath() + "/toLogin"); 解决类似的非根目录下部署的跳转问题；

**Comment by lixue123221** [comment]
刚下载的master分支，编译后，登录到http://localhost/xxl-job-admin/toLogin，输入用户名和密码后，点击登录只是刷新了下登录界面，为啥还是停留在登录界面
