### ISSUE TITLE
调度中心在集群模式下，执行器启动时向调度中心注册时,若任意节点注册失败将导致执行器启动失败

### ISSUE THREAD

**Issue by caoenergy** [xuxueli/xxl-job#544]
老师,你好! 因公司需要后面可能使用xxl-job,但在看代码过程中发现一些问题或疑问,望解答

问题一: 调度中心在集群模式下,执行器启动时向集群中的调度中心节点注册时,若任意节点失败，将会导致执行器启动失败
代码参见: com.xxl.job.core.executor.XxlJobExecutor#initAdminBizList, 在此过程中很有可能因各中各样的原因导致注册失败,但从集群来将则本应允许单点故障,与实际代码体现不符

问题二: 为什么不使用Zookeeper作为注册中心?

**Comment by xuxueli** [comment]
你好：
1、该问题不存在，执行器启动时只是创建ClientProxy，并不会发起注册请求，请求是异步触发的。
2、目前采用自研注册中心，保持系统轻量。不过支持自由扩展。
