### ISSUE TITLE
子任务无法失败重试，自动把失败重试次数设置为0了

### ISSUE THREAD

**Issue by ppr1011** [xuxueli/xxl-job#545]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
子任务失败重试
### Actual behavior
子任务无法失败重试
### Steps to reproduce the behavior
设置两个任务，父任务正常调度执行，让子任务调度失败
### Other information

**Comment by xuxueli** [comment]
你好，该问题已经修复并推送master，可以pull master代码体验下。将会跟随  2.0 版本一同发布。
