### ISSUE TITLE
【自动创建定时调度任务】业务服务器API

### ISSUE THREAD

**Issue by yl-yue** [xuxueli/xxl-job#547]
### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
如：创建订单30分钟后自动取消订单、1天后红包过期等！

涉及大量的定时任务添加与撤销
目前部署服务：xxl-job-admin、xxl-job-executor-sample-springboot
### Actual behavior
查看了文档，发现没有相关的详细说明，感觉很疑惑，无从下手。

![api](https://user-images.githubusercontent.com/39790401/47067923-72ff0400-d21d-11e8-8b31-8e5611a137f2.png)

如：5.11.2 提供给业务的API服务描述

**Comment by ppr1011** [comment]
这个API试了一下一直报错：请选择执行器！ 你们也是这个错误？

**Comment by yl-yue** [comment]
API倒是没问题。执行器选择你注册的就OK了。
但应该没有像死信队列，过期队列这样的功能。无法达到我想要的效果.

**Comment by yl-yue** [comment]
> 这个API试了一下一直报错：请选择执行器！ 你们也是这个错误？

API倒是没问题。执行器选择你注册的就OK了。
但应该没有像死信队列，过期队列这样的功能。无法达到我想要的效果.

**Comment by ppr1011** [comment]
> API倒是没问题。执行器选择你注册的就OK了。
>但应该没有像死信队列，过期队列这样的功能。无法达到我想要的效果.
请问可以提供一下请求的报文数据吗？我试试。。。

**Comment by yl-yue** [comment]
> > API倒是没问题。执行器选择你注册的就OK了。
> > 但应该没有像死信队列，过期队列这样的功能。无法达到我想要的效果.
> > 请问可以提供一下请求的报文数据吗？我试试。。。

目前调度中心已经被我关闭了，我打算采用redis或RabbitMQ实现，如果后续有调度需求会再次集成，听说springboot版本的调度中心也在进程中了。
关于你这个问题，需要注意的一个点，就是调用API需要关闭登录拦截，你注册的项目便是执行器。

**Comment by ppr1011** [comment]
![image](https://user-images.githubusercontent.com/11866257/47127196-b2316180-d2be-11e8-8896-f5501fe4f67d.png)
不知道这个报文有啥错呢？
已经关闭了登录拦截，
@RequestMapping("/add")
	@ResponseBody
	@PermessionLimit(limit = false)
	public ReturnT<String> add(XxlJobInfo jobInfo) {
		return xxlJobService.add(jobInfo);
	}

**Comment by ppr1011** [comment]
@yl-yue 谢谢回复。已经解决问题了，是请求的参数类型问题。

**Comment by gosenme** [comment]
@ppr1011  请问请求参数类型问题，具体是哪个参数什么类型。有成功的json报文吗？ 我也类似以上问题。

我们这边的业务场景是：需要随机指定一些设备，让其在某些指定时间点执行一些命令。

**Comment by xuxueli** [comment]
赞！
不过 “30min 超时取消订单” 这种需求，推荐以MQ的方式实现的。
在此推荐 XXL-MQ，分布式消息队列，支持延迟消费，自定义重试次数等。
