### ISSUE TITLE
调度中心重启后，执行器的任务没有恢复执行（执行器已经注册成功），要暂停再恢复才能执行。

### ISSUE THREAD

**Issue by 120003808** [xuxueli/xxl-job#548]
调度中心重启后，执行器的任务没有恢复执行（执行器已经注册成功），要暂停再恢复才能执行。
![default](https://user-images.githubusercontent.com/12481091/47073189-443b5a80-d22a-11e8-9226-89c646db0416.png)
![default](https://user-images.githubusercontent.com/12481091/47073222-4ef5ef80-d22a-11e8-9b78-f7f6521161a1.png)
![default](https://user-images.githubusercontent.com/12481091/47073291-7cdb3400-d22a-11e8-9e6d-d4d3be42a559.png)

**Comment by xuxueli** [comment]
无法复现，需要进一步提供复现条件
