### ISSUE TITLE
一些改进的建议

### ISSUE THREAD

**Issue by oneal32** [xuxueli/xxl-job#55]
1、可以查看任务的子任务和父任务依赖关系的图。（这个可以参考一下airflow的图）
2、可以做一个任务跑错或者挂了 之后重试的配置。
3、任务之间的依赖触发，可以只配置最后的（叶子节点）任务执行时间，然后子任务进入排队，先把父任务执行完整，依次递归触发。  感觉这样配置触发时间会更加地灵活。
4、可以加入配置任务优先级。

**Comment by xuxueli** [comment]
你好感谢关注哈！
1、任务依赖图，已经放到TODO里面；
2、失败重试策略，在v1.7.2已经实现；
3、子任务先进入队列，这种方式实现起来有风险，如果父任务挂了，需要处理队列中子任务，不太现实；
4、任务优先级已经放到TODO里面了；
再次感谢宝贵建议：）

**Comment by mlinge** [comment]
最近在项目中使用XXL-JOB，非常好，但有两个小的点觉得要是能有的话就更加完美了：
1、XxlJobLogger的日志多参数支持
2、任务多了的时候，无法记住每个任务具体做什么的，能为任务设定备注信息就好了

**Comment by xuxueli** [comment]
感谢信任和关注啊：）
针对上面两个建议，说明如下啊：
1、XxlJobLogger多参数支持这个确实很有必要，已经加入到TODO LIST中了；
2、“任务描述” 现在已经支持录入，新建或编辑任务时，可以自由指定的；
感谢宝贵建议：）

**Comment by RalfJones** [comment]
能不能支持指定机器执行？
