### ISSUE TITLE
提供docker-compose编排支持

### ISSUE THREAD

**Issue by weiwunb** [xuxueli/xxl-job#550]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v1.9.2
### Expected behavior
新增docker-compose编排支持
### Actual behavior
1. 为xxl-job定制一个mysql基础镜像，容器启动时自动生成16张表
2. 出版本时，提供版本镜像: job-admin, job-executors-samples等
3. 提供compose编排文件
### Steps to reproduce the behavior
N/A
### Other information
我已经对这些工作做了一个版本，包括: mysql基础镜像和compose编排文件，请问如何贡献？

**Comment by weiwunb** [comment]
# docker build -t xxl-job-mysql:v1.9.2 .
# Derived from official mysql image (our base image)

FROM mysql:5.6
# Add a database
ENV MYSQL_DATABASE xxl-job
ENV MYSQL_ROOT_PASSWORD xxl-job@root_pwd

# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./doc/db/tables_xxl_job.sql /docker-entrypoint-initdb.d/

**Comment by minliacom** [comment]
先fork项目
然后提交pull request即可
