### ISSUE TITLE
有办法集群内保证串行吗

### ISSUE THREAD

**Issue by evancyz** [xuxueli/xxl-job#561]
雪大大你好，现在看起来，阻塞策略是针对单机的。
我们现在遇到的场景其实是，一个每30分钟跑的Job，要执行40分钟，然后导致两台机器串行，产生并发。
我们现在的临时处理是 用您的一致性HASH + 单机运行时丢弃 
有什么办法保证在集群内同时只有一个Job在跑吗

**Comment by xuxueli** [comment]
你好，你们现在的做法就是推荐方案：单机路由策略（一致性HASH，第一台等） + 阻塞策略（单机串行）。

**Comment by evancyz** [comment]
行吧 看来暂时只有这样了 不过这样就有点low了。。。
