### ISSUE TITLE
自动注册Ip获取不准确

### ISSUE THREAD

**Issue by leolird** [xuxueli/xxl-job#564]
webserver-192.168.126.101(真正执行任务的server)和job server-192.168.126.102分别在同一局域网中的两台计算机上，
job server跑在docker环境中，并暴露9000端口给局域网，
web server在非docker环境中(注意web server所在计算机中安装有docker服务，但是并未在docker container中运行该web server)，web server连接job所用地址为192.168.126.102:9000, 这时发现job自动注册获取到的ip是172.17.0.1:9999 , why ？？？？ 为啥不是192.168.126.101:9999 ？
这导致执行任务失败信息如下：
触发调度：
address：172.17.0.1:9999
code：500
msg：java.lang.RuntimeException: Network request error: Connect to 172.17.0.1:9999 [/172.17.0.1] failed: Connection refused (Connection refused)

**Comment by xuxueli** [comment]
你好，机器存在多网卡情况下会导致获取IP不准，此时支持手动执行IP。
迭代中的 2.0.0 对IP获取方式进行了优化，可参考下。

**Comment by leolird** [comment]
@xuxueli 好的，感谢回复

**Comment by magang0425** [comment]
这个现在怎么处理的呢？

**Comment by leolird** [comment]
> @leolird 这个现在怎么处理的呢？

改用手动注册ip

**Comment by Edgar3399** [comment]
你好，docker启动执行器时，日志返回
![image](https://user-images.githubusercontent.com/25998322/58469691-90605d00-8172-11e9-8ce7-20fd05181732.png)

不使用docker正常，怎解
