### ISSUE TITLE
ReturnT 类型增强

### ISSUE THREAD

**Issue by asanghehe** [xuxueli/xxl-job#567]
### 扩增ReturnT类型的子类，框架上识别增强的ReturnT类型，处理返回来的调度的策略的微调

**Comment by xuxueli** [comment]
你好，ReturnT 是我设计实用的一个经典响应数据结构，几乎可以承担任意逻辑数据结构。

针对你的需求，不需要修改代码，你可以通过扩展状态码 code 枚举来实现，比如 300 表示放弃一定周期的调度等。

具体逻辑可以自行定制。
