### ISSUE TITLE
spring boot版本的admin没有spring-boot-maven-plugin

### ISSUE THREAD

**Issue by xiaochunping** [xuxueli/xxl-job#569]
1.9.2版本中admin已经改为spring boot了，同时加入了docker的支持。但是使用maven package打包后，java -jar xxl-job-admin.jar会报错：xxl-job-admin-2.0.0-SNAPSHOT.jar中没有主清单属性；原因是没有添加spring-boot-maven-plugin，在spirng boot的示例代码中又添加，希望作者在admin中也添加下。谢谢！

**Comment by grainrain** [comment]
等待作者的回答,还是在这边找到了答案,谢谢

**Comment by xuxueli** [comment]
你好，2.0 仍然在迭代中，可以等待发布后体验。推荐实用release版本；
