### ISSUE TITLE
jobinfo.index.1.js中button job_operate在IE11下type值全部变成了submit，导致功能失效

### ISSUE THREAD

**Issue by bobpan** [xuxueli/xxl-job#57]
RT

**Comment by xuxueli** [comment]
你好，调度中心采用bootstrap3，推荐使用chrome系浏览器啊！
（刚刚我对 “button job_operate” 做了些小的调整，不清楚是否支持IE11，可以pull一下master分支代码测试下）

**Comment by bobpan** [comment]
@xuxueli 神速，呵呵，几天不见，1.7.0了，大大的赞
我之前做了调整，将type改为name，可以修复IE 11的问题，看代码的是改为了_type，应该是没有问题了，谢谢

另发现一个小问题，新开一个Issue
