### ISSUE TITLE
您好,请教一个实现方式

### ISSUE THREAD

**Issue by javaylh** [xuxueli/xxl-job#570]
如果有十个任务，它们的数据库连接，用户名，密码参数都是一样的，只是表名这个参数不一样，之后如果连接，用户名，密码值变了，那是不是只能一个一个的去修改任务？或是有其他实现的方法

**Comment by daiing** [comment]
用bean模式，自己调用代码里写

**Comment by xuxueli** [comment]
可以把公共的部分封装起来，变动的时候只需要修改一次。
