### ISSUE TITLE
调度中心执行任务时，调度失败：执行器地址为空

### ISSUE THREAD

**Issue by shi0907** [xuxueli/xxl-job#572]
当我选择自动录入是提示执行器地址为空，当我指定执行器地址时，500错误，错误信息：msg：java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null

**Comment by xuxueli** [comment]
执行器地址说明执行器还没有注册成功，任务注册由短暂延迟可以稍等下。
上述错误时请求没响应，确认下执行器地址或端口是不是配置，默认端口9999；

**Comment by ashuai5061** [comment]
我下载的2.4.1版本,还是一样,官方的demo就报这个
