### ISSUE TITLE
任务的pause，kill，恢复等操作没有效果

### ISSUE THREAD

**Issue by caihuaxue** [xuxueli/xxl-job#574]
在实际测试中，测试了手动执行任务，执行一半的时候暂停，然后恢复；或者执行一半的时候，把任务杀死。但是没有效果，日志还是照样打印任务执行完成。
后来分析了下源码，源码对任务的这些操作都是调度quartz的api，这说明quartz本身还没有解决掉这些问题。有些任务是需要开启独立的进程去执行的，这个时候其实任务已经摆脱了quartz的束缚了。
有没有好的办法可以解决这些问题，操作系统底层支持对进程暂停么？

**Comment by xuxueli** [comment]
任务的暂停、恢复针对的触发功能，已经触发的任务并不会受影响。如果需要终止已经触发的任务，可以到任务日志列表点击 “终止任务” 来终止任务。
