### ISSUE TITLE
mvn 打包后的jar 无法启动 

### ISSUE THREAD

**Issue by grainrain** [xuxueli/xxl-job#576]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0-SNAPSHOT    jdk：1.8
### 反馈：xxl-job-admin-2.0.0-SNAPSHOT.jar中没有主清单属性

**Comment by xuxueli** [comment]
你好，2.0 仍然在迭代中，可以等待发布后体验。推荐实用release版本；
