### ISSUE TITLE
调度控制台无法查看执行日志

### ISSUE THREAD

**Issue by sukkiCat** [xuxueli/xxl-job#578]
所有任务的执行日志都会一直loading，最后报“终止请求Rolling日志,请求失败次数超上限,可刷新页面重新加载日志”
### Which version of XXL-JOB do you using?
1.9.1

### Expected behavior
![image](https://user-images.githubusercontent.com/30313245/47960320-5263e600-e034-11e8-83a8-b0f86f56b5a9.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/30313245/47960323-64458900-e034-11e8-8b41-1d5c6c802863.png)

**Comment by xuxueli** [comment]
任务没有回调导致的，排查下回调地址是不是配错。

**Comment by sukkiCat** [comment]
> 任务没有回调导致的，排查下回调地址是不是配错。

能看到执行状态回调成功的日志 但是看不到日志回调的日志 也没有报错
![image](https://user-images.githubusercontent.com/30313245/48062562-63138800-e1fd-11e8-961f-a327b383218d.png)

**Comment by xuxueli** [comment]
本地无法复现。

可以在执行器测远程debug下试试，日志加载异常。
