### ISSUE TITLE
希望增加主任务 参数|结果 传递功能

### ISSUE THREAD

**Issue by xiaochunping** [xuxueli/xxl-job#579]
因为有了子任务这个功能后，确实方便了很多。
但是有时候会有这样的需求：主任务带了参数，在主任务执行完后执行子任务的时候需要把主任务的参数传递给子任务。或者是说主任务的执行结果需要传递给子任务。这个需求确实很实用也很常见，希望大佬在新版本中考虑增加。谢谢。。。

**Comment by shubending** [comment]
这个需求确实很必要  现在实现类似的就是一个任务触发另一个任务trigger方法的时候把参数带过去 不过这样在java代码中发送请求很耗时

**Comment by xuxueli** [comment]
DAG流程任务，合并至：https://github.com/xuxueli/xxl-job/issues/172
