### ISSUE TITLE
2.0.0-SNAPSHOT版本中[执行器]不能自动注册发现

### ISSUE THREAD

**Issue by grainrain** [xuxueli/xxl-job#580]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0-SNAPSHOT
### Expected behavior
不知道作者有没在发布版本后做测试 2.0.0-SNAPSHOT执行器是不能自动注册发现的
 回退到1.9.2版本后，能够自动注册

**Comment by caoyunshi** [comment]
执行器是按照appname去扫描的。所以exec那边的执行器如果改了appname，需要先在admin的执行器里 增加执行器name

**Comment by caoyunshi** [comment]
> > 执行器是按照appname去扫描的。所以exec那边的执行器如果改了appname，需要先在admin的执行器里 增加执行器name
> 
> 你说的我都了解，从1.8.2就开始使用了，2.0.0-SNAPSHOT 在第一次通过appname就无法注册的问题

那就不知道了哎，等作者看一下你的问题，我升级了2.0.0-SNAPSHOT，没有问题的。

**Comment by shi0907** [comment]
请问下，admin中appname去哪里增加执行器name

**Comment by caoyunshi** [comment]
> 请问下，admin中appname去哪里增加执行器name

执行器管理，新增执行器：
AppName* 的内容 必须与 执行器代码中 application.properties文件xxl.job.executor.appname= 属性指定的一致。

**Comment by xuxueli** [comment]
@grainrain 建议用 Release 版本。确保调度中心与执行器通讯没问题。

**Comment by grainrain** [comment]
> @grainrain 建议用 Release 版本。确保调度中心与执行器通讯没问题。

好的，生产环境回退到了1.9.2 ，已经没问题了。希望2.0.X版本能能够尽快稳定

**Comment by jovi521** [comment]
终于发现问题了，如果注册的应用没有启动，那么job会一直注册不起，也许这是作者避免资源浪费的优化方案，把我坑了一下午，我以为job出问题了。最终我启动了我的那个应用，一下子注册起了。
![image](https://user-images.githubusercontent.com/25958206/88608815-354b3280-d0b5-11ea-97a5-e5aaaa43c7d0.png)
