### ISSUE TITLE
2.0版 admin 使用了spring-boot。pom.xml需要自己增加build插件。

### ISSUE THREAD

**Issue by caoyunshi** [xuxueli/xxl-job#582]
2.0版 admin 使用了spring-boot。
需要在pom.xml增加打包语句，才能打包 可执行jar包。
<-build>
        <-plugins>
            <-plugin>
                <-groupId>org.springframework.boot</groupId>
                <-artifactId>spring-boot-maven-plugin</artifactId>
                <-version>${spring-boot.version}</version>
                <-executions>
                    <-execution>
                        <-goals>
                            <-goal>repackage</goal>
                        <-/goals>
                    <-/execution>
                <-/executions>
            <-/plugin>
        <-/plugins>
    <-/build>

**Comment by xuxueli** [comment]
你好，release版本插件已经存在，可以参考下。
