### ISSUE TITLE
HttpJobHandler.java 对HTTPS地址没有做处理。可以忽略证书错误，继续执行。

### ISSUE THREAD

**Issue by caoyunshi** [xuxueli/xxl-job#583]
ContentResponse response = request.send();这一句会报错SSL

简单一点 就把https 转为http
                  // ignoreSsl
			String[] arr = param.split("://");
			String protocol = arr[0].toLowerCase();
			if( "https".equals(protocol) ){
				//SslUtils.ignoreSsl();
				param="http://" + arr[1];
			}

**Comment by xuxueli** [comment]
你好，默认针对 “IP:PORT” 格式会补充 "http://" 前缀，这种方式是支持 https 调用的。
针对https地址格式，可以在业务设置请求地址时手动处理的。
