### ISSUE TITLE
2.0.1 左侧菜单的缩回和展开，有问题。

### ISSUE THREAD

**Issue by caoyunshi** [xuxueli/xxl-job#584]
临时处理：common.1.js
// left menu status v: js + server + cookie
	$('.sidebar-toggle').click(function(){
		var xxljob_adminlte_settings = $.cookie('xxljob_adminlte_settings');	// on=open，off=close
		if ('off' == xxljob_adminlte_settings) {
            xxljob_adminlte_settings = 'on';
            $('body').removeClass('sidebar-collapse');
		} else {
            xxljob_adminlte_settings = 'off';
            $('body').addClass('sidebar-collapse');		}
		$.cookie('xxljob_adminlte_settings', xxljob_adminlte_settings, { expires: 7 });	//$.cookie('the_cookie', '', { expires: -1 });
		
		return false;
	});

不知道作者是怎么动态加的样式（2.0.0是OK的，2.0.1有问题）

**Comment by xuxueli** [comment]
你好，这是升级adminlte过程中的一个遗留问题。master分支已经修复，将会跟随下个版本一同发布。

修复commit：https://github.com/xuxueli/xxl-job/commit/2e2777573223ccecc650bda4dc0cd14d06835286

**Comment by xuxueli** [comment]
已经发布新版本修复这个问题，可以从 v2.0.0 直接覆盖更新：https://github.com/xuxueli/xxl-job/releases/tag/v2.0.1
