### ISSUE TITLE
任务管理，执行器列表，建议增加全部。

### ISSUE THREAD

**Issue by caoyunshi** [xuxueli/xxl-job#587]
后端代码都是支持的，前端ftl增加option即可。
jobinfo.index.ftl: line27-37

<--div class="row">
	    		<--div class="col-xs-3">
	              	<--div class="input-group">
	                	<--span class="input-group-addon">${I18n.jobinfo_field_jobgroup}</span>
                		<--select class="form-control" id="jobGroup" >
                            
                            <--option value="0" <#if jobGroup==0>selected</#if> >${I18n.system_all}</option>
                			<--#list JobGroupList as group>
                				<--option value="${group.id}" <#if jobGroup==group.id>selected</#if> >${group.title}</option>
                			<--/#list>
	                  	<--/select>
	              	<--/div>
	            <--/div>

**Comment by xuxueli** [comment]
你好，后期排期基于执行器做权限控制，“全部” 一列不方便进行权限隔离，暂时不打算开放改选项。
