### ISSUE TITLE
IE can not login

### ISSUE THREAD

**Issue by changjunjie** [xuxueli/xxl-job#588]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB v2.0.0，分布式任务调度平台
### Expected behavior
IE can not login

**Comment by caoyunshi** [comment]
The ‘front end’  uses CSS3,
Below IE8 bad compatibility.

**Comment by xuxueli** [comment]
建议 chrome、firefox 或 edge。
