### ISSUE TITLE
调度策略疑问？

### ISSUE THREAD

**Issue by lhaiq** [xuxueli/xxl-job#589]
我想了解下，
1.我是手动注册的，用的忙碌转移策略，但是感觉所有的任务都压倒前几台机器了，后面的都没有分配到。这是什么原因呢？
2.假如用轮询，想知道这个轮询的范围，是本任务内轮询还是调度器轮询

**Comment by caoyunshi** [comment]
调度器只能指定1个，轮循指的是 本任务在调度器内Ip轮循。 1个调度器组 可以有多个exec终端。

例如：

排序 | AppName                   | 名称      | 注册方式 | OnLine 机器地址                                        | 操作
1 | xxl-job-executor-sample | 执行器1 | 自动注册 | 192.168.0.132:20003 192.168.0.132:20005

**Comment by xuxueli** [comment]
你好。
1、压倒前几台，说明消费速度快，具体看策略说明；
2、任务所绑定执行器机器内轮训。

**Comment by lhaiq** [comment]
好的，，谢谢
