### ISSUE TITLE
关于任务的创建

### ISSUE THREAD

**Issue by bin272** [xuxueli/xxl-job#59]
目前xxl-job支持web页面对任务进行CRUD操作。但是没有api的方式。能否开放一个api接口来增加任务？我测试过xxl-job-admin/jobinfo/add   这个方法模拟表单请求、但是需要登录验证。

**Comment by xuxueli** [comment]
你好，不推荐通过API方式操作任务，还是推荐通过界面方式操作任务啊。
但是，v1.7.2调度中心已经提供了API服务，如果确实需要通过API调用，可以参考该版本API服务自定定制。
：）

**Comment by bin272** [comment]
如您说所。 不推荐通过api 的方式操作任务的原因是什么？    
1.7.2提供的API服务有哪些功能？我没有找到关于该版本API服务自定定制。能指点一下吗？

谢谢！

**Comment by xuxueli** [comment]
API服务可以参考，暂时没有暴露仅开放为执行器底层使用：com.xxl.job.admin.controller.JobApiController

**Comment by wzshuang** [comment]
@xuxueli 
我也想问不推荐通过api方式操作任务的原因是什么。
有个需求，需要根据用户的操作来创建或删除任务，并且任务的执行时间也不尽相同，请问通过xxl-job应该怎样实现呢？

**Comment by xuxueli** [comment]
@wzshuang 通过api操作任务已经加入到TODO，将会在后续版本迭代发布。
