### ISSUE TITLE
调度器调度的时候，首次执行成功，后边就执行失败了

### ISSUE THREAD

**Issue by zenghuabin** [xuxueli/xxl-job#591]
![image](https://user-images.githubusercontent.com/33113832/48050394-b9bc9a00-e1dc-11e8-8a95-f7e9fbb4a24f.png)

**Comment by ZuiSong** [comment]
#586   应该就是这个问题

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/586

**Comment by ioiioo** [comment]
#586 我今天下午也遇到了同样的问题，见我的回复，可以解决问题，但具体的问题原因还需要再确认。
