### ISSUE TITLE
获取本机IP不准确问题及解决思路

### ISSUE THREAD

**Issue by ioiioo** [xuxueli/xxl-job#595]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
```
<dependency>
<groupId>com.xuxueli</groupId>
<artifactId>xxl-job-core</artifactId>
<version>2.0.0</version>
</dependency>
```

### Actual behavior
获取本机IP不准确问题, 本机上面装有虚拟机或是多个网卡，获取的IP并不是十分准确，例如：
![image](https://user-images.githubusercontent.com/26021227/48061596-7bce6e80-e1fa-11e8-9b0a-3ee4187a4eeb.png)

例如：我机器上面有三个网卡，每次获取到的IP地址是：`192.168.119.1` 而这个是我虚拟机网卡的IP，我希望获取的IP是 `10.168.1.50`  为什么会是这样的呢? 因为我本地网卡接口的序号是：
![snipaste_2018-11-06_19-35-11](https://user-images.githubusercontent.com/26021227/48061812-162eb200-e1fb-11e8-9e57-fd3ec18fe7ba.png)

名为LAN-001的网卡ifIndex值靠后，而代码里面获取IP的方法如下（debug图）：
![snipaste_2018-11-06_19-39-51](https://user-images.githubusercontent.com/26021227/48062050-d3b9a500-e1fb-11e8-8853-2e1872d34005.png)

从上图可以看到，这一块是源码按顺序从 网卡接口面里取出了，不符合`isValidAddress()` 这个方法里面的条件的IP，可是这并非是网卡真正的IP，当然实际线上服务器没有这复杂。但万一有了,获取IP不准确，在使用自动发现执行器节点的功能就会有误，最终会影响到任务执行。
当然我是Windows机器，由于在win机器根本无法 修改网卡接口的`ifIndex`
请参见：
 [无法修改网卡接口ifIndex的例子1--Changing the ifIndex for Network Adapter](https://social.technet.microsoft.com/Forums/en-US/44607844-2390-4746-b922-e23c71810fa2/changing-the-ifindex-for-network-adapter?forum=win10itpronetworking)
 [无法修改网卡接口ifIndex的例2--Adjusting the Network Protocol Bindings in Windows 10](https://blogs.technet.microsoft.com/networking/2015/08/14/adjusting-the-network-protocol-bindings-in-windows-10/)
 [无法修改网卡接口ifIndex的例子3--Set-NetIPInterface powershell change -interfaceindex to another number](https://www.experts-exchange.com/questions/29079816/Set-NetIPInterface-powershell-change-interfaceindex-to-another-number.html)

从上面三个案例发现在win下面真心无法修改网络接口的index,所以按现源码实现，很有可能在win机器上面获取IP不准确，但在linux上面另说，必竟liunx上修改网卡相关信息soeasy

### Other information

期待参考：以下链接具体JAVA实现，来获取真实的IP地址：
[java在windows上获取网卡的mac地址](https://blog.csdn.net/u010366748/article/details/77572301)
[Java API研究：获取本地环境所有网卡及每个网卡的所有网络配置](http://www.cnblogs.com/guangshan/p/4712550.html)

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/191
