### ISSUE TITLE
xxl-job-admin部署问题

### ISSUE THREAD

**Issue by zsf513** [xuxueli/xxl-job#597]
希望将xxl-job-admin发布成一个release版的压缩包，里面包含启动、停止脚本、配置文件等，部署时直接修改一些配置，即可方便运行。当前部署不便之处在于需要将源码下载下来编译打包。

**Comment by coolyujiyu** [comment]
docker 版本不就适合你使用啦

**Comment by xuxueli** [comment]
是的，建议使用docker版本，一行命令即可启动。
