### ISSUE TITLE
建议调度日志列表加上执行时长列、和任务名称列，并且支持按照执行时长排序

### ISSUE THREAD

**Issue by jiming** [xuxueli/xxl-job#599]
Please answer some questions before submitting your issue. Thanks!
任务的执行时长很重要，很多时候 job 服务器负载高需要快速定位是哪个 job 造成的，如果列表页加上执行时长，那么就可以更快的定位的问题 job
### Which version of XXL-JOB do you using?
2.0.0

### Expected behavior
![image](https://user-images.githubusercontent.com/455978/48112698-981dea00-e292-11e8-9545-9fbdbfd654e8.png)

### Other information

**Comment by xuxueli** [comment]
你好，已经加入TODO列表，将会排期跟进。
