### ISSUE TITLE
日期分布图能否再加个按照小时的分布图，如果只提供日期粒度的话有点粗

### ISSUE THREAD

**Issue by jiming** [xuxueli/xxl-job#600]
Please answer some questions before submitting your issue. Thanks!

### Actual behavior
![image](https://user-images.githubusercontent.com/455978/48113006-e2ec3180-e293-11e8-85b4-034123e42c41.png)

### Other information

**Comment by xuxueli** [comment]
你好，日期分布以天为未读的，进一步细分可以自行定制添加一张新报表。
