### ISSUE TITLE
'com.xxl.job.core.rpc.codec.RpcRequest' is an unknown class in TomcatEmbeddedWebappClassLoader

### ISSUE THREAD

**Issue by sukkiCat** [xuxueli/xxl-job#603]
升级到1.9.2版本执行任务就会报如下错误

'com.xxl.job.core.rpc.codec.RpcRequest' is an unknown class in TomcatEmbeddedWebappClassLoader

**Comment by xuxueli** [comment]
你好，应该是有些类没引入，可以查看下依赖数，确认core中依赖全部引入并且版本一致。
