### ISSUE TITLE
LRU路由更新问题

### ISSUE THREAD

**Issue by walyuuc** [xuxueli/xxl-job#609]
执行器实例1启动，在online机器能看到ip1，
执行器实例1关闭，在online机器，空
执行器实例2启动，在online机器能看到ip2（仅ip2，因为此时实例1已关闭）
当路由使用LRU时，还是有时会调度到ip1，导致调度失败
是LRU内存没更新么？

**Comment by walyuuc** [comment]
2.0.2版本

**Comment by xuxueli** [comment]
你好，感谢反馈！
问题已修复，即将推送master分支，将会跟随下个版本一同修复。
