### ISSUE TITLE
1.9 版本中 在一次任务执行过程中失败，返回错误信息是：业务运行中，被强制终止

### ISSUE THREAD

**Issue by ruyuhi** [xuxueli/xxl-job#613]
一个任务调度返回结果是：业务运行中，被强制终止   ，如下图，任务配置为单机串行。执行时间为每2分钟一次，但是在同一个时间点：2018-11-13 16:54:00 ，任务有两条执行日志，一条成功，一条失败。

![image](https://user-images.githubusercontent.com/20806597/48404328-f3584c80-e76a-11e8-8993-5d5134fc7c37.png)

![image](https://user-images.githubusercontent.com/20806597/48404378-079c4980-e76b-11e8-84fb-e691ea063411.png)

**Comment by xuxueli** [comment]
重复触发合并至：https://github.com/xuxueli/xxl-job/issues/370
