### ISSUE TITLE
bug 无法查看日志

### ISSUE THREAD

**Issue by wuchangrice** [xuxueli/xxl-job#614]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0
### Expected behavior
问题表现
/xxl-job-admin/joblog/logDetailPage?id=4688不展示日志
问题原因
/xxl-job-admin/joblog/logDetailCat 接口中参数logId:4,688转int会失败
### Other information

**Comment by jia82** [comment]
logId大于1000就有这个问题，JobLogController -> logDetailPage中的model.addAttribute("logId", jobLog.getId()); 返回到前端变成'1,000'格式，再转int出错

**Comment by xuxueli** [comment]
请升级 2.0.1，问题已修复。

**Comment by chf-gh** [comment]
> 请升级 2.0.1，问题已修复。

我用的2.0.1,页面还是会出现这个问题呀。大于1000的logId会自动添加逗号。导致查看不到日志
