### ISSUE TITLE
关于系统扩展的事

### ISSUE THREAD

**Issue by caojipian** [xuxueli/xxl-job#615]
下面这段直接读取注解的方式是否可参考spring注解派生性的方式解析，这样可以提升一些扩展性，如公司架构师可以根据它进行一个扩展，不需要使用原生的@JobHandler注解进行开发，我正在使用您的调度系统，这是在再次封装中提供的一个建议，希望采纳

// init job handler action
        Map<String, Object> serviceBeanMap = applicationContext.getBeansWithAnnotation(JobHandler.class);

        if (serviceBeanMap!=null && serviceBeanMap.size()>0) {
            for (Object serviceBean : serviceBeanMap.values()) {
                if (serviceBean instanceof IJobHandler){
                    String name = serviceBean.getClass().getAnnotation(JobHandler.class).value();
                    IJobHandler handler = (IJobHandler) serviceBean;
                    if (loadJobHandler(name) != null) {
                        throw new RuntimeException("xxl-job jobhandler naming conflicts.");
                    }
                    registJobHandler(name, handler);
                }
            }
        }

**Comment by xuxueli** [comment]
你好，系统扩展可以借助任务组件组件手动注册。先扫描自定义注解任务，然后注册即可。
```
XxlJobExecutor.registJobHandler("demoJobHandler", new DemoJobHandler());
```
