### ISSUE TITLE
admin到executor通讯能不能借助存在的web接口，而不是再引入一个jetty容器

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#620]
博主您好：admin到executor通讯是引入了jetty容器通过http请求来处理，一般executor运行在springboot里面，springboot已经有一个tomcat容器了，这样就会造成executor端存在2个web容器，能不能再配置里面配置交互的接口地址和协议，让executor来实现。从而去除jetty容器的依赖呢？

**Comment by beykery** [comment]
我想问下，别的语言怎么注册成执行器？被admin调度？

**Comment by RoonyLi** [comment]
xxl-job默认是jetty，除非替换你初始化的代码，没有灵活设置的方式。可以考虑默认使用netty，或者判断有哪个依赖用哪个。

**Comment by walyuuc** [comment]
@beykery 别的语言貌似还不能注册成执行器，但可以了解下GLUE

**Comment by farsunset** [comment]
我看了xxl-rpc文档 无法替换，会有端口冲突

**Comment by mail6562** [comment]
通信还是要用jetty，我改了别的服务，就不稳定 了，版本，协议不兼容

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/35
