### ISSUE TITLE
关于返回结果的疑问

### ISSUE THREAD

**Issue by ruanxingshi** [xuxueli/xxl-job#621]
当我们通过xxl-admin触发任务时，我们都是直接返回结果。那要是执行过程中报错了，xxl-admin哪里可以看到相关信息呢？

**Comment by walyuuc** [comment]
未捕获的异常，框架会处理，上报，可以在admin调度日志中看到异常堆栈信息
如果job捕获了异常，就是ReturnT的内容

**Comment by walyuuc** [comment]
quartz触发任务后，放到线程池里，线程执行下发任务，下发成功后就完事了，不阻塞等待任务执行结果。本地收到任务后，执行任务，执行完成后，结果上报admin

**Comment by xuxueli** [comment]
@walyuuc 正解。
