### ISSUE TITLE
执行器springboot升级到了2.1.0，导致jobHandler没有被注册到调度器

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#623]
执行器springboot升级到了2.1.0，导致jobHandler没有被注册到调度器
请问这个大概是什么原因呢
admin端执行的时候报 jobHandler not found

**Comment by sunhao91** [comment]
看demo，demo有变化

**Comment by farsunset** [comment]
就是按照demo里面做的之前1.5.9版本都可以升级到了2.1.0 就无法上报handler到了admin，还有没有其他地方需要注意的

**Comment by farsunset** [comment]
问题找到了  是没有使用XxlJobSpringExecutor
