### ISSUE TITLE
springboot集成xxl-job后, 启动进程一阵时间后端口自动失效的问题

### ISSUE THREAD

**Issue by Yanxinwei** [xuxueli/xxl-job#624]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job版本:1.8.1;
spring-boot版本:2.0.5.RELEASE
### Expected behavior
应用启动后,可以通过xxl-job-admin页面启手动启动定时任务
### Actual behavior
应用启动几秒钟后,开给xxl进行任务调度的端口被释放,通过xxl-job-admin页面启手动启动定时任务显示调用失败
### Steps to reproduce the behavior
1.新建一个最简单的springboot应用,版本使用2.0.5.RELEASE, 接入xxl-job版本1.8.1;
2.新增一个定时任务, 以bean的方式实现;
3.启动应用;
4.通过xxl-admin查看任务可调用的实例及端口,发现注册无问题;
5.手动启动一次2中的定时任务;
6.提示启动失败.
### Other information
给应用接入spring-boot-starter-actuator(版本2.1.0.RELEASE)后,查看显示bean已经注入,但是本该被占用的端口被释放

**Comment by LuTongT** [comment]
[jetty版本问题](https://github.com/xuxueli/xxl-job/issues/586)

**Comment by Yanxinwei** [comment]
> [jetty版本问题](https://github.com/xuxueli/xxl-job/issues/586)

按照要求加上jetty依赖后, 问题解决.
