### ISSUE TITLE
1.9.0版本能无缝升级到2.0.1吗

### ISSUE THREAD

**Issue by gonnalee** [xuxueli/xxl-job#626]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
生产环节升级到2.0.1，希望无缝升级
### Other information

**Comment by xuxueli** [comment]
你好，1.9.x 到 2.x 属于大版本升级，数据库有调整，需要一小段停机升级时间的啊。
可以对比两个版本建表SQL调整DB获取增量脚本。

**Comment by gonnalee** [comment]
已经成功升级，使用两周未发现问题。是否考虑以后如果可以兼容性升级的话可以把增量脚本提供出来？
