### ISSUE TITLE
建议日志列表显示任务描述

### ISSUE THREAD

**Issue by ileeoyo** [xuxueli/xxl-job#629]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
1，建议日志列表显示任务描述，大量job，日志列表只显示任务id，发现有调度失败的日志，只有id很难一眼看出是哪个任务报错了。建议显示任务描述
2，日志列表建议把筛选参数放到url中，就算刷新页面，也能保留筛选参数
3，建议增加任务分组功能。微服务大量job都是单个项目执行器。建议增加分组，比如：运维job，业务job分组，等等
### Actual behavior
目前版本未有该功能
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/599

任务日志建议通过新增执行器隔离。不同执行器可以复用AppKey的。

**Comment by xinhaiCai** [comment]
任务描述和编辑任务保存后自动刷新跳回首页我通过稍微修改了前端的js自己解决了，比较影响体验
