### ISSUE TITLE
在写executor的时候怎么方便的进行本地调试呢？

### ISSUE THREAD

**Issue by dnfhujun** [xuxueli/xxl-job#63]
目前只能通过发布代码，在调度后台执行来测试业务的代码对不对，非常不方便，请问有什么快捷的本地调试executor的方式呢？

**Comment by xuxueli** [comment]
你好，执行器开发的时候进行任务逻辑测试，确实很重要。
我写了一个任务测试的示例，已经推送到master分支了，可以参考一下啊。
代码位置：https://github.com/xuxueli/xxl-job/blob/master/xxl-job-executor-example/src/test/java/com/xxl/executor/test/DemoJobHandlerTest.java

**Comment by dnfhujun** [comment]
感谢大神！！
