### ISSUE TITLE
执行器部署到容器平台取到的IP是内部IP，管理端无法访问。

### ISSUE THREAD

**Issue by qtzheng** [xuxueli/xxl-job#630]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by RoonyLi** [comment]
@Bean(initMethod = "start", destroyMethod = "destroy")
    public XxlJobSpringExecutor xxlJobExecutor(InetUtils inetUtils) {
        logger.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppName(appName);
        if (StringUtils.isBlank(ip)) {
            ip = inetUtils.findFirstNonLoopbackHostInfo().getIpAddress();
        }
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);
        return xxlJobSpringExecutor;
    }
用spring cloud 的 inetUtils 可以解决。
配置文件或者容器启动变量增加
spring.cloud.inetutils.preferred-networks: '192.168.163.'

**Comment by xuxueli** [comment]
@RoonyLi 赞！欢迎PR。

**Comment by zenglanyuan** [comment]
我也是遇到这个问题，springboot怎么解决呢？

**Comment by kervin521** [comment]
已解决docker的swarm下通过网卡获取域真实IP

**Comment by chenxd1991** [comment]
> @bean(initMethod = "start", destroyMethod = "destroy")
> public XxlJobSpringExecutor xxlJobExecutor(InetUtils inetUtils) {
> logger.info(">>>>>>>>>>> xxl-job config init.");
> XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
> xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
> xxlJobSpringExecutor.setAppName(appName);
> if (StringUtils.isBlank(ip)) {
> ip = inetUtils.findFirstNonLoopbackHostInfo().getIpAddress();
> }
> xxlJobSpringExecutor.setIp(ip);
> xxlJobSpringExecutor.setPort(port);
> xxlJobSpringExecutor.setAccessToken(accessToken);
> xxlJobSpringExecutor.setLogPath(logPath);
> xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);
> return xxlJobSpringExecutor;
> }
> 
> 用spring cloud 的 inetUtils 可以解决。
> 配置文件或者容器启动变量增加
> spring.cloud.inetutils.preferred-networks: '192.168.163.'

为什么我获取到的还是docker容器的IP，而不是宿主机的IP地址

**Comment by ty1972873004** [comment]
> 已解决docker的swarm下通过网卡获取域真实IP

如何解决？
