### ISSUE TITLE
关于调度中心启动后不能通过域名或者ip+端口直接跳转到登录页

### ISSUE THREAD

**Issue by bin272** [xuxueli/xxl-job#631]
hi XXL
  调度中心启动后能够设置一个默认跳转页、全部都跳转到/xx-job-admin 这个地址去嘛？

**Comment by walyuuc** [comment]
这个取决于你的配置，server.context-path=/ 就可以直接用域名访问

**Comment by RoonyLi** [comment]
/ 很多资源文件不完全支持。

**Comment by bin272** [comment]
@xuxueli  关于这个问题有没有什么解决方案？ 如上所说、如果设置server.context-path=/  是可以跳转到登录页、但是登录成功后、首页等一些资源就加载不到了

**Comment by xuxueli** [comment]
这取决于你的配置方式，配置在跟地址下即可。
