### ISSUE TITLE
InheritableThreadLocal，在线程池下打印日志错误

### ISSUE THREAD

**Issue by fengzhentian** [xuxueli/xxl-job#634]
我在某个任务内，采用线程池开启子线程的方式，同时处理多条数据

在线程池下的线程里打印日志，只会打印到第一次执行任务的日志文件里

以后我启动其他的任务，任务的日志文件里，都是空的，都是打到了第一次的日志文件

**Comment by xuxueli** [comment]
你好，问题无法复现，请完成提供操作步骤重新提交。
