### ISSUE TITLE
SpringBoot 2.0.6版本，使用xxl-job 1.9.2，使用SpringBoot自带的jetty版本，随着任务执行线程会无限加大

### ISSUE THREAD

**Issue by fengzhentian** [xuxueli/xxl-job#635]
我的定时任务应用，采用SpringBoot 2.0.6版本，使用的是xxl-job 1.9.2调度中心

SpringBoot，默认配置的jetty版本号为9.4.12.v20180830
使用这个版本，jetty线程是以etp一串数字开头，类似etp507125010-1097
然后随着时间的推移，任务的逐渐执行，没有限制的无限加大。我测试时，这样的一批线程都上千了。

我经过查看官网提供的示例，你在SpringBoot应用示例里，手动修改了jetty的版本号为9.2.26.v20180806
我当初没有理解这块的意图，就没有加

后面我在代码里补充上这块，jetty的线程名称，就变为 pool-2-thread-32 这种格式的了
而且，线程也不会一直涨上去，而是在某一数量下，就不在上升了

以下是我的修改方式

    <properties>
        <jetty-server.version>9.2.26.v20180806</jetty-server.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-server</artifactId>
                <version>${jetty-server.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-util</artifactId>
                <version>${jetty-server.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-http</artifactId>
                <version>${jetty-server.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-io</artifactId>
                <version>${jetty-server.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

**Comment by xuxueli** [comment]
你好，底层通讯采用的jetty server，它通过线程池方式提供服务的，不过正常情况下 jetty Server 线程池存在上限的，并不会无限制增长。

你使用的jetty版本应该是一个有bug的版本，可以参考这条ISSUE：https://github.com/xuxueli/xxl-job/issues/625

这条ISSUE关闭了，可以在上面ISSUE里查看进度。
