### ISSUE TITLE
路由策略的疑问？

### ISSUE THREAD

**Issue by yushangjian** [xuxueli/xxl-job#636]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 2.0.0
### Other information
最不经常使用、故障转移、忙碌转移 感觉这几个策略应该不是互斥关系，对于集群部署应该同时支持这几个策略才行啊，但是任务只能选择一种策略。

**Comment by weiwunb** [comment]
老铁，正在动手改写路由策略。。。

**Comment by xuxueli** [comment]
👍 策略策略可以自定灵活扩展
