### ISSUE TITLE
启动一个任务后，down掉那台执行任务的服务器，任务就一直在执行中

### ISSUE THREAD

**Issue by a327919006** [xuxueli/xxl-job#638]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT

### Expected behavior
期望：任务能变成失败，并发送邮件通知

### Actual behavior
目前情况：任务一直处于执行中状态，也不会失败，也没有通知。

### Steps to reproduce the behavior
1、启动admin（单机）和executor（单机）。
2、点击执行某个耗时任务。
3、在任务执行过程中，停掉executor（模拟真实情况,服务器挂了）

### Other information
1、当前版本是否能实现期望？如果能，麻烦回复下配置步骤，是否是我的配置有问题
如果不能，未来版本能否支持？

**Comment by yushangjian** [comment]
确实存在这个Bug啊 重启执行器后并不会进行回调。。

**Comment by Var-iazioni** [comment]
> 你好，调度中心依赖执行器回调来感知任务结果，如果执行器不回调，调度中心不会做处理的。
> 
> 不过，执行器关闭之前（正常关闭），会将任务失败Log存磁盘的，执行器回复之后会立即重试回调的，不会有遗漏。

执行器恢复后并没有回调啊。。我也遇到这个问题了。。

**Comment by Var-iazioni** [comment]
我修改了JobRegistryMonitorHelper和JobFailMonitorHelper，基本已经实现了执行器下线后调度中心停止该执行器正在执行中的任务。

**Comment by toohandsome** [comment]
同样的问题.去查admin网页的日志的话,admin后台会打一堆链接失败的日志.
建议: 是否可以增加一个设置,多久没返回就认为是失败了,然后转移到其他机器执行?

**Comment by toohandsome** [comment]
@xuxueli

**Comment by toohandsome** [comment]
或者说心跳检测的时候,自动剔除这种在执行中的任务,可以认为是失败了 @xuxueli

**Comment by xiaoluobotouzi** [comment]
@xuxueli +1

**Comment by zhengzhiyuan** [comment]
@xuxueli  +1

**Comment by xuxueli** [comment]
如下特性已经加入TODO列表，将会排期跟进，可以关注下：

- 任务结果丢失处理：针对长期（设置过期时间时，超过"有效期+1min"；未设置超时时间时，超过"2H"）处于运行中的任务，主动检测该执行器是否在线，如果不在线主动标记失败；
