### ISSUE TITLE
定时任务总是无法正常

### ISSUE THREAD

**Issue by leeronen** [xuxueli/xxl-job#64]
![image](https://cloud.githubusercontent.com/assets/11371186/25993075/637b197a-373b-11e7-9a5d-fab1a98f7da3.png)
无法正常结束

**Comment by leeronen** [comment]
我看了代码，是因为线程判断只有成功才返回成功，实际上我已经成功执行，错误为请求超时，一直夯在那里

**Comment by xuxueli** [comment]
你好，你是指任务执行结果回调的时候超时了吗？
是不是调度中心回调地址配合错了啊？

**Comment by leeronen** [comment]
你好，是因为部分成功，部分不成功，因为这个我才很奇怪的，区别在于一个在本地一个在测试服务器

**Comment by leeronen** [comment]
主要是我已经获取到了execute中的return信息为成功，但是，线程处于超时状态，所以没太明白，回调已经完成为什么还有线程在retry

**Comment by leeronen** [comment]
因为测试服务器时间不同导致的

**Comment by YxShion** [comment]
我 的就是调度时间可能会相差八个小时导致执行时失败，现在不知道怎么处理，你那个问题是怎么处理的？

**Comment by leeronen** [comment]
调整一下服务器的时间，时区保持一致

**Comment by xuxueli** [comment]
是的，时区保持一致即可。

**Comment by YxShion** [comment]
我的不是全部不对，大概有一半的时间是时区相差八个小时，另一半的时间和调度都是OK的。不知道是哪里出了问题

**Comment by leeronen** [comment]
是调用同一台服务器同一个容器出现两种状况吗，容器关闭时未kill掉进程，再次启动可能会产生一半成功一半失败，（容器关闭时未kill掉进程，再次启动具体原因当时我没有查明）但是会有这个样的现象发生
