### ISSUE TITLE
关于阻塞处理策略-覆盖之前调度的疑问

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#640]
覆盖之前调度：调度请求进入单机执行器后，发现执行器存在运行的调度任务，将会终止运行中的调度任务并清空队列，然后运行本地调度任务；
其中终止运行中的调度任务，没有理解是如何终止的，是用线程中断 停止IJobHandler的execute方法吗？(可能方法已经执行了一半)
我的场景是 每5秒执行一次，但是一次任务可能最长需要执行20秒左右，这个我应该如何选择阻塞处理策略呢

**Comment by farsunset** [comment]
我看了一下源码，我可能需要一种新的阻塞策略:
丢弃后续调度并且不记日志

**Comment by walyuuc** [comment]
2.0有丢弃后续的阻塞策略

**Comment by xuxueli** [comment]
丢弃后续调度策略很早就提供了。
@farsunset 新阻塞策略，可以自行灵活扩展。

**Comment by luobotiantang** [comment]
丢弃后续调度并且不记日志感觉比较好，本身都丢弃了还记个调度异常日志干什么？
