### ISSUE TITLE
子任务状态显示问题

### ISSUE THREAD

**Issue by patricklo** [xuxueli/xxl-job#645]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0

### Expected behavior
当任务B设置被任务A触发，任务B作为纯粹子任务，不应该再设cron, 应提供任务的类型选择。当选择为子任务时，就不应该再额外设置cron。

### Actual behavior
当任务B设置被任务A触发，任务B还被强制设置cron参数，但又不需要任务B的cron生效，只能把任务B暂停。
但，此时状态显示有PAUSED, 完全展示不出任务B是被任务A触发的设置。

### Other information

**Comment by xuxueli** [comment]
你好，多谢反馈！
目前任务管理是平等的，任务触发来源可以任务触发备注日志里查看，区分是哪里触发的。
任务暂停状态，cron改为非必填，这个后续迭代会考虑的。
