### ISSUE TITLE
调度中心宕机的问题

### ISSUE THREAD

**Issue by sldx01** [xuxueli/xxl-job#646]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB 1.9.1
### Other information
调度中心一台
执行任务约200个，单机部署

运行过程中 调度中心宕机 
xxl-job-admin.log  出现  java.lang.InterruptedException: sleep interrupted 日志
请问这个是什么原因？

![image](https://user-images.githubusercontent.com/44745732/49273555-5c9cc700-f4b0-11e8-97ee-5c492fde3cc0.png)

**Comment by xuxueli** [comment]
你好，问题无法复现。有没有对调度中心添加监控，比如Cat？可以分析下相应的监控数据。另外，除了这部分日志外，还有其他报错Log吗？

**Comment by ParanoidKevin** [comment]
我也遇到一样的问题，调度中心宕机，执行器没有，都是在删除一个任务后宕机的。 @xuxueli 
![image](https://user-images.githubusercontent.com/29868934/55383028-ba721600-5559-11e9-8ccc-ff146d0a7ade.png)
![image](https://user-images.githubusercontent.com/29868934/55383136-03c26580-555a-11e9-9996-e60947b0ae93.png)
