### ISSUE TITLE
如何支持springcloud多个微服务之间的任务调度？

### ISSUE THREAD

**Issue by windlikeman** [xuxueli/xxl-job#647]
version 1.9.2
up主是不是要把眼光投向springcloud了？

**Comment by xuxueli** [comment]
你好，springboot 项目支持非常好，开箱即用。

原生提供了 springboot 格式的执行器示例项目，可以参考调整。

**Comment by jiaoyilun** [comment]
我们是在sc中新加入了一个executor模块，加入了xxl-core的依赖，然后在这个模块中通过feign去调用触发不同的服务，这样做减少不必要的耦合，但是定时器的日志就有点不太好收集了，因为实际业务执行不再这个模块，不知道大家有什么好的方案

**Comment by Var-iazioni** [comment]
> 我们是在sc中新加入了一个executor模块，加入了xxl-core的依赖，然后在这个模块中通过feign去调用触发不同的服务，这样做减少不必要的耦合，但是定时器的日志就有点不太好收集了，因为实际业务执行不再这个模块，不知道大家有什么好的方案

最近也在搞这个。。我的解决方案是把调度中心和执行器直接注册到Eureka。然后业务模块通过feign调用调度中心的接口。。Eureka感知服务上下线来给不同模块发通知。。

**Comment by jiaoyilun** [comment]
> > 我们是在sc中新加入了一个executor模块，加入了xxl-core的依赖，然后在这个模块中通过feign去调用触发不同的服务，这样做减少不必要的耦合，但是定时器的日志就有点不太好收集了，因为实际业务执行不再这个模块，不知道大家有什么好的方案
> 
> 最近也在搞这个。。我的解决方案是把调度中心和执行器直接注册到Eureka。然后业务模块通过feign调用调度中心的接口。。Eureka感知服务上下线来给不同模块发通知。。

没太明白，feign调用调度中心哪些接口，目的是什么呢，enreka发什么通知？我是直接搞了一个服务让调度中心来调用
