### ISSUE TITLE
日志过大导致执行器启动时直接内存溢出

### ISSUE THREAD

**Issue by liaochente** [xuxueli/xxl-job#648]
因为测试环境下的任务有BUG，导致不断的写job日志，最后job日志变得很大以后再重启执行器，就启动不起来了，查看源码发现是在启动得时候会去加载job日志，因日志过大导致内存直接溢出；
加载源码com.xxl.job.core.util.FileUtil.loadFileLines(String fileName):
`public static List\<String\> loadFileLines\(String fileName\) {

        List<String> result = new ArrayList<>();

        // valid log file
        File file = new File(fileName);
        if (!file.exists()) {
            return result;
        }

        // read file
        StringBuffer logContentBuffer = new StringBuffer();
        int toLineNum = 0;
        LineNumberReader reader = null;
        try {
            //reader = new LineNumberReader(new FileReader(logFile));
            reader = new LineNumberReader(new InputStreamReader(new FileInputStream(file), "utf-8"));
            String line = null;
            while ((line = reader.readLine())!=null) {
                if (line!=null && line.trim().length()>0) {
                    result.add(line);
                }
            }
        } catch (IOException e) {
            logger.error(e.getMessage(), e);
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    logger.error(e.getMessage(), e);
                }
            }
        }

        return result;
    }
`
是否可以考虑优化日志加载或者记录日志得时候做限制？

**Comment by weiwunb** [comment]
这个问题恐怖了。。。老铁你是怎么在定时任务里打日志的？分享下，我们回避这个坑。

**Comment by liaochente** [comment]
> 这个问题恐怖了。。。老铁你是怎么在定时任务里打日志的？分享下，我们回避这个坑。

return new ReturnT<String>(500, msg.toString())

代码中try catch了异常，然后把异常信息塞到msg里了，然后定时任务中有几个数据有异常导致那几条数据被处理的时候一直抛异常，然后。。。一不小心就撑爆了。。。

ps:我觉得就算是正常的返回错误信息，迟早也会有爆的一天的。。。

**Comment by liaochente** [comment]
紧急处理方案 删除 xxl-job/jobhandler下的日志文件，保证执行器能成功启动

**Comment by xuxueli** [comment]
迭代分支问题已修复，将会跟随下个版本一同发布，可以 pull master 体验下。
