### ISSUE TITLE
xxl-job-admin是2.0.2-SNAPSHOT版本，执行器用的xxl-job-core是2.0.1,兼容吗？

### ISSUE THREAD

**Issue by zpa3x60** [xuxueli/xxl-job#649]
如题，目前执行器没有2.0.2的快照版本。

**Comment by AdilXia** [comment]
也是遇到了这个问题
[INFO] Building xxl-job-admin 2.0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.xuxueli:xxl-job-core:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.984 s
[INFO] Finished at: 2018-12-05T16:23:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xxl-job-admin: Could not resolve dependencies for project com.xuxueli:xxl-job-admin:jar:2.0.2-SNAPSHOT: Could not find artifact com.xuxueli:xxl-job-core:jar:2.0.2-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by xuxueli** [comment]
你好，v2.0.2 通讯组件由调整，该版本仍然在迭代中，线上使用建议用Release版本；
