### ISSUE TITLE
配置文件没有驼峰，和spring整体规范不符合

### ISSUE THREAD

**Issue by RainyII** [xuxueli/xxl-job#650]
官网和demo里的配置文件都是
applicationcontext-xxl-job.xml

而其他配置文件都是
applicationContext-xxx.xml

这样从规范来讲不遵守，而且误导大家吧。

**Comment by mizhiming521** [comment]
同意提出者意见  请作者修改规范

**Comment by xuxueli** [comment]
多谢反馈！上述问题已修复，最新分支版本已经迁移至springboot格式。
