### ISSUE TITLE
C3P0连接池 Deadlocked PoolThread

### ISSUE THREAD

**Issue by zhangandyhui** [xuxueli/xxl-job#651]
2018-11-29 19:55:41 xxl-job-admin [com.mchange.v2.async.ThreadPoolAsynchronousRunner]-[C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-AdminTaskTimer]-[log]-[220]-[WARN] com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@324185f4 -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!
2018-11-29 19:55:41 xxl-job-admin [com.mchange.v2.async.ThreadPoolAsynchronousRunner]-[C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-AdminTaskTimer]-[log]-[220]-[WARN] com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@324185f4 -- APPARENT DEADLOCK!!! Complete Status: 
	Managed Threads: 3
	Active Threads: 3
	Active Tasks: 
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@673ed7b3
			on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#0
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@3d9de759
			on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#2
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@5fc8d46c
			on thread: C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#1
	Pending Tasks: 
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@680efaae
		com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask@799c2b53
Pool thread stack traces:
	Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#0,5,main]
		java.net.PlainSocketImpl.socketConnect(Native Method)
		java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
		java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
		java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		java.net.Socket.connect(Socket.java:589)
		com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
		com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
		com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
		com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
		com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
		com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
		com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
		sun.reflect.GeneratedConstructorAccessor140.newInstance(Unknown Source)
		sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		java.lang.reflect.Constructor.newInstance(Constructor.java:422)
		com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
		com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
		com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#2,5,main]
		java.net.PlainSocketImpl.socketConnect(Native Method)
		java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
		java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
		java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		java.net.Socket.connect(Socket.java:589)
		com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
		com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
		com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
		com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
		com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
		com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
		com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
		sun.reflect.GeneratedConstructorAccessor140.newInstance(Unknown Source)
		sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		java.lang.reflect.Constructor.newInstance(Constructor.java:422)
		com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
		com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
		com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Thread[C3P0PooledConnectionPoolManager[identityToken->z8kflt9y44kulz17l9g12|66d138e2]-HelperThread-#1,5,main]
		java.net.PlainSocketImpl.socketConnect(Native Method)
		java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
		java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
		java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		java.net.Socket.connect(Socket.java:589)
		com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
		com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
		com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
		com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
		com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
		com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
		com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
		sun.reflect.GeneratedConstructorAccessor140.newInstance(Unknown Source)
		sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		java.lang.reflect.Constructor.newInstance(Constructor.java:422)
		com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
		com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
		com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
		com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
		com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
		com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
		com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

**Comment by wangxen** [comment]
host文件配置好localhost地址

**Comment by xuxueli** [comment]
可以参考：https://blog.csdn.net/zfmsa/article/details/84293680
