### ISSUE TITLE
版本增量脚本维护

### ISSUE THREAD

**Issue by maohc** [xuxueli/xxl-job#652]
现在都是基于全量脚本进行发版，使用人员在进行版本升级的时候，无增量脚本可执行，只能手动比对脚本得出增量脚本文件，升级带来困难。

**Comment by imkratos** [comment]
我也有相同疑问，比如调度中心，我现在使用1.9.0，想要升级最新版，可是发现表结构改了挺多，不能平滑升级，好像只能停机维护，然后和执行器一起升级，不知道是不是我没找对办法，看了整个文档也没有介绍。

还有，有个建议，有的表没有主键，这个好像在mysql里不是特别友好吧？而且比如日志表没有索引，可能导致主页加载非常慢。还有一些外键是不是也不是特别友好，纯讨论。

**Comment by daiing** [comment]
agree+1

**Comment by xuxueli** [comment]
@maohc 版本升级时，建议先比对建表SQL，一般仅部分字段调整。少量表字段调整后，直接用新版本调度中心与执行器覆盖即可。

@imkratos 无主键、有外键的这些表都是 quartz内部的表，这部分复用的原生的没有调整。其他扩展表都是合规的。

**Comment by xuxueli** [comment]
v2.0.2 之后通讯组件趋于稳定，后续执行器升级会支持不停机、灰度升级。
