### ISSUE TITLE
执行器没有执行

### ISSUE THREAD

**Issue by kinas129** [xuxueli/xxl-job#655]
版本1.9.2-SNAPSHOT

执行器一直报连接超时，然后就一直没有执行了，但是其他job都是正常的，暂停\恢复执行器后又正常了
执行器为单机，调度中心为集群
![image](https://user-images.githubusercontent.com/8350160/49569296-83ef0a80-f96e-11e8-9205-376b7d11f248.png)

**Comment by xuxueli** [comment]
你好，从日志看是执行器回调请求失败，请确认调度中心服务稳定，执行器请求调度中心网络通畅。
