### ISSUE TITLE
急！执行器正常，调度中心正常，任务却调度失败。

### ISSUE THREAD

**Issue by prety16** [xuxueli/xxl-job#656]
急，希望大大能解答。
执行器自动注册，正常，调度中心也运行正常。
但是定时任务却一直调度失败。
查看错误日志为：msg：java.lang.RuntimeException: Network request error: Connect to 172.16.42.78:9998 [/172.16.42.78] failed: connect timed out
但是，点手动执行却能调度成功。
在调度中心XxlJobDynamicScheduler类的getExecutorBiz方法下的   
executorBiz = (ExecutorBiz) new NetComClientProxy(ExecutorBiz.class, address, accessToken).getObject();打了断点，发现点击手动执行能进入断点处，但是定时任务却无法进入断点，就显示调度失败了。
不知道任务调度时，调度中心与执行器间的通信机制到底是怎么样的。

**Comment by prety16** [comment]
暂停任务，重启调度中心和执行器，任务执行会正常，但是过程中如果调度中心重启，执行器不重启，就会再次出现这样的问题

**Comment by xuxueli** [comment]
你好，问题无法复现，请完整提供复现操作步骤。
底层仅是一次普通的http通讯，借助jetty实现。
从日志看应该是执行器端口服务或者网络问题。

**Comment by Kevin-chenyang** [comment]
急，现在遇到一个问题,定时任务自动调用一致处与执行中,一直未完成,也没有出现报错的情况,但是点手动执行却能执行成功,请问这种情况可能是什么原因造成的呢?

**Comment by 410919244** [comment]
@xuxueli 看了好几个人都这么说确实有这个问题啊。不是网络问题。手动执行能成功。自动调度每次都失败。如果是网络问题手动也会失败。每5秒执行一次，不可能每次我手动点就没问题。自动调度就出现网络问题。有一点可以确定 手动执行和自动调度执行的ip地址不一样。自动调度的机器ip一直都是：172.18.58.93。手动执行的调度机器ip不是这个。而且没有93这个ip。感觉是自动调度写死了。或者是缓存到了什么地方。我用的阿里云k8s环境部署的 不知道会不会与k8s容器每次启动ip都会变有关。但是为什么自动调度总是一个错误的ip？

**Comment by 410919244** [comment]
打扰了。。。原因已经找到。因为两个不同的环境访问的同一个数据库。

**Comment by haha-john** [comment]
> @xuxueli 看了好几个人都这么说确实有这个问题啊。不是网络问题。手动执行能成功。自动调度每次都失败。如果是网络问题手动也会失败。每5秒执行一次，不可能每次我手动点就没问题。自动调度就出现网络问题。有一点可以确定 手动执行和自动调度执行的ip地址不一样。自动调度的机器ip一直都是：172.18.58.93。手动执行的调度机器ip不是这个。而且没有93这个ip。感觉是自动调度写死了。或者是缓存到了什么地方。我用的阿里云k8s环境部署的 不知道会不会与k8s容器每次启动ip都会变有关。但是为什么自动调度总是一个错误的ip？

@xuxueli 同样在阿里云的k8s中部署，问题也都差不多，都是自动调度时偶尔调度的机器IP为docker0 的IP地址，而非pod ip，当为 docker0 的IP地址时，网络请求不通，执行器IP都相同

自动调度日志：
      任务触发类型：Cron触发
      调度机器：169.254.123.2
      执行器-注册方式：自动注册
      执行器-地址列表：[http://10.0.0.36:8090/]
      路由策略：轮询
      阻塞处理策略：单机串行
      任务超时时间：0
      失败重试次数：0
      
      >>>>>>>>>>>触发调度<<<<<<<<<<<
      触发调度：
      address：http://10.0.0.36:8090/
      code：500
      msg：xxl-job remoting error(connect timed out), for url : http://10.0.0.36:8090/run

手动调度日志：
      任务触发类型：手动触发
      调度机器：10.0.1.7
      执行器-注册方式：自动注册
      执行器-地址列表：[http://10.0.0.36:8090/]
      路由策略：轮询
      阻塞处理策略：单机串行
      任务超时时间：0
      失败重试次数：0
      
      >>>>>>>>>>>触发调度<<<<<<<<<<<
      触发调度：
      address：http://10.0.0.36:8090/
      code：200
      msg：null

**Comment by little-coati** [comment]
> 打扰了。。。原因已经找到。因为两个不同的环境访问的同一个数据库。

我也是这个问题，一直纳闷为什么一直报xxl-job remoting error(connect timed out)，后来见到别的issue下有设置重试次数的，设置了一下，发现重试可以成功。恍然大悟，有人在本地起了xxl-job然后用的线上的数据库...

**Comment by varcarfu** [comment]
> > 打扰了。。。原因已经找到。因为两个不同的环境访问的同一个数据库。
> 
> 我也是这个问题，一直纳闷为什么一直报xxl-job remoting error(connect timed out)，后来见到别的issue下有设置重试次数的，设置了一下，发现重试可以成功。恍然大悟，有人在本地起了xxl-job然后用的线上的数据库...

确实是这个原因，一个数据库被两个xxl-job admin连接着

**Comment by iockx** [comment]
我的情况是注册成功，自动任务和手动任务都执行失败...显示连接超时，xxl-job只有一个在运行，有朋友知道什么情况么？
