### ISSUE TITLE
作者您好，我可否在您的代码基础上新建仓库进行重构开发，相关代码命名全部重新定义，文档中会指出重构来源

### ISSUE THREAD

**Issue by liangshan-li** [xuxueli/xxl-job#658]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by liangshan-li** [comment]
我使用的版本是1.9.2-SNAPSHOT
期望在此基础上，进行重构开发

**Comment by weiwunb** [comment]
如果这个项目要重构，就不再仅仅是改命名规范这么简单了。
经过几个月的试用，不断的改写，扩展，以及日益涌现的bug，深深觉得如果要重构开发，最好是在架构设计上再仔细思考和优化。

**Comment by xuxueli** [comment]
可以的，只要符合开源协议可以任意定制。

定制版本欢迎在这里汇总分享下：https://github.com/xuxueli/xxl-job/issues/658
