### ISSUE TITLE
每次项目停止报错：java.lang.IllegalStateException: !STOPPED

### ISSUE THREAD

**Issue by zhuyucheng52** [xuxueli/xxl-job#66]
是不是因为项目停止时没有调用jetty server的stop就直接调用了destory导致项目停止时报错。

**Comment by xuxueli** [comment]
你好，可以贴一下再用的XXL-JOB的具体版本吗 ：）

**Comment by xqinghu** [comment]
没猜错应该是log4j shutdown报错， 没深究这个问题，我这替换为logback就没问题了，怀疑是web.xml中Log4jConfigListener的问题
