### ISSUE TITLE
构建环境

### ISSUE THREAD

**Issue by 749145134** [xuxueli/xxl-job#660]
您好，我看见您官方文档中写到
JDK：1.7+
Servlet/JSP Spec：3.1/2.3
Tomcat：8.5.x/Jetty9.2.x
Spring-boot：1.5.x/Spring4.x
Mysql：5.6+
Maven：3+
我们环境版本较低，如果使用您的框架，在这些组件版本较低的情况下，是否会出现不可预知错误

**Comment by xuxueli** [comment]
你好，JDK与MySQL版本务必满足，不然编译部署可能会有问题。
