### ISSUE TITLE
xxl-job 2.0.1初始化mysql脚本在mysql5.6上执行报错

### ISSUE THREAD

**Issue by madfrog2047** [xuxueli/xxl-job#661]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
mysql初始化脚本执行报错
### Actual behavior
执行的SQL语句出错：
CREATE TABLE XXL_JOB_QRTZ_JOB_DETAILS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
)
错误信息：Index column size too large. The maximum column size is 767 bytes.
### Steps to reproduce the behavior
直接在mysql5.6中执行导入
### Other information

**Comment by fangweidujian** [comment]
在建表语句后加上存储引擎和字符集。比如 ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by xuxueli** [comment]
你好，这部分是quartz内部表，没有做变更。可以参考 @fangweidujian 方式做调整。
