### ISSUE TITLE
xxl-job如何设置并行

### ISSUE THREAD

**Issue by 749145134** [xuxueli/xxl-job#666]
您好，xxl-job如果设置并行的话，应该如何设置?

**Comment by yushangjian** [comment]
你可以配置2个任务就可以并行了 。

**Comment by Var-iazioni** [comment]
自己实现一个基于logId的jobThreadRepository就可以了

**Comment by jinyue233** [comment]
老哥，最近在看xxl-job，请教一个问题：                                                                             xxl-job是通过1，一个后台的单线程来不停扫描job-info表来执行不同的任务的吗？
2，若是单线程的话，假如有两个任务要同时执行，会存在时间差异吧，还有万一这个线程阻塞了呢，岂不是会影响其他定时任务？
