### ISSUE TITLE
通过其它日志框架如log4j打印的日志如何写入调度日志中？

### ISSUE THREAD

**Issue by cnhnnyzhy** [xuxueli/xxl-job#67]
您好，我发现最新版本中只能将调用XxlJobLogger.log()方法打印的日志写入调度日志并可查看，通过其它日志框架如log4j打印的日志如何写入调度日志中？如何通过管理平台查看其它框架打印的日志呢？

**Comment by xuxueli** [comment]
你好，感谢关注啊！
在v1.7.1之前的版本，日志是通过定制log4j的append实现的，但是该方式强依赖log4j因此废弃了，毕竟很多项目用Logback的。
v1.7.1版本之后，任务日志目前统一通过 “XxlJobLogger.log()” 来打印。如果想通过log4j打印，目前是不支持的，不过可以参考历史版本中log4j的append实现。
