### ISSUE TITLE
最不经常使用、最近最久未使用无法感知执行器上、下线

### ISSUE THREAD

**Issue by yushangjian** [xuxueli/xxl-job#670]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0
### Actual behavior
当任务采用上述策略时，如果某一个执行器下线，调度器无法感知该执行器已掉线，
会调度失败。
### Other information

**Comment by xuxueli** [comment]
问题已修复，将会在下个版本一同发布，可以pull master体验。
