### ISSUE TITLE
接入xxl-job-executor-samples之后导致PageHelper分页失效，请问如何解决呢？

### ISSUE THREAD

**Issue by JoneYing** [xuxueli/xxl-job#673]
接入xxl-job-executor-samples之后导致PageHelper分页失效，请问如何解决呢？

**Comment by qiankun30** [comment]
我也遇到过，我那是springboot 版本是2.1.0  ，需要 PageHelper  版本到 5.1.8。如果是pagehelper-spring-boot-starter 需要到 1.2.10。

**Comment by JoneYing** [comment]
我更改springboot版本为2.1.0 和pagehelper-spring-boot-starter  1.2.10发现还是不行。你这边是接入PageHelper吗？

**Comment by qiankun30** [comment]
不好意思，太忙了，刚看到。 我这边用的是springboot 2.1.0  、pagehelper-spring-boot-starter 1.2.10，这个是按 pagehelper-spring-boot-starter 升级版本说明 https://github.com/pagehelper/pagehelper-spring-boot （v1.2.10 - 2018-11-11）。https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Important.md 你可以看下 Mybatis-PageHelper 重要提示，再者建议你把异常及代码贴出来。

**Comment by JoneYing** [comment]
我后面查到了原因，是因为我在XxlJobConfig类上配置扫描的包包含了整个项目的bean,将这个扫描范围改成任务handler包之后该问题得以解决。谢谢你的帮助~
