### ISSUE TITLE
单个任务不支持并发执行，请问是出于什么考虑？

### ISSUE THREAD

**Issue by Var-iazioni** [xuxueli/xxl-job#676]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

仔细研读过大佬的代码后发现，串行机制是由JobThread中的队列实现的，而且run方法中也都是只能从队列里获取，完全没有留给并发执行扩展的余地，请问这样是出于什么考虑？如果强行修改源码支持单任务并发执行，会有什么性能/稳定性/安全性上的隐患吗？

**Comment by zenghuabin** [comment]
job 一般限制单次一台机器执行就可以了，并发执行 这种意义不大，上一次job，都还没执行，下一次的job有来调了，这样肯定有问题的呀

**Comment by Var-iazioni** [comment]
> job 一般限制单次一台机器执行就可以了，并发执行 这种意义不大，上一次job，都还没执行，下一次的job有来调了，这样肯定有问题的呀

但是我现在有这种需求，建一个任务，每次手动触发给不同的参数。这样只能串行执行，建多个任务又浪费资源，查询也不方便。
看了看作者的代码，这一块控制的很严格，想改成并行需要很大的改动。

**Comment by zenghuabin** [comment]
创建任务的时候不是有个运行模式么，你调整下看有没有用

**Comment by Var-iazioni** [comment]
> 创建任务的时候不是有个运行模式么，你调整下看有没有用

只有单机串行和丢弃前后进度。
奇怪的是源码里的枚举倒是有并行选项，但是被注释了，没仔细看过文档，不知是作者要增加并行，还是之前有过，后来取消了？

**Comment by Var-iazioni** [comment]
我自己修改好了。。copy了一份以logId为key的jobThreadRepository。如果有并行任务。就走自己写的jobThread。。
