### ISSUE TITLE
调度中心运行一段时间后自动挂掉（紧急）

### ISSUE THREAD

**Issue by lichunhui1314** [xuxueli/xxl-job#678]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-admin-2.0.1

### Expected behavior
调度中心运行稳定

### Actual behavior
调度中心运行一段时间后，因出现异常导致服务挂掉

### Steps to reproduce the behavior
18:50:29.899 logback [http-nio-8090-exec-5] INFO  c.x.j.a.service.impl.AdminBizImpl - >>>>>>>>> JobApiController.callback success, handleCallbackParam=HandleCallbackParam{logId=10790, logDateTim=1545130229567, executeResult=ReturnT [code=200, msg=null, content=null]}, callbackResult=ReturnT [code=200, msg=null, content=null]
18:50:31.592 logback [Thread-4] INFO  c.x.j.a.c.t.JobFailMonitorHelper - >>>>>>>>>>> job monitor, job success, JobLogId:10790
19:11:20.629 logback [http-nio-8090-exec-10] INFO  c.x.j.a.service.impl.AdminBizImpl - >>>>>>>>> JobApiController.callback success, handleCallbackParam=HandleCallbackParam{logId=10791, logDateTim=1545131471846, executeResult=ReturnT [code=200, msg=迁移过期二维码定时任务结束, content=null]}, callbackResult=ReturnT [code=200, msg=null, content=null]
19:11:21.610 logback [Thread-4] INFO  c.x.j.a.c.t.JobFailMonitorHelper - >>>>>>>>>>> job monitor, job success, JobLogId:10791
22:44:14.138 logback [Thread-7] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4ccabbaa: startup date [Mon Dec 17 10:57:41 CST 2018]; root of context hierarchy
22:44:14.140 logback [Thread-7] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
22:44:14.142 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_dzf-071545015468249 paused.
22:44:14.143 logback [Thread-7] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
22:44:14.156 logback [Thread-7] INFO  c.x.j.a.c.t.JobTriggerPoolHelper - >>>>>>>>> xxl-job trigger thread pool shutdown success.
22:44:14.156 logback [Thread-3] ERROR c.x.j.a.c.t.JobRegistryMonitorHelper - job registry instance error:{}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.xxl.job.admin.core.thread.JobRegistryMonitorHelper$1.run(JobRegistryMonitorHelper.java:82)
	at java.lang.Thread.run(Thread.java:745)
22:44:14.157 logback [Thread-4] ERROR c.x.j.a.c.t.JobFailMonitorHelper - job monitor error:{}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.xxl.job.admin.core.thread.JobFailMonitorHelper$1.run(JobFailMonitorHelper.java:94)
	at java.lang.Thread.run(Thread.java:745)
22:44:14.170 logback [Thread-7] INFO  o.s.s.quartz.SchedulerFactoryBean - Shutting down Quartz Scheduler
22:44:14.170 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_dzf-071545015468249 shutting down.
22:44:14.170 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_dzf-071545015468249 paused.
22:44:14.172 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_dzf-071545015468249 shutdown complete.

### Other information

**Comment by AlexRITIAN** [comment]
我也遇到了同样的问题，但是我在本地启动是没有问题的，放到容器服务器上就出现这个报错了。是在刚启动的时候。

10:31:25.632 logback [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:31:25.633 logback [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/static/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:31:25.753 logback [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:31:26.835 logback [main] INFO  o.s.u.f.SpringTemplateLoader - SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@27f8302d: startup date [Wed Dec 19 10:31:17 UTC 2018]; root of context hierarchy] and template loader path [classpath:/templates/]
10:31:26.837 logback [main] INFO  o.s.w.s.v.f.FreeMarkerConfigurer - ClassTemplateLoader for Spring macros added to FreeMarker configuration
10:31:27.743 logback [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
10:31:27.828 logback [main] INFO  o.s.c.s.DefaultLifecycleProcessor - Starting beans in phase 2147483647
10:31:27.828 logback [main] INFO  o.s.s.quartz.SchedulerFactoryBean - Will start Quartz Scheduler [getSchedulerFactoryBean] in 20 seconds
10:31:27.839 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
10:31:27.927 logback [main] INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
10:31:28.136 logback [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8080 (http)
10:31:28.142 logback [main] INFO  c.x.job.admin.XxlJobAdminApplication - Started XxlJobAdminApplication in 12.717 seconds (JVM running for 14.175)
10:31:47.830 logback [Quartz Scheduler [getSchedulerFactoryBean]] INFO  o.s.s.quartz.SchedulerFactoryBean - Starting Quartz Scheduler now, after delay of 20 seconds
10:31:47.867 logback [Quartz Scheduler [getSchedulerFactoryBean]] INFO  o.s.s.quartz.LocalDataSourceJobStore - ClusterManager: detected 1 failed or restarted instances.
10:31:47.868 logback [Quartz Scheduler [getSchedulerFactoryBean]] INFO  o.s.s.quartz.LocalDataSourceJobStore - ClusterManager: Scanning for instance "service-2582-798fc4654f-gsckg1545214853025"'s failed in-progress jobs.
10:31:47.902 logback [Quartz Scheduler [getSchedulerFactoryBean]] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_service-2586-54699f5c5f-zd5671545215483257 started.
10:33:20.920 logback [Thread-7] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@27f8302d: startup date [Wed Dec 19 10:31:17 UTC 2018]; root of context hierarchy
10:33:20.925 logback [Thread-7] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
10:33:20.926 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_service-2586-54699f5c5f-zd5671545215483257 paused.
10:33:20.927 logback [Thread-7] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
10:33:20.931 logback [Thread-7] INFO  c.x.j.a.c.t.JobTriggerPoolHelper - >>>>>>>>> xxl-job trigger thread pool shutdown success.
10:33:20.933 logback [Thread-3] ERROR c.x.j.a.c.t.JobRegistryMonitorHelper - job registry instance error:{}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.xxl.job.admin.core.thread.JobRegistryMonitorHelper$1.run(JobRegistryMonitorHelper.java:82)
	at java.lang.Thread.run(Thread.java:745)
10:33:20.934 logback [Thread-4] ERROR c.x.j.a.c.t.JobFailMonitorHelper - job monitor error:{}
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.xxl.job.admin.core.thread.JobFailMonitorHelper$1.run(JobFailMonitorHelper.java:91)
	at java.lang.Thread.run(Thread.java:745)
10:33:20.935 logback [Thread-7] INFO  o.s.s.quartz.SchedulerFactoryBean - Shutting down Quartz Scheduler
10:33:20.936 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_service-2586-54699f5c5f-zd5671545215483257 shutting down.
10:33:20.936 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_service-2586-54699f5c5f-zd5671545215483257 paused.
10:33:20.938 logback [Thread-7] INFO  org.quartz.core.QuartzScheduler - Scheduler getSchedulerFactoryBean_$_service-2586-54699f5c5f-zd5671545215483257 shutdown complete.

**Comment by xuxueli** [comment]
你好，问题无法复现。请完整提供问题复现操作步骤。

**Comment by luobotiantang** [comment]
我遇到过线程达到200服务就会挂掉的情况
