### ISSUE TITLE
web服务使用同一个端口

### ISSUE THREAD

**Issue by IAMTJW** [xuxueli/xxl-job#679]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
xxl-job-client开发不要使用自己单独的端口，与web服务使用同一个端口
### Actual behavior
目前xxl-job-client与spring boot服务集成时需要设置两个端口
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/620
