### ISSUE TITLE
是否支持通过接口添加任务？

### ISSUE THREAD

**Issue by cowcomic** [xuxueli/xxl-job#680]
是否支持通过接口创建添加任务，执行器已经添加好了，但任务现在希望是通过接口进行添加，任务不是由人来管理了，在文档中没有看到接口相关的说明，请问是否能支持呢？

另外是否支持通过接口获取任务的状态？

### Which version of XXL-JOB do you using?
1.9.2

**Comment by cowcomic** [comment]
> 同问，也很想知道

从文档看目前不支持添加任务，但是能够执行启动暂停任务

**Comment by xuxueli** [comment]
你好，支持的，文档搜索关键字 ”提供给业务的API服务“
