### ISSUE TITLE
2.0.1新版没有了停止，默认状态是NONE

### ISSUE THREAD

**Issue by liuxiang12138** [xuxueli/xxl-job#683]
![image](https://user-images.githubusercontent.com/12131831/50222466-4a3ceb80-03d3-11e9-9ff1-471bf8cd5207.png)
点击执行后，只运行一次？

**Comment by ren959** [comment]
刚遇到，本地测试1.9版本升级2.0.1版本会出现这种问题，清理下浏览器缓存就可以了
