### ISSUE TITLE
阻塞策略单机串行任务累加

### ISSUE THREAD

**Issue by liuxiang12138** [xuxueli/xxl-job#684]
阻塞策略里设置了单机串行，有个任务是每分钟执行一次，但是基本上都需要1分3-5秒才能执行完。结果导致正在运行的任务越来越多
![image](https://user-images.githubusercontent.com/12131831/50261992-f8837800-0449-11e9-8f35-8cd4170ab630.png)
点开执行日志后：
![image](https://user-images.githubusercontent.com/12131831/50262172-c58db400-044a-11e9-8f83-99ab4d5ebb2e.png)

**Comment by shubending** [comment]
执行器执行任务不是并发的 最近研究发现了这个问题 有点尴尬

**Comment by Var-iazioni** [comment]
可以修改为并发。

**Comment by xuxueli** [comment]
目前任务单机串行的（单机并发对执行器系统稳定性有损害），并发需要借助执行器集群来实现，或者进行二次开发。

**Comment by huasio** [comment]
请问下，它这个单机串行，是针对每个单独任务内的串行，还是将所有定时任务串行？
