### ISSUE TITLE
希望提供执行器一个心跳失败的回调

### ISSUE THREAD

**Issue by EightMonth** [xuxueli/xxl-job#685]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
永远注册成功
### Actual behavior
注册失败
### Steps to reproduce the behavior
1.布置调度器
2.布置执行器时配置调度器
3.停掉调度器，换个地址布置
这样导致的最终结果就是，执行器因为调度器切换地址，导致执行器无意义，是否可以提供一个心跳失败的回调。
### Other information

**Comment by imkratos** [comment]
个人理解，就算有心跳失败回调，调回哪儿呢 ？ 原先的调度器地址么？ 注册失败了，本身就是和调度中心通讯失败，加个回调有什么作用呢？ 纯讨论。个人认为应该以调度器为中心，而不是执行器。

**Comment by EightMonth** [comment]
我个人已经把xxl-job做了一些改变，加入了spring cloud common组件来适应spring cloud环境，若失败，回调时，重新通过spring cloud common里面DiscoveryClient获取调度器服务的地址，即可响应。

**Comment by xuxueli** [comment]
上述问题，通过一个域名可以搞的定。为调度中心分配一个固定域名即可。
