### ISSUE TITLE
通过tomcat shutDown命令关闭调度中心报内存溢出警告

### ISSUE THREAD

**Issue by yushangjian** [xuxueli/xxl-job#686]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0
### Actual behavior
![qq 20181220160917](https://user-images.githubusercontent.com/28582287/50272274-372d2880-0472-11e9-9780-773e10335cdc.png)

之前没注意到这个警告，直到后面调度中心卡死直接内存溢出了才发现这个问题，每次调用shutDown都会产生这个警告。
20-Dec-2018 16:04:45.555 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [xxlAdmin] appears to have started a thread named [quartzScheduler_Worker-23] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
### Other information

**Comment by xuxueli** [comment]
你好，应该Tomcat关闭策略的问题，可以参考：https://blog.csdn.net/huilixiang/article/details/8730520
