### ISSUE TITLE
使用@Value注解后，项目启动是会报错

### ISSUE THREAD

**Issue by cjyfff** [xuxueli/xxl-job#69]
您好。我在使用的时候遇到一个问题，能不能帮忙看看是什么原因导致呢？十分感谢。
版本：
spring-boot: 1.3.8.RELEASE
xxl-job-core: 1.7.2
我发现当项目中存在@Value注解的时候，项目启动会报错，报错信息为：
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobExecutor' defined in class path resource [applicationcontext-xxl-job.xml]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@465232e9 has not been refreshed yet`
当去掉@Value注解后，项目能正常启动。@Value注解中的内容我能保证是正确的，因为我的项目中在引入xxl-job之前，这些@Value注解一直正常工作。我在xxl-job-executor-springboot-example中也能重现出这个问题。希望能帮忙看看这个问题，再次感谢。

**Comment by xuxueli** [comment]
你是指老项目引入执行器之后，项目之内的@Value注解全部失效了吗？
文件 “applicationcontext-xxl-job.xml” 有改动吗？

**Comment by cjyfff** [comment]
我换了另一台机器发现没有这个问题了，应该是我的IDE设置有问题。谢谢啦～～
