### ISSUE TITLE
任务项不显示启动按钮

### ISSUE THREAD

**Issue by onthewayok** [xuxueli/xxl-job#690]
各位前辈，我按照文档配置好了之后，新增任务之后，没有显示“启动”按钮，但是有“执行”按钮，只能手动执行。不知道是什么情况。我试过v2.0.1、v2.0.0和v1.9.2都是这种情况。
![xxl-job](https://user-images.githubusercontent.com/29566578/50323037-c853dc00-0512-11e9-9617-b522e9144f72.png)

**Comment by xuxueli** [comment]
你好，底层DB存在问题，建议重新初始化DB。
