### ISSUE TITLE
执行器在k8s中的使用场景问题

### ISSUE THREAD

**Issue by jiaoyilun** [xuxueli/xxl-job#692]
我们的服务发布在k8s服务中，k8s的一个特性就是支持伸缩，比如我一个执行器服务，伸缩为多个，那这几个执行器的appName肯定是一样的，这样有没有问题，是否能起到作用呢

**Comment by imkratos** [comment]
其实伸缩为多个的话，建议把注册那边设置为自动注册应该就可以了，这样你的一个执行器，是有多台机器。
