### ISSUE TITLE
xxl-job-admin所在的数据库在重启后服务不能正常重连，需要手动操作开启

### ISSUE THREAD

**Issue by deep3008** [xuxueli/xxl-job#693]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

**Comment by xuxueli** [comment]
问题无法复现，请提供复现步骤。

**Comment by zhaisx** [comment]
出现相同的问题，业务数据库断开或重启后，服务显示正常，所有任务都不能执行，需要手动停止后重启才可以
