### ISSUE TITLE
请问xxl-job-admin现在能支持spring cloud eureka了吗

### ISSUE THREAD

**Issue by Amos-x** [xuxueli/xxl-job#694]
你好，现在项目基本都是spring cloud的了，请问怎样能整合成spring cloud的工程，接入eureka，作为一个微服务来使用？

**Comment by mail6562** [comment]
那个要升级版本的，这个版本比较低

**Comment by apa7** [comment]
可以, 2.x版本

**Comment by xuxueli** [comment]
你好，XXL-JOB 并不依赖第三方组件，功能上并不需要 eureka。

**Comment by yuweiming2016** [comment]
感觉是需要的，直接adminAddresses从注册中心获取，我们开发一般都有很多个环境的，这样不容易乱

**Comment by wangzhengxi** [comment]
@yuweiming2016 @Amos-x @mail6562  
我改了下客户端源码可以支持，请看这个项目https://github.com/wangzhengxi/xxl-job-eureka
