### ISSUE TITLE
任务是否具有有效期

### ISSUE THREAD

**Issue by lemont-sr** [xuxueli/xxl-job#695]
xxljob虽然提供了任务的开始和停止，但觉当任务过期时再发生请求停止任务不太好用。请问下是否能实现在创建定时任务的时候就设置任务的有效期，过期任务自动取消掉

**Comment by Ruffianjiang** [comment]
cron可以设置时间段的，可以多了解一下
部分示例如下：
2018年11月的周五 1点执行
0 0 1 ? 11 5 2018
2018年1月12号到2月12号 每天0、6、18点执行，可以拆成两个任务：
0 0 0,6,18 12-31 1 ? 2018
0 0 0,6,18 1-12 2 ? 2018

**Comment by xuxueli** [comment]
@Ruffianjiang 支持这种做法。有效期概念增加学习成本，暂时不考虑。
