### ISSUE TITLE
XXL_JOB_QRTZ_TRIGGER_REGISTRY表为什么没有索引

### ISSUE THREAD

**Issue by CraneChen** [xuxueli/xxl-job#696]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.8.1
### Expected behavior
 XXL_JOB_QRTZ_TRIGGER_REGISTRY表的registry_group 、registry_key 、registry_value三个字段希望能加索引
### Actual behavior
 XXL_JOB_QRTZ_TRIGGER_REGISTRY表的registry_group 、registry_key 、registry_value三个字段没有索引
### Steps to reproduce the behavior
DB脚本中没有找到建立相关索引的sql
### Other information
调度中心有以下sql操作：
<update id="registryUpdate" >
        UPDATE XXL_JOB_QRTZ_TRIGGER_REGISTRY
        SET `update_time` = NOW()
        WHERE `registry_group` = #{registryGroup}
          AND `registry_key` = #{registryKey}
          AND `registry_value` = #{registryValue}
    </update>
，既然如此，registry_group 、registry_key 、registry_value三个字段应该加上索引，提高数据库操作的性能。

**Comment by Ruffianjiang** [comment]
这是执行器的注册表
1. 执行器服务不会太多，几十个已经很多了
2. 这张表会频繁的增删改

so，没必要去建索引，建索引也只会增加资源消耗

**Comment by xuxueli** [comment]
@Ruffianjiang  正解。
