### ISSUE TITLE
block strategy effect：Discard Later

### ISSUE THREAD

**Issue by dongzehong** [xuxueli/xxl-job#699]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
release 1.9.2

### Steps to reproduce the behavior
日志显示调度结果是失败，调度备注显示：msg：block strategy effect：Discard Later
1天大概有少量的几次这个错误，想知道原因和解决办法。另外在同一个时刻会有一条成功的日志，但是没有设置失败重试。
配置如下：
路由策略：分片广播(0/1)
阻塞处理策略：丢弃后续调度

**Comment by xuxueli** [comment]
你好，你遇到了quartz重复执行的问题，请参考：https://github.com/xuxueli/xxl-job/issues/370
