### ISSUE TITLE
executor部署多个节点之后，配置为故障转移，失败重试次数为0，总有一台机器会调度失败

### ISSUE THREAD

**Issue by patience00** [xuxueli/xxl-job#700]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
admin部署单节点，executor部署多个节点之后，配置为故障转移，失败重试次数为0，总有一台机器会调度失败
### Steps to reproduce the behavior
com.xxl.rpc.util.XxlRpcException: java.net.NoRouteToHostException: No route to host at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:351) at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:185) at org.eclipse.jetty.io.ManagedSelector.access$1200(ManagedSelector.java:60) at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:455) at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:325) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) at java.lang.Thread.run(Thread.java:748) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161) at com.sun.proxy.$Proxy181.run(Unknown Source) at com.vcolco.adas.taskadmin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.vcolco.adas.taskadmin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.vcolco.adas.taskadmin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) 
### Other information

**Comment by xuxueli** [comment]
可以参考：https://blog.csdn.net/xxxx3/article/details/81009597
