### ISSUE TITLE
【最后一个】+【单机串行】出现重复执行的现象

### ISSUE THREAD

**Issue by wangdongjie68** [xuxueli/xxl-job#702]
![image](https://user-images.githubusercontent.com/8454080/50553639-b4179800-0ce5-11e9-92b3-2d98b2e69d4d.png)
![image](https://user-images.githubusercontent.com/8454080/50553643-cf82a300-0ce5-11e9-9c9d-eaa276fa1a26.png)
请问大神，这是什么原因导致的，使用了近一年的xxl-job，第一次出现这种情况

**Comment by qsLI** [comment]
+1

**Comment by xuxueli** [comment]
你好，你遇到了quartz重复执行的问题，请参考：https://github.com/xuxueli/xxl-job/issues/370
