### ISSUE TITLE
能否支持配置指定网卡接口或索引来进行自动获取执行器的注册 IP 地址

### ISSUE THREAD

**Issue by caryyu** [xuxueli/xxl-job#704]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1 

### Expected behavior
根据以下的截图可以看到容器中有两个网卡地址，但我其实想要拿到的地址为：172.21.216.5，即（eth0@if135）

### Actual behavior
执行器注册到调度中心的地址实际用的 IP 地址为：172.31.255.5（eth0@if137）

### Other information
![image](https://user-images.githubusercontent.com/4496641/50625161-28aa3b00-0f61-11e9-8ba7-ec9761a8c26e.png)

@xuxueli

**Comment by xuxueli** [comment]
你好，多网卡时支持手动指定固定IP。

**Comment by caryyu** [comment]
> 你好，多网卡时支持手动指定固定IP。

手动指定没意义，因为实例跑在容器环境，需要利用 IP 地址自动获取功能处理。
