### ISSUE TITLE
http 方式 异步调用业务系统，执行成功后再主动通知调度中心任务执行成功呢？

### ISSUE THREAD

**Issue by 287400117** [xuxueli/xxl-job#705]
如题，我们有一个定时发送优惠券的任务，需要定时调用业务系统发券，但发券的任务执行时间过长，导致http请求超时，然后这个任务就显示失败啦；
可不可以用http 方式 异步调用业务系统，执行成功后再主动通知调度中心任务执行成功呢？

**Comment by 287400117** [comment]
```
- 1、“调度中心”向“执行器”发送http调度请求: “执行器”中接收请求的服务，实际上是一台内嵌jetty服务器，默认端口9999;
- 2、“执行器”执行任务逻辑；
- 3、“执行器”http回调“调度中心”调度结果: “调度中心”中接收回调的服务，是针对执行器开放一套API服务;
```

把上面的“执行器” 换成我们的业务服务就是我想要的功能

**Comment by vipwangtian** [comment]
+1

**Comment by AaronLiang** [comment]
+1 应该支持异步调用，都是io线程，没有必要阻塞。异步调用吞吐量能翻几倍

**Comment by caiwen09** [comment]
+1，确实可以通过http回调调度结果。

**Comment by xuxueli** [comment]
你好，感谢关注，这部分已经加入到TODO规划中。

XXL-JOB会逐渐演进成一种任务调度规范和协议。根据协议规范，第三方可以自行开发自己的执行器实现。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/824
