### ISSUE TITLE
是否可以独立一个 xxl-job-core-api.jar 授权为Apache 授权或LGPL，现在这个GPL授权不太友好

### ISSUE THREAD

**Issue by GuoHuiChen** [xuxueli/xxl-job#707]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by GuoHuiChen** [comment]
已改选其他

**Comment by charlesvhe** [comment]
我们同样有这个诉求

**Comment by xuxueli** [comment]
已统一处理。

合并至：https://github.com/xuxueli/xxl-job/issues/1033

**Comment by change-ljf** [comment]
> 

您好，最近我也遇到了相似的问题，对于这么好的框架因为协议的问题放弃确实有点可惜。请问您最终选择了哪款框架呢？
