### ISSUE TITLE
调度器地址获取不正确

### ISSUE THREAD

**Issue by cjj137783** [xuxueli/xxl-job#709]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?   
1.9.2

### Expected behavior  
正确完成定时调度

### Actual behavior
1、定时调度的时候，有时候能获取到正确的调度器ip，有时候不能
2、手动执行的时候都能获取到调度器的ip  
(是调度器的ip，不是执行器的ip)

### Other information
网络状况没有任何问题，因为手动执行的时候，每次都能成功，而我每隔3分钟
定时调度一次，就会存在大几率失败的情况，有时候也会成功，我查看了调度器
的ip，发现失败的时候调度器的ip是另外一个莫名奇妙的ip地址，不是我本身admin机子的ip,
我这边是通过docker安装的，谢谢

以下分别是成功和失败的控制台截图，注意调度器ip是不一样的
![default](https://user-images.githubusercontent.com/12795327/50754342-6c1de580-1290-11e9-8cb0-475cef655eeb.jpg)

![default](https://user-images.githubusercontent.com/12795327/50754354-73dd8a00-1290-11e9-8be5-840d2f8b16e6.jpg)

**Comment by cjj137783** [comment]
已解决，部署了多个容器在不同的环境（运维同学的锅，他自己都不知道这个环境的存在），连接的同一个数据库，由于网络问题，导致另一个环境连不上我的执行器，故每当从另一个环境发起调用的时候，就提示连接超时

**Comment by ioiioo** [comment]
@cjj137783  咨询下你的执行器也是部署到Docker中的吗？ 调度中心如何找到 执行器来调度任务呢?

**Comment by xuxueli** [comment]
@cjj137783 赞！通过调度备注里的调度机器IP就可以定位，是两个不同的调度中心的发起调度请求，其中一个网络有问题。
