### ISSUE TITLE
能否增加“任务批次”功能?

### ISSUE THREAD

**Issue by betterdanielding** [xuxueli/xxl-job#710]
我们需要调度的任务有上千个，希望能将任务分到不同的批次里执行，这样只需要管理十几个批次，对批次设置调度时间和前后依赖关系。这个功能有计划支持吗？谢谢

**Comment by lindingjiao** [comment]
我们也有类似需求

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
