### ISSUE TITLE
xxl-job控制台点击任务暂停，执行器执行的任务有没有取消或者暂停？

### ISSUE THREAD

**Issue by Moving521** [xuxueli/xxl-job#712]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Moving521** [comment]
xxl-job控制台点击任务暂停，执行器执行的任务有没有取消或者暂停？

看您的代码，没有对执行器正在执行的任务进行取消或者暂停的操作。
/**
     * pause
     *
     * @param jobName
     * @param jobGroup
     * @return
     * @throws SchedulerException
     */
    public static boolean pauseJob(String jobName, String jobGroup) throws SchedulerException {
    	// TriggerKey : name + group
    	TriggerKey triggerKey = TriggerKey.triggerKey(jobName, jobGroup);
        
        boolean result = false;
        if (checkExists(jobName, jobGroup)) {
            scheduler.pauseTrigger(triggerKey);
            result = true;
            logger.info(">>>>>>>>>>> pauseJob success, triggerKey:{}", triggerKey);
        } else {
        	logger.info(">>>>>>>>>>> pauseJob fail, triggerKey:{}", triggerKey);
        }
        return result;
    }

**Comment by Moving521** [comment]
`/**
* pause
*
* @param jobName
* @param jobGroup
* @return
* @throws SchedulerException
*/
public static boolean pauseJob(String jobName, String jobGroup) throws SchedulerException {
// TriggerKey : name + group
TriggerKey triggerKey = TriggerKey.triggerKey(jobName, jobGroup);

    boolean result = false;
    if (checkExists(jobName, jobGroup)) {
        scheduler.pauseTrigger(triggerKey);
        result = true;
        logger.info(">>>>>>>>>>> pauseJob success, triggerKey:{}", triggerKey);
    } else {
    	logger.info(">>>>>>>>>>> pauseJob fail, triggerKey:{}", triggerKey);
    }
    return result;
}`

**Comment by pencilso** [comment]
我也遇到了

**Comment by walyuuc** [comment]
https://blog.csdn.net/varyall/article/details/79981299
interrupt并不会中断线程

**Comment by Moving521** [comment]
> 我也遇到了



> https://blog.csdn.net/varyall/article/details/79981299
> interrupt并不会中断线程

所以就不做任务暂停或者中断了？这样假如一个参数错了，任务运行时间太久，除了重启执行器所在的服务，就没有别的办法了？

**Comment by Moving521** [comment]
能不能基于暂停，取消 事件，JobHandler做接口，让业务方自己实现。

**Comment by xuxueli** [comment]
任务暂停支持停止了任务的后续触发。
运行中的任务终止，可以到任务日志界面点击 ”终止任务“ 按钮操作。

任务终止借助线程中断实现，所以业务逻辑里不可以catch InterruptedException ，这部分文档有说明。
