### ISSUE TITLE
misfire策略优化

### ISSUE THREAD

**Issue by walyuuc** [xuxueli/xxl-job#713]
期望可以在job添加界面，增加misfire策略的选择，而不是用代码中默认的nothing
withMisfireHandlingInstructionFireAndProceed
withMisfireHandlingInstructionDoNothing
withMisfireHandlingInstructionIgnoreMisfires
场景：
定期清理类，适合fireAndProceed，执行一次就行
严格执行任务比较适合ignore
非严格执行任务比较适合nothing，错过也没事

**Comment by xuxueli** [comment]
感谢反馈！
上述特性通用性较低，建议自行灵活定制。
