### ISSUE TITLE
1.9.2和2.0.0 版本升级的问题

### ISSUE THREAD

**Issue by dpdawy** [xuxueli/xxl-job#714]
我们的项目现在刚开始使用 1.9.2的版本并接入一部分执行器进行试点，但是我发现1.9.2版本升级非常麻烦，不能无缝升级到更高的版本，我想知道2.0.0版本开始，以后再往高版本升级的时候是否可以无缝升级或者说能够支持2.0.0以上的低版本的客户端，如果可以我想趁现在接入的执行器客户端还比较少的时候，先升级到2.0.0版本，请大神指教

**Comment by xuxueli** [comment]
你好，大版本升级会有兼容性问题。建议等待2.0.2后升级，届时通讯组件趋于稳定。
