### ISSUE TITLE
2.0.1版本的xxl-job在30秒执行一次时报EofException

### ISSUE THREAD

**Issue by magicFire** [xuxueli/xxl-job#715]
我正在使用2.0.1版本的xxl-job，调度中心去调度执行器执行任务时，30秒调度一次会频繁报出EofException相关的错误，报错率在5%左右，但是10秒、15秒、20秒、1分钟执行一次就没有这样的报错。考虑到心跳的间隔也是30S，有没有可能是任务的时间间隔和心跳周期一致的时候，会存在特殊的异常。报错的调度详情如下：

任务触发类型：Cron触发
调度机器：172.25.240.2
执行器-注册方式：自动注册
执行器-地址列表：[172.25.188.2:9990]
路由策略：轮询
阻塞处理策略：单机串行
任务超时时间：5
失败重试次数：2

触发调度：
address：172.25.188.2:9990
code：500
msg：com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@1ed6582c(l:/172.25.240.2:36644 <-> r:/172.25.188.2:9990,closed=false)[HttpChannelOverHTTP@a36c085(exchange=HttpExchange@45af4f83 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@788d4532(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@2ba1373(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]] at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277) at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1305) at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182) at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129) at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69) at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90) at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:748) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161) at com.sun.proxy.$Proxy75.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748)

**Comment by EthanMrZhang** [comment]
me too ...

**Comment by Ruffianjiang** [comment]
用的2.0.2目前没遇到，不过期待能集成注册中心

**Comment by EthanMrZhang** [comment]
最高2.0.1啊 你在哪下载的2.0.2

**Comment by Ruffianjiang** [comment]
> 最高2.0.1啊 你在哪下载的2.0.2

2.0.2-SNAPSHOT

**Comment by naturn** [comment]
据说是因为Jetty 客户端和服务器端的idletime设置了相同的值,给的建议是idletime服务器值大于客户端的值,不要用默认值.相关链接
http://jetty.4.x6.nabble.com/Fwd-occasional-earlyEOF-exceptions-td4966836.html

**Comment by xuxueli** [comment]
建议采用Release版本，并且Jetty版本同core包的 ”jetty-server.version“ 保持一致，调度中心与执行器均一致。

最新迭代版本已经废弃Jetty，通讯层默认选型Netty，将会跟随下个版本一同推出，可以pull master分支体验下。
