### ISSUE TITLE
xxl could not be killed

### ISSUE THREAD

**Issue by guodage** [xuxueli/xxl-job#717]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-core 2.0.2
### Expected behavior
kill <pid> successfully
### Actual behavior
sometimes xxl-executer which running several hours could not be killed.
### Other information
anyone meet this?
I've added some code to make xxl-executer which be killing can't accept xxl-admin's dispatching.
But the one not be killed is still running and print `registry success` log.

![image](https://user-images.githubusercontent.com/5564268/50981333-b5db2a00-1535-11e9-9d72-d3bef56d858d.png)

**Comment by xuxueli** [comment]
Hello, the problem cannot be repeated. Please describe the problem again and submit it
