### ISSUE TITLE
建议执行器和调度器可以独立升级

### ISSUE THREAD

**Issue by lollipok** [xuxueli/xxl-job#718]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v1.9.0

### Expected behavior
执行器保持 v1.9.0, 调度器升级到 v1.9.2，希望调度器能够兼容低版本的执行器，因为是分布式任务调度，执行器有许多，而且由不同开发组维护，不能保证每个执行器都可以同步升级。

### Actual behavior
Rpc 序列化错误

### Other information

**Comment by xuxueli** [comment]
你好，v1.9与v2.0通讯组件变更较大，需要升级。

**Comment by huangdezhou008** [comment]
2.1.0升级到2.3.0，这样的版本升级的话，执行器和调度器，需要同时升级吗
