### ISSUE TITLE
福建阿思可网络教育有限公司

### ISSUE THREAD

**Issue by Lenilying** [xuxueli/xxl-job#72]
www.91asking.com

xxl-job-admin和xxl-job-executor-springboot-example容器话部署，xxl-job的路由策略和docker swarm mode的replicas模式结合，挺灵活实用的

**Comment by Lenilying** [comment]
希望分布式任务调度系统产品越做越好，秉持好 开箱即用 的理念

**Comment by xuxueli** [comment]
赞！感谢关注和信任 ：）
XXL系列会拥抱变化，持续发展，Burning~
