### ISSUE TITLE
2.0.1 是否支持spring boot2.0.8

### ISSUE THREAD

**Issue by RongXiong2016** [xuxueli/xxl-job#720]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by lyliyongblue** [comment]
看了源码，调度中心、执行器demo的都是基于springboot 1.5.18的，但是这不影响你使用其他版本的springboot构建你的其他执行器，因为正常情况下你不会修改调度中心的代码。

**Comment by xuxueli** [comment]
@lyliyongblue  正解。

**Comment by likenamehaojie** [comment]
调度器是没有问题，但是执行器在注册的时候使用netth-http 出错
