### ISSUE TITLE
aop 拦截job 

### ISSUE THREAD

**Issue by gyjx** [xuxueli/xxl-job#721]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

1.9.1

### Expected behavior
集成Spring aop 拦截所有job
### Other information
使用spring aop 拦截所有job，发现无法拦截

**Comment by xuxueli** [comment]
你好，XXL-JOB 底层是frameless的，并不受spring管理，如需拦截需要在内部代码中定制。
