### ISSUE TITLE
这个不支持多个上游任务执行成功后才触发下游任务吗？

### ISSUE THREAD

**Issue by cysjtu** [xuxueli/xxl-job#722]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by qiuxin** [comment]
新建任务的对话框里面，可以关联其它的任务ID，看看是否可以满足你的要求

**Comment by dzyok** [comment]
我也想问一下，这个没有前置条件定时任务，比如我一个任务：依赖很多其它的定时任务，就想其它任务执行成功了，在马上执行它

**Comment by Kiddinglife** [comment]
@dzyok  you can try airflow.

**Comment by lyliyongblue** [comment]
我觉得这个可以在以后的版本中晚上，现在的任务链配置，只能二叉树的形式不断的延伸，子任务的执行不能依赖1个以上任务执行成功

**Comment by bugmeng** [comment]
这个缺陷确实比较的大，竟然不支持多父节点

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
