### ISSUE TITLE
配置cron后，任务没有按照定时的时间执行？

### ISSUE THREAD

**Issue by qiuxin** [xuxueli/xxl-job#723]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
配置cron为0 0,30 0/1 * * ? ， 期望每30分钟执行一次
### Actual behavior
未执行
### Other information

**Comment by qiuxin** [comment]
已经解决

**Comment by qiuxin** [comment]
已经解决

**Comment by DeliciousOrange** [comment]
怎么解决的？我配置的定时任务0 56 15 ? * 2，总是未执行
