### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by light0x00** [xuxueli/xxl-job#725]
### 1. 连接池配置
因为在线上发现连接池中存在已经被回收的连接,导致无法连接mysql,看了一下admin-ui的配置, 发现可能需要加上下面两行
```
spring.datasource.tomcat.test-on-borrow=true
# 验证语句
spring.datasource.tomcat.validationQuery=SELECT 1
# 验证间隔(单位ms)
spring.datasource.tomcat.validationInterval=30000
```

### 2. 异常处理
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/29830476/51160926-2fbf3a80-18cb-11e9-828b-7c511faa622a.png">

查看admin-ui的运行日志 发现这里可能需要判断一下类型( 有静态资源无法加载的时候也会触发下面的代码)
<img width="647" alt="image" src="https://user-images.githubusercontent.com/29830476/51160821-bcb5c400-18ca-11e9-960a-d5a861002b6f.png">

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/29830476/51160924-2df57700-18cb-11e9-94f5-97542ce8c50d.png">

**Comment by xuxueli** [comment]
你好，问题1已经进行修复，将会跟随下个版本一同发布。

但是问题2并未复现，可否将复现步骤完整描述下？方便的话可以一并提供修复的PR啊。
