### ISSUE TITLE
内网测试环境 触发执行Network request error: Connect to x.x.x.x:9998 failed: connect timed out

### ISSUE THREAD

**Issue by 377262688** [xuxueli/xxl-job#726]
手动执行可以调用成功，自动触发执行只有很少的会成功，大部分都会报错：java.lang.RuntimeException: Network request error: Connect to failed: connect timed out

**Comment by xuxueli** [comment]
你好，手动与Cron触发逻辑一致，可以debug跟踪或者加log确认下，是不是网络抖动导致。
