### ISSUE TITLE
xxl-job执行器导致停止服务时无法正常结束进程

### ISSUE THREAD

**Issue by qsjia** [xuxueli/xxl-job#727]
### Which version of XXL-JOB do you using?
2.0.1和2.0.2-SNAPSHOT

停止服务时，调用XxlJobExecutor.destroy()，执行到xxl-rpc的XxlRpcInvokerFactory.stop()方法, 先销毁了httpclient，然后才执行ExecutorRegistryThread里面的取消服务注册，导致又重新创建了httpclient而没有销毁，造成进程无法退出。

**Comment by guodage** [comment]
持续关注

**Comment by Cyanist26** [comment]
尝试整合到SpringBoot2的项目中时，也是因为XxlRpc的原因无法优雅停机，放弃了

**Comment by xuxueli** [comment]
最新迭代版本 v2.0.2 已经升级 xxl-rpc 至最新版本。已经解决了上述问题，将会跟随下个版本一同发布，可以pull master分支体验下。
