### ISSUE TITLE
web后台统计问题

### ISSUE THREAD

**Issue by imkratos** [xuxueli/xxl-job#728]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.0
### Expected behavior
首页统计慢
### Actual behavior
首页统计正常
### 
当定时任务执行数量过多之后，由于表里数据过多，几百万级别的时候，首页统计会特别慢，我们生产系统现在每天执行3W次左右。
现在的解决办法是手动删除一个月之前的日志。并且发现另外一个问题，由于日志表数据过大，当删除的时候是根据创建时间字段来删除的，所以，导致删除也很慢。希望可以优化。
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/596
