### ISSUE TITLE
子任务-调度日志-优化建议

### ISSUE THREAD

**Issue by lyliyongblue** [xuxueli/xxl-job#730]
### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT

### Expected behavior
关联子任务执行的整个调度日志按照一定的关联关系进行关联展示

### Actual behavior
在调度日志中分别展示了每一个独立的子任务执行结果，无法很明确的看出子任务的关联关系

### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/331
