### ISSUE TITLE
是否支持spring5？

### ISSUE THREAD

**Issue by zhentao1123** [xuxueli/xxl-job#733]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Other information

**Comment by bugmeng** [comment]
不支持，不过看后续版本迭代计划，好像应该是下个版本就支持了，不过又要等到猴年马月

**Comment by xuxueli** [comment]
感谢反馈！
spring版本向下兼容，支持spring5构建使用的。
