### ISSUE TITLE
在进行分片操作的时候，并不能知道是哪个服务进行调度的

### ISSUE THREAD

**Issue by mrxlh** [xuxueli/xxl-job#734]
在进行分片操作的时候，并不能知道是哪个服务进行调度的，不知是否可以支持？

**Comment by imkratos** [comment]
可以通过查看自带的那个日志来区分，目前就是这种状态吧。

**Comment by xuxueli** [comment]
可以根据调度日志的 ”调度备注“ 属性查看，相关调度机器、执行器机器等信息均有记录。
