### ISSUE TITLE
用 spring-boot 的 HTTP shutdown 请求来关闭应用时无法优雅停机

### ISSUE THREAD

**Issue by ldcsaa** [xuxueli/xxl-job#736]
版本：2.0.1
两个问题（如下图）：
1、用 spring-boot 的 HTTP shutdown 请求（http://${host}:${port}/_admin/shutdown）来关闭应用时无法优雅停机，进程不能结束
2、应用退出时，JettyServer.stop() 方法执行两次

![image](https://user-images.githubusercontent.com/5990337/51800509-bdefd500-226a-11e9-8b4b-0935d45b77e6.png)

**Comment by xuxueli** [comment]
你好，最新迭代版本已经做了大量优化，修复了该问题，将会跟随下个版本一同发布。可以参考master分支体验下。
