### ISSUE TITLE
关闭应用程序时总是报ERROR异常，影响报警和绩效分析

### ISSUE THREAD

**Issue by ldcsaa** [xuxueli/xxl-job#737]
如下图：
1、如果是正常情况的话麻烦把日志级别修改为INFO或WARN，同时去掉异常堆栈。
2、JettyServer.stop() 方法重复执行。
![image](https://user-images.githubusercontent.com/5990337/51800581-24292780-226c-11e9-8457-9d47334c1f7d.png)

**Comment by xuxueli** [comment]
你好，感谢反馈！
最新迭代版本已经做了相关优化，将会跟随下个版本一同发布。
