### ISSUE TITLE
为什么XxlJobExecutor里的ip port属性不提供get的方法.

### ISSUE THREAD

**Issue by cikeJonas** [xuxueli/xxl-job#738]
![tim 20190130105208](https://user-images.githubusercontent.com/10081824/51955131-ac324b80-247d-11e9-9fdc-97bcdd6d15e1.jpg)

**Comment by cikeJonas** [comment]
无法自定义JobExecutor

**Comment by xuxueli** [comment]
你好，暂时没有发现目标场景，可否告知？
