### ISSUE TITLE
docker模式发布，历史日志由于镜像释放丢失

### ISSUE THREAD

**Issue by freegodo** [xuxueli/xxl-job#739]
Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT

采用docker模式发布。由于执行日志在执行器服务镜像中。新的发布时，由于旧镜像释放。物理日志随之丢失。
建议将日志可配置存储方式，DB模式支持存储到DB中。避免docker化发布造成的日志文件丢失。

**Comment by xuxueli** [comment]
你好，Rolling Log日志量太大，不建议存储到DB中。建议通过挂载磁盘的方式输出到外部磁盘中。
