### ISSUE TITLE
输出日志乱码

### ISSUE THREAD

**Issue by shenjler** [xuxueli/xxl-job#741]
Please answer some questions before submitting your issue. Thanks!

### Expected behavior
正常日志输出
### Actual behavior
python任务日志输出乱码
### Steps to reproduce the behavior
windows下，执行器与调度机器是同一台。python任务。

**Comment by shenjler** [comment]
![error](https://user-images.githubusercontent.com/4507904/52253409-a5567d80-2942-11e9-9b0b-ec844691e438.png)

**Comment by shenjler** [comment]
![image](https://user-images.githubusercontent.com/4507904/52253513-49402900-2943-11e9-9382-328868b04f31.png)

**Comment by xuxueli** [comment]
你好，问题无法复现，请提供版本以及测试代码信息。

**Comment by adam-lsc** [comment]
我也看到类似问题。 
xxl版本：xxl-job-2.0.1
os: windows7
python版本：3.7.1
glue(python)代码：

#!/usr/bin/python
# -*- coding: UTF-8 -*-
import time
import sys
print ("中文乱码吗？")
exit(0)

**Comment by vampniklaus** [comment]
同样问题求解决

**Comment by chenqiang1121** [comment]
我们这里也有同样的问题，看日志文件里面的中文还是正常的。接口是utf-8的格式输出。 但是中文就是显示 ?????,数字和英文正常

**Comment by chenqiang1121** [comment]
环境是java

**Comment by bobo325** [comment]
是的，我们这边用的xxl，也存在着中文乱码问题
![图片](https://user-images.githubusercontent.com/18496636/102595461-9356e000-4152-11eb-8cbd-2ad9b82cdb5a.png)
