### ISSUE TITLE
Sharding of Jobs to different executors

### ISSUE THREAD

**Issue by omkar1707** [xuxueli/xxl-job#742]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0..2-snapshot

### Expected behavior
I have 1000 jobs which will run every 5 min. I have one admin and two executor instance running on two servers. Is there a way that 1000 jobs will be automatically distributed across the executors. 
For example. 500 jobs will run on executor 1 and 500 will run on the executor 2

### Other information

**Comment by bugmeng** [comment]
自己写策略算法吧。

**Comment by omkar1707** [comment]
Can you share a simple example lets say if I have 2 executor instance and job with even id will go to executor 1 and job with odd id will go to executor 2?

**Comment by xuxueli** [comment]
You can choose "Block Strategy" called "CONSISTENT_HASH", that can hash tasks evenly across multiple machines
