### ISSUE TITLE
是否支持父任务执行后，启动子任务，而不是执行一次任务，或者是否支持从某个时刻开始才需要执行？

### ISSUE THREAD

**Issue by Xifeng** [xuxueli/xxl-job#743]
想要实现在未来某个时刻开始，每隔一定时间执行一次任务的功能。（从某个时刻开始才需要执行）

做法是通过设置两个任务，一个父任务，一个子任务。

父任务，设置一个具体的时间 如： 0 0 12 28 2 ? 2019   在2019年1月31日12点执行父任务

子任务，开始规律性的执行一段任务。如： 0/15 * * * * ? * 每隔15s执行一次任务

**Comment by xuxueli** [comment]
你好，上述场景通用性较低，建议自定定制实现。
