### ISSUE TITLE
请问 2.0.2版本计划什么时候发布？

### ISSUE THREAD

**Issue by ldcsaa** [xuxueli/xxl-job#744]
请问 2.0.2版本计划什么时候发布？

**Comment by bugmeng** [comment]
更新开发版，打包就是2.0.2

**Comment by ldcsaa** [comment]
> 更新开发版，打包就是2.0.2

不是正式版，不敢用了~

**Comment by bugmeng** [comment]
> > 更新开发版，打包就是2.0.2
> 
> 不是正式版，不敢用了~

不会用于生产吧，生产正式版你敢用？可能也就用常用功能吧

**Comment by xuxueli** [comment]
Release版本预计会在本季度发布，正在处理本迭代周期内的需求收尾工作。

**Comment by xuxueli** [comment]
预计本周发布；
