### ISSUE TITLE
当调度中心未启动时,在注册时失败导致应用无法启动

### ISSUE THREAD

**Issue by cikeJonas** [xuxueli/xxl-job#746]
当调度中心没启动时,应该在注册失败后停止注册,从而不影响应用的启动和其他业务.
![error](https://user-images.githubusercontent.com/10081824/52684220-75315f00-2f80-11e9-9712-bba6588d0362.jpg)

**Comment by xuxueli** [comment]
你好，问题无法复现。注册失败并不影响应用启动，仅仅输出响应故障日志。
