### ISSUE TITLE
关于同一调度并发执行

### ISSUE THREAD

**Issue by zhoupeng9101** [xuxueli/xxl-job#748]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
同一调度任务能并行
### Actual behavior
只有串行，覆盖和丢弃
### Other information
spark任务本来设置的就是FAIR公平调度，现在一个调度没跑完下一个任务启动不了，这是个很头疼的问题，希望在串行，覆盖和丢弃基础之上能提供一个并行的选项

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/666
