### ISSUE TITLE
v1.9.1  升级v2.0.1

### ISSUE THREAD

**Issue by hailongwu** [xuxueli/xxl-job#749]
目前使用版本
v1.9.0

现在在升级V2.0.1,由于做了二次开发，升级改动点比较多。
数据库变动明细也没有看到在哪，需要一个个表核对字段。
花了一天时间把代码合并完了，启动不了。

升级好累。。。

下面有行代码，不应该写在for循环里面吧？
![image](https://user-images.githubusercontent.com/5811118/52768130-83a67600-3067-11e9-8ee6-b56caa888835.png)

**Comment by bugmeng** [comment]
国内软件一个人维护太困难了，还不如交给开源组织

**Comment by imkratos** [comment]
我这都不敢升级2.0.。。 连通讯协议都变了。。。 没有特别好的办法来优雅升级

**Comment by bugmeng** [comment]
> 我这都不敢升级2.0.。。 连通讯协议都变了。。。 没有特别好的办法来优雅升级

我刚接触，不知道这块，以前是啥协议？现在么？不知道该不该入坑

**Comment by hailongwu** [comment]
> 我这都不敢升级2.0.。。 连通讯协议都变了。。。 没有特别好的办法来优雅升级

已经放弃升级了，各业务方都的同时跟着升级，这个比较坑，准备重新搭建V2.0.1版本供新业务使用。

**Comment by imkratos** [comment]
@hailongwu 恩，我这边也是，打算，重新搭建2.X版本，但是那些定时任务迁移是个问题。。。直接倒表不行的，有的不兼容。。。近100个任务难道要重新配置吗。。。

**Comment by xuxueli** [comment]
@imkratos 你好，任务升级DB数据升级比较方便的。先备份DB数据，然后对比两个版本建表SQL做调整即可，通常高版本仅变更少量字段，调整之后设置默认值即可。上述代码已经调整，会跟随下个小版本一同发布；
