### ISSUE TITLE
The POM for com.xuxueli:xxl-job-core:jar:2.0.2-SNAPSHOT is missing, no dependency 

### ISSUE THREAD

**Issue by bugmeng** [xuxueli/xxl-job#750]
Please answer some questions before submitting your issue. Thanks!

### Other information

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building xxl-job-admin 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.xuxueli:xxl-job-core:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.395 s
[INFO] Finished at: 2019-02-14T11:43:00+08:00
[INFO] Final Memory: 15M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xxl-job-admin: Could not resolve dependencies for project com.xuxueli:xxl-job-admin:jar:2.0.2-SNAPSHOT: Could not find artifact com.xuxueli:xxl-job-core:jar:2.0.2-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

**Comment by bugmeng** [comment]
解决了

**Comment by QuanmetaStudio** [comment]
怎么解决的
