### ISSUE TITLE
一个任务连续执行2次

### ISSUE THREAD

**Issue by liuxiang12138** [xuxueli/xxl-job#751]
![image](https://user-images.githubusercontent.com/12131831/52835472-806fc080-3121-11e9-996a-f75276d9ac49.png)
![image](https://user-images.githubusercontent.com/12131831/52835480-88c7fb80-3121-11e9-999c-1b07a448bf77.png)

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/370
