### ISSUE TITLE
docker pull失败

### ISSUE THREAD

**Issue by tzxylao** [xuxueli/xxl-job#752]
[root@izbp1itlw36onyj4m9b4hiz docker-xxl-job]# docker pull xuxueli/xxl-job-admin
Using default tag: latest
Trying to pull repository docker.io/xuxueli/xxl-job-admin ... 
manifest for docker.io/xuxueli/xxl-job-admin:latest not found

docker执行命令失败

**Comment by xuxueli** [comment]
你好，docker pull 尽量指定版本号啊；

**Comment by tzxylao** [comment]
[root@izbp1itlw36onyj4m9b4hiz ~]# docker pull xxl-job-admin
Using default tag: latest
Trying to pull repository docker.io/library/xxl-job-admin ... 
repository docker.io/xxl-job-admin not found: does not exist or no pull access
[root@izbp1itlw36onyj4m9b4hiz ~]# docker pull xxl-job-admin:v1.3
Trying to pull repository docker.io/library/xxl-job-admin ... 
repository docker.io/xxl-job-admin not found: does not exist or no pull access
[root@izbp1itlw36onyj4m9b4hiz ~]# docker pull xxl-job-admin:v1.9.2
Trying to pull repository docker.io/library/xxl-job-admin ... 
repository docker.io/xxl-job-admin not found: does not exist or no pull access
[root@izbp1itlw36onyj4m9b4hiz ~]# docker pull xxl-job-admin:1.9.2
Trying to pull repository docker.io/library/xxl-job-admin ... 
repository docker.io/xxl-job-admin not found: does not exist or no pull access
[root@izbp1itlw36onyj4m9b4hiz ~]# docker pull xxl-job-admin:v1.7
Trying to pull repository docker.io/library/xxl-job-admin ... 
repository docker.io/xxl-job-admin not found: does not exist or no pull access

大神，要不你自己docker拉下看，是不是失效了

**Comment by xuxueli** [comment]
可以尝试：docker pull xxl-job-admin:2.0.1 

（从 2.0.0 开始才推送dockerhub仓库）

**Comment by xuxueli** [comment]
你好，需要加上namespace：docker pull xuxueli/xxl-job-admin:2.0.1
