### ISSUE TITLE
无法解析xxl-rpc 1.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by zhouzach** [xuxueli/xxl-job#753]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT
### Expected behavior
maven解析xxl-rpc 1.3.2-SNAPSHOT
### Actual behavior
maven 不能解析xxl-rpc 1.3.2-SNAPSHOT
### Other information

**Comment by xuxueli** [comment]
你好，快照版本及相关依赖未推送中央仓库，推荐使用正式Release版本。

**Comment by zhouzach** [comment]
@xuxueli 感谢回复，我从github直接拉到项目，回溯到版本v1.9.2还是不行，回溯到v1.8.2可以了

**Comment by xuxueli** [comment]
快照版本未推送不建议使用。
除此之外，最新Release版本都可以的（ https://github.com/xuxueli/xxl-job/releases ），版本 v2.0.1 及以下。
先清空本地maven依赖缓存，重新编译下。
