### ISSUE TITLE
日志显示问题

### ISSUE THREAD

**Issue by crazy-91Q** [xuxueli/xxl-job#754]
任务执行时日志正常显示，任务执行完成后重新查看日志，页面只显示[Load Log Finish]

**Comment by xuxueli** [comment]
你好，问题无法复现。确认执行器侧对应日志文件是否被删除，可以在执行器测debug下日志加载逻辑。

**Comment by XiaoShunjie** [comment]
我也遇见了同样的问题。
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
执行器运行日志文件存储磁盘路径

![image](https://user-images.githubusercontent.com/26452003/55385770-7a626180-5560-11e9-96d7-9a9978f11e46.png)

就现象来看，日志文件超过2MB，就会出现[Load Log Finish]

**Comment by zouweijava** [comment]
有啥解决方案吗，清除日志？

**Comment by QQK000** [comment]
加一，logID超过1000会报转换错误，出现Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: "1,011"]，字符串含逗号

**Comment by QQK000** [comment]
> 
解决方案：
joblog.detail.ftl文件下修改var logId = '${logId}';为var logId = '${logId?c}';即可，防止前端加逗号
