### ISSUE TITLE
standardize the sql script

### ISSUE THREAD

**Issue by wkclz** [xuxueli/xxl-job#758]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
- v 2.0.1
### Expected behavior
- tables_xxl_job.sql,  named the database name as underline.
- tables_xxl_job.sql, set all tables 'ENGINE=InnoDB DEFAULT CHARSET=utf8'
### Actual behavior
- Named the database name middle line
- In an existing database, can not execute the sql script with index error, and must set the engine as InnoDB
### Steps to reproduce the behavior
- NaN
### Other information
- Just standardize the code, and improving using experience.

**Comment by xuxueli** [comment]
Hello,SQL has been optimized, please upgrade v2.1.x to experience

**Comment by xuxueli** [comment]
Hello,SQL has been optimized, please upgrade v2.1.x to experienceHello,SQL has been optimized, please upgrade v2.1.x to experience
