### ISSUE TITLE
执行器IP变化后，自动注册时IP不更新

### ISSUE THREAD

**Issue by billytomato** [xuxueli/xxl-job#759]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior
期望：执行器不重启，但是执行器所在的网络发生变化，执行器自动注册时自动更新
### Actual behavior
实际：执行器不重启，但是执行器所在的网络发生变化，IP地址变了，执行器自动注册时，使用的是老ip
### Steps to reproduce the behavior
1.启动执行器，自动注册到调度中心;
2.测试调度正常；
3.更改执行器所在机器的IP，观察执行器日志，发现执行器依然以老IP注册；
4.测试调度异常，因为调度器通过老IP调度

**Comment by bugmeng** [comment]
我也遇到了，新IP会新加进去，老的IP不会消失，可能是容错的一种方式吧，最好做成看的时候能显示多执行器服务状态的情况

**Comment by xuxueli** [comment]
@billytomato 目前系统IP为单例方式获取，性能优先。如切换IP推荐重启应用。

@bugmeng 过期地址存在一定延时，默认连续3次心跳失败会被自动摘除。
