### ISSUE TITLE
任务分片如何做？怎么保证执行器不重复执行任务呢？有demo吗？

### ISSUE THREAD

**Issue by beelzebub2006** [xuxueli/xxl-job#76]
任务分片如何做？怎么保证执行器不重复执行任务呢？有demo吗？

**Comment by xuxueli** [comment]
在当前版本（v1.7.2）中，分片是通过任务参数实现的，业务通过任务参数确认分片。每次调度对应一条可追踪Log，可保证只执行一次。

**Comment by wuyanfei123** [comment]
@xuxueli 请问分片的具体用法能介绍一下吗，比如参数的配置格式？JobHandler里面的execute函数又需要如何解析？  十分感谢^.^

**Comment by xuxueli** [comment]
你好，可以参考官网文档：http://www.xuxueli.com/xxl-job/  （章节：5.9 分片广播 & 动态分片 ）

**Comment by Gao92** [comment]
@xuxueli 这个广播分片的意思就是，需要在具体执行器里面进行参数的过滤，对不属于当前执行器分片的数据进行忽略，可以这样理解吗
