### ISSUE TITLE
功能做的应该挺不错，但是代码写的极度不规范，实话实说

### ISSUE THREAD

**Issue by pan-common** [xuxueli/xxl-job#761]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by pan-common** [comment]
改sql兼容多数据库改的头都大了

**Comment by xuxueli** [comment]
感谢反馈！
有好的建议欢迎PR啊。

**Comment by jaoyina** [comment]
> 改sql兼容多数据库改的头都大了

兄弟你改了支持其他数据库了？能分享下吗？
