### ISSUE TITLE
本地调用 远程服务器部署的任务调度中心 超时（一定要同一网段吗）

### ISSUE THREAD

**Issue by miaojf** [xuxueli/xxl-job#762]
请问 我的客户端 注册成功了、本机 jobhandler 也显示注册成功 xxl-job register jobhandler success

为什么 任务执行总是调用超时呢？

xxl-job 是部署在阿里云上的，我本机是在本地调试。
能支持其他形式如长连接调度吗？

![image](https://user-images.githubusercontent.com/10215067/53297428-b61b5480-3859-11e9-85b5-94ad1962d48e.png)

![image](https://user-images.githubusercontent.com/10215067/53297577-4ad28200-385b-11e9-9f14-d4091b5c3718.png)

**Comment by zhaofutao** [comment]
这是因为调度的ip是172.17.0.1，如果可以通过强制绑定ip地址解决

**Comment by miaojf** [comment]
多谢，
请问是 xxl.job.executor.ip=  配置吗？这个好像是执行器的，是在我本地的，没有对外可以访问的公网ip，


我感觉 172.17.0.1 是调度平台的 ip，在阿里云，请问是指定这个吗？在哪里配置？ 改成公网ip吗？

**Comment by xuxueli** [comment]
调度要成功，需要调度机器ping执行器机器网络没问题，你上面的问题，本机必须要一个外部端口供阿里云访问才可以。
