### ISSUE TITLE
Enhancement in CONSITENT HASHING Algorithm

### ISSUE THREAD

**Issue by omkar1707** [xuxueli/xxl-job#766]
### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT

### Issue or Enhancement
H/W: 2 EC2 medium instances (1 with admin and executor, 1 with the only executor)
Created 1000 jobs with CONSITENT_HASHING
ExecutorRouteConsistentHash has not distributed the jobs correctly. 
On server 1 total no of jobs executed = 836
On server 1 total no of jobs executed = 164

I have added *[JumpConsistentHash](https://arxiv.org/abs/1406.2294)* instead of existing logic of *ExecutorRouteConsistentHash*
The result with that
On server 1 total no of jobs executed = 499
On server 1 total no of jobs executed = 501

I would like to add this new hashing technique in the codebase. Please suggest.

**Comment by xuxueli** [comment]
Thanks for the feedback, we are looking forward to your PR.

**Comment by xuxueli** [comment]
The balance of ExecutorRouteConsistentHash depends on the number (currently 5) of virtual nodes. You can increase this value, for example, increase it to 100, 200, etc.

```
com.xxl.job.admin.core.route.strategy.ExecutorRouteConsistentHash#VIRTUAL_NODE_NUM
```
