### ISSUE TITLE
1.7.2 自动注册失效

### ISSUE THREAD

**Issue by bobpan** [xuxueli/xxl-job#77]
使用1.7.2版本，Admin 部署在centos， Executor 部署在winserver

在admin设置自动注册，无法发现机器，手工注册可正常运行

同一个Executor在winserver的admin中可以自动注册

想了解这种情况可以在哪些方面检查？

**Comment by xuxueli** [comment]
你好，这种情况，通常是执行器请求admin进行心跳注册失败导致的。可以查看一下你的winserver是否ping的通centos上的admin啊。
还有一个可能是，配置的执行器地址有问题啊。
