### ISSUE TITLE
 xxl-rpc provider invokeService error.

### ISSUE THREAD

**Issue by xumingxiang** [xuxueli/xxl-job#770]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Actual behavior
12:41:51.987 logback [http-nio-8081-exec-1] ERROR c.x.r.r.p.XxlRpcProviderFactory - xxl-rpc provider invokeService error.
java.lang.IllegalArgumentException: java.lang.ClassCastException@3dcac1cc
### Steps to reproduce the behavior
使用  JACKSON 代替 HESSIAN 序列化时报上述异常

**Comment by xuxueli** [comment]
你好，Jackson序列化方式仅支持简单数据类型，如基础数据类型、List、Map等原生数据结构。

复杂类对象建议使用 hessian、protostuff、kryo 等几种原生提供的序列化方案。
