### ISSUE TITLE
xxl-job-core-1.9.1版本 出现 [com.xxl.job.core.util.ShardingUtil$ShardingVO@456eae6f]) but failed to remove it when the web application was stopped

### ISSUE THREAD

**Issue by lazyducker** [xuxueli/xxl-job#771]
项目中使用的xxl-job-core-1.9.1版本，
项目启动运行一段时间后出现如下异常：

04-Mar-2019 19:32:02.666 严重 [Thread-17] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [vehicle-dashboard] created a ThreadLocal with key of type [java.lang.InheritableThreadLocal] (value [java.lang.InheritableThreadLocal@4f8131cc]) and a value of type [com.xxl.job.core.util.ShardingUtil.ShardingVO] (value [com.xxl.job.core.util.ShardingUtil$ShardingVO@456eae6f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

看提示应该是 ThreadLocal 未关闭的问题，麻烦看下

**Comment by xuxueli** [comment]
你好，问题无法复现，看日志应该是Tomcat未正常销毁导致，确认通过Tomcat提供的shutdown脚本销毁容器。

**Comment by xuxueli** [comment]
建议升级最新Release版本。
