### ISSUE TITLE
Method threw 'com.xxl.rpc.util.XxlRpcException' exception. Cannot evaluate com.sun.proxy.$Proxy82.toString()

### ISSUE THREAD

**Issue by xumingxiang** [xuxueli/xxl-job#777]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
master分支 ，3月1日下载的
### Actual behavior
报如下错误
Method threw 'com.xxl.rpc.util.XxlRpcException' exception. Cannot evaluate com.sun.proxy.$Proxy82.toString()

### Steps to reproduce the behavior
跑到下面这段代码时报错
        // set-cache
        executorBiz = (ExecutorBiz) new XxlRpcReferenceBean(
                NetEnum.NETTY_HTTP,
                Serializer.SerializeEnum.HESSIAN.getSerializer(),
                CallType.SYNC,
                LoadBalance.ROUND,
                ExecutorBiz.class,
                null,
                5000,
                address,
                XxlJobAdminConfig.getAdminConfig().getAccessToken(),
                null,
                null).getObject();
### Other information

建议最好不要使用xxl-rpc，减少客户端的依赖。
建议使用http+json 这种通用的传输+序列化的方式，使用通用的方式也方便我们二次开发。比如我们除了java，有python、.Net、golang 等各语言的job，也都希望能一起调度，管理起来，所以我们有计划开发其他语言的客户端，但HESSIAN 这个库可能就java的库好用，像.Net 已经找不到可用的库

**Comment by ZoeShaw101** [comment]
Same here, was it solved?

**Comment by ZoeShaw101** [comment]
@xumingxiang 请问您解决了吗？我也遇到这个问题了

**Comment by chenyanxin** [comment]
请问您解决了吗？我也遇到这个问题了

**Comment by 9oo9le** [comment]
请问您解决了吗？我也遇到这个问题了

**Comment by chaiyanliang** [comment]
我也遇到同样的问题

**Comment by ZoeShaw101** [comment]
@xuxueli

**Comment by xuxueli** [comment]
这处报错 “com.sun.proxy.$Proxy82.toString() ” 是因为代理了非接口方法 ，只会在dubug调用toString时触发，正常运行不会有问题。

执行器多语言可以合并至：https://github.com/xuxueli/xxl-job/issues/824
