### ISSUE TITLE
spring boot版本提升2.1.1 后执行器启动报异常

### ISSUE THREAD

**Issue by shaojava** [xuxueli/xxl-job#778]
Please answer some questions before submitting your issue. Thanks!

### Expected behavior
spring boot版本提升2.1.1  spring 版本 5.1.3 执行器启动报异常信息
23:39:14.395 logback [nioEventLoopGroup-4-1] ERROR c.x.r.r.n.i.n.c.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse

断点查看
Method threw 'com.xxl.rpc.util.XxlRpcException' exception. Cannot evaluate com.sun.proxy.$Proxy53.toString()
rpc调用报错 
spring boot 1.5.19执行正常
### Other information

**Comment by xumingxiang** [comment]
同样问题，求解

**Comment by shaojava** [comment]
> 同样问题，求解
作者未回复 当前还是 2.0.1 版本 未升级 最新代码  2.0.1 升级 spring boot 2.1.1 未发现 问题

**Comment by shaojava** [comment]
@xumingxiang 最新代码 移出 xxl-rpc最新依赖 rpc使用 1.2.1 版本

**Comment by changcaichao** [comment]
我的也是这个问题，
@xumingxiang 请问该怎么解决？

**Comment by lirui9156** [comment]
同问

**Comment by likenamehaojie** [comment]
同问

**Comment by likenamehaojie** [comment]
已经解决，大家看下 xxl-rpc模块中我的一个提交目前还没有合并到主分支，急用的话可以复制提交代码，自己打包

**Comment by mxf1990** [comment]
> 已经解决，大家看下 xxl-rpc模块中我的一个提交目前还没有合并到主分支，急用的话可以复制提交代码，自己打包

谢谢，我试一下。

**Comment by xuxueli** [comment]
@likenamehaojie @mxf1990 @shaojava @xumingxiang @changcaichao @li-Coulson 

xxl-rpc 已经合并了 “@likenamehaojie” 提交的优化内容。xxl-job也已经升级相关依赖。大家可以重新pull master分支体验下。
