### ISSUE TITLE
可否把文檔部分搬遷進 GitHub 的 Wiki 功能

### ISSUE THREAD

**Issue by RedL0tus** [xuxueli/xxl-job#78]
看到了 OSC 那邊的文章過來觀摩了下 XD

README.md 應該更適合拿來做簡單的項目說明，具體的如何部署部分在 Wiki 下結構應該會更清晰，也方便閱讀，也方便別的熱心人編輯、優化。

只是個建議 XD

**Comment by xuxueli** [comment]
你好，非常感谢！
后面我会详细整理一下文档，从ReadMe中剥离出去啊。
ReadMe只展示简单项目说明信息啊
：）

**Comment by xuxueli** [comment]
你好，文档已经迁移至：http://www.xuxueli.com/xxl-job/
