### ISSUE TITLE
xxl-job调度机器失败

### ISSUE THREAD

**Issue by sohoku** [xuxueli/xxl-job#780]
Please answer some questions before submitting your issue. Thanks!
xxl-job admin中，调度中心无法调用到执行器，从源码中看到，IpUtil获取执行器时，获取到了docker的网关地址，正确的应该是_enp3s0_的ip，docker0需要过滤掉，请问是否有地方可以指定调度机器的地址？

### Which version of XXL-JOB do you using?
2.0.1
### Actual behavior
任务触发类型：失败重试触发
调度机器：172.18.0.1
执行器-注册方式：自动注册
执行器-地址列表：null
路由策略：轮询
阻塞处理策略：单机串行
任务超时时间：3
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<< 
调度失败：执行器地址为空

## ifconfig

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:7fff:fe00:8eae  prefixlen 64  scopeid 0x20<link>
        ether 02:42:7f:00:8e:ae  txqueuelen 0  (Ethernet)
        RX packets 290936  bytes 83010592 (79.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 295304  bytes 65134498 (62.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.5.236  netmask 255.255.255.0  broadcast 172.17.5.255
        inet6 fe80::b03e:5d87:cab0:86d1  prefixlen 64  scopeid 0x20<link>
        ether 60:a4:4c:62:b2:2c  txqueuelen 1000  (Ethernet)
        RX packets 3132426  bytes 2106142402 (1.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1579438  bytes 148993840 (142.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by pmzgit** [comment]
@sohoku 配置文件有指定执行器的ip配置： xxl.job.executor.ip，不知道你说的调度器地址指什么？但是如你所说，不配置的话，会自动获取本机ip，本机有docker网桥，所以我的情形跟你一样获取了docker bridge地址，我也想自动获取本地enp地址

**Comment by xuxueli** [comment]
你好，可以参考这个：https://github.com/xuxueli/xxl-job/issues/630
