### ISSUE TITLE
客户端会出现大量的 close_wait 链接没有释放解决

### ISSUE THREAD

**Issue by Pipppo** [xuxueli/xxl-job#781]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Actual behavior
当xxljob运行一段时间之后，客户端会出现大量的 close_wait 链接没有释放解决，相应的线程也被挂起

### Other information
客户端日志
2019-01-15 02:12:57.562 WARN com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(193) - Long polling failed, will retry in 2 seconds. appId: CPMS, clus
ter: default, namespaces: application, long polling url: http://10.203.96.58:20813/notifications/v2?cluster=default&appId=CPMS&ip=10.203.25.64&notifications=%5B%7B%22namespaceName%22%3A
%22application%22%2C%22notificationId%22%3A1316%7D%5D, **reason: Could not complete get operation [Cause: unable to create new native thread]**

户端使用的 @JobHandler 注解。管理端使用的是单机串行 Bean模式定时触发(大约每5分钟一次)。目前我们对客户端JVM启动参数进行配置，没有再发生类似问题。不确定修改参数的方式是否能完全解决问题。

JVM参数
java -Xmx1024m -Xms1024m -Xmn750m -Xss256k -XX:PermSize=32m -XX:MaxPermSize=32m

应用开发框架
spring boot

客户端应用服务器
4C， 8G， Red Hat Enterprise Linux Server release 5.7 (Tikanga)

**Comment by xuxueli** [comment]
你好，问题无法复现，可以进一步提供详细复现步骤或者完整日志。另外，建议升级最新版本。
