### ISSUE TITLE
执行器ip错误

### ISSUE THREAD

**Issue by yc6090340** [xuxueli/xxl-job#782]
执行器注册的ip地址是
![image](https://user-images.githubusercontent.com/30584411/54262254-b8dfae80-45a8-11e9-8389-b0aae72e79e6.png)
但是实际调度的ip地址不对
![image](https://user-images.githubusercontent.com/30584411/54262321-d876d700-45a8-11e9-902e-394d57157c6e.png)
希望大神帮忙看看  谢谢

**Comment by xuxueli** [comment]
你好，LRU策略存在问题，最新快照版本已经修复了这个问题，可以参考调整 “ExecutorRouteLRU”。或者等待即将发布的小版本，将会修复这个问题。
