### ISSUE TITLE
#功能建议# 取消 【开启关闭任务时】弹出的操作成功对话框

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#783]
墙裂建议 取消 【开启关闭任务时】弹出的操作成功对话框
每次 开启关闭任务成功后都要点1次确定对话框，这个交互毫无意义并且会打扰用户后续操作，完全可以用toast的方式提示

**Comment by xuxueli** [comment]
以优化推送至master分支，将会跟随下个版本一同发布。
