### ISSUE TITLE
求方案,调度php时多项目问题

### ISSUE THREAD

**Issue by LjxFaighting** [xuxueli/xxl-job#788]
我现在调度php项目都是在php服务器（如A机器）上启动一个java的执行器jar。然后在后台配置一个shell
这个shell来调度php!

那么问题来了，又来了一个 php项目(B项目)。我还得新弄一个java-agent在 B项目所在机器上按照之前的方式再次按照A的方式再来一次，
为了不建项目，我直接再java-agent上创建分支 用不同的app-Name来区分。这样虽然没有多项目了，多分支问题也出来了，维护很不方便！

有什么好的思路来解决这样的非 java客户端执行器的问题呢

###  欢迎大家吐槽我的问题  mailTo  375341227@qq.com  谢谢。

**Comment by xuxueli** [comment]
你好，非Java客户端可以通过 HttpJobHandler 来触发。
你可以为你的php程序开发一个http接口，通过参数路由到不同任务上。在xxl-job上你只需要简单配置任务的http链接和参数即可。

**Comment by Veitor** [comment]
@LjxFaighting 话说题主最后这问题是怎么处理的？分享一下方案呗，因为我也是用PHP开发的任务处理脚本。
我咋觉得xuxueli可能是不太了解php吧，我们期望的是直接执行php脚本命令，而不是通过fpm来执行（也就是说通过http请求来触发）。所以HttpJobHandler也不是很合适啊

**Comment by feng99** [comment]
> @LjxFaighting 话说题主最后这问题是怎么处理的？分享一下方案呗，因为我也是用PHP开发的任务处理脚本。
> 我咋觉得xuxueli可能是不太了解php吧，我们期望的是直接执行php脚本命令，而不是通过fpm来执行（也就是说通过http请求来触发）。所以HttpJobHandler也不是很合适啊

的确是这样  xxlJob对非java语言的支持   很弱.  
php也有cli模式的   
用HttpJobHandler 走的是fpm模式   有超时时间限制的   
有的离线任务  可能1分钟 也执行不完
