### ISSUE TITLE
用子任务方式来管理任务依赖问题

### ISSUE THREAD

**Issue by hongtaox** [xuxueli/xxl-job#79]
我也想采用这个项目做调度系统，但是有个问题没有解决，用子任务方式来管理任务依赖，新上线任务时要改被依赖的任务的配置，如果一个任务依赖多个任务，请问如何保证所有依赖都运行完了才运行这个任务，且只运行一次？

**Comment by xuxueli** [comment]
你好，感谢关注啊！
我理解你的意思是要实现类似会签的功能，也就是一个子任务有多个父任务，父任务都执行完了才会触发且触发一次子任务？这个暂时是不直接支持的啊，暂时可以通过业务参数自己逻辑判断。
目前支持的是一个父任务配置一个或多个子任务的模式，父任务每次成功执行办证只会触发一次子任务执行。

**Comment by JohnWey** [comment]
一个子任务依赖多个父任务太常见了，更何况父任务有可能并行，或者一部分并行，通过业务判断逻辑岂不是每个流程都需要重写？

**Comment by xuxueli** [comment]
这确实是一个问题，我们也在考虑这种场景。
目前XXL-JOB定位是轻量级分布式调度，流程任务如果要做的细致，目前的方案代价比较大，会让项目变得略微繁重。
大家有好的建议吗？

**Comment by kevin82008** [comment]
怎么感觉@JohnWey 有点把这个调度当工作流来用？
应该属于不同范畴的东西吧，感觉不需要考虑支持像工作流一样复杂的任务。
@xuxueli 现在一个任务完成后触发另外一个任务之前，如果可以注入个插件做点自己的事情（类似mybatis的那种），也许就可以了？有这种判断的自己写个插件，在插件里判断下当前自己依赖的父任务是不是已经执行过了之类的。

**Comment by xuxueli** [comment]
恩恩，明白了，这个方案很不错啊：）
一旦这样实现，流程任务里的一批任务需要共享一个uuid来校验父子任务状态。
不过有一些困难点需要克服，比如触发子任务时怎么传递这个uuid，目前触发子任务是通过quartz异步触发的，改为同步触发还待考虑。

**Comment by happy7023** [comment]
我们现在也是这样的场景，一个子任务需要依赖多个父任务，父任务并行跑。我的想法是这样的，在出发信息表里面增加两个字段，一个父任务IDS，一个父任务status,多个父任务都好隔开，每个父任务执行完之后执行回掉获取子任务时检查父任务状态，不满足执行条件就更新对应的父任务状态，知道全部父任务执行完后将全部父任务状态改为未执行。等待下一次触发，不知道有没有没有考虑到的坑。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/172
