### ISSUE TITLE
web container destroy and kill the job，这个异常是在什么情况下产生的呢？

### ISSUE THREAD

**Issue by xufanevel** [xuxueli/xxl-job#790]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Other information

**Comment by xuxueli** [comment]
应用容器销毁时触发。

**Comment by romeoblog** [comment]
我也是遇到这个问题，检查了容器的情况，结果容器并没有被摧毁，处于正常的状态，xxl-job-admin任务报了此类的问题，请问还有其他的问题引起这类情况吗？

**Comment by nestalee** [comment]
我也是遇到这样的问题。容器是没有被摧毁的，一部分的任务报这个错误，一部分没有报错。
