### ISSUE TITLE
任务调度后没有执行

### ISSUE THREAD

**Issue by xiedongbing** [xuxueli/xxl-job#796]
你们是否有遇到过
![image](https://user-images.githubusercontent.com/17705783/54811686-36e83780-4cc4-11e9-88fa-d273301ec850.png)
![image](https://user-images.githubusercontent.com/17705783/54811735-4d8e8e80-4cc4-11e9-937b-f936d9ae8200.png)

**Comment by xiedongbing** [comment]
任务在12:30:00已经开始调度，但是真正执行得到12:45:28开始执行，是否存在配置延迟
![image](https://user-images.githubusercontent.com/17705783/54811878-b2e27f80-4cc4-11e9-8b4f-6028a77617ed.png)

**Comment by guyi** [comment]
我也出现这样的问题，楼主有找到解决方法吗？

**Comment by xiedongbing** [comment]
> 我也出现这样的问题，楼主有找到解决方法吗？

无解

**Comment by xuxueli** [comment]
你好，从log看12:30:00已经进入任务线程，这段阻塞发生在业务JobHandler里。可以在业务JobHandler开始和末尾分别加一行日志，确认业务逻辑耗时。
