### ISSUE TITLE
请教：具体步骤操作

### ISSUE THREAD

**Issue by kamiaowudi** [xuxueli/xxl-job#8]
按照maven格式将源码导入IDE（文档以Eclipse为例），更新项目pom依赖，maven编译项目
问题：xxl-job-admin报错，maven update之后还是这样，我开始疑问是不是我导入Eclipse的方式不对，我是通过import-maven-existing Maven Projects 然后选中下载的源码文件夹，这样操作不对吗

**Comment by xuxueli** [comment]
你好，可以参考下这篇教程：http://jingyan.baidu.com/article/597a0643442a0d312b524331.html

**Comment by xuxueli** [comment]
可以到交流群反馈下，里面有一些大牛的哈。
