### ISSUE TITLE
为啥每天凌晨2点多CPU负载会变得很高

### ISSUE THREAD

**Issue by maxshucn** [xuxueli/xxl-job#80]
为啥每天凌晨2点多CPU负载会变得很高？而且一天比一天高。
一段时间后又下降了，因为在半夜，所以没有进一步查找问题。
![qq 20170612104907](https://user-images.githubusercontent.com/23044196/27017673-d347415a-4f5c-11e7-8848-b55f792be1e0.png)

**Comment by lirenzuo** [comment]
mark

**Comment by xuxueli** [comment]
你好，你们线上JOB是不是大量集中在凌晨2点这个时间点周围啊？

**Comment by maxshucn** [comment]
那倒没有，修改了下代码，重启了wildfly，继续观察几天再说。

**Comment by xuxueli** [comment]
奇怪了。不过，你可以dump分析一下内存数据，应该可以发现点问题啊。

**Comment by maxshucn** [comment]
没有问题了，估计是代码写的有问题，谢谢！
