### ISSUE TITLE
JobPersistenceException: The job (1.3) referenced by the trigger does not exist.

### ISSUE THREAD

**Issue by lvzheng0404** [xuxueli/xxl-job#801]
admin端日志报错JobPersistenceException: The job (1.3) referenced by the trigger does not exist.
是什么问题？

**Comment by lvzheng0404** [comment]
@xuxueli

**Comment by xuxueli** [comment]
你好，这是quartz底层库中存在脏数据导致。可以升级最新版本，或者删除该任务重新创建一次。
