### ISSUE TITLE
任务基于CRON执行时的时间误差问题

### ISSUE THREAD

**Issue by xpxu** [xuxueli/xxl-job#804]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

> 1.9.2

### Expected behavior

> cron设定在整点执行。任务应该在整点时执行。

### Actual behavior

> 根据日志记录，出现一次在59分59秒提前执行任务的情况。

### Steps to reproduce the behavior

> 偶现

### Other information

**Comment by xpxu** [comment]
@xuxueli

**Comment by xpxu** [comment]
调度页面情况：
```
16 | 2019-03-27 10:30:00 | 成功 | 查看 | 2019-03-27 10:30:03 | 成功 | 查看 | 执行日志

```

调度执行日志：

```
2019-03-27 10:29:59 [com.xxl.job.core.thread.JobThread#run]-[123]-[Thread-890] 
----------- xxl-job job execute start -----------
----------- Param:
2019-03-27 10:30:03 [com.xxl.job.core.thread.JobThread#run]-[128]-[Thread-890] 
----------- xxl-job job execute end(finish) -----------


```

**Comment by xuxueli** [comment]
你好，确认下DB和机器是否存在始终不一致情况。
