### ISSUE TITLE
cron新功能建议

### ISSUE THREAD

**Issue by CCweixiao** [xuxueli/xxl-job#806]
### 新功能建议

![image](https://user-images.githubusercontent.com/27730211/55370285-90562f00-552c-11e9-8e97-b6e289752ea7.png)

cron表达式解析（验证功能），新增一列，下次执行时间，这样是否有更好的用户体验

**Comment by JetBrainZP** [comment]
已实现
![image](https://user-images.githubusercontent.com/10757257/61214235-f2345080-a739-11e9-8c6e-cd0ebf66e521.png)

**Comment by JetBrainZP** [comment]
任务列表改造新增功能
1.应用的是否在线，如果在线显示在线机器数量
2.任务列表返回最近一次执行和调度结果
3.cron表达式显示下次触发的时间点
4.页面上显示时间，方便跟触发的时间进行对比
5.默认展示所有的任务列表
![image](https://user-images.githubusercontent.com/10757257/61214830-8eab2280-a73b-11e9-914c-2f247dc825c3.png)

**Comment by sundoya** [comment]
> 已实现
> ![image](https://user-images.githubusercontent.com/10757257/61214235-f2345080-a739-11e9-8c6e-cd0ebf66e521.png)

请问在哪个版本里呢? 我下载master 没有哦

**Comment by yuweiming2016** [comment]
估计是2.1.1版本才有吧

**Comment by xuxueli** [comment]
最新版本已经提供支持，可以体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
