### ISSUE TITLE
powershell中文乱码怎么解决？

### ISSUE THREAD

**Issue by dusansheng** [xuxueli/xxl-job#809]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
设置下环境编码即可，可以谷歌下 “powershell 中文乱码”

**Comment by wang-xiaowu** [comment]
解决方案，特此记录下：https://cloud.tencent.com/developer/article/1835811

但如该文章作者所说，会遇到一些中文软件显示不正常问题
