### ISSUE TITLE
/data/applogs/xxl-job/xxl-job-admin.log

### ISSUE THREAD

**Issue by Rollines** [xuxueli/xxl-job#814]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by Rollines** [comment]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - Failed to create parent directories for [/data/applogs/xxl-job/xxl-job-admin.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - openFile(/data/applogs/xxl-job/xxl-job-admin.log,true) call failed. java.io.FileNotFoundException: /data/applogs/xxl-job/xxl-job-admin.log (No such file or directory)

**Comment by wangzym** [comment]
这个没有关系的，没有找到对应的文件目录和文件，可以自己新建目录和文件

**Comment by gaoshengnan** [comment]
> ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - Failed to create parent directories for [/data/applogs/xxl-job/xxl-job-admin.log]
> ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - openFile(/data/applogs/xxl-job/xxl-job-admin.log,true) call failed. java.io.FileNotFoundException: /data/applogs/xxl-job/xxl-job-admin.log (No such file or directory)

如果你使用的是 2.0.2 版本，新建的目录和文件对应的路径，要对应好 xxl-job/xxl-job-admin/src/main/resource/logback.xml 里面的 <property name="log.path" value=""/> 的 value 值，比如我的 value 值是 xxl-job/xxl-job-admin/data/applogs/xxl-job/xxl-job-admin.log，我的 xxl-job-admin.log 文件就放在了那个目录下～

**Comment by Penough** [comment]
I pulled the docker image with version 2.2.0.This problem also happened.So how to solve the issue
