### ISSUE TITLE
关于新版的2.0.2问题

### ISSUE THREAD

**Issue by wangzym** [xuxueli/xxl-job#816]
1. 2.0.2的控制台pakage为jar包，对于部署的话不是很方便
2. 针对不同执行器的设置，由于jobhandler不是自动发现，导致可以配置为：A机器的handler配置B机器对应的执行器执行，而且B机器里面没有A机器的handler，会导致执行失败，当执行器数量和job数量比较多的时候是容易配置错的，希望回复

**Comment by xuxueli** [comment]
1、版本2.x后迁移为springboot版本，打包为jar，可以参考下springboot部署方式；
2、执行器是自动注册的，推荐任务绑定在执行器上，从执行器上获取机器地址信息。

**Comment by xuxueli** [comment]
你好，请升级最新Release版本：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2
