### ISSUE TITLE
默认情况下会出现重复调度

### ISSUE THREAD

**Issue by shenmimoon** [xuxueli/xxl-job#817]
默认acquireTriggersWithinLock=false的意义何在?有完整的测试过嘛?

**Comment by bugmeng** [comment]
请问谁来测，难道我们不是小白鼠？个人维护的项目都这样，习惯就好了，不行就自己改改

**Comment by guoyunfei123** [comment]
@shenmimoon 你用的哪个版本，我测的集群环境下2.0.1没发现重复执行啊，还是我的测试比较low，你是怎么测试的呢，麻烦贴我一下，谢谢

**Comment by xuxueli** [comment]
提issue之前，可以先参考下已有issue。迭代仅4年，多数问题前人都遇到、解决过；
https://github.com/xuxueli/xxl-job/issues/370
