### ISSUE TITLE
admin模块中XxlJobServiceImpl建议增加事物！！

### ISSUE THREAD

**Issue by z6165039** [xuxueli/xxl-job#818]
admin模块中XxlJobServiceImpl建议增加事物，毕竟存在多次操作数据库！

**Comment by XuMinCha** [comment]
每个方法里只有一个更新操作，剩下的都是查询，目前是没有问题

**Comment by z6165039** [comment]
remove不是有多个delete操作吗？
xxlJobInfoDao.delete(id);
			xxlJobLogDao.delete(id);
			xxlJobLogGlueDao.deleteByJobId(id);

**Comment by xuxueli** [comment]
事务要求不是很必要，不过可以自行添加。
