### ISSUE TITLE
同一个类中加入多个定时任务

### ISSUE THREAD

**Issue by XuMinCha** [xuxueli/xxl-job#819]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0
### Other information
需要在同一个类中实现多个定时任务的，可以先用https://github.com/XuMinCha/xxl-job.git

基于2.0版本新加功能：
>*  新加任务执行线程池，替换JobThread,减少线程创建销毁带来的开销
>*  新增注解@MultiplexJobHandler和@JobMethod，支持方法级别任务，类似spring的@scheduled
     使用方式见CompositeJobHandler
>*  新增job.log日志文件，记录日内执行的所有任务log

**Comment by Sdky** [comment]
请问会申请合并吗？

**Comment by XuMinCha** [comment]
我可以试一下merge request , 但个人觉得作者不一定会approve并且源码中的线程模型变了，需要花时间code review。如果有需要的，可以先用这个分支

**Comment by xuxueli** [comment]
你好，最新版本已经支持方法级别任务，可以升级体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
