### ISSUE TITLE
Nubia 道歉了吗

### ISSUE THREAD

**Issue by naivor** [xuxueli/xxl-job#82]
上次看到Nubia 拿这个项目去申请专利了，后续呢，有告他们吗，他们有道歉吗？

**Comment by xuxueli** [comment]
你好，这件事我们原则是 “就事论事，撤销专利”。目前正在国家知识产权局申诉撤销，暂时还没有得到答复。可以在开源中国跟进了解。
感谢关注啊！

**Comment by naivor** [comment]
把文章发到今日头条，让他们上头条，知乎和微博传播面好像不够广
