### ISSUE TITLE
执行器重启后，调度中心对应的执行器ip没有更改

### ISSUE THREAD

**Issue by yc6090340** [xuxueli/xxl-job#821]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1

执行器部署在容器，重启后，调度中心执行器的地址还是旧的ip。选择编辑执行器，什么也不改，直接点保存后，ip才会更新

**Comment by xuxueli** [comment]
你好，执行器自动注册存在短暂延时，稍等一会即可。
