### ISSUE TITLE
ExecutorRegistryThread 内存占用

### ISSUE THREAD

**Issue by peak-c** [xuxueli/xxl-job#823]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Expected behavior            
com.xxl.job.core.thread.ExecutorRegistryThread
54行移至while 外

### Actual behavior
**com.xxl.job.core.thread.ExecutorRegistryThread**
54行：我看此对象值应是不变，while 循环中不断new 对象
RegistryParam registryParam = new RegistryParam(RegistryConfig.RegistType.EXECUTOR.name(), appName, executorAddress);

### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
这处修改可行，可以提交一份PR一起参与进来啊。
