### ISSUE TITLE
通讯协议升级为Restful，方便扩展三方执行器。

### ISSUE THREAD

**Issue by youbeiwuhuan** [xuxueli/xxl-job#824]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2     及 2.0.2
### Expected behavior
得到执行器实现的标准，而不是去看源码，方便其他语言执行器的维护
### Actual behavior
实现其他语言执行器，如golang、c++
### Steps to reproduce the behavior
看源码中，计划自己写一个golang执行器的demo，最终实现golang执行器的库
### Other information
如果能提供个执行器实现的标准，我想xxl-job基本实现了跨语言和跨平台

**Comment by youbeiwuhuan** [comment]
也希望xxl-job的rpc通信协议能早点定型

**Comment by vipwangtian** [comment]
+1

**Comment by lkqm** [comment]
+1

**Comment by sniperking1234** [comment]
请问go版本的执行器开发怎么样了，我也有开发go执行器的需求，相互交流下

**Comment by huanggm** [comment]
顶一个，想要实现一个node执行器，类似于Java的bean模式

**Comment by xuxueli** [comment]
你好，感谢关注，这部分已经加入到TODO规划中。

XXL-JOB会逐渐演进成一种任务调度规范和协议。根据协议规范，第三方可以自行开发自己的执行器实现。

**Comment by jiladahe1997** [comment]
+1 期待node执行器

**Comment by xuxueli** [comment]
大家好，RESTful API 已经推送master分支，将会今日发布，大家可以 pull master 体验下。

```
RESTful API：调度中心与执行器提供语言无关的 RESTful API 服务，第三方任意语言可据此对接调度中心或者实现执行器。
```

**Comment by PGshen** [comment]
按照作者的实现Java执行器的思路，实现的golang版本的执行器，引入包即可使用，欢迎交流～
[https://github.com/PGshen/go-xxl-executor](https://github.com/PGshen/go-xxl-executor)

**Comment by dumyjob** [comment]
怎么用了?  java  jobHandler中使用api调用其他服务， 做到api异步调用，即使api调用时间很长
