### ISSUE TITLE
执行器挂起，注册中心轮询还是会选择挂起的执行器执行

### ISSUE THREAD

**Issue by maojqxaut** [xuxueli/xxl-job#825]
Please answer some questions before submitting your issue. Thanks!
@xuxueli 
两台执行器执行同一个任务，采用轮询策略。 当我停掉一台执行器，调度中心仍然会轮询两台，导致执行成功一次，失败一次。 注册中心不能定时探测执行器是否挂起，过滤掉吗？ 只能我手动在界面更新执行器时，才会探测更新掉执行器列表中挂起的。

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
两台执行器执行同一个任务，采用轮询策略。 当我停掉一台执行器，调度中心仍然会轮询两台，导致执行成功一次，失败一次。期望自动探测死掉的执行器，自动过滤掉
### Actual behavior
两台执行器执行同一个任务，采用轮询策略。 当我停掉一台执行器，调度中心仍然会轮询两台，导致执行成功一次，失败一次
### Steps to reproduce the behavior
启动两台执行器执行一个任务（轮询），停掉一台，后面执行仍然会选择轮询到这台挂起机器执行

**Comment by xuxueli** [comment]
你好，执行器注册和故障摘除存在短暂延时，稍等一会故障机器会自动下线。
