### ISSUE TITLE
XxlJobTrigger，为什么没有填充executor_address、executor_handler信息到xxl_job_qrtz_trigger_log中

### ISSUE THREAD

**Issue by kkkoko** [xuxueli/xxl-job#826]
![图片](https://user-images.githubusercontent.com/20294291/56272030-73287f80-612c-11e9-8a07-9d64e6417cb7.png)

#### 请问是什么情况，会导致XxlJobTrigger没有执行具体的update（存在信息都填充好的记录）。
---------

**Comment by xuxueli** [comment]
因为需要先生成任务ID，所以需要先生成一条空数据log记录；然后远程触发执行器，在获取触发结果之后，才会一并更新trigger log。

新版本info级别只会打印异常和敏感日志，可以调低日志级别查看详细日志，或者手动定制下。
