### ISSUE TITLE
规模支持疑惑

### ISSUE THREAD

**Issue by koala87** [xuxueli/xxl-job#828]
1、同时支持运行的任务数目测试过多少？我的项目需求，会有一些轻量任务，每个就是发些http请求，轮询状态。需要2W+个任务并发执行，是否OK
2、有API文档吗

**Comment by jaoyina** [comment]
可以cluster吧，不够就加服务器。

**Comment by xuxueli** [comment]
单机 5K，支持集群。不过海量任务，推荐实用 XXL-MQ 实现，支持海量消息。
