### ISSUE TITLE
能否增加前置依赖、流程图管理、任务优先级支持、作业目录树管理功能

### ISSUE THREAD

**Issue by ppqchina** [xuxueli/xxl-job#829]
最近因为项目需要切到了xxl-job平台，操作上手很快，也挺稳定。体验上如果能实现前置依赖、流程图管理、任务优先级支持、作业目录树管理等功能，或有替代解决方案，感觉会更好，不知道相应功能什么时候能增加~

**Comment by aliank516** [comment]
我也有类似的前置依赖需求

**Comment by atlas555** [comment]
这个需求很强烈，感谢

**Comment by coralW6** [comment]
我也有类似dags管理依赖的需求，感谢

**Comment by jic138168** [comment]
这个可以有

**Comment by dudiao** [comment]
我看这个需求已经纳入到了版本2.1.1中，是已经在开发了吗

**Comment by hhggbb** [comment]
前置依赖或者说父级依赖目前有哪些任务调度平台可以实现吗

**Comment by AtlantisWing** [comment]
> 前置依赖或者说父级依赖目前有哪些任务调度平台可以实现吗

很多公司自研的有不少，这个属于基础功能，不过都是重量级的和深度定制的

**Comment by xuxueli** [comment]
DAG流程任务，合并至：https://github.com/xuxueli/xxl-job/issues/172
