### ISSUE TITLE
xxl-job从2.0.1升级到2.0.2 是可以平滑升级吗？

### ISSUE THREAD

**Issue by zpa3x60** [xuxueli/xxl-job#832]
现在client用的是2.0.1版本，服务器上跑的是 2.0.2-SNAPSHOT，经常调用报 EOFException,如果服务端升级到2.0.2，客户端那边兼容吗？因为现在有很多项目在用这个了。

**Comment by xuxueli** [comment]
你好，2.0.2 升级通讯组件Jetty为Netty，需要两端共同升级才可以。
建议两端版本保持一致，且使用Release版本。
EOFException 问题由Jetty导致，升级可避免该问题。

**Comment by zpa3x60** [comment]
现在线上部署了8个应用，35个服务，有没有一个平滑升级的方案啊？
