### ISSUE TITLE
日志和统计能否升级

### ISSUE THREAD

**Issue by alaikis** [xuxueli/xxl-job#833]
Please answer some questions before submitting your issue. Thanks!
日志能够使用默认滚动和限大小，前一阵忘记修改，每天上T增加，不好管理，还有就是日志太多，首页默认统计页，基本打不开
### Other information

**Comment by xuxueli** [comment]
你好，日志分为调度中心表日志和执行器文件日志。
执行器文件日志，支持设置日志保存时间，过期日志自动清理。
调度中心表日志，日志界面提供了手动清理的功能，可以手动删除日志表数据。

**Comment by alaikis** [comment]
我是觉得如果能够设置保留时间会比较好，而且日志系统本来就支持滚动保存，无需要你再行开发，那个清理小的时候还好，上千万条的时候经常清理琐表
------------------
Alex Lai
              All from Small and Ended Big!                            Email:alex@laialex.com


                                                                        
                           
              
 


 




------------------ Original ------------------

**Comment by xuxueli** [comment]
已记录至TODO列表，将会排期优化。
