### ISSUE TITLE
迁移了数据库有一个状态字段是导不出来的

### ISSUE THREAD

**Issue by shinynz** [xuxueli/xxl-job#834]
状态字段是一个图片从数据库导出是乱码
![image](https://user-images.githubusercontent.com/15795798/56645580-8c8f7580-66b0-11e9-9a0f-2970742b4eaf.png)

**Comment by xuxueli** [comment]
你好，从截图看应该是quartz底层表数据异常导致。建议完整迁移数据库表数据，并且确定两端应用和DB的时钟保持一致。
