### ISSUE TITLE
配置执行器失败

### ISSUE THREAD

**Issue by zhangdechang** [xuxueli/xxl-job#84]
xxl.job.executor.appname=xxl-job-executor-example
xxl.job.executor.ip=
xxl.job.executor.port=9999
自动为空获取不到,手写也不好用.项目执行不了.显示失败,这个地方怎么配置,执行器能跑起来呢?admin项目启动,使用的springboot-example,其中修改springboot项目中serverport:8081-->9999,其他配置不变,项目启动执行器执行失败,报错调用地址为空(本地测试,电脑防火墙已关闭)
![image](https://user-images.githubusercontent.com/29501546/27252191-4e7b34fe-538a-11e7-848b-46458beb8694.png)

**Comment by xuxueli** [comment]
你好，你的调度中心admin的部署跟地址，需要和执行器配置文件中的回调地址保持一致哈，可以检查一下。

**Comment by Vickey-Wu** [comment]
你好，怎样才算一致呢？

我的配置如下：
admin：
```调度中心的地址和端口：172.20.0.15:8888```
executor:
```applicationcontext-xxl-job.xml：<property name="adminAddresses" value="192.168.0.2" />
xxl-job-executor.properties：xxl.job.admin.addresses=http://172.20.0.15:8888/xxl-job-admin```

前台执行结果：
![image](https://user-images.githubusercontent.com/24975216/40470974-bfb839b6-5f67-11e8-9b6c-c4313c56d6b4.png)
执行器管理页面OnLine 机器地址是为空的

**Comment by Vickey-Wu** [comment]
executor的日志是报register error，那跟这个错是一样的，一开始没看到。。。参考这个issue解决
[执行启动成功了，但是 注册失败了 #375]

**Comment by GiltyCrown** [comment]
同问这个问题

**Comment by danedang** [comment]
解决了吗

**Comment by KL-hub** [comment]
怎么解决，大佬们
