### ISSUE TITLE
咨询一个分片的问题

### ISSUE THREAD

**Issue by liyongsdh** [xuxueli/xxl-job#841]
雪里，你好：
      我想问一下job分片的问题，是这样的，我们现在有个需求，我们是按仓库id进行分片的，我们现在job是0=39,1=17,2=9,3=15,4=27这种分片，问题就是我们现在想把一部分job用xxl-job替换现有，所心想问一下，看看是否可以支持这种分片策略呢，谢谢！

**Comment by xuxueli** [comment]
你好，是支持的。启用分片任务后，任务触发的时候可以动态获取分片参数，处理进行相关业务逻辑。
