### ISSUE TITLE
问下升级到2.0.2的正确姿势

### ISSUE THREAD

**Issue by jaoyina** [xuxueli/xxl-job#843]
我之前跑的2.0.1没问题，最近我用docker重新安装了xxl-job-admin 2.0.2版本，安装完后无法打开页面，怎么可以查看镜像里面服务器的log啊，应用log里没看到任何错误。

**Comment by xuxueli** [comment]
你好，首先确认请求地址正常，端口号、路径是否包含应用名等。其次确认调度中心是否报错，默认日志路径在：/data/applogs/xxl-job/xxl-job-admin.log
