### ISSUE TITLE
执行器容器部署，动态ip，调度中心查看历史任务执行日志问题

### ISSUE THREAD

**Issue by tsfeng** [xuxueli/xxl-job#844]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
执行器 容器集群部署，ip动态获取，容器重启后，调度中心仍能查看之前已执行的任务的执行日志
### Actual behavior
调度中心 已经找不到之前的调度日志
### Other information

**Comment by tsfeng** [comment]
==Caused by: java.net.NoRouteToHostException: No route to host

**Comment by pkptzx** [comment]
1.别用ip表示.
2.如果用IP,在容器启动时指定.

**Comment by tsfeng** [comment]
> 1.别用ip表示.
> 2.如果用IP,在容器启动时固定ip,别动态ip.

会有原容器销毁，部署新容器的场景，ip不固定

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/630

**Comment by tsfeng** [comment]
这不是一样的问题，还合并一起。这个问题的原因是ip变化后，再根据原注册ip去找之前的执行日志文件，根本找不到呀？不知道生成日志文件的目的是什么。。。求指导
