### ISSUE TITLE
任务调度问题

### ISSUE THREAD

**Issue by liyongsdh** [xuxueli/xxl-job#847]
雪里，你好：
      我问一下，一个任务在一台执行器上可以同时被调度两次吗？

**Comment by webjoin** [comment]
这个问题太抽象了。请把场景描述下  最近也在研究可以一起分享下你的问题

**Comment by liyongsdh** [comment]
是这样的，比如说我有A、B、C、D四台服务器，我现在想做的事情就是一个作业同时调度8次，然后由xxl-job平均分到4台机器上执行，而不是我在程序里写逻辑云判断，这么说可以不？

**Comment by longxibendi** [comment]
你直接写8个 作业 不行吗？

**Comment by webjoin** [comment]
“我问一下，一个任务在一台执行器上可以同时被调度两次吗？”  那就配置两次调度 这样是否可以 ？

**Comment by xuxueli** [comment]
@liyongsdh 可以参上上面的建议，可以通过配置多个任务实现单执行器调度多次。
