### ISSUE TITLE
XxlRpcException: xxl-rpc, request timeout at:

### ISSUE THREAD

**Issue by zhengxingtao** [xuxueli/xxl-job#848]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Steps to reproduce the behavior
任务触发类型：手动触发
调度机器：192.168.3.98
执行器-注册方式：手动录入
执行器-地址列表：[192.168.3.148:9998]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<< 
触发调度：
address：192.168.3.148:9998
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1557048670489, request:XxlRpcRequest{requestId='73b5535f-b142-4415-81a1-21549a05769d', createMillisTime=1557048665471, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=2, executorHandler='iotDeviceJobHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=33, logDateTim=1557048665434, glueType='BEAN', glueSource='', glueUpdatetime=1557043370000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219) at com.sun.proxy.$Proxy81.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:77) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)
### Other information

**Comment by zhengxingtao** [comment]
版本换到1.9.2 一切正常了。。。

**Comment by yunbaozhou** [comment]
最新版本不行吗？

**Comment by zhengxingtao** [comment]
> 最新版本不行吗？

懒得调试了，目前使用的是1.9.2，个人感觉1.9.2 的war包部署比jar包部署方便一些

**Comment by xuxueli** [comment]
你好，问题无法复现。升级高版本，需要DB、调度中心与执行器版本保持一致，可以确认下。
