### ISSUE TITLE
建议增加调度日志开关

### ISSUE THREAD

**Issue by MingCore** [xuxueli/xxl-job#849]
每次调度时都会在磁盘里新建一个file文件，建议可以加个开关，由使用者自己选择是否新建该file文件

**Comment by w25193** [comment]
那个应该是log4j产生的日志，在配置里面可以自己修改吧

**Comment by tsfeng** [comment]
赞成，这个文件在执行器ip不固定的情况下，基本用不上了

**Comment by xuxueli** [comment]
@MingCore 你好，执行器提供了配置设置日志保存时间，过期日志会自动清理的。
