### ISSUE TITLE
有什么办法支持hive定时任务吗.

### ISSUE THREAD

**Issue by chyun** [xuxueli/xxl-job#851]
有什么办法支持hive定时任务吗.

**Comment by IAMTJW** [comment]
> 有什么办法支持hive定时任务吗.

底层还是依赖 quartz来实现定时任务的，目前quartz不支持 hive，实现起来可能就稍微麻烦点了https://github.com/quartz-scheduler/quartz/tree/quartz-2.2.x/distribution/src/main/assembly/root/docs/dbTables

**Comment by xuxueli** [comment]
@IAMTJW 你好，master迭代的最新版本已经移除了quartz依赖，下个版本会发布。

@chyun 你好，支持的hive任务的，可以在执行器测接入hive，在JobHandler里开发hive任务逻辑。
