### ISSUE TITLE
调度日志不能再IDEA控制台显示

### ISSUE THREAD

**Issue by lyings** [xuxueli/xxl-job#853]
当开发的时候，需要看到实时的执行错误日志，代码编辑器控制台，却不能显示出来。只能通过页面上的查看日志功能看执行日志。建议优化。

所有日志都是默认配置。

**Comment by tsfeng** [comment]
用Logger打印执行器日志

**Comment by xuxueli** [comment]
@lyings 你好，你指的应该是 ”XxlJobLogger.log“ 打印的日志看不到。这个组件打印的日志其实也是写入日志文件里的，可以debug "XxlJobLogger.log" 代码查看本地调度日志写入文件位置，通过该文件查看任务日志。

**Comment by noakcn** [comment]
com.xxl.job.core.log.XxlJobLogger
可以在该类的42行处，加入一个开关，检测是否是测试环境，将XxlJobLogger的日志也输出到控制台。
简单测试：不建议如此，可以设置开关来处理
![image](https://user-images.githubusercontent.com/17428111/78424975-bd8b6f00-76a3-11ea-87ec-b11fe7aa1c5e.png)
