### ISSUE TITLE
为什么properties 配置文件在idea中是中文，打包后乱码？

### ISSUE THREAD

**Issue by yunbaozhou** [xuxueli/xxl-job#856]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by yunbaozhou** [comment]
其实我想表达的问题是，调试时从数据库取出的中文数据和从配置文件中读取的中文数据，使用钉钉推送时，数据都正常。但是当打包后在测试服务器上，监控报警都是乱码，如下：
“������������ļ�ر����� 
 
 logId=224 
 title=��ƽ̨Jobִ���� 
 jobId=2 
 jobDesc=���Ե��� 
 TriggerMsg=���񴥷����ͣ��ֶ�����<br>���Ȼ�����106.14.240.65<br>ִ����-ע�᷽ʽ���Զ�ע��<br>ִ����-��ַ�б?null<br>·�ɲ��ԣ���һ��<br>��������ԣ�������<br>����ʱʱ�䣺0<br>ʧ�����Դ���0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>��������<<<<<<<<<<< </span><br>����ʧ�ܣ�ִ������ַΪ��<br><br> 
 HandleCode=null”
但是相同的数据发送到邮箱，在邮箱里却正常显示中文。 对此我也十分不解。

### **经过尝试，最终解决。方法就是： 在执行运行jar包命令前，指定编码方式。命令如：java -Dfile.encoding=utf-8 -jar xxl-job-admin-2.1.0-SNAPSHOT.jar**

**Comment by xuxueli** [comment]
应该是系统编码的问题，原生CentOS和Mac没有上述问题。

”-Dfile.encoding=utf-8 “  设置系统编码 utf-8 可以解决该问题。

**Comment by yunbaozhou** [comment]
嗯。感谢回复。
