### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by dengcq2** [xuxueli/xxl-job#861]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-core-2.0.0.jar

### Expected behavior
下载对应jar 打包本地仓库
### Actual behavior
打入本地仓库成功，但是启动应用任然报错，找不到依赖
### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。请提供完成日志。
