### ISSUE TITLE
关于“终止任务”的逻辑

### ISSUE THREAD

**Issue by xumingxiang** [xuxueli/xxl-job#862]
请教作者，“终止任务” 比较困惑，看了源代码，终止任务是通过 结束 指定 Jobid的jobThread 来实现的，是“JobId” 而不是“logId”，在整个stop的逻辑里没见到 logid，如果此时 队列中堆积了很多排队等待执行的 logId ，且不是全部被杀了？

**Comment by xuxueli** [comment]
你好，终止任务是终止单个执行器的整个任务，包括执行中和队列中的任务。

**Comment by ygmyth** [comment]
终止任务的逻辑主要是这两行代码：
```
oldJobThread.toStop(removeOldReason);
oldJobThread.interrupt();
```
对一个正在执行中的job来说，
```
while(!toStop）{
    triggerParam = triggerQueue.poll(3L, TimeUnit.SECONDS);
    executeResult = handler.execute(triggerParam.getExecutorParams());
}
```
只有这个job执行完，线程再次走到循环，判断toStop标志位，停止从队列拉取任务。
job里没有阻塞逻辑，interrupt也无效。
上面的终止逻辑对正在运行job无效，没法终止执行中的，只能终止队列中的任务。
