### ISSUE TITLE
用户管理界面的显示bug

### ISSUE THREAD

**Issue by zhhhc** [xuxueli/xxl-job#864]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
最新版本

### Expected behavior
![image](https://user-images.githubusercontent.com/20251916/57591335-677d7c80-7563-11e9-9787-a8d8dbde6213.png)
用户管理界面的角色Dropdown中，管理员和普通用户对应的key不正确，反了。导致查询结果也是反的。

### Actual behavior
用户管理查询结果不正确

### Other information

**Comment by linghushaoxia** [comment]
你好！
请问，你用的版本是2.0.2么？我运行之后，为什么看到不到管理页面？
![图片](https://user-images.githubusercontent.com/5456974/57908884-cb7da900-78b3-11e9-986d-b77fdaf903de.png)

**Comment by xuxueli** [comment]
你好，建议使用release版本，不要使用master快照分支。

上述功能尚未release，迭代中，不稳定。

**Comment by zhhhc** [comment]
好的，谢谢。
