### ISSUE TITLE
调度时间偶尔错误

### ISSUE THREAD

**Issue by dongzehong** [xuxueli/xxl-job#865]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Actual behavior
我有一个任务是每隔10秒执行一次，出现过几次调度时间错误，非常小概率的，遇到过几次了。
有遇到过同样问题的吗？什么原因？忽略或者如何解决呢？

配置从cron如下：
![image](https://user-images.githubusercontent.com/45219487/57591631-0060c780-7565-11e9-94bf-30c5959e5860.png)

调度时间错误的截图如下：
![image](https://user-images.githubusercontent.com/45219487/57591612-e2936280-7564-11e9-80eb-96a0f8989a4b.png)

### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。
怀疑是数据库链接的问题，写入日志延迟。可以在jobbean里加点日志确认下。

**Comment by dongzehong** [comment]
> 你好，问题无法复现。
> 怀疑是数据库链接的问题，写入日志延迟。可以在jobbean里加点日志确认下。

谢谢回复
不知道是不是我加了这行配置的关系：org.quartz.jobStore.acquireTriggersWithinLock: true
不过我印象中，没加这行配置之前，也出现过类似的错误。以下的截图是加了这行配置以后的，加配置之前的日志找不到了。
5月25号又复现了一次，把调度日志打出来了你看下。
首先admin的调度日志显示如下：
![image](https://user-images.githubusercontent.com/45219487/58399936-51f07280-808c-11e9-8a74-72b298839c88.png)
失败不用管，因为是“丢弃后续调度”导致的失败，根本原因还是调度时间错误引起的。
红色字体是应该调度的时间。可以看到，本来应该是07:22:50调度的，变成了07:23:08调度。之后就像匆忙地弥补之前没有做的调度一样，07:23:09，07:23:10分别又调度了1次。

代码里将调度时间打日志了，如下：
![image](https://user-images.githubusercontent.com/45219487/58400575-0c34a980-808e-11e9-9964-a113ac9c2ed4.png)
可以看出，前面说的那3条只打印了1条，因为只有07:23:08时间是调度成功的（其他两条因为丢弃后续调度，丢弃了）。

打日志的代码如下：
![image](https://user-images.githubusercontent.com/45219487/58400639-4736dd00-808e-11e9-8a18-d160e78c1af7.png)

这样的情况还有5月27号出现了1次，简单的截一下图如下：
![image](https://user-images.githubusercontent.com/45219487/58400809-b7ddf980-808e-11e9-9573-4bbc304534f8.png)
失败的原因也不用管，依然是丢弃后续调度。

总的来说，出现了调度时间偶尔出错的问题。

**Comment by dongzehong** [comment]
@xuxueli

**Comment by dongzehong** [comment]
查了一下增加配置之前的调度日志，都是重复调度的问题，应该和调度时间错误不是同一个问题。所以没法提供调度时间错误的日志了。截图如下：
![image](https://user-images.githubusercontent.com/45219487/58401880-8adf1600-8091-11e9-95ee-26d2f1da1962.png)

另外说一下重复调度的问题，重复调度出现的频率不多，但也不少，20天出现了6次吧，截图如下：
![image](https://user-images.githubusercontent.com/45219487/58401787-54a19680-8091-11e9-81d8-f814aba32ff7.png)

所以才加上了这个配置：org.quartz.jobStore.acquireTriggersWithinLock: true
从每天的调度次数来看，貌似是成功的。看这个调度统计图：
![image](https://user-images.githubusercontent.com/45219487/58402099-1d7fb500-8092-11e9-85f6-ea1ac041418f.png)
我的所有job每天总的调度次数应该是：15840；在增加这条配置之前，每天调度的次数是大于16000次；5月8号增加了这条配置以后，每天的次数都是：15841，正确的。不知道这样算不算解决了重复调度的问题呢？
![image](https://user-images.githubusercontent.com/45219487/58402371-bb737f80-8092-11e9-9c04-91cacb358f9e.png)
