### ISSUE TITLE
2.0.1版本的使用 偶尔会出现连续调度两次的情况

### ISSUE THREAD

**Issue by jzhahaha** [xuxueli/xxl-job#866]
使用的是2.0.1版本，最近发现有的任务出现连续调度两次的情况（原本的定时任务应该是每半小时调度一次）
![image](https://user-images.githubusercontent.com/40509002/57602740-93fcbd00-7592-11e9-81c7-a4c095559592.png)

**Comment by feiflyv** [comment]
这个问题我也遇到过

**Comment by jzhahaha** [comment]
> 这个问题我也遇到过

你出现的频率高么？？

**Comment by xuxueli** [comment]
你好，这是quartz重复调度的bug，前面issue有案例和解决方案，可以参考下。

**Comment by xuxueli** [comment]
可以参考这个ISSUE：https://github.com/xuxueli/xxl-job/issues/370
