### ISSUE TITLE
xxl-rpc-core依赖下载不下来

### ISSUE THREAD

**Issue by java-aodeng** [xuxueli/xxl-job#869]
xxl-job-core模块：

		
		<dependency>
			<groupId>com.xuxueli</groupId>
			<artifactId>xxl-rpc-core</artifactId>
			<version>${xxl-rpc.version}</version>
		</dependency>

**Comment by qhl100** [comment]
<dependency>
    <groupId>com.xuxueli</groupId>
    <artifactId>xxl-rpc-core</artifactId>
    <version>1.4.0</version>
</dependency>



	<xxl-rpc.version>1.4.0</xxl-rpc.version>

**Comment by java-aodeng** [comment]
@qhl100 嗯，这个版本下载下来了，谢谢

**Comment by xuxueli** [comment]
你好，建议使用release版本，不要使用master快照分支。
