### ISSUE TITLE
xxl-job admin tomcat后台报错，求解

### ISSUE THREAD

**Issue by shineforever** [xuxueli/xxl-job#87]
现在使用admin可以控制xxl-job springboot client执行任务，并且执行成功，但是tomcat的日志不停报错，报错如下：
![image](https://user-images.githubusercontent.com/1472799/27481567-ba450b3c-584f-11e7-97d5-bf2825cbe79f.png)
请问这个是什么回事？！

**Comment by xuxueli** [comment]
你好，这是执行器回调执行结果失败导致的。
可以检查一下执行器配置的回调地址啊。

**Comment by shineforever** [comment]
麻烦请问在什么地方查看啊？执行器的回调地址的不是代码默认的吗？

**Comment by xuxueli** [comment]
执行器回调地址的跟地址需要配置的，文档有介绍。
见配置文件 “xxl-job-executor.properties” 的配置项 “xxl.job.admin.addresses”，值为调度中心的部署跟地址；

**Comment by shineforever** [comment]
但是这个地方，我是配置过的的啊:
![image](https://user-images.githubusercontent.com/1472799/27507606-2f3c4cba-5905-11e7-8353-f62d412c9cb6.png)

目前我的情况是，执行器执行脚本成功与否，我在web管理端是看的见状态的，但是tomcat日志里面显示又不支持post请求。。。。
![image](https://user-images.githubusercontent.com/1472799/27507613-43eec96c-5905-11e7-890a-f0fd927571de.png)

PS:xxl-job-admin和xxl-job-executor-springboot-example我安装在一台服务器上；

**Comment by shineforever** [comment]
好的，解决了，主要是配置文件里面有一段url，所有我直接修改了ip，后面地址没有修改。。。
