### ISSUE TITLE
aws 公有云平台因只能映射一个端口导致执行器在集成到项目中调度中心无法调度的问题

### ISSUE THREAD

**Issue by hao373738397hao** [xuxueli/xxl-job#871]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0

### Expected behavior
执行器的发布端口与注册端口分离，解决docker发布端口与映射端口不同的问题

### Actual behavior
XxlJobExecutor类添加    private String registryIp; private int registryPort;
### Steps to reproduce the behavior
initRpcProvider(ip, port, registryIp, registryPort, appName, accessToken);
String address = IpUtil.getIpPort(registryIp, registryPort);
        Map<String, String> serviceRegistryParam = new HashMap<>();
        serviceRegistryParam.put("appName", appName);
        serviceRegistryParam.put("address", address);

### Other information
通过添加注册端口ip，解决docker部署执行器端口映射问题
[XxlJobExecutor.txt](https://github.com/xuxueli/xxl-job/files/3186333/XxlJobExecutor.txt)

**Comment by hao373738397hao** [comment]
这是解决方法，就是稍微动下源代码就ok了，测试有效

**Comment by xuxueli** [comment]
问题合并至：https://github.com/xuxueli/xxl-job/issues/708
