### ISSUE TITLE
能不能修改一下表结构

### ISSUE THREAD

**Issue by kangqiao-lu** [xuxueli/xxl-job#872]
作为一个DBA，看到您的表结构确实头疼，现在绝大多数使用MySQL innodb，但是您的表却跟常见的innodb建表规范差别很大，希望后面能改一下。
比如主键，innodb一般都使用增长的int来做
外键，一般在MySQL里都不让用的，业务本身来保证数据的映射对应关系

**Comment by xuxueli** [comment]
你好，这些都是quartz内置的表结构，它规定如此。

不过，新版本正在尝试自研触发组件，届时会废弃quartz内置表，重新梳理优化。

**Comment by xuxueli** [comment]
你好，master分支迭代的新版本（新版本处于快照阶段，下个版本会发布）对表结构已经做了优化，可以体验下。

**Comment by kangqiao-lu** [comment]
感谢感谢
