### ISSUE TITLE
XXL 必要性讨论

### ISSUE THREAD

**Issue by caryyu** [xuxueli/xxl-job#874]
目前 K8S 已经提供 CronJob 资源来管理定时任务了，对于 XXL-JOB 来说，采用此方案的必要性将会进一步减少，对于未来我比较看好 K8S 的定时任务系统，此项目想要进一步加大竞争力的话，应该需要做一些与 K8S 的 CronJob 融合的机制，否则随着时间的发展，这个项目终将会被淘汰。
 
以上是我个人的一些粗浅的见解，希望作者可以作为参考。

**Comment by xuxueli** [comment]
感谢反馈。
xxl-job与k8s侧重点不同，xxl-job重点在于功能性与易用性。
另外，从star数量与社区群规模增长情况来看，xxl-job社区非常活跃。

上文提到的建议后续迭代时会给足考虑，目前已经提供了docker镜像方便云服务使用。
