### ISSUE TITLE
ExecutorBiz触发的job在调度中心web页面无日志记录

### ISSUE THREAD

**Issue by Granstone** [xuxueli/xxl-job#876]
2.0.2版本，测试代码com.xxl.job.executor.ExecutorBizTest

job通过executorBiz.run(triggerParam)触发后，在web页面看不到调度日志，triggerParam里面设置了demoJobHandler任务，程序使用的本地执行器已经注册到调度中心了，是还需要通过日志接口把日志发到调度中心么？

本地控制台可以看到demoJobHandler已经成功执行并打印结果了。

**Comment by xuxueli** [comment]
你好，ExecutorBizTest 方式调度任务并不会记录到调度中心，这种方式仅用于任务开发阶段跑测试用例使用。
