### ISSUE TITLE
2.0.2 STOP状态的任务仍然会被调度执行

### ISSUE THREAD

**Issue by qsjia** [xuxueli/xxl-job#877]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2 Release

将admin从2.0.2 SNAPSHOT更新到2.0.2以后,  STOP状态的任务也会被调度执行

**Comment by zpa3x60** [comment]
我也遇到此问题了

**Comment by zpa3x60** [comment]
如果再把状态是STOP修改成run，会有两个job在执行，很危险的事情。

**Comment by ylls520** [comment]
STOP下会运行 RUN下调用多次

**Comment by ylls520** [comment]
按顺序清空 这3张表
xxl_job_qrtz_cron_triggers 
xxl_job_qrtz_triggers 
xxl_job_qrtz_job_details
然后重新启动任务就可以了
看了一下是GROUP由原来的组ID变成了 DEFAULT

**Comment by xuxueli** [comment]
你好，高版本表结构有调整，建议重新初始化表结构。上述问题应该是历史表数据冗余数据未清理导致。
