### ISSUE TITLE
建议将admin的springboot依赖版本升级为2.x，因为springboot2.x已经很普遍了

### ISSUE THREAD

**Issue by yuweiming2016** [xuxueli/xxl-job#883]
建议将admin的springboot依赖版本升级为2.x，因为springboot2.x已经很普遍了。

我试过将springboot版本改成2.0.5，结果freemarker一直报错，说I18nUtil找不到，奇怪，我又没动过freemarker，感觉是1.x与2.x版本差异导致的。

**Comment by wangzhengxi** [comment]
我升级到了2.0.1也是freemarker core报错，重新引入2.0.1的freemarker就可以了
