### ISSUE TITLE
 建议：content在作为父Job返回处理结果给子任务时特别有用，可以作为子Job的执行业务参数

### ISSUE THREAD

**Issue by crazythinking** [xuxueli/xxl-job#884]
问题：
执行器返回如下：return new ReturnT(obj);
最终记录执行日志如下：
----------- ReturnT:ReturnT [code=200, msg=null, content=null]

content被记录为null，实际应是obj.toString()的返回值才对。
问题在于com.xxl.job.core.thread.JobThread第162行【executeResult.setContent(null); // limit obj size】将执行结果的content设置为null，导致以上方法无法记录具体日志内容.

估计许大是考虑该字段保存到xxl_job_qrtz_trigger_log#handle_msg容易超长, 建议考虑在xxl_job_qrtz_trigger_log增加专门字段保存Content，这个content在作为父Job返回处理结果给子任务时特别有用，可以作为子Job的执行业务参数。

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/579
