### ISSUE TITLE
执行器的自动发现仅仅只能发现实例吗

### ISSUE THREAD

**Issue by celesky** [xuxueli/xxl-job#885]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
自动发现所有appName 下的执行器实例
### Actual behavior
只能手动先添加appName,才能自动发现这个appName下的执行器实例
### Other information

**Comment by xuxueli** [comment]
你好，目前需要先添加AppName后才能注册。可以防止无效AppName注册。
