### ISSUE TITLE
首页调度报表的日期排序问题

### ISSUE THREAD

**Issue by bubblepp1** [xuxueli/xxl-job#887]
Please answer some questions before submitting your issue. Thanks!
不知道是不是又是我们这使用的是TIDB的缘故，首页的调度报表折线图里的日期顺序是乱的，在mapper.xml中加上 order by triggerDay后恢复正常
### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT
### Expected behavior
首页调度报表能按日期排序
### Actual behavior
首页调度报表没能按日期排序
### Other information

**Comment by xuxueli** [comment]
你好，问题已修复并推送master分支，将会跟随下个版本一同发布。
