### ISSUE TITLE
任务调用失败没有告警提示

### ISSUE THREAD

**Issue by zpa3x60** [xuxueli/xxl-job#888]
Please answer some questions before submitting your issue. Thanks!
版本 2.0.2
### Which version of XXL-JOB do you using?
在调度时候，没有调用成功。业务没有收到调度请求，但也没有告警。

在调度日志上，在【调度结果】和【执行结果】项都是空。

### Other information

**Comment by xuxueli** [comment]
你好，这种情况应该是调度中心更新调度信息的时候发生异常，可以确认下有没有相关报错。
