### ISSUE TITLE
执行器一直执行，应用的内存一直往上升，没有释放，有这个问题吗

### ISSUE THREAD

**Issue by villins** [xuxueli/xxl-job#889]
Please answer some questions before submitting your issue. Thanks!

### 2.0.2

没有执行任务的，就没有内存增加

任务的只是简单的执行查询更新语句，没有特别的导致内存泄露的代码

**Comment by DonaldY** [comment]
有相同的问题，一直在执行。有些任务还不能停止。。。

**Comment by villins** [comment]
@DonaldY 是的，准备用其他方案做哥备案方案，不然得时不时去重启下系统

**Comment by xuxueli** [comment]
@villins 你好，执行器运行任务时会创建线程，因此会存在一定内存消耗。不过执行器线程做了上限控制，而且，任务线程如果空闲会提供线程自动销毁策略的。这个可以放行。

@DonaldY 你好，调度中心测任务不能停止，可能因为执行器回调结果丢失导致，其实任务线程已经停止，这个可以确认下。

**Comment by villins** [comment]
@xuxueli 「执行器运行任务时会创建线程，会存在一定的内存消耗」这一定的内存消耗可以给下具体的数值吗，这边有一个五秒的轮训任务，一直轮训的话，他的内存消耗一直攀升，达到容器的内存限制就会死掉，想请教下「执行器线程做了上限控制」这个具体消耗是多少，因为我这边预留两三百M容器内存，它还是会慢慢消耗掉

**Comment by villins** [comment]
@DonaldY 这个问题你那边怎么处理呢
