### ISSUE TITLE
xxl-job-admin 能否自我注册

### ISSUE THREAD

**Issue by GavinAlison** [xuxueli/xxl-job#891]
大咖， 请问一下，xxl-job能否实现自我注册，spring cloud中有一个功能是自我注册的，我现在的需求是，实现一个自我注册功能，只需要一个配置中心，一个执行器，他们是一体的， 实现最简单的功能。

**Comment by xuxueli** [comment]
你好，是支持的。底层注册表支持区分注册类型的，是调度中心还是执行器注册。
可以参考执行器注册逻辑，实现调度中心注册逻辑。
