### ISSUE TITLE
2.0.2  调度中心 localhost:9080/xxl-job-admin

### ISSUE THREAD

**Issue by wangzhengxi** [xuxueli/xxl-job#892]
版本为2.0.2 ，然后admin的端口改成9080，登录地址写成localhost:9080/xxl-job-admin，
进到任务管理，点击启动按钮，没任何反应。

写成ip:9080/xxl-job-admin并没有这种问题， 端口改成别的端口也没有这种问题。

**Comment by xuxueli** [comment]
你好，问题无法复现。请确认下页面js或者后端服务有没有报错，有的话可以提供下。
