### ISSUE TITLE
请问下串行执行多个任务,cron表达式怎么写?

### ISSUE THREAD

**Issue by Passer-Bye** [xuxueli/xxl-job#895]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
有没有串行触发式执行任务的demo
### Other information

task1,task2,task3
3个任务想依次执行,1执行完了触发2执行,然后触发3执行

这个需要怎么配置呢?   

如果写了cron表达式,好像就不是触发执行了吧.

只想指定task1在某个时间内执行,后面的触发执行就好了

**Comment by xuxueli** [comment]
你好，这种情况可以将子任务暂停掉，子任务即使配置cron暂停状态也不会执行的。

**Comment by xuyixun21** [comment]
意思是还没有触发执行模式的任务配置么
