### ISSUE TITLE
执行器注册必须要先在执行器管理里添加AppName 吗？不能xxl.job.executor.appname 指定自动添加吗？

### ISSUE THREAD

**Issue by cws1981** [xuxueli/xxl-job#897]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
执行器注册不需要手动添加appName
### Other information

**Comment by xuxueli** [comment]
你好，执行器AppName需要单独配置，AppName时任务注册的一基于，新版本也会基于它进行权限控制。
