### ISSUE TITLE
大咖，执行器的端口问题

### ISSUE THREAD

**Issue by GavinAlison** [xuxueli/xxl-job#898]
大咖，执行器应用程序注册时候，后台会利用netty启动一个执行器port=9999的server, 它与自身应用程序的端口有何区别，直接利用应用程序的端口不好吗？

**Comment by xuxueli** [comment]
内嵌Server支持Http/Tcp，RPC服务效率更高。
而且，一些应用并非Web项目，这个时候内嵌Server时唯一的选择。
