### ISSUE TITLE
咨询在K8s环境下日志的解决方案

### ISSUE THREAD

**Issue by duzhuo** [xuxueli/xxl-job#899]
Please answer some questions before submitting your issue. Thanks!
我们的执行器和调度器都打算部署在k8s平台上。我们公司k8s平台要求所有日志都必须输出到控制台(这也是k8s的标准做法)，后面再由ELK去抽取。所以执行器无法将通过XxlJobLogger.log()将日志输出到文件，调度器也无法查看任务的执行日志。请问有什么解决方案没有？

### Which version of XXL-JOB do you using?
v2.0.2

**Comment by simply-lu** [comment]
mark一下，同样遇到此问题

**Comment by duzhuo** [comment]
顶起来

**Comment by xuxueli** [comment]
有两种解决方案：
1、将核心日志写入任务结果的 ReturnT.msg 属性里，会记录到任务日志表的 “执行备注” 属性里。但是数据长度有限制。
2、可以将日志写入到k8s宿主机日志磁盘文件里，容器启停日志不会丢失。
3、自定定制Rolling Log存取逻辑，比如接入ES， “XxlJobLogger.log” 写入和查看均通过ES读写实现。

**Comment by jiangxiaoqiang** [comment]
> Please answer some questions before submitting your issue. Thanks!
> 我们的执行器和调度器都打算部署在k8s平台上。我们公司k8s平台要求所有日志都必须输出到控制台(这也是k8s的标准做法)，后面再由ELK去抽取。所以执行器无法将通过XxlJobLogger.log()将日志输出到文件，调度器也无法查看任务的执行日志。请问有什么解决方案没有？
> 
> ### Which version of XXL-JOB do you using?
> v2.0.2

你好，能分享下你们的k8s部署么，现在遇到无法注册执行器的问题。
