### ISSUE TITLE
分片过后，执行器挂掉的补救措施

### ISSUE THREAD

**Issue by wangzhengxi** [xuxueli/xxl-job#900]
假如我们现在总数据量有 3 万条数据，任务进行触发了，但是在线的执行器可能是 3 台。当触发的时候会分别向 0、1、2 进行发送请求。这时候 0 接受到的参数就是03，2 就是 13，最后一个是 23。这样根据参数对总数据进行分片，把最大数据拿到，进行处理。
假如其中一台执行器挂掉了，他的分片就改变了，我怎么保证数据都会被执行到呢。或者用什么补救措施呢。

**Comment by xuxueli** [comment]
你好，故障节点会自动摘除，故障分片也支持自动重试的，而且下次调度的时候会重新进行数据分片。

**Comment by SevenBlue2018** [comment]
@xuxueli 当调度中心成功发送触发请求到执行器端，但是执行器执行了一半挂了，那么当前这次调度就等于失败了？即使存在者其他节点也不能起到高可用的作用呀。是否应该提供一个机制来处理这种情况，当执行器执行任务的节点挂掉时，可以让调度中心重发一次请求让其他可用节点继续去执行。
