### ISSUE TITLE
服务器时间前后跳变导致定时任务在某一段时间内无法正常执行

### ISSUE THREAD

**Issue by IAMTJW** [xuxueli/xxl-job#902]
Please answer some questions before submitting your issue. Thanks!

### Expected behavior

看作者的更新日志，目前已经移除quartz，自己实现了JobScheduleHelper 来进行任务调度，目前在定时任务场景中遇到的服务器时间大范围的跳变，导致任务不再执行或者要经过很长时间才能正常执行，作者感觉可以在JobScheduleHelper中解决吗？之前quartz是无法解决这个问题的。

### Other information

**Comment by xuxueli** [comment]
目前常规触发组件都是通过计算任务下次触发事件的方式进行触发的，都是依赖时钟时间的。

不过你提到的时钟跳变问题应该可以解决的，可以在调度中心启动一个时钟监控线程，时钟跳变时重新计算以便任务下次触发事件即可。可以基于 v2.1.0 自行定制，会比较方便；
