### ISSUE TITLE
期望扩展任务状态 -  部分成功

### ISSUE THREAD

**Issue by qrqhuang** [xuxueli/xxl-job#905]
目前任务状态只有 
ReturnT.SUCCESS
ReturnT.FAIL

实际上一个任务中我们可能会批量处理一些订单。
会有比如某一单数据异常， 造成任务失败的情况。

实际上这种告警级别要比整个任务的FAIL要低的多。
所以期望扩展状态 ReturnT.PARTIAL  部分成功。

由handler自行计算业务订单成功率
成功率：
```
100% :  SUCCESS
(0%, 100%):  PARTIAL  
0%:  ERROR
```
PARTIAL 下的告警机制可与ERROR一致。

**Comment by xuxueli** [comment]
你好，这种情况可以自定定制扩展实现。
