### ISSUE TITLE
2.0.1和2.0.2版本用户管理左侧菜单栏找不到问题

### ISSUE THREAD

**Issue by uzdz** [xuxueli/xxl-job#907]
XXL-JOB version：2.0.1 ／ 2.0.2

![image](https://user-images.githubusercontent.com/28328355/58689168-dad31b00-83b8-11e9-88e1-22e053942925.png)

是隐藏了还是我打开的姿势不对？

**Comment by xuxueli** [comment]
你好，这是 v2.1.0 提供的功能，还在自测阶段，即将发布。
