### ISSUE TITLE
XXL-Job无法和SpringCloud Finchley版本集成

### ISSUE THREAD

**Issue by uzdz** [xuxueli/xxl-job#908]
目前项目用的是SpringBoot2.x + SpringCloud Finchley版本，但是目前XXL-Job最新版本为2.0.2使用的SpringBoot版本是1.5.20.RELEASE，导致无法将Feign集成到调度中心里面，如何处理呢？

**Comment by xuxueli** [comment]
你好，目前调度中心为兼容JDK1.7用户，springboot版本只能保持在1.5.x版本。
如果想要升级到springboot2.x，升级jdk编译版本即可。
