### ISSUE TITLE
Task能不能在执行器启动的时候自动新增/更新？不一定非得通过调度中心页面来添加嘛？（TASK多了好麻烦啊）

### ISSUE THREAD

**Issue by shenqianjin** [xuxueli/xxl-job#912]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by caixiaomao** [comment]
作者好像有在计划吧，多了确实稍微有点麻烦

**Comment by xuxueli** [comment]
你好，任务拥有非常多的属性，目前可以通过手动配置，或者通过API接口调用两种方式创建。

TODO里有任务自动注册的规划，但是实施起来有难度，比如覆盖优先级等问题，还在考虑。
