### ISSUE TITLE
多个任务前后依赖如何实现？

### ISSUE THREAD

**Issue by jwwam** [xuxueli/xxl-job#914]
前序任务执行完成后再执行后续任务，有多个依赖如何实现？
现在的解决办法是通过子任务，A执行完到子任务B，再到B的子任务C依次这样，但是感觉很麻烦，而且依赖之间的参数无法传递

**Comment by xy83918** [comment]
貌似不支持吧？ 我也有这个需求

**Comment by jwwam** [comment]
> 貌似不支持吧？ 我也有这个需求

只能通过子任务嵌套来实现，但是参数有依赖就很鸡肋了

**Comment by xy83918** [comment]
我的需求是子任务失败，主任务也要失败的逻辑怎么实现呢？

**Comment by jwwam** [comment]
> 我的需求是子任务失败，主任务也要失败的逻辑怎么实现呢？

貌似是不支持的，但是可以自己做，我看了下源码，思路就是在子任务的回调里将父任务的状态改一下就可以了，通过子任务的ID可以查到他的父任务，然后直接改状态。

**Comment by xy83918** [comment]
我们自己系统中，也有一个基于quartz 的调度系统想找个开源项目替代它，以减少代码量

**Comment by jwwam** [comment]
> 我们自己系统中，也有一个基于quartz 的调度系统想找个开源项目替代它，以减少代码量

可参考的很多，Azkaban很强大，唯品会的Saturn也不错，xxl应该是最简单的了，相应的功能也欠缺很多，主要是xxl没有工作流任务的概念，遇到这种需求就很鸡肋的感觉

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/447
