### ISSUE TITLE
job-admin 2.0.1 能直接升级到 2.0.2 吗？

### ISSUE THREAD

**Issue by ldcsaa** [xuxueli/xxl-job#918]
我尝试从 2.0.1 升级到 2.0.2。
发现数据库结构基本一致，只是 XXL_JOB_QRTZ_TRIGGER_LOG 表 多了 一个 alarm_status 字段。增加该字段后 job-admin 启动正常。

但运行时发现了一个非常严重的问题：
1、原有JOB会显示为STOP，但通过日志看一直都在执行并未停止。
2、如果点击“启动”，JOB状态会显示为RUNNING，但通过日志看是重复执行了2次。
![image](https://user-images.githubusercontent.com/5990337/58864428-43870400-86e7-11e9-8715-916514dd2388.png)

![image](https://user-images.githubusercontent.com/5990337/58864603-9fea2380-86e7-11e9-8c5d-6619392a0460.png)
![image](https://user-images.githubusercontent.com/5990337/58864708-d162ef00-86e7-11e9-807d-35d219bb5751.png)

**Comment by xuxueli** [comment]
你好，新版字段有少量调整，对比表结构调整即可。另外，除了扩展表数据，quartz原始表数据最好清除掉。

**Comment by qsjia** [comment]
> 你好，新版字段有少量调整，对比表结构调整即可。另外，除了扩展表数据，quartz原始表数据最好清除掉。

你好，这种不能兼容旧版本的升级，能否提供一份升级说明，哪些表或数据需要改动，毕竟对于已有旧数据的，直接删掉表再重建一次是不现实的。

**Comment by ldcsaa** [comment]
是的，求一份升级指南。
由于JOB太多，并且由不同团队创建的。很难重建！

**Comment by bugmeng** [comment]
2.1.0完全换了底层

**Comment by izhangzhen** [comment]
@xuxueli 您好，咨询一个问题，我从2.0.1升级到2.0.2启动admin发现后台任务一直在跑，而页面上显示任务都是stop状态，请问怎么才能停止这些任务，如果要删除某张表的数据，请问是哪几张表

**Comment by xuxueli** [comment]
@ldcsaa @qsjia @izhangzhen  
在 v2.1.0 之前的版本由于底层依赖quartz相关表，任务调度信息委托给quartz维护，因此可能存在不兼容问题。无法左侧平滑升级。

但是，在即将发布的 v2.1.0 之后已经改为自研调度组件，移除了quartz相关11张表，届时版本升级不会存在上述问题。

**Comment by izhangzhen** [comment]
嗯，谢谢您的回复，我已经手动把启动定时任务数据清除了，然后再手动启动一遍，问题已经解决了




在2019年06月08日 11:37，许雪里 写道：

@ldcsaa@qsjia@izhangzhen
在 v2.1.0 之前的版本由于底层依赖quartz相关表，任务调度信息委托给quartz维护，因此可能存在不兼容问题。无法左侧平滑升级。

但是，在即将发布的 v2.1.0 之后已经改为自研调度组件，移除了quartz相关11张表，届时版本升级不会存在上述问题。

**Comment by xuxueli** [comment]
👍

**Comment by xumeng** [comment]
> 嗯，谢谢您的回复，我已经手动把启动定时任务数据清除了，然后再手动启动一遍，问题已经解决了 在2019年06月08日 11:37，许雪里 写道： @ldcsaa@qsjia@izhangzhen 在 v2.1.0 之前的版本由于底层依赖quartz相关表，任务调度信息委托给quartz维护，因此可能存在不兼容问题。无法左侧平滑升级。 但是，在即将发布的 v2.1.0 之后已经改为自研调度组件，移除了quartz相关11张表，届时版本升级不会存在上述问题。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

请问具体是清除什么数据，能详细描述下步骤吗？我升级到2.0.2遇到同样的问题:(

**Comment by izhangzhen** [comment]
建议删除之前先把所有的表中数据备份。

试一下删除这三张表数据，任务启动的执行周期和设定会记录在这三张表中：
XXL_JOB_QRTZ_CRON_TRIGGERS
XXL_JOB_QRTZ_JOB_DETAILS
XXL_JOB_QRTZ_TRIGGERS

清空数据之前最好先记录下哪些任务是已启动需要跑的任务，避免遗忘。

**Comment by xumeng** [comment]
非常感谢你！ @izhangzhen
