### ISSUE TITLE
 tables_xxl_job.sql  created  tables  ERROR 

### ISSUE THREAD

**Issue by Koooooo-7** [xuxueli/xxl-job#919]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.0.2  (Latest release)

### Expected behavior
 Running the tables_xxl_job.sql  to  create tables correctly
### Actual behavior
ERROR  [ "Specified key was too long; max key length is 1000 bytes"]

### Steps to reproduce the behavior
Running the `tables_xxl_job.sql`  to  create tables
### Other information
When I added  `ENGINE=InnoDB DEFAULT CHARSET=utf8`  at the end of `XXL_JOB_QRTZ_*`tables ,
 everything was fine .

**Comment by xuxueli** [comment]
你好，感谢反馈！
在新版本表结构已经做了相关优化，将会跟随下个版本发布：https://github.com/xuxueli/xxl-job/blob/master/doc/db/tables_xxl_job.sql
