### ISSUE TITLE
使用测试例子报错，求帮助

### ISSUE THREAD

**Issue by wbq4585** [xuxueli/xxl-job#92]
java.lang.RuntimeException: RpcResponse byte[] is null

**Comment by xuxueli** [comment]
这个问题是执行器未正常响应导致，请检查一下执行器是否正常启动啊。

**Comment by wbq4585** [comment]
谢谢，可以启动了。原因是：执行器的端口，与tomcat的端口配置的相同

**Comment by sosojustdo** [comment]
@xuxueli , 我也遇到了类似的问题问题发生在xxl-job的日志中，调度日志里面显示每一次job触发状态是成功的，但是进入任务调度中心首页时都是执行错误的次数，没有一次执行成功。

**Comment by sosojustdo** [comment]
@wbq4585 我试过，我讲执行器端口配置和tomcat一样的话，xxl-job-admin会报上面的错误，但是我的执行器端口与tomcat不一样，xxl-job报了上面这个错误，不知道为啥？

**Comment by yuexingri** [comment]
@sosojustdo 应该是你的xxl.job.admin.addresses地址写的有点问题,例子里面是xxl.job.admin.addresses=http://127.0.0.1:9090/xxl-job,这样写的话,每次executor去提交心跳信息,都会返回空,实际上应该写为xxl.job.admin.addresses=http://127.0.0.1:9090,这样就能被正常检测到并正常注册到注册中心

**Comment by frixiang** [comment]
执行DemoJobHandler这个demo,为何总是提示调度失败：执行器地址为空
注：使用的jetty启动的项目
配置如下：
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://127.0.0.1:8889

### xxl-job executor address
xxl.job.executor.appname=xxl-job-executor-sample
xxl.job.executor.ip=
xxl.job.executor.port=9998

### xxl-job, access token
xxl.job.accessToken=

### xxl-job log path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### xxl-job log retention days
xxl.job.executor.logretentiondays=-1


执行器APPName:xxl-job-executor-sample,自动注册方式
任务：运行模式bean模式，jobHandler:demoJobHandler,cron：每30秒执行一次

**Comment by sosojustdo** [comment]
@yuexingri 后来发现是项目启动时候执行器出了问题

**Comment by wwm0104** [comment]
我也遇到了这个问题 但是 控制台输出 执行器已经启动成功java.lang.RuntimeException: RpcResponse byte[] is null
控制台启动结果：
![default](https://user-images.githubusercontent.com/29632074/41769863-37646362-7643-11e8-9746-0633eed07143.png)

相关配置：
![default](https://user-images.githubusercontent.com/29632074/41769875-3dcade20-7643-11e8-830c-c9614ae139a3.png)

spring boot 方式  @xuxueli

**Comment by smileqingyuan** [comment]
@wwm0104 你把xxl.job.admin.addresses=http://192.168.115.1:8080/xxl-job-admin改为xxl.job.admin.addresses=http://192.168.115.1:8080试一下。

**Comment by apa7** [comment]
我也遇到了这个问题, 

java.lang.NullPointerException
	at com.xxl.job.core.rpc.netcom.NetComServerFactory.invokeService(NetComServerFactory.java:65)
	at com.xxl.job.admin.controller.JobApiController.doInvoke(JobApiController.java:39)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:55)

**Comment by xuhj007** [comment]
> java.lang.RuntimeException：RpcResponse byte []为null
我也遇到了同样的问题

**Comment by xuxueli** [comment]
@whenas @xuhj007 @apa7 @wbq4585 应该是回调地址配置的问题，可以参考 @yuexingri 的方案。回调地址应该配成调度中心的跟地址。

**Comment by haoxiaoyong1014** [comment]
查看执行器和xxl-admin的版本是否一致

**Comment by erpengpeng** [comment]
https://blog.csdn.net/erpenggg/article/details/108506507

**Comment by erpengpeng** [comment]
[https://blog.csdn.net/erpenggg/article/details/108506507](https://blog.csdn.net/erpenggg/article/details/108506507) 亲测可用
