### ISSUE TITLE
DEADLOCK

### ISSUE THREAD

**Issue by shenmimoon** [xuxueli/xxl-job#921]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0

### Actual behavior
mysql deadlock
### Other information
DELETE FROM XXL_JOB_QRTZ_TRIGGER_REGISTRY   WHERE update_time   <   DATE_ADD(NOW(),INTERVAL -? SECOND)
no index to lock

**Comment by xuxueli** [comment]
你好，高版本注册表已经进行索引优化，可以pull master体验下。将会在线挨个版本发布：https://github.com/xuxueli/xxl-job/blob/master/doc/db/tables_xxl_job.sql
