### ISSUE TITLE
为什么xxjob启动的时候会默认占用7080端口，我已经指定对外提供的7085端口了

### ISSUE THREAD

**Issue by xuchi1994** [xuxueli/xxl-job#922]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuchi1994** [comment]
server.port=7085

**Comment by xuchi1994** [comment]
感谢

**Comment by xuxueli** [comment]
你好，调度中心只占用一个端口，即 “server.port” 对应的容器端口，保证该端口未被占用即可。

执行器会占用两个端口，分别时 “server.port” 容器端口和 “xxl.job.executor.port” 执行器服务端口，需要保证这两个端口均未被实用。
