### ISSUE TITLE
3个优化建议

### ISSUE THREAD

**Issue by farsunset** [xuxueli/xxl-job#923]
使用xxl-job近一年的感受，关于xxl-job-admin有几个小痒点可以进行优化

1 打印的日志过多，一天会生成很多日志文件，可以选择性的忽略一些无关紧要的日志，重要的日志可以不丢失信息的情况下尽量精简一些，因为这些日志不出问题基本不会去查看。

2 页面优化，建议默认登录进来打开任务管理页面，而不是运行报表，因为报表日志数据越来越多，导致报表页面打开非常缓慢，主要的是一般进来都是管理任务的，而非查看报表

3 页面优化，建议任务管理页面添加责任人查询条件，而且是下拉列表选择，选中直接发起查询，因为开发人员较多，任务有几百个的时候，按照名称，hander查询都很不方便 

 望采纳，谢谢

**Comment by xuxueli** [comment]
你好，感谢反馈！
1、日志过多问题：高版本日志级别已经优化，非核心日志调整为debug级别；
2、页面运行报表缓慢问题：高版本已经对日志表做了索引优化；后续计划单独新建报表数据库表，进一步优化报表缓慢问题；
3、任务责任人筛选问题：即将发布的 v2.1.0 已经提供了按照责任人筛选的选项，届时可以升级体验。

**Comment by vampniklaus** [comment]
借楼说一下，任务管理界面的5个按钮嫩不能不换行

**Comment by xuxueli** [comment]
@vampniklaus 你好，功能按钮比较多，一行放不下。有好的建议欢迎ISSUE或PR啊。
