### ISSUE TITLE
为何需要执行器的概念？

### ISSUE THREAD

**Issue by wllfengshu** [xuxueli/xxl-job#924]
xxl-job有执行器和调度器的概念，而且执行器必须引入xxl-job-core的依赖，导致他们之间耦合性太强。比如我仅仅是想周期性的使用xxl-job去做某事，并不想或者说根据不能处理这件事，那怎么办？

**Comment by xuxueli** [comment]
你好，执行器时为了将调度与执行解耦引入的，两个组件职责专一。xxl-job-core时执行器与调度中心交互的核心依赖是必须的。
