### ISSUE TITLE
请问带用户权限管理的版本是哪一个？

### ISSUE THREAD

**Issue by AaronLiang** [xuxueli/xxl-job#925]
请问带用户权限管理的版本是哪一个？我们用的是2.0.2 没有看到用户管理模块。谢谢

**Comment by xuxueli** [comment]
你好，用户管理将在版本 v2.1.0 提供，即将发布，即将期待。

**Comment by chenyongsuda** [comment]
@xuxueli 请问view代码的权限可以也进行控制么？

**Comment by chenyongsuda** [comment]
@xuxueli 急需用户管理功能.
