### ISSUE TITLE
没有执行器的时候报错

### ISSUE THREAD

**Issue by bigbenfather** [xuxueli/xxl-job#926]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

### Steps to reproduce the behavior
清空所有的执行器
### Other information
![image](https://user-images.githubusercontent.com/3414309/59179050-6a37b580-8b93-11e9-8a0a-b8a297d0b259.png)

**Comment by xuxueli** [comment]
你好，正常情况下系统至少保留一个执行器，上面问题应该是数据异常导致的。可以重新初始化一次数据库，或者手动创建一条执行器表记录。
