### ISSUE TITLE
任务已经执行成功并   return ReturnT.SUCCESS;  但后台日志一直显示在执行中

### ISSUE THREAD

**Issue by ranying01** [xuxueli/xxl-job#927]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
<xxl-job.version>1.9.1</xxl-job.version>
jdk 1.7 
spring boot 1.5.10.RELEASE

### Expected behavior
return ReturnT.SUCCESS;  任务执行结束

### Actual behavior
查阅日志发现定时任务一直在执行中

附配置文件：

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8189/xxl-job-admin
    executor:
      appName: pstn-api
      ip:
      port: 3357
      logPath: /mnt/logs/xxl-job/jobhandler
      logRetentionDays: -1
    accessToken:

大神有没有遇到过这种情况，跪求解决的办法。

**Comment by xuxueli** [comment]
你好，这是执行器没有成功回调日志结果导致的，可以排查小调度日志。

**Comment by ranying01** [comment]
好的，谢谢大神

在 2019-07-06 20:02:26，"许雪里" <notifications@github.com> 写道：


你好，这是执行器没有成功回调日志结果导致的，可以排查小调度日志。
