### ISSUE TITLE
HttpJobHandler 的优化建议

### ISSUE THREAD

**Issue by comyujie** [xuxueli/xxl-job#933]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
支持 HTTP 返回结果中的中文
### Actual behavior
返回结果中的中文是乱码
### Steps to reproduce the behavior
1. 创建 httpJobHandler 任务，调用返回结果中包含中文
2. 查看调度日志
3. 日志中的返回结果是乱码
### Other information
我本地做了如下修改，经测试可以避免此问题：
`bufferedReader = new BufferedReader(new InputStreamReader(connection.getInputStream()))`
改为：
`bufferedReader = new BufferedReader(new InputStreamReader(connection.getInputStream(), "UTF-8"))`

**Comment by vampniklaus** [comment]
兄弟，你直接PR多好

**Comment by comyujie** [comment]
我怕改坏了，影响别人:)

**Comment by xuxueli** [comment]
别怕，直接PR。

**Comment by xuxueli** [comment]
你好，该功能已经推送master分支，将会跟随下个分支一同发布。
