### ISSUE TITLE
MySQL5.7以下版本767字节长度问题

### ISSUE THREAD

**Issue by jingxiaohu** [xuxueli/xxl-job#937]
执行建表语句的时候，如果数据库编码类型使用utf8mb4 -- UTF-8 Unicode，就会报错显示
[Err] 1709 - Index column size too large. The maximum column size is 767 bytes.

**Comment by xuxueli** [comment]
你好，这种情况下可以升级mysql版本。

**Comment by jingxiaohu** [comment]
因为用的云数据库，版本不好升级，是否有兼容方案处理？


 
---原始邮件---
发件人: "许雪里"<notifications@github.com>
发送时间: 2019年6月20日(星期四) 晚上9:30
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"jingxiaohu"<251878350@qq.com>;
主题: Re: [xuxueli/xxl-job] MySQL5.7以下版本767字节长度问题 (#937)



你好，这种情况下可以升级mysql版本。
