### ISSUE TITLE
迁移xxl-job后服务cpu、内存飙升的问题

### ISSUE THREAD

**Issue by luobotiantang** [xuxueli/xxl-job#939]
问题详细描述：在没有迁移到xxl-job之前，我们采用的调度是springboot的组件cron注入的方式，迁移到xxl-job之后服务占用内存相对会增多

**Comment by xuxueli** [comment]
你好，执行器通讯以及任务线程会消耗一部分内存，不过这部分内存已经做了上限控制的。
cpu问题这个应该不是xxl-job导致，可以结合监控排查下部分任务逻辑是不是有问题。

**Comment by zuohengfeng** [comment]
迁移到xxl-job之后,内存一下飙升到5G,实际上只运行了四五个任务
