### ISSUE TITLE
优化任务日志

### ISSUE THREAD

**Issue by cwqsolo** [xuxueli/xxl-job#94]
在调度日志里面， 当显示全部任务的时候，有个字段能显示任务key，便于使用者区分。
另外，调度日志里面，最好加上一个查询条件 （执行情况： 失败/成功）

**Comment by xuxueli** [comment]
你好，感谢关注啊！
调度日志界面提到的两个建议很有意义，相关调整已经推送master，将会跟随下个版本发布。
在此感谢关注啊：）

**Comment by xuxueli** [comment]
功能已Release发布。
