### ISSUE TITLE
关于重复调度、调度时间错误，两个问题

### ISSUE THREAD

**Issue by dongzehong** [xuxueli/xxl-job#941]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
### Actual behavior
使用的是1.9.2版本，调度中心是集群部署了两台。

首先第一个重复调度的问题，作者已经统一放在这个issue回复：
[https://github.com/xuxueli/xxl-job/issues/370](https://github.com/xuxueli/xxl-job/issues/370)

我这边尝试在这个文件（quartz.properties）加了这个配置：
org.quartz.jobStore.acquireTriggersWithinLock: true
重复调度似乎是没有再出现了，关于重复调度的问题，能通过这个解决吗？有什么利弊呢？

以下是加配置之前，重复调度的情况：
![image](https://user-images.githubusercontent.com/45219487/59479559-13cabf80-8e90-11e9-9ff5-18714732dbaf.png)
我的所有job每天总的调度次数应该是：15840；在增加这条配置之前，每天调度的次数是超过16000次，说明有超过200次的重复调度；5月8号增加了这条配置以后，每天的次数都是：15841，正确的。不知道这样算不算解决了重复调度的问题呢？

加配置前的报表截图如下：
![image](https://user-images.githubusercontent.com/45219487/59479584-293fe980-8e90-11e9-9d02-f4a141030a70.png)

加配置后的报表截图如下：
![image](https://user-images.githubusercontent.com/45219487/59479646-5a201e80-8e90-11e9-900d-99a09b2444d1.png)

第二个调度时间错误的问题：
加了上述配置以后，发现了调度时间偶尔错误的问题，所以才把这两个问题放在一起。怀疑加配置前表现为重复调度，加配置后表现为非常小概率的调度时间错误。

我有一个任务是每隔10秒执行一次，出现非常小概率的执行时间错误。
cron：0/10 * * * * ? *
调度时间错误的截图如下：
![image](https://user-images.githubusercontent.com/45219487/59480195-483f7b00-8e92-11e9-9b82-ed7fa231c8c9.png)

按照作者意见，查看了日志，并且也复现了，截图如下：
![image](https://user-images.githubusercontent.com/45219487/59480234-6ad19400-8e92-11e9-936f-ec7deb5627f0.png)
红色字体是应该调度的时间。可以看到，本来应该是07:22:50调度的，变成了07:23:08调度。之后就像匆忙地弥补之前没有做的调度一样，07:23:09，07:23:10分别又调度了1次。

代码里将调度时间打日志了，如下：
![image](https://user-images.githubusercontent.com/45219487/59480284-a10f1380-8e92-11e9-9abc-98727f6edfd5.png)
可以看出，前面说的那3条只打印了1条，因为只有07:23:08时间是调度成功的（其他两条因为丢弃后续调度，丢弃了）。

这样的情况还有5月27号出现了1次，简单的截一下图如下：
![image](https://user-images.githubusercontent.com/45219487/59480311-b7b56a80-8e92-11e9-80a3-3a06afffd40a.png)

总的来说，出现了调度时间偶尔出错的问题。

我的理解是：重复调度、小概率调度时间错误这两个问题，都是由quartz本身的任务调度引起的，和XXL-JOB没有关系。就像作者说的重复调度可以通过结合 "单机路由策略（如：第一台、一致性哈希）" + "阻塞策略（如：单机串行、丢弃后续调度）" 来规避，最终避免任务重复执行；而小概率调度时间错误，可能因为一些数据库问题或者什么阻塞导致的？

目前我的解决方案是：加上org.quartz.jobStore.acquireTriggersWithinLock: true配置（因为重复调度还是比较频繁的），忽略非常小概率的调度时间错误问题（因为概率非常小；时间虽然错误但不会不执行）。

希望能解决两个问题：
1、org.quartz.jobStore.acquireTriggersWithinLock: true解决重复调度问题是否可行？有什么利弊？
2、调度时间非常小概率的错误，原因是什么？是由上述配置引起的吗？如何解决？

### Other information

**Comment by dongzehong** [comment]
@xuxueli 帮忙看下这个问题，谢谢！

**Comment by xuxueli** [comment]
你好，感谢反馈！
1、重复调度问题，按照上述加锁配置可以解决，但是加锁会影响性能；
2、调度小概率时间不准确，怀疑加锁导致，加锁后任quartz需要处理逻辑更多，调度密集时会导致调度阻塞，引起时间偏差。

新版本 v2.1.0 自研调度组件，移除了quartz依赖，会修复上述问题。

**Comment by dongzehong** [comment]
了解了，感谢回复！

**Comment by keepkeeping** [comment]
![image](https://user-images.githubusercontent.com/6418259/67646302-71a40380-f968-11e9-8e88-0ffe0c8f35b0.png)
明明是每天执行一次的，结果每分钟执行一次

**Comment by BruceAn1978** [comment]
> ![image](https://user-images.githubusercontent.com/6418259/67646302-71a40380-f968-11e9-8e88-0ffe0c8f35b0.png)
> 明明是每天执行一次的，结果每分钟执行一次

检查你的Cron表达式，不要使用图形化插件。然后再选择“下一次执行时间”看看是否正确。

**Comment by umena337** [comment]
mark
