### ISSUE TITLE
一个小建议~

### ISSUE THREAD

**Issue by liuq3323** [xuxueli/xxl-job#944]
在现有项目集成和调试的过程中，有的时候一个工程集群部署时，其中有的机器我可能并不想注册到远程的调度中心参与调度任务，希望可以添加一个配置参数true或者false来控制是否启用功能~
暂时我本地项目是修改了xxl-core的代码，在XxlJobExecutor类中新增了isRegister属性来判断~
再次感谢大大的开源项目~

**Comment by lhw209** [comment]
非常实用的idea。

**Comment by xuxueli** [comment]
你好，这个功能很早就支持了。
执行器 “xxl.job.admin.addresses” 配置项为空则关闭自动注册，文档中有说明。
