### ISSUE TITLE
新版本2.1.0io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9998

### ISSUE THREAD

**Issue by caijiaolong** [xuxueli/xxl-job#946]
本地启动完整版clone下来的包，修改数据库之后，启动springboot和admin
1手动执行，执行成功，无异常
2定时一分钟一次就会出现失败，如果设置重试次数，重试是成功的
触发调度：
address：192.168.1.107:9997
code：500
msg：com.xxl.rpc.util.XxlRpcException: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.107:9997 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) at com.sun.proxy.$Proxy132.run(Unknown Source) at com.zhukebao.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.zhukebao.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.zhukebao.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.zhukebao.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:76) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.107:9997 at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ... 1 more

**Comment by luobotiantang** [comment]
我也遇到过类似的问题
     业务场景：
          5秒执行一个调度，数据量大的时候这个调度5分钟左右执行完，业务量少的时候几秒就执行完，策略选择（终止后续调度策略）业务量大的时候会出现调度异常

**Comment by xuxueli** [comment]
你好，从上述日志来看 “ io.netty.channel.ConnectTimeoutException: connection timed out” 应该是网络或防火墙问题。

上述日志中 “com.zhukebao.xxx” 包路径并非官方版本，应该是自己调整过。

问题无法复现，请进一步提供细致复现步骤。

**Comment by zoucaifeng** [comment]
请问楼主您这个问题解决了吗？我也碰到了一样的问题，而且我的调度机器的ip是k8s中不存在的pod ip:
任务触发类型：Cron触发
调度机器：10.42.2.93
执行器-注册方式：自动注册
执行器-地址列表：[10.42.6.103:9999]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：10.42.6.103:9999
code：500
msg：com.xxl.rpc.util.XxlRpcException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.42.6.103:9999 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:250) at com.sun.proxy.$Proxy89.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at
