### ISSUE TITLE
xxl-job怎样设置能等上次执行完了,再去执行下一次调度（即使设置cron时间）

### ISSUE THREAD

**Issue by luobotiantang** [xuxueli/xxl-job#947]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by luobotiantang** [comment]
业务场景：
         例如：2秒去扫描数据表，扫到数据之后去执行业务代码，数据量小的时候1秒执行完没问题，但会出现数据量比较大的时候，此时需要5分钟左右才能执行完，但是此时还是每2秒调一次就会导致任务累积，虽然文档中有说明用“阻塞处理策略” 但是会导致后台出现调度失败的日志记录 @xuxueli 大佬这个有解决方案吗？

**Comment by ordinary** [comment]
可以自己做分布式锁，如果发现有人在占用，当前任务的调度，直接返回成功，2s执行的任务不用担心任务丢失的问题。

**Comment by xuxueli** [comment]
@luobotiantang 你好，可以启用阻塞策略，但是阻塞后提示失败。或者，可以考虑 @ordinary  提供的方案。
