### ISSUE TITLE
运行报表的日期分布图重合覆盖问题

### ISSUE THREAD

**Issue by shouqiong** [xuxueli/xxl-job#949]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
XXL-JOB 2.0.2
### Expected behavior
当日期分布图同时展示成功、失败、进行中这3个状态的分布时，应该可以清晰明了区分各种状态的分布情况。
### Actual behavior
当日期分布图同时展示成功、失败、进行中这3个状态的分布时，成功状态的分布图会覆盖其他两种状态的分布图。
### Steps to reproduce the behavior
打开运行报表菜单
![1560764849(1)](https://user-images.githubusercontent.com/51909217/59595905-4a6f3700-9129-11e9-9a8e-ae3e7bfb00dd.jpg)

**Comment by xuxueli** [comment]
你好，日期分布报表是 “堆叠折线图”，具体到每一天，三种状态的的数据会堆叠的方式展示在报表中，都会展示的，并不会覆盖。
上图中只看到成功状态日志，说明成功比例非常高，其他状态按照比例只展示一条细线，因此感觉覆盖了。其实没覆盖，只不过比例相差太大了。
