### ISSUE TITLE
spring boot版xxl-job，consul，spring cloud，informix 。。。

### ISSUE THREAD

**Issue by LiaoWenn** [xuxueli/xxl-job#95]
https://github.com/LiaoWenn/ccb-job

**Comment by xuxueli** [comment]
赞 ：）

**Comment by javaboy863** [comment]
ccb版啥也不说了，各种错误，启动都启动不起来

**Comment by LiaoWenn** [comment]
@javaboy863   小主，我错了~ 之前提交的版本很多的信息没有改动~ 所以阔能有点问题，重新提交了一版~  sorry~ 错了错了。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by xuxueli** [comment]
已合并至：https://github.com/xuxueli/xxl-job/issues/154
