### ISSUE TITLE
咨询新版调度任务问题

### ISSUE THREAD

**Issue by ordinary** [xuxueli/xxl-job#953]
看了下2.1的调度，把2.0中的quartz的调度改为timewheel方式
JobScheduleHelper 这个类中，先用select for  update获取最近10s钟需要调度的任务，然后把任务的下次执行的时间修改为下次执行时间，接着用timewheel执行最近10s钟的任务。
如果admin获取了最近10s的钟的任务，admin服务不稳定（如:admin机器死掉了），是否这批任务会都失败？

**Comment by xuxueli** [comment]
你好，v2.1.0 会预读5s内（预读间隔已调整）的任务到内存中，目的是为了任务的精确触发。
调度中心正常关闭时，调度组件会阻塞，直至内存中预读的任务处理完后才会关闭，可以避免任务丢失。
但是，如果直接kill -9直接杀死进程，可能会导致该节点预读的5s内的一部分调度丢失。因此，应该尽量避免kill -9和类似粗暴关闭方式。
