### ISSUE TITLE
如何控制并发度: 我们用xxl-job调度启动informatic任务,但informatic线程是10，最多同时跑10个任务，但调度器会同时调度很多任务，导致informatic宕机，怎么能控制调度器的并发度？ 

### ISSUE THREAD

**Issue by dusansheng** [xuxueli/xxl-job#955]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，可以启用执行器阻塞策略，限制单机单任务同一时刻只有一个在运行。
或者，可以自己添加一个分布式锁，限制 informatic 访问频率。
