### ISSUE TITLE
底层通讯方案优化后，admin 调度器和 executor 是否都要升级？

### ISSUE THREAD

**Issue by leiwangouc** [xuxueli/xxl-job#956]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by leiwangouc** [comment]
计划从 1.9.1 升级到 2.0.2， 调度器和执行器需要同时升级吗？ 只升级一个会不会有通信问题？

**Comment by xuxueli** [comment]
你好，建议同时升级。如果不仅仅，建议等待即将发布的 v2.1.0 发布后升级。
