### ISSUE TITLE
执行器重启不会重新执行进行中的任务

### ISSUE THREAD

**Issue by chen-ABC** [xuxueli/xxl-job#957]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 使用版本XXL-JOB  2.0.2
### Expected behavior
任务调度成功，但是在任务执行过程中，执行器宕机，重启执行器后，任务要重新被跑完。
### Actual behavior
任务调度成功，但是在任务执行过程中，执行器宕机(这里直接强制关闭进程进行模拟)，重启执行器后，任务还是一直进行中。
### Steps to reproduce the behavior
配置
![image](https://user-images.githubusercontent.com/30097790/59733767-992fe480-9281-11e9-9a18-b2d9358a80dd.png)
结果
![image](https://user-images.githubusercontent.com/30097790/59733861-e449f780-9281-11e9-8322-b861b1414339.png)
一直卡死在进行中
### Other information
我查询了以前的issue，看到1.9.2 在宕机有落盘结果，但是并没有看到这个期望的效果

**Comment by xuxueli** [comment]
你好，kill -9强制关闭并不会成功落盘。建议使用常规shutdown方式，这样容器销毁前会将失败结果落盘，重启后才会回调。
