### ISSUE TITLE
任务状态NONE的疑问？

### ISSUE THREAD

**Issue by 799983050** [xuxueli/xxl-job#958]
![图片](https://user-images.githubusercontent.com/45658355/59817373-2e021300-9352-11e9-9703-5c033e76ea3a.png)
我使用的版本是V1.9.2
任务的状态突然变成NONE了，请求是什么原因？

**Comment by xuxueli** [comment]
你好，该任务委托给quartz的底层数据被污染，建议删除后新建任务。
