### ISSUE TITLE
com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74

### ISSUE THREAD

**Issue by stonezpl** [xuxueli/xxl-job#960]
pom:
<dependency>
			<groupId>com.xuxueli</groupId>
			<artifactId>xxl-job-core</artifactId>
			<version>2.0.2</version>
</dependency>

springboot : 1.5.3

error: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74

**Comment by xuxueli** [comment]
你好，这是rpc服务端口被非法请求导致的，非法请求参数无法识别导致上述报错。确认下是否有类似请求。
