### ISSUE TITLE
关于XxlJobScheduler 和XxlJobAdminConfig

### ISSUE THREAD

**Issue by hyz1994121** [xuxueli/xxl-job#961]
Please answer some questions before submitting your issue. Thanks!

在这两个类上面我发现使用的是Configuration注解
但是在内部都没有声明bean,为何不使用component注解代替,使用Configuration很容易产生误解
而且在加载时会出现一些问题

### Which version of XXL-JOB do you using?
master分支
### Other information

**Comment by xuxueli** [comment]
你好，感谢反馈！
已经参考上述建议调整，并推送master分支。将会跟随下个版本发布。
