### ISSUE TITLE
2.02 版本初始化SQL异常，主键字段太大

### ISSUE THREAD

**Issue by Ecloss** [xuxueli/xxl-job#962]
下了最新的xxl-job来使用，但是在初始化的时候就发生了SQL初始化异常：
CREATE TABLE XXL_JOB_QRTZ_JOB_DETAILS 
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);

**报错：**
`
1709 - Index column size too large. The maximum column size is 767 bytes.
时间: 0.181s
`

**Comment by hylexus** [comment]
@Ecloss 新版本中的联合主键都改成了自增了，建议升级。https://github.com/xuxueli/xxl-job/blob/master/doc/db/tables_xxl_job.sql

**Comment by enguangzhang** [comment]
在创建每张表脚本最后加上ENGINE=InnoDB DEFAULT CHARSET=utf8就没问题了

**Comment by xuxueli** [comment]
@hylexus  +1，建议升级mysql版本，或者等待升级到即将发布的V2.1.0版本。
