### ISSUE TITLE
监控到 xxl-job 慢查询(commit)

### ISSUE THREAD

**Issue by hylexus** [xuxueli/xxl-job#963]
### Which version of XXL-JOB do you using?

- xxl-job-core:2.0.2
- xxl-rpc-core:1.4.0
- xxl-registry-client:1.0.2

### Actual behavior

![image](https://user-images.githubusercontent.com/13914832/59902924-1b5f0b00-9432-11e9-8703-fc908a96bf9f.png)

### Other information

云服务监控到有commit耗时比较长，请问这种问题在什么场景下会存在？

**Comment by xuxueli** [comment]
你好，可以确认下是不是日志表数据量太大，可以进行索引优化。
（高版本日志表已经做了优化，可以参考）
