### ISSUE TITLE
一个任务的执行需要满足at least once

### ISSUE THREAD

**Issue by apodemakeles** [xuxueli/xxl-job#964]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
当同一个AppName下有多个执行器实例存在的前提下：
一个正在执行任务的执行器宕机了（可能是更新服务引起的），在超时时间达到之后，满足重试次数条件的前提下，调度器将此任务发送给另外一个执行器。

即，一个任务需要在满足不超过某一个最大时间阈值的前提下，至少执行一次。

### Actual behavior
任务没得到重新调度，而是一直处在执行状态。

### Other information

**Comment by xuxueli** [comment]
你好，执行器失败回调后会自动触发失败重试，执行器服务按照正常停机流程回调不会丢失的，除非Kill-9，应该避免这种方式。
