### ISSUE TITLE
延时任务执行多次

### ISSUE THREAD

**Issue by 979163895** [xuxueli/xxl-job#966]
version：2.1
任务新建代码
![image](https://user-images.githubusercontent.com/24423846/59991153-ad585500-9678-11e9-8719-6f92a7d75a50.png)

xxl_job_info表 sql 语句
INSERT INTO `xxl-job`.`xxl_job_info` (`id`, `job_group`, `job_cron`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES ('10', '1', '00 47 11 24 06 ? 2019', '测试任务', '2019-06-24 11:46:00', '2019-06-24 11:46:00', 'xingwang.ma', NULL, 'FIRST', 'DemoJobHandler', '{\"id\":\"1\",\"time\":1561347960094}', 'SERIAL_EXECUTION', '0', '2', 'BEAN', 'BEAN', 'GLUE代码初始化', '2019-06-24 11:46:00', NULL, '1', '0', '1561348020000');
![image](https://user-images.githubusercontent.com/24423846/59991236-12ac4600-9679-11e9-8220-f125110154d4.png)

问题1：00 47 11 24 06 ? 2019
这种表达式能否支持 只执行一次？如果支持，我的新建任务是否有问题？
问题2：admin 项目新建 类似这种任务 【00 47 11 24 06 ? 2019】 等到执行的时候，在这块代码会报错
JobScheduleHelper 类 的 start 方法 79 行

![image](https://user-images.githubusercontent.com/24423846/59991361-ae3db680-9679-11e9-85db-b993a6bcb6a7.png)

**Comment by 979163895** [comment]
@xuxueli

**Comment by xuxueli** [comment]
你好，版本v2.1.0仍然在自测阶段尚未发布，需要等待Release后实用。

上述指定事件点仅执行一次的惹任务，建议实用延时MQ的方案来实现，推荐 XXL-MQ，支持自定义消费事件，重试次数等；

**Comment by 979163895** [comment]
好的，感谢回复
