### ISSUE TITLE
xxl-job在Spring cloud父子级项目中引用报错问题

### ISSUE THREAD

**Issue by 290046464long** [xuxueli/xxl-job#97]
大家好，我这里引用xxl-job启动的时候会报错，不知道怎么去解决，求助啊：java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@94e51e8: startup date [Mon Jul 03 18:17:07 CST 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@63376bed

**Comment by xuxueli** [comment]
你好，我们这里没有你的源码无法进一步定位问题。
你可以先对比文档上关于执行器的配置步骤，仔细检查配置项，确保配置无误；
如果还不能解决，可以加入交流群，一起讨论哈：）
