### ISSUE TITLE
非常紧急！调度时间是15秒一次，但是执行时间却不是15秒每次

### ISSUE THREAD

**Issue by yunbaozhou** [xuxueli/xxl-job#972]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。
推测应该是任务阻塞了，可以适当调大任务线程配置。

**Comment by yunbaozhou** [comment]
> 你好，问题无法复现。
> 推测应该是任务阻塞了，可以适当调大任务线程配置。

后来观察是队列任务大量阻塞导致的。任务线程配置在哪里？
