### ISSUE TITLE
JobScheduleHelper 调度一致性事务的死锁问题

### ISSUE THREAD

**Issue by ShakespeareFeng** [xuxueli/xxl-job#974]
JobScheduleHelper 在一致性事务开启之后，事务提交之前发生任何异常将会导致死锁，连接超时期间调度系统不可用。

以下是并发下的测试代码和错误截图：
![image](https://user-images.githubusercontent.com/16386529/60315199-2832b000-9998-11e9-9dc4-d7e7d426bf60.png)

![1561693099937](https://user-images.githubusercontent.com/16386529/60315464-3f25d200-9999-11e9-8c38-98bcf5e3edad.jpg)

建议作者在finally代码块中commit事务。

**Comment by xuxueli** [comment]
你好，感谢反馈！
上述问题已修复，并推送master分支。将会跟随下个版本一同发布。
