### ISSUE TITLE
XxlJobExecutor的initRpcProvider方法和xxlRpcProviderFactory属性需要设置为protected

### ISSUE THREAD

**Issue by flycloudOne** [xuxueli/xxl-job#977]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2

强烈建议：
为了方便扩展，需要将XxlJobExecutor的initRpcProvider方法和xxlRpcProviderFactory属性需要设置为protected

现在的目标是需要实现动态设置docker映射ip和端口

**Comment by xuxueli** [comment]
你好，问题合并至：https://github.com/xuxueli/xxl-job/issues/871
