### ISSUE TITLE
重复注册，一个执行器多个同样的注册地址

### ISSUE THREAD

**Issue by shatangege** [xuxueli/xxl-job#98]
soros-pay	支付交易系统	自动注册	118.178.120.222:9999
118.178.120.222:9999
编辑  删除
2	soros-order	订单系统	自动注册	118.178.120.222:9998
118.178.120.222:9998
118.178.120.222:9998
118.178.120.222:9998
编辑  删除
3	soros-risk	风控系统	自动注册	118.178.120.222:9997
118.178.120.222:9997
118.178.120.222:9997
编辑  删除
18	soros-batch	批处理系统	自动注册	118.178.120.222:10000
编辑

**Comment by xuxueli** [comment]
你好，类似问题在1.8.0的快照版本 （https://github.com/xuxueli/xxl-job/blob/master/xxl-job-admin/src/main/java/com/xxl/job/admin/core/thread/JobRegistryMonitorHelper.java#L49 ） 已经做了处理，对系统正常运营没有影响。
问题原因是：同一执行器机器，重复心跳注册时生成了多条记录。
但是，心跳注册通常是更新同一条已存在的记录，根据update行数判断是否存在旧注册记录，不存在才会新增，你们系统对心跳注册的SQL是否做了定制呢 （update没有正确返回行号） ？
