### ISSUE TITLE
调度日志建议调整为long

### ISSUE THREAD

**Issue by strongant** [xuxueli/xxl-job#981]
目前 xxl-job 中的调度日志类型为 int 类型,数据库表中 xxl_job_qrtz_trigger_log 的 id 字段为 int(11)，当增长最大值超过 2147483647 时，存在主键溢出的风险，导致调度任务不能正常调度，建议修改为 long 类型。   

![image](https://user-images.githubusercontent.com/7685936/60497220-fba7cc80-9ce6-11e9-9754-6234c6eead58.png)

**Comment by xuxueli** [comment]
感谢反馈和PR！
master分支已经合并了相关PR，将于下个版本一同发布。

**Comment by zymapp** [comment]
xxl_job_info表的id最好也改为bigint
