### ISSUE TITLE
maven编译xxl-job-admin时报错

### ISSUE THREAD

**Issue by emolwy** [xuxueli/xxl-job#985]
Downloading: https://repo.maven.apache.org/maven2/com/xuxueli/xxl-job-core/2.1.0/xxl-job-core-2.1.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/mybatis/mybatis-spring/1.3.2/mybatis-spring-1.3.2.jar (53 KB at 122.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-webmvc/4.3.24.RELEASE/spring-webmvc-4.3.24.RELEASE.jar (901 KB at 312.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/mybatis/mybatis/3.4.6/mybatis-3.4.6.jar (1588 KB at 2586.3 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.47/mysql-connector-java-5.1.47.jar (984 KB at 974.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:32.724s
[INFO] Finished at: Fri Jul 05 10:54:10 CST 2019
[INFO] Final Memory: 12M/120M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xxl-job-admin: Could not resolve dependencies for project com.xuxueli:xxl-job-admin:jar:2.1.0: Could not find artifact com.xuxueli:xxl-job-core:jar:2.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by toohandsome** [comment]
很明显2.1版本没发布.切换到2.0.2版本再编译吧

**Comment by xuxueli** [comment]
@toohandsome +1，新版V2.1.0 还在测试阶段，计划近期发布。
