### ISSUE TITLE
建议:重大版本更新时是否可以提供下升级方案

### ISSUE THREAD

**Issue by crwccqcl** [xuxueli/xxl-job#988]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1
### Other information
希望提供升级方案，当前只能通过更新日志去比对升级需要做的相关调整

**Comment by xuxueli** [comment]
你好，低版本升级 v2.1.0 核心操作步骤如下：

1、使用 v2.1.0  版本建表SQL，初始化一套新底层数据库；

2、针对新数据库中几张新表做数据迁移，相关表迁移方案如下：

- xxl_job_lock：新表，无需迁移；
- xxl_job_group：从历史表 “XXL_JOB_QRTZ_TRIGGER_GROUP” 中迁移，两张表结构一致；
- xxl_job_info：从 历史表 “XXL_JOB_QRTZ_TRIGGER_INFO” 中迁移，两张表结构基本一致，新表新增了个别字段，需要对比添加；
- xxl_job_log：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOG” 中迁移，两张表结构一致；
- xxl_job_logglue：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOGGLUE” 中迁移，两张表结构一致；
- xxl_job_registry：从历史表 “XXL_JOB_QRTZ_TRIGGER_REGISTRY” 中迁移，两张表结构一致；
- xxl_job_user：新表，无需迁移；

3、升级调度中心：编译部署新版调度中心即可；

4、升级执行器依赖：执行器项目升级执行器依赖版本，重新部署即可。

**Comment by gang0713** [comment]
是好是有角本能一键迁移

**Comment by kissss** [comment]
> 你好，低版本升级 v2.1.0 核心操作步骤如下：
> 
> 1、使用 v2.1.0 版本建表SQL，初始化一套新底层数据库；
> 
> 2、针对新数据库中几张新表做数据迁移，相关表迁移方案如下：
> 
> * xxl_job_lock：新表，无需迁移；
> * xxl_job_group：从历史表 “XXL_JOB_QRTZ_TRIGGER_GROUP” 中迁移，两张表结构一致；
> * xxl_job_info：从 历史表 “XXL_JOB_QRTZ_TRIGGER_INFO” 中迁移，两张表结构基本一致，新表新增了个别字段，需要对比添加；
> * xxl_job_log：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOG” 中迁移，两张表结构一致；
> * xxl_job_logglue：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOGGLUE” 中迁移，两张表结构一致；
> * xxl_job_registry：从历史表 “XXL_JOB_QRTZ_TRIGGER_REGISTRY” 中迁移，两张表结构一致；
> * xxl_job_user：新表，无需迁移；
> 
> 3、升级调度中心：编译部署新版调度中心即可；
> 
> 4、升级执行器依赖：执行器项目升级执行器依赖版本，重新部署即可。

有什么注意事项吗？执行器向下兼容吗

**Comment by Sdky** [comment]
> 你好，低版本升级 v2.1.0 核心操作步骤如下：
> 
> 1、使用 v2.1.0 版本建表SQL，初始化一套新底层数据库；
> 
> 2、针对新数据库中几张新表做数据迁移，相关表迁移方案如下：
> 
> * xxl_job_lock：新表，无需迁移；
> * xxl_job_group：从历史表 “XXL_JOB_QRTZ_TRIGGER_GROUP” 中迁移，两张表结构一致；
> * xxl_job_info：从 历史表 “XXL_JOB_QRTZ_TRIGGER_INFO” 中迁移，两张表结构基本一致，新表新增了个别字段，需要对比添加；
> * xxl_job_log：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOG” 中迁移，两张表结构一致；
> * xxl_job_logglue：从历史表 “XXL_JOB_QRTZ_TRIGGER_LOGGLUE” 中迁移，两张表结构一致；
> * xxl_job_registry：从历史表 “XXL_JOB_QRTZ_TRIGGER_REGISTRY” 中迁移，两张表结构一致；
> * xxl_job_user：新表，无需迁移；
> 
> 3、升级调度中心：编译部署新版调度中心即可；
> 
> 4、升级执行器依赖：执行器项目升级执行器依赖版本，重新部署即可。

你好，这些升级方案可以放到文档里说明一下吗？

**Comment by xuxueli** [comment]
@kissss  大版本不兼容，最好全量升级下。
@Sdky 你好，这份升级方案仅针对2.1.x 以下版本，暂时只存放在这里。

**Comment by yuweiming2016** [comment]
建议再增加一份oracle的脚本

**Comment by wkclz** [comment]
xxl_job_info 的执行状态，追代码发现看不懂从哪里获取的，以下方案，是从执行 log 里面来判断执行状态【三天内有产生 log 的，将置为执行状态】
`
INSERT INTO xxl_job_info (
	id,
	job_group,
	job_cron,
	job_desc,
	add_time,
	update_time,
	author,
	alarm_email,
	executor_route_strategy,
	executor_handler,
	executor_param,
	executor_block_strategy,
	executor_timeout,
	executor_fail_retry_count,
	glue_type,
	glue_source,
	glue_remark,
	glue_updatetime,
	child_jobid,
	trigger_status
)
SELECT
	ti.*,
	IF(tl.id IS NULL, 0, 1) trigger_status
FROM
	xxl_job_qrtz_trigger_info ti
	LEFT JOIN xxl_job_qrtz_trigger_log tl ON tl.job_id = ti.id AND tl.trigger_time > DATE_SUB(NOW(),INTERVAL 3 DAY)
GROUP BY
	ti.id;
`
祝升级成功！
