### ISSUE TITLE
清理日志操作报错（在选择全部的时候）见图 必现

### ISSUE THREAD

**Issue by sniperZj** [xuxueli/xxl-job#99]
![image](https://user-images.githubusercontent.com/16409106/27852694-b45cf3be-6192-11e7-942f-f2a99def097f.png)

**Comment by xuxueli** [comment]
你好，这个问题没有复现。可以把对应条件执行的最终SQL发我一份吗？

**Comment by untrueman** [comment]
https://www.oschina.net/question/2005806_244970
看一下你的是不是这种问题，跟项目没有关系吧，应该是数据库的问题。

**Comment by sniperZj** [comment]
@xuxueli 是选择 的  清理  所用日志数据吗

**Comment by sniperZj** [comment]
@xuxueli 我是 执行器-全部   任务-全部   清理类型-清理所用日志数据
