### ISSUE TITLE
2.1版本调度中心登录页的用户名和密码的默认值问题

### ISSUE THREAD

**Issue by crwccqcl** [xuxueli/xxl-job#990]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1
### Expected behavior
去掉用户名和密码的默认值
### Actual behavior
目前默认值为admin和123456
### Other information
![image](https://user-images.githubusercontent.com/22720746/60791549-7b75e100-a196-11e9-8800-13d25a61f715.png)

[](![image](https://user-images.githubusercontent.com/22720746/60791321-fa1e4e80-a195-11e9-9993-f3df56300242.png))

**Comment by xuxueli** [comment]
欢迎提个PR。
