### ISSUE TITLE
希望可以通过扫描@JobHandle注解的方式自动新增任务与执行器

### ISSUE THREAD

**Issue by hopepretty** [xuxueli/xxl-job#991]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
希望可以通过扫描@JobHandle注解的方式自动新增任务与执行器
### Actual behavior
1、只能通过web控制台新增任务，任务量大很麻烦，数据迁移有问题，而且当新开发人员检出新项目时，无法启动任务，还得重新导入任务与执行器数据
2、或者完善相关新增任务与执行器的API接口供外部调用，现API接口不满足需求
### Other information

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-job/issues/991
