### ISSUE TITLE
运行两天，文件数超出错误

### ISSUE THREAD

**Issue by lianghongming** [xuxueli/xxl-job#992]
java    16113 root *207u  a_inode                0,9         0      5528 [eventpoll]
java    16113 root *208r     FIFO                0,8       0t0 201118270 pipe
java    16113 root *209w     FIFO                0,8       0t0 201118270 pipe
java    16113 root *210u  a_inode                0,9         0      5528 [eventpoll]
java    16113 root *211r     FIFO                0,8       0t0 201118271 pipe
java    16113 root *212w     FIFO                0,8       0t0 201118271 pipe
java    16113 root *213u  a_inode                0,9         0      5528 [eventpoll]
java    16113 root *214r     FIFO                0,8       0t0 201118272 pipe
java    16113 root *215w     FIFO                0,8       0t0 201118272 pipe
java    16113 root *216u  a_inode                0,9         0      5528 [eventpoll]
java    16113 root *217r     FIFO                0,8       0t0 201118273 pipe
java    16113 root *218w     FIFO                0,8       0t0 201118273 pipe
java    16113 root *219u  a_inode                0,9         0      5528 [eventpoll]
java    16113 root *239u     IPv6          203681193       0t0       TCP hadoop3:58962->cs02:ndmp (ESTABLISHED)
[root@hadoop3 collector]# lsof -p 16113 | wc -l
60257

**Comment by lianghongming** [comment]
[2019-07-09 16:00:00] - [xxl-rpc, NettyHttpServer-serverHandlerPool-2014648014] [ INFO] com.xxl.job.core.executor.XxlJobExecutor:241 - >>>>>>>>>>> xxl-job regist JobThread success, jobId:2, handler:com.jiayi.platform.collector.jobhandler.DemoJobHandler@6afaf27
[2019-07-09 16:00:00] - [xxl-rpc, NettyHttpServer-serverHandlerPool-418057159] [ INFO] com.xxl.job.core.executor.XxlJobExecutor:241 - >>>>>>>>>>> xxl-job regist JobThread success, jobId:3, handler:com.jiayi.platform.collector.server.DeviceService@6c7f804c

运行上面之后，增加了200多个
[root@hadoop3 collector]# lsof -p 19676 | wc -l
378
[root@hadoop3 collector]# lsof -p 19676 | wc -l
595

**Comment by lianghongming** [comment]
文件句柄泄漏为pipe/eventpoll泄漏，这是Java NIO操作未正确关闭Selector所致，文件句柄泄漏发生在Native层面，由于Selector对象已被回收，所以在内存dump中也无法找到对应导致句柄泄漏的Selector对象

**Comment by lianghongming** [comment]
* 大批量的打开“anon_inode:[eventpoll]” 和 "pipe",  超过100个eventpoll, 通常情况下是开启了太多的HandlerThread/Looper/MessageQueue, 线程忘记关闭, 或者looper 没有释放

**Comment by xuxueli** [comment]
@lianghongming  你好，你部署的应该是v2.0.2 或更低版本。
问题 ”eventpoll“ 为低版本已知问题，可以单独升级xxl-rpc至1.4.1予以修复。或者升级xxl-job至最新版本。

**Comment by lianghongming** [comment]
<xxl-rpc.version>1.4.1</xxl-rpc.version>

**Comment by lianghongming** [comment]
解压的包如下：

已提取: BOOT-INF/lib/xxl-job-core-2.1.0.jar
已提取: BOOT-INF/lib/xxl-rpc-core-1.4.1.jar
已提取: BOOT-INF/lib/xxl-registry-client-1.0.2.jar





在 2019-07-09 19:49:10，"许雪里" <notifications@github.com> 写道：


@lianghongming 你好，你部署的应该是v2.0.2 或更低版本。
问题 ”eventpoll“ 为低版本已知问题，可以单独升级xxl-rpc至1.4.1予以修复。或者升级xxl-job至最新版本。
