### ISSUE TITLE
执行器回调失败

### ISSUE THREAD

**Issue by zenglanyuan** [xuxueli/xxl-job#993]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Other information

项目无法自动注册执行器
执行器log：
![image](https://user-images.githubusercontent.com/24584198/60880917-32498e00-a277-11e9-9f3c-df4b7e641e98.png)
 
手动注册后执行器回调失败：
调度中心log:
![image](https://user-images.githubusercontent.com/24584198/60881141-a1bf7d80-a277-11e9-8534-119030b19022.png)

这是什么原因？

**Comment by xuxueli** [comment]
你好，应该是回调地址配错，或者回调请求网络有问题，可以排查下。
