### ISSUE TITLE
调度结果为空，调度备注为空？

### ISSUE THREAD

**Issue by majinding** [xuxueli/xxl-job#997]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT
### Expected behavior
调度结果成功或失败，调度备注有描述
### Actual behavior
调度结果空，调度备注无
### Steps to reproduce the behavior
新建glue（java）类型的job
### Other information

![屏幕快照 2019-07-10 18 21 14](https://user-images.githubusercontent.com/2681645/60962670-5a9dbf00-a341-11e9-9f34-9a8258d16ebb.png)

**Comment by xuxueli** [comment]
你好，建议用release版本，快照版本不稳定。
